묵찌빠 게임 [STEP 1] Lingo, 우롱차
yagom-academy/ios-rock-paper-scissors pull request #107
Opened 2022-02-15 06:45 UTC by llingo

@Jager-yoo
안녕하세요 예거 😃
7_group의 Lingo, 우롱차 입니다. 잘 부탁드립니다!
묵찌빠 게임 STEP 1 PR 보냅니다.

## 고민한 점
1. checkGameResult 함수에서 기존에 출력 기능과 체크하는 기능이 같이 있어서 분리를 했습니다.
2. GameOptions 열거형 타입으로 지나치게 사용한 건 아닌지 고민이 되었습니다.
3. 열거형 타입을 사용하여 하드코딩을 최대한 줄일 수 있도록 고민했습니다.

## 해결한 점
1. checkGameResult 함수에서 기존에 출력 기능과 체크하는 기능이 같이 있어서 하나의 함수가 여러 기능을 하고 있다고 생각했습니다. showGameResult 함수를 새로 생성하여 게임 결과를 체크하는 부분과 출력하는 부분으로 분리했습니다.

## 조언 받고 싶은 부분
checkGameResult 에서 가위, 바위, 보에 대한 게임 결과를 판단하는 로직에서 아래의 로직이 너무 긴 것 같습니다. 어떻게 개선이 가능할 지 궁금합니다.

```swift
(playerInput == GameOptions.scissor.rawValue && computerInput == GameOptions.lock.rawValue) ||
(playerInput == GameOptions.lock.rawValue && computerInput == GameOptions.paper.rawValue) ||
(playerInput == GameOptions.paper.rawValue && computerInput == GameOptions.scissor.rawValue)
```

2022-02-15 20:56 UTC, Jager-yoo commented
안녕하세요! 우롱차 링고~ 반갑습니다. 😄 

빠르게 `스텝1` PR 완성해서 제출해주시면서도 `순서도`와 `리드미`까지 꼼꼼하게 작성하셨더라구요! 👏🏻

### ✅ 저도 리뷰를 꼼꼼하게 드리면서도, 난이도 조절을 위해 `추가 미션`도 적절하게 드렸습니다. 😆 

두 분이서 충분히 잘 해결하실 수 있을 거라 믿구요!
혹시나 도움이 필요하시면 코멘트나 디스코드 DM 으로 연락주시기 바랍니다. ㅎㅎㅎ

질문 주신 로직에 대한 의견은 `코멘트`에 붙여두었으니 거기서 확인해주시면 감사하겠습니다~! 👍🏻

2022-02-15 20:57 UTC, Jager-yoo requested changes

2022-02-15 20:57 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    else {
프로그램 내에서 `player`하고 `user` 라는 단어가 혼용해서 쓰이고 있지는 않은가요? 😓 
동일한 개념을 지칭하는 단어는 하나로 통일해서 사용하시는 게, 의도치 않은 혼동을 줄일 수 있는 방법입니다!

다른 개발자가 이 코드 처음 읽으면, `"플레이어 따로 있고 유저가 따로 있나?"` 라고 생각할 수도 있으니까요 ㅎㅎㅎ

2022-02-15 20:57 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let gameResult = checkGameResult(player: playerInput, computer: computerInput)
여기 computerInput 을 만들어낼 때, 숫자 1 ~ 3 중에서 하나를 뽑아내는데
범위가 하드코딩 되어있죠? ㅎㅎㅎ

### ⛑️ 난이도 있는 리팩토링 미션을 드려볼게요!

- GameOptions 열거형 타입의 `타입 연산 프로퍼티`를 만들어서 리팩토링해보세요!
가위, 바위, 보 셋 중에 하나를 랜덤하게 골라, Int 타입의 rawValue 를 반환하는 연산 프로퍼티입니다. 😄 
반환 타입을 `Int`로 할지, `Int?`로 할지는 여러분들 자유입니다~ 👍🏻

2022-02-15 20:57 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
- 이쪽 로직을 개선할 수 있는지 질문 주셨는데요! ㅎㅎㅎ
가위바위보 게임은 순방향으로 흐르면서도 `변칙`이 하나 존재하죠.

- 가위(1), 바위(2), 보(3) 가 있을 때
가위(1) < 바위(2)
바위(2) < 보(3)
이렇게 숫자가 크면 이길 때도 있지만
가위(1) > 보(3) 와 같은 경우엔 숫자가 작은 경우에 이기니까요 😄 
이 변칙 때문에 로직 구현이 조금 복잡해지더라구요.

- 링고와 우롱차가 만들어주신 로직도 좋은데요.
조금의 변형을 통해 `가독성`을 개선할 수 있을 것 같아요!

- 먼저, ~rawValue 사용하는 부분, 매번 쓰기엔 텍스트가 너무 길죠?
상수 선언을 통해 이 메서드 내부에서라도 짧은 단어로 대체해서 쓰면, 가독성이 크게 향상됩니다.
그리고 논리 연산자 `&&` 표현은 `컴마(,)`로 대체할 수 있어요! ㅎㅎ 

- 또한, draw 가 나오는 상황이 제일 직관적이니까 위로 올려준 점은 좋은데요!
순서 논리 상, `승리 조건`이 먼저 나오는 게 자연스러울 것 같아요.

```suggestion
    let scissor = GameOptions.scissor.rawValue
    let rock = GameOptions.rock.rawValue
    let paper = GameOptions.paper.rawValue
    
    if playerInput == computerInput {
        return .draw
    } else if playerInput == scissor, computerInput == paper ||
              playerInput == rock, computerInput == scissor ||
              playerInput == paper, computerInput == rock {
        return .win
    } else {
        return .lose
    }
```

2022-02-16 05:57 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
### 1. 네임스페이스는 왜 필요할까?
하드 코딩된 소스코드는 읽기 어렵고 유지보수 측면에서도 좋지 않다고 생각합니다.
네임스페이스를 사용하게 되면 읽기 쉬워지고 유지보수와 재사용성이 늘어나기 때문입니다.

### 2. 네임스페이스는 보통 열거형으로 만든다는데, 구체적으로 어떻게 만드는 게 좋을까?
열거형의 raw 타입과 case 사용해서 만들게 되면 `rawValue` 를 통해 접근해야하는 번거로움이 있는 것 같습니다. 
`static let` 타입 프로퍼티를 사용하여 구성하는 것이 좋을 것 같습니다.

`struct` 를 사용하게 되면 인스턴스화 되는 경우가 있기 때문에 보통 `enum` 을 사용하는 것 같습니다.

```swift
Enum Settings {
    static let menu = "가위(1), 바위(2), 보(3)! <종료 : 0> : "
    static let gameDidEnd = "게임 종료"
    ...
}

print(Settings.menu)
```

2022-02-16 06:00 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
`GameOptions` 를 손모양의 의미를 더 직관적으로 표현하기위해 `HandType` 이라는 열거형으로 네이밍을 변경하였습니다.
또한, `gameEnd`는 손모양과 관련이 없기 때문에 `Settings` 에 `exitCode`로 변경하였습니다.

2022-02-16 06:00 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
주어를 `player` 라고 생각하여 변경하였습니다.

2022-02-16 06:03 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
공식문서에는 위의 사진처럼 `else`를 올려쓰도록 되어있지만, StyleShare 가이드를 참고하다보니 그렇게 작성한 것 같습니다.
이번 리팩토링 과정에서 변경하였습니다.

[StyleShare Guide](https://github.com/StyleShare/swift-style-guide)
![스크린샷 2022-02-16 오후 3 03 12](https://user-images.githubusercontent.com/94151993/154205833-f91509eb-896f-4f2f-82a0-24ede354b50d.png)
.

2022-02-16 06:09 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return nil
`CaseIterable` 프로토콜을 채택하여 `allCases` 프로퍼티로 받은 열거형 배열에서 해당 입력이 존재하는 지를 `contains`를 사용하여 구현하였습니다. 만약, `손모양`이 추가되게 되고 중간에 `손모양`이 연속된 숫자가 아니면 범위로는 모든 값을 처리할 수 없다고 생각하여 다른 방식으로 구현하였습니다.

```swift
/// HandType
enum HandType: Int, CaseIterable {
    case scissor = 1
    case rock = 2
    case paper = 3
    
    static func randomHandType() -> Int? {
        return Self.allCases.randomElement()?.rawValue
    }
}

/// 구현 로직
(HandType.allCases.contains(playerGameOptionsInput) || playerIntInput == Settings.exitCode) else {
```

2022-02-16 06:11 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    else {
리팩토링 과정에서 `player` 로 통일했습니다.

2022-02-16 06:12 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
오! 좋습니다 링고~! 👍🏻 
아주 핵심 포인트만 딱 적어두셨네요~! 맞습니다.

두 분의 코드에서, 메시지 String 만 모아둔 열거형이라면 굳이 `rawValue` 까지 붙여서 쓸 필요가 없었던 것이죠 ㅎㅎㅎ
`static let` 으로 선언하면 `쩜(dot syntax)` 을 2번이 아니라, 1번만 사용하고 불러올 수 있어서, 가독성도 좋아지죠 😄

2022-02-16 06:14 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
깔끔하게 타입 분리하는 원칙! 좋아요 👍🏻 
손모양이란 의미의 `HandType`도 적절하네요 ㅎㅎ

2022-02-16 06:16 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
아~ 스타일쉐어 가이드를 참고하셨던 거군요!
저도 가끔 들여다보긴 했지만, guard문의 else절을 저렇게 분리해서 사용하시는 줄은 몰랐네요! 😅 
`코드의 근거`가 명확했군요. ㅎㅎㅎ

2022-02-16 06:20 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let gameResult = checkGameResult(player: playerInput, computer: computerInput)
```swift
enum HandType: Int, CaseIterable {
    case scissor = 1
    case rock = 2
    case paper = 3
    
    static var randomHandType(): Int? {
        return Self.allCases.randomElement()?.rawValue
    }
}
```

`randomHandType` 타입 연산 프로퍼티를 사용하여 `Int?`로 반환하도록 구현하였습니다.

2022-02-16 06:33 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
`승리조건`이 `패배조건`보다 먼저 오도록 변경하였고 승리를 비교하는 로직을 짧게 수식화했습니다.

```swift
func checkGameResult(player playerInput: Int, computer computerInput: Int) -> GameResult {
    let computerLoseCondition = (computerInput % 3) + 1

    if playerInput == computerLoseCondition {
        return GameResult.playerWin
    } else if playerInput == computerInput {
        return GameResult.playerDraw
    } else {
        return GameResult.playerLose
    }
}
```

2022-02-16 09:10 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let gameResult = checkGameResult(player: playerInput, computer: computerInput)
네 좋습니다! 👍🏻 

근데 열거형 타입 이름에 이미 `HandType` 이라는 단어가 있기 때문에
연산 프로퍼티를 사용할 때 HandType.randomHandType -> 이렇게 하면 동일한 단어 반복되죠 ㅎㅎㅎ

연산 프로퍼티 이름은 단순히 `random` 또는 `randomPick` 정도로 나눠도 좋겠습니다.
그리고 연산 프로퍼티라서, 메서드 처럼 `괄호()`는 불필요합니다!

2022-02-16 11:22 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return nil
좋습니다! 👍🏻 
`CaseIterable` 프로토콜을 사용하셨군요~! 잘 찾으셨습니다. ㅎㅎㅎ

처음에는 `타입 메서드`로 구현하셨다가, 후에 `타입 연산 프로퍼티`로 변경하셨었나보군요? 😄 
파라미터 없이, 리턴값만 존재하는 메서드는 -> `연산 프로퍼티`로 변경할 수 있습니다.
그게 가독성도 좋구요~ 잘하셨습니다! 💯

2022-02-16 11:34 UTC, Jager-yoo requested changes

2022-02-16 11:34 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return Self.allCases.randomElement()?.rawValue
열거형 타입 이름에 이미 `HandType` 단어가 들어가있습니다.
그래서 연산 프로퍼티 네이밍에도 들어가면 중복입니다! 😄 

간단하게 `random` 으로 바꿔보거나, `randomPick` 같은 건 어떨까요~?

```suggestion
    static var random: Int? {
        return Self.allCases.randomElement()?.rawValue
```

2022-02-16 11:34 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
단 하나의 프로퍼티만 가지고 있더라도, 꼼꼼하게 `타입 분리` 해주시는 점 훌륭합니다! 😄

2022-02-16 11:34 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return
연산 프로퍼티 리턴값이 `Int?` 라서 guard문으로 바인딩해주셨는데요!
여기서 `nil`이 나와 else절로 빠질 가능성은 0 에 가깝지만, 그럼에도 꼼꼼하게 `error` 메시지 만들어서 대응해주신 점 정말 좋습니다!! 👍🏻👍🏻👍🏻

2022-02-16 11:34 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
변환할 때 마다 새로운 `상수`로 이름지어 받아주는 점, 꼼꼼하고 좋습니다.

다만, 하나의 guard문 안에 너무 많은 일들이 모여있으면, 오히려 가독성이 떨어질 수 있습니다.
특히 `옵셔널 바인딩`을 하는 guard문과, 조건문 역할을 하는 guard문은 분리해주는 게 좋습니다. 😄 

```suggestion
    guard let playerInput = readLine(),
          let playerIntInput = Int(playerInput),
          let playerGameOptionsInput = HandType(rawValue: playerIntInput) else {
        return nil
    }
    
    guard HandType.allCases.contains(playerGameOptionsInput) || playerIntInput == Settings.exitCode else {
        return nil
    }
```

2022-02-16 11:34 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
오~ 뭔가 새로운 로직으로 코드가 간결해졌군요!
해당 로직이 `스텝2` 에서도 계속 쓰일 수 있을 지는 모르겠지만...
로직 간결화를 위해 계속해서 리팩토링 시도하는 태도가 대단합니다.. 👏🏻 

제안드리고 싶은 건, 해당 메서드는 리턴 타입이 `GameResult`로 명시되어 있잖아요? ㅎㅎ
그 경우, return 해주는 부분에서는 `타입 명시`를 굳이 해주지 않아도 됩니다. ㅎㅎ
쩜(.) 한 번 찍고 사용하면 가독성이 좋아져요~! 😄 

```suggestion
    let computerLoseCondition = (computerInput % 3) + 1

    if playerInput == computerLoseCondition {
        return .playerWin
    } else if playerInput == computerInput {
        return .playerDraw
    } else {
        return .playerLose
    }
```

2022-02-16 12:02 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return nil
연산프로퍼티로 수정 완료했습니다!

2022-02-16 12:04 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let gameResult = checkGameResult(player: playerInput, computer: computerInput)
수정 완료했습니다!

2022-02-16 12:08 UTC, llingo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
guard 문 분리 완료했습니다! 😃

2022-02-16 14:04 UTC, Jager-yoo commented
링고, 우롱차!
`스텝1` 리팩토링 수고하셨습니다~! 머지합니다!
다음 스텝도 화이팅입니다! 😄

2022-02-16 14:05 UTC, merged