가위바위보 게임 [Step1]  로이 ,마이노
yagom-academy/ios-rock-paper-scissors pull request #108
Opened 2022-02-15 08:32 UTC by Roy-wonji

안녕하세용   요한  @yohanBlessYou
STEP1 작성해서 보냅니당!
리뷰 잘 부탁드릴게요~

### Flow chart
<img src = "https://i.imgur.com/4Pvq7Kj.jpg" width="200px"></br>

### 로직구현  
- final class RockPaperScissorsGame
   - `private enum RockPaperScissorsType: Int`
   - `private enum GameResult: String`
   - `func startProgram()`: 프로그램을 시작하는 함수
   -  `private func playSelectedMenu()`: 선택된 메뉴에 따른 게임 실행 함수
   - `private func judgeGameResult(userSelectedNumber: Int)`: 결과를 판단해주는 함수
  - `private func printUserInterface()`: 사용자 인터페이스를 출력해주는 함수
  - `private func printGameOver()`: 게임 종료를 출력해주는 함수
  - `private func printErrorMessage()`: 에러 메세지를 출력해주는 함수
  - `private func printGameResut(gameResult: GameResult)`: 게임의 결과를 출력 하는 함수 
- struct User
  - `enum UserOption
func selectedMenu() -> Int`: 가위바위보 메뉴 선택 함수 
  - `private func verifyUserInput(userInput: Int) -> Bool`: 사용자의 입력 검증 하는 함수 
- struct Computer
  - `func generatedComputerNumber(numberRange: ClosedRange<Int> = GameOption.computerNumberRange) -> Int`: 컴퓨터의 난수를 생성해주는 함수
- enum GameOption

    
### 고민했던점 && 궁금한점
- 어떤 경우에 ` class 와  struct`를 적정하게 써야 되는지 고민을 많이 했습니다. 
- `switch ` 문에서 `self`가 동작하는 이유가 무엇인지 궁금합니다. 
- 역시나 네이밍은  매번 어렵네요 😂

2022-02-15 12:08 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rockPaperScissorsGame: RockPaperScissorsGame = RockPaperScissorsGame(user: user, computer: computer)
명확한 타입명시를 의도하신 것 같아요~ 다만, 특별히 헷갈릴만한 포인트가 아니라면 생략해주는 편이 더 대중적이어서, 매우 명확한 경우엔 생략해주어도 무방할 것 같아요

2022-02-15 12:10 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/User.swift
> +        }
이런 early exit이 목적인 조건문은 `guard`를 사용하는 것도 좋겠네요!

2022-02-15 13:05 UTC, YohanBlessYou requested changes
로이, 마이노 수고하셨습니다👏
두분이 고민하셨던 흔적들이 코드에 많이 녹아있는 것 같아요. 네이밍들이 API 가이드라인 준수 하에 합리적으로 지어졌고 특히 enum의 활용이 눈에 띕니다. 1함수1기능 요구사항도 잘 지켜주셨고 재귀함수 장.단점도 README에 잘 정리해주셨네요! (정리습관은 향후 정말 큰 자산이 됩니다👍)

코멘트한 부분들은 그밖에 제가 판단하기에 개선할만하다거나 고민해볼만한 주제입니다. 앞으로 다른 리뷰어분들도 언급하시겠지만 제 생각이 정답은 아니며, 기본적으로 로이와 마이노의 판단을 따르시되 제 의견은 참고사항 정도로만 받아들여주시면 되겠습니다

---

> Q1. 어떤 경우에 class 와 struct를 적정하게 써야 되는지 고민을 많이 했습니다.

이 부분은 추후 활동학습에서 깊게 다뤄질 예정이라 지금 자세하게 다루진 않겠습니다 (양해 부탁드려요🙏🏻). 지금 시점에 말씀드릴 수 있는 부분은 가능한 한 값타입인 struct를 사용하는 것이 성능/코드복잡도 측면에서 유리하기에 참조타입의 특성이 반드시 필요한 경우에만 사용하는게 좋다는 것입니다. (나중에 다루겠지만 예습차원에서 혹시나 너무 궁금하시면 [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)를 참고하셔도 좋을 것 같네요)

> Q2. switch 문에서 self가 동작하는 이유가 무엇인지 궁금합니다.

switch문은 if문과 비교 연산자(==)의 조합의 변형임을 아실거에요. 즉, 비교연산이 가능하다면 switch문에서도 사용이 가능합니다. 값타입인 enum 인스턴스는 서로 비교연산이 가능하기에 switch문에서도 사용이 가능하다고 볼 수 있겠네요

> Q3. 역시나 네이밍은 매번 어렵네요 😂

네이밍은 늘 어렵죠ㅎㅎ 오래된 경력자분들도 많이 고민하시곤 합니다. 참고하시면 좋을 네이밍 포스팅이 있어 추천드려요  https://soojin.ro/blog/english-for-developers-swift

2022-02-15 13:15 UTC, Roy-wonji commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +            }
앗  줄 버꿈이 들어 갔네용  수정해서 push 하겠습니다

2022-02-15 13:26 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rockPaperScissorsGame: RockPaperScissorsGame = RockPaperScissorsGame(user: user, computer: computer)
생략 해보았습니다!
감사합니다!

2022-02-15 13:27 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/User.swift
> +        }
guard문으로 변경했습니다!
감사합니다!

2022-02-15 13:29 UTC, Roy-wonji commented on RockPaperScissors/RockPaperScissors/User.swift
> +
Foundation Framework는 데이터 저장, text 처리, 날짜 및 시간 계산, 정렬 및 필터, 네트워킹을 포함한 앱 기능과 Frameworks의 기본이 되는 Framework라고 알고 있습니다 
 Array나 데이터 타입을 지정하거나 네트워킹같이 App에서 기본적인 기능을 구현하기 위해서 필수적으로 import되어야하는 Framework라고 해서 사용하는 이유를 알고 있습니다

2022-02-15 13:39 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    private enum RockPaperScissorsType: Int {
해당 class에서 user와 computer를 참조하는 부분이 있어서 class로 구현해보았습니다!
struct안에 레퍼런스가 있는 경우, 레퍼런스 수에 비례하여 레퍼런스 카운팅 오버헤드를 지불하게되고 둘 이상의 레퍼런스가 있는 경우 class보다 레퍼런스 카운팅 오버헤드가 더 많이 유지되기 때문에 성능적으로 좋지 못하다. 라는 내용을 wwdc 영상에서 본적이 있어서 이런식으로 진행을 해보았습니다!

2022-02-16 00:42 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    private enum RockPaperScissorsType: Int {
WWDC 영상까지 보셨군요👍 다만, user와 computer가 struct라 이들을 참조하는게 아닌 직접 소유하고 있는 개념에 가깝습니다

2022-02-16 00:42 UTC, merged