묵찌빠 게임 [Step 1] marisol, cathy
yagom-academy/ios-rock-paper-scissors pull request #110
Opened 2022-02-15 08:48 UTC by GoMyungju171

@yeha

step 1 PR입니다.

decideWinner 함수 구현 시 지금 구현해놓은 index를 활용하는 방법과 아래와 같이 tuple을 활용하는 방법 두가지 중 어떤 방법이 나을지 고민하였습니다.
```
func decideWinner1() {
    let computerNumber = String(Int.random(in: 1...3))
    let userNumber = checkValidity()
    let tuple: (String, String) = (computerNumber, userNumber)
    switch tuple {
    case ("1","2"),("2","3"), ("3","1"):
        print("이겼습니다!")
    case ("1","1"), ("2","2"), ("3","3"):
        print("비겼습니다!")
    default:
        print("졌습니다!")
    }
}
```

그리고, 출력 시 게임 종료 후에 ()가 출력되는데 어떤 부분을 수정해야할지 여쭤보고 싶습니다.

2022-02-15 14:03 UTC, marisol-develop commented
### 수정사항

아까 말씀해주신 매직넘버, 매직리터럴을 최대한 제거해보았습니다! 피드백 부탁드려요 🙇‍♀️

-------------------------------------------

### 조언을 얻고 싶은 부분

그리고 사용자에게 입력받은 숫자의 유효성을 체크하는 `checkValidity(userInput: String) -> Int?` 함수의 로직을 아래와 같이 구현했는데요, 
1) 유효한 숫자의 배열을 만듦 ["0", "1", "2", "3"]
2) 유효한 숫자 배열에 파라미터로 받은 userInput이 포함되어 있는지 확인
3) 포함되어 있다면, userInput을 Int로 형변환
4) 포함되어 있지 않다면, wrongInput 메세지를 출력하고, 다시 숫자를 입력받음

저희가 생각한 로직에서는 유효한 숫자의 배열을 하드코딩하는 것 말고는 다른 방법을 못찾아서, 조언 부탁드려도 될까요?🙏

-------------------------------------------

### 질문

이번에 enum을 처음 사용해보았는데요, 
case의 값을 사용하려면 항상 case 뒤에 .rawValue를 해줘야하는 걸까요?

감사합니다! @ye-ha

2022-02-16 04:45 UTC, ye-ha requested changes
두 분 고생하셨습니다! 스텝 1 나온지 얼마 되지 않아 금방 제출해주셨군요. 🚤
전체적으로 기능 분리하려고 하신 점, 깔끔하게 작성하려고 하신 점 잘 보였어요. 🌟 커밋 단위 잘 나누신 점도 아주 좋습니다. 👍😆👍  
후에 말씀드렸던 매직 넘버와 매직 리터럴 처리해주신 부분 좋습니다. 👏👏👏👏

현재 비기면 게임이 종료되게 처리되어 있는데, 비기면 게임을 다시 할 수 있도록 수정이 필요합니다. 비기는 경우에 다시 초기 메뉴를 출력하고 입력을 받는 부분을 어디에서 어떻게 처리할지 고민해주세요. 😄

---
> decideWinner 함수 구현 시 지금 구현해놓은 index를 활용하는 방법과 아래와 같이 tuple을 활용하는 방법 두가지 중 어떤 방법이 나을지 고민하였습니다.
> 

우선 지금은 구현하신 코드가 보기에 더 간결해 보여요. 
해당 부분에 코멘트를 남겨 놓았으니, 그 부분을 먼저 고민한 후 개선한다면 tuple도 사용할 수 있을 거라고 생각합니다. 😄

> 그리고, 출력 시 게임 종료 후에 ()가 출력되는데 어떤 부분을 수정해야할지 여쭤보고 싶습니다.
> 

종료 후에 () 가 출력이 안되는데, 개선하신 걸까요?

> 그리고 사용자에게 입력받은 숫자의 유효성을 체크하는 `checkValidity(userInput: String) -> Int?` 함수의 로직을 아래와 같이 구현했는데요,
> 
> 1. 유효한 숫자의 배열을 만듦 ["0", "1", "2", "3"]
> 2. 유효한 숫자 배열에 파라미터로 받은 userInput이 포함되어 있는지 확인
> 3. 포함되어 있다면, userInput을 Int로 형변환
> 4. 포함되어 있지 않다면, wrongInput 메세지를 출력하고, 다시 숫자를 입력받음
> 
> 저희가 생각한 로직에서는 유효한 숫자의 배열을 하드코딩하는 것 말고는 다른 방법을 못찾아서, 조언 부탁드려도 될까요?🙏
> 

변수에 담아 유효한 숫자인지 검사하는 지금의 방식도 나쁘다고 생각하지 않아요. 게임 종료(0)를 검사할 때 함께 검사하는 방법이 있을 수 있고요. (로직을 바꿔야 할 수 있습니다.) 하드 코딩과 관련해서 다른 방법이 궁금하시다면, enum 사용은 어떤가요? [**[Enumerations](https://github.com/yagom-academy/ios-rock-paper-scissors/pull/110/%5B%3Chttps://docs.swift.org/swift-book/LanguageGuide/Enumerations.html%3E%5D(%3Chttps://docs.swift.org/swift-book/LanguageGuide/Enumerations.html%3E))**]([https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html)) 문서의 특히 **Implicitly Assigned Raw Values 부분을 보시면 어떻게 사용할지 보여주고 있습니다. 참고해주세요. 😄**

> 이번에 enum을 처음 사용해보았는데요,
> 
> 
> case의 값을 사용하려면 항상 case 뒤에 .rawValue를 해줘야하는 걸까요?
> 

이 부분은 다른 방법이 있습니다.
코멘트에 왜 namespace로 enum을 사용하셨는지 질문남겼어요. 대답을 찾으며 여러 enum 사용을 보다 보면 발견하실 수도 있을 것같아서 지금 바로 말씀드리지는 않을게요!

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case rockScissorsPaper = "가위(1), 바위(2), 보(3)! <종료 : 0>"
저희가 묵찌빠게임을 하고 있긴 하지만..이 부분은 게임 시작에 출력되는 문구같아요. 이름에 의미를 명확하게 담아볼까요?

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
메세지를 모아 놓는 namespace를 만드셨군요.  👏👏👏👏 빠른 반영 아주 좋습니다 👍

하나의 Message 열거형 내에 메뉴, 게임 결과, (입력값) 에러가 함께 모여 있어서 여러 역할을 하는 느낌이에요. 

여기에서 질문 드려요. 
namespace를 만드는 방법으로 enum을 선택하신 이유가 있을까요?

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
이 열거형은 기호 관련이군요. 👍

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +func checkValidity(userInput: String) -> Int? {
이 부분은 꼭 반영하지 않으셔도 좋습니다. 😄
[Swift Language Guide- Functions](https://docs.swift.org/swift-book/LanguageGuide/Functions.html) 내 Specifying Argument Labels 을 보시면 argument label 지정해주는 예시가 나와요. 이 함수에서 활용한다면 좀 더 자연스럽게 읽히도록 바꾸어 볼 수 있을 것 같아요!

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let endingNumber = "0"
사용자가 입력할 수 있는 endingNumber.. 저는 야악간 모호하게 느껴지는데요. 이 부분은 상의해보시고 바꾸셔도, 바꾸지 않으셔도 좋습니다.

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerNumber = Int.random(in: numberRange)
변수에 따로 담아주셨군요. 👍 가독성을 높일 수 있는 좋은 방법입니다. 
저는 `numberRange` 를 보았을 때, 넓은 범위를 의미하고 있다는 생각이 들었어요. 그래서 입력할 수 있는(입력이 허용된) 숫자 범위를 의미하고 있으니, 수식하는 말을 하나 더 붙여서 조금 더 명확하게 한정지을 수 있을 것 같다고 생각했는데요. 여러분의 생각은 어떠신가요?

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let number: Int = validNumber - computerNumber
숫자라는 네이밍은 너무 넓은 범위를 가져요. 😭 어떤 의미를 가지는 상수인지 더 명확하게 바꿔 볼 수 있을까요?

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Message.defeat.rawValue)
연산을 사용해서 승패 여부를 가리는 방법을 선택하셨군요. 👏
하지만 이 부분만 본다면 1, -2, 2, -1 이 각각 어떤 것을 의미하는지 바로 알기 어려울 것같아요. 어떻게 개선해 볼 수 있을까요? 
+ 매직 넘버도 함께 개선해 봅시다!

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let arrayOfValidNumbers = ["0", "1", "2", "3"]
무엇에 valid한지 더 자세한 이름을 붙이면 의미가 잘 전달될 것이라고 생각해요. 추가로 이미 배열을 할당하고 있기 때문에 arrayOf이 빠져도 의미 전달이 될 것이라고 생각하는데, 여러분의 생각은 어떠신가요?

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userInput = readLine() else { return PunctuationMarks.emptyString.rawValue }
guard문을 통해 사용자 입력을 안전하게 받고 있군요! 👍👍👍👍👍

2022-02-16 04:45 UTC, ye-ha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let validNumber = checkValidity(userInput: userNumber) else { return }
startGame() 에서 입력값을 먼저 받고, 게임 종료인지 아닌지 검사한 후 이 부분에서 입력값이 유효한지 검사하는군요! 
함수 이름이 decideWinner라 입력값이 유효한지 검사하는 기능과 승패를 결정하는 기능을 나누어 볼 수 있을 것같은데요. 어떻게 분리할 수 있을지 고민해볼까요? 🤔

2022-02-16 05:07 UTC, cathy171 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case rockScissorsPaper = "가위(1), 바위(2), 보(3)! <종료 : 0>"
rockScissorsPaper 를 messageToStartGame 으로 변경하였습니다.

2022-02-16 05:16 UTC, cathy171 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
1. StartAndEndMessage, ErrorMessage, GameResultMessage 세가지로 분리하였습니다.
2. static let으로 변경하면 property 상수에 담기게 되어 .rawValue를 쓰지 않고도 바로 사용할 수 있습니다.

2022-02-17 10:27 UTC, cathy171 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func checkValidity(userInput: String) -> Int? {
파라미터에 _를 추가하여서 checkValidity(userInput)처럼 userInput만 입력하여 사용할 수 있게 변경하였습니다.

2022-02-17 10:28 UTC, marisol-develop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let validNumber = checkValidity(userInput: userNumber) else { return }
입력값이 유효한지 검사하는 기능을 분리해서 startGame에 넣어서 
- 사용자 입력값이 0,1,2,3 중 하나인지?
- 0이 아닌지?
위 두 조건을 같이 판단하도록 했습니다.
그래서 0이 아니고 && 유효한 숫자일때만 승패를 가르는 decideWinner 함수를 호출하도록 분리했습니다!

2022-02-17 10:28 UTC, cathy171 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let number: Int = validNumber - computerNumber
승자를 결정하기 위한 숫자를 의미하는 numberToDecideWinner 로 수정하였습니다.

2022-02-17 10:30 UTC, marisol-develop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let arrayOfValidNumbers = ["0", "1", "2", "3"]
게임실행을 위한 유효한 숫자라는 의미로 validNumbersForGame이라고 이름을 붙여봤습니다!
저는 왠지 모르겠지만 Collection 타입은 이름에 자꾸 타입명을 넣게 되는 것 같아요😅

2022-02-17 10:30 UTC, cathy171 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerNumber = Int.random(in: numberRange)
입력이 허용된 숫자 범위를 의미하는 allowedNumberRange로 수정하였습니다.

2022-02-17 10:31 UTC, marisol-develop commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Message.defeat.rawValue)
승부를 판단하는 숫자라는 뜻으로, enum 타입으로 DecisionNumber를 선언했습니다.
배열로 선언해서, index를 활용해서 호출했습니다.
더 좋은 방법이 혹시 있을까요? 🙏

2022-02-17 10:32 UTC, marisol-develop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let number: Int = validNumber - computerNumber
어찌 저렇게 썼을까요...🥲
numberToDecideWinner로 변경했습니다.

2022-02-17 10:32 UTC, cathy171 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Message.defeat.rawValue)
열거형을 사용하여 winNumber, defeatNumber에 각각 배열로 승자를 결정하기 위한 숫자들을 지정해주었습니다.

2022-02-17 10:34 UTC, marisol-develop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let endingNumber = "0"
이 코멘트는 어떤 의미인지 정확히 파악을 못해서 수정을 못했습니다🥲
접근제어에 대한 말씀이셨을까요?

2022-02-17 11:11 UTC, merged

2022-02-17 11:21 UTC, ye-ha commented
구두로 코멘트 드렸습니다. 😄 두 분 모두 고생하셨어요! 👍