[s]
yagom-academy/ios-rock-paper-scissors pull request #113
Opened 2022-02-15 11:03 UTC by cherrishRed

2022-02-15 15:42 UTC, ChaminLee commented
안녕하세요 red, mmim! 
이번 프로젝트 리뷰를 맡게된 차차입니다~ 잘 부탁드려요! 

리뷰 전에, 제가 드리는 의견은 100% 정답이 아니기에, 참고하셔서 두 분이서도 의견을 충분히 나눠보시고 더 살펴보고 나만의 것으로 습득하는 시간을 가져보면 좋을 것 같네요 😄 

--- 

> ## 에러 핸들링
> inputPlayerOption이라는 하위 메서드에서 에러 핸들링을 처리해 주다 보니, 그 상위에 있는 메서드 들이 모두 throw 와 try 를 사용하게 되었습니다. 그렇게 throw 문이 많이 생기다 보니, 정확히 에러를 핸들해 주는 곳이 어디인지 알기도 어렵고, 코드가 복잡하다는 느낌이 들었습니다. 조언을 얻고 싶습니다.

-> 맞아요, 지금처럼 에러를 던질 수 있는(`throws`) 메서드를 사용하다보면 `try`나 `throw` or `do-catch`는 필수적으로 따라오죠! [Error Handling](https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html) 문서에서도 다양한 방식으로 처리하고 있음을 볼 수 있습니다. 

이런 경우, 사실은 필수적으로 에러를 던져야하는 상황이 아니라면은 `nil`을 활용해볼 수도 있을 것 같아요. 

```swift
// 기존의 함수 
mutating func checkValidOption(with playerOption: Int) throws -> Int {
    guard optionRange.contains(playerOption) else { throw ErrorCase.valueIsOverRange }
    return playerOption
}

// 수정 
mutating func checkValidOption(with playerOption: Int) -> Bool {
    guard optionRange.contains(playerOption) else { 
        return false
    }
    return true
}
```

위의 방식처럼 로직을 변경해서 에러를 던지는 상황 자체를 피해주는 것도 하나의 방법이 될 수 있을 것 같아요! 

개인적으로 error는 "제가 제어할 수 없는 상황"에서 발생하는 경우에 주로 사용하곤 합니다! 예를 들어서 네트워킹을 하다가 서버에서 발생한 에러를 받게 되는 경우에는 외부에서 발생한 에러를 저희가 핸들링 하기 위해 error 타입을 만들어서 대응해 볼 수 있는 상황이 될 수 있을 것 같아요. 하지만 반면에 optional 값이 바인딩 되지 않는다고 해서 에러를 던지기 보다는, nil을 던져서 해결해볼 수도 있겠죠!

```swift
// 에러대신 optional을 반환
func convertStringToInt(stringValue: String) ->  Int? {
    guard let intValue = Int(stringValue) else {
        return nil
    }
    return intValue
}

func playGame() {
    guard let intValue = convertStringToInt(stringValue: "1") else {
        return 
    }
    // 로직 진행 
}
```
예시를 들자면 위처럼 에러 대신에 optional을 반환해서 로직을 처리해볼 수도 있겠죠 😄 
이 처럼 다양한 방법으로 에러 핸들링을 해볼 수 있습니다! 계속 try를 사용하기 보다는 적당한 선에서 `do-catch`를 사용해서 에러를 처리해주기도 하고요! 한 번 고민해보시면 좋을 것 같습니다! 

> ## class vs structure
>class와 structure를 비교했을 때 성능의 차이가 많이 난다고 생각해서 class를 써야하는 특별한 이유가 없다면(상속이나, extension) structure를 사용하는 것이 맞다고 생각하여, PlayRockScissorPaper``StoreGameData 를 structure 로 설정했습니다.
> 그런데 StoreGameData 함수의 경우 모든 메서드가 mutating 이라는 키워드를 사용하게 되어, 복잡한 느낌이 들었습니다. 이 경우 클래스를 쓰는 것이 옳을까요?

-> struct와 class를 선택하는 건 항상 쉽지 않은 고민인 것 같아요! 말씀하신 것 처럼 `상속`도 선택의 기준이 될 수 있는데요~ 보통은 말씀하신 것 처럼 value type, reference type의 특성을 가지고 기준을 정하는 것 같아요~ [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes)같은 아티클을 읽어봐도 좋을 것 같아요! 본인만의 기준을 정해보는 것도 좋을 것 같아요!

아마 이 부분은 추후 학습활동에서 심도 있게 다뤄볼거라 지금은 대략 어떠한 차이가 있는지 정도만 알아두셔도 좋을 것 같습니다!

> ## enum 타입 사용에 대해서
```swift
enum CaseOfHands: Int {
    case scissor = 1
    case rock = 2
    case paper = 3
}
enum CaseOfHands: String {
    case 1 = "scissor"
    case 2 = "rock"
    case 3 = "paper"
}
```
>CaseOfHands 라는 enum 타입을 지정할 때, 위의 예시와 아래 예시 중 어떤 예시로 결정할 지에 대한 고민이 있었습니다. 결론적으로 저희는 CaseOfHands를 선택할 때의 가독성을 위해서 위의 예시를 선택했습니다. 그런데 처음 player 에게 받는 값이 1, 2, 3 이다 보니 아래 코드도 옳은 것 같은 생각이 들었습니다. rawValue 를 정확히 어떻게 활용해야 하는지 조언 부탁드립니다.

저도 위의 방법이 사용할 때에 좋은 방법일 것 같네요~ 
사용자의 정수값을 케이스에 매칭하기 위해서는 이니셜라이저를 생성해보거나, 기본적으로 제공되는 실패가능한 이니셜라이저를 사용해봐도 좋을 것 같아요~

2022-02-15 15:42 UTC, ChaminLee requested changes

2022-02-15 16:22 UTC, JoSH0318 commented on RockPaperScissors/RockPaperScissors/StoreGameData.swift
> +        let validPlayerOption = try checkValidOption(with: convertedPlayerOption)
결국 같은 값이지만 타입만 변환된 값이어서 구분 짓기 위해 타입 명시를 했습니다.
이 부분도 다시 한번 체크하겠습니다ㅎㅎ

2022-02-16 06:40 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/PlayRockScissorPaper.swift
> +    let resultListWithPaper: Array<ResultMassage> = [ResultMassage.lose, ResultMassage.win, ResultMassage.draw]
Array<Type> 으로 설정한 이유는, 명확히 타입을 알고 싶어서 설정하였는데요, 더 간결한 방법이 여러개 있었군요! 이 상수 자체가 리펙토링을 하는 과정 중에 삭제 되었는데, 다음에 활용하도록 하겠습니😄

2022-02-16 06:42 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/PlayRockScissorPaper.swift
> +    }
네! `displayResult`를 `displayMatchResult` 와 `excuteAfterMatch` 로 분리하였습니다.

2022-02-16 06:44 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/PlayRockScissorPaper.swift
> +    }
저희가 에러 처리에 익숙하지 않은 상황에서, 여러가지를 시도해 보다가, 다른 상황에서 생기는 에러라고 생각되어 케이스를 나눠서 작성하였는데요... 리펙토링 이후에는 do try 문을 삭제하고 에러 처리 로직을 변경해 이 부분이 없어졌습니다.

2022-02-16 06:45 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +try somePlayer.playGame()
넵 이번 프로젝트를 하면서 에러 핸들링 부분을 열심히 공부하게 되었습니다! 
리펙토링 하는 과정에서, 옵셔널로 에러를 핸들링 하면서 이 부분은 사라졌지만, 공부에는 아주 도움이 되었어요😂

2022-02-16 06:55 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/StoreGameData.swift
> +        return computerHand
좋은 방법 제안해 주셔서 감사합니다. `CaseIterable` 과 `allCases`에 대해 알게 되었습니다. 
활용할 일이 많을 것 같습니다. 
리펙토링을 진행 하면서 손모양만 들어갔던 enum 타입에서, 사용자의 선택을 받을 수 있는 enum 타입으로 수정하였더니, allCalses 를 받는 의미가 없어져, 저희 코드에서 이 부부을 수정할 수 없었는데요(allCases -2 이렇게 처리하는 것은 아닌 것 같아서요.) 혹시 playerOption 을, 가위, 바위 보 와 게임종료, 같이 받되 나눠서 관리할 방법은 없을 까요???

2022-02-16 06:57 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/StoreGameData.swift
> +        guard let inputPlayerOption: Int = Int(playerOption) else { throw ErrorCase.valueIsWorngFormat }
아 그렇군요, 왜 한 줄에 작성하는 것을 지양하는 것인지 궁금했는데, 궁금증이 해결 되었습니다. 감사합니다.

2022-02-16 06:58 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/StoreGameData.swift
> +        let validPlayerOption = try checkValidOption(with: convertedPlayerOption)
`check-` 라는 문구를 `Bool` 타입에 주로 사용하는지 처음 알아 갑니다! 네이밍은 변경 해 보겠습니다!

2022-02-16 07:01 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/PlayRockScissorPaper.swift
> +    case paper = 3
넵, rawValue를 없애는 로직으로 변경하였습니다. 
그렇다면 rawValue 를 어떤 상황에서 사용하는 것이 좋을까요?

2022-02-16 07:02 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/PlayRockScissorPaper.swift
> +    case draw = "비겼습니다!"
네! 연산 프로퍼티로 변경하여 rawValue 를 수정하였습니다.

2022-02-16 07:24 UTC, cherrishRed commented
@ChaminLee 🚗
STEP1 리펙토링 완료 했습니다. 🥳
* playerHand 타입 변경에 따른 메서드 삭제 및 추가
* vertifyWinner 함수 로직 변경 
* 에러 처리 로직 변경
* enum 타입 전면 수정

## enum 타입 전면 수정
기존 `enum` 타입의 `rawValue를` 쓰지 않기 위해 고민했고, `extension` 을 추가해서 최대한 의미를 알수 없는 `rawValue` 사용을 줄이고자 했습니다.
그로인해 `enum` 타입을 사용할 때 `rawValue` 를 쓰지않고 정수를 받아쓸 수 있게 변경했습니다.
또한, `printMassage` 연산 프로퍼티를 `extension CaseOfOptions`에 추가함으로써 출력 제어 로직도 바꿨습니다.

## playerHand 타입 변경에 따른 메서드 삭제
`playerHand` 를 Int 로 받고 있었는데, `PlayerOptions` 이라는 enum 타입이 생겨나면서, `playerHand` 를 `PlayerOptions` 타입으로 설정하게 되었습니다. 

이에 따른 `convertStringToInt` 메서드 삭제와 `convertStringToOption` 메서드 생성이 일어났습니다. 

## vertifyWinner 함수 로직 변경
기존에 승패를 담아 저장 하였던 에러이가 무슨 일을 맞고 있는 아이인지 알아보기가 여러워 삭제하고, 경우의 수를 분석해서 if 조건문을 사용하는 로직으로 변경하였습니다. 

## 에러 처리 로직 변경 
기존에 throw 와 do-catch 문으로 처리하던 에러 처리를 throw 를 발생시키지 않고, guard 문만을 사용하여 처리하도록 변경하였습니다.

2022-02-16 13:25 UTC, ChaminLee commented on README.md
> +ex) 5-cherrishred, 5-cherrishred-step1, 5-cherrishred-step2
step마다 요구하는 기능들이 다르기 때문에 이를 분리하기 위해서라도 branch를 스텝에 따라 나눠서 진행해보시는 것도 좋을 것 같습니다~

2022-02-16 14:18 UTC, ChaminLee commented
리팩토링까지 빠르게 하시고 고생많으셨습니다 👍 

이번에는 타입 분리까지 잘 신경쓰셔서 해주셨네요! 💯 
조금 더 코멘트 남기자면 각 사용자 정의 타입 내의 프로퍼티에 기본값이 의미가 크게 없는 것 처럼 보여졌습니다. 이에 이를 개선해보는 걸 한 번 필수로 해보고 넘어가면 좋을 것 같아요! 

자세한 부분은 코멘트 참고 부탁드립니다

---

## rawValue를 사용해야할 때

개인적으로는 rawValue를 통한 초기화가 필요할 때 사용하는 것 같습니다. 특정한 값을 나타내기 위해 rawValue를 사용하게 되면 외부에 드러나는 `rawValue`라는 이름이 의미가 명확하지 않기에 이러한 경우에는 rawValue가 아닌 다른 방법을 우선 고려해보는 것 같네요~

## 가위바위보와 메뉴 입력 옵션을 구분하는 방법 

말씀하신 것 처럼 가위바위보, 게임 종료를 같이 받되 나눠서 관리하려면 구현하신 것 처럼 구간을 나누어 판단한다거나 해야할 것 같습니다~ 

만약에 저라면 이전처럼 가위바위보만 가지는 열거형은 그대로 둘 것 같습니다! 대신 사용자가 입력할 1~3 이외의 수인 0이나 그 이상의 수는 처음에 `readLine()`을 받을 때 판단해줄 것 같습니다~ 

만들어두신 `inputPlayerOption()`에서 옵셔널 바인딩에 실패했을 때 뿐만 아니라, 유효하지 않은 입력인 경우에도 `.error`를 뱉어주도록 구현해볼 수도 있겠네요!

2022-02-16 14:19 UTC, ChaminLee requested changes

2022-02-16 14:19 UTC, ChaminLee commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +    }
앞서 드린 코멘트 처럼 이 부분에서 결과를 바로 반환해 볼 수 있을 것 같네요~! 그러면 내부의 `matchResult` 프로퍼티 없이도 구현해볼 수 있을 것 같네요~!
```suggestion
    mutating func vertifyWinner(_ playerHand: Int,_ computerHand: Int ) -> MatchResult {
        if playerHand == computerHand {
            return .draw
        } else if playerHand - computerHand == 1 || computerHand - playerHand == 2 {
            return .win
        } else {
            return .lose
        }
    }
```

2022-02-16 14:40 UTC, JoSH0318 commented on RockPaperScissors/RockPaperScissors/MatchResult.swift
> +    var printMessage: String {
이 부분에서 약간의 고민이 생겼었어요 ㅎㅎ
프로퍼티이지만 "무언가를 연산하는 동작"의 성격을 가지고있다고 생각이 들어서 고민 끝에 저런 네이밍을 했습니다 ㅎㅎ
말씀하신대로 좀 더 고민하고 수정하겠습니다!

2022-02-16 18:21 UTC, JoSH0318 commented on README.md
> +   - 이슈 목록에서 상세보기를 하면 댓글을 통해 팀원과 이슈에 대한 소통을 할 수 있다.
🥳

2022-02-16 18:22 UTC, JoSH0318 commented on RockPaperScissors/RockPaperScissors/GameData.swift
> +    var playerOption: PlayerOptions = .scissor
리턴과 파라미터를 적극 활용하여 수정했습니다.

2022-02-16 18:23 UTC, JoSH0318 commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +    }
로직의 흐름에 따라 함수 호출을 개선했습니다!

2022-02-16 18:38 UTC, cherrishRed commented
@ChaminLee 🚗
STEP1 리펙토링 완료 했습니다. 😭
* 의미 없는 기본 값 제거
* 메서드 분리
* enum 타입 분리
* 예외 조건 처리 향상

## 의미 없는 기본 값 제거
모든 `rawValue` 를 삭제 하였습니다. `rawValue` 로 처리하던 로직을 `optionNumber` 라는 프로퍼티를 만들어 수정했습니다. 

## 메서드 분리
메서드가 이름의 역할을 충실히 다할 수 있도록 메서드를 분리했습니다. 
그리고 로직의 흐림에 따라 메서드의 호출 순서를 변경 하였습니다. 

## enum 타입 분리
`PlayerOption`enum 타입을 사용에 따라 `PlayerHands` 와 `Status` 로 분리 하였습니다. 
처음에는 함수 자체에서 다양한 리턴 타입을 발생할 수 있게 처리하고 싶었지만, 방법을 찾지 못해, 튜플을 사용했습니다.
`PlayerHands` 와 `Status` 를 동시에 튜플로 처리를 함으로써, 사용자의 패와 현재 상태를 동시에 알 수 있게 하였습니다. 

`PlayerOption` 타입의 분리로 인해, 오직 `Status` 에서만 에러를 처리 할 수 있게 되었습니다. 

## 예외 조건 처리 향상
예외 조건을 처리 해주는 함수와 할당을 해주는 함수가 나뉘어져 있었는데 리턴을 활용해 `convertToPlayerOption` 에서 두 가지를 동시에 처리하도록 하였습니다.

2022-02-17 03:11 UTC, ChaminLee commented
코드 확인해보았는데요~! 전체적으로 잘 개선된 것 같네요~! 이번 스텝에서는 이 정도까지만 수정하고 넘어가면 좋을 것 같고요! 다음 스텝에서 좀 더 개선해보면 좋을 것 같은 사항 남겨둡니다! 

- `generateComputerHand()` 내에 플레이어의 옵션을 변경한다는 `convertToPlayerOption()` 가 들어가 있는 부분 
- 상태를 사용하면서 손모양에 `.none` 이 들어가있는데, enum의 case에 none을 만들기 보다는 none이 필요한 부분에 nil을 리턴해주는 등 옵셔널을 활용해보셔도 좋을 것 같습니다~ 
- 그리고 rawValue 사용을 지양하면 좋겠다고 했던 부분은 case에 = 1, = 2 할당하는 것을 지양하는게 아니라, 외부에 `case.rawValue` 와 같이 드러나는 사용 방식을 지양하라고 말씀드리고 싶었습니다~ 

위 부분은 참고만 해주시면 될 것 같고, 머지 요청 주시면 머지 진행하도록 하겠습니다~ 
고생많으셨습니다 👍

2022-02-17 03:11 UTC, merged