묵찌빠게임 [STEP2] 로이, 마이노
yagom-academy/ios-rock-paper-scissors pull request #118
Opened 2022-02-17 01:17 UTC by Mino777

@YohanBlessYou 
STEP2 PR입니다!
잘 부탁드립니다🥰

### 구현내용
- struct MukjipaGame
    - `private enum MukjipaType: Int`
    - `mutating func startMukjipaGame(currentTurn: Player)`: 묵찌빠게임을 시작하는 메서드
    - `private mutating func playSelectedMenu()`: 선택된 메뉴에 따른 게임 실행 메서드
    - `private mutating func judgeGameResult(userSelectedNumber: Int)`: 결과를 판단해주는 메서드
    - `private mutating func changeCurrentTurn()`: 턴을 교체해주는 메서드
- enum GameOption
- enum Player
- struct UserInterface: 출력 메서드들을 모아둔 구조체
    - `print~()`
   
---

### 고민했던점 && 궁금한점

- 묶찌빠 조건에서  이기면 턴이넘어가는걸 구현할때 `swith문`으로 구현을을 할까  아니면 `if문으로` 참거짓을 판별해서 구현을 할까 고민이 많았습니다 
- 이번에 프로젝트를 하면서 구현 별로 파일을 분리 했는데 파일을 분리 하는 기준을 어떻게 잡는지 궁금해서 의견을 물어봅니다!!🤔
- 이번에 git에서 이슈라는 기능이 있다고 하는데 이 기능에대해 좀  자세히 알고 싶어요🤔

---

### 개선한 점

- final class RockPaperScissorsGame -> struct로 변경
    - 현재 RockPaperScissorsGame타입 안에 있는 User, Computer, UserInterface 프로퍼티의 경우 값타입인 struct 타입이기 때문에 class로 진행할 이유가 없음.
-  print 관련 메서드들을 UserInterface로 분리하여 관리
-  폴더 그룹핑 및 공통으로 쓰는 코드 분리 

---

감사합니다!🙇‍♂️

2022-02-17 11:47 UTC, YohanBlessYou requested changes
STEP2도 고생많으셨어요👏
새로이 추가된 `MukjipaGame`의 메서드들이 기존 `RockPaperScissorsGame`의 메서드들과 서로 유사한 기능을 가지는데, 동일한 네이밍을 사용해주셔서 쉽게 읽을 수 있었어요. 지금처럼 유사한 기능을 하는 프로퍼티/메서드들은 네이밍을 통일시켜주는게 좋습니다👍

그리고 결과 출력 기능을 전담하는 `UserInterface`를 별도의 타입으로 만들어 가위바위보와 묵찌빠에서 재사용해주신 부분도 정말 좋았습니다👍

>Q1. 묶찌빠 조건에서 이기면 턴이넘어가는걸 구현할때 swith문으로 구현을을 할까 아니면 if문으로 참거짓을 판별해서 구현을 할까 고민이 많았습니다

저는 다른 것보다 가독성을 기준으로 선택하고 있는데, 현재 코드에서는 구현해주신대로 switch문이 더 적절해보이네요

>Q2. 이번에 프로젝트를 하면서 구현 별로 파일을 분리 했는데 파일을 분리 하는 기준을 어떻게 잡는지 궁금해서 의견을 물어봅니다!!🤔

현재 코드에 분리해주신 것처럼, 1파일1타입이 저를 포함해서 대중적으로 많이 사용되는 것 같아요. 이 부분은 따로 정답이 없고 협업자 간 합의만 된다면 어떤 식으로든 괜찮다고 생각되네요

>Q3. 이번에 git에서 이슈라는 기능이 있다고 하는데 이 기능에대해 좀 자세히 알고 싶어요🤔

issue를 활용하는 다양한 예시가 있겠지만, 저는 보통 commit들을 그룹핑하여 보고 싶을 때 사용합니다. 예로, 묵찌빠게임에선 "STEP2"를 milestone으로 설정하고 하위 issue들은 "출력기능구현", "묵찌빠게임 로직구현", "리팩터링" 등으로 만들 수 있겠네요. commit이 많은 상태에서 과거의 commit을 찾아볼 때 이런 분류가 도움이 됩니다. 이 외에도 활용예시가 많을테니 여러 사람의 의견을 듣고 구글링해보시는걸 추천드려요

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/Common/UserInterface.swift
> +
개인적으로 정말 좋아하는 스타일입니다. 특정 기능을 하는 별도의 타입을 만드는 방식은, 대부분의 경우 가독성과 코드 유연성에 유리한 것 같아요👍

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/Common/Player.swift
> +}
none은 어떤 경우에 필요한가요?

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/Common/User.swift
>      }
만약 게임 룰이 바뀌어 묵/찌/빠 외에 선택지가 더 생기면 이 부분도 수정되어야 할까요?

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +        userInterface.printMukjipaGameUserInterface(currentTurn: currentTurn)
self는 어떤 기준으로 붙이고 계신가요? 이에 대한 로이,마이노의 기준이 있는지 궁금합니다

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +        }
switch-case 문 줄바꿈 규칙이 다른 부분과 통일되어 있지 않은 것 같아요

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +
`Int`라는 명시가 붙은 곳도 있고 없는 곳도 있는 것으로 보아 로이,마이노가 정한 규칙이 있는 것 같아요. 타입명시는 어떨 때 붙게 되나요?

2022-02-17 11:47 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          }
이런 승패로직을 포함해서 코드 전반적으로 Int가 아닌 열거형 RockPaperScissorsType으로 다루면 가독성도 좋아지고 열거형의 장점을 살릴 수 있을 것 같아요. 좀 더 근본적인 질문을 드리면, 열거형은 어떤 경우에 사용하며 어떤 장점을 가질까요?

2022-02-17 11:57 UTC, Roy-wonji commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +        }
네  수정 하겠습니다

2022-02-17 12:00 UTC, Roy-wonji commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          }
열거형은 유사한 종류의 여러 값을 한 곳에 모아서 정의해서 사용하는거라고 알고 있습니다.
비슷환 타입별로 묶어서 사용을 했습니다

2022-02-17 12:01 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +
앗 최근에 타입을 명시해주는것이 컴파일단에서 타입을 추론하는 비용을 줄여준다라는 글을 읽어서  모두 명시하는 습관을 들일려고 최대한 타입을 명시해주었습니다!
타입 명시를 안해준곳이 있었나보네요..!
모두 명시하는걸로 수정하겠습니다!

2022-02-17 12:04 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +        userInterface.printMukjipaGameUserInterface(currentTurn: currentTurn)
self의 경우 파라미터의 네이밍과 프로퍼티 네이밍이 같거나 비슷한경우에 self를 붙입니다!
그런데 지금보니 그 경우가 아닌경우에도 self를 붙였었네용😭
해당 경우가 아닌 부분은 수정했습니다!

2022-02-17 12:08 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Common/Player.swift
> +}
해당 부분은 묵찌빠 게임을 처음 초기화할때 사용합니다!
currentTurn이 변수이기 때문에 디폴트값을 지정해주기 위해 사용했습니다!

2022-02-17 13:23 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          }
열거형을 사용하는 경우에 해당 타입만 사용하도록 제약을 줄 수 있어서 좀 더 안전한 코드가 될 수 있을 것 같습니다!

해당 피드백 관련하여 최대한 열거형을 사용하여 전반적으로 리팩토링 해보았습니다. 그런데 해당 로직의 경우 열거형으로 비교했을 때는 모든 경우의수를 if문으로 처리해야하는 부분때문에 요한한테 좀 더 피드백을 듣는게 나을 것 같아서 우선은 Int로 두었습니다!

2022-02-17 13:25 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Common/User.swift
>      }
해당 부분의 경우 저희가 아직 에러처리에 대한 부분을 염두하지않고 진행을 하다보니 예외처리를 이런식으로 진행한 것 같습니다😭

2022-02-18 02:23 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/Common/User.swift
>      }
이 부분은 사실 에러처리보단 게임룰과 관련한 `wrongInput` 프로퍼티를 `User`라는 타입이 갖는게 적절한가?에 대한 질문이었습니다😁 static let이라는 방식은 괜찮다고 느껴집니다

2022-02-18 02:49 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          }
가위바위보 게임에선 여러 케이스의 조건문 body가 서로 중복되므로, 불필요한 중복을 피하고자 알고리즘적으로 처리해주신 것으로 생각됩니다. 하지만 모든 케이스를 명시하지 않고 알고리즘적으로 처리할 때는 우선 상대적으로 가독성이 불리하다는건 알고 계실거에요. 이 경우 switch와 튜플을 사용하면 모든 케이스를 명시하면서도 중복을 피하도록 작성할 수 있을 것 같네요~

```swift
switch (user, computer) {
case (.rock, .rock),(.scissor, .scissor), (.paper, .paper):
    print("draw")
case (.rock, .scissor),(.scissor, .paper), (.paper, .rock):
    print("user win")
case (.rock, .paper),(.scissor, .rock), (.paper, .scissor):
    print("computer win")
default:
    break
}
```

2022-02-18 02:54 UTC, YohanBlessYou commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +
좋은 접근이고 팩트지만 실제로는 명시해주는 사람이 거의 없긴합니다ㅜ  추측컨대 가성비(성능대비귀차니즘)를 따진게 아닌가 싶네요

2022-02-18 02:57 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          }
와우.... 와... 이건 정말 미처 생각을 하지 못했었네요...!!!
너무 깔끔합니다...
열심히 공부하겠습니다!!!
감사합니다!

2022-02-18 03:00 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/MukjipaGame.swift
> +
그건 맞는 것 같습니다ㅠㅠ
정말 큰 프로젝트가 아닌 이상 딱히.. 차이가 없을 것 같긴 합니당
해당 부분에 있어서는 협업자와의 상의와 상황에 따라 적절한 트레이드 오프가 필요한 것 같습니다
의견 감사드립니당!!

2022-02-18 04:02 UTC, merged