묵찌빠 게임 [STEP 2] Lingo, 우롱차
yagom-academy/ios-rock-paper-scissors pull request #122
Opened 2022-02-17 12:36 UTC by llingo

@Jager-yoo 
안녕하세요 예거 😃
7_group의 Lingo, 우롱차 입니다. 잘 부탁드립니다!
묵찌빠 게임 STEP 2 PR 보냅니다.

> 파일을 완전히 새로 분리한 뒤 커밋을 해서 `예거`가 리뷰하기 힘든 점과 커밋 단위를 크게한 점 사죄드립니다.

## 순서도 (Flow chart)
<img width="400" alt="야곰 프로젝트 2 - STEP2" src="https://user-images.githubusercontent.com/94151993/154480574-5afdc45f-36a0-4cb5-ac55-f8ff27f1b54e.png">

## 고민한 점
1. 너무 많은 기능들이 main 파일에 몰려있어서 가독성도 떨어지고 찾기도 힘들었습니다. 
2. 가위바위보 게임과 묵찌빠 게임에서 유사한 기능들이 많았는데 이를 전부 새로 구현하는 게 맞는 건지 의문이 들었습니다.

## 해결한 점
main 파일에 몰려있었던 문제를 `class`를 사용해 분리하는 방법과 파일로 분리하는 방법을 고민했고 저희 팀은 파일 분리로 진행하여 RockScissorPaper, MukZziPpa 파일로 분리하고 공통된 열거타입을 Common 로 분리했습니다.

## 조언 받고 싶은 부분
네이밍을 불가피하게 MukZziPpa 로 선언했는데 혹시 세련된 네이밍이 있을 지 `예거` 라면 어떻게 했을지 조언 받고 싶습니다.

2022-02-17 16:34 UTC, Jager-yoo commented
안녕하세요 우롱차, 링고! 😄 
빠르게 작업해서 `스텝2` 제출해주셨군요~ 수고 많으셨습니다. 👏🏻 

진도가 나간 만큼, `순서도`를 수정해주셔서 코드 구조를 이해하기 편했습니다. 👍🏻 
순서도 그릴 때 무슨 tool 을 사용하시는지 궁금하네요. ㅎㅎㅎ 디자인도 알록달록 예쁘고 심플해서 좋네요!

## 🦺 코드 총평

파일 분리를 크게 4개(네임스페이스, 가위바위보 게임, 묵찌빠 게임, main.swift)로 해주신 점과
전반적으로 네이밍에 신경을 많이 쓰신 게 느껴졌습니다. 👍🏻 

리팩토링 방향은 -> 타입이나 메서드 `재사용`을 최대한 해볼 수 있는 방향으로 설정해봤습니다!
묵찌빠 게임에서, `찌(2)는 가위(1)로, 묵(1)은 바위(2)로 변환`하는 과정만 신경쓰시면 손모양 타입은 하나로만 쓸 수 있습니다. 😄 
고민 충분히 해보시길 바랄게요!!! 🚀 

## 💭 고민하신 점에 대해

네이밍 `"MukZziPpa"` 에 대한 고민이 있으셨군요 ㅎㅎㅎ
재밌는 점은, 저도 4달 전에 묵찌빠 게임 할 때 똑같은 고민을 했었습니다.

저는 당시에 어떻게 생각했냐면, 묵찌빠 게임은 `고유명사`니까, 어설프게 영어로 번역하지 말고 원문 그대로를 살리자!
-> 라고 생각했었어요. 그래서 구글링을 해보니, [위키백과](https://ko.wikipedia.org/wiki/%EB%AC%B5%EC%B0%8C%EB%B9%A0)에 `"muk-chi-ba"` 라고 나와있더라구요?
그래서 저는 사전을 근거하여, `"MukChiBa"` 라고 네이밍했었습니다. 😆 

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/154490803-5d2b1a02-b040-4360-bf4e-a3e7d3f427da.png" width="80%"></p> 

물론 두 분에게 백과사전에 나와있는 대로 네이밍을 바꾸라는 말은 절대 아닙니다.
사실 그거나 그거나... 비슷하잖아요? 😄 
고유명사 같은 단어를 `코드 네이밍`으로 변환할 때, 어떤 기준으로 변경할 지 고민해보신 것으로 충분합니다! 👍🏻

2022-02-17 16:35 UTC, Jager-yoo requested changes

2022-02-17 16:35 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/MukZziPpa.swift
> +}
이 메서드는 가위바위보에서와 거~의 유사한데, 별도의 메서드로 분리해서 `재사용`이 아쉬우셨죠?

재사용을 못하셨던 가장 큰 이유는 무엇이었나요? ㅎㅎ

> 가위(1), 바위(2), 보(3)
> 묵(1), 찌(2), 빠(3)

가위바위보와 묵찌빠 게임의 `입력 규칙`이 달라서 그러셨을 것 같아요! 🤔 
그래서 메서드가 비슷한 게 2번이나 만들어지고, 심지어 손모양 타입도 2개로 분화되었죠.

어떻게 하면 메서드를 `재사용` 하면서 묵찌빠 게임일 때와, 아닐 때를 분기처리해줄 수 있을까요?
더 나아가, `손모양 타입`도 하나만 쓸 수 있을까요?

천천히 메서드 하나, 타입 하나씩 리팩토링을 같이 시도해보죠! 😄

2022-02-17 16:35 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +}
해당 메서드를 예시로 함께 리팩토링해볼까요!? 😄 

> 가위(1), 바위(2), 보(3)
> 묵(1), 찌(2), 빠(3)

표현은 다르지만, 근본적으로 `손모양은 3개 뿐`입니다.
가위바위보, 묵찌빠 게임 둘의 보(3) == 빠(3)는 동일하지만
가위와 바위가 서로 `교차` 하는 게 문제의 핵심이죠 ㅎㅎㅎ

따라서, 묵찌빠 게임인 걸 체크한 뒤에,
플레이어가 묵(1)을 내면 -> 변환해서 -> 바위(2)로 들어온 거로 처리하고
플레이어가 찌(2)를 내면 -> 변환해서 -> 가위(1)가 들어온 거로 처리하면 됩니다!

* 일부로 else절 위치를 [스타일쉐어 가이드](https://github.com/StyleShare/swift-style-guide) 처럼 해봤습니다. 😉 

```swift
// 묵찌빠 게임인지 아닌지, 파라미터로 받음
func getPlayerInput(isMukZziPpa: Bool) -> Int? {
    guard let playerInput = readLine(),
          let playerIntInput = Int(playerInput)
    else {
        return nil
    }
    
    guard playerIntInput != Settings.exitCode
    else {
        return playerIntInput
    }
    
    guard HandType.contains(playerIntInput)
    else {
        return nil
    }
    
    // 묵찌빠 게임이 맞고, 보(3) == 빠(3) 가 아닌 경우 손모양을 교차시켜서 내보냅니다.
    if isMukZziPpa, playerIntInput != HandType.paper.rawValue {
        // 묵(1) 들어온 경우 -> 바위(2)로 바꿔서 내보내고
        // 찌(2) 들어온 경우 -> 가위(1)로 바꿔서 내보냅니다.
        return (playerIntInput % 2) + 1
    }
    // 묵찌빠 게임이 아니라면, 가위바위보 게임 로직 그대로 갑니다.
    else {
        return playerIntInput
    }
}
```

2022-02-17 16:35 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/MukZziPpa.swift
> +        print(GameDisplayMessage.error)
가위바위보와 묵찌빠에서 사용되는 `손모양`은 동일합니다.
그리고 컴퓨터는 여전히 랜덤한 손을 내잖아요?ㅎㅎㅎ

따라서 여기서 굳이 묵찌빠 만을 위한 손모양 타입(MukZziPpaHandType)을 만들지 마시고
기존 손모양 타입(HandType)을 재사용해보시면 좋겠습니다!

대신 묵찌빠 게임 결과 판단하는 `로직`은 손보셔야 할 거에요!!

```suggestion
    guard let computerInput = HandType.randomPick else {
        print(GameDisplayMessage.error)
```

2022-02-17 16:35 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/MukZziPpa.swift
> +    printMukZziPpaGameMenu(result)
묵찌빠 게임이 시작할 때는, 이미 이전 게임인 가위바위보에서 승패가 정해진 상황이잖아요?
그래서 묵찌빠 시작하는 메서드에서 `파라미터로 이전 게임의 결과`를 받아주시는 거로 이해했습니다! 👍🏻 

이때, 파라미터 생략하기 보다는, `with` 전치사를 사용해서
"묵찌빠 게임을 어떤 결과와 `함께` 시작한다." -> 이런 늬앙스를 담으면 어떨까요? 😄 

```suggestion
func startMukZziPpaGame(with result: GameResult) -> GameResult? {
    printMukZziPpaGameMenu(result)
```

```swift
// 사용되는 모습
startMukZziPpaGame(with: .playerLose)
startMukZziPpaGame(with: .playerWin)
```

2022-02-17 16:35 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/MukZziPpa.swift
> +    let computerWinCondition = (computerInput % 3) + 1
여기 `메서드 시그니처`(메서드 네이밍과 파라미터 리스트들)가 맘에 들어요!! 👍🏻👍🏻
플레이어와 컴퓨터의 숫자를 받고, 마지막 승자가 누구인지도 파라미터로 받아주고
내부에서 로직 돌려서, 다시 `GameResult` 타입을 내보내주는 게 좋네요 ㅎㅎㅎ
GameResult 타입이 계속 재사용되는 게 훌륭합니다! 😄 

만약 `손모양 타입`을 하나로 통일하는 거로 리팩토링을 시작하셨다면,
그 아래 `computerWinCondition` 의 로직은 다시 점검하셔서, 이상이 없는지 꼭 체크해보세요!

2022-02-18 04:04 UTC, llingo commented on RockPaperScissors/RockPaperScissors/Common/Constant.swift
> +}
추후에 항목이 추가될 가능성을 염두해두었기 때문에 `Settings`라고 네이밍을 하게되었습니다.

2022-02-18 16:10 UTC, Jager-yoo requested changes

2022-02-18 16:10 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/MukZziPpa.swift
> +    let playerWinCondition = (computerInput % 3) + 1
여기 메서드 길이가 꽤 길죠~?
그래서 스타일쉐어 가이드 대로 줄바꿈해보셨군요. 좋습니다 😄 

그리고 `playerWinCondition` 또한 이름 변경해주셨군요!! 👍🏻👍🏻
게임 결과를 판단해주는 메서드가 2개 (가위바위보 하나, 묵찌빠 하나) 있기 때문에
내부에서 쓰는 `상수명`을 통일해주시니, 이해하기가 더 쉽네요 ㅎㅎㅎ

2022-02-18 16:10 UTC, Jager-yoo commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +        switch value {
묵찌빠 손타입을 가위바위보 손타입으로 변환해주는 타입 메서드를 만드셨군요! 👍🏻 

지난 코멘트에서도 말씀드렸지만, `HandType`의 타입 메서드이므로
호출될 때 `HandType.convertMukZziPpaToHandType` 와 같이 불리게 될 겁니다.
"HandType" 이라는 단어가 중복되죠? ㅎㅎㅎ

차라리 손모양을 `묵찌빠 스타일`로 전환하다(convert) 라는 의미를 주는 건 어떨까요? 😄 

```suggestion
    static func convertMukZziPpaStyle(_ value: Int) -> Int? {
        switch value {
```

2022-02-20 05:58 UTC, llingo commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    }
`예거` 가 피드백해준 내용처럼 `isHandType` 에서 `contains` 변경하고 `CaseIterable`의 allCases를 더 활용할 수 있도록 리팩토링했습니다!

2022-02-20 05:59 UTC, llingo commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +}
파라미터를 받도록 해서 `getPlayerInput` 함수의 재사용성을 늘렸습니다! 😀

2022-02-20 06:03 UTC, llingo commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +        switch value {
처음 네이밍을 할때 **묵찌빠 형식을 HandType 열거형의 case에 맞게 변환해준다**는 의미로 `convertMukZziPpaToHandType` 라고 했었는데 피드백 해주신 `~스타일` 라는 네임으로 리팩토링 했습니다.
역시 네이밍이 가장 어렵네요 😅

2022-02-20 08:34 UTC, merged

2022-02-20 12:21 UTC, Jager-yoo commented
링고, 우롱차!
스텝2 리팩토링하시느라 수고하셨어요! 👏🏻👏🏻 `머지`했습니다.

짧은 일주일 이었지만, 리뷰를 해주며 저 또한 다시 배워갑니다. ㅎㅎㅎ
그리고 `README`도 깔끔하게 잘 써주셨더라구요. 중요한 2~3개 포인트만 얻어가셔도, 계속 성장하실 수 있을 거에요 👍🏻 

그럼 다음 <쥬스메이커> 프로젝트도 화이팅입니다~~ 😄 💐