묵찌빠 게임 [STEP 2] 쿼카, minseong
yagom-academy/ios-rock-paper-scissors pull request #125
Opened 2022-02-18 02:52 UTC by Minseong-yagom

@llghdud921 
안녕하세요 제리~
저희가 로직 구현 하면서 예상치 못한 재귀오류(무한재귀)를 만나서 그것을 해결 하는데 시간이 많이 소요된 것 같았습니다.
약 한 5 시간?? 정도를 재귀 오류 해결 하는데 사용한 것 같은데 너무나 영광스럽고 많이 배운 것 같습니다. 😉
제리 바쁘신 와중에도 꼼꼼한 리뷰 감사합니다 [STEP 2]도 잘 부탁드립니다~. ☺️

# 기능 구현
### [타입]
- `private HandGame` : Hand Game의 필요한 기능과 특성들을 담은 값
- `private Kind` : 게임의 종류를 담은 값
- `private Hand` : HandGame에 필요한 패를 담은 값
- `private Player` : 사용자와 컴퓨터를 담은 값
- `private Guide` : 게임 실행시 출력되는 메세지를 담은 값
- `private Result` : 게임결과시 출력 메세지를 담은 값
- `private Erorr` : 잘 못된 입력시 출력되는 메세지를 담은 값

### [프로퍼티]
- `private hasUserWin` : 묵찌빠의 공격자 턴을 구별 해주기 위한 프로퍼티

### [함수]
- `play()` : 가위바위보 및 묵찌빠 게임을 시작
- `private printInputGuidanceMessage()` : 게임에 필요한 입력가이드를 제시
- `private receiveUserInputHand()` : 사용자 패를 입력 받는다
- `private isValueZero()` : 입력된 패가 "0"(게임종료)인지 확인
- `private convertedUserHand()` : 사용자가 입력한 패를 게임에 맞게 변환
- `private generatedRandomHand()` : 컴퓨터의 패 랜덤으로 생성
- `private judgeUserGameResult()` : 가위바위보 결과를 판정
- `private playMukjipa()` : 묵찌빠 게임을 시작
- `private printRockPaperScissorsWinnerTurn()` : 가위바위보 승리자 턴 출력
- `private isWrongInputted` : 정상적인 입력 외에 값인지 검사 
- `private printGameResult()` : 게임결과 메세지를 출력
- `private switchTurn()` : 턴을 변경
- `private printMukjipaWinnerTurn()` : 묵찌빠게임 현재턴을 출력
- `private printMukjipaWinner()` : 묵찌빠게임 승자를 출력
- `private judgeMukjipaWinner()` :  묵찌빠게임 결과를 판정

# 순서도
### [STEP2]
![image](https://user-images.githubusercontent.com/94295586/154607106-40b9a890-740c-4bca-92a9-3d4e8277d6a8.png)
# 문제 해결 & 어려웠던점 & 고민했던점 & 궁금한점
## 문제 해결
- 묵찌빠게임에서 `convertedUserHand` 함수로 패를 반환하는데 묵찌빠에서도 재활용이 가능해보였습니다. 재활용을 하게될시 두가지 문제점이 발생하였습니다. 첫번째는 패만 반환되는것이아니라 `0` 대한 값도 반환해주어야한다는 점이고 두번째는 가위바위보 게임에서는 사용자입력이 `1`번이 가위이고 `2`번이 바위이지만 묵찌빠에서는 `1`번이 바위이고 `2`번이 가위입니다. 

**0에대한 해결방법)** 먼저 사용자입력을 받고나서 바로 `0`인지에대해 검증하는 함수로 연결을 해주었습니다. `0`은 게임을 종료하는 로직이기때문에 가장 먼저 처리해주는것이 적절하다고 생각했습니다. 그리고 난 후에 `Hand`에 `case end`를 제거해줬습니다. 이방법은 묵찌빠에서도 적용됩니다.

**두 게임의 1, 2의 차이 해결방법)** `gamd Kind`라는 열거형을 만들어 가위바위보와 묵찌빠게임에 대한 `case`를 만들고, `convertedUserHand`함수 매개변수에 `gamekind`타입을 추가해주었습니다. 그래서 가위바위보게임일때는 `1`번이 가위, 2번이 바위로 처리가되지만 묵찌빠일때는 `if`문으로 `gamekind == .mukjipa`일때는 1,2번을 바꾸어 `Hand`를 `return`하는 방식을 선택하였습니다. 그렇게 두줄의 코드를 추가함으로써 `convertedUserHand` 함수를 재사용할 수 있었습니다.

## 어려웠던점
- 묵찌빠 게임할때에도 `convertedUserHand`함수를 재활용 할 수 있겠다는 판단이 들었습니다. 묵찌빠게임은 잘 못 입력했을 때 사용자입력을 다시 받는 재귀함수 패턴이 아니라 사용자 턴이 바뀌고 입력을 받게됩니다. `convertedUserHand`함수에서 사용자턴으로 바뀔때 실행될 필요없는 `default`값 때문에 초기에는 `if`문을 사용하여 `default`를 빼주는것을 고민해보았으나 잘 못 입력된것에대해서 지속적으로 메세지를 표해주고 재귀함수필요없이 값을 받아주는게 `switch`문의 편리한점때문에 사용했지만 재귀가 리턴하는 과정에서 로직에러가 계속 발생하고 에러 파악하기로 어려워져 `switch`을 사용하지 않고 불필요한 재귀는 최소화하는 방향으로 `if`문으로 수정하였습니다. 

## 고민했던점 & 느낀점
- `enum Type` `Naming`을 `스위프트 랭귀지 가이드 문서` 를 참고하여 단수로 지정하였습니다.
- 묵찌빠 게임에서 사용자 입력을 받을 함수를 재활용 할까 고민 했는데 재사용성에 대해서 고민해보는것도 좋지만 이를 해결하기위해 만들어지는 함수가 오히려 더 많아지는 역설적인 상황이 생기기도 한다. 이번기회에 재사용성에대해서 고민해보고 삽질을 할 수 있는 좋은기회였던것같다.
- 턴 체인지에 대한 방법고민을 많이했던것 같습니다. 그중에서 가장 유연하고 편리한 방법으로  `var hadUserTurn` 프로퍼티를 만들어 턴을 구별해주는 방식으로 처리하였다.
- 재사용성 코드에대해서 고민을 해보았습니다.

# 궁금한점
- 사용자입력받는 함수 실행전에 lldb에 초기화된 값이 찍히는게 궁금합니다. `Case`첫번째값이 `default`로 찍히는데 이는 왜그런건가요 ?? 🧐
- 네이밍문서(https://www.swift.org/documentation/api-design-guidelines/)에 보면 사이드 이펙트가 없는 함수에는 함수명을 명사로 짓는다걸 확인했어요. 저의가 작성한 함수드들은 대부분 사이드이펙드가 없다고 판단되는데 제리에 생각은 어떠한가요?

2022-02-19 10:39 UTC, llghdud921 requested changes
안녕하세요! 쿼카~ 민성~
Step2까지 고생하셨습니다 👍
코드 구현하신거 보면서 정말 잘하신다고 느껴졌습니다.... 앞으로 정말 잘하실 것 같아요... ☺️
재귀 오류로 인해 5시간이나 노력하신점 정말 끈기있으시다고 느꼈어요 😮 대단합니다 👍 
이번 리뷰를 끝으로 다시 리뷰드리지는 못하지만 앞으로 캠프생활에서 자주 만나요 :) 

## Good
- 함수가 하나의 기능을 가지도록 한점 정말 완벽하네요... 저는 이렇게 못합니다.... 💯 
- 코드를 재사용하기 위한 노력이 많이 보였어요 gameType을 입력받도록 메서드 구현한 것이 정말 좋았습니다 👏
- 문제 해결했던 점과 어려운점을 리드미에 남겨놓으신 거 정말 좋다고 생각했어요 👍 저도 읽어보면서 이런 문제가 있었구나... 이해하였습니다 🤗

## 조언 드릴 점
- 리드미에 적어놓으신 페어 프로그래밍에 대한 어려움을 읽어보았어요. 저도 정말 공감이 많이 되었고 협업하는 방식에 대해 고민이 많으실거에요... 저는 지금도 힘듭니다ㅠ 그래도 먼저 해보아야할 것은 커밋을 번갈아서 기능을 구현하는 것은 꼭 지키셨으면 좋겠어요! 페어 프로그래밍은 두사람의 충분한 이해를 위해 진행하는 것인데 제대로 지키지 않으면 이해의 차이는 존재할 거라 생각이 듭니다 😢 
진행하는데 어려움이 있으면 야곰이나 크루, 선배들에게 도움을 요청하셔도 좋습니다 🤗

## 질문에 대한 답변
> 사용자입력받는 함수 실행전에 lldb에 초기화된 값이 찍히는게 궁금합니다. Case첫번째값이 default로 찍히는데 이는 왜그런건가요 ?? 🧐

저도 디버깅을 해보았는데요! 컴파일 타임에 코드영역을 저장될때 변수가 저장이 되는데요 그때 열거형의 첫번째 case로 저장이 되는 것 같아요. 하지만 실제로 stack 할당된 것은 아닙니다!
<img width="749" alt="스크린샷 2022-02-19 오후 7 35 59" src="https://user-images.githubusercontent.com/40068674/154797296-3bf8230d-c423-4948-9644-e129385e7daf.png">
위 사진처럼 할당이 되지 않아서 print문도 찍히지 않죠 ☺️ 이 구조는 앞으로 메모리 구조를 배우실때 더 잘 이해가 가실거에요! 저도 값이 할당된것처럼 보여서 당황햇네요ㅎㅎ 더 자세한 부분은 제가 다른분에게 여쭤보고 답글 남겨놓을게요! 정말 꼼꼼하게 잘 보시는것같아 좋습니다 👍 

> 네이밍문서([https://www.swift.org/documentation/api-design-guidelines/)에](https://www.swift.org/documentation/api-design-guidelines/)%EC%97%90) 보면 사이드 이펙트가 없는 함수에는 함수명을 명사로 짓는다걸 확인했어요. 저의가 작성한 함수드들은 대부분 사이드이펙드가 없다고 판단되는데 제리에 생각은 어떠한가요?

네이밍 잘하시고 계시구요! 추가로 말씀드릴 부분은 코멘트에 남겨놓았습니다 😊

2022-02-20 08:46 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +        if userGameResult != .draw { playMukjipa(didUserWin: self.hasUserWin) }
`self`를 작성하지않아도 컴파일 에러는 안나는걸로 알고있어요. 다만 자신의 프로퍼티를 사용한다는것을 직관적으로 알려주기위함으로 작성하였습니다. 😄

2022-02-20 08:47 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +            return .scissors
재사용성을 고려하여 하나로 만들어보았지만 두개로 분리해볼수도 있을것같아요. 분리하는게 가독성측면에서 좋을까요 ?? (궁금)

2022-02-20 08:52 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
>              play()
안그래도 함수의 기능이 두가지역할을 하는게 아닌가하는 염려가 되었었어요 ..^^
미리 이전에 게임결과가 비겼을때를 처리해주는 함수로 빼는게 좋을것같아요! 👍

2022-02-20 08:52 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +    private mutating func switchTurn(by gameResult: Bool) {
매개변수에도 `Bool` 에대한 네이밍을 지어준다는것을 간과했네요 ㅎㅎ 
`hasUserWin`으로 수정하겠습니다!

2022-02-20 08:53 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +        let normalValues = ["1", "2", "3", "0"]
함수 내부에서 변수로 처리되는게 메모리측면에서 좋지않을까 시도했었는데요!
생각해보니 1,2,3,0은 다른데에서도 계속 사용될수도있으니 좋을 방법인것같아요 ㅎㅎ

2022-02-20 08:54 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +            if normalValue == value { return false }
헉,,,, `contains`으로 쉽게 해결해볼 수도 있겠네요 ㅎㅎ 감사해요

2022-02-20 11:20 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> -        print(HandGame.Guide.message.description, terminator: "")
와우,,,, 이런 프로토콜이 있었군요.... 코드많이줄여볼 수 있을것같아요 ㅎㅎ 감사합니다!

2022-02-20 11:21 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +    private var hasUserWin = false
피드백 감사해요!!

2022-02-20 11:22 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/main.swift
> +var handGame = HandGame()
유일하게 가지고있는 `hasUserWin`프로퍼티의 값이 턴표시할때 변경되기때문에 `var`로 변경하였습니다.

2022-02-20 11:41 UTC, Quokkaaa commented on RockPaperScissors/RockPaperScissors/HandGame.swift
> +    private mutating func judgeUserGameResult(userHand: HandGame.Hand, computerHand: HandGame.Hand) -> HandGame.Result {
`User`이라는 단어를 뺴는게 적절할까요 ??

2022-03-24 13:47 UTC, closed without merging