묵찌빠 게임 [STEP1] seohyeon2, KayAhnDS
yagom-academy/ios-rock-paper-scissors pull request #129
Opened 2022-04-18 10:22 UTC by KayAhnDS

@dnwhd0112

안녕하세요 우롱차!
저희는 seohyeon2, KayAhnDS 입니다.
묵찌빠 게임 STEP1 PR 요청 드립니다!
잘 부탁 드립니다!!

## 📖 함수 목록 및 역할

- printUserOption()
    - “가위, 바위, 보, 종료”  출력
- makeComputerRandomNumber() -> Int
    - 1이상 3이하의 랜덤한 수를 반환
- inputUserNumber() -> Int
    - printUserOption()을 기본적으로 출력하고
    - 사용자로부터 입력받은 후 checkUserInputNumber를 통해 입력에 해당하는 숫자를 반환
- checkUserInputNumber(userInput: String) -> Int
    - 문자열을 입력 받고 스위치문을 통해 분기 처리 및 값 반환
- printErrorMessage()
    - “잘못된 입력입니다. 다시 시도해주세요.” 출력
- compareTwoNumbers (userInput: Int, computerInput: Int) -> Int
    - 사용자가 이기는 케이스를 선언.
    - 사용자와 컴퓨터가 비기는 케이스, 사용자가 이기는케이스, 사용자가 지는 케이스를 검사 후 해당 값 반환.
- printResult(matchResult: Int)
    - 매개변수로 받은 matchResult에 따라 스위치문으로 분기 처리 후 해당 문구 출력
- startGame()
    - 게임을 시작하는 함수
    - 먼저 컴퓨터의 숫자를 입력 받고
    - 무한 루프를 돌면서 사용자 입력이..
        - -1 인 경우 다시 입력 요구.
        - 0 인 경우 종료.
        - 1에서 3사이의 값은 컴퓨터의 숫자와 비교
            - 이기거나 지는경우는 게임종료.
            

## 📖 궁금한점

- 스타트게임을 조금 더 세분화 하고싶은데 좋은 방법을 알려주시면 감사하겠습니다!
- 변수명과 함수명을 많은 시간을 들여 작성했지만, 잘 썼는지 궁금합니다!
- enum을 사용해서

2022-04-18 17:38 UTC, dnwhd0112 requested changes
안녕하세요! seohyeon2, KayAhnDS 
수고하셨어요!

1. 스타트게임을 조금 더 세분화 하고싶은데 좋은 방법을 알려주시면 감사하겠습니다!
-> 왜 세분화를 하고 싶은가요? 지금 세분화는 충분하다고 느끼시지 않나요? 세분화를 하는 기준은 뭔가요?

2. 변수명과 함수명을 많은 시간을 들여 작성했지만, 잘 썼는지 궁금합니다!
-> 이부분은 적절치 않은 변수, 함수명이라 느껴지면 커멘트를 남겨놓도록 하겠습니다. 이해하기 쉽고 확실한 변수명, 함수명이면 좋겠어요.

3. enum의 연관값을 저렇게 사용해 보았는데, 가독성을 해치지 않는지 궁금합니다! 더 좋은 방법이 있다면 알려주세요!
-> 저는 보통 enum에서 case에 값을 할당하고 rowValue를 쓰는 편인대요. 변수명으로 하는게 가독성이 훨씬 좋긴 하지만 짜는 사람입장에서 보면 아무래도 변수에 대한걸 하나 더 생성해줘야되고 이를 또 고려해줘야되는 점이 안좋긴 하네요. 두분은 어떻게 생각하시나요? 어떤 장점이 있고 어떤 단점이 있을까요?

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameResult: Int {
굳이 Int값을 반환해줘야 될 필요가 있을까요? 또 반환해준 Int값에 무슨 의미가 있나요?

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RockPaperScissorsGame: Int {
enum 이름이 잘 이해가 안가요... RockPaperScissorsGame은 우리가 진행하는 게임 아닌가요?

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case .terminate:
terminate, inputError가 number는 아닌거 같은대... 혹시 여기에 terminate와 InputError가 필요한가요?

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var result: Int {
이런 방식으로 값을 리턴 하는것도 좋네요!
저는 항상 case에 value를 주는 형식으로 구현했는대 이 방식도 좋아 보이네요.

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let inputNumber = readLine() ?? ""
inputNumber가 nil 값이 할당안되도록 한게 좋네요!

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            selectedNumber = verifiedUserInput
이부분은 가독성이 떨어지네요 혹시 좀 더 좋은방법은 없을까요?

2022-04-18 17:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printResult(matchResult: Int) {
출력문을 따로 빼주시는점 좋습니다

2022-04-19 01:26 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RockPaperScissorsGame: Int {
기존에 있던 terminate, InputError 케이스를 빼고, 
가위,바위,보에 해당하는 번호만 처리하는 `RockPaperScissor`라는 명칭으로 수정했습니다!😌

2022-04-19 01:28 UTC, KayAhnDS commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameResult: Int {
ExceptionalInput, RockPaperScissor, GameResult 이라는 Enum을 각각 만들어준 이유는 코드 전반에 뿌려져있는 숫자들을 한곳으로 모아 관리하면 유지 및 보수적인 측면에서 유용하다 생각이고, ( 한곳에서 관리하니 나중에 한곳만 수정하면 코드 전체에 영향을 미침), Int로 반환하는 이유는, checkUserInputNumber에서 사용하기 위함입니다.

2022-04-19 01:29 UTC, KayAhnDS commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case .terminate:
다시 생각해보았는데 굳이 (가위,바위,보)Enum들과 같이 있을 필요는 없는것으로 보여 따로 빼주었습니다! 한번 더 생각하게 해주셔서 감사합니다!

2022-04-19 01:31 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            selectedNumber = verifiedUserInput
가독성이 떨어지는 이유가 명칭에서 오는 것이 크다고 생각하여 네이밍을 수정했습니다!
가위,바위,보에 해당하는 번호를 담고 있는 enum의 명칭은 
RockPaperScissorsGame -> RockPaperScissor

가위,바위,보에 해당하는 연관값의 명칭은
number -> correspondingNumber

로 수정하는 방법으로 가독성을 높여봤습니다!

2022-04-19 01:31 UTC, KayAhnDS commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var result: Int {
감사합니다!

2022-04-19 01:31 UTC, KayAhnDS commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printResult(matchResult: Int) {
감사합니다!

2022-04-19 01:32 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let inputNumber = readLine() ?? ""
감사합니다🥳

2022-04-19 03:38 UTC, dnwhd0112 approved these changes
이번 스텝에서 조금 아쉬웠던 부분은 다음 스텝에서 고쳐주시면 좋겠습니다!
그럼 다음 스텝도 화이팅하세요!

2022-04-19 03:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameResult: Int {
GameResult 가 Int를 반환하지 않고도 프로그램을 짤 수 있을꺼 같아요! 그리고 GameResult에 할당되는 숫자는 무슨 의미가 있죠?

2022-04-19 03:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            selectedNumber = verifiedUserInput
제가 말한 부분은 변수명보다는 case문에 너무 많은 조건이 있어서 그랬어요. 이걸 좀 짧게 표현하는 방법은 없을까요?
참고: caseiterable

2022-04-19 03:38 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameResult: Int {
그리고 프린트 되는 출력문들도 enum으로 관리하는 방법은 어떨까요?

2022-04-19 03:38 UTC, merged

2022-04-19 11:27 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            selectedNumber = verifiedUserInput
오! caseiterable 처음알았네요! 
RockPaperScissor 타입을 caseiterable로 하고,
이에 따라 체크해주신 부분(checkUserInputNumber 함수 안) 수정했습니다!

2022-04-19 11:38 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameResult: Int {
원래 숫자의 역할은 게임의 결과를 차례로 갖는 인덱스의 역할을 했습니다.
할당되는 숫자의 의미를 보다 명확하게 하고 출력문들도 enum으로 관리하기 위해,
Int 에서 String 반환 형식으로 GameResult를 바꿨습니다!