묵찌빠 step1 구현
yagom-academy/ios-rock-paper-scissors pull request #13
Opened 2020-11-05 12:35 UTC by wonhee009

묵찌빠 step1까지 구현한 코드입니다. 리뷰 부탁드립니다ㅎㅎ

2020-11-05 23:56 UTC, yagom requested changes
상수의 사용이 인상깊습니다.
몇 가지 질문이 있어요. 
또, 프로그램을 하나의 함수의 실행을 통해 실핼할 수 있도록 구현해 보면 좋을것 같아요.

2020-11-05 23:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +let errorInput = "잘못된 입력입니다. 다시 시도해주세요."
반복적으로 사용할 코드를 상수로 선언한 것이 정말 좋아요!
스위프트에서 연관된 상수끼리 묶어주는 방법은 없을까요? :)

2020-11-05 23:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> + */
이 주석이 없더라도 코드 해석이 가능하도록 구현하는 방법에 대해 고민해보면 좋을것 같습니다.

2020-11-05 23:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
1년 뒤, 내가 이 숫자를 보고 게임 결과를 유추할 수 있을까요?

2020-11-05 23:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
사용자의 입장에선 입력에 실수를 할 수 있는데, 아무런 안내 없이 갑자기 프로그램이 종료되어 버리면 당혹스러울 것 같아요.
이런 것은 기획자에게 다시 의도를 물어보거나 통념적인 방법으로 프로그래머가 구현할 수 있습니다.
이를 묵시적 요구사항이라고도 합니다.

2020-11-06 04:54 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> + */
enum을 통해 해결해봤습니다!:)

2020-11-06 09:08 UTC, yagom requested changes
많은 개선이 있었네요! 👍 
몇 가지 질문과 코멘트가 있습니다!

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func turnMessage(_ turn: Gamer) -> String {
함수를 호출하여 사용하는 입장에서는 전달인자로 무엇을 보내야할지 함수 이름만으로는 알 수 없을 것 같아요.
만약 이 함수를 제대로 사용하려면 이 함수의 정의부로 다시 돌아와서 확인해 봐야할 것 같아요.
매개변수 레이블을 굳이 없앤 이유가 있을까요?
turn이라는 매개변수 이름도 내부에서 사용할 때 직관적이지 않은것 같습니다.
일 년 뒤에 내가 이 코드를 보고도 명확히 이해할 수 있는 이름이 필요합니다.

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func turnMessage(_ turn: Gamer) -> String {
또, 메시지라는 이름 자체가 메시지 자체를 반환해 줄 것 같은데, 이 함수는 메시지가 아니라 뭔가... 턴의 주체를 반환하는 함수네요.
좀 더 역할을 명확히 표현할 수 있는 이름이 필요할 것 같습니다.

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return ""
빈 문자열이 없음을 나타내는 것이 아니라 빈 문자열도 '문자열'입니다. 빈 문자열을 사용한 이유가 있을까요?

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func winMessage(_ turn: Gamer) -> String {
이 함수는 이름처럼 명확하게 메시지 전체를 반환해 주는군요.
좋아요. 매개변수 레이블은 다시 고민해 볼 필요가 있을 것 같습니다.
매개변수 레이블이 어떤 역할을 할지는 스위프트 언어 가이드 문서의 함수 파트와 API 디자인 가이드라인 문서를 함께 살펴보면 좋을것 같아요.

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return Gamer.computer
숫자를 사용한 것보다 훨씬 명확하고 이해하기 쉽네요 :) 좋습니다!

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print(Msg.errorPrint.rawValue)
사용자를 배려하여 메시지를 보내주는 것은 좋아요 :)

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            if number == 0 {
여기서 0도 좀 더 직관적으로 표현해 볼 수 있지 않을까요?

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            // 비긴 경우는 다시 게임
코드가 명확해지면 주석은 없어도 괜찮아요 :)

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +
위의 코드와 아래 코드를 줄바꿈으로 분리한 이유가 있을까요?

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func gameStart() {
gameStart 보다는 startGame이 더 좋을 것 같아요.
Swift API Design Guidelines의 Naming 파트를 참고해보세요.

2020-11-06 09:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +gameStart()
프로그램을 하나의 함수로 실행한 것은 좋은 시도입니다 :)

2020-11-06 10:42 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            if number == 0 {
이 부분에 대해서는 private 변수인 exitCode를 사용해 수정해보았습니다.

2020-11-06 11:13 UTC, yagom approved these changes
흡수력이 스폰지 같아요 :)
코드를 빠르게 만들어 내는데 집중하지 않고, 문서를 한 번 차근히 살펴보는 여유도 필요합니다.
코멘트 확인하고 이번 프로젝트는 여기에서 마쳐도 좋습니다.
더 커밋하지 않고 PR 스스로 Merge 해도 좋습니다.
주말 푹 쉬고 건강한 모습으로 다음주에 만나요!

2020-11-06 14:04 UTC, yagom approved these changes
이번 프로젝트의 코멘트는 여기까지입니다.
이번주 고생 많았습니다.

2020-11-06 14:04 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +private let exitCode = 0
특별히 private를 사용한 이유가 뭘까요?

2020-11-06 14:04 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum HandState {
아직 state와 status의 차이에 대한 대답을 듣지 못했어요.
이 코드에 state를 사용하는 것이 더 알맞다고 판단한 걸까요?

2020-11-06 14:04 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return .draw
GameStatus.draw 대신에 .draw 처럼 사용할 수 있는 이유는 무엇이었나요?

2020-11-06 14:04 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            if number == exitCode {
훨씬 직관적이네요 👍

2020-11-06 14:11 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +private let exitCode = 0
exitCode가 게임을 종료하는 code이니까 만약 다른 곳에서 exitCode에 접근할 수 있다면 1로 바뀔 경우 사용자가 가위/묵을 선택했는데 종료되는 경우가 생길 수 있지 않을까 생각해서 private로 선언했습니다!:)

2020-11-06 14:14 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum HandState {
코딩할때마다 state를 사용할지 status를 사용할지 고민이 많았는데 야곰의 리뷰를 통해 어느정도 기준이 생긴거 같아요!
state와 status는 상태를 의미하는 것에 사용할 수 있지만 status는 과정의 상태에 대해 사용한다 생각해
손 상태는 과정이 중요한게 아니라 생각해서 HandState를 사용했어요!
코드에서 GamersStatus라는 struct가 있는데 여기는 사용자의 손 상태의 흐름, 누구의 게임 턴인지 같은 과정이 중요해서 status를 사용했구요!

2020-11-06 14:17 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return .draw
함수를 선언할때 return 타입으로 GameStatus를 선언해서
return할 때 GameStatus라는 enum이라고 추론할 수 있어 GameStatus를 선언하지 않고 .draw만으로 return할 수 있는거 같아요!

2020-11-06 14:18 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +private let exitCode = 0
이 소스코드에서 private를 사용한 경우 exitCode가 영향을 미칠 수 있는 범위가 어디까지일까요?
또, let으로 선언했다면 상수기 때문에 다른 곳에서 변경할 수 없습니다 :)

2020-11-06 14:18 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum HandState {
그렇군요, 좋아요 👍

2020-11-06 14:19 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return .draw
네, 짐작한 내용을 직접 문서에서 찾아보면 훨씬 좋습니다 :) 다른 블로그 글 보다는 진짜로 애플이 남겨둔 그 설명서가 제일 정확하죠.

2020-11-06 14:32 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +private let exitCode = 0
exitCode가 main.swift내에서만 접근할 수 있어요. 
현재 프로젝트는 main.swift만 있지만 프로젝트가 커져 다른 블록들이 늘어난다면 다른 블록에서 exitCode에 대해 몰라야한다고 생각해서 private으로 선언했어요.
저는 exitCode가 게임을 종료하는 코드이기에 크리티컬한 부분이라 생각했거든요.
(let이라서 수정 불가능한거를 위의 코멘트서는 간과했네요..ㅋㅋ)

2020-11-06 14:35 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return .draw
앗! 제가 이전에 공부했던 내용인데 추론하듯이 적어놨네여!ㅋㅋㅋ 담부턴 좀 더 자신감을 가지고 적어야겠어여!

2020-11-06 14:48 UTC, merged