묵찌빠게임 [STEP1]  unchain123, borysarang
yagom-academy/ios-rock-paper-scissors pull request #131
Opened 2022-04-18 11:14 UTC by yusw10

@kimkyunghun3 
코멘트 잘 부탁해요 에디! :hammer:

:label: 함수 설명
======
- `startMenu` 최초 게임 시작을 하기 위한 함수, 유저 인풋을 받기위한 startMenu 함수 호출
- `choiceMenu` 사용자에게 0,1,2,3중 한가지를 입력받아 가위바위보를 진행
- `getComputerNumber` 컴퓨터의 가위바위보 값을 랜덤으로 생성
- `checkUserInput` 사용자 입력값이 정상적인지(0,1,2,3 중 하나) 확인하는 함수
- `compare` 사용자 입력값과 랜덤으로 생성된 컴퓨터의 가위바위보 값을 비교한다. 비길 경우 재귀적으로 다시 startMenu 함수 호출

``` swift 
enum RPS: Int {
    case scissors = 1
    case rock = 2
    case paper = 3
    case none = -1
}
```
사용자 입력값과 컴퓨터가 생성한 랜덤값을 부여하는 enum입니다. 컴퓨터와 사용자의 입력값을 비교하는 부분에서 Enum을 사용한다면 어떤 경우에 이기는 지 알기 쉬울 거라고 생각하여 작성하였습니다. 
none 값은 가위바위보와 관련 없으나 초기화를 하기 위해 의미없는 값을 지정해주었습니다. 

```swift 
my == RPS.rock && computer == RPS.scissors ||
my == RPS.scissors && computer == RPS.paper ||
my == RPS.paper && computer == RPS.rock
```

:mag: 고민한 점
======
### Naming 
 가위-바위-보 라는 개념을 담은 enum 열거형을 만들어서 활용하려고 했는데 사용자의 입력, 컴퓨터의 랜덤생성된 값, number와 choice의 차이 등 최대한 의미를 담는 변수명을 지으려고 노력했습니다. 
 
### 재귀함수 사용시의 장,단점
 loop를 활용해서 반복을 구현하는 방법과, 재귀를 통해서 반복을 구현하는 것 중 고민을 하였으나 반복이 실행되는 부분은 '비겼을 경우'와 '잘못 입력되었을 경우'이고 대부분의 정상적인 플레이를 한다면 짧게 프로그램이 진행된다고 생각되어 재귀적으로 코드를 작성하였습니다(이러는 쪽이 가독성이 더 좋다고 생각했습니다!)

:pencil2: 공부한 부분
======

### enum 활용
 열거형의 값을 비교하고 사용하기 위해 방법을 찾던 중 rawValue라는 프로퍼티로 값을 지정하고 사용할 수 있다는걸 찾아서 사용했습니다.

2022-04-18 15:13 UTC, kimkyunghun3 requested changes
안녕하세요~STEP2 구현하시느라 고생했습니다!

아래 의견들은 어디까지나 제 의견이고, 정답은 아니니까 참고만 해주세요.
항상 팀원끼리 상의하시고 작성하신 코드가 맞다고 생각하시면 저와 다시 이야기 해봐요😃

커밋 단위도 잘 나누어서 어떤 기능을 단위별로 수행했는지 파악하기 편했습니다!
다음 스텝에서도 요번 스텝처럼 잘 나누어서 하면 좋을 것 같습니다

Enum도 활용 잘하시고, rawValue를 이용한 접근도 아주 잘하셨습니다! 공부 열심히 한것이 보였습니다 🔥

네이밍에 대한 고민도 많이 한 흔적이 보였습니다. 그래서 많은 부분에 대한 수정이 필요하진 않았지만 명확하지 않는 부분에 대해서는 다시 한번 고민해봐도 좋을 것 같습니다!

FlowChart도 작성하고 프로젝트 하신 것같은데, 그러면 실수도 줄일 수 있어서 좋습니다!
앞으로도 먼저 설계 후 코드 작성하는 습관을 가져보세요!

재귀함수와 일반 반복문의 장단점에 대해 알려주세요!
대부분 짧게 실행 되었을 때 재귀함수 사용하는 것은 좋은 방법인 것 같습니다 또한  가독성이 더 좋다고 생각하신 것도 어느 정도 맞다고 생각합니다!!
그러면 재귀함수 사용시 주의해야할 점은 무엇이 있을까요?

리드미 작성을 미리미리 하시면 좋을 것 같습니다. 프로젝트가 끝나고 하게되면 Step 1에서 한 것이 무엇인지 까먹을 수도 있으니 Step 2 시작 전이나 PR 전에 하는 것도 방법같네요!

마지막으로 PR에서 고민한 점을 자세히 적어주실수록 저의 리뷰는 자세하게 가능해집니다! 여러분들이 고민하고 이야기 나누었던 부분을 풀어서 설명해주신다면 처음 보는 제가 어느 부분을 더 고민했고, 왜 이런 네이밍이 나왔는지 등을 자세히 알 수 있어서 그에 적절한 커멘트가 남겨질 것같습니다! 다음에는 고민이 생긴다면 미리 메모를 하고 PR 작성 시 참고하면 더 자세한 고민한 점이 나오지 않을까 싶네요🧐

2022-04-18 15:13 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func choiceMenu(number: String) {
또한 이곳이 실제 동작하는 것이 메뉴를 선택하는 메서드 인가요?

2022-04-19 05:21 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
이 부분에는 1. 누가 코드를 작성했는지 2. 작성한 코드의 저작권이 누구에게 있는지가 적혀있는거라고 생각했습니다. 
저희가 최초에 야곰의 프로젝트를 포크 해와서 야곰의 소스 기준으로 되어있어서 이부분을 저희의 것으로 바꾸는게 맞는지, 아니면 그냥 지금 request 보낸대로 삭제를 하는게 맞는지 고민 했었습니다. 
다만 이 프로젝트 자체가 야곰에게 머지될 것이고 저희의 이력은 커밋 이력으로 남아서 코드상에서는 삭제하는게 맞다고 생각했습니다...!

2022-04-19 05:28 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case none = -1
choiceMenu 함수에서 myChoice를 초기화할때 사용하기 위해 none을 만들었습니다. 유저의 선택 후 비교 하기전에 RPS값으로 변환하는 과정에서 초기화를 하지 않으면 오류가 나는데 이때 초기화를 하는 값이 가위,바위,보 중에 아무 값인 것 보다는 none인게 더 자연스러운것 같아서 사용하게 되었습니다.

2022-04-19 05:28 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case scissors = 1
감사합니다😄

2022-04-19 05:34 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let choicedMenu = readLine() {
게임을 시작함수가 맞다고 판단하여 startGame으로 변경하였습니다.

2022-04-19 05:43 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func choiceMenu(number: String) {
첫 시작 함수의 이름을 startGame으로 변경하면서 이 함수의 이름도 choose(동사형) 에서 다른 의미로 바꾸는게 맞다고 생각하여 operateGame으로 변경하였습니다. 
게임시작 > 게임의 기능 작동 ( 가위바위보 값 지정 > 비교 > 결과출력) 이라는 흐름으로 가면 좋겠다고 생각하여 operate으로 지정했습니다..!

2022-04-19 05:52 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
number값에 따라서 분리를 해주고 싶어서 if문을 사용해보았는데 코멘트를 보고 다시 확인해 보니 if문 else if가 많이 들어가면서 switch문 보다 가독성이 떨어지는 것 같아 switch문으로 변경하였습니다.

2022-04-19 06:03 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("ERROR getComputerNumber()")
에러메세지를 "컴퓨터의 값을 얻어오지 못했습니다."로 변경하였습니다.

2022-04-19 06:05 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func getComputerNumber() -> RPS {
유저와 비교하기 위한 컴퓨터의 랜덤한 가위바위보 값을 생성하는 메서드입니다..!
일단 RPS 열거형 타입으로 반환을 하기 때문에 Int타입을 반환하는 것처럼 해석될 것 같은 number를 뺐고, 
컴퓨터의 값(enum이라 값이라는 의미로 생각했습니다..!)을 "얻는다"는 의미로 
obtain을 써서 obtainComputerValue로 변경해보았습니다.

변수, 메서드명 관련해서 항상 고민이 많았는데 좋은글 공유 감사합니다! 정독 해보겠습니다🫡

2022-04-19 06:24 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return
처음에 플로우차트를 작성하면서 필요한 과정을 unchain과 이야기하는 중에 '유저의 인풋이 1,2,3,0 이 아닌 값이 들어오면 처리를하는' 과정이 필요하다고 생각했습니다. 필요한 기능을 하나씩 module별로 작성 하면서 checkUserInput도 작성을 한 메서드입니다.
그런데 operateGame(이전의 choiceMenu메서드)을 구현하는 과정에서RPS enum값에 매칭을 할 때 바로 예외처리를 진행해서 사용할 일이 없는 함수가 되어 서로 고민해보고 불필요한 함수라고 생각해서 제거하게 되었습니다.

에러에 대한 프린트를 찍지 않은 이유도 operateGame 내부에서 이미 예외처리를 해서 추가적으로 더 처리해줄 필요가 없다고 생각해서 적지 않았었습니다..!

2022-04-19 06:29 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if 0...3 ~= userInput {
~= 이라는 코드는 제가 작성했는데 "0 부터 3 사이의 값이라면 true" 라는 의미로, 즉 기능요구 사항에서 유저가 정상적인 입력값을 입력 했을 떄를 한번에 표현하고 싶어서 작성했습니다. 
매직넘버라는 개념을 잘 몰라서 0...3이라고 표현 했는데 이렇게 보니 0이 어떤걸 나타내는지 확실히 다른 사람이 본다면 알 수 없을것 같다고 생각이 들었습니다. 
if를 통과하고 함수가 정상적으로 종료되면 그다음 이 함수를 호출한 부분에서 그 다음 기능을 수행하고 아니라면 재귀로 다시 게임을 처음부터 시작하게 하려고 했었는데, 코멘트 읽어보고 생각해보니 이렇게 처리한다면 guard를 사용하는게 더 깔끔할 것 같습니다..!
다만 함수 전체가 불필요해서 위에 코멘트에 작성했듯이 삭제를 했습니다...

2022-04-19 06:32 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compare(my:RPS, computer:RPS) {
나의 선택과 컴퓨터의 선택을 비교하는 의미라고 생각해서 myChoice, computerChoice으로 변경하여 주었습니다.

2022-04-19 06:32 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compare(my:RPS, computer:RPS) {
띄어쓰기 수정완료했습니다.

2022-04-19 06:46 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("이겼습니다!\n게임종료")
enum guidanceMessage 를 만들어서 처리해 주었습니다.
반복되는 문구 출력에 재사용성을 높이는데 도움이 될것 같습니다. 감사합니다.

2022-04-19 06:47 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        myChoice = RPS.scissors
감사합니다!😄

2022-04-19 06:48 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func choiceMenu(number: String) {
매뉴를 선택하는게 아닌 가위바위보 중에 하나를 선택하는 게임을 진행하는 메서드 이라고 판단하여 메서드명을 operateGame 변경해 주었습니다.

2022-04-19 08:09 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func getComputerNumber() -> RPS {
ComputerValue라는 말은 조금 애매할 수 있다고 봅니다. 현재 이곳을 실제 가위바위보 게임이라고 했을 때, 무슨 말이 좋을까요?
Number, Value 이런 단어는 어쩌면 코드적 표현이지 않을까 생각도 드네요!
RPS game를 위키에서 보시면 가위,바위, 보에 대해 통합된 단어를 찾아볼 수 있습니다.
혹시 한번 찾아보실까요?

2022-04-19 08:12 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if 0...3 ~= userInput {
생각하신 방향은 매우 좋은 것같습니다! 설계할 때 그런 생각을 통해 더 다양한 코드가 나올 수 있는거같네요! 잘하셨습니다👍
말씀하신 것처럼 if문에서 아무것도 없는 것보다 다른 방식으로 처리했다면 더 깔끔한 코드가 되지않았나싶어요!
하지만, 전체적으로 새로운 시도와 그에 합당한 이유는 맘에듭니다 🔥

2022-04-19 08:14 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compare(my:RPS, computer:RPS) {
Choice라면 나의 초이스? 컴퓨터 초이스? 이렇게 생각하잖아요! 그럼  그 초이스가 무엇일까요? `compare(myChoice: ?? , computerChoice: ??` 이렇게만 보았을 때 어떤 것을 비교하는지 파악이 가능한가요?
아까 number, value에 대한 코멘트와 비슷합니다. 좀더 구체적으로 그리고 이 게임에 적절한 네이밍이 필요할듯싶습니다!

2022-04-19 08:22 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("이겼습니다!\n게임종료")
guidanceMessage라는 문구가 안내 메시지? 라는 말로 파악해도되나요?  제 생각에는 어떤 메시지들을 가지고 있는지 파악하기 어려운데 네이밍 수정을 해볼까요?

2022-04-19 08:39 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case none = -1
만약 none를 사용하고 싶으시다면, 이 열거형에서 들어가기 적절하지 않는 것 같습니다. 열거형 이름이 RPS인데 그곳에 none이 있는 것은 매칭이 안됩니다. 열거형 네이밍을 바꾸거나 none을 다른곳으로 옮기는 것을 생각해볼까요?

2022-04-19 08:44 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func choiceMenu(number: String) {
의미 파악은 잘된거같습니다! 현재 메서드에서 compare 메서드까지 호출하다보니 조금 복잡해보이네요! 그래서 네이밍에 대해 operateGame이 몬가 적절한가 싶습니다..! 그래서 컴퓨터, 유저의 가위바위보만 갖고 다른 곳에서 compare하는 것을 생각하면 조금 네이밍이 쉬워질거같은데 만약 시간이 부족하다면 이 내용은 다음 스텝에서 생각해봐도 좋을것같네요!

2022-04-19 08:49 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
import Foundation 에 대해 설명해주세요!

2022-04-19 11:14 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
데이터 타입 객체(String 등), 콜렉션, os단에서 제공하는 기능(URL 등)을 사용할 때 import 해야 하는 라이브러리로 이해하고 있었습니다. 다만 String객체에서 구현된 메소드 등을 사용할 줄 알고 코드 작성중에 삭제하지 않았는데 완성 코드에서 기능을 사용하지 않아 삭제했습니다..!
Foundation을 찾아보면서 알게된점으로는 xcode4.x 이상부터는 Enable Foundation Assertions이라는 프로퍼티가 빌드 세팅에 들어가서 import를 따로 하지 않아도 타입 객체의 메소드를 사용할 수 있는 것 같았습니다. 
여기서 궁금한 점이 생겼는데 String의 components 메소드는 foundation을 import하지 않으면 사용이 안되는게 확인이 되었는데 `Int.random(1..3)` 이 메소드는 사용이 잘 되었습니다. 구현부를 찾아보고 싶었는데 도저히 못찾겠는데 Integer는 Foundation에 구현이 되어있는게 아닌걸까요?

2022-04-19 11:56 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case none = -1
최초에 유저의 RPS(입력한 가위바위보 enum값) 변수를 선언하고 switch문을 통해서 초기화를 해주려고 했습니다. 다만 Optional로 만들지 않아서 switch 문에서 옵셔널 바인딩을 하면 이중 들여쓰기가 될 것 같아서 가위바위보를 하기 위한 준비 단계라는 none값, 즉 아직 RPS값이 정해지지 않은 상태라는 의미로 none을 생성하였습니다. 
다만 하면서 RPS라는 enum의 naming을 다시 생각해 보니 가위, 바위, 보 라는 세가지 값만 있는게 맞다고 다시 생각이 들었습니다.

따라서 none을 없애기 위해 none이 사용 된 두 부분 1. 컴퓨터의 랜덤한 값 리턴부분 2. 사용자의 RPS값 초기화 부분 
이렇게 두군데서 사용이 되고 있어서 두 부분 모두 옵셔널 바인딩을 통해서 예외처리와 값 대입을 하도록 코드를 리팩토링 했습니다. 
추가로 재귀의 형태로 돌아가는 중간에 0값은 바로 코드가 종료되어야 해서 기존 switch문에서 확인하던 게임종료부분은 `operateGame` 부분의 상단에서 예외처리로 넣어 주었습니다.

2022-04-19 12:05 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func choiceMenu(number: String) {
operate 보다 play게임을 한다 라는게 더 자연스러울 것 같아 playGame으로 메서드명을 변경해 봤습니다. 게임이 시작되고 컴퓨터와 유저가 각각 어떤 동작을 할지 정한뒤 비교하는 메서드 이므로 play가 맞다고 생각했습니다.

2022-04-19 12:18 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func getComputerNumber() -> RPS {
위키에서 찾아보니 Rock Scissors Paper game 에서 손의 형태에 따른 개념을 HandDesign 이라는 단어로 표현하는것 같아 value대신 HandDesign으로 변경해보았습니다.

2022-04-19 12:21 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compare(my:RPS, computer:RPS) {
위에 말씀주신것처럼 이 부분도 "나"와 "컴퓨터"의 **무엇**을 비교하는지 알 수 없는 것 같아 이부분도 통일감을 넣기 위해 myHandDesign(내 가위바위보값) 과 같이 바꿔보았습니다.

2022-04-19 12:21 UTC, yusw10 commented on README.md
> +![RPSFlowChartv1](https://user-images.githubusercontent.com/39454792/163807587-2056a952-5beb-4ee0-95fe-dca56f694761.png)
이부분 변경하여 커밋올려놨습니다!

2022-04-19 12:22 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +
코드 컨벤션 전체적으로 확인해보았습니다..!

2022-04-19 12:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func choiceMenu(number: String) {
게임을 시작하고 결과가 나올때 까지 반복해서 "게임을 한다" 라는 의미로 playGame으로 다시 변경해보았습니다!

2022-04-20 00:20 UTC, merged

2022-04-20 03:51 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
![스크린샷 2022-04-20 오후 12 48 02](https://user-images.githubusercontent.com/52434820/164146541-e71f7d75-65a4-437b-88d0-0dcdc35e7e03.png)

![스크린샷 2022-04-20 오후 12 47 28](https://user-images.githubusercontent.com/52434820/164146545-2a117e15-e9a5-4b73-8519-0dd059e1f32e.png)

![스크린샷 2022-04-20 오후 12 44 48](https://user-images.githubusercontent.com/52434820/164146549-404f0d1b-7ff4-44ba-9b1b-92546c5f291c.png)

이렇게 보았을 때 왼쪽 상단을 보시면 어떤 식으로 이것들이 파생된 것인지 볼 수 있습니다.
그래서 Integer도 검색해보시면 이것이 스위프트 내장 라이브러리 인지, Foundation에 있는지 파악하실 수 있습니다!
Xcode에서 cmd + shift + 0(숫자) 클릭하셔서 검색한번 해보세요!

2022-04-20 03:52 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
만약 내부 구현을 더 파헤쳐 보고 싶다면, Swift github이나 xcode에서 커멘트 누르고 원하는 것을 누른 다음 Jump to definition 들어가면 내부 코드를 확인하실수있습니다!