묵찌빠 게임 [STEP2] seohyeon2, KayAhnDS
yagom-academy/ios-rock-paper-scissors pull request #139
Opened 2022-04-19 11:56 UTC by KayAhnDS

@dnwhd0112 

안녕하세요 우롱차!
seohyeon2, KayAhnDS 입니다.
묵찌빠 게임 STEP2 PR 요청 드립니다!

## 📖 페어 프로그래밍 중 고민한점 및 해결한 점

- 처음엔, 가위바위보에서 사용하는 compareTwoNumber함수, 묵찌바에서 사용하는 compareMJPTwoNumber함수를 각각 구현했다가 winningCase 외 내부 구조가 모두 동일한 점을 파악하여 어떻게 하나의 함수로 구현할까 고민했습니다. 결국, 열거형을 이용해 각각 가위바위보와 묵찌빠의 winningCase를 열거하고 compareTwoNumber함수의 매개변수로 넣어주는 것으로 해결 했습니다.
- 구조체와 클래스 중 어떤것을 사용해 객체를 생성 해야 하는지 고민하던중 상속이 필요없다는 점과 인스턴스를 넘겨줄때 참조를 넘겨주는 코드가 없을 것으로 판단되어 구조체를 사용했습니다.
- 객체가 자신의 turn을 프로퍼티로 갖게 함으로써, doTurnChange()함수에서 특정 상황에 따라 자신의 속성을 바꾸어 게임의 진행이 쉽게 이뤄지도록 구현 했습니다.
- 외부에서 몰라도 되는 객체의 프로퍼티는 private로 접근 제어 했습니다. 그리고 필요한경우 구조체내 이름에 접근하는 함수를 만들어 사용 했습니다.
- 스텝1에서 말씀해주신것처럼 함수로 뺄 수 있는 코드는 빼주고 묶어줄 수 있는 것들은 묶어주는데 많은 시간을 할애했습니다.

## 📖 새로 배운 것

```swift
if let verifiedUserInput = Int(userInput) {
        switch verifiedUserInput {
        case _ where verifiedInputCases.contains(verifiedUserInput):
            selectedNumber = verifiedUserInput
        default:
            selectedNumber = ExceptionalInput.wrongInput.correspondingNumber
        }
    }
```
- case안에 조건이 너무 많아 알려주신 caseIterable을 사용하여 where이후의 조건을 짧게 표현해 보았습니다!
<br>
<br>

2022-04-19 14:28 UTC, dnwhd0112 requested changes
수고하셨습니다!
처음엔, 가위바위보에서 사용하는 compareTwoNumber함수, 묵찌바에서 사용하는 compareMJPTwoNumber함수를 각각 구현했다가 winningCase 외 내부 구조가 모두 동일한 점을 파악하여 어떻게 하나의 함수로 구현할까 고민했습니다. 결국, 열거형을 이용해 각각 가위바위보와 묵찌빠의 winningCase를 열거하고 compareTwoNumber함수의 매개변수로 넣어주는 것으로 해결 했습니다.
구조체와 클래스 중 어떤것을 사용해 객체를 생성 해야 하는지 고민하던중 상속이 필요없다는 점과 인스턴스를 넘겨줄때 참조를 넘겨주는 코드가 없을 것으로 판단되어 구조체를 사용했습니다.
객체가 자신의 turn을 프로퍼티로 갖게 함으로써, doTurnChange()함수에서 특정 상황에 따라 자신의 속성을 바꾸어 게임의 진행이 쉽게 이뤄지도록 구현 했습니다.
외부에서 몰라도 되는 객체의 프로퍼티는 private로 접근 제어 했습니다. 그리고 필요한경우 구조체내 이름에 접근하는 함수를 만들어 사용 했습니다.
-> 저도 이거 굉장히 햇갈렸는대 단순 리턴하는 프로퍼티들은 private(set) 으로 하는 편이에요. 메소드로 단순히 리턴을 해준다면 결국 외부에 노출이 되는거랑 다름 없지 않은지 생각이 들더라구요. 이부분은 조금 더 고민해보세요!
스텝1에서 말씀해주신것처럼 함수로 뺄 수 있는 코드는 빼주고 묶어줄 수 있는 것들은 묶어주는데 많은 시간을 할애했습니다.
-> 스텝1에서 훌륭하게 묶어주셨는대 step2에서 작성한 코드는 묶어주지 않아주셔서 아쉬웠습니다.

2022-04-21 04:37 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
>      if let verifiedUserInput = Int(userInput) {
만약 가위바위보 단계라면 에러메세지를 출력하고 다시 입력받습니다.

묵찌빠 단계라면 에러메세지 출력 후, 컴퓨터의 턴으로 넘어가 사용자의 입력을 다시 받습니다.


그 이유는 checkUserInputNumber 함수의 첫 줄에 있습니다 ☺️

checkUserInputNumber의 반환값인 selectedNumber의 초기값을 에러메세지를 출력하는 번호로 해놨습니다. 

만약 입력값이 Int로 변환하지 못한다면, 그대로 초기값이 반환됩니다.

이 값은 175번째 userRPSInput 상수의 값으로 들어갑니다.

176번째처럼 userRPSInput의 값이 잘못된 입력값이라면 에러메세지 출력 하고

다시 사용자의 입력을 받게 continue를 수행합니다!

2022-04-21 04:59 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var correspodingMJPNumber: Int {
MuckJjiPpa 축약어 였습니다..😂 MuckJjiPpa로 수정 했습니다!

2022-04-21 04:59 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
넵 축약어 수정 완료 했습니다~

2022-04-21 05:45 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
위에 두 함수 삭제 후, 알려주신 private(set) 사용하여 수정했습니다!
우롱차 덕분에 또 한번 새로운 기능을 알게 되네요! 감사합니다.

한가지 궁금한 점이 있다면,
함수로 생성하는 것과  private(set)으로 처리하는 것 둘다
값을 반환해주는 기능만 하는 것이라 큰 차이가 없다고 생각이 듭니다.
그럼에도 함수를 생성하는 것보다 private(set)으로 처리하는 걸 선호하시는 이유가 무엇인가요?!😯

2022-04-21 06:25 UTC, KayAhnDS commented on RockPaperScissors/RockPaperScissors/main.swift
> +            doTurnChange()
startMJPGame()내 이미 doTurnChange(), printErrorMessage() 함수처럼 묶어줄수 있는 부분들은 묶어주었고, continue와break가 나오는 곳들은 오히려 함수로 묶어주는것이 나중에 더 큰 혼란을 가져올 수 있다고 생각하여 함수로 묶지 않았습니다.

2022-04-21 06:27 UTC, seohyeon2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +struct Player {
상속이 필요한 경우에 class를 사용하고, 그 외에는 struct 사용을 권장하는 것으로 알고 있습니다!
둘의 차이점은 위와 같이 상속 가능 여부가 있습니다.
또 class는 참조타입, struct는 값 타입으로 타입이 다르다는 점이 있습니다.

피드백 대로 비슷한 기능끼리 묶어 여러 파일들로 분리해보았습니다☺️

2022-04-21 06:33 UTC, KayAhnDS commented
@dnwhd0112

안녕하세요 우롱차!
seohyeon2, KayAhnDS 입니다.
묵찌빠 게임 STEP2 리리뷰-요청 드립니다!

## 수정한 부분

- main.swift 파일에 있던 함수들, 구조체 등등을 분류해서 기능에 맞게 생성하고 나눠 주었습니다.
- private(set)을 이용해서 기존에 func retrievePlayerName()를 제거 했습니다.
- MJP라는 축약어를 MuckJjiPpa로 수정 했습니다.
- 마지막엔 전체적으로 줄일수 있는 코드는 줄여주고 불필요한 코드는 삭제하면서 수정을 마쳤습니다. 감사합니다!
<br>

2022-04-22 07:04 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +struct Player {
ㅎㅎㅎ 맞습니다! 하지만 이유가 좀 더 있어요! 자세한건 공식문서에서 한번 찾아보세요!
참조타입과 값타입의 차이는 알고 계시죠???

2022-04-22 14:18 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            doTurnChange()
오... 함수로 묶어주면 왜 더 큰 혼란을 가져올 수 있나요???

2022-04-22 14:22 UTC, dnwhd0112 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
일단 함수를 생성해서 처리를 하게 되면 코드의 수가 늘어나죠!
그리고 우리가 함수를 사용해서 사용하는 이유가 외부에서 감추기 위함인대 함수로 단순히 값을 리턴한다면 그건 정말 감춘게 맞나요???
이 부분은 하시면서 느끼실수 있으실꺼에요! 외부에서 사용할때 instance.value 를 쓰는것과 instance.Value()를 쓰는것중 어느것이 더 편한지!

2022-04-22 14:23 UTC, merged