묵찌빠 게임 [STEP2] unchain123, borysarang
yagom-academy/ios-rock-paper-scissors pull request #142
Opened 2022-04-20 08:00 UTC by yusw10

묵찌빠 게임 [STEP2] borysarang, unchain123
=====
@kimkyunghun3 
###### tags: PR

### 기능구현
기존에 구현해 놓은 가위바위보 게임의 코드를 재사용하면서 묵찌빠 코드를 작성하였습니다.
- `startMukChiBaGame`: 최초 가위바위보로 승자가 정해진 후 묵찌빠를 실행시키는 함수
- `playMukChiBaGame`: 묵찌빠를 진행하기 위해 사용자 입력을 검증하고 compareMukChiba를 실행 시키는 함수
- `compareMukChiBa`: 사용자와 컴퓨터의 가위바위보 값과 턴을 받아서 결과를 도출하는 함수, 승리가 나지 않는다면 재귀적으로 다시 startMukChiBaGame을 실행시킨다.
- `Winner`: 승자가 턴을 가져오므로 누가 승자인지 넘겨주기 위한 열거형 타입

### 고민한점

이전 STEP1을 구현하면서 네이밍관련 고민을 많이 했었기에, 이번 STEP2를 진행할 때는 미리 어떤 변수명들을 사용해야 할지 시작전에 서로 이야기를 많이 나누었습니다. RPS라는 값도 Rock-Paper-Scissors에서 차용하였기에 직접 만든 내용이었는데, 묵찌빠는 대응되는 영어 단어도 존재하지 않았기에(위키에서 한국의 민속놀이라는 것을 보고 처음 알았습니다) 영어로 직접 mukchiba라고 사용하게 되었습니다.

STEP2 플로우 차트를 구성하면서 미리 필요한 함수들을 정리해보았습니다. STEP1에서 구현한 코드를 보면서 flowchart에 어떤 함수를 쓸지 생각해보는데 기존에 가위바위보를 구현하면서 구현한 코드를 재사용 할 수 있었습니다. 그래서 STEP2를 진행하면서 재사용성에 대해 다시 생각해 볼 수 있었습니다. 

![](https://i.imgur.com/ObIBvfb.png)

2022-04-20 10:48 UTC, kimkyunghun3 requested changes
프로젝트하시면서 고생많으셨습니다!🔥
제가 요구한 것도 많고, 리뷰도 많이 해서 혹시나 부담스러우실 수도 있다고 생각했는데 바로 대응을 잘해주셔서 보기 좋았습니다.

코드를 보니 확실히 고민한 흔적도 많이 보이고 네이밍도 지속적으로 이해하기 쉽게 작성하려고 노력한 것을 볼 수 있었습니다.

커밋단위도 대부분 명확해서 단위별로 무엇을 했는지 알 수 있었습니다. 하지만 일부 커밋에서는 커밋명과 다른 작업들도 포함되어 있어서 이 부분은 다음 프로젝트부터는 조심해서 분리해주시면 더 좋을 것 같네요 🙂

컨벤션도 이번 PR 보면서 꼼꼼하게 잘 살펴보셨다는게 보였습니다. 그래서 이번 PR에는 컨벤션에 대한 언급이 필요없을 정도로 잘해주셨습니다  앞으로도 이렇게 해주시면 좋을 것 같네요! if  조건문이나 return 컨벤션은 사람마다 다를 수 있기 때문에 자신만의 기준을 두고 있으시되 다른 분이 다른 기준을 가지고 있다면 협의하에 맞춰보는 것도 좋은 협업같네요!

2022-04-20 10:48 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
>  enum InformationMessage {
정보 메시지, 이곳에 포함되는 정보는 어떤 것들일까요? 조금 디테일한 네이밍을 해볼까요?

2022-04-20 10:48 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
전역으로 선언할수도있는데 열거형 내에 static 선언하는 이유와 장점이 무엇이 있을까요?

2022-04-20 10:48 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard number != "0" else {
“0” 이라는 것은 매직넘버이겠죠? 매직넘버는 지양해주세요!

2022-04-20 10:48 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                myHandDesign == RPS.paper && computerHandDesign == RPS.rock {
요거를 따로 빼거나, 스위치 문에서 튜플 활용한 방식으로 가독성 높이게 비교문을 변경할 수 있는데 이를 한번 해볼까요? 이것만 봤을 때 논리연산자가 많아서 가독성도 떨어지고 이해하기 어려울것같습니다!

2022-04-20 10:48 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    print("[\(winner) 턴] \(InformationMessage.startMukChiBaGame)", terminator: "")
한칸 띄어야 입력하는 곳이 한칸 띄어서 나올것같습니다!

2022-04-20 10:48 UTC, kimkyunghun3 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard number != "0" else {
이외에도 다른 매직넘버가 있는데 그 부분도 수정해볼까요?
Int.random 부분에도 있습니다!

2022-04-20 10:48 UTC, kimkyunghun3 commented on README.md
> +팀원: unchain123, borysarang
리드미 작성 좋군요!!! 아주 잘했습니다!!

2022-04-20 10:48 UTC, kimkyunghun3 commented on README.md
> +
고민한점이 더 있으셨지 않을까요? 고민한 부분 다 적으시면 좋을것같네요! 그리고 해결을 했다면 어떻게 해결했는지를 자세히 써주면 더 좋아요 :)

2022-04-21 05:07 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
>  enum InformationMessage {
GameGuideMessage 로 변경해 보았습니다.
게임을 안내하는 메세지라고 생각하였습니다.

2022-04-21 05:29 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
전역 변수로 선언하는 것은 메모리 할당에서 문제가 발생하기 쉽고 가독성과 신뢰성이 떨어집니다.
 nameSpace를 구성하기 위해 열거형으로 연관이 있는 항목끼리 묶어줌으로서 가독성과 신뢰성을 확보하고 초기화된 String값을 바로 출력하기 위해 사용했습니다.
 static으로 선언하게 되면서 싱글톤패턴이 되어 하나의 인스턴스에만 할당이 되어서 불필요한 메모리 사용을 줄일 수 있는 장점이 있습니다.

2022-04-21 05:42 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard number != "0" else {
매직넘버 부분 수정하기 위해 유저의 입력값인 "0","1","2","3" 부분을 따로 열거형으로 만들어 주었습니다.
Int.random값도 guard부분에서 따로 빼서 앞쪽에 변수로 선언하여 사용해보았습니당

2022-04-21 06:03 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                myHandDesign == RPS.paper && computerHandDesign == RPS.rock {
스위치문에서 튜플을 활용하여 변경해 보았습니다.

2022-04-21 07:00 UTC, unchain123 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    print("[\(winner) 턴] \(InformationMessage.startMukChiBaGame)", terminator: "")
넵 수정 했습니다.

2022-04-21 07:27 UTC, yusw10 commented on README.md
> +
STEP2 추가 및 생각했던 부분 좀 더 적어보았습니다.!

2022-04-21 10:18 UTC, kimkyunghun3 commented
마지막 수정까지 잘하셨네요! 힌트만 드려도 잘 해결해주셔서 보는 제가 뿌듯했습니다👍
지금처럼 고민하며 코드 짜시면 앞으로 프로젝트도 잘 하실 수 있을 것 같습니다!

마지막으로 커밋명만 통일되게 해주셨으면 좋겠습니다~
refactoring, fix, renamed 모두 다른 방식의 커밋명이라 처음 보았을 때 이게 차이점이 존재하는건가 싶었습니다!
다음에는 통일되게 커밋하시면서 진행하면 좋을거같습니다 😄

2022-04-21 10:29 UTC, merged