묵찌빠 게임 [STEP2] bradheo65, Hugh
yagom-academy/ios-rock-paper-scissors pull request #143
Opened 2022-04-21 06:05 UTC by bradheo65

안녕하세요 @Kim-TaeHyun-A Step02 첫번째 PR보냅니다.

## 고민했던점
Step01에서 재귀함수로 코드를 작성해 보았는데 Step02에서는 반복문으로 변경 후에 코드 작성했습니다.
기존에 Step01에서 작성한 코드가 확인해보니 제대로 된 재귀함수가 아니였던 것 이였습니다. 그렇게 생각한 이유는 실행 시 첫 스택에 생성된 함수에서 결과가 나오고 종료되는 것이 아니라 중간에 결과가 나오는 것으로 보아 재귀함수를 제대로 사용 못 한걸로 판단하여 Step02에서는 반복문으로 수정했습니다. 

Step02에 대해서 생각해보니 기존에 Step01에서 작성한 함수를 활용하기 위해 class 상속을 이용하여 코드를 작성해보았습니다.
묵찌빠 게임에서 누구의 턴을 알기위해 저장속성과 계산속성을 이용해 코드를 작성해 보았습니다.

- Step01 struct
```swift
struct RockPaperScissorsGame {
}
```

- Step02 class
```swift
class rockPaperSissorsGam {
}

class MukjjibbaGame: RockPaperScissorsGame {
}
```

가위, 바위, 보, 묵, 찌, 빠의 매직넘버를 열거형을 사용해서 표현해 보았습니다.

- ex) 가위, 바위, 보 게임
```swift
enum RockPaperScissors {
    case rock
    case scissors
    case paper
    case end
}

extension RockPaperScissors {
    var theNumberOfCase: String {
        switch self {
        case .scissors:
            return "1"
        case .rock:
            return "2"
        case .paper:
            return "3"
        case .end:
            return "0"
        }
    }
}
```

2022-04-21 10:14 UTC, Kim-TaeHyun-A requested changes
`안녕하세요! 브레드, 휴😀`

`
타입을 만들고 상속을 사용하려는 시도는 좋았지만 방식이 조금 잘못된 것 같아 아쉽습니다.🤔
프로젝트의 수행에 앞서 공식문서 꼭 읽어주시고 핵심 경험을 수행을 꼭 수행하셔야 합니다.`

# **고민했던점**

Step01에서 재귀함수로 코드를 작성해 보았는데 Step02에서는 반복문으로 변경 후에 코드 작성했습니다.기존에 Step01에서 작성한 코드가 확인해보니 제대로 된 재귀함수가 아니였던 것 이였습니다. 그렇게 생각한 이유는 실행 시 첫 스택에 생성된 함수에서 결과가 나오고 종료되는 것이 아니라 중간에 결과가 나오는 것으로 보아 재귀함수를 제대로 사용 못 한걸로 판단하여 Step02에서는 반복문으로 수정했습니다.

`재귀함수는 무엇이라고 생각하시나요🤔`  

`결과가 중간에 나오는 것이 왜 재귀함수가 아닌가요?`

`정의를 다시 찾아보는 것을 좋을 것 같습니다! 구글에서 재귀함수라고 검색하고 예제를 확인합시다!`

Step02에 대해서 생각해보니 기존에 Step01에서 작성한 함수를 활용하기 위해 class 상속을 이용하여 코드를 작성해보았습니다.묵찌빠 게임에서 누구의 턴을 알기위해 저장속성과 계산속성을 이용해 코드를 작성해 보았습니다.

`함수의 재사용성을 위해 상속을 선택하는 것은 이상한 것 같아요. 상속으로 함수가 재사용될 수 있지만 재사용을 위해서 상속을 하면 안됩니다.`

`상속은 무엇이고 왜 할까요?`

`힌트 : 공통점을 생각하면서 일반화를 진행하죠🤔 묵찌빠 게임과 가위바위보 게임의 공통점은 무엇일까요?`

- Step01 struct

```
struct RockPaperScissorsGame {
}
```

- Step02 class

```
class rockPaperSissorsGam {
}

class MukjjibbaGame: RockPaperScissorsGame {
}
```

가위, 바위, 보, 묵, 찌, 빠의 매직넘버를 열거형을 사용해서 표현해 보았습니다.

- ex) 가위, 바위, 보 게임

```
enum RockPaperScissors {
    case rock
    case scissors
    case paper
    case end
}

extension RockPaperScissors {
    var theNumberOfCase: String {
        switch self {
        case .scissors:
            return "1"case .rock:
            return "2"case .paper:
            return "3"case .end:
            return "0"
        }
    }
}
```

`열거형에 대한 공식문서 읽어주세요!`

2022-04-22 03:22 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/GameCondition.swift
> +}
아래의 코드로 구조와 네이밍을 변경해 보았습니다.
```swift
enum RockPaperScissors: String {
    case scissors = "1"
    case rock = "2"
    case paper = "3"
}

extension RockPaperScissors {
    var hand: String {
        switch self {
        case .scissors:
            return RockPaperScissors.scissors.rawValue
        case .rock:
            return RockPaperScissors.rock.rawValue
        case .paper:
            return RockPaperScissors.paper.rawValue
        }
    }
}
```
이런 열거형 코드가 티아나가 말씀해주신 방향이 맞는지 궁금합니다!

2022-04-22 03:24 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
Foundation 프레임워크가 데이터처리를 위해 필요하기 떄문에, RockPaperScissorsGame 파일로 이동했습니다.

2022-04-22 03:26 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        let allright: [String] = ["1", "2", "3", "0"]
allright -> fitNumber로 변경해보았습니다.
```swift
    func isFitNumber(from inputData: String) -> Bool {
        let fitNumber: [String] = ["1", "2", "3", "0"]
        
        if fitNumber.contains(inputData) {
            return false
        } else {
            return true
        }
    }
```

2022-04-22 03:26 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/GameCondition.swift
> +//
네 통일 했습니다.

2022-04-22 03:27 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/GameCondition.swift
> +    case end
새로운 열거형을 만들어서 rock, scissors,paper와 end를 분리했습니다.

2022-04-22 03:29 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    }
열거형을 사용해서 사용자와, 컴퓨터를 생성했고, 옵셔널을 사용해보았습니다.
```swift
    var currentTurn: String? {
        switch gameResult {
        case win:
            return user
        case lose:
            return computer
        default:
            return nil
        }
    }
```

2022-04-22 03:31 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +        super.startGame()
해당 프로그램에서 묵찌빠 게임을 실행시키기 위해선 가위바위보게임의 startGame() 함수를 호출해서 진행을 해야하기 떄문에 사용했습니다.
혹시 티아나는 어떤 방식을 생각하고 계시는지 궁금합니다.

2022-04-22 03:32 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    }
set 을 is으로 변경해서 Bool 타입에 어울리는 함수명을 재작성 해보았습니다.
`func isMukjjibbaResult(userInput: String, randomNumber: String) -> Bool {`

2022-04-22 03:33 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    func getTurn(_ userInput: String, with randomNumber: String) {
getTurn -> setMukjjibbaRule 변경해 보았습니다.
`func setMukjjibbaRule(_ userInput: String, with randomNumber: String) {`

2022-04-22 03:36 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +            }
자기 타입 내에 속성을 명확하게 가르키기 위해 셀프를 사용 했었지만 없어도 코드가 동작하는데 지장이 없어 제거 했습니다.
if문은 switch문으로 변경했습니다.
```swift
        switch userInput {
        case scissors:
            if randomNumber == rock {
                gameResult = lose
            } else if randomNumber == paper {
                gameResult = win
            }
        case rock:
            if randomNumber == paper {
                gameResult = lose
            } else if randomNumber == scissors {
                gameResult = win
            }
        case paper:
            if randomNumber == scissors {
                gameResult = lose
            } else if randomNumber == rock {
                gameResult = win
            }
        default:
            break
        }
```

2022-04-22 03:37 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +            }
논리 연산자를 사용해 간결하게 개선했습니다.

2022-04-22 03:38 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    func choiceRockPaperScissors() {
choice를 select로 변경했습니다.
`func selectRockPaperScissors() {`

2022-04-22 03:38 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          let numberList: [String] = ["1", "2", "3"]
numberList를 numberOfCase로 변경했습니다.
`let numberOfCase: [String] = ["1", "2", "3"]`

2022-04-22 03:39 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        self.userNumber = userInput
유저가 입력 시 실수로 공백을 입력해도 제거 해주는 기능을 넣어보았습니다.

2022-04-22 03:40 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +            }
위에서 제시한 방법으로 switch문으로 수정해보았습니다.

2022-04-22 03:42 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    func checkRockPaperScissorsRule(from inputData: String) {
함수명과 저장속성을 제거하고 함수 return 값을 Bool타입으로 해주었습니다.
```swift
    func isFitNumber(from inputData: String) -> Bool {
        let fitNumber: [String] = ["1", "2", "3", "0"]
        
        if fitNumber.contains(inputData) {
            return false
        } else {
            return true
        }
    }
```

2022-04-22 03:51 UTC, bradheo65 commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    private var endGame: String = Mukjjibba.end.theNumberOfCase
티아나의 답변에 대한 의도가 가위바위보게임의 열거형과 묵찌빠게임의 열거형의 값이 같아서 하나로 묶어서 사용해보는게 어떤지 의 의도가 맞나요..?😳🤔
저의의 생각은 열거형 활용시에 가독성이 더 좋아진다고 생각해 각각 만들어 주었습니다.
더 좋은 방법이 있으면 알려주세요!!

2022-04-22 03:53 UTC, bradheo65 commented
상속시 부모클래스의 속성과 메서드를 활용할 수도 있어 사용을 해보았고, 그렇게 생각한 이유는 묵찌빠게임도 결국 가위바위보게임의 일부라고 생각을 해서 상속한 후 좀 더 구체적인 기능과 속성을 추가해 코드를 작성했습니다.

2022-04-22 05:08 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +            }
```swift
func findGameResult(computerValue: RockPaperScissors, userValue: RockPaperScissors) -> GameResult {
    switch (computerValue, userValue) {
    case (.rock, .paper), (.scissors, .rock), (.paper, .scissors):
        return .win
    case (.scissors, .paper), (.rock, .scissors), (.paper, .rock):
        return .loss
    case (.rock, .rock), (.scissors, .scissors), (.paper, .paper):
        return .tie
    }
}
```
위와 같은 메서드를 만들어서 활용하는 것은 어떨까요🤔

2022-04-22 05:09 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        self.userNumber = userInput
그러면 이 메서드가 유저의 입력도 받고 실수도 처리하는 2가지의 역할을 하는 것 아닌가요🤔

2022-04-22 05:12 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
>          let numberList: [String] = ["1", "2", "3"]
case를 사용한 이유가 뭔가요? 이 숫자들의 목적이 무엇인가요? `의도한목적numbers`로 수정해볼까요?
의도한 목적 부분은 형용사형으로 해주세요~

2022-04-22 05:17 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +            }
gameResult != win && gameResult != lose 로 바꾸셨네요
gameResult가 enum 타입이라면 더 간결한 방식으로 바뀔 것 같네요🤔
win이나 lose가 아니면 tie겠죠?

2022-04-22 05:19 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +            }
switch문에 if가 있다면 가독성이 더 안좋은 것 같네요🤔
switch문의 각 case에서의 들여쓰기는 안됩니다.
case의 실행문은 간결한 형태를 가지도록 해주세요!

2022-04-22 05:24 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    func getTurn(_ userInput: String, with randomNumber: String) {
"묵찌빠의 규칙을 정한다"로 이해됩니다.
두 분이 생각하기에는 가위바위보를 하는 것의 목적(기능)이 "규칙" 정하기인가요?

2022-04-22 05:33 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +        super.startGame()
가위바위보 게임의 묵찌빠 게임의 일반화된 형태라는 것이 어색해 보였답니다.
게임이라는 타입의 하위 타입으로 두 게임이 있는 것 같아요.
중복을 줄이기 위해 상속을 했다고 하셨는데 중복된 부분이 존재한다면 어딘가에서 잘못된 것이 아닐까요?
상속했지만 여전히 유사한 형태를 보이네요.

두 분이 생각하신대로 상속관계라고 해도 startGame()의 super의 호출은 순차적으로 게임이 실행되는 것을 대체하는 것으로 보이는데요.
차라리 다른 곳(별개의 타입)에서 호출을 두 번 하는 것은 좋을 것 같다고 생각했답니다🤔
또는 프로퍼티로 가위바위보를 가지는 것이 좋을 것 같습니다🤔

2022-04-22 05:37 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    private var endGame: String = Mukjjibba.end.theNumberOfCase
묵찌빠 타입을 enum으로 만들었는데 굳이 String으로 프로퍼티를 만들 필요가 있을까요?
이 프로퍼티가 존재하는 것도 어색하다고 생각합니다.
게임이 이 프로퍼티를 꼭 가져야 하나요🤔
묵찌빠 속성이 해당 타입 내부에 있기를 원하시면 nested type으로 처리하는 것이 좋을 것 같습니다.

2022-04-22 05:39 UTC, Kim-TaeHyun-A commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        let allright: [String] = ["1", "2", "3", "0"]
컬렉션 타입의 네이밍은 마지막에 s를 붙이는 것이 자연스러워 보입니다🤔

2022-04-23 03:00 UTC, merged