묵찌빠 게임 [STEP 2] groot, yeton
yagom-academy/ios-rock-paper-scissors pull request #148
Opened 2022-04-21 13:44 UTC by yeeton37

@cherrishRed 
안녕하세요 레드
step2 PR 보냅니다!

저번 코멘트에서 여쭤보셨던 꼬리재귀에 대해 찾아보았습니다.
저희가 README에는 써주었는데 코멘트를 안 남겼네요...ㅠㅠ

- **꼬리재귀** : 재귀함수 사용 시 추가연산을 하지않고 함수를 끝내는 것
    - 일반적인 재귀함수는 함수를 호출할 때 연산정보를 스택에 쌓으며 계산을 한다. 꼬리재귀를 사용하면 스택에 쌓지 않고 바로 다시 함수를 실행시키는 방법을 사용한다.
    - 조건 : 컴파일러가 최적화를 지원하는지 확인 후 사용해야 함
    - 컴파일러가 최적화를 지원하면 내부적으로는 재귀 함수를 반복문으로 변경되어 실행이 된다. 따라서, Stack Overflow 에 대한 위험이 없다고 하는 것이다.
   
라고 정리해보았습니다.

저희가 이번 step2에서 가장 고민한 것은 연산 프로퍼티와 Bool타입 네이밍과 함수 단위의 분리였습니다.

1. 연산 프로퍼티

```swift
enum GameRockPaperScissorsChoice: Int {
    case end = 0
    case scissors = 1
    case rock = 2
    case paper = 3
    case error
    
    var number: Int {
        get {
            return self.rawValue
        }
    }
}
```

Red와 디스코드에서 이야기를 나눴습니다.
`rawValue`를 코드상에서 직접적으로 쓰면 그 rawValue가 Int인지 String인지 사용자가 알 수 없기 때문에 가독성을 좋게 하기 위해서 rawValue를 number라는 이름으로 대체해주면 좋을 것 같다는 피드백을 받고,
그러기 위해서 `enum(GameRockPaperScissorsChoice)` 안에서 연산 프로퍼티를 위와 같이 사용했습니다.
괜찮게 사용한 것일까요?

2. Bool type으로 된 튜플의 네이밍에 대해 고민했습니다.

3. 순서도만 보고 바로 코드로 구현한다음 어떻게 함수 단위로 분리할 것인지 고민했습니다.

처음 들여쓰기랑 함수 단위를 생각하지 않고 의식의 흐름대로 짜본 코드입니다. 
```swift
func 묵찌빠게임시작() {
    var computernumber: Int
    var userTurn: Bool = true
    while true {
        print("1~3중에 입력하세요, 0은 종료")
        var userinput = Int(readLine()!)!    // 인풋받는거는 함수가 될 수 있음
        computernumber = Int.random(in: 1...3)  // 검증하는거도 함수가 될 수 있음
        if userinput >= 0 && userinput <= 3 { 
            if userTurn == true {
                if computernumber == userinput {
                    print("사용자 승리")
                    break
                } else {
                    userTurn = false
                }
            } else {
                if computernumber == userinput {
                    print("컴퓨터 승리")
                    break
                } else {
                    userTurn = true
                }
            }
        }
    }
}
```

위와 같이 한번에 코드를 짠 후에 if-else 구문을 기준으로 함수단위로 분리해주었더니 훨씬 수월하게 함수로 분리할 수 있었습니다. 하지만 그 후에 매개변수를 받는 것을 생각하는 것이 너무 어렵더라구요. ㅜㅜ 이건 아마도 프로그래밍 경험을 더 많이 해봐야할 것 같습니다.

여기까지입니다.
잘부탁드립니다~✨

2022-04-21 19:58 UTC, cherrishRed requested changes
# 리뷰글 

private 을 붙이신 점 칭찬
mutating 이 무엇인지 어떤 메서드 인지 생각해 보기 

@Groot-94 @yeeton37
STEP2 수고하셨습니다!🥳

실력이 빠르게 성장하고 계시네요!

## 🥳 칭찬드리고 싶은점
* 모든 프로퍼티와 메서드의 캡슐화와 은닉화가 잘 진행된 것 같습니다. 
* 메서드 분리가 아주 잘 이루어졌습니다!
* 네이밍에서도 전보다 많이 고민하신 흔적들이 보였습니다.
* flow 적인 부분이 깔끔하고 출력되는 부분등 요구사항을 충실히 지켜주셨습니다!

## 🤔 고민한 점에 대한 답변

**1. 연산 프로퍼티**
>`경우 1` 구현되는 함수의 로직이 복잡할 때
>`경우 2` 호출이 error를 발생시킬 때
>`경우 3` 매 작업마다 다른 값을 반환할 때(프로퍼티 값이 변할 때) 주로 연산 프로퍼티를 사용한다고 정리해보았습니다.

라고 해주셨네요!
공부하신 내용이 약간의 오류가 있는 것 같네요. 
>`경우 1` 구현되는 함수의 로직이 복잡할 때
❗️오히려 복잡할 때 메서드를 쓰는 경우가 더 많습니다. 여기서 말하는 복잡함 이라는 것은 get 과 set 이 모두 필요할 때를 말하는 것 같습니다. 값을 프로퍼티에서 가져오려고 할 때, 그리고 변경도 하려고 할 떄 메서드로 구현하려면 2개의 메서드가 나오겠지만 연산 프로퍼티를 사용하면 get set 을 이용해서 한번에 만들어 줄수 있겠죠.

> `경우 2` 호출이 error를 발생시킬 때
> ❗️오히려 이럴 때 메서드를 씁니다. 

> `경우 3` 매 작업마다 다른 값을 반환할 때(프로퍼티 값이 변할 때)
> ❗️이럴 때 사용할 수 도 있겠지만, 이 자체가 연산 프로퍼티가 자주 사용되는 경우라고 하기엔 애매한 것 같네요😙

연산 프로퍼티가 처음 접할 때 조금 어렵습니다. 당연히 잘 와 닿지가 않을 수도 있어요. 
그래도 앞으로 쓸일도 많은 기본 개념이니, 연산 프로퍼티에 대한 공식 문서를 찬찬히 다시 읽어보시고 예제 같은 것도 여러번 따라해 보시면 감이 조금씩 오실 거예요!!

연산 프로퍼티에 대한 구현하신 부분은 너무 잘 하셨습니다!

**2. Bool type으로 된 튜플의 네이밍에 대해 고민했습니다.**
`(isUserTurn, isSameChoice)` 이 부분을 말씀하시는 것이 맞을까요?
이렇게만 사용해도 지금 아주 깔끔하다고 칭찬 드리고 싶어요! 

조금 더 명확하게 해주고 싶으시다면, 
[스위프트 랭귀지 가이드](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html) 의 튜플 부분을 읽어보시면 좋을 것 같습니다!
튜플에도 레이블을 달 수 있는 방법에 대해서 나와있습니다.

**3. 순서도만 보고 바로 코드로 구현한다음 어떻게 함수 단위로 분리할 것인지 고민했습니다.**
이 부분이 참 어려운 부분이고 말씀하신 대로 경험이 생기고 분리 하시는 연습을 계속 하면 쉬워 집니다. 

우선은 저렇게 코드를 작성하시고 나누는 방법도 괜찮지만, 조금 익숙해 지시면 flow 적인 개념을 이야기 할 때 부터 어느 정도로 함수를 나눌지 이야기 나누시고 구현하는 방법이 더 쉬울 수도 있습니다! 이미 짜논 플로우를 벗어나는 법이 어렵기 때문입니다. 

애기 해주신 대로 매개변수와 return 타입을 잘 활용할 줄 알게 된다면 이점이 정말 많습니다!
조금 지나면 배우시겠지만 스위프트에서 함수는 1급 객체이기 때문에 파라미터로 함수 자체를 받을 수도 있고 함수자체를 리턴해 줄 수도 있습니다. 이러한 장점들을 잘 이용하면 전역 변수의 수도 줄일 수 있고 다양한 장점이 많습니다. (전역 변수를 줄이는 것이 왜 좋은지 찾아보시면 좋을 것 같아요.)

앞으로 모든 프로젝트에서 이 부분에 대한 연습을 계속 해서 하게 되실 것이기 때문에 계속 인지하고 연습하다보면 분명 실력이 금방 늘을 것이라고 장담 합니다. 😉 너무 걱정하지 마세요.


## 📌 추가적으로 드리고 싶은 말씀

**꼬리재귀**
꼬리재귀에 대해서 잘 조사하셨네요!
꼬리재귀를 구현한 다음에 컴파일러가 최적화를 진행해주기 위해서는 최적화 설정을 켜주어야 합니다. 
Buliding settign 에 Optimization Level 의 Debug 와 Release 부분을 설정해 주면 됩니다. 
이해가 잘 안가시면 아래 링크 달아 드린 글에서 화면 사진을 보세요!
[xcode 에서 컴파일 최적화 설정하기](https://velog.io/@cherrish_red/iOS-컴파일-최적화-feat-꼬리재귀)

**객체 나누기**
지금은 `Game` 이라는 객체가 모든 것을 관리하고 있는 것 처럼 보이네요. 
Game 이라는 큰 카테고리에 저 값들이 다 연관이 있는 값이긴 하지만, 한 객체의 코드가 너무 길다 보니 조금은 읽기 힘들 수도 있을 것 같습니다. 객체를 관련 있는 것들끼리 조금은 분리 해 보는 것은 어떨까요? 

**제목 커밋 글자수 제한하기**
![](https://i.imgur.com/AD79AY0.png)
한 줄에 제목이 다 보이지 않아 ... 으로 표시되게 됩니다. 한 눈에 모든 텍스트를 확인할 수 있도록 글자 수를 제한 해주시면 좋을 것 같습니다!

나머지 이야기들은 제가 코멘트로 모두 달아 두었습니다!

## 😗 추가적인 질문
이 질문들에 답을 달아 주세요!

* mutating 을 많이 사용하셨는데, mutating 은 어떨 때 쓰는 것일까요? 메모리적으로 mutating 을 붙이면 무슨 일이 일어날까요? 
* 예톤과 그루트가 STEP2를 진행하면서 객체를 여러개 만들었는데, 코드를 짜면서 개인적으로 느낀 객체를 만들었을 때의 장점 또는 단점은 무엇인가요?

2022-04-22 07:28 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/GameCollection/GameRockPaperScissorsChoice.swift
> +    case error
수정했습니다!

2022-04-22 07:28 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/GameCollection/GameStatus.swift
> +    }
감사합니다!🥹

2022-04-22 07:55 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +extension Game {
extension은 클래스, 구조체, 열거형 또는 프로토콜 유형에서 기존의 소스코드의 수정없이 새로운 기능을 추가하기 위해서 사용하는 확장된 객체 ? 라고 생각합니다.

처음엔 가위바위보 게임에서 사용한 함수들을 묵찌빠 게임에서 사용하기 위해 구조체에 추가하려고 했으나, extension을 활용해보고 싶어서 extension을 사용했습니다.

2022-04-22 07:56 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
수정했습니다 ㅎ

2022-04-22 08:00 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/GameCollection/GameMukChiBaChoice.swift
> +    }
리뷰를 보고 예톤과 함께 enum 연관값을 사용해보려고 했으나, 어떤 방식으로 사용해야 할 지 어려워서 결국 수정은 하지 못했습니다. 나중에 시간이 남으실때.. 어떤 의도로 말씀해주셨는지 알려주시면 감사하겠습니다!

2022-04-22 08:00 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
수정했습니다!

2022-04-22 08:01 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
좋은 함수를 알게 됐습니다. 코드가 훨씬 깔끔하네요 ㅎㅎ 감사합니다!

2022-04-22 08:01 UTC, Groot-94 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
감사합니다!

2022-04-22 08:02 UTC, Groot-94 commented on README.md
>  > 리뷰어: @Red
좋은 의견 감사합니다.. 저희가 착각했네요.. ㅍ

2022-04-22 08:05 UTC, yeeton37 commented
안녕하세요 레드
코멘트 주신대로 step2 코드 수정해봤습니다!


먼저, 레드의 피드백
```swift
묵지빠를 enum 으로 나타내 주신점 좋았습니다!
그런데 GameRockPaperScissorsChoice과 비교했을 때 네이밍이 조금 다르고 rawValue 가 다른 점 말고는 큰 차이가 없는 것 같아요.

이 두개도 합쳐 볼 수 있을 것 같습니다. 하나의 enum 타입으로 만들고, 가위바위보를 위한 연관값, 묵찌빠를 위한 연관값을 두는 것은 어떨까요?
서로의 타입관의 변환해주는 userMukChiBaChoice 변수 computerMukChiBaChoice 변수를 합쳤으면 좋겠다고 제안 드렸었는데요, 타입을 합쳐준다면 변환해주는 메서드가 아예 필요 없어 질 수도 있습니다.
```

을 받고 가위바위보를 위한 연관값, 묵찌빠를 위한 연관값을 만들어서 `userMukChiBaChoice 변수`와`computerMukChiBaChoice 변수`를 합치고싶었는데...
실패했습니다....
연관값을 사용하는게 저희에겐 아직 너무 어렵더라구요
그래서 어떻게 사용해야할 지 여쭤봅니다 감도 안잡히네요...


나머지 피드백은 모두 적용해서 다시 commit했습니다

### 1. error 라는 case 를 없애고 옵셔널을 이용해서 처리
```swift
 private func changeToGameChoice(from number: Int?) -> GameRockPaperScissorsChoice? {
        switch number {
        case GameRockPaperScissorsChoice.end.number:
            return .end
        case GameRockPaperScissorsChoice.scissors.number:
            return .scissors
        case GameRockPaperScissorsChoice.paper.number:
            return .paper
        case GameRockPaperScissorsChoice.rock.number:
            return .rock
        default:
            return nil 
            // 여기에 의미없는 값으로 .draw를 넣어줬는데 생각해보니 옵셔널을 사용해주면 됐네요!
        }
    }
``` 

### 2. 반복되는 함수를 enum 안의 메서드로 변경
`GameRockPaperScissorsChoice `타입을 `GameMukChiBaChoice 타입`으로 변환하는 것에서 비슷한 동작이 두번 반복되기 때문에 반복되는 코드를 합쳐서 `GameRockPaperScissorsChoice` 타입 안에 메서드로 만들어 주었습니다.
```swift
enum GameRockPaperScissorsChoice: Int {
    case end = 0
    case scissors = 1
    case rock = 2
    case paper = 3
    
    var number: Int {
        get {
            return self.rawValue
        }
    }
    // 함수 추가
    func changeMukChiBa() -> GameMukChiBaChoice {
        switch self {
        case .end:
            return .end
        case .scissors:
            return .muk
        case .rock:
            return .chi
        case .paper:
            return .ba
        }
    }
}
```
### 3. 삼항 연산자를 toggle()로 대체

`이전 코드`
```swift
private mutating func changeTurn() {
        isUserTurn = isUserTurn ? false : true
    }
```
`바꾼 후 코드`
```swift
 case (true, false):
            isUserTurn.toggle()
            GameStatus.computerTurn.printMessage()
            executeMukChiBa()
```

toggle()을 사용하니 훨씬 더 알아보기 편해서 바꿔주었습니다!
유용한 개념을 알려주셔서 감사해요><


## 질문주셨던 것에 대한 답변

1. ### mutating
> 구조체에서 왜 mutating 키워드를 붙여줄까?
 

mutating은 객체를 바꾸는 함수임을 알리는 키워드입니다.
구조체 내부 함수에서 변수를 바꾸려고 할 때 mutating 키워드가 없으면 'self' ~~ 에러가 발생합니다.
구조체는 값 타입이고, 인스턴스 자체가 힙 메모리에 저장되어 참조할 수 있는 클래스와 다르게 구조체는 자체가 값을 가지고 있으므로 스택 메모리에 저장이 됩니다. 따라서 구조체는 전달될 때마다 참조가 아니라 매번 복사되어 전달됩니다.
그래서 Swift는 효율적으로 동작하기 위해 ‘값이 변경되었을 때에만’ 복사하도록 만들어졌습니다.
그리고 구조체의 값을 변경하는 함수의 경우 스위프트에게 알려주는 키워드가 바로 mutating입니다.


Swift는 메모리에 단독으로 접근하기 위해, 메모리의 위치를 수정하는 코드를 요구해서, 메모리의 동일한 영역에 대해 다중 접근이 충돌하지 않도록 하기 때문에 mutating 을 붙여줘서 메모리의 충돌을 막을 수 있는 것 같아용


### 2.객체를 사용할 때의 장점과 단점?

`저희가 생각한 장점`: 객체로 분리하면서 진행하니까 수정이 용이했고, step1에서 사용했던 객체들을 step2에서 다시 사용할 때 수정없이 사용할 수 있어서 좋았습니다!(원하는 부품을 사용하듯이).
결론적으로는 재사용이 쉽고, 수정이 용이하다고 생각했습니다. 

`저희가 생각한 단점`: 코드가 길어지고, 시간이 많이 듭니다. 가독성이 떨어져 보이는 것 같기도 합니다. (객체 간의 상호작용에 너무 포커스를 맞추다 보니 객체의 캡슐화가 저해되는 느낌이 들었습니다,,)

여기까지입니다
꼼꼼하고 정성스러운 답변 저희 둘 다 너무너무 감사하게 생각하고 있습니다🔥🔥
잘부탁드려요!

2022-04-22 11:31 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/GameCollection/GameRockPaperScissorsChoice.swift
> +    case error
에러는 보통 case 로 처리하지 않습니다. 
error 라는 타입이 `GameRockPaperScissorsChoice` 의 하나의 case 로 들어있는 것은 조금 이상한 것 같아요. 
에러 타입이 여러개여서 다른 처리를 해주어야 할 때는 에러 핸들링을 사용합니다!

2022-04-22 16:59 UTC, cherrishRed commented
예톤 그루트 수정하신 부분 모두 확인했습니다!

`GameRockPaperScissorsChoice` 와 `GameRockPaperScissorsChoice` enum 을 합치는 부분에 대해서는 디스코드에서 말씀드린 대로 진행해 주시면 좋을 것 같아요!

리펙토링 하시고 알려주세요!

2022-04-23 16:33 UTC, cherrishRed commented on README.md
> +`단점`: 코드가 길어진다. 시간이 많이 든다. 가독성이 떨어질 수가 있다. (객체 간의 상호작용에 너무 포커스를 맞추다 보니 객체의 캡슐화가 저해되는 느낌이 들었따?)
README 작성을 너무 잘해주셨네요!
이 부분에 대해서 고민하신 것 정말 좋습니다!
특히 캡슐화가 저해되는 느낌을 받으셨다니 지금 코드에서는 그런 것이 맞지요.
앞으로 공부하시다 보면 객체를 나누면서도 각 객체간의 분리도를 높이는 방법들에 대해 배우게 되실겁니다😁

2022-04-24 07:32 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +
아 그렇게 생각이 들겠네요 미처 생각지 못한 부분이예요,,,, 
```swift
var game = MukChiBaGame()
game.executeMukChiBa()
```
이렇게 바꿔주었습니다!

2022-04-24 07:34 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    }
단순히 userChoice가 옵셔널 값이기 때문에 바인딩해주는 방법으로 바로 switch-case문을 선택한건ㄷㅔ 저렇게 삼항연산자로 나타내주는 방법이 있었네요 완전 꿀팁이에요!!

2022-04-24 07:46 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
넵 피드백 반영해서
```swift
    private mutating func convertChoiceToMukChiBa() {
        userChoice = userChoice?.changeMukChiBa()
        computerChoice = computerChoice?.changeMukChiBa()
    }
```
위와 같이 한번에 묵찌빠로 바꾼 값을 받아오도록  convertChoiceToMukChiBa 메서드를 만들어주었습니다!

2022-04-24 07:48 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +        if userChoice?.changeMukChiBa() == computerChoice?.changeMukChiBa() {
그러게요 changeMukChiBa()를 안해줘도 결국은  같은 값을 비교하는 거네요!
수정해줬습니당 ㅎㅎ

2022-04-24 07:50 UTC, yeeton37 commented on README.md
> +`단점`: 코드가 길어진다. 시간이 많이 든다. 가독성이 떨어질 수가 있다. (객체 간의 상호작용에 너무 포커스를 맞추다 보니 객체의 캡슐화가 저해되는 느낌이 들었따?)
분리도를 높이는 방법을 배우면 코드를 볼때 훨씬 이해하기도 편해지겠네요! 칭찬 감사합니다....🥺🥺

2022-04-25 01:02 UTC, cherrishRed approved these changes

2022-04-25 01:11 UTC, merged