가위바위보게임 [STEP1] 애종,Mangdi
yagom-academy/ios-rock-paper-scissors pull request #150
Opened 2022-08-22 09:04 UTC by MangDi-L

@Jeon-Minsu 

진행 단계 : Step1

## 🤔 코드를 작성할 때 고민되었던 점
* 가위바위보게임중 컴퓨터가 낸 값과 사용자의 입력을 비교할때 switch문으로 작성할지 if문으로 작성할지 고민이었는데
가위바위보를 통해 낼수있는값이 가위,바위,보 같은 한정적이어서 switch문으로 쉽게 나타낼수있을것같아 switch문으로 작성했습니다.

* 게임을 종료할건지 아닐건지 결정하는 exitGame이라는 bool타입의 변수가 judgeWhoWins() 함수의 인자값으로 값을 변경받고자할때
judgeWhoWins() 함수 안에는 기본적으로 인자값으로 전달된 변수나상수를 상수로 취급하여 값의 변경이 이루어지지 않았습니다.
이를 어떻게 해결할까 고민했었는데 inout 키워드를 이용하여 구현할수있었습니다.

## 😢 해결이 되지 않은 점
* 가위바위보의 경우의 수가 9가지여서 if문을 9번 사용했는데, 로직을 잘 이용하면 이 경우의 수를 줄일 수 있을 것 같았는데 생각해내지 못했습니다.

## 🆘  조언을 얻고 싶은 부분 등 상세하게 작성
* 사용자의 값과 컴퓨터의 값을 비교할때 if문을 통해 작성하게되면 총 9가지의 if문을 작성하게됩니다.
만약 가짓수가 가위 바위 보 같이 한정적인게 아니라 이보다 많다면 if문으로 작성해야하는코드는 배로 늘어날것입니다.
그렇다면 if로 작성하는 이 부분이 약간 노가다 작업처럼 보여져서 더 효율적으로 처리하는 로직이 있을까 궁금하게되었습니다!

2022-08-22 13:23 UTC, Jeon-Minsu commented
안녕하세요 애종, Mangdi!!
두 분의 리뷰를 담당하게 되어 매우 영광입니다!! 
캠프 생활 2주차인데 프로젝트는 잘 적응하고 계시나요?? 😆😆

이번 묵찌빠 게임 프로젝트 STEP1 진행하시느라 정말 고생하셨습니다!!
코드를 보며 반복문과 조건문 처리를 위하여 노력하였다는 점이 느껴졌습니다!! 👍👍

앞으로 다양한 프로젝트를 통해서 많은 리뷰를 받으실 텐데, 코드에는 정답이 없기 때문에 제가 드리는
리뷰 또한 정답이 아니라는 점을 알고 계시면 좋겠습니다! 그러므로, 제 리뷰를 통해 본인들이 다시 생각해보아도, 본인의 생각이 더욱 타당하다 생각하여 저를 설득시킬 수 있다면, 그것 또한 하나의 답이고 좋은 경험이라고 생각합니다!
그러니, 리뷰 하나하나에 일희일비하지 않기를 바랍니다..🥲🥲
언제든지 궁금하신 점이 생기시면 바로바로 질문해주세요!! 🤗🤗

2022-08-22 14:11 UTC, Jeon-Minsu commented
- 고민되었던 점

1. 가위바위보게임중 컴퓨터가 낸 값과 사용자의 입력을 비교할때 switch문으로 작성할지 if문으로 작성할지 고민이었는데
가위바위보를 통해 낼수있는값이 가위,바위,보 같은 한정적이어서 switch문으로 쉽게 나타낼수있을것같아 switch문으로 작성했습니다.

> 조건문 작성에 대하여 if문과 switch문 중 어느 것을 사용한지 고민을 해보셨군요!! 아주 좋은 고민입니다!! 👍👍 두 분은 if와 switch 조건문의 차이와 장단점에 대해서 어떻게 생각하시는지 정리해주실 수 있나요? 그리고 한정적이라는 표현은 약간 모호할 수도 있다고 생각하여, 어떤 상황일 때 if문과 switch문을 사용하는지 좀 더 구체적인 기준을 듣고 싶어요! 고민되었던 점에 덧붙여 질문하고 싶은 점은 한정적이라고 생각하셔서 switch문을 통해 가위바위보를 낼 수 있는 값을 처리해주셨는데, case 안에 있는 1, 2, 3의 경우는 한정적인 경우가 아닐까요?? 🤔🤔


2. 게임을 종료할건지 아닐건지 결정하는 exitGame이라는 bool타입의 변수가 judgeWhoWins() 함수의 인자값으로 값을 변경받고자할때
judgeWhoWins() 함수 안에는 기본적으로 인자값으로 전달된 변수나상수를 상수로 취급하여 값의 변경이 이루어지지 않았습니다.
이를 어떻게 해결할까 고민했었는데 inout 키워드를 이용하여 구현할수있었습니다.

> 벌써 inout 키워드에 대하여 알아보셨군요!! 대단합니다!! 직접 포인터에 접근하는 것은 자유도가 높다는 장점도 있지만, 예상치 못하게 원본에 대한 수정이나 훼손이 가능하므로 주의하여야 합니다. 현재 구현한 함수에서는 해당 단점을 상쇄할정도로 inout 키워드가 필요한지는 의문이 드네요... 🥲🥲 여러분들의 의견을 다시 한 번 말씀해주시면 좋을것 같아요!!

---

- 해결되지 않은 점

1. 가위바위보의 경우의 수가 9가지여서 if문을 9번 사용했는데, 로직을 잘 이용하면 이 경우의 수를 줄일 수 있을 것 같았는데 생각해내지 못했습니다. 사용자의 값과 컴퓨터의 값을 비교할때 if문을 통해 작성하게되면 총 9가지의 if문을 작성하게됩니다.
만약 가짓수가 가위 바위 보 같이 한정적인게 아니라 이보다 많다면 if문으로 작성해야하는코드는 배로 늘어날것입니다.
그렇다면 if로 작성하는 이 부분이 약간 노가다 작업처럼 보여져서 더 효율적으로 처리하는 로직이 있을까 궁금하게되었습니다!

> 두 분의 말씀이 맞습니다. 지금은 총 9가지의 경우밖에 없지만, 만약 경우의 수가 100가지나 된다면 그걸 하나하나 하드코딩하는 것은 절대 좋은 방법이 아닙니다. 이런 경우 로직을 발견하여, 최대한 줄이려고 노력합니다! 이번 경우에는 저번주 활동학습 때 배운 개념을 활용해보는 것은 어떨까요?(Hint. 두 이상의 타입을 포함하는 타입) 아래의 공식문서를 확인해보시면 좋을 것 같아요!

https://docs.swift.org/swift-book/ReferenceManual/Types.html

2022-08-22 14:25 UTC, Jeon-Minsu requested changes
추가적으로 개행이 12번 줄을 제외하고는 거의 사용되지 않은 것 같습니다!
이에 대한 코드 컨벤션을 통일시켜 주시면 좋겠습니다!!

그리고 [e8a8800](https://github.com/yagom-academy/ios-rock-paper-scissors/pull/150/commits/e8a8800e733a1133d518d38bc4d154886afabb77) 커밋을 보시면, 리팩토링과 기능추가가 함께 있는데, 같이 올라온 것 같아요! 커밋 단위를 좀 더 세분화하시면 좋을 것 같아요!
추가적으로, 네비게이터와 드라이버에 대하여 커밋 메시지에 작성하지 않으셔도 좋습니다!! 😃

마지막으로, main에서 프로젝트를 모두 진행하기 보다는 스텝별로 브랜치를 별도 생성하여 커밋해주시면 더 좋을 것 같아요! 

이번 프로젝트 STEP1 PR 보내시느라 고생많으셨습니다!! 👍👍

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by 애종, Mangdi.
필요없는 주석을 알맞게 변경해주셨군요!! 좋습니다 😄😄

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var exitGame: Bool = false
가위바위보에 정답이 있을까요?? 🧐🧐
computerAnswer 네이밍에 대하여 다시 고민해보시면 좋겠습니다!

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
guard문 내부에 continue 키워드를 사용하였는데, continue 키워드는 어떤 역할을 하나요?
다른 키워드는 무엇이 있을까요??

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
computerAnswer와 같은 이유로, userAnswer 네이밍도 다시 고민해보시면 좋을것 같아요!

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
judgeWhoWins 네이밍 보다는, 게임의 결과를 출력해주는 기능을 하고 있는 것 같은데, 그에 걸맞은 네이밍을 다시 생각해볼까요?

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
1. 위에서 언급했다시피, inout 파라미터를 사용하지 않고 수정한다면 어떻게 수정을 하는게 좋을까요?

2. switch case 내에 break 지시어를 사용한 이유가 무엇일까요?

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +    while exitGame == false {
이번 프로젝트 순환함수(재귀함수)와 반복문의 장단점 비교해보기가 있는데,
두 분께서 두 방법의 장단점을 설명해주시고, 이번 프로젝트에서는 어떤 기준으로 while문을 사용하셨는지, 알 수 있을까요?

2022-08-22 14:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +startRockScissorsPaperGame()
현재 파일 분리 없이, main 파일 내에서 모든 기능이 구현되어 있는데, 파일을 분리해보는 것은 어떨까요? 🤔

2022-08-23 00:39 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var exitGame: Bool = false
가위바위보를 내는거니까 고르다, 선택하다, 뽑다 라는 뜻의 pick으로 대체했습니다!

2022-08-23 00:50 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
- 반복문내에서 continue가 사용되는 순간, 아래 코드를 건너 뛰고 다음 반복으로 넘어가게 하는 역할을 합니다. 
- 그리고 guard let 을 쓰고 else 블록 안에는 Control Transfer Statements(흐름 제어 구문)의 종류 5가지 continue, break, fallthrough, return, throw 중 한 가지를 사용해야 합니다.

2022-08-23 00:51 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
확인했습니다!

2022-08-23 00:56 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
그러네요, 유저의 선택에 따른 게임의 결과를 보여준다는 표현이 더 어울리는 것 같아요! showGameResult() 로 함수명을 변경해보았습니다 😀

2022-08-23 01:34 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
1. 네이밍 변경된 judgeWhoWins함수 -> showGameResult함수 에 리턴값을 주어서 inout을 사용하지않는방향으로 수정했습니다!
2. java에서 switch문을 작성할때 break문을 사용하지않으면 case조건에 상관없이 다 훑고 지나갔었는데 swift에서는 다르다는것을 늦게 알았습니다.ㅠㅠ 앞으로 사용에 유의하겠습니다!

2022-08-23 02:32 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/main.swift
> +    while exitGame == false {
- 재귀함수  : 자기 자신을 다시 호출하여 재창조하는 구조를 가집니다. 스택 메모리를 사용하고 반복적으로 자기 자신을 호출하면서 스택에 계속해서 쌓이므로 스택 오버플로우가 발생할 수 있습니다. 이럴 경우 충돌이 일어나면서 프로그램이 비정상적으로 종료될 수 있습니다. 또 재귀함수는 실행속도가 반복문에 비해 느리지만 코드 길이와 변수가 적어 가독성이 높다는 장점이 있습니다. 
간결한 알고리즘을 사용하여 쉽게 구현할 수 있는 장점을 가졌습니다.

- 반복문 : 특정 조건에 도달할 때까지 반복적으로 실행합니다. 스택 메모리에 한번만 올라갑니다. 실행속도는 빠르지만, 코드 길이가 길어지고 변수가 많아져 가독성이 떨어진다는 단점이 있습니다.

- 반복문을 쓴 이유 : startRockScissorsPaperGame함수를 재귀함수를 통해 호출할 경우 스택오버플로우를 야기할 수 있을 뿐 아니라 앞으로 step2를 진행할 때 코드가 더 복잡해질 것을 생각하여  반복문을 사용하게 되었습니다.

2022-08-23 02:43 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/main.swift
> +startRockScissorsPaperGame()
확인했습니다!

2022-08-23 04:44 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by 애종, Mangdi.
맨 위에서 2번째 코멘트 달아주신것에대한 답변을 이곳에서 진행하겠습니다!

* if문과 switch문의 차이점
> if문은 조건문이 많을수록 위에서 조건문을 비교하며 내려오기 때문에 복잡성이 증가하지만 switch문은 해당하는 case문으로 바로 넘어갑니다. 또한 조건이 많을수록 switch가 if문보다 가독성이 좋습니다. 따라서 저희가 작성한 코드에는 조건문이 많은경우라 생각 해서 switch문을 사용했습니다.

2022-08-23 04:48 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by 애종, Mangdi.
## inout 키워드의 사용

- inout 키워드가 예상치 못한 원본의 훼손을 야기할 수 있는 줄 몰랐네요 ! 이 프로젝트에서는 이러한 위험을 감수할정도로 inout이 필요하지는 않다고 판단됩니다. inout 대신에 저희는 두 가지 대안을 생각해보았는데요.

  1. 전역변수의 사용
  2. 함수가 bool 타입을 반환해 게임의 종료여부를 판단

- 먼저 전역변수를 사용하는 경우. var exit: Bool 과 같이 선언하고 필요에 따라 변경하여 프로그램을 종료하게 해줄 수 있을 것 같았지만, 전역변수는 되도록 지양하는 것이 바람직하다고 생각해 이 방법은 선택하지 않았습니다.
- 저희는 함수의 bool타입 반환을 통해 프로그램의 종료를 결정했습니다. showGameResult() 함수 내부에 지역변수로 var exit: Bool 을 선언해주고, 게임 종료에 해당하는 상황에 exit = true 처리했습니다. 그리고 exit을 반환해주어 게임종료가 처리되게 구현했습니다.

2022-08-23 05:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by 애종, Mangdi.
본인들의 확실한 근거를 바탕으로 switch문을 사용하였군요!! 훌륭합니다!! 👍👍
앞으로도, 문제를 처리하는데 있어 다양한 방법을 마주하게 될텐데, 지금처럼 각 방법의 차이와 장단점을 주목하여,
본인들의 사용 기준을 만드시면 좋은 공부 방법이 될 것 같습니다!! 😃😃

2022-08-23 06:02 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by 애종, Mangdi.
inout 키워드의 대안으로 좋은 방법들을 고민해주셨군요!!
이번에 선택하신 후자의 방법은 메서드의 return 값을 이용하여 다른 메서드와 상호작용을 하는 방식은 좋은 접근인 것 같아요!!
아주 좋습니다!! 😄😄

2022-08-23 06:08 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
흐름 제어 구문에 알아보셨군요! 이번 시간을 통해 각 흐름 제어 구문의 특징을 잘 이해하셨기를 바랍니다!
혹시, 이번 코드에서 continue 대신 다른 흐름 제어 구문을 사용해보셨나요??
흐름 제어 구문을 break나 return으로 바꾸면 과연 while문은 반복되지 않을까요?
이를 직접 확인해보셔서 해당 흐름 제어구문의 범위를 다시 확인해보고 수정이 필요하다면 수정해보시면 좋겠습니다! 🙏🙏

2022-08-23 06:10 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
리턴값을 활용하도록 메서드 내부를 아주 잘 바꿔주셨습니다! 
또한, java와 swift에서의 switch 문 사용의 차이를 알게 되셨네요! 좋습니다!!

2022-08-23 06:12 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +    while exitGame == false {
하나의 메서드 작성에도 앞으로 예상할 수 있는 문제들을 고려하여 최선의 방법을 선택한 점 매우 칭찬드리고 싶어요!!
현재 기능 구현에만 급급하지 않고 다가올 문제를 예상하여 유연한 코드를 작성하는 것은 매우매우 중요한 작업입니다!
이를 아주 완벽히 수행하셨네요!! 👍👍
추가적으로, 재귀함수를 사용함에 있어 스택 오버플로우를 예방할 수 있는 방법도 한 번 알아보시면 도움이 되실 것 같아요!

2022-08-23 06:13 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +startRockScissorsPaperGame()
main과 기능 구현에 대한 파일을 나누셨군요! 좋습니다!!
다만, 해당 메서드를 담는 파일의 네이밍으로 step1은 다소 부적절해보입니다.
해당 파일 내 기능을 아우를 수 있는 네이밍을 고민해보시면 좋을 것 같아요!! 🤩🤩

2022-08-23 06:25 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
메서드 네이밍은 좋아 보입니다! 
다만, showGameResult(computerNumber: Int, userNumber: Int)의 입력에 대하여 
메서드와 파라미터 네임 간에 연결이 약간은 부자연스러워보이고,
입력 부분에 대하여 showGameResult(computerNumber: computerNumber, userNumber: userNumber)와 같이
중복 사용된다는 느낌이 드네요! 이를 해결하는 방법을 고민해보시면 좋을 것 같아요!

2022-08-23 06:31 UTC, Jeon-Minsu commented
전체적으로 코멘트를 바탕으로 수정한 코드를 보니, 하나하나의 기능에 대하여 많이 고민한 흔적이 보였습니다!!
지금과 같이, 세심하게 코드를 작성하면 좋을 것 같네요!!  👍👍

다음 스텝에서 적용해보면 좋을 사항을 아래에 추가적으로 남겨봅니다!

1. 매직 리터럴 관리
> 1,2,3으로 표현된 가위바위보를 다른 개발자가 이해할 수 있도록, 딕셔너리를 이용하여 가위, 바위, 보임을 명확히 알 수 있게 한 것은 좋은 접근입니다. 하지만 이또한 매직 리터럴을 사용한 경우로, 한 글자라도 잘못 적게되는 등 휴먼 에러가 발생할 가능성이 여전히 존재합니다. 이에 대하여 Namespaces를 관리할 수 있는 타입으로 enum, struct 등을 고려해보시면 좋을 것 같아요!! 

2. 반복문 하드코딩 지양

>  해결되지 않은 점에 대한 전체 코멘트에 대해서 다시 한 번 고민해보시면 좋을 것 같아요! 저는 코드를 더욱 간결화하기 위하여 튜플을 사용해볼 것 같네요!!

2022-08-23 06:41 UTC, merged