[STEP 1] rhovin, zhilly
yagom-academy/ios-rock-paper-scissors pull request #153
Opened 2022-08-22 11:09 UTC by yuvinrho

@wongbingg 
안녕하세요 웡빙! 로빈, 질리입니다~ Step1 완료해서 PR 보냅니다. 이번주 리뷰 잘부탁드립니다😀

# 코드를 작성할 때 고민되었던 점 & 조언을 얻고 싶은 부분
## 함수 기능분리
한 가지 기능만 처리하는 함수를 만들기 위해 분리를 해보았는데, 의도에 맞게 잘 되었는지 걱정됩니다. 함수 분리가 필요하거나 불필요하게 많이 분리되어있지 않는지 궁금합니다!
- `displayGameMessege()` : 게임화면 메시지 출력 함수
- `inputUserSelction() -> String?` : 사용자 입력받고 반환하는 함수
- `judgeValidInput(userInput: String?) -> Int?` : 사용자 입력을 매개변수로 받아 0~3으로 반환하는 함수 
- `judgeWin(userInput: Int, computerHand: Int) -> Int` : 게임 승패를 반환하는 함수
<br>

## 게임시작으로 돌아가는 방법
사용자가 입력을 잘못 하거나, 비겼을때 다시 입력받는 부분으로 돌아가야 하는데 어떤 방식으로 돌아가야할지 고민했습니다.
게임을 시작하는 함수 `startGame()`를 생성해서 돌아가야하는 조건문에 return에 `startGame()` 을 호출했습니다. wongbingg이라면 어떻게 처리하셨을지 궁금합니다!
<br>

## 네이밍
- 사용자의 입력이 0~3사인지 판단하여 Int?타입으로 반환하는 함수이름을 어떻게하면 잘 의도를 나타낼 수 있을까 고민한 결과 `judgeValidInput(userInput: String?) -> Int?` 이렇게 이름을 지었습니다. 해당 함수가 의도가 명확하게 나타나는 이름인지와 전반적으로 네이밍에 대한 웡빙의 의견이 궁금합니다!
<br>

2022-08-22 14:11 UTC, wongbingg reviewed
안녕하세요 로빈, 질리 ~ 반갑습니다😊 PR메세지를 잘 작성해주셨네요 ! 
같이 공부하는 입장에서, 제 리뷰가 여러분에게 도움이 되었으면 좋겟네요 ! ㅎㅎ 

### 함수 기능분리 
함수를 세분화 하는 과정은 굉장히 중요하다고 생각합니다! 제가 봤을 땐, 전반적으로 기능 분리가 잘 되어있는 것 같습니다 ㅎㅎ 

### 게임시작으로 돌아가는 방법
재귀함수를 이용하셨군요! 잘 처리하셨어요 ㅎㅎ 저도 예전에 할 때 같은 방법을 이용 했었습니다 !

### 네이밍 

이 부분의 경우 함수명에서 “유효한 입력값인지 판단한다. “ 라는 뜻으로 보이는데, 그렇다면 결과값이 Bool 값이 나와야할 것 같습니다..! 하지만 이 함수의 수행은 :
> 1. String 값을 Int값으로 변환해주는 작업
> 2. 유효한 값을 판별해내는 작업

이 두가지 기능을 하고있는 것 같습니다! 분리해봐도 좋겠군요 ..! 나머지 메서드들의 네이밍은 전반적으로 깔끔명료해서 코드읽기에 수월했습니다 ㅎㅎ

2022-08-22 15:03 UTC, wongbingg requested changes
전반적으로 코드를 잘 작성 해주셨네요~ ㅎㅎ👍👍  제가 드린 코멘트가 모두 정답은 아닙니다! 여러분 끼리 상의 해보시고, 코멘트에 대한 질문이 있으시면 언제든지 물어봐주세요 ~! ! ㅎㅎ

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +//  Created by rhovin and zhilly on 2022/08/22.
주석도 신경써서 작성해주셨군요 👍👍 좋습니다 !

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
네이밍 좋습니다 ! 👍 
전체적으로 private 처리를 해주신 이유가 무엇 일까요 ? 그리고 접근제어자의 종류는 무엇무엇이 있을까요 ?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
여기도 잘 작성 해주셨군요 ~ 👍👍

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
위에서 언급드렸던 부분입니다 ! 기능분리를 해보면 어떨까요 ?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
난수를 생성하는 방법에는 또 어떤 것이 있을까요? 그리고 그 중, shuffled() 메서드를 사용하신 이유가 있을까요?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +}
judgeWin이라는 네이밍은 "승리를 판별해내다 " 라는 해석이 됩니다. 하지만 여기서 반환값인 Int 값이 무엇을 나타내는지 자세히 보지 않으면 이해할 수 없을 것 같습니다. 
이렇게 소스 코드 안에 작성된 구체적인 숫자값 또는 문자열을 매직넘버, 매직리터럴 이라고 합니다. 여기서의 1, 2, 3 값에 대한 의미는 코드작성자가 아니고서야 한눈에 알아보기 힘들 것 같습니다. 어떻게 바꿔줄 수 있을까요?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +extension RockPaperScissorsLibrary: RockPaperScissorsLibraryProtocol {
벌써 프로토콜을 사용하시는 군요 ~? 대단합니다 👍 
프로토콜을 사용하신 이유가 궁금합니다 ! ㅎㅎ 또한 extension의 기능은 무엇이며, extension에 접근제어자를 주게 되면 어떻게 될까요 ?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        }
여기서의 0도 매직넘버에 해당합니다. 어떻게 바꾸어줄 수 있을까요 ?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        let result = judgeWin(userInput: userInput, computerHand: generateRandomComputerHand())
judgeWin 메서드에서 받게되는 두개의 파라미터명 네이밍에 통일성을 가지면 조금더 깔끔할 것 같습니다 ㅎㅎ 예를들면 userHand , computerHand 이런식의 네이밍 입니다 !

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        }
각 case의 모든 부분에 return 이 필요할까요 ?

2022-08-22 15:03 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/main.swift
> +let RockPaperScissors: RockPaperScissorsLibraryProtocol = RockPaperScissorsLibrary()
타입을 프로토콜로 명시해준 이유가 무엇인가요 ?

2022-08-23 06:07 UTC, yuvinrho commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
> 전체적으로 private 처리를 해주신 이유가 무엇 일까요 ?

모든 메서드들은 내부에서 작동하기 때문에 굳이 외부에서 따로 접근할 필요가 없다고 생각해서 private으로 접근제어를 처리하였습니다. 현재 startGame() 메소드도 private으로 은닉화 시켜주었고, 외부로 노출되는 callStartGame() 메소드를 만들어 안에서만 startGame()을 호출하도록 리팩토링 하였습니다.

>  그리고 접근제어자의 종류는 무엇무엇이 있을까요 ?

아래와 같이 5개의 접근 제어자가 있습니다. 이번 기회에 각 접근제어자에 대해 팀원과 공부해보았습니다.
1. public
2. open
3. internal
4. fileprivate
5. private

2022-08-23 06:11 UTC, yuvinrho commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
기존 `inputUserSelction() -> Int?` 는 사용자 입력을 단순 String? 으로 반환하였는데,
수정된 함수는 Int? 로 형변환하게 수정하였습니다.

`judgeValidInput(userInput: Int?) -> RockPaperScissorCase? ` 에서 사용자 입력을 `RockPaperScissorCase` 열거형으로 반환하도록 수정하였습니다.

2022-08-23 06:14 UTC, yuvinrho commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    }
저번주 과제 1-9까지 섞어서 3개의 숫자를 뽑아내서 이번에 생각없이 `shuffled()` 로 썼었습니다. 😂
 이번에는 한개의 숫자만 필요한 것이기 때문에` random()`으로 수정하였습니다~

2022-08-23 06:16 UTC, yuvinrho commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +}
`RockPaperScissorCase`와 `WinLoseDrawCase` 열거형을 만들어서 코드를 보는사람이 한번에 이해할 수 있도록 리팩토링 하였습니다~ 조언 감사합니다 웡빙!!😊

2022-08-23 06:20 UTC, yuvinrho commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        }
`RockPaperScissorCase` 열거형 타입으로 수정해 주었습니다~

2022-08-23 06:26 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +extension RockPaperScissorsLibrary: RockPaperScissorsLibraryProtocol {
> 프로토콜을 사용하신 이유가 궁금합니다 ! 

프로토콜을 사용함으로 사용자에게 프로그램의 인터페이스를 제시해 준다는 목적으로 사용하였습니다! 

> 또한 extension의 기능은 무엇이며, 

extension에는 여러가지 기능이 있지만 extension을 사용한 이유는 `RockPaperScissorsLibrary` 가`RockPaperScissorsLibraryProtocol` 를 준수하도록 하기 위해 작성하였습니다.

> extension에 접근제어자를 주게 되면 어떻게 될까요 ?

extension을 사용하여 프로토콜 준수성을 추가한 경우 extension에 대한 명시적 접근 제어자를 사용할 수 없는 것으로 알고 있습니다!

2022-08-23 06:27 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        }
미처 생각하지 못했던 부분이네요! 코멘트 감사합니다 👍

2022-08-23 06:28 UTC, yuvinrho commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        let result = judgeWin(userInput: userInput, computerHand: generateRandomComputerHand())
웡빙최고👍 좋은 의견 감사합니다. 해당부분 반영하여 아래와 같이 수정하였습니다ㅎㅎ

```
let result: WinLoseDrawCase = judgeWin(
            userHand: userInput,
            computerHand: generateRandomComputerHand()
        )
```

2022-08-23 06:29 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let RockPaperScissors: RockPaperScissorsLibraryProtocol = RockPaperScissorsLibrary()
타입은 요구사항이 충족된다고 해서 프로토콜을 자동으로 채택하지 않습니다. 따라서 항상 프로토콜 채택을 명시적으로 선언해 줘야 해서 명시해 주었습니다!

2022-08-23 09:25 UTC, merged

2022-08-26 06:51 UTC, yuvinrho commented
안녕하세요 웡빙 @wongbingg 😄
웡빙 덕분에 생각하지 못한 부분과 어떻게 하면 좀 더 나은 코드가 될 수 있는지 많이 배울 수 있었습니다. 감사합니다!