- 가위 바위 보 게임 [Step 1] Kyo, Aaron
yagom-academy/ios-rock-paper-scissors pull request #154
Opened 2022-08-22 11:58 UTC by KyoPak

@yusw10 
안녕하세요 보리사랑! 
Step1구현해서 PR 전달드립니다.

진행 단계 : Step1

## ⭐️ 코드를 작성할 때 고민되었던 점
1. 1,2,3 값외에 다른 값을 받았을 경우를 `isValidInput()`함수에서 1,2,3 이외의 값을 받을 경우의 false값과 0값인지 혹은 0,1,2,3이외의 값인지를 조건문을 통해 구현하였습니다. 
2. 승패로직함수 `decideWinLose()` 구현시 if문을 반복하여 사용해서 구현하려고 했으나 더 간결하게 하기위해서 값 두개의 차이를 이용해서 구현하였습니다. 

## ⭐️ 해결이 되지 않은 점
아쉽게도 없습니다..!

## ⭐️ 조언을 얻고 싶은 부분 
Kyo - enum을 사용하게 된다면 간결해질 것이라고 생각했는데 코드가 더 복잡해졌었습니다. 혹시  enum을 사용하게 된다면 코드 가독성 장점을 제외하고 더 좋은 점이 있을까요?
Aaron - 함수 구현에 있어서 기능 별로 모듈화를 어느정도 까지 해야하는지 조언을 얻고 싶습니다.
제가 작은 단위로 쪼개면 런타임시에 워크플로를 확인하기 쉽지 않아 함수의 모듈화에 어려움을 느꼈습니다.

2022-08-22 19:26 UTC, yusw10 requested changes
STEP1 진행하시느라 수고많으셨습니다 👏👏👏👏👏
엄청 빨리 PR을 보내셔서 굉장히 놀랐습니다ㅎㅎ

전체적인 생각을 말씀드리자면, 로직적인 부분에서는 딱히 말씀 드릴게 없을 정도로 깔끔했습니다. 제가 묵찌빠 프로젝트 진행할 때보다 몇배는 잘하셔서 굉장히 긴장해야겠다고 생각이 들었어요...
STEP1 진행하시느라 수고 많으셨고 여기서는 질문하신점이랑 전체적인 코멘트 남겨드릴게요.
제기 남겨드린 리뷰 내용이 절대 정답은 아닙니다! 읽어보시고 아니다 싶으시면 언제든지 두분상의해서 저한테 말씀주셔도 괜찮습니다.

---

>enum을 사용하게 된다면 간결해질 것이라고 생각했는데 코드가 더 복잡해졌었습니다. 혹시 enum을 사용하게 된다면 코드 가독성 장점을 제외하고 더 좋은 점이 있을까요?

[원초적인 질문인것 같아요. 기본적인 질문이지만 굉장히 중요하기에 집중해서 답변 드려보겠습니다...]
enum을 쓰면 코드가 오히려 복잡해지셨다고 했는데 제가 그 복잡한 코드를 직접 본건 아니라 어떤 상태일지는 모르겠어요. 복잡해 진다는게 혹시 코드가 길어져서 한눈에 로직이 들어오지 않는다는걸 말씀하시는걸까요? 

코드 전체적인 관점에서 생각해봅시다. 코멘트에서 남겨드렸지만 가위, 바위, 보 값이 무조건 1,2,3일까요? [1,4,9]이나 [2,3,8] 을 가위바위보 각각에 대입한다면 어떻게 될까요? 이때도 대응되는 상수를 적어놓고 주석으로 부가설명을 해야할까요?

여러분은 1,2,3이라는 각 숫자를 가위, 바위, 보라는 추상적 개념에 매핑을 시키셨죠? 하지만 이건 저희 캠퍼 사람들끼리만 이해가 가능한 "아 1,2,3 순서대로 가위바위보에 매핑이 되어있겠구나" 라는 암묵적 전제를 기반으로 하는 행위입니다. "왜 1이 가위인데" 라고 질문이 들어오면 할말이 없지 않을까요? 이런 요구사항을 모르는 개발자가 코드를 읽는다면 사용자입력과 컴퓨터값을 빼는 로직, 검증로직, 예외사항을 읽고 직접 추론하여야만 이해할 수 있습니다.

열거형은 하나의 타입처럼 사용이 가능합니다. 1이 가위라는게 아니라 그냥 가위 타입을 만드는 방식이죠. 여러분이 코드에서 사용하신 암묵적인 추상화가 아니라 실제 그 개념을 타입으로 적용할 수 있습니다. 
```swift
enum RockScissorsPaper {
    case scissor
    case rock
    case paper
}
```
누가 봐도 가위, 바위, 보 라는걸 네이밍을 통해서 유추 할 수 있습니다. 

위의 열거형에 rawValue라는걸 사용해볼까요?
```swift
enum RockScissorsPaper: String {
    case scissor = "1"
    case rock = "2"
    case paper = "3"
}
```
여러분의 기존의 코드에서 1,2,3 이 아니라 2,3,8로 매핑을 바꾼다고 가정해봅시다. 1,2,3이 사용된 모든 로직을 직접 찾아야합니다. 
`isValidInput`, `generateComputerInput`, `rockScissorsPaper`정도를 수정해야 할 것 같네요. 반면에 위의 rawValue를 사용했다면 어땠을까요? 입력받은게 어떤 enum 값인지만 확인하는 함수 한개만 있으면 무슨 숫자가 매핑되던간에 대응할 수 있지 않을까요?
결과값도 마찬가지입니다. 1과 -2라는 승리 조건은 숫자가 변경되면 매번 계산해야합니다. 만약 RockScissorsPaper의 연산프로퍼티로 값 자체를 비교하여 승패를 결론짓는다면 어떤 숫자를 입력받더라도 값 자체(가위인지 주먹인지 보인지)를 비교하기 때문에 재사용성이 올라가지 않을까요?

임의의 타입을 지정하여 사용한다는점은 굉장히 사용성이 높습니다. `타입.값`으로 접근하기 때문에 코드의 길이가 길어져서 언뜻보기엔 복잡해져 보일수 있습니다. 하지만 20~30 자 정도 길어짐을 감수하고 확장성, 재사용성, 가독성을 높일 수 있다면 오히려 좋은 트레이드 오프 아닐까요?

사실 가독성을 향상시킬 수 있다는것부터 사용 이유는 충분하다고 생각합니다(전세계에서 IOS 개발자가 저 혼자가 아니라면요🥲) 그외에 열거형을 사용하면 가독성 이외의 장점으로는 약간의 성능향상이 있는걸로 알고 있습니다. 여러분이 선언하고 메모리에 할당하는 변수, 상수, 함수, 데이터 타입 모두 저장 영역이 정해져있습니다. 대게 열거형은 Stack영역에 저장되고, String은 Struct이지만 Heap 영역에 저장됩니다(상황에 다르지만 대체로) Heap에 할당될 때는 메모리가 동적으로 할당되기 때문에 정적할당 방식인 enum을 사용하는게 String을 깡으로 사용하여 사용하는것보다 성능적으로 이득이 있습니다(무조건은 아닙니다.) 다만 이 내용은 지금은 이해하실 필요는없고 추후에 공부하실 기회가 오니 그때 해보셔도 무방합니다.

![](https://i.imgur.com/10F5PuK.png)
"enum을 왜 쓰는거야?" 하는 생각을 저도 여러분과 마찬가지로 했었습니다. 아마 merge된 제 묵찌빠 프로젝트를 보면 그 당시의 제가 짠 지저분하기 그지 없는 코드가 나올거에요(남부끄러운 코드중 하나입니다🥲). 저는 여러분처럼 왜? 라고 생각안하고 일단 하면 좋다니까 했었거든요.
그리고 enum 대신 전역 프로퍼티로 써도 될 것 같고, String을 직접 깡으로 비교해도 되는거아닌가 싶었어요. 하지만 적절한 위치에서 알맞게 사용되는 enum타입을 짜고 그 코드를 보신다면 높아진 가독성, 간결한 코드를 얻을 거라고 확신합니다.

---

> 함수 구현에 있어서 기능 별로 모듈화를 어느정도 까지 해야하는지 조언을 얻고 싶습니다.
제가 작은 단위로 쪼개면 런타임시에 워크플로를 확인하기 쉽지 않아 함수의 모듈화에 어려움을 느꼈습니다.

**저같은 경우에 하나의 함수는 한가지 기능만 갖도록 구현하려고 노력하는 편입니다.**
다만 이번 프로젝트에서는 하나의 기능만 동작하게 기능분리를 하면 줄어드는 로직보다 늘어나는 함수의 갯수가 더 많아질겁니다. 말씀하신대로 워크 플로를 따라가기 위해 이곳저곳에 구현된 함수를 찾아야 하는 일이 발생하는거죠.

하지만, 그럼에도 불구하고, 함수의 기능을 분리하는 일은 생각보다 중요합니다. 여러분은 앞으로 점점더 많은 기능의 복잡한 로직을 잔뜩 수행하는 코드를 구현하실거에요. 이때 함수의 기능분리는 재사용성, 확장성에 큰 기여를 합니다. 

```swift 
func bringUserInput() -> Int {
    guard let input = readLine() else { return 404 }
    guard let userInput = Int(input) else { return 404 }
    return userInput
}
```
여기 여러분이 작성한 **사용자 입력을 받아 정수형태로 형변환 하여 반환하는 함수** 가 있습니다.
코멘트에서도 말씀 드렸지만 이 함수는 기능이 두가지입니다. 형변환과 사용자 입력이요.
이런 코드를 갖고 있는데 만약 프로젝트 내부에서 Double타입으로 리턴하는 입력값이 필요하다면 함수를 하나 더 만들겟죠? Float, Character타입이 필요하다면요? 함수가 입력가능한 데이터 타입의 갯수만큼 필요하지 않을까요?
굉장히 비약을 심하게 해서 예를 들어드렸습니다만, 실제로 확장성과 재사용성을 염두에 두지 않는다면 충분히 발생할 수 있는 오류입니다.

반드시 진짜 절대 무조건 함수는 한개의 기능만해야해! 이건아닙니다. 다만 고려를하고 작성한 코드와 느낌가는대로 작성한 코드는 다를수밖에 없지 않을까요?

질문주신 이 부분은 저도 아직 다른사람의 코드를 보거나 여러 방법으로 같은 코드를 리팩토링 하면서 개선해 나갈려고 하는 부분중 하나입니다. 어려운게 당연한 주제라고 생각해요. 벌써부터 이런 고민을 하신다는게 대단하다고 생각합니다.
ps. SOLID 원칙이라고 들어보셨을까요? 단일책임 원칙에 관련된 좋은예와 나쁜예에 대해서 읽어보시면 도움이 될것같습니다(캠프 중반에 배우실 내용이므로 이런게 있구나 하고 넘어가셔도 좋을것같아요!)

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userInput = Int(input) else { return 404 }
404라는 정수는 어떤걸 의미하는걸까요? HTTP response status code에서 아이디어를 얻어오신걸까요?
이 코드는 정수 이외 타입은 분명 404로 return시켜서 어디에선가 정상적으로 에러처리 될겁니다.
다만 404가 이런 에러를 정확히 표현할 수 있을까요? 만약 소수점이 포함된 실수와 알파벳, 한글입력에 대해서 각각 다르게 에러문을 출력한다면 404하나로 표현이 가능할까요?

사용자 입력값에대한 검증을 위해 `isValidInput`라는 메서드를 구현해주신것 같아요. 다만 `isValidInput `메서드는 1,2,3 인것만 검증하고, 정수외의 입력값인지에 대해서는 `bringUserInput`메서드가 검증하고 있는것같지 않나요?

예외사항처리하는 함수, 입력만을 받는 함수를 생각하고 이런구조로 접근하신점은 아주좋습니다👍 다만 정확하게 함수의 네이밍이 갖는 의미와 실제 동작은 약간 다른것 같아요. 잘 생각해보시고 리팩토링 해보시면 좋을것 같습니다

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if 1...3 ~= input {
범위연산자를 사용하셨군요!
한눈에 input값이 1부터 3사이라는걸 확인할 수 있어서 좋았습니다.

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var gameStatus = true
사용자입력과 랜덤생성한 컴퓨터의 입력값을 비교하여 승부가 결정되면 탈출 조건으로 사용할 Bool타입으로 보입니다.]
다만 `gameStatus`라는 변수명은 사용 목적과 비교했을 때 약간 의미가 모호해보입니다.
비긴상태도 게임의 상태이지 않을까요?
게임이 끝나는게 참값일지, 게임을 계속하는게 참값일지도 코드의 흐름을 쭉 읽어보지 않는한 while조건문만을 보고는 추측이 어려워보입니다. 네이밍에 대해서 한번 더 고민해보면 좋을것같아요.

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return false
사용자 입력과 컴퓨터의 랜덤값의 차를 이용해 가위바위보의 상태를 정의해주신것 같아요. 다만 현재 코드를 한번 처음보는 사람의 입장에서 한번 볼 필요가 있습니다.

이긴 경우를 `[사용자 입력값 - 컴퓨터 입력값]`의 결과값이 1과 -2임으로 확인하는 코드네요. 다만 이 코드로는 어디에서도 왜 이긴게 1인지 -2인지에 대해서 추론을 할 수가없습니다. 당장 print()문에서 `(1)`, `(2)`, `(3)`를 빼면 이 코드를 읽는 사람은 왜 1이 이긴건지 추론이 가능할까요? 아마 가위는 1, 바위는2, 보는 3이라는 출력문을 가지고 머리속에서 이기는 경우의수를 시뮬레이션해야만 1과 -2가 이긴다는걸 이해할 수 있지 않을까요?

1과 -2라는 매직넘버를 사용하신부분도 문제가 될 수 있습니다. 만약 가위는 1, 바위는 4, 보는 9를 입력받는 걸로 요구사항이 변경된다면 어떻게 해야 할까요? 1과 -2라는 숫자는 단순히 입력값이 "우연히" 1,2,3이어서 발생하는 값입니다. 이렇게 상수를 직접대입한다면 요구사항이 바뀔때 마다 그 차이를 일일이 계산해서 if문을 수정해야하지 않을까요?

입력값을 정수로 받기 떄문에 이들의 차를 이용하여 승패를 결정짓는 로직은 좋다고 생각합니다. 👍 다만 이 로직은 최초 작성한 여러분만 100퍼센트 이해하는 것이고 남들이 읽을 때 이 로직이 쉽게 이해되도록 코딩하는것을 지향해야합니다.

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
`isValidInput(input: userInput) == false`가 두번쓰이네요. 이를 줄여볼 수 없을까요?

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func rockScissorsPaper() {
함수명인데 명사3개의 조합이네요. 가위바위보 게임을 시작한다는 의미가 담기도록 Swift API Design Guidelines 을 참고하여 네이밍을 고민해보시면 좋을거같습니다.

2022-08-22 19:26 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let userInput = bringUserInput()
userInput이 어떤 타입일까요? 
bringUserInput 함수는 Int타입을 반환하고 있지 않나요? 
대게 콘솔 프로그램의 경우 사용자 입력은 String으로 이해할 수 있습니다. readLine()이 String? 타입인지 ios 개발자는 모두 알고 있으니까요.
다만 이 한줄만 봤을 때는 이게 String타입인지 Int타입인지 추론이 불가능한거같습니다.

2022-08-23 06:33 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let userInput = bringUserInput()
수정 했습니다!

2022-08-23 06:34 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/main.swift
> +func rockScissorsPaper() {
수정완료하였습니다!

2022-08-23 06:34 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var gameStatus = true
isGaming으로 수정완료하였습니다!

2022-08-23 06:35 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return false
매직넘버 상수처리해서 수정완료하였습니다!

2022-08-23 06:42 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
이 부분을 어떻게 줄여나갈지 모르겠어서 수정하지 못했습니다 ㅠㅜ

2022-08-23 06:49 UTC, Hashswim commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userInput = Int(input) else { return 404 }
해당 부분은 입력에러와 형변환 에러모두 생각해 에러타입으로 처리해 유효한 값이 아니라면 에러를 던지도록 구현했습니다..!

2022-08-23 09:08 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return false
좋네요! 말씀드린의도가 로직은 정말 좋은데 사용하실 때 1과 -2가 갑자기 뜬금없이 나오기 떄문에 코멘트 단 것도 있었습니다.
이렇게 사용하시면 적어도 1과 -2가 승리 조건이라는걸 미리 읽고 조건문을 읽기 때문에 이해하는데 도움이 됩니다.

2022-08-23 09:11 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userInput = Int(input) else { return 404 }
에러타입을 사용하셨군요! 훌륭합니다
이정도 까지를 생각하고 코멘트 드린건 아닌데 너무 잘 리팩토링하신것 같아요.
기왕 에러타입을 직접 구현해보셨으니 관련해서 미리 예습할것도 슬쩍 드려봅니다(이건 이런게 있다고 알고만 넘어가시고 이번 프로젝트에서 반영 안하셔도 됩니다. 진짜 예습이니까요)

[result type](https://developer.apple.com/documentation/swift/result)

2022-08-23 11:12 UTC, yusw10 approved these changes

2022-08-23 11:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerInput = InputOption.allCases.filter { $0 != .gameExit }.randomElement() ?? .scissors
scissors로 한 이유가 있을까요?
저도 이 부분 관련해서 고민을 많이 했습니다. "아니 리턴을 해야하는데 옵셔널이네? 기본값을 뭘로하지?" 하면서요.

"InputOption에 옵셔널 처리를 위한 변수를 추가할까?"
"이 함수에서는 일단 옵셔널을 리턴해서 함수 호출부에서 처리를 해줄까?"
"random만 함수로 따로 빼서 분리를 해줄까?"

정답은 없을거같아요. 다만 지금 방식대로라면 **왜 random을 적용했을 때 기본값이 가위인지**에 대한 근거가 있어야 할것같아요.

2022-08-23 11:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let input = Int(input ?? "") else { return .gameExit }
`guard let`구문의 return 개행관련 생각하신 규칙이 있으실까요?
```swift
guard let input = Int(input ?? "") else {
        throw InputError.numberError(message: errorSentence)
    }
```
이부분에서는 개행을 해주셨네요.

2022-08-23 11:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
enum 활용 좋습니다!

2022-08-23 11:12 UTC, merged