가위, 바위, 보 게임 [STEP 1] Ash, Jeremy
yagom-academy/ios-rock-paper-scissors pull request #159
Opened 2022-08-23 03:25 UTC by yjjem

# 고민한점 🤔
### 1. if와 switch 구문 사용에 대한 고민
가위바위보 게임에서 user의 승패를 확인할 때, userNumber - computerNumber 를 기준으로 확인을 했습니다.
해당 수를 기준으로 user가 승인 경우, 그 차이값이 1인 경우 2가지와 -2인 경우 1가지가 있었습니다.
패인 경우는 숫자만 다를 뿐 가지수는 같은 상황이었습니다.
그래서 처음에는 승패를 판단할 때, 둘 중 어느 조건문을 사용할지 고민했습니다.
아래의 예시는 user가 승리인 경우 입니다.
- if 사용: if문으로 userNumber 가 1이고, computerNumber 가 3인 경우면 user의 승리, else if문으로 그것이 아니라면 userNumber - computerNumber 값이 1일 때 승리하는 것으로 처리한다.
- switch 사용: userNumber - computerNumber 값이 -2 혹은 1이면 승리하는 것으로 처리한다.

의사코드와 같이 if문은 두가지의 경우를 모두 확인해야 하는 상황이었고, switch문으로 처리를 하는 경우에는 기준값에 따라 바로 해당 case로 이동하게 되어 if문보다 간결한 작업처리를 할 수 있다고 생각했습니다.

### 2. 함수 기능에 따른 코드 분리의 기준에 대해 고민했습니다.
처음에는 `startGame()` 함수내에 모든 기능을 포함하여 구현했습니다.
이후에 step2 까지 고려하면 기능 분리가 불가피하다고 생각되어 하나의 함수에서 한가지 기능만을 가질 수 있게 refactoring 해봤습니다. 

# 조언을 얻고 싶은 부분 🤔
`startRockPaperScissor()` 의 네이밍이 적절한지 궁금합니다.

2022-08-23 13:15 UTC, finnn1 commented
안녕하세요 Jeremy, Ash! ☺️

STEP 1 진행하시느라 정말 수고 많으셨습니다!!🥳
코드가 전체적으로 굉장히 깔끔한 것 같습니다. 👍👍

우선적으로 야곰이 항상 말씀하시는 것처럼 코드에는 정답이 없기 때문에,
제가 드리는 리뷰가 모두 정답은 아니라는 것을 꼭 인지하시면 좋을 것 같아요 ☺️

만약 제가 코멘트를 달았던 부분에 대해서 여러분들의 코드에 근거가 있고, 이게 더 나은 방향인 것 같은데 라는 생각이 드신다면 저를 설득하시는 과정 또한 정말 좋은 경험이 되실 것 같아요!

언제든지 궁금하신 점이 생기시면 바로바로 말씀해주세요😁

## 고민하셨던 점에 대해서 :
### 1. if와 switch 구문 사용에 대한 고민
`if`와 `switch` 구문의 차이를 공부하신 후 적절한 조건문을 채택하여 사용하셨군요! 👏👏
무엇을 사용하든 차이와 특징을 확실하게 알고 사용하는 것은 정말 좋은 자세라고 생각합니다.
### 2. 함수 기능에 따른 코드 분리의 기준에 대해 고민했습니다.
하나의 함수에서 한가지 기능만을 가질 수 있도록 기준을 잡고 `refactoring` 하셨군요!
좋은 코드를 짜기 위한 꼭 필요한 마인드라고 생각합니다. ☺️👍

## 조언을 얻고 싶은 부분에 대해서 :
`startRockPaperScissor()` 메서드의 네이밍이 적절한지 질문 주셨는데요!
가위바위보를 시작한다는 의미에서 적절한 네이밍인 것 같습니다.
별도로 코멘트 드릴 부분은 없는 것 같아요!

## 기능 구현에 대해 :

> 0~3이 아닌 값을 입력받은 경우 : “잘못된 입력입니다. 다시 시도해주세요.” 출력 후 최초 실행 상태로 복귀

요구사항에는 이렇게 적혀있는데요,
현재는 숫자 외의 입력(ex. `!`,`@`,`&` 등)이 들어갈 경우 무조건 게임이 종료되는 것으로 보입니다 🤔
이 부분을 해결해볼 수 있을까요?

2022-08-23 13:19 UTC, finnn1 requested changes

2022-08-23 13:19 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
혹시 `Foundation`이 무엇인지 설명해주실 수 있을까요?
현재 파일에서 꼭 필요한 부분일까요? 🤔

2022-08-23 13:19 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
코드의 역할분리 👍👍
깔끔합니다!

2022-08-23 13:19 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
9번째 라인에서 하나의 함수에서 한가지 기능만을 가질 수 있도록 `StartGame()` 메서드와 `startRockPaperScissor()` 메서드를 분리하신 것으로 생각되는데요 👍
다만, `startRockPaperScissor()` 메서드 내부에서는 두 세가지의 일을 맡고 있다는 느낌이 드는 것 같아요.
지금은 괜찮지만, 말씀하신대로 STEP2를 고려해본다면 이 부분에 대해서도 조금 더 고민해볼 수 있을까요? 🤔

지금은 프로젝트의 규모가 크지 않아 코드의 역할 분리 필요성에 대한 의문이 드실 수 있어요.
저 또한 그랬기 때문에 충분히 공감하지만, 지금부터 연습해서 좋은 습관을 만들어놔야 나중에 프로젝트의 규모가 커지더라도 좋은 코드를 짤 수 있다고 야곰이 말씀하셨던 것 같아요 ☺️

2022-08-23 13:19 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
메서드명만 보고도 어떤 역할을 하는지 직관적으로 잘 네이밍 해주셨네요! 👏
코드의 역할 분리 또한 칭찬합니다 👍

2022-08-23 13:19 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgeWinner(_ userNumber: Int, _ computerNumber: Int) {
메서드명은 매개변수를 포함해서 하나의 문장처럼 자연스럽게 읽히는 것이 좋은데요!
`Argument Label` 을 활용해보시는 것은 어떻게 생각하시나요? 🤔

2022-08-23 13:19 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
가위바위보의 승패 결과 코드를 정말 간결하게 잘 짜주셨네요! ☺️
다만, 유지보수 차원으로 본다면 가독성이 좋지 않다는 느낌이 들어요. 🤔
알고리즘 대회에서 문제를 푸는 것이라면 상관없겠지만,
회사에서 팀 프로젝트를 진행할 때 다른 개발자, 또는 미래의 자신이 해당 코드를 본다고 생각하고 조금 더 한 눈에 이해하기 쉽도록 코드를 짜볼 수 있을까요?
프로젝트의 규모가 커지면 커질수록 한 눈에 알아볼 수 있는 직관적인 코드가 굉장히 중요하다고 생각해요 ☺️

2022-08-24 03:09 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgeWinner(_ userNumber: Int, _ computerNumber: Int) {
```swift
func judgeWinner(with userNumber: Int, and computerNumber: Int) {}
```
`with`와 `and`를 추가하였습니다 ! 👍

2022-08-24 03:18 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
유저와 컴퓨터의 패의 결과를 한눈에 보이게 Switch 에서 enum을 활용하여 refactor 하였고 
입력 값을 enum case 로 번역해주는 함수 `translateNumbersToHandSigns()` 를 추가했습니다. 😄

2022-08-24 03:21 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
`getUserInput()` 함수가 print와 Input을 담당하도록 기능을 분리했습니다. 감사합니다 ! 🤓

2022-08-24 03:42 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
공부가 부족했던 것 같습니다! 
`Foundation` 은 기본 데이터 타입, 자료구조 등을 담당하는 Framework로 알고있었습니다!
반드시 Import 해줘야하는 것인줄 알았는데. 
다시 공부를 해보니 NS접두어가 붙은 Objective-C 의 타입이 구현되어 있었습니다.

저희가 사용하는 타입들은 Swift  항목안에 들어있다는 사실을 확인하였고. 
<img width="281" alt="스크린샷 2022-08-24 12 37 45" src="https://user-images.githubusercontent.com/88357373/186323607-1089a144-ab28-4ea6-80e5-7c1168395898.png">
Foundation 을 import 해줄 필요가 없다는 결과에 도달했습니다.
감사합니다.

2022-08-24 08:24 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
정말 상세하게 공부를 잘 하셨네요 👍👍
불필요한 코드를 쓰지 않는 습관을 기르는 것이 중요할 것 같아요! 👍

2022-08-24 08:45 UTC, finnn1 requested changes

2022-08-24 08:45 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/Enum.swift
> +//  Created by 유연수 on 2022/08/24.
주석을 지우거나, 혹은 프로젝트를 함께 하고있는 팀원의 이름을 적어보는 것은 어떻게 생각하시나요? ☺️👍

2022-08-24 08:45 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/Enum.swift
> +//  Enum.swift
enum을 별도의 파일로 분리하셨군요! 👏👏
일반적으로 파일의 이름은 내부에서 정의할 타입의 이름과 동일하도록 네이밍 하고 있으니 참고해주시면 좋을 것 같아요 ☺️

2022-08-24 08:45 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
55번째, 56번째 라인을 지나면 `userHandSign `와 `computerHandSign `에 무조건 값이 할당 되는 것으로 보이는데요!
이 51번째, 52번째 라인에서 `.rock` 으로 초기화를 해줄 필요가 있을까요? 🤔
`optional` 키워드로 찾아보시는 것을 추천드립니다. ☺️

혹시라도 정말로 여유가 되신다면 타입이 인스턴스화가 일어나면 메모리에서 어떤 일이 일어나는지도 알아보시면 좋을 것 같아요 👍

2022-08-24 08:46 UTC, merged

2022-08-24 10:41 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/Enum.swift
> +//  Created by 유연수 on 2022/08/24.
주석을 지우는 것으로 통일하였습니다! :)

2022-08-24 11:05 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
`userNumber`를 가져오는 과정에서 nil값이 없도록 처리를 해주기 때문에 `translateNumbersToHandSigns()`의 반환 데이터 타입을 힌트를 주신대로 옵셔널로 처리해도 문제가 없다고 생각했습니다.
step2부터는 아래와 같이 단순히 정수형 데이터를 HandSigns 타입으로 변환하는 기능만 하도록 수정하여 코드를 구현해볼 생각입니다! 
```swift
func translateNumbersToHandSigns(of input: Int) -> HandSigns? {
    return HandSigns(rawValue: input)
}
```

타입이 인스턴스화 되는 과정에 대해서도 알아보았는데, 아직 메모리 구조에 대한 학습이 부족한 상태라 시간이 조금 더 필요할 것 같습니다. 🥲
시간을 가지고 꼭 알아보도록 하겠습니다.