Lina solo1
yagom-academy/ios-rock-paper-scissors pull request #16
Opened 2020-11-06 03:37 UTC by lina0322

새로운 구조로 시도해보았습니다!

2020-11-06 07:32 UTC, yagom requested changes
고생 많았습니다~!
고민 많았겠어요 :)
몇몇 질문과 의견이 있습니다!

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Hand: Int {
empty 패가 있다는게 꽤 인상적입니다! 옵셔널을 사용하지 않고 empty case를 일부러 만든 이유가 있을까요?

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum PlayerIs: String {
enum의 이름을 다시 한 번 더 고민해보면 좋겠습니다.

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +var playerIs: PlayerIs = .draw
전역변수를 사용했을 때의 부작용은 없을까요? 어디서든 읽고 쓸 수 있습니다.
이름에 대한 고민도 다시 해보면 좋을 것 같아요.

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printInputErrorAndResartRPSGame() {
함수에 and를 사용하지 않도록 노력해보세요
함수는 한 가지 일만 하는 것이 좋습니다

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func checkWhoIsWinner(_ playerHand: Hand, vs computerHand: Hand) {
함수를 사용하는 입장에서는 함수의 정의부로 돌아오지 않는 한 첫 번째 전달인자가 사용자인지 컴퓨터인지 알기 어려울 것 같아요.
또, 이름은 개선의 여지가 있을 것 같아요.
determine... 정도를 사용해보면 어떨까요? 이름에 대한 것은 단순히 의견이고, 좀 더 좋은 방향이 있으면 개선해보면 좋겠습니다.

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return true // 1. 여기를 false로 해야하는 건지.. true로 해야하는 건지 모르겠어요
왜 모르겠을까요? 본인이 작성한 코드도 본인이 헷갈린다면 안됩니다. 좀 더 코드를 직관적으로 작성할 수 있도록 다시 고민해보면 좋을 것 같아요.
함수의 이름이 play...로 시작하는데 반환값이 있어요. 이 반환값이 무슨 역할을 하는지 함수의 이름만으로는 알 수가 없어서 더욱 직관적이지 못한 것 같은데 어떻게 생각하나요?

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    print("player: \(player) vs computer: \(computer)") // 값 확인용 출력, 삭제 예정
삭제 예정인 코드를 commit하면 안됩니다.
이게 정말로 사용자에게 배포될 코드라고 생각하고 작성해야합니다.
확인이 필요하다면 lldb 명령어 등을 통해 디버깅 하는게 좋습니다.
assert 등의 함수를 사용해도 좋아요.

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if playerIs == .draw { playRockPaperScissorsGame() }
if를 줄바꿈을 하는 경우도 있고 한 줄로 쓰는 경우도 있는데 나름의 규칙이 있는건가요?

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func palyMukchibaGame() {
가위 바위 보와 같이 play...로 시작하는 이름인데 이 친구는 반환값이 없군요

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +palyMukchibaGame()
함수 하나로 프로그램의 실행을 구현한 것의 시도가 좋습니다!

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("잘못된 입력입니다. 다시 입력해주세요.")
사용자를 배려한 안내 좋네요 :D

2020-11-06 07:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("잘못된 입력입니다. 다시 입력해주세요.")
같은 코드가 여러번 반복되고 있습니다. 개선할 여지가 있을까요?

2020-11-06 08:08 UTC, lina0322 commented
1. empty 패가 있다는게 꽤 인상적입니다! 옵셔널을 사용하지 않고 empty case를 일부러 만든 이유가 있을까요?
> player의 입력값이 잘못었는데도 뒤의 흐름을 따라가는 경우가 생길까봐 염려하여 작성했습니다.
아직 player가 패를 내지 않았는데, 하나로 지정해두었다가 값이 전달될까봐... empty를 사용하였고, 옵셔널을 사용하면 뭔가 뒤쪽에서 언래핑하는게 복잡해질 것 이라고 생각했습니다.

2. 왜 모르겠을까요? 본인이 작성한 코드도 본인이 헷갈린다면 안됩니다. 좀 더 코드를 직관적으로 작성할 수 있도록 다시 고민해보면 좋을 것 같아요.
함수의 이름이 play...로 시작하는데 반환값이 있어요. 이 반환값이 무슨 역할을 하는지 함수의 이름만으로는 알 수가 없어서 더욱 직관적이지 못한 것 같은데 어떻게 생각하나요?
3. 가위 바위 보와 같이 play...로 시작하는 이름인데 이 친구는 반환값이 없군요
> 처음에 play만 하기 위해서 작성한 후에 묵찌빠에서 사용하려고 하면서 반환값이 생겨났습니다. 이 과정에서 제가 혼돈이 있었던 것 같습니다. 이 부분도 play라고 진행할것이라면, 반환값이 없는 방법으로 고안해보겠습니다!

4. if를 줄바꿈을 하는 경우도 있고 한 줄로 쓰는 경우도 있는데 나름의 규칙이 있는건가요?
> if 의 {} 안에서 한 가지 일만 처리하고, 내용이 짧으면 한 줄로 쓰는 편입니다. 
전부 통일하여 줄바꿈을 하는 것이 가독성에 더 좋을까요..?

5. 같은 코드가 여러번 반복되고 있습니다. 개선할 여지가 있을까요?
> 제 고민중에 하나인데 똑같이 반복되지만 print("잘못된 입력입니다. 다시 시도해주세요.") 이렇게 한줄로 표현이 가능한데, 이 부분을 printInputError()처럼 함수로 만드는 것이 더 나을까요?? 말씀하신 부분이 func로 만들어서 사용하라는 건지, 아니면 흐름을 잘 짜서 같은 처리를 해야하는 부분이 한쪽으로 모이게(?) 하라는 뜻인지 잘 이해하지 못하였습니다ㅠㅠ!

6. 이름 짜기
> 이름을 짜는데 어려움이 많습니다. 이 부분을 개선하기 위해서 어떠한 방법을 사용하는게 좋을까요? 다른 사람들의 코드를 많이 읽어보는것이 좋을까요..? 단어를 선택하는 것이 어렵습니다..ㅠ_ㅠ

2020-11-06 08:32 UTC, yagom commented
1. 언래핑의 복잡함이 두려워 강력한 옵셔널을 사용하지 않는다면 스위프트의 절반을 잃는 셈입니다.
4. 항상 같은 스타일로 작성하면 문제 없습니다. 가독성은 사람마다 다른 기준이 있을 수 있으니까요. 이 부분은 협업하면서 서로 협의된 컨벤션으로 맞추는 것은 중요합니다. 즉, 팀 룰에 따라 항상 맞춰 작성하는 것이 중요합니다.
5. 이 부분에 대해서는 다른 캠퍼들과도 한 번 논의해보세요.
6. Swift API Design Guidelines의 Naming 파트를 정독해보면 어느정도 힌트를 얻을 수 있습니다. 또, Swift Library 혹은 Cocoa Touch Framework의 API 정의부를 잘 살펴보면 많은 도움이 됩니다. 처음부터 잘 할수는 없어요. 정말로 많이 고민해봐야 합니다. 아마 계속해서 더 많이 고민해봐야 할거예요.

2020-11-06 11:56 UTC, lina0322 commented
새로운 방식으로 도전해보았습니다...! 이렇게 하는 방법은 어떨까요..??

2020-11-06 14:15 UTC, yagom approved these changes
새로운 시도 좋아요.
작은 프로젝트이기 때문에 한 번에 갈아엎는게 허용될 수도 있지만 규모가 커질수록 어려워지겠죠?
그래서 처음부터 코드를 함수 단위로 작게 나눠서 진행하면 코드 몸통을 통채로 도려내는 수술의 빈도가 줄어들겁니다.
일주일 사이에 정말 많은 발전이 있었네요!
코드도 훨씬 직관적이고 읽기 좋아졌죠?
이번 프로젝트 피드백은 여기까지입니다.
남은 코멘트는 다음 프로젝트에서 고민하고 반영해보도록 해요 :)
코멘트 확인하고 답변할 것은 답변하고 Merge하면 됩니다.
이번 한 주 고생 많았습니다! 👍

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameState: String {
훨씬 낫네요!
그런데 state와 status의 차이는 무엇일까요?

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum WinnerState: String {
음... 아직 이름에 물음표가 있어요

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum SelectGame {
GameType은 어때요?

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +class MukchibaGame {
클래스와 구조체 중에 클래스를 선택한 이유가 있을까요?

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum WinnerState: String {
PlayerType?

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if playerHand == computerHand { gameState = .draw }
처음 코드보다 훨씬 직관적이고 읽기 편하지 않나요?

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        else if gameState == .lose { winner = .computer }
else를 사용하지 않고 else if를 사용한 이유가 있나요?

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
>          case "0":
여기의 문자열도 더 직관적으로 바꿔볼 수 있을 것 같아요 :)

2020-11-06 14:15 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mukchibaGame.playMukchibaGame()
MukchibaGame().playMukchibaGame()
으로 하지 않은 이유가 있을까요?
또, 앞으로 변경되지 않을 친구인데 변수인 var로 선언한 이유가 있을까요?
Xcode가 경고를 주지 않던가요?

2020-11-08 13:13 UTC, lina0322 commented
야곰, 감사합니다! 코멘트 해주신 부분들은 TIL에서 해결하겠습니다!
마지막 코멘트해주신 부분까지 수정하고 푸시한 다음에 merge하는 걸까요,
지금 merge하는걸까요...?
제가 merge를 할 수 있는건가요??
PR하는 방법 google docs보면서 따라했는데, 반응이 없어서요..!!

2020-11-08 15:09 UTC, merged