묵찌빠 게임 [STEP 2] 태리, 토털
yagom-academy/ios-rock-paper-scissors pull request #163
Opened 2022-08-23 07:45 UTC by tottalE

@minsson 안녕하세요 minsson! STEP2 완료하고 PR드립니다. 편안하게 지적해주실 부분 많이 지적해주세요 ㅎㅎ

## 고민했던 점

- set get을 함수명으로 사용하는 것에 대하여 이게 옳은 방법인지 궁금합니다!
- trun을 함수 파라미터 명으로 넣어줬는데, 더 나은 방법이 있을 지 궁금합니다! funtion(turn: turn)의 형태여서 마음에 걸려서요 ㅎㅎ
- 파일 명이 적절한지 궁금합니다!

## 추가적인 질문
- 해당 프로그램이 클래스와 스트럭트로 만들어지는게 알맞은지, 혹은 그냥 아래처럼 스크립같이 쓰는게 알맞은지 궁금합니다. 이 예시가 객체지향프로그래밍 예시에도 적합하다면 태리와 함께 클래스로도 한번 코드를 짜볼 생각입니다 어떻게 생각하시나요?

2022-08-24 15:53 UTC, minsson requested changes
안녕하세요! 토털이, 태리!

우선 멋진 코드 정말 잘 봤습니다.
보면서 많이 감탄했습니다!

칭찬은 디스코드에서 대화를 나누며 너무 많이 한 것 같으니, 바로 리뷰로 넘어가보겠습니다.

또, 이미 너무 많이 강조했지만, 코드에는 정답이 없으며, 제 생각은 당연히 정답이 아니며, 여기 작성하는 것은 모두 제 개인적인 견해일 뿐입니다 ☺️

## 1. 고민했던 점에 대한 피드백
질문하신 부분에 대해서는 그룹대화방에서 충분히 많은 대화를 나누었던 것 같습니다.
여기서는 아주 간략하게만 답변하겠습니다

### 1.1 네이밍 관련
말씀드렸던대로 네이밍 관련해서 제가 참고했던 글과 관련 영상 링크를 남깁니다.
[노수진님 네이밍 관련 글](https://soojin.ro/blog/english-for-developers-swift)
[노수진님 발표 영상](https://tv.naver.com/v/4980432/list/267189)

### 1.2 파일명
곧 타입명으로 파일명을 작성하게 될테니 지금 크게 고민하지 않아도 되는 부분 같습니다.

### 1.3 묵찌빠와 가위바위보의 로직 중복
토털이가 화면 공유로 보여주셨던 것처럼, 두 로직을 합쳐 만드신 함수는 분기가 너무 많아 가독성이 좋지 않아 보였습니다. 묵찌빠와 가위바위보는 `switch-case`문의 구조는 비슷하지만 승패를 판정하는 로직과 게임이 진행되는 흐름도 달라, 별개의 게임이라고 생각할 수 있을 것 같습니다.

반면 현재 PR에 작성해주신 묵찌빠와 가위바위보 승패 결정 함수는 규칙을 알고, 스위프트 문법을 조금만 알면 누구나 막힘 없이 읽을 수 있을 정도로 가독성이 좋다고 생각합니다. 

또, 가독성을 희생해서 퍼포먼스를 유의미하게 끌어올릴 수 있다면 의미있는 트레이드 오프가 될 수도 있지만, 아시다시피 지금 프로젝트에서 퍼포먼스를 논하는 건 의미가 없다고 생각합니다.

물론 선택은 여러분들의 자유입니다!

## 2. 추가적인 질문에 대한 답
현재 코드에서는 객체간의 소통이 진행되기는 애매할 것 같아, 굳이 클래스나 구조체로 만들어야만 할 이유는 없다고 생각합니다. 하지만 하면 안될 이유도 없죠! 연습할 겸 해보는 것도 좋다고 생각합니다!

## 3. 제가 드리고 싶은 질문
### 3.1 클래스 vs 구조체
클래스와 구조체 중 무엇을 선택해서 구현하실 생각인가요? 둘의 차이는 무엇인가요? 

### 3.2 확장성과 오버엔지니어링에 대한 질문
이 프로젝트에서 제가 과거에 작성했었던 코드도 보고, 그때 했던 고민도 떠올릴 수 있었습니다.
여러분의 코드와 함께 보며 각 코드의 장단점에 대해 여러 생각이 들기도 했고, 여러분의 코드가 간결하고 깔끔해서 저도 많이 배울 수 있었습니다.

특히 `확장성을 고려한 코드`와 `오버엔지니어링`에 대해 생각해볼 수 있었습니다. 

이 키워드에 대해 여러분은 어떻게 생각하시나요? 비록 지금 진행하는 프로젝트는 연습용 프로젝트라 이런 키워드가 어울리지 않는다고 생각하실 수 있지만, 그때의 저는 `확장성`에 진심이었는데, 지금 생각해보면 방향을 잘못 잡아 이상한 오버엔지니어링을 해버렸던 것 같습니다.

여러분은 이 코드를 작성할 때 이 부분에 대해 고민하신 적이 있나요? 여러분의 생각이 궁금합니다!

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
함수의 네이밍을 보면 `가위바위보를 출력한다`로 보입니다. 그런데 출력하는 문장을 보면 유저에게 선택지를 제시하는 메뉴로 보여 혼동을 줄 수 있을 것 같네요! 👀

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
여기도 `printRockScissorPaper()`와 마찬가지로 함수의 네이밍과 실제 출력하는 문장의 차이가 느껴집니다.
또, MGP는 무엇의 약자인지 이해하기 어려운 측면도 있을 것 같습니다. 

[API Design Guidelines - Naming](https://www.swift.org/documentation/api-design-guidelines/#naming)을 다시 한번 읽어보면 좋겠네요 ☺️

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
`get`에 대한 제 의견은 그룹대화방에서 말씀드린 바와 같습니다! 판단은 여러분 자유입니다 😁

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
`UserHandNumber`라는 네이밍이 적절한지 고민됩니다. 선택지 `0`, 즉 `종료`도 있는데 이것도 포함할 수 있는 네이밍일까요? 😲

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
무척 깔끔해보입니다! 다만 `validate`라는 단어를 쓰는데 타입도 바꿔주고 있네요. 함수의 기능분리와 네이밍 측면에서 아쉬운데 코드가 너무 깔끔해보여서 저도 특정한 방향성에 대해 말씀드리기가 조심스럽네요. 여러분은 어떻게 생각하시나요? 😯

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +          let computerHand = HandType(rawValue: Int.random(in: 1...3))
너무 깔끔하고 좋네요..! 👏👏👏👏👏

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
이 함수도 `validateUserHandNumber(input:) -> Int?`와 비슷한 맥락에서 `setHandType`이라는 네이밍에서 `게임 종료` 여부까지 판단하는 게 적절한지 잘 모르겠습니다. 여러분은 어떻게 생각하시나요?

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
함수의 네이밍 측면에서 어떤 곳에서는 `RSP`를 풀어서 쓰고, 이렇게 줄여서 쓰기도 하는 것 같은데요. 혹시 어떤 기준으로 결정하신 건가요? 😲

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
그리고 내부 구조 정말 깔끔하다고 생각합니다..! 👏👏👏👏👏
특히 case let, where를 너무 깔끔하게 써주셔서 놀랐습니다..! 👏👏👏👏👏

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
사용자의 승리와 관련된 case에서 `:` 앞에 불필요한 공백이 하나 있네요!

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
바로 앞의 함수와 완전히 동일한 피드백을 적용할 수 있을 것 같습니다!

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/HandType.swift
> +import Foundation
`Foundation`을 `import`한 이유는 무엇인가요?
그리고 `Foundation`의 역할은 무엇인가요? 👀

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Turn.swift
> +import Foundation
`Foundation`을 `import`한 이유는 무엇인가요?
그리고 `Foundation`의 역할은 무엇인가요? 👀

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
`Foundation`을 `import`한 이유는 무엇인가요?
그리고 `Foundation`의 역할은 무엇인가요? 👀

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/main.swift
> +func startGame() {
다른 함수들과 달리 `startGame()`과 `playMGP(turn:)`만 `main`에서 정의하고 있는 이유는 무엇인가요?

2022-08-24 15:53 UTC, minsson commented on RockPaperScissors/RockPaperScissors/main.swift
> +startGame()
다른 함수들의 정의부를 다른 파일로 분리하여 `main`파일이 깔끔해졌네요! 👏👏👏

2022-08-25 01:57 UTC, lxodud commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
printRockScissorPaperMenu()로 수정하였습니다!!

2022-08-25 01:58 UTC, lxodud commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
printMukZiPaMenu()로 수정하였습니다!!

2022-08-25 02:55 UTC, lxodud commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
userInput()이라는 네이밍으로 수정하였습니다!!

2022-08-25 03:02 UTC, lxodud commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
validate함수인데 타입도 변환해서 리턴하는 것이 맞지 않다고 생각돼서 타입 변환을 다른 함수로 기능 분리해봤습니다. 
```swift
func validateUserInputNumber(input: String?) -> Bool {
    guard let input = input,
          let userInputNumber = Int(input),
          userInputNumber <= 3,
          userInputNumber >= 0
    else {
        return false
    }
    return true
}

func makeStringToInt(_ input: String?) -> Int? {
    guard let input = input else { return nil }
    return Int(input)
}
```
Int 변환이 중복되어서 고민인데 어떻게 생각하시는지 궁금합니다.
validate라는 네이밍에서 Bool타입이 아닌 다른 타입의 값을 리턴하는게 어색하다고 생각하셨는지도 궁급합니다!!

2022-08-25 03:05 UTC, lxodud commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
```swift
func setHandType(_ userHandNumber: Int) -> (HandType, HandType)? {
    guard let userHand = HandType(rawValue: userHandNumber),
          let computerHand = HandType(rawValue: Int.random(in: 1...3))
    else {
        return nil
    }
    return (userHand, computerHand)
}
```
위 함수에서 게임 종료 여부를 판단하는게 적절하지 않다고 생각되어서 startGame()에서 종료 여부를 판단하도록 분리하였습니다!!

2022-08-25 10:55 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
사실 민쏜이 말해주기 전까지는 기준이 없었습니다. 허허 그런데 이번 계기로 전부 풀어쓰는것으로 통일했습니다!!

2022-08-25 10:55 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
공백 지워줬습니다 감사합니다!!

2022-08-25 10:55 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
네 공백 지워줬습니다 ㅎㅎ!!

2022-08-25 10:56 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/main.swift
> +func startGame() {
저희가 생각하기에 게임을 실행하는 두개의 메인함수라고 생각하여 그렇게 작성하였습니다!!

2022-08-25 10:56 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/main.swift
> +startGame()
감사합니다 !!

2022-08-25 11:03 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/HandType.swift
> +import Foundation
foundation에 대해서 공식문서를 읽어보니 Int와 String과 같은 타입들도 포함하고 있는데, foundation 없이도 프로그램이 돌아가는 이유가 저희도 궁금한 상황입니다...!! foundation이 스트링과 인트처리 그리고 많은 네트워크나 여러가지 기능들을 포함하는 라이브러리라는 것 까지는 이해가 갔는데 String과 Int 또한 포함되어 있는데 어떻게 실행이 되는지 저희도 궁금합니다!!
그리고 이런 경우 어떻게 잘 찾아서 프레임워크를 이해할 수 있을까?도 저희가 궁금한 부분입니다!

2022-08-25 11:03 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/Turn.swift
> +import Foundation
위와 같은 답변입니다!!

2022-08-25 11:03 UTC, tottalE commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
위와 같은 답변입니다!!

2022-08-26 02:44 UTC, tottalE commented
- 코드를 다시 살피던 중 userHand의 순서가 다르다는 것을 깨달았습니다! 가위바위보는 가위, 바위, 보 순이고, 묵찌빠는 바위, 가위, 보 순이라는 걸 놓쳤었네요! 그래서 userHand의 값을 할당해주는 static func를 enum안에 만들어주어 문제를 해결하였습니다. 
- 게임 종료의 경우도 분리하여 0일때 종료할 수 있도록 하였습니다!
- 시간이 없어 구조체와 클래스로 구현하지는 못했습니다 ㅠㅠ (대신 공식문서 공부에 더 많은 시간을 할애하기로 하였습니다) 하지만 이 경우 저희는 같은 기능들을 상속받는 구조로 구현해보고 싶었기 때문에 클래스를 사용하고 싶었습니다! (validate와 게임종료 기능 등등) 클래스의 경우 reference 타입이고 struct는 값 타입이라는 차이점이 있지만, 이 경우 상속이 중요하다고 생각하여 클래스를 사용하는 편이 낫다고 생각하였습니다!! 민쏜은 클래스와 구조체를 사용할때 어떤 기준으로 사용하시는지 궁금합니다!
- 확장성과 오버엔지니어링의 경우 저희가 단순해서 그런지 전혀 생각하지 못한 부분이라 저희도 고민이 많았습니다. 확장성을 고려한 코드에 대해서 생각했을 때 제일 먼저 매직 리터럴이 떠올랐습니다. 현재 코드에서 1~3을 바로쓰는 부분을 변수로 치환해서 사용한다면 다른 요구사항이 생겼을 때 리팩토링하기 더 쉽고 가독성도 더 좋아진다고 생각합니다. 민쏜은 어느 부분까지 확장성을 고려하셨는지 궁금합니다!!

2022-08-27 06:35 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
말씀해주신 고민이 생긴 이유는 input을 String 타입으로 갖고 있기 때문이라고 생각합니다. input을 받은 이후의 로직에서는 계속 Int 타입을 쓰므로, input을 받은 후에는 Int 타입으로 형변환해서 들고 있으면 편할 것 같습니다! ☺️

2022-08-27 06:38 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
`isValid` 라는 말이 포함된 Bool 타입 변수가 자주 쓰이는 편입니다.
그래서 validate라는 단어를 봤을 때 Bool 타입을 리턴할 것이라고 생각했어요.

2022-08-27 06:38 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
isValid 라는 말이 포함된 Bool 타입 변수가 쓰이곤 합니다.
그래서 validate라는 단어를 봤을 때 Bool 타입을 리턴할 것이라고 생각했어요.

2022-08-27 06:38 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RocksScissorPaperFunc.swift
> +}
`isValid` 라는 말이 포함된 Bool 타입 변수가 쓰이곤 합니다.
그래서 validate라는 단어를 봤을 때 Bool 타입을 리턴할 것이라고 생각했어요.

2022-08-27 06:40 UTC, minsson commented on RockPaperScissors/RockPaperScissors/HandType.swift
> +import Foundation
그룹대화방에서 설명드렸으므로 여기서의 답변은 생략하겠습니다.
다음에 보실 때 [Swift](https://developer.apple.com/documentation/swift)를 참고하시면 됩니다! 😁

2022-08-27 06:54 UTC, minsson approved these changes
안녕하세요! 토털이, 태리! ☺️

그룹대화방 음성대화로 전체적으로 답변드렸으므로, 여기서는 나중에 참고하실 수 있도록 간략하게 답변하겠습니다.

### 1. 가위바위보, 묵찌빠 타입
지금 작성하신 것처럼 해주셔도 되고, 가위바위보 타입과 묵찌빠 타입을 나눠도 된다고 생각합니다.
또, 가위바위보 게임의 인풋을 받는 타입, 묵찌빠 게임의 인풋을 받는 타입으로 나누어 0, 1, 2, 3이라는 경우의 수를 모두 고려할 수도 있을 것 같습니다.

### 2. 클래스 vs 구조체
#### 우선은 아래 링크를 기준으로 생각하시면 됩니다.
[Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)
####  아래 링크는 지금 보면 너무 혼란스러우므로 4~5개월 후에 보시는 걸 추천합니다!
[WWDC2016 - Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)

### 3. 확장성과 오버엔지니어링
화면공유를 통해 다른 코드와 비교하며 자세히 설명드렸으므로 여기서는 생략하겠습니다!
결과적으로 예전에 제가 작성했던 코드에 비해 아주 깔끔하게 잘 작성하셨다는 이야기였습니다 ☺️

---


Step 2 리팩토링 진행하시느라 고생하셨습니다! ☺️
다음 프로젝트도 화이팅이에요! 💪

2022-08-27 06:55 UTC, merged