[STEP 1] Wonbi, 미니
yagom-academy/ios-rock-paper-scissors pull request #164
Opened 2022-08-23 08:06 UTC by leegyoungmin

@yeeton37 안녕하세요!! 예톤 저희가 많은 고민을 하다 보니까 거의 저녁이 됐네요 ㅜㅜ

### STEP 1
#### 순서도
![flowCharts](https://i.imgur.com/NX7XYB8.png)

#### 고민했던 점

1. `Protocol`을 채택한 이유는 활동학습에서 배웠던 캡슐화를 한번 시도해보고 싶어서 사용해 보았습니다. 또한 Step2에 있는 묵찌빠 게임과 분리하기 위해 사용하였습니다. 이런 방식으로 사용하는 게 맞을까요?
    - 가위바위보 게임과 구분되는 묵찌빠 게임 파일을 생성할 예정이고, 이에 대해서 공통적으로 가지고 있어야 하는 함수인 `startGame` 이라는 함수만 우선적으로 생성하였습니다.

2. `CardType` 내부에 구현되어 있는 `compare` 메소드가 다른 코더의 입장에서 직관적이지 못하다고 생각하여서, 직접 `enum`을 비교하는 방법과 고민하였습니다. 저희 생각에는 다른 코더가 `compare` 라는 메소드를 타고 들어왔을 때, 안에있는 로직과 `compare`의 반환 값을 보고 충분히 유추가 가능할 것이라 판단하여 `compare` 메소드를 그대로 사용하였습니다.

#### 궁금한 점
1. CardType에서 rawValue를 활용하여 함수를 작성하는 것이 가독성에 영향을 주는 지 궁금합니다.
    ```swift
    enum CardType: Int {
        ...
        
        func compare(to computerCard: CardType) -> GameState {
            let userNumber = self.rawValue
            let computerNumber = computerCard.rawValue
            let comparedResultNumber = userNumber - computerNumber

            switch comparedResultNumber {
            case -2, 1:
                return .win
            case -1, 2:
                return .lose
            default:
                return .draw
            }
        }
    }
    ```

2. ComputerNumber를 생성하는 과정에서 rawValue를 통해서 CardType을 초기화 할때, Optional로 생성되는 문제를 해결하기 위해서 case none을 추가하였는데, 이외에 다른 해결 방법이 있는지 궁금합니다.

    ```swift
    enum CardType: Int {
        case none = 0
        case scisser = 1
        case rock = 2
        case paper = 3
        ...
    }
    ```
    - none 케이스에 0을 할당하고 다음 케이스에 따로 Int값을 할당하지 않으면 자동으로 `+= 1` 씩 되어 할당하는 것을 알고 있었지만, 좀 더 값을 직관적으로 보이게 하고 싶어서 직접하나하나 할당을 해주었습니다.

3. 사용자가 잘못된 입력을 할 경우, 다시 입력 받는 함수를 실행하는 재귀 함수로 구현 하였지만 사용자의 반복적인 오류 입력에 의한 Stack Over Flow 를 방지하는 방법이 있는지 궁금합니다.

    ```swift
	private func handleInputError(_ error: InputError) {
		print(error.description)
		if error == .invalidNumber {
			startGame()
		}
	}

	private func checkGameResult(userCard: CardType) {
		let computerCard = generateComputerCard()
		
		let result = userCard.compare(to: computerCard)
		
		print(result.description)
		if result == .draw {
			startGame()
		}
	}
    ```

4.  Error 프로토콜을 채택한 InputError에서 ExitGame이라는 에러를 생성하는 것이 적절하지 않다고 생각하는 데 어떻게 생각하시는 지 궁금합니다.
    ```swift
    enum InputError: Error {
        case invalidNumber
        case exitGame

        var description: String {
            switch self {
            case .invalidNumber:
                return "잘못된입력입니다. 다시 시도해주세요."
            case .exitGame:
                return "게임 종료"
            }
        }
    }
    ```

2022-08-24 06:15 UTC, yeeton37 requested changes
안녕하세요!
미니, Wondi 두 분 모두 STEP1 고생하셨습니다 😋

PR에 올려주신 순서도와 고민했던 점 모두 잘 정리해주셔서 보기 좋았어요 
코드를 깔끔하게 잘 작성해주시고 구현 사항 모두 잘 지키셨네요 칭찬합니다!👏

말씀해주신 고민한 점과 궁금한 점에 대한 답변은 아래에 적어놓았습니다.
리뷰에 대해서 궁금증이나 다른 의견을 가지고 계신 부분은 언제든 말씀해 주세요!

## 🥰 칭찬드리고 싶은 점
- 순서도를 완벽하게 짜셨네요 🥇
- 활동학습때 배웠던 것을 적용하려고 노력하신 점이 정말 좋아요 🥇
- 다소 어려울 수 있는 개념인 Result 타입과 프로토콜을 벌써 사용하시다니 대단해요..! 🥇
    - 나중에 네트워킹을 배우시게 되면 Result 타입과 프로토콜을 많이 사용하실 거에요. 미리 적용해보신 것 정말 도움이 될 것 같네여.
- 하드코딩을 하지 않으시고 enum으로 묶어서 한 곳에서 처리해주신 점 좋았습니다 🥇
- 메서드 분리를 잘 해주셔서 메서드가 한가지 일만 수행하고 있는 것 좋아요. 굿. 🥇


## 🧐 고민하신 점에 대한 답변

> 1. Protocol을 채택한 이유는 활동학습에서 배웠던 캡슐화를 한번 시도해보고 싶어서 사용해 보았습니다. 또한 Step2에 있는 묵찌빠 게임과 분리하기 위해 사용하였습니다. 이런 방식으로 사용하는 게 맞을까요?
    - 가위바위보 게임과 구분되는 묵찌빠 게임 파일을 생성할 예정이고, 이에 대해서 공통적으로 가지고 있어야 하는 함수인 startGame 이라는 함수만 우선적으로 생성하였습니다.
    

- 벌써 프로토콜을 사용하시다니 대단하네요. 위에서 시도해보고 싶다고 말씀해주신 `캡슐화`는 혹시 `추상화`를 말씀하신 것일까요?
    - 맞다면 추상화라는 키워드에 대해 더 공부해보시면 좋을 것 같아요. 
    - 추상화는 사실 저에게도 아직까지 매우매우 어려운 개념이고, 적용하는 데 생각할 시간이 많이 필요해요. 프로토콜을 통해 추상화하는 방법이 잘 나와있는 wwdc 영상이 있는데, 조금 어려울 수도 있어서 시간이 되실 때 한번 보시면 좋을 것 같아요. 지금 이해하지 못하는 것이 정상입니다ㅋㅋ
[참고 링크](https://developer.apple.com/videos/play/wwdc2022/110352/)

- 또한 공통적으로 가지고 있어야 하는 함수인 `startGame`을 프로토콜로 구현해주신 점 아주 칭찬해요! 추후에 step2의 묵찌빠게임 파일도 생성하실텐데, 이때 가위바위보 게임과 같은 기능을 하는 함수나 프로퍼티가 있다면 구현하신 프로토콜 내에 추가해주시면 좋을 것 같아요!


> 2. CardType 내부에 구현되어 있는 compare 메소드가 다른 코더의 입장에서 직관적이지 못하다고 생각하여서, 직접 enum을 비교하는 방법과 고민하였습니다. 저희 생각에는 다른 코더가 compare 라는 메소드를 타고 들어왔을 때, 안에있는 로직과 compare의 반환 값을 보고 충분히 유추가 가능할 것이라 판단하여 compare 메소드를 그대로 사용하였습니다.

- 다른 코더의 입장까지 고려해주셨다니, 유의미한 고민이네요. 결론적으로 저는 직접 enum을 비교하는 방법과 enum 내부에 compare 메서드를 작성한 방법 모두 괜찮은 방법이라 생각해요. 원비와 미니가 작성해주신 코드를 읽었을 때 저는 `let result = userCard.compare(to: computerCard)` 는 컴퓨터 패와 사용자 패를 비교하는 코드라는 것이구나를 직관적으로 이해할 수 있었어요. 코드는 자신이 그렇게 작성한 이유가 있으면 그게 정답입니다. 
- 그나저나 벌써 enum 내부에서 self 키워드를 통해 메서드를 구현하는 것까지 하시다니 멋져용~
   
  


## 📚 궁금한 점에 대한 답변

> 1. CardType에서 rawValue를 활용하여 함수를 작성하는 것이 가독성에 영향을 주는 지 궁금합니다.
- rawValue를 일일이 지정해서 사용해도 되고, 아래와 같이 작성해줄 수도 있습니다.

```swift
enum CardType: Int {
     case none = 0
     case scissors = 1
     case rock = 2
     case paper = 3

     var number: Int {
         return self.rawValue
     }
```

- 위의 코드는 enum 내부에 연산 프로퍼티를 작성해주어 외부에서 `CardType.rock.number` 와 같이 부를 수 있도록 해준 것입니다. 
- `연산 프로퍼티`라는 개념에 대해 공부해보시면 좋을 것 같네요. 저 같은 경우에는 rawValue를 직접 써주기 보단 위의 방식을 자주 사용합니다. rawValue를 통해 int 타입인지 string 타입인지 유추하는 것보단 number와 같이 더 정확한 이름으로 호출해줄 수 있기 때문이죵


> 2. ComputerNumber를 생성하는 과정에서 rawValue를 통해서 CardType을 초기화 할때, Optional로 생성되는 문제를 해결하기 위해서 case none을 추가하였는데, 이외에 다른 해결 방법이 있는지 궁금합니다.

- 코드상에서 아래 부분이 맞겠죠? 다음 번에는 질문 주실 때 코드로 같이 적어주시면 훨씬 수월하게 질문을 파악하기 좋을 것 같습니다 🤗🤗
```swift
private func generateComputerCard() -> CardType {
		let randomNumber = Int.random(in: 1...3)
		guard let computerCard = CardType(rawValue: randomNumber) else {
            return .none
        }
		return computerCard
	}
```
- 이 부분은 반환 타입인 CardType 형식을 맞춰주기 위해서 guard let 구문에서 return을 해줄 때 .none을 어쩔 수 없이 사용하신 것 같아요. 이렇게 되면 randomNumber가 1부터3이 아니라면 .none, 즉 0을 반환하게 되는데 이게 맞는 로직일까요?🤔 한번 고민해보시면 좋을 것 같아요! 
- 제 생각에는 이럴 경우에는 에러를 던지거나, nil을 반환하는 것이 로직상 맞는 것 같네여. 반환 타입인 CardType을 옵셔널로 변경해준 뒤에 return nil을 해주는 것도 하나의 방법 같아요. 나중에 컴퓨터 패와 사용자 패를 비교하는 부분에서 옵셔널 바인딩을 해주면 되지 않을까요~?


> 3. 사용자가 잘못된 입력을 할 경우, 다시 입력 받는 함수를 실행하는 재귀 함수로 구현 하였지만 사용자의 반복적인 오류 입력에 의한 Stack Over Flow 를 방지하는 방법이 있는지 궁금합니다.

- 일반적인 재귀함수는 함수를 호출할 때 연산정보를 스택에 쌓으며 계산을 하지만, 꼬리재귀를 사용하면 스택에 쌓지 않고 바로 다시 함수를 실행시키는 방법을 사용합니다.
- `꼬리재귀`라는 키워드를 한번 공부해보시면 좋을 것 같아요! 스택 오버플로우까지 생각하시다니 굿굿

> 4. Error 프로토콜을 채택한 InputError에서 ExitGame이라는 에러를 생성하는 것이 적절하지 않다고 생각하는 데 어떻게 생각하시는 지 궁금합니다.
- 이 부분은 아래 코멘트에 달았습니다 😁

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +class RockPaperScissors: GameAble {
클래스를 사용하셨네요!
레퍼런스 타입과 값타입에 대해서 잘 알고 계실까요?

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		checkValidable(of: userCard)
함수 호출 순서대로 함수의 구현부 위치를 옮겨주면 가독성이 훨씬 좋아질 것 같아요!

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
`"가위(1), 바위(2), 보(3)! <종료 : 0> : "` 같은 게임 메시지를 enum으로 한번에 관리해보면 좋을 것 같아요. 
`네임스페이스`라는 키워드에 대해 찾아보시면 좋을 것 같습니다!

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +			  0...3 ~= inputedNumber else { return .failure(.invalidNumber) }
~= 라는 범위 연산자를 사용해주셨군요! 좋네요 👏👏

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +			return .failure(.exitGame)
사용자가 0을 입력한 경우는 게임 종료를 하는 것이지 에러라고 보기는 어려울 것 같아요. 0을 입력한 경우뿐만 아니라 게임에서 이기거나 질 때도 게임 종료를 출력해야 할텐데, 이것을 에러라고 보기는 쪼금 힘들 것 같네요 🥲 어떻게 해주면 좋을까요~?

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +	private func fetchUserInput() -> Result<CardType, InputError> {
벌써 Result 타입을 사용하시다니, 원비 미니 쵝오입니다!

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +	private func checkValidable(of userInputedResult: Result<CardType, InputError>) {
Validable이라는 단어가 제가 구글에 검색했을 때는 나오지 않네요..?🤔 사용하신 이유가 있을까요 
타당성, 유효성을 의미하는 validity는 어떨까요?

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/main.swift
> +protocol GameAble {
protocol은 여러 객체들에 대하여 범용적이면 좋습니다. (최소 2개 이상)
묵찌빠와 가위바위보 객체에서 둘 다 사용해주려고 생성해주셨군요. 

또한 프로토콜 네이밍은 보통 `Gameable`와 같이 사용해줍니다.

아래 링크를 참고해보세요!
[참고 문서](https://gist.github.com/godrm/d07ae33973bf71c5324058406dfe42dd)

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Models/InputError.swift
> +			return "잘못된입력입니다. 다시 시도해주세요."
띄어쓰기!! 👀

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Models/InputError.swift
> +			return "게임 종료"
위에서 말했듯이 게임 종료 부분은 가위바위보를 이기거나 질때도 출력해야 하기 때문에 에러 부분에서는 제외해주는 것이 좋지 않을까요?

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Models/CardType.swift
> +            return .draw
위에서 말했던 부분과 동일한 코멘트이지만, 한번 더 말씀드립니다!
만일 작성해주신대로라면 user가 1~3 사이의 값을 입력하지 않았다면, return으로 .none이 되고, 이는 추후에 이 switch문에 들어오게 되면
default로 처리가 되어 비기는 문구를 출력하게 될 텐데, 이는 확실히 로직상의 오류인 것 같네요..! 수정이 필요해보입니다!

2022-08-24 06:15 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +			  0...3 ~= inputedNumber else { return .failure(.invalidNumber) }
gurad-let의 줄바꿈 부분은 [참고링크](https://github.com/StyleShare/swift-style-guide#줄바꿈) 을 참고해보세요!

2022-08-24 07:16 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		checkValidable(of: userCard)
네 옮겼습니다!

2022-08-24 07:17 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		checkValidable(of: userCard)
GameMessage 타입으로 네임 스페이스를 구성하고 게임의 상태에 따른 description과 게임에 필요한 게임 메시지도 포함하여서 구성하였습니다.

2022-08-24 07:17 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
네임 스페이스에 대해 공부하는 시간을 가졌습니다.
네임스페이스를 활용해서 메세지를 관리하면 한번만 메세지를 수정해도 모두 적용되니 유지보수하기 더 편해진거 같아요!

2022-08-24 07:17 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
GameMessage 타입으로 네임 스페이스를 구성하고 게임의 상태에 따른 description과 게임에 필요한 게임 메시지도 포함하여서 구성하였습니다.

2022-08-24 07:19 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +	private func checkValidable(of userInputedResult: Result<CardType, InputError>) {
네! 메서드 이름 수정하였습니다!

2022-08-24 07:20 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +	private func checkValidable(of userInputedResult: Result<CardType, InputError>) {
그러게요... 저희도 검색해보니 단어가 없네요 ㅜㅜ 오타였던 것 같습니다.
수정하여서 커밋하였습니다.

2022-08-24 07:20 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Models/InputError.swift
> +			return "잘못된입력입니다. 다시 시도해주세요."
넵!! 수정하였습니다

2022-08-24 07:21 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Models/InputError.swift
> +			return "잘못된입력입니다. 다시 시도해주세요."
앗.. 실수..!😅

2022-08-24 07:21 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +protocol GameAble {
일단 묵찌빠와 가위바위보 사이에서 어떤 메소드가 중복으로 사용되는지를 직접 묵찌빠를 구현하면서 확인해보고, 그다음 프로토콜을 구현하고자 일단은 프로토콜을 지웠습니다! 이후 step2에서 네이밍 시 참고 하겠습니다!

2022-08-24 07:22 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Models/InputError.swift
> +			return "게임 종료"
넵 수정하였습니다!

2022-08-24 07:24 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Models/CardType.swift
> +            return .draw
이부분 말씀해주신 부분 참고하여 `none` 케이스의 경우 `guard`문을 통해 `.exit`값이 반환되도록 수정하였습니다!

2022-08-24 07:30 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +			return .failure(.exitGame)
저희도 생각해보니 0이 에러일 경우가 아니라는 점을 알게 되었습니다.
`inputNumber`가 0이 들어와도 초기화가 가능하기 때문에 `RPS.none` 케이스로 만든 후 `RPS.compare 함수`에서 `guard` 구문을 통해서 `GameState.exit` 값을 반환하도록 하였습니다.

2022-08-24 07:33 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +			  0...3 ~= inputedNumber else { return .failure(.invalidNumber) }
참고 링크를 통해서 서로 컨벤션에 대한 의논을 하였고, `guard-let` 구문의 길이가 길어지는 경우는 개행하는 걸로 결정했습니다. 하지만, 조건이 한개이고 구문이 짧은 경우는 한 줄에 작성하도록 결정하였습니다.

2022-08-24 07:54 UTC, leegyoungmin commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +class RockPaperScissors: GameAble {
레퍼런스 타입은 스택 영역에 포인터만 저장하고, 실제 값은 힙영역에 저장됩니다. 값 타입의 경우, 인스턴스 모두가 힙영역에 할당됩니다.
묵찌빠 게임에서 가위바위보 게임을 상속할 지 잘 모르는 상태였기 때문에 class로 구현하였었습니다. 하지만, 추가적인 상속이 없다고 판단하여 struct로 수정하였습니다.

2022-08-24 08:17 UTC, wonbi92 commented
@yeeton37 
안녕하세요 예톤! 자세한 피드백 정말 감사드립니다! 많은 공부가 되었습니다!

## 🤔 고민한 부분

### 묵찌빠 단계로 넘어가기 위한 준비
- 리팩토링 과정에서 묵찌빠 게임으로 넘어가는 단계에 대한 고민을 많이 하였습니다. 처음에는 가위바위보를 클래스로 처리해서 묵찌빠 클래스가 가위바위보를 상속받는 방식으로 구현 하려고 했는데, 이 방법 보다는 모듈화를 통해 각 게임이 독자적인 인스턴스를 가지고 그 인스턴스들을 한번에 처리하는 방식으로 구현하기로 결정하였습니다. 그에 맞게 코드를 수정하는 과정에서 게임의 대한 결과물을 반환하는 모듈과 게임에 대한 사용자의 입력을 처리하는 모듈로 다시 구분하여 구현하게 되었습니다. 그 결과 필요없는 메서드들이 정리가 되기도 하고, 어쩔 수 없이 여러번 유효성을 체크하는 과정이 많이 줄어들게 된거 같아 좋은 판단이었다고 생각합니다.

## 👀 조언을 얻고 싶은 부분

### 모듈화?
- 위에서 고민한 내용이 정말 이전에 사용하던 방식보다 좋은 방식인지에 대한 고민이 있었습니다. 사실 저희가 리팩토링 과정에서 모듈화라는 부분을구현하는 과정에서 거의 모든 코드를 수정하게 되었는데 저희는 이 방법이 유지보수나 step2에서 구현할 묵찌빠를 좀 더 쉽게 구현할 수 있는 방법이라 생각하고 이런 결정을 내리게 되었습니다. 이 결정이 옳은 결정인지가 궁금합니다.

2022-08-24 10:19 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +class RockPaperScissors: GameAble {
아주 잘 이해하셨네요! 하지만 값 타입의 경우는 인스턴스가 힙영역이 아닌 스택영역에 할당이 됩니다!

정리하자면, 구조체와 클래스 모두 인스턴스를 선언 할 시 스택의 영역에 들어가게 됩니다. 하지만, 구조체는 스택의 영역에 값이 들어가고, 클래스는 힙 영역에 값이 들어가고, 그 주소값이 스택에 저장됩니다. 

이 개념은 앞으로 캠프생활 하시면서 무수히 많이 공부하실 것이기 때문에 이번 기회에 확실히 개념을 잡고 가시면 편하실거에요! 😃

2022-08-24 10:20 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +		print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
오, GameMessage 타입의 네임스페이스를 만들어주셨군요. 아주 좋습니다!!

2022-08-24 10:24 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RockPaperScissors.swift
> +			  0...3 ~= inputedNumber else { return .failure(.invalidNumber) }
컨벤션을 따르되, 팀원 간 `조건이 한개이고 구문이 짧은 경우는 한 줄에 작성하도록` 규칙을 정하신 점 정말 좋네요!
앞으로도 코드를 작성하실 때 팀원 간의 규칙을 정하시고, 그에 대한 타당한 이유만 있다면 좋을 것 같습니다.

2022-08-24 10:54 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RPSGameManager.swift
> +	private func fetchUserInput() -> Result<RPS, InputError> {
`fetchUserInput`에서 접근 제어를 붙여준 뒤 `startGame`에서 사용하여 구현부를 수정하지 못하도록 캡슐화해주었군요!  💯

2022-08-24 10:54 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/RPSGameManager.swift
> +class RPSGameManager {
RPSGameManager 라고 해서 RPS가 뭐지..? 했네요😁
축약형은 지양하는 것이 좋습니다! 저희끼리만 이해할 수 있기 때문이죠ㅋㅋㅋ 
너무 길다면 `RockPaperScissorsManager` 이런 식은 어때요?

2022-08-24 10:54 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Models/RPS.swift
> +	}
CaseIterable과 allCases을 사용해주셨군요! 🤓👍👍 

self와 Self의 차이점을 알고 계신가요??

2022-08-24 10:54 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/main.swift
> +			startConsole()
```swift
case .draw, .error: 
    startConsole()
```

이렇게도 써줄 수 있습니다!

2022-08-24 10:54 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/main.swift
> +// 6. 같다면, 선공자 승리 아닐 경우, 게임을 다시 진행 (선공을 결정)
프로젝트 수행 시 제약사항에 주석을 달지 않는 것이 있습니다! 주석은 지워주는 것이 좋을 것 같아요 👻

2022-08-24 11:02 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Models/GameMessage.swift
> +}
👍👍👍

2022-08-24 11:02 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/main.swift
> +	func startConsole() {
접근 제한자를 붙여주고 메서드로 소통하도록 구현한 것 좋아요👍

2022-08-24 11:02 UTC, yeeton37 commented on RockPaperScissors/RockPaperScissors/Games/MukjipaGameManager.swift
> +class MukjipaGameManager {
`MukjipaGameManager`만 class이고, `RPSGameManager`와 `GameManager`는 struct로 구현하신 이유가 있을까요??

2022-08-24 16:22 UTC, yeeton37 commented
@wonbi92, @leegyoungmin 리팩토링에서 많은 변화를 주셨네요! 
특히 가위바위보와 묵찌빠 게임을 타입으로 만들어 모듈화 시킨 부분 정말 칭찬드리고 싶어요~ 
척척 잘해주시니 정말 대단합니다 두분! 
 
### 🤔 고민한 점에 대한 답변

> 1. 묵찌빠 단계로 넘어가기 위한 준비
리팩토링 과정에서 묵찌빠 게임으로 넘어가는 단계에 대한 고민을 많이 하였습니다. 처음에는 가위바위보를 클래스로 처리해서 묵찌빠 클래스가 가위바위보를 상속받는 방식으로 구현 하려고 했는데, 이 방법 보다는 모듈화를 통해 각 게임이 독자적인 인스턴스를 가지고 그 인스턴스들을 한번에 처리하는 방식으로 구현하기로 결정하였습니다. 그에 맞게 코드를 수정하는 과정에서 게임의 대한 결과물을 반환하는 모듈과 게임에 대한 사용자의 입력을 처리하는 모듈로 다시 구분하여 구현하게 되었습니다. 그 결과 필요없는 메서드들이 정리가 되기도 하고, 어쩔 수 없이 여러번 유효성을 체크하는 과정이 많이 줄어들게 된거 같아 좋은 판단이었다고 생각합니다.

- 묵찌빠 클래스가 가위바위보를 상속받는 방식이 옳은가? 라고 생각했을 때 그 방법이 옳다면 상속받는 방식도 좋다고 생각해요. 개인적으로 저는 묵찌빠 게임이 가위바위보 게임을 소유하고 있는 것 좋다고 생각했습니다.
- 또한 말씀하신 모듈화를 해주기 위해 각 타입을 나눠준 것 저 또한 좋은 판단이라고 생각되네요! 앞으로 모듈화는 차차 프로젝트마다 적용해보게 될 것입니다.

> 2. 모듈화?
위에서 고민한 내용이 정말 이전에 사용하던 방식보다 좋은 방식인지에 대한 고민이 있었습니다. 사실 저희가 리팩토링 과정에서 모듈화라는 부분을구현하는 과정에서 거의 모든 코드를 수정하게 되었는데 저희는 이 방법이 유지보수나 step2에서 구현할 묵찌빠를 좀 더 쉽게 구현할 수 있는 방법이라 생각하고 이런 결정을 내리게 되었습니다. 이 결정이 옳은 결정인지가 궁금합니다.

- 모듈화에 대해 고민하신 것이 코드 상에 잘 드러났어요ㅎㅎ 이미 구현이 되는 코드를 더 좋은 방식으로 바꿔주기 위해 노력하신 게 보여서 정말 칭찬드리고 싶네요. 쉽지 않으셨을텐데 저도 많이 배웁니다..ㅠㅠ 

모듈화에 대해서는 아래의 질문에 대해 고민해보시면 도움이 많이 될 것 같아요! 
- `모듈`은 무엇일까요? 
- `모듈`은 어떤 특징이 있을까요?
- swift에서 `모듈화`란  무엇인가요?
- `모듈화`의 장단점은 무엇인가요? 

묵찌빠와 가위바위보 게임을 따로 구조체와 클래스 타입으로 분리해 그 안에 메서드를 묶어주신 점, 또한 각각의 타입별로 파일을 분리해주신 점 모두 잘 진행해주셨습니다. 위의 질문에 대해 답해보시면서 step2를 진행하시면 될 것 같아요!
천천히 찾아보셔도 됩니다. ㅎㅎ 
그럼 여기서 머지 요청 해주시면 머지해드릴게요~ 두분 너무 잘하셨고 고생하셨어요.👍

2022-08-25 00:08 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Games/RPSGameManager.swift
> +class RPSGameManager {
넵! 수정하였습니다!

2022-08-25 00:09 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +			startConsole()
넵! 이것도 수정하였습니다!

2022-08-25 00:11 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Games/MukjipaGameManager.swift
> +class MukjipaGameManager {
이게 원래 스텝1 브랜치에 들어가면 안되는데.. 저희가 스텝2로 머지하는 과정에서 좀 꼬인거 같습니다! 스텝2에서는 구조체로 구현하겠습니다~!!

2022-08-25 00:13 UTC, wonbi92 commented on RockPaperScissors/RockPaperScissors/Models/RPS.swift
> +	}
self는 인스턴스 자기자신을 참조할 때 사용하고, Self는 그 인스턴스 타입 자체을 참조할 때 사용합니다! 암시적 프로퍼티인 self의 타입은 Self입니다!

2022-08-25 02:11 UTC, merged