묵찌빠 게임 [STEP 1] Baem, Dragon
yagom-academy/ios-rock-paper-scissors pull request #165
Opened 2022-08-23 08:20 UTC by DragonYG

@bar-d 

바드 안녕하세요!
묵찌빠 게임 [Step1] 완료하여 PR 드립니다. 확인부탁드립니다^^

### 고민한 점

- compareUserWithComputer 함수를 if문 또는 Switch문 중 어떤 것이 적당한지에 대한 고민을 해봤습니다.
다른 경우의 재사용을 고려하여 Switch문으로 사용하였습니다.
  - Switch문에서 Default 처리에 대해서도 고민하였습니다.
1. If문을 활용한 방법 
```swift
If user == computer {
        print("비겼습니다!")
    } else if user == 1, computer == 2 {
        print("컴퓨터 승리")
    } else if user == 2, computer == 3 {
        print("컴퓨터 승리")
    } else if user == 3, computer == 1 {
        print("컴퓨터 승리")
    } else {
        print("유저 승리")
    }
```
2. Switch문을 활용한 방법
```swift
    switch (user, computer) {
    case (1, 2), (2, 3), (3, 1) :
        print("컴퓨터 승리")
    case (1, 1), (2, 2), (3, 3) :
        print("비김")
    case (2, 1), (3, 2), (1, 3) :
        print("user 승리")
    default :
        print("그럴일 없어.....")
    }
}
```

- 함수 동작과 네이밍간의 연관성을 최대한 고려해봤습니다.

### 조언을 얻고 싶은 부분

- 함수를 최대한 쪼개 구현해보았는데 추가적으로 함수를 기능적으로 분할해야할지 조언 부탁드립니다.
- 묵찌빠에서 비겼을 경우 다시 gameStart()함수를 호출하게 되는데 이 경우 문제가 없는지 확인부탁드립니다.
아니면, 더 좋은 방법이 있는지 조언 부탁드립니다.
```swift
func compareUserWithComputer(_ user: Int, _ computer: Int) {
    switch (user, computer) {
    case (1, 2), (2, 3), (3, 1) :
        print("졌습니다!")
    case (2, 1), (3, 2), (1, 3) :
        print("이겼습니다!")
    default :
        print("비겼습니다!")
        gameStart()
    }
}
```
- Switch문에서 Defalut 처리를 어떻게 해야할지 조언 부탁드립니다.
- 오류처리를 Do-Try-Catch문을 통해 처리해주는게 더 좋은 접근일지 조언 부탁드립니다.

2022-08-23 17:38 UTC, bar-d commented
step1 진행하시느라 고생하셨습니다
## 👏칭찬드리고 싶은 점

### 함수의 기능분리를 잘해주신 점👏  
- 함수를 기능별로 분리를 잘해주셨어요
### 코드 가독성이 좋은 점 👏👏  
- 코드들이 통일성을 가지고 작성이 되어서 코드를 읽는데 수월하네요
### 커밋 메세지 컨벤션 👏👏  
- 커밋 메세지를 아주 잘 작성해주시고 계시네요  
코드와 마찬가지로 커밋 메세지도 지금처럼 통일성 있게 적어주세요

## 고민한 점

>compareUserWithComputer 함수를 if문 또는 Switch문 중 어떤 것이 적당한지에 대한 고민을 해봤습니다.  
다른 경우의 재사용을 고려하여 Switch문으로 사용하였습니다.  
Switch문에서 Default 처리에 대해서도 고민하였습니다.  
1. If문을 활용한 방법
```swift
If user == computer {
        print("비겼습니다!")
    } else if user == 1, computer == 2 {
        print("컴퓨터 승리")
    } else if user == 2, computer == 3 {
        print("컴퓨터 승리")
    } else if user == 3, computer == 1 {
        print("컴퓨터 승리")
    } else {
        print("유저 승리")
    }
```
2. Switch문을 활용한 방법
```swift
    switch (user, computer) {
    case (1, 2), (2, 3), (3, 1) :
        print("컴퓨터 승리")
    case (1, 1), (2, 2), (3, 3) :
        print("비김")
    case (2, 1), (3, 2), (1, 3) :
        print("user 승리")
    default :
        print("그럴일 없어.....")
    }
}
```
>함수 동작과 네이밍간의 연관성을 최대한 고려해봤습니다.

- 우선적으로 네이밍이 저는 어색하다고 생각해요   
해당 함수를 읽는 것에는 무리가 없지만 해당 함수의 매개변수와 네이밍이 겹쳐서 어색해보여요  
[해당 영상](https://tv.naver.com/v/4980432/list/267189)을 한번 보시는 것도 추천드려요  
- 현재 예시로서는 저는 If문이 가독성이 더 좋아보이네요  
제가 If문이 가독성이 좋아보인다고 답이 아니에요  
두 분이서 결정하시면 되는 부분이에요
Switch문은 아래 커멘트에서 말씀드리겠습니다

- `If`문을 사용했을 때와 `Switch`문을 사용했을 때의 차이점이 무엇인가요

## 조언을 얻고 싶은 부분

>함수를 최대한 쪼개 구현해보았는데 추가적으로 함수를 기능적으로 분할해야할지 조언 부탁드립니다.  
묵찌빠에서 비겼을 경우 다시 gameStart()함수를 호출하게 되는데 이 경우 문제가 없는지 확인부탁드립니다.  
아니면, 더 좋은 방법이 있는지 조언 부탁드립니다.
```swift
func compareUserWithComputer(_ user: Int, _ computer: Int) {
    switch (user, computer) {
    case (1, 2), (2, 3), (3, 1) :
        print("졌습니다!")
    case (2, 1), (3, 2), (1, 3) :
        print("이겼습니다!")
    default :
        print("비겼습니다!")
        gameStart()
    }
}
```

- 무조건적으로 함수를 분할하는 것 보다는 기능적으로 분할하는게 더 맞다고 생각을 해요  
한 기능을 하는 함수를 여러 함수로 분리해버리면 해당 기능을 하는 함수를 여러개 찾아야 하기 때문에 더 코드가 난잡해질 것 같아요  

> Switch문에서 Defalut 처리를 어떻게 해야할지 조언 부탁드립니다.  
- `Switch`문에서 Default가 생기는 이유는 무엇인가요?
> 오류처리를 Do-Try-Catch문을 통해 처리해주는게 더 좋은 접근일지 조언 부탁드립니다.
- 말씀해시는 오류처리는 어디에서의 오류처리를 말씀해주시는 걸까요?  
- `Swift`에는 어떠한 오류처리 방법이 있을까요

2022-08-23 17:41 UTC, bar-d requested changes

2022-08-23 17:41 UTC, bar-d commented on README.md
> +![묵찌빠게임](https://user-images.githubusercontent.com/102534252/186052330-f512a49b-5f9e-4171-aa2a-81fade88091e.jpg)
순서도 작성해주신 점 좋습니다  
png 파일로도 넣어주시면 리뷰할때 보기가 편해져요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by Baem, Dragon
사소한 고침도 좋아요 👍
항상 이 프로젝트를 누가 진행했는지 명시해주세요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func validUserNumber() -> Int {
함수 네이밍이 조금 어색한 것 같아요  
`valid`는 `유효한`이라고 해석되요  
[공식문서](https://www.swift.org/documentation/api-design-guidelines/#naming)를 참고하고 다시 한번 변경해볼까요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +    while true {
이번 프로젝트에서 반복문과 재귀 함수 비교하기가 있는데.  
반복문을 사용하신 이유가 무엇일까요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
이 부분도 함수로 역할을 분리해 줄수 있을것 같네요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let userInput = readLine()
사용자가 과연 숫자만 제대로 입력할까요?  
예를 들어 공백을 추가하고 1을 입력한다던가 반대로 1을 입력하고 공백을 추가해주면 그 숫자는 1이 아닐까요?  
리팩토링을 조금 해주면 더 개선시킬 것 같아요
몽키테스트에 대해 한번 알아보시면 좋을 것 같아요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func checkUserInput(_ userInput: String?) -> Int? {
반환값을 옵셔널로 준 이유가 무엇인가요?

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNumber = Int(userInput) else { return nil }
`guard let` 구문을 하나로 묶어줄 수 있을 것 같아요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if userNumber < 0 || userNumber >= 4 {
저는 프로퍼티를 선언해주고 if문은 개행해주는 편이에요  
적절한 띄어쓰기는 가독성을 높여줍니다
필수가 아닌 두분이서 논의해보고 결정해주셨으면 좋겠습니다

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
저는 함수의 반환값을 개행해주는 편인데요
두분은 개행한게 가독성이 좋다고 느껴지시나요 아니면 개행안한게 가독성이 좋다고 느껴지시나요?
필수가 아닌 두분이서 논의해보고 결정해주셨으면 좋겠습니다

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return computerInput
해당 부분도 마찬가지로 두분이서 논의하시고 전체 코드의 개행을 통일해주세요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compareUserWithComputer(_ user: Int, _ computer: Int) {
함수명과 파라미터가 겹쳐요
어색하게 느껴지네요
네이밍을 다시 해볼까요

2022-08-23 17:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
`user`와 `computer`를 `enum` 타입으로 넣어주면 어떨까요?
처음 코드를 보는 사람이 (1, 2)를 보고 이해를 할 수 있을지 의문이네요
`enum` 타입을 사용하면 지금 코드와는 어떻게 달라질까요

2022-08-23 17:44 UTC, bar-d requested changes

2022-08-23 17:44 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func gameStart() {
위에서 말씀드린 네이밍 문서 보시고 변경해주시면 될 것 같아요

2022-08-24 05:25 UTC, Dylan-yoon commented on README.md
> +![묵찌빠게임](https://user-images.githubusercontent.com/102534252/186052330-f512a49b-5f9e-4171-aa2a-81fade88091e.jpg)
Step2에서 첨부하도록 하겠습니다~!

2022-08-24 05:25 UTC, Dylan-yoon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func validUserNumber() -> Int {
```swift
func createUserNumber() -> Int {}
```
로 변경했습니다.
유저의 값을 받아오는 역할을 하고, createRandomNumber와의 유사한 기능으로 판단하여 통일성을 위해 위와 같이 변경했습니다.

2022-08-24 05:25 UTC, Dylan-yoon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    while true {
재귀 함수를 사용 할 수 있었지만,
스택 오버플로우 발생의 위험까지 감수하면서 굳이 사용해야 하나 라는 생각이 들어
while 문으로 작성 했습니다.
또한
꼬리 재귀함수를 사용해서 스택 오버플로우 발생을 막을 수 있지만, 
여러번 반복해서 입력값에 오류가 난다면,  함수의 중첩 즉 스택이 쌓이기 때문이 비효율 적이라 생각 되었습니다.

2022-08-24 05:25 UTC, Dylan-yoon commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
역할 분리를 위해 많은 고민을 한 끝에, 큰 공사를 했습니다.
[refactor: validUserNumber->creatUserNumber 네이밍 변경 및 print문 gameStart(…]함수에 통합
위에 커밋 내용에서 변경사항 확인 부탁드립니다.

2022-08-24 05:27 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNumber = Int(userInput) else { return nil }
guard let 구문을 하나로 묶는 식으로 수정하였습니다.

2022-08-24 05:27 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if userNumber < 0 || userNumber >= 4 {
guard let 구문을 하나로 묶는 식으로 수정하였습니다. (위랑 동일하여 동일답변 달았습니다)

2022-08-24 05:36 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
이번 프로젝트에서 저희들만의 convention은 현재 상태로 진행하기로 하여 유지하도록 하겠습니다!
return, continue (빠른종료) 만을 사용하고 있을 때는 이렇게 쓰도록 결정하였습니다.

2022-08-24 05:38 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return computerInput
네 확인했습니다!

2022-08-24 05:48 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compareUserWithComputer(_ user: Int, _ computer: Int) {
고민해본 결과 매개변수 또는 함수명을 변경하는 두가지 방법을 생각해보다가
최종적으로 compareUserWithComputer -> compareTwoInput 으로 함수명을 변경하였는데,
이런 경우에는 매개변수 또는 함수명 중 어떤 것을 바꾸는 것이 더 좋을지 질문드립니다.

2022-08-24 05:52 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +func gameStart() {
함수명 gameStart() -> excuteRockPaperScissors() 로 변경하였습니다.

2022-08-24 06:21 UTC, Dylan-yoon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func checkUserInput(_ userInput: String?) -> Int? {
Optional 값이 아니면 임의의 특정값을 지정해 return 시켜주어야 하는데,
불필요한 숫자를 대입하기보단 nil값으로 오류 처리 하는것이 좋다고 판단했습니다.

2022-08-24 06:45 UTC, Dylan-yoon commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let userInput = readLine()
공백 삭제기능 추가로 구현했습니다.

2022-08-24 07:34 UTC, Dylan-yoon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
코드변경 했습니다!

2022-08-24 07:46 UTC, bar-d commented
고생하셨습니다 step2도 화이팅이에요

2022-08-24 07:46 UTC, merged