[STEP 2] rhovin, zhilly
yagom-academy/ios-rock-paper-scissors pull request #166
Opened 2022-08-24 03:43 UTC by yuvinrho

@wongbingg
안녕하세요 웡빙! 로빈, 질리입니다~ Step2 PR 보냅니다. 

# 코드를 작성할 때 고민되었던 점 & 조언을 얻고 싶은 부분

## 함수 기능분리
- 기존 `startGame()` 함수에서 가위바위보 결과를 출력해주고, 이에 따른 묵찌빠 게임을 실행하는 `startMukChiBba(_ result: WinLoseDrawCase)`를 따로 분리하였습니다.

- 사용자 턴과 묵찌빠 메뉴 안내를 출력할 수 있도록 `displayTurnMenu(turn: TurnCase) ` 함수로 기능분리 하였습니다.
- 묵찌빠 결과에 따라 턴을 출력하고, 다음 턴의 묵찌빠를 실행하도록 `passTurn(_ turn: TurnCase, _ result: WinLoseDrawCase)` 함수로 기능분리 하였습니다.

## 네이밍
- `startMukChiBba(_ result: WinLoseDrawCase)` : 가위바위보 결과를 매개변수로 받아 묵찌빠를 실행하는 함수
- `mukChiBba(turn: TurnCase)` : 묵찌빠 로직이 담겨있는 함수. 함수이름에 동사를 넣고싶은데 적절한 동사가 생각나지 않아 mukChiBba로 정했습니다.
- `passTurn(_ turn: TurnCase, _ result: WinLoseDrawCase)` : 턴과 묵찌빠 결과를 매개변수로 받아 다음 턴의 묵찌빠 함수를 실행

함수이름을 위와 같이 지었는데, 항상 이름 짓는 것은 고민입니다. 의도가 잘 파악되는지 웡빙의 의견 궁금합니다~

## if와 Switch
어떤 상황에서 if와 Switch를 써야할지 고민을 했습니다.
결론적으로 WinLoseDrawCase, TurnCase, RockPaperScissorCase 세 가지 열거형을 비교하는 로직에서는 if 문 보다 switch를 사용하면 가독성이 좋고 열거형 케이스에 맞게 분기가 가능해서 switch문을 사용했습니다.

2022-08-25 05:05 UTC, wongbingg reviewed
안녕하세요 여러분 ~ step2 도 고생하셨습니다~!! 내용 확인해보니 코드가 정말 깔끔해서 손볼 곳이 많이 없었어요 !! 가독성도 너무나 좋고 잘 해주셨습니다 !! ㅎㅎ

2022-08-25 05:51 UTC, wongbingg requested changes
전반적으로 네이밍 관련 부분에 대한 코멘트가 많았네요 ! ㅎㅎ 로직적으로 수정할 부분이 없이 완벽하게 만들어 주셔서 그런 것 같습니다..! 저도 이런 깔끔한 코드를 짜야 겠다는 생각이 드는군요! ㅎㅎ 여러분께 한 수 배우는 좋은 시간이었습니다 ㅎㅎ

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>                let userSelection = Int(userInput) else {
inputUserSelection 메서드에서 반환값이 옵셔널 이군요 ! guard let을 통해 userSelection을 반환하는 것과, 단순히 Int(userInput) 을 반환하는 것 두개의 결과는 어떨까요?

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>          switch userInput {
지금의 네이밍도 훌륭하지만! 중복되는 단어를 제거할 수 있는 방법이 있다면 제거해주는 것이 더욱 깔끔해 보일 것 같습니다 ㅎㅎ

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func startMukChiBba(_ result: WinLoseDrawCase) {
이 메서드는 가위바위보의 결과 우승한 쪽의 턴을 묵찌빠 게임으로 주입시켜주는 역할인 것 같습니다 ! 더 적합한 네이밍을 찾아볼까요? 또한 파라미터명에 어떤 것의 결과값인지 구체적으로 작성 해볼까요 ?

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +            print("\(turn.rawValue)의 승리!")
enum의 rawValue를 활용하셨군요 ~!! 👍👍 좋습니다

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func mukChiBba(turn: TurnCase) {
메서드의 네이밍은 동사로 시작해야 자연스러운 것 같습니다 ~! 현재는 중복되서 어쩔 수 없이 이런 네이밍을 택하신 것 같은데요! 위에서 언급드렸던 부분의 네이밍이 수정된다면 이 부분이 startMukChiBba가 되어도 좋을 것 같습니다 ~! ㅎㅎ

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func mukChiBba(turn: TurnCase) {
파라미터 명 또한 그냥 "turn" 이 아닌, 게임 시작의 첫번째 턴 이라는 의미가 들어갔으면 좋겠군요 ~!

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/TurnCase.swift
> +}
완벽합니다...! enum으로 케이스 분리를 해주니 코드가 가독성이 쭉쭉 ~!! 올라가네요 ㅎㅎ

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        )
어떤 게임의 결과값인지 명확히 써주면 더 좋을 것 같습니다! ㅎㅎ

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func displayTurnMenu(turn: TurnCase) {
이 메서드는 묵찌빠 게임의 인터페이스 역할을 하는 프린트 문 이라고 생각됩니다!ㅎㅎ "묵찌빠게임" 이라는 의미를 추가로 담아서 네이밍 해보는 것은 어떨까요 ?

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func passTurn(_ turn: TurnCase, _ result: WinLoseDrawCase) {
result 값에 따른 switch문이 실행되고 있는 메서드네요 ! 
결과값에 따라 승리 또는 사용자턴 또는 컴퓨터턴이 되는데, 결과값으로 다음 스텝을 정하는 느낌을 받아서 
예시)  judgeNextStep(by result: WinLoseDrawCase, currentTurn: TurnCase ) 
이런식으로 argument label 과 parameter 모두를 활용해 전치사도 이용해보면 좋을 것 같습니다..!

2022-08-25 05:51 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>          computerHand: RockPaperScissorCase
현재 if-else 문으로 분기처리 되고있는 부분을 switch문으로 바꿔보면 어떻게 될까요 ? switch (userHand, computerHand) { ... }
저는 보통 3개 이상의 분기처리가 될 때 switch-case 문을 자주 사용하는 편입니다 ㅎㅎ 둘다 사용해보시면 좋을 것 같아요!

2022-08-26 01:10 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>                let userSelection = Int(userInput) else {
`userSelection`부분이 불필요하게 guard let 안에 들어있었던 것 같습니다! 단순히 보면 두개의 출력 결과는 같기 때문에 `return Int(userInput)` 으로 수정했습니다~ 👍

2022-08-26 01:19 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>          switch userInput {
`judgeValidInput(userEnter: Int?)` 로 수정해 봤는데 웡빙이라면 어떻게 하셨을지 의견이 듣고 싶습니다!

2022-08-26 01:36 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func startMukChiBba(_ result: WinLoseDrawCase) {
`injectTurnToMukChiBba(_ rockPaperScissorsResult: WinLoseDrawCase)` 로 수정했습니다!
또한 기존의 result가 parameter name을 직관적이게 `_ rockPaperScissorsResult`로 수정했습니다.

2022-08-26 01:44 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func mukChiBba(turn: TurnCase) {
> 메서드의 네이밍은 동사로 시작해야 자연스러운 것 같습니다 ~! 현재는 중복돼서 어쩔 수 없이 이런 네이밍을 택하신 것 같은데요! 위에서 언급 드렸던 부분의 네이밍이 수정된다면 이 부분이 startMukChiBba가 되어도 좋을 것 같습니다 ~! ㅎㅎ

기존 네이밍에서 웡빙의 의견대로 `startMukChiBba`로 수정했습니다. 👍

> 파라미터 명 또한 그냥 "turn" 이 아닌, 게임 시작의 첫 번째 턴이라는 의미가 들어갔으면 좋겠군요 ~!

파라미터 명응 `startMukChiBba` 함수가 첫 번째 턴뿐만 아니라 게임에서 묵찌빠 기능이 필요할 때마다 사용되는 함수이기 때문에 첫 번째 턴이라는 의미가 들어가면 안 될 것 같다고 판단해서 수정하지 않았습니다...!

2022-08-26 01:47 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +        )
위에서 언급했던 부분과 마찬가지로 가위바위보 결과는 `rockPaperScissorsResult`로 묵찌빠 결과는 `mukChiBbaResult`로 조금 더 직관적이게 수정했어요 웡빙! 😃

2022-08-26 01:51 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func displayTurnMenu(turn: TurnCase) {
좋은 의견입니다 웡빙!

`displayGameMenu` -> `displayRockPaperScissorsInterface`
`displayTurnMenu` -> `displayMukChiBbaInterface`

로 통일성 있게 수정했습니다~ 👍

2022-08-26 01:57 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func passTurn(_ turn: TurnCase, _ result: WinLoseDrawCase) {
웡빙의 의견을 적극!수용해

`judgeNextTurn(by mukChiBbaResult: WinLoseDrawCase, currentTurn: TurnCase)` 로 수정했습니다~

2022-08-26 02:13 UTC, zhilly11 commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>          computerHand: RockPaperScissorCase
tuple을 이용한 switch 사용방법을 생각하지 못했었네요! 이번 기회에 로빈과 같이 알아봤습니다!

`let bothHands = (userHand, computerHand)` 를 새로 작성해주어서 switch 구문에 `bothHands`를 활용하여 수정해봤습니다!

2022-08-26 06:47 UTC, zhilly11 commented
웡빙! @wongbingg 
묵찌빠 게임 디테일하고 친절한 리뷰 감사했습니다 👍
덕분에 많이 배웠습니다 😀

2022-08-26 06:52 UTC, yuvinrho commented
안녕하세요 웡빙 @wongbingg 😄
웡빙 덕분에 생각하지 못한 부분과 어떻게 하면 좀 더 나은 코드가 될 수 있는지 많이 배울 수 있었습니다. 감사합니다!

2022-08-26 07:14 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>          switch userInput {
저같은 경우 , validate 가 유효성을 검사하다 라는 뜻이기 때문에 
`validate(userInput: Int?) -> RockPaperScissorCase?` 또는  
`validate(on userInput: Int?) -> RockPaperScissorCase?`
이런 식의 네이밍을 사용할 것 같습니다 ㅎㅎ 네이밍에 정답은 없기 때문에 참고만 해보시면 좋을 것 같아요!ㅎㅎ 
문장처럼 읽히게 만드는 것을 연습해보시면 좋을 것 같습니다 ㅎㅎ

2022-08-26 07:24 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
> +    private func startMukChiBba(_ result: WinLoseDrawCase) {
만약 Game이라는 타입이 있다고 가정하고
`let mukChiBbaGame = Game()`
이런식의 인스턴스가 하나 만들어 졌다고 생각해보면 
`inject(_ rockPaperScissorsResult: WinLoseDrawCase, to game: Game = mukChiBbaGame)`
이렇게 기본값을 할당하여 네이밍을 해줄 수도 있을 것 같습니다 ㅎㅎ
이 부분은 상상했을 때의 일이니 보고 넘어가셔도 될 것 같습니다 ㅎㅎ

2022-08-26 07:36 UTC, wongbingg commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsLibrary.swift
>          computerHand: RockPaperScissorCase
switch문에 대해 깊게 알아보셨군요 ~! 이전보다 가독성이 훨씬 좋아진 것 같습니다 ㅎㅎ where조건절까지 활용을 하셨군요 ~!! 완벽합니다 ㅎㅎ 여기서는 더 이상 수정할 것이 없지만 만약 조금 더 무언가 바꿔주고 싶다면? 
.win을 반환하는 case 3가지를 묶어서 하나의 case로 표현하는것 정도? 는 수정해볼 수 있을 것 같아요 ㅎㅎ 
- 예시:
```swift
private func judgeWin(
         userHand: RockPaperScissorCase,
         computerHand: RockPaperScissorCase
     ) -> WinLoseDrawCase
     {
         let bothHands = (userHand, computerHand)

         switch bothHands {
         case let (userHand, computerHand) where userHand == computerHand:
             return .draw
         case (.scissor, .paper), (.rock, .scissor), (.paper, .rock):
             return .win
         default:
             return .lose
         }
     }
```

2022-08-26 07:37 UTC, merged