묵찌빠 게임 [STEP 2] stone, SummerCat
yagom-academy/ios-rock-paper-scissors pull request #167
Opened 2022-08-24 04:36 UTC by ttokin

@ZZBAE 안녕하세요 재재! STEP 2 첫 PR입니다.
STEP 1 리뷰에서 재재가 말씀해주신 "반복되는 부분을 어떻게 줄일 수 있을까?"에 대한 해답을 STEP 2를 진행하면서 얻을 수 있었던 것 같습니다. 갓 재재 👍  감사합니다!

## [STEP 2]
### 고민했던 점
#### 1. 가위바위보의 승/패 결과를 처리하는 함수의 case 내에서 묵찌빠 게임을 실행하는 함수를 호출했더니, 묵찌빠 게임을 모두 실행한 후에 `checkGameResult()` 함수의 가장 아래에 있는 코드들이 실행되는 문제가 있었습니다.

```swift
// 처음 작성한 코드
func checkGameResult(computerChoice: RockPaperScissors, userChoice: RockPaperScissors) {
    if computerChoice == userChoice {
        print("비겼습니다")
        playMCBGame(gameResult = .draw)
    }

    switch userChoice {
    case .scissors:
        if computerChoice == .rock {
            print("졌습니다!")
            playMCBGame(gameResult = .lose)
        }
    case .rock:
        if computerChoice == .paper {
            print("졌습니다!")
            playMCBGame(gameResult = .lose)
        }
    case .paper:
        if computerChoice == .scissors {
            print("졌습니다!")
            playMCBGame(gameResult = .lose)
        }
    }

    print("이겼습니다!")
    playMCBGame(gameResult = .win)
}
```
- 위 코드의 경우, `lose`일 때 `playMCBGame`을 실행한 후, 묵찌빠 게임이 종료된 후에 `checkGameResult`의 `switch`문 바깥에 있는 `print("이겼습니다!")`와 `playMCBGame(gameResult = .win)`을 실행하는 문제가 있었습니다.
- 위와 같은 오류를 해결하기 위해 `checkGameResult` 함수가 게임의 승/패/무승부/입력오류를 반환하는 `enum` 타입의 `GameResult`를 반환하도록 변경한 후,
`startGame` 함수 내에서 위 `GameResult`값을 받아 받아온 값으로 `switch`문을 사용해 묵찌빠 게임을 실행할 것인지(승/패의 경우) / 게임의 시작으로 돌아가서 사용자 입력을 다시 받을 것인지 (무승부) / 게임을 종료할 것인지 결정하도록 했습니다.

```swift=
func checkGameResult(computerChoice: RockPaperScissors, userChoice: RockPaperScissors) -> GameResult {
    if computerChoice == userChoice { return .draw }
    
    switch userChoice {
    case .scissors:
        if computerChoice == .rock { return .lose }
    case .rock:
        if computerChoice == .paper { return .lose }
    case .paper:
        if computerChoice == .scissors { return .lose }
    case .none:
        return .exit
    }
    
    return .win
}

```
```swift=
let gameResult = checkGameResult(computerChoice: computerChoice, userChoice: userChoice)
    
    switch gameResult {
    case .win:
        print("이겼습니다!")
        playMCBGame(gameResult: .win)
    case .lose:
        print("졌습니다!")
        playMCBGame(gameResult: .lose)
    case .draw:
        print("비겼습니다")
        startGame()
    case .exit:
        print("게임 종료")
        break
    }
```

#### 2. 사용자 입력에 따라 게임을 반복하는 부분을 반복문(`while`)로 구현했었으나, 재귀함수로 변경
- `Step1`에서는 Bool 값을 갖는 `isRunning` 변수를 활용해 무승부인 경우에는 무한 반복하는 반복문으로 구현했었습니다.
- `Step2`를 진행하던 중, 가위바위보의 사용자 승/패 조건에 따라 묵찌빠 게임에서 턴이 결정되는 부분을 고려했을때 RPS게임에서의 반복조건이 적합하지 않다고 판단되었습니다. 그리고 `startGame` 함수의 `while`문 내에서 묵찌빠 게임을 실행하는 함수를 호출하기 때문에, 묵찌빠 게임이 종료된 후 다시 `while`문으로 돌아와서 그 이후의 구문을 실행하는 문제가 있었습니다. 이것은 게임을 즉시 종료하기를 원하는 저희의 의도와 맞지 않았기 때문에 재귀함수로 변경하게 되었습니다.

#### 3. 사용자 입력값을 처리하는 enum에 잘못된 입력의 케이스 `none`, 게임 결과 반환값에 게임 종료를 의미하는`exit` 추가
- 사용자 입력 값을 처리하는 부분에서 `enum` 타입에 `none`이라는 타입을 추가해준다면, `enum`타입의 생성자와 `0...3 ~=` 이라는 범위 연산자의 유효성 체크를 한번에 해줄 수 있다고 판단하였습니다.
- `0...3 ~= ` 범위연산자를 제거해주고, enum 타입에 none을 추가 해줌으로써, `none`의 Raw Value인 `0`은 게임을 종료시키는 조건으로 사용할 수 있도록 했습니다.
- `GameResult`라는 열거체를 추가하고, `switch`문을 활용해 `GameResult`의 값에 따라 게임 진행 흐름을 제어하도록 변경하면서 RPS게임에서 Bool값을 갖는 `isGame` 플래그 변수를 활용한 `while` 반복문 대신 재귀함수로 처리할 수 있었습니다.
- `exit`라는 `GameResult`의 타입을 추가함으로써 게임 종료에 대한 타입을 한가지로 통일하였습니다.

#### 4. 묵찌빠 게임 시작 시 이전 게임의 승/패 결과에 따른 사용자/컴퓨터 턴 플래그 변수
- RPS게임의 결과값으로 win과 lose를 묵찌빠 게임의 시작에 대한 턴으로 결정해 주기 위하여 `isUserTurn`이라는 변수를 추가하였습니다.
- 묵찌빠 게임 내에서 턴을 정할 때에도, `isUserTurn`이라는 변수를 이용해서 사용자의 턴과 컴퓨터의 턴을 핸들링 할 수 있었습니다.

2022-08-25 13:20 UTC, Hugh-github commented
STEP 2 하시느라 정말 고생하셨어요!!! 👏👏👏
리뷰가 늦어져서 정말 죄송합니다 🙇🏻

### 고민한 점
> STEP1 에서 가위바위보 구조체에서 생성했었던 메서드를 재활용하고싶어서 고민했었습니다 ( ex)fetchUserNumber, judgeUserGameResultIn). fetchUserNumber메서드는 묵찌빠 구조체에서 가위바위보 구조체의 인스턴스를 생성 후 재사용했고, judgeUserGameResultIn 메서드는 GameResult 열거형 안에서 메서드 선언 후 사용해보았습니다.

+ 어떻게 해야 기존에 생성한 타입을 활용할 수 있는지 고민해 보신 점 정말 좋은 것 같아요 💯

> class상속이용: 처음엔 묵찌빠는 가위바위보에서 몇몇 기능이 추가 된 확장판이라고 생각하여 class로 변환 후 상속을 활용하는 방법으로 진행하다가 상속관계가 아닌 것을 알게되었습니다. 집합관계에서 가위바위보가 묵찌빠에 모두 포함되어 있지 않다는 것을 깨달아서 채택하지 않은 컨셉이었습니다

+ 제가 생각했을 때 가위바위보 게임이 묵찌빠 게임의 상위 객체가 되는 게 어색한 것 같아요. 상속은 큰 상위 객체를 상속해 좀 더 디테일한 객체를 만들 때 사용한다고 생각합니다. 예를 들어 동물(상위 객체) -> 고양이(하위 객체) 이런 느낌으로요. 해당 프로젝트에서 상속을 사용한다면 Game이라는 상위 객체를 만들고 가위바위보 게임과 묵찌빠 게임이 Game을 상속받게 할 것 같습니다.

> struct extension 이용: 기능을 확장한다는 의미로 extension을 사용하려 했는데 묵찌빠를 표현하기 위해서는 구조체의 네이밍을 묵찌빠로 해주어야 했기에 채택하지 않은 컨셉이었습니다.

+ 두 분이 생각하신 것처럼 `extension` 을 사용하면 기존에 만든 타입을 바꿔줘야 하는 문제가 발생할 것 같아요. 다시 한번 많은 생각을 하셨다는 게 느껴지네요!!

> 묵찌빠 struct내에서 가위바위보 인스턴스생성: 휴의 도움으로 알게 된 컨셉으로 2번 컨셉의 문제를 해결하고 가위바위보진행과 가위바위보의 메서드를 묵찌빠 구조체 안에서도 사용할 수 있는 컨셉이라 판단되어 채택하였습니다.

+ 제가 도움을 드렸지만 이 방법이 꼭 맞는 방법이 아닐 수 있습니다. 제가 이렇게 생각한 이유는 묵찌빠 게임의 순서가 가위바위보 결과에 의존하고 있다고 생각했습니다. 써니쿠기와 제이푸시는 더 좋은 방법을 찾을 수 있을 것 같아요 ☺️

> judgeUserGameResultIn메서드를 GameResult 열거형 안으로 넣어준 이유 : 
가위바위보 구조체의 인스턴스를 생성 한 후 묵찌빠 승패를 판단하는 함수호출로 RPSGame.judgeUserGameResult() 라고 사용하는것이 어색하다고 느껴졌습니다. 그래서 GameResult 열거형 안으로 넣어준 후 가위바위보와 묵찌빠에서 모두 사용하였습니다.

+ 두 타입에서 사용되는 공통된 기능을 적절한 타입으로 옮겨 구현해 주신 것 같아요 👏👏👏

### 조언을 얻고싶은 부분

#### Enum.isEmpty 같은 메서드의 존재
> 1~3사이의 숫자가 필요한 computerRPSNumber를 만들어줄 때 RPS.allcases.randomElement 를 이용해 랜덤값을 가져오고 싶었습니다. 그런데 case가 없을 경우가 있기때문에 randomElement가 옵셔널이라는 것을 알았습니다. 이것을 언래핑 해주기위해서 case가 정확히 있다는것을 알 수 있는 isEmpty같은 방법이 있을까요? 예를들면 아래와같은 코드를 의미하는 느낌(?)입니다.

+ `CaseIterable` 을 공부해 보시면 될 것 같아요.
```swift!
enum RPS: CaseIterable {
    case rock
    case paper
    case scissors
}

RPS.allCases.randomElement()
```

### 수정할 부분
![](https://i.imgur.com/K10uByB.png)
현재 0을 누르면 게임이 바로 종료되는 게 아니라 한 번 더 0을 입력해야 게임이 종료되는 것 같습니다. 이 부분 수정 부탁드립니다.

2022-08-25 16:11 UTC, ZZBAE reviewed
>### 고민했던 점
>#### 1. 가위바위보의 승/패 결과를 처리하는 함수의 case 내에서 묵찌빠 게임을 실행하는 함수를 호출했더니, 묵찌빠 게임을 모두 실행한 후에 checkGameResult() 함수의 가장 아래에 있는 코드들이 실행되는 문제가 있었습니다.
> 위 코드의 경우, lose일 때 playMCBGame을 실행한 후, 묵찌빠 게임이 종료된 후에 checkGameResult의 switch문 바깥에 있는 print("이겼습니다!")와 playMCBGame(gameResult = .win)을 실행하는 문제가 있었습니다.
위와 같은 오류를 해결하기 위해 checkGameResult 함수가 게임의 승/패/무승부/입력오류를 반환하는 enum 타입의 GameResult를 반환하도록 변경한 후,
startGame 함수 내에서 위 GameResult값을 받아 받아온 값으로 switch문을 사용해 묵찌빠 게임을 실행할 것인지(승/패의 경우) / 게임의 시작으로 돌아가서 사용자 입력을 다시 받을 것인지 (무승부) / 게임을 종료할 것인지 결정하도록 했습니다.

- `switch`문을 활용하신 점, 반환값을 지정해주어 rawValue를 사용하신 점 칭찬드립니다. 하지만 `switch`문 대신 사용할 수 있는 다른 방법은 없을까요? 추가적인 내용은 밑의 코멘트 참고해주세요.

>#### 2. 사용자 입력에 따라 게임을 반복하는 부분을 반복문(while)로 구현했었으나, 재귀함수로 변경
> Step1에서는 Bool 값을 갖는 isRunning 변수를 활용해 무승부인 경우에는 무한 반복하는 반복문으로 구현했었습니다.
Step2를 진행하던 중, 가위바위보의 사용자 승/패 조건에 따라 묵찌빠 게임에서 턴이 결정되는 부분을 고려했을때 RPS게임에서의 반복조건이 적합하지 않다고 판단되었습니다. 그리고 startGame 함수의 while문 내에서 묵찌빠 게임을 실행하는 함수를 호출하기 때문에, 묵찌빠 게임이 종료된 후 다시 while문으로 돌아와서 그 이후의 구문을 실행하는 문제가 있었습니다. 이것은 게임을 즉시 종료하기를 원하는 저희의 의도와 맞지 않았기 때문에 재귀함수로 변경하게 되었습니다.

- 명확한 이유가 있어서 좋습니다! 자세한 내용은 밑의 코멘트에서 추가로 남기겠습니다.

>#### 3. 사용자 입력값을 처리하는 enum에 잘못된 입력의 케이스 none, 게임 결과 반환값에 게임 종료를 의미하는exit 추가
>사용자 입력 값을 처리하는 부분에서 enum 타입에 none이라는 타입을 추가해준다면, enum타입의 생성자와 0...3 ~= 이라는 범위 연산자의 유효성 체크를 한번에 해줄 수 있다고 판단하였습니다.
0...3 ~= 범위연산자를 제거해주고, enum 타입에 none을 추가 해줌으로써, none의 Raw Value인 0은 게임을 종료시키는 조건으로 사용할 수 있도록 했습니다.
GameResult라는 열거체를 추가하고, switch문을 활용해 GameResult의 값에 따라 게임 진행 흐름을 제어하도록 변경하면서 RPS게임에서 Bool값을 갖는 isGame 플래그 변수를 활용한 while 반복문 대신 재귀함수로 처리할 수 있었습니다.
exit라는 GameResult의 타입을 추가함으로써 게임 종료에 대한 타입을 한가지로 통일하였습니다.

- `enum`(열거형)의 활용하려는 생각의 흐름이 좋다고 생각합니다👍🏻 자세한 내용은 밑의 코멘트에서 추가로 남기겠습니다.

>#### 4. 묵찌빠 게임 시작 시 이전 게임의 승/패 결과에 따른 사용자/컴퓨터 턴 플래그 변수
>RPS게임의 결과값으로 win과 lose를 묵찌빠 게임의 시작에 대한 턴으로 결정해 주기 위하여 isUserTurn이라는 변수를 추가하였습니다.
묵찌빠 게임 내에서 턴을 정할 때에도, isUserTurn이라는 변수를 이용해서 사용자의 턴과 컴퓨터의 턴을 핸들링 할 수 있었습니다.

- 사용자 턴과 컴퓨터 턴을 결정해주기 위한 변수를 따로 지정해주신 점 칭찬드립니다 👍🏻 네이밍도 다른 것이 별로 생각 안날 정도로 잘 설정해주셨네요.
<br>

---

**🍓 개인적인 의견 🍓**
- PR문을 작성하실 때, 지금 두 분이서 적어주신 고민하는점 4가지는 troubleShooting으로 고민한 점 + 해결한 점이 정리되어 있네요! 궁금하신 점이나, 해결하지 못한 부분이 있을 때는 추가로 적어주시면 더 좋을 것 같습니다 ☺️
- 엑스코드 프로젝트 파일에서 최상단에 생기는 주석은 지워주지 않으셔도 됩니다. 저작권 설명도 있고, created by 로 팀원들의 이름을 적고, 어떤 swift파일인지 설명이 나와있기 때문에 되도록이면 안지워주셔도 될 것 같습니다!

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/GameResult.swift
> +}
다른 열거형들과 컨벤션을 맞춰주시는건 어떨까요~?

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBa.swift
> +}
코멘트에서 말씀해주신 것과 같이 `none` 케이스를 지정하여 게임을 종료시키는 조건으로 사용하신점 칭찬드립니다! 👍🏻

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
사용자의 입력값을 확인하는 부분을 메서드로 따로 분리해주는 것은 어떨까요? 여러분의 의견이 궁금합니다!

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +        return playMCBGame(gameResult: .lose)
PR문에서 적어주셨듯 여러분들의 의도와 맞지 않아 `while`문 대신 재귀함수를 활용해보셨다는 점에서 여러분들이 코드를 짤 때, 고민을 많이 하셨다는 게 느껴져서 좋았습니다 👏🏻👏🏻

혹시 순환함수(재귀함수)를 사용하는 것과 반복문을 사용하는 것의 장단점은 어떤 부분이 있을까요?
추가적으로 재귀함수의 시간복잡도/공간복잡도를 공부해보시고, 어떤 의견이 생겼는지 공유해주실 수 있을까요?

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        break
저는 객체를 분리하면 step 2에 있는 enum들과 함수들의 객체 정리가 될 것 같은데,
혹시 class와 struct의 개념과 차이점에 대해 알고 계실까요? 간단하게 설명 한 번 부탁드리겠습니다 ☺️

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +}
하나의 함수는 한가지의 기능(역할)을 하는 것이 좋기 때문에 분리가 필요해보입니다.

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
[공식문서 참고링크](https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html) 에서 early exit일 경우, guard문을 사용한다고 되어 있는데, if문을 선택하신 이유가 있으실까요?

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    }
guard문으로 한번에 정리해주신 점 정말 칭찬드립니다!! 👍🏻

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +    if computerChoice == userChoice { return .draw }
step의 진행도에 맞춰 네이밍을 적절하게 바꿔주신 점 센스가 좋으십니다!!

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +        print("\(isUserTurn ? "사용자" : "컴퓨터" )의 승리!")
삼항연산자를 사용하신 이유가 있으실까요?

2022-08-25 16:11 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
>  }
`enum`의 `rawValue`를 사용하면 어떤 장점이 있을까요?

2022-08-26 01:07 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/GameResult.swift
> +}
컨벤션 통일 완료하였습니다.

2022-08-26 01:30 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
`if-else`를 통해서 조건문이 연결되지 않고 모든 `if`문 내에서 `return`을 통해 함수를 탈출하고 있기 때문에, 이번 같은 경우는 `guard`를 사용해서 early exit 하는 것과 exit을 빠르게 하는가?에 대해서는 차이가 없다고 생각했습니다.

guard를 사용할 경우 첫 번째의 무승부를 판단하는 조건은 아래와 같이 작성할 수 있습니다.
```swift
guard userChoice != computerChoice else { return .draw }
```
그러나 위와 같은 경우, "유저의 선택과 컴퓨터의 선택이 같을 경우 비긴다"에 비해 가독성이 떨어지는 것으로 판단했습니다.

그리고 승/패를 비교하는 조건의 경우 `guard`문으로는 다음과 같이 표현할 수 있습니다.
```swift
case .muk:
  guard computerChoice == .ba else { return .win }
```
이 경우, "유저가 묵을 낸 경우, 컴퓨터가 빠를 내지 않으면 이긴다"의 흐름으로 해석할 수 있는데, 이보다는 "유저가 묵을 낸 경우, 컴퓨터가 빠를 내면 진다"가 읽는 사람 입장에서 가독성이 훨씬 좋다고 생각했습니다.

2022-08-26 01:46 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +        print("\(isUserTurn ? "사용자" : "컴퓨터" )의 승리!")
`checkMCBGameResult`에서 넘긴 묵찌빠의 승무패 값은 `isUserTurn`의 값을 변경해주지 않고, `gameResult`라는 새로운 상수로 분기처리를 합니다. `gameResult`의 값이 `draw`일 경우, 현재 턴을 잡고 있는 사람이 승리하기 때문에 `isUserTurn`과 `gameResult`를 동시에 활용해야 승패 판단을 내릴 수 있습니다.
그리고 삼항연산자를 사용할 경우, 승자를 표현하기 위해 추가적인 String 변수를 사용하지 않아도 되기 때문입니다.

2022-08-26 01:52 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
>  }
이번 프로젝트의 경우, 가위 바위 보에 해당하는 1 ~ 3의 Int값을 직접 비교해서 게임 결과를 판정할수도 있지만,  enum값의 rawValue를 사용해 Int값에 대한 enum의 case(가위, 바위 보)가 나오기 때문에, 코드를 읽는 사람 입장에서 더 직관적으로 파악할 수 있는 장점이 있다고 생각합니다.

2022-08-26 03:18 UTC, lws2269 commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +        return playMCBGame(gameResult: .lose)
반복문의 경우 반복되는 코드의 실행 흐름을 파악하는게 상대적으로 쉽지만,
단점으로는 반복문이 반복되기 위한 조건을 신경써서 작성해줘야 한다는 점이 있습니다.
재귀함수의 경우 조건에 따라 함수를 다시 호출 함으로써 반복문과 같은 재귀를 처리 할 수 있고 파라미터 값을 넘겨줌으로써, 이전 결과 값을 활용 할 수 있습니다.
단점으로는 재귀 함수 내에서 여러가지 조건에 따라 분기처리가 될 수도 있으므로 시간 복잡도에 대한 계산이 어렵습니다. 또, 무한 루프에 빠지지 않도록 재귀 함수 탈출 조건에 대하여 신경을 써주어야 합니다.
또, 재귀 함수는 반복하여 호출될 때마다 매개변수, 지역변수, 반환값 등을 모두 스택 메모리에 추가로 저장합니다. 하지만 반복문의 경우 선언한 변수의 값 만큼의 메모리만 차지하기 때문에 재귀함수에 비해 메모리를 적게 차지할 수 있습니다.

묵찌빠 프로젝트에서는, 분기처리하는 부분에 따라 다음 함수를 호출할 것인지, 해당 구문을 반복할 것인지에 대한 처리를 해줘야 하다보니 반복문보다는 재귀함수가 적합하다라는 생각이 들었습니다.

2022-08-26 03:22 UTC, lws2269 commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
7, 8번째 라인의 구문은 사용자 입력 값에 따른 생성자 정의이다보니, 함수를 분리하여 userChoice와 computerChoice에 대한 값을 처리해주고 리턴 해주는 것보다, guard let 문에서 한번에 처리하는게 더 좋다고 판단됩니다..!! 
함수를 분리하여 처리하려 시도했는데, 가독성이 떨어지는 느낌이였습니다..! 😂

2022-08-26 03:37 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        break
`class`는 참조 타입, `struct`는 값 타입이라는 가장 큰 차이점이 있습니다. 참조 타입은 값의 주소값을 가지고 있어 인스턴스를 생성하면 값을 참조해서 전달(값의 주소값을 전달)하고, 값 타입은 값 자체를 가지고 있기 때문에 인스턴스를 생성하면 인스턴스에 값 자체를 복사해서 전달합니다.
`class`는 상속이 가능하고 `struct`는 상속이 불가능하기 때문에, 상속이 필요할 경우에는 `class`를 사용합니다.

2022-08-26 03:42 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        break
저희가 재재님의 코멘트를 이해하기로는, 현재 묵찌빠 게임과 가위바위보 게임이 파일 분리만 되어있어서 각 게임을 별도의 객체로 분리해서 객체와 함수 관계를 명확하게 표현하면 어떤지 의견을 주신 것 같은데.. 제대로 이해한 것이 맞는지 모르겠네요 ㅠㅠ

2022-08-26 13:38 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
여러분들의 의견이 명확히 있어서 좋습니다 👍🏻

2022-08-26 13:40 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +        return playMCBGame(gameResult: .lose)
재귀함수와 반복문의 차이점과 지금 프로젝트에서 필요한 부분을 정확히 알고 계신 것 같네요 좋습니다 😎👍🏻

2022-08-26 15:36 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
`guard`문 일 경우, 이런 식으로 코드가 작성되어 가독성이 떨어진다고 판단하셨다 해주셨는데, 위의 코드 중 비교연산자가 잘못된 것 같다고 생각이 듭니다. guard문에 대한 이해를 위해 다시 한 번 찾아보시는게 어떨까요?

```swift
guard userChoice != computerChoice else { return .draw }
```
추가로 `switch`문와 `if`문 둘 다 조건문인데, 조건문을 두 번씩 써야하는 이유가 있을까요?

그리고 case가 될 수 있는 경우 중 더 효율적으로 사용할 수 있는 방법이 있지 않을까요? (hint: ~~tuple~~ )

2022-08-26 15:41 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        break
우선 제가 말씀드린 의도와 같은 방향으로 이해하셨습니다! 👏🏻👏🏻
객체 관련된 개념은 앞으로도 계속 공부하셔야 하는 부분이라 말씀드렸습니다.  그리고 `class` 와 `struct`의 기본 개념을 설명 잘해주신 점 좋습니다 👍🏻

2022-08-26 15:51 UTC, ZZBAE requested changes

2022-08-26 15:51 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/MCBGameManager.swift
> +        }
`RockPaperScissors` 및 `MukChiBa` enum 타입 내부에서 `.none`이라는 case가 끼어있는 것이 조금 어색하다고 느껴집니다..!
만약, 어떠한 데이터가 존재하지 않는다는 것을 표현하고 싶으신거라면, `optional` 키워드를 알아보시는 건 어떠실까요?

2022-08-26 15:51 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/main.swift
>  //
주석 수정 좋습니다 👍🏻

2022-08-26 15:51 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rpsGameManager = RPSGameManager.init()
이 부분 `init()`키워드를 명시해주신 이유가 있을까요? 그리고 해당 키워드를 작성하지 않으면 게임진행에 어떤 문제가 생기나요?

2022-08-26 16:06 UTC, ZZBAE commented on RockPaperScissors/RockPaperScissors/RPSGameManager.swift
> +        }
3번째 라인에 게임이 시작하기 전에 `randomComputerNumber`를 생성하게 되어있네요. 그럼 사용자가 1~3이 아닌 다른 숫자를 선택할 경우 `randomComputerNumber`가 생성되었다가 그냥 없어지게 될텐데 그럼 불필요한 작업이 되는 것은 아닐까요?

2022-08-27 10:58 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/MukChiBaGame.swift
> +    }
오!! 지금까지는 tuple을 사용한 케이스로 작성하면 6가지? 케이스를 모두 작성해야 한다고 생각해서 가독성이 떨어질 거라고 생각했는데, 그렇지 않게 할 방법이 있었네요!
재재 덕분에 또 하나 익혀갑니다 👍

2022-08-27 11:00 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/RPSGameManager.swift
> +        }
오 그렇네요..! 재재가 말씀해주신 대로 불필요한 연산&메모리 사용이 있겠네요!
수정해보았습니다.

2022-08-27 11:02 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rpsGameManager = RPSGameManager.init()
`enum`에서 rawValue를 사용할 때 `init()` 키워드를 사용해서 초기화하다 보니 무의식적으로 사용한 것 같습니다.
`RPSGameManager.init()`이 아닌 `RPSGameManager()` 만으로도 객체 생성이 되기 때문에, 해당 키워드가 없어도 게임 진행에는 문제가 없다고 생각합니다.

2022-08-27 11:07 UTC, ttokin commented on RockPaperScissors/RockPaperScissors/MCBGameManager.swift
> +        }
값이 없다는 의미로 사용한 것이 아니라, 0을 입력해서 게임을 종료하는 경우를 `none` 이라고 설정했었습니다.
재재의 말대로 적절치 못한 네이밍인 것 같아 `exit`로 수정하였습니다.

2022-08-28 07:59 UTC, merged