묵찌빠게임 [STEP2] 애종, Mangdi
yagom-academy/ios-rock-paper-scissors pull request #169
Opened 2022-08-24 08:57 UTC by jonghancha

@Jeon-Minsu 
안녕하세요 수꿍 :) 좋은 저녁 보내고 계신가요. STEP2 PR 보냅니다! 묵찌빠 게임은 가위바위보와 비슷하면서도 다른 점이 많아서 STEP1의 코드를 수정-보완해 완성해보았습니다! 부족한 실력이기에 다소 산만한 코드일 수 있습니다😭 리뷰 잘부탁드리구 조언과 지적 많이많이 써주세요..!!

## 진행 단계 : Step2

### 🤔 코드를 작성할 때 고민되었던 점
- 사용자의 입력을 받는 방식이 가위바위보, 묵찌빠 모두 1,2,3,0으로 동일했습니다. 그래서 사용자의 입력을 받아 조건에 따라 오류를 배제하고 Int형을 반환하는 filterUserInput()함수를 구현해봤습니다. 1,2,3,0 이 아닌 경우에는 nil을 반환해 오류로 처리했습니다. 
- 지난 PR때 말씀해주신 튜플에 대해서 어떻게 활용할지 고민했습니다.  수꿍이 의도한대로 잘 작성했는지는 모르겠으나 이번 step2는 튜플을 전반적으로 사용해보았습니다!
- 가위바위보에서 묵찌빠로 넘어갈때 묵찌빠에서 비기지않고 지거나 이길경우 다시 묵찌빠 로직을 실행할때 턴을 누가어떻게 잡을건지 매우 고민했었습니다. 이를 startMukChiBbaGame 함수의리턴값으로 튜플을 전달해서 스위치구문으로 누가 턴을 잡을건지 구현했었는데 이보다 더 간결하게 할수있는방법이 있을까 질문드립니다!
---
### 😢 해결이 되지 않은 점
- 묵찌빠게임과 가위바위보게임에 관련된 함수를 서로 다른 파일로 분리하지 못했습니다. PR 후에 수정해서 Push하겠습니다.
---
### 🆘 조언을 얻고 싶은 부분 등 상세하게 작성
- 코드를 작성하는데 의도치않게 한 함수에 많은 기능을 담아서 구현하다가 나중에 이걸 어찌 나눌까 난감할때가 종종 있었습니다. 이미 선언한 변수들, 앞 뒤로 이미 쓰여진 코드와 매끄럽게 이어지게 하기가 매우 어려웠습니다. 최대한 나눈다고 나누긴 했는데 보시고 더 나눌수있는 부분이 있다면 조언해주세요!

- 아무래도 재귀함수가 아닌 while 문을 통해 반복이 진행되다 보니 게임 진행 결과를 return값으로 받아 게임 종료를 결정하곤 했습니다. 이럴 때마다 '전역변수를 쓰면 참 편할텐데'라는 유혹이 듭니다..😂
함수 간에 소통할 때 Bool타입으로 return받아 의사결정이 이루어지는 과정이 자연스러운지 잘 모르겠습니다.

2022-08-25 05:57 UTC, Jeon-Minsu commented
## 코드를 작성할 때 고민되었던 점

1. 사용자의 입력을 받는 방식이 가위바위보, 묵찌빠 모두 1,2,3,0으로 동일했습니다. 그래서 사용자의 입력을 받아 조건에 따라 오류를 배제하고 Int형을 반환하는 filterUserInput()함수를 구현해봤습니다. 1,2,3,0 이 아닌 경우에는 nil을 반환해 오류로 처리했습니다.

> 가위바위보와 묵찌빠 게임 모두 0~3 사이의 숫자 입력만을 필요로합니다. 이에 대하여 예외 사항들을 매직 넘버가 아닌 nil을 반환도록 처리한 점 매우 칭찬드립니다!! 👍👍

2. 지난 PR때 말씀해주신 튜플에 대해서 어떻게 활용할지 고민했습니다. 수꿍이 의도한대로 잘 작성했는지는 모르겠으나 이번 step2는 튜플을 전반적으로 사용해보았습니다!

> startRockScissorsPaperGame 메서드 내 compareTwoThings라는 튜플 타입의 변수를 사용하여 승리 케이스를 간결하고 가독성 높게 잘 바꿔주셨어요!! 제가 의도한 바와 동일합니다! 훌륭합니다 🤗🤗

3. 가위바위보에서 묵찌빠로 넘어갈때 묵찌빠에서 비기지않고 지거나 이길경우 다시 묵찌빠 로직을 실행할때 턴을 누가어떻게 잡을건지 매우 고민했었습니다. 이를 startMukChiBbaGame 함수의리턴값으로 튜플을 전달해서 스위치구문으로 누가 턴을 잡을건지 구현했었는데 이보다 더 간결하게 할수있는방법이 있을까 질문드립니다!

> 코드에서 자세하게 코멘트 남기도록 하겠습니다.

## 해결이 되지 않은 점

1. 묵찌빠게임과 가위바위보게임에 관련된 함수를 서로 다른 파일로 분리하지 못했습니다. PR 후에 수정해서 Push하겠습니다.

> 묵찌빠게임과 가위바위보게임 관련 함수를 서로 다른 파일로 분리하지 못한 이유를 알 수 있을까요? 시간이 부족해서인지, 아니면 어떻게 나눠야할지 방향을 못 잡은건지 궁금하네요. 저는 PR 후에 수정해서 push하겠다는 의미는 어떤 부분이 잘못되었고 어떻게 고쳐야할지 인지하였으나 일단 PR을 보내고 고치겠다는 의미로 받아들여집니다. PR은 일단 보내놓고 추가 수정을 하는 것보다는, 최대한 완성도 있는 코드로 PR을 보냈는데도 미처 생각하지 못했던 점이나 리뷰어의 코멘트에 새롭게 알게된 부분을 수용하여 코드를 보완하는 작업이라고 생각합니다. 일단 보내놓고 수정하겠다는 생각은 조금 아닌 것 같아요 🥲 혹시 제가 오해한 것이라면 사과드립니다...

## 조언을 얻고 싶은 점

1. 코드를 작성하는데 의도치않게 한 함수에 많은 기능을 담아서 구현하다가 나중에 이걸 어찌 나눌까 난감할때가 종종 있었습니다. 이미 선언한 변수들, 앞 뒤로 이미 쓰여진 코드와 매끄럽게 이어지게 하기가 매우 어려웠습니다. 최대한 나눈다고 나누긴 했는데 보시고 더 나눌수있는 부분이 있다면 조언해주세요!

> 하나의 메서드를 10줄 이내로 적는 연습을 해보면 좋을 것 같아요!! 현재 제가 보기에는 하나의 메서드가 하나의 기능 이상을 하는 부분을 종종 발견하였습니다! 이는 코드에서 자세히 다루어봅시다! 처음부터 익숙해지기엔 매우 어렵습니다. 지금부터 하나하나 연습해보시면 나중에는 능숙하게 분리를 하실 수 있을거예요!! 화이팅입니다!! 👍👍

2. 아무래도 재귀함수가 아닌 while 문을 통해 반복이 진행되다 보니 게임 진행 결과를 return값으로 받아 게임 종료를 결정하곤 했습니다. 이럴 때마다 '전역변수를 쓰면 참 편할텐데'라는 유혹이 듭니다..😂 함수 간에 소통할 때 Bool타입으로 return받아 의사결정이 이루어지는 과정이 자연스러운지 잘 모르겠습니다.

> 게임 진행 결과를 return으로 전해주는 방법도 매우 좋은 방법입니다! 메서드와 메서드 간 소통(?)을 할 때, return 값을 이용하는 경우는 매우 자연스러운 경우이므로 걱정하지 않으셔도 됩니다! 한가지 궁금한 점은 전역변수 사용을 걱정하여 사용을 자제해주셨는데, 함수는 지금 어떤 범위에서 작성되고 있을까요? 전역 변수 사용을 자제하고 싶다면, 그에 따른 함수 또한 전역 함수가 아닌 범위에서 사용되어야 하지 않을까요? struct나 class를 이용해보는 것은 어떤가요?

2022-08-25 07:53 UTC, Jeon-Minsu requested changes
기본적으로 네이밍 관련 수정이 많이 필요해보였습니다!
Swift API Design Guideline을 꼼꼼히 확인해보시고 네이밍을 좀 더 연마해봅시다!
코멘트에 대하여 이해가 되지 않는 부분이 생기시면 부담없이 말씀해주세요!! 🤗🤗

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors.xcodeproj/project.pbxproj
> +				57F2414128B47592007412C5 /* RockScissorsPaperGame.swift in Sources */,
파일의 네임을 적절하게 잘 변경해주셨군요!! 👍👍

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +//
주석도 빠뜨리지 않고 알맞게 바꾸면 좋을 것 같아요!! 🤩

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +import Foundation
Foundation이 이번 프로젝트에서 필요할까요?? 🧐
Foundation에 대하여 공식문서를 보며 어떠한 기능을 하는지 알아보는 시간을 가져봅시다!!
(https://developer.apple.com/documentation/foundation)

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +//
여기도 주석 변경해주세요!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
이 파일에서도 Foundation이 필요할지 고민해봅시다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +}
enum을 통해 매직 넘버를 알아보기 쉽게 변경한 점 매우 좋습니다!! 👍👍

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    }
if 구문과 guard 구문의 차이점을 알 수 있을까요?
또한, 두 분께서는 어떠한 기준으로 if와 guard를 선택하는지 궁금합니다! 🤩

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    return nil
매직 넘버가 아닌 nil로 처리한 점 아주 좋습니다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
매직 리터럴을 제거해보는 건 어떨까요? 🤔

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    var exitGame: Bool = false
게임이 현재 가위바위보이기 때문에 computerNumber는 숫자라는 의미로 받아들여져 혼란이 올 수 있다고 생각합니다.
다른 네이밍을 고민해보는 것은 어떨까요? 🤔

또한, exitGame 또한 Bool 값임에도 불과하고 true/false를 담는 네이밍이라고 느껴지지 않습니다.
즉, Bool 값을 담는 프로퍼티나 메서드의 네이밍은 코드를 읽는 사람에게 assertion으로 읽혀야 합니다.
Bool값을 담는 변수의 네이밍에 대하여 [Swift API Design Guideline](https://www.swift.org/documentation/api-design-guidelines/#special-instructions) 을 참고해보면 좋을 것 같습니다!! 😃😃
지금은 오히려 메서드의 네이밍 같네요 🥹🥹

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +func readyRockScissorsPaperGame() {
해당 메서드의 네이밍은 적절한 지 다시 한 번 고민하셨으면 좋겠습니다!
제가 보기에는 이미 게임이 진행되고 있다고 생각됩니다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +}
파라미터 입력값과 파라미터 네임과의 스페이싱 확인 부탁드립니다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let selectMenu = userChoice
userChoice와 동일한 값인데 selectMenu 상수를 별도로 생성한 이유가 궁금합니다. 🧐
추가적으로, startRockScissorsPaperGame도 네이밍이 조금 명확하지 않다고 생각합니다.
어떻게 바꾸는 게 좋을까요?? 메서드의 기능이 무엇인지 고려하며 바꿔봅시다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let userPick = RockScissorsPaper(rawValue: userChoice)
computerChoice와 userChoice에 대하여 Int가 아닌 RockScissorsPaper 타입을 받아보는 것은 어떨까요??
물론 RockScissorsPaper를 따르면 부가적인 수정이 필요할 것입니다..🥲
지금도 충분히 좋은 방법이고, 하나의 제안이라고 생각해주세요!!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
compareTwoThings은 프로퍼티의 네이밍으로 적절하지 않은 것 같습니다🥲
명사형 네이밍을 사용해봅시다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    }
튜플을 이용하여 코드를 간결화하고 가독성을 높이신 점 매우 칭찬드립니다!! 👏👏
다만, 65과 69번의 `return true`는 각각 호출해야하는 이유가 있을까요? 🤔

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/main.swift
Foundation 확인 부탁드립니다

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func readyMukChiBbaGame(takeUserWin: Bool) {
메서드의 네이밍이 readyRockScissorsPaperGame와 같이 준비의 범위를 벗어나지 않은가 싶습니다.
takeUserWin 파라미터 네임도 Bool 값임을 유추하기 힘들뿐만 아니라, 사용자의 승리만 가져온다고 받아들여집니다.
수정 부탁드려요! 🙏🙏

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var computerNumber: Int
exit도 Bool 값임을 유추하기에는 아쉬운 네이밍 같습니다.
isUserWin 변수를 새로 만드신 이유가 궁금합니다!
묵찌빠에 대하여 computerNumber의 Number는 적절하지 않다고 판단됩니다.

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    }
연산 프로퍼티를 사용하셨군요!! 훌륭합니다!! 👍👍

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +                return "컴퓨터" }
연산 프로퍼티 안에 조건문을 사용하여 들여쓰기가 초과한 것 같습니다.
해당 로직에 대하여 더 간단히 표현하는 방법은 무엇이 있을까요? 🧐

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        computerNumber = Int.random(in: 1...3)
매직 넘버 마찬가지로 수정하면 좋을 것 같아요! 🥹

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var roundOneWinner: String {
roundOneWinner는 가위바위보 게임의 승리자?, 묵찌빠 게임의 공격권을 가진 자?로 보기에는 다소 아쉽습니다!
더 나은 네이밍을 고민해볼까요?

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        guard let userNumber = filterUserInput() else {
filterUserInput은 가위바위보 게임과 묵찌빠게임에서 모두 사용되고 있네요!
그렇다면 과연 가위바위보 게임 파일 안에 위치하는 게 옳을까요? 🤔🤔
공통된 기능에 대하여 어떻게 처리하면 좋을까요?
현재는 모든 함수가 전역 함수로 정의되어 있는데, struct나 class에 담아보는 것은 어떨까요?
그리고 해당 타입에서 공통된 기능을 어떻게 처리하는지 공부해보시면 좋을 것 같습니다.

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +            }
들여쓰기가 과도하게 사용되고 있습니다! 
사용자의 턴일때만 컴퓨터의 턴으로 넘기기 위하여 조건문을 사용하여 토글을 하고 계신데,
isUserWin = false로 간단하게 표현해보는 것은 어떨까요?

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +            continue
continue가 작용하는 범위를 다시 한 번 재고해보았으면 좋겠습니다.
해당 continue는 while문의 영역까지 영향을 미칠까요, 아니면 guard문의 영역까지 영향을 미칠까요? 🤔

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        var exitOrTurnChange = (canExit: exit, checkUserWin: isUserWin)
네이밍이 부적절해보입니다.. 🥲
해당 결과에 대해서 간단히 생각해보면, 묵찌빠 게임에 들어가 사용자가 묵, 컴퓨터까 찌를 내는 경우는 exit, turnChange 어느 영역에도 해당되지 않습니다. 이를 모두 아우를 수 있는 네이밍을 고민해봅시다.

파라미터 네임도 마찬가지로 고민해봅시다. 누구의 턴인지, 승리자가 정해진 것인지, 아니면 승리자가 정해지기 전 게임 종료가 된 것인지 명확히 할 필요가 있다고 생각합니다. checkUserWin도 Bool 값으로 설정해서 그런지, 너무 사용자 입장에서 생각한 것 같습니다.

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        exitOrTurnChange = startMukChiBbaGame(computerNumber: computerNumber, userNumber: userNumber, takeUserWin: isUserWin)
34번과 35번 줄을 나누어서 작성하신 이유가 궁금합니다. 🤔
한번에 초기화하면 안될까요?

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        }
38번 줄만 _ 를 사용하신 이유가 있을까요? 🤔
또한, continue 범위 재고해주세요
case에서 튜플의 파라미터 네임 생략 가능합니다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func startMukChiBbaGame(computerNumber: Int, userNumber: Int, takeUserWin: Bool) -> (Bool,Bool) {
메서드, 파라미터 네이밍 고민해보시면 좋을 것 같습니다!
메서드가 해당 기능을 사용하고 있는지, Number를 사용하는 것인지, takeUserWin은 과연 옳은 표현일지 생각해봅시다!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var takeUserWin = takeUserWin
다시 변수에 담으신 이유를 알 수 있을까요?

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    let compareTwoThings = (computerPick, userPick)
상수 네이밍 고쳐주세요!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    }
return 값인 튜플 사이에 스페이싱 확인해주세요!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    return (false,takeUserWin)
스페이싱 확인해주세요!
그리고, 묵찌빠 게임에서 비기지 않을 경우 누구의 턴으로 가는지 출력문이 누락되었습니다.

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +}
메서드 분리에 관하여 판단하는 로직이 담긴 부분을 하나의 메서드 안에 넣어서, 
묵찌빠 게임 승리자가 정해진 경우와 정해지지 않은 경우에 대한 조건문들을 또 다른 별도의 메서드로 분리할 수 있지 않을까 싶네요!

약식으로 표현하면, 아래와 같을 것 같아요!

```
func 전체판단 {
    승리자 있는지 판단하는 메서드()
    누구의 턴인지 판단하는 메서드()
}
```

잘 이해가 되지 않으시면 언제든지 말씀해주세요!

2022-08-25 07:53 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    var computerNumber: Int
`var computerNumber: Int` 선언이 while문 밖에 있어야하는 이유가 있을까요?

2022-08-25 13:05 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors.xcodeproj/project.pbxproj
> +				57F2414128B47592007412C5 /* RockScissorsPaperGame.swift in Sources */,
감사합니다 ㅎㅎ 👍

2022-08-25 13:07 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +//
파일을 변경하면서 빠트렸네요 ..! 수정하고 앞으로 주석 더 신경쓰겠습니다 :)

2022-08-25 13:11 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +import Foundation
다른파일들은 import Foundation이 필요없지만 
RockScissorsPaperGame파일에는 replacingOccurrences 함수가 필요로하는것을 확인했습니다! 공식문서 링크 감사합니다 참고할게요!

2022-08-25 13:14 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
위로2칸 코멘트 내용과 동일합니다!

2022-08-25 13:31 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    }
- 이 부분은 제가 함수를 나누면서 if구문을 사용한 것이기 때문에 우선 제가 답변을 해보겠습니다..! if let 문은 if 블록 안에서만 선언한 상수를 사용할 수 있고, guard let 구문은 else블록 바깥 전부에서 사용 가능하다고 알고 있습니다. 또 guard는 조건에 맞지 않을 시 조기탈출이 가능하다는 특징이 있다고 알고 있습니다. 

- 우선 제가 이 userNumber를 리턴하는 과정에서 If를 쓴 이유는 userNumber라는 입력값은 3가지 조건에 부합해야 올바른 값으로 인정돼 리턴된다는 목적을 전달하고싶어서였습니다. 평소에 binding된 상수를 많이 사용해 코드의 길이가 길어지는 경우 guard를 통해 바깥에서 사용해주지만 코드의 길이가 크게 차이가 나지 않고, 조건문 안에 정당한 값이 리턴된다는 걸 보여주는게 이 함수가 원하는 방향을 좀 더 확실하게 전달할거라고 생각해서 If를 사용해봤습니다...물론 이런 이유도 저의 생각일 뿐이라 확신이 있진 않습니다 😅..

2022-08-25 13:32 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    return nil
감사합니다 ! nil을 리턴하면서 이렇게 해도 되나 생각했는데 다행이네요😇

2022-08-25 13:50 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    }
if와 guard 구문의 차이에 대하여 잘 파악하셨군요!!

if문 사용에 대하여 근거를 아주 명확히 밝혀주셔서 매우 좋았습니다!! 😁😁 저도 if문의 경우 depth가 깊어질 가능성이 높아 사용에 주의를 가하지만, 오히려 if문을 통해서 더욱 명확히 표현할 수 있는 장점도 존재합니다! 앞으로도 코드를 작성하면서 본인만의 기준을 공고히 하셨으면 좋겠습니다!!

2022-08-25 14:11 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +}
감사합니다! 👍 👍

2022-08-25 14:12 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
enum타입의 케이스 값들을 랜덤으로 받을수있게 수정했습니다!

2022-08-25 14:13 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    var computerNumber: Int
함수 내에서 computerNumber라는 변수를 사용할 것이기 때문에 먼저 선언하고 시작했던 것 같습니다. 그리고 computerNumber 변수는 이번 수정과정에서 없애고 computerPick 선언에서 곧바로 Enum의 랜덤 case를 불러오는 방식으로 변경했습니다.

2022-08-25 14:29 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    var exitGame: Bool = false
확인했습니다! 앞에 is라는 단어를 추가해서 수정했습니다!

2022-08-25 14:29 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +//
확인했습니다!

2022-08-25 15:06 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +func readyRockScissorsPaperGame() {
최대한 함수의 기능에 걸맞는 네이밍으로 수정해봤습니다 !

2022-08-25 15:08 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +}
앗 이런부분을 확인못했었네요... 매의눈이십니다..! 👀

2022-08-25 15:11 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let selectMenu = userChoice
- 다시 확인하니 필요없는 부분이라고 생각되어 해당 상수는 삭제했습니다 🥲
- 해당 함수는 묵찌빠를 시작하기 전에 누구의 턴으로 시작할지 정하는 함수라고 생각해 decideWhoStartsFirstTurn()라고 네이밍을 바꿨습니다!

2022-08-25 15:18 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let userPick = RockScissorsPaper(rawValue: userChoice)
생각해보니 굳이 computerChoice를 인자로 받을필요없이 그 함수내부에서 자체적으로 랜덤값을 생성해줘도 괜찮을거라 판단해서 startRockScissorsPaperGame 함수 내부에서 랜덤값을 생성하도록 수정했습니다!

2022-08-25 15:26 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
comparisonOfTwoThing로 수정했습니다!

2022-08-25 15:29 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/main.swift
넵 확인했습니다!

2022-08-25 15:30 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    }
두 가지 경우 모두 같은 true를 return해주는군요,..! switch문 바깥에서 return true 하나만 쓰는 방법으로 수정했습니다!

2022-08-25 15:44 UTC, jonghancha commented
해결이 되지 않은 점에 파일 분리 이야기를 한 것은 create new PR 하고 입력하는 도중에 파일분리 문제를 발견해서였습니다 ..ㅜㅜ PR 전에 완벽히 준비를 못한 저희의 잘못입니다 죄송합니다. PR 입력 중에 push를 하면 혹시나 파일이 꼬이거나 하는 상황이 걱정돼 해결되지 않은 부분에 쓰게 되었습니다. 혹시나 저희가 성의 없게 느껴지셨다면 정말 죄송합니다😭. 앞으로는 PR 전에 더블체크하는 습관 들이겠습니다!

2022-08-26 01:24 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var takeUserWin = takeUserWin
다시 확인해보니 써줄필요가 없다고 판단되서 변수선언부분을 삭제했습니다! 👍 👍

2022-08-26 02:00 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +            }
아....🥵 민망합니다..잘못된 값을 입력한다면 사용자의 턴이던 컴퓨터의 턴이던 모두 컴퓨터의 턴으로 수렴하게되죠,,
isUserWin = false 한 문장으로 수정했습니다!

2022-08-26 02:07 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var computerNumber: Int
* exit -> isExitGame으로 수정했습니다!
* isUserWin -> isUserTurn으로 수정했습니다 이 변수를 만든 이유가 묵찌빠에서 비기지않을경우 다시 묵찌빠를 진행할때 누가 턴을 잡을지 결정하기위해 만들었습니다. 그리고isUserTurn의 변화를 roundOneWinner연산프로퍼티에서 get으로 받아 실시간으로 누구의 턴인지 보여주기 위함이기도 합니다. 
* 저도 수꿍과 같은 의견입니다! decideWhoWins함수 내부에서 enum타입의 allCases.randomElement()를 통해 랜덤 묵찌빠를 고르게 수정했습니다!

2022-08-26 02:11 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    }
감사합니다: 👍 👍

2022-08-26 02:14 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +                return "컴퓨터" }
삼항연산자를 통해 코드1줄로 압축했습니다! 이런 방법이 있었군요 + _ +

2022-08-26 02:19 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        computerNumber = Int.random(in: 1...3)
네 위에서와 마찬가지로 let computerPick = MukChiBba.allCases.randomElement() 를 사용해 바로 할당해주었습니다!

2022-08-26 02:27 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var roundOneWinner: String {
좀 직접적이긴 하지만 mukChiBbaAttacker로 변경해봤습니다.

2022-08-26 03:23 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        guard let userNumber = filterUserInput() else {
공통적으로 사용되는 함수를 따로 파일로 이동시켰습니다. 그리고 파일마다 class타입에 담고 상속을 통해 공통된 기능을 사용하게 구현했습니다. 
가위바위보게임 내부에서 묵찌빠 클래스의 함수를 사용할 때에는 인스턴스를 생성해주어 함수를 사용하게 구현했습니다!

2022-08-26 03:55 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        var exitOrTurnChange = (canExit: exit, checkUserWin: isUserWin)
* 유저가 0을 내거나 서로 다른것을 낼경우 둘다 포함하기때문에 isExitOrWhoseTurn이라고 네이밍을 지었습니다 
* checkUserWin -> checkUserTurn으로 수정해서 사용자 턴인가 아닌가를 명확하게 했습니다! 그리고 checkUserTurn파라미터는 isUserTurn을 받는데 isUserTurn은 MukChiBbaAttacker의 프로퍼티연산 get에 true인지 false인지에 따라 "사용자" 또는 "컴퓨터" 턴임을 표시하기때문에 bool값으로 설정해주었습니다

2022-08-26 04:00 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        exitOrTurnChange = startMukChiBbaGame(computerNumber: computerNumber, userNumber: userNumber, takeUserWin: isUserWin)
canExit, checkUserTurn 이름을 붙여서 어떤 값인지 파악하기 쉽게하기 위해 선언을 먼저 해주고 할당을 했습니다.
 하지만 타입에 이름을 붙여주어 한번에 초기화하는 방법으로 수정했습니다!

2022-08-26 04:09 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func startMukChiBbaGame(computerNumber: Int, userNumber: Int, takeUserWin: Bool) -> (Bool,Bool) {
- 메서드명은 decideWhoWins로
- 파라미터 명은 userInput과 isUserTurn으로 변경했습니다!

2022-08-26 04:10 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    let compareTwoThings = (computerPick, userPick)
compareTwoThings -> comparisonOfTwoThings 으로 수정했습니다!

2022-08-26 04:11 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    }
스페이싱 수정했습니다 :)

2022-08-26 04:15 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    return (false,takeUserWin)
확인했습니다! 
윗부분에 MukChiBbaAttacker의 프로퍼티연산으로 takeUserWin(isUserTurn) 이 true/false값을 반환하면  "컴퓨터" 또는 "사용자" 턴이 출력되게 했습니다!

2022-08-26 05:07 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +}
startMukChiBbaGame (네이밍변경) -> decideWhoWins함수를 if문과 swich문을 따로 나누어  decideWhoWins 와 decideWhoseTurn 2개의 함수로 분리했습니다.

2022-08-26 05:10 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func readyMukChiBbaGame(takeUserWin: Bool) {
넵! 확인했습니다. 
함수네이밍은 startMukChiBbaGame으로, 파라미터명은 isUserTurn으로 수정했습니다!

2022-08-26 11:00 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    var exitGame: Bool = false
제가 영어를 잘 하지 못해서 isExitGame이 관용적으로 맞는지 잘 모르겠어요..
저는 이게 "방탈출 게임이니?" 같은 의미로 읽히는데, isGameOver 네이밍을 사용해보는 건 어떨까요? 🤔

2022-08-26 11:09 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let selectMenu = userChoice
코멘트를 반영하여 잘 수정해주셨군요!!
다만 아쉬운 점은, startGame 메서드 내에 `isExitGame = decideWhoStartsFirstTurn(with: userInput)` 부분에 대하여 연결이 부자연스럽다는 생각이 들어요.
저라면, RockScissorspaperGame 클래스 내에 isExitGame 프로퍼티를 선언할 것 같은데, 한 번 고려해보시면 좋을 것 같습니다!! 😃

2022-08-26 11:10 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let userPick = RockScissorsPaper(rawValue: userChoice)
CaseIterable 프로토콜을 사용하여 randomElement() 메서드를 사용해보셨군요!!
아주 좋습니다!! 불필요한 파라미터를 훌륭하게 삭제해주셨습니다!! 👍👍

2022-08-26 11:11 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
명사형으로 잘 바꿔주셨어요!! Things 보다 Picks를 사용해보는 것도 추천드려요! 😆

2022-08-26 11:14 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func readyMukChiBbaGame(takeUserWin: Bool) {
네이밍을 잘 바꿔주셨습니다!
다만, 아쉬운 점은 RockScissorsPaperGame의 경우에는 startGame()으로 네이밍을 하셨는데, 컨벤션이 통일되었으면 하네요!!
제 생각에는 인스턴스를 생성함에 있어 어떤 게임인지 알 수 있으니 startGame()이나 start()로 간단히 표현할 수 있을 것 같아요!! 중복되는 부분은 최대한 줄여봅시다!

```swift
let rockScissorsPaperGame = RockScissorsPaperGame()
rockScissorsPaperGame.start()
```

2022-08-26 11:16 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    var computerNumber: Int
아주 잘 바꿔주셨습니다!!
isExitGame 경우만 위의 코멘트를 참고하여 수정해보면 좋을 것 같습니다!

2022-08-26 11:16 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +                return "컴퓨터" }
척하면 척 아시는군요!! 훌륭합니다!! 👍👍

2022-08-26 11:23 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        guard let userNumber = filterUserInput() else {
struct와 class 중 class를 사용해보신 이유를 알 수 있을까요?
상속을 사용하여 공통된 기능을 사용해보는 것도 방법 중 하나입니다.
하지만 그러기 위해서는 상속 클래스와 피상속 클래스 간 정말 상속 관계에 있는지 확인해보아야 합니다.
CommonFunctions는 가위바위보 게임보다 상위의 객체임을 유추할 수 있을까요?
공통된 기능을 사용하는 방법으로 protocol을 활용하는 방법도 있을 것 같습니다.
저의 경우라면 protocol과 extension을 활용하여 공통의 기능을 미리 구현하여 각각의 게임에서 해당 프로토콜을 채택해볼 것 같습니다!
그리고 피상속 클래스의 네이밍으로서 CommonFunctions은 다소 부적합해 보입니다!

2022-08-26 11:28 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        exitOrTurnChange = startMukChiBbaGame(computerNumber: computerNumber, userNumber: userNumber, takeUserWin: isUserWin)
좋습니다! 해당 방법을 사용하면 변수가 아닌 상수로 선언할 수 있어 더 좋아보입니다! 🤗

2022-08-26 11:33 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        var exitOrTurnChange = (canExit: exit, checkUserWin: isUserWin)
isExitOrWhoseTurn의 경우에도 가위바위보 게임에서와 같이 isGameOver 변수를 클래스 내부에 생성한다면 튜플을 사용하지 않고 하나의 타입만을 이용하여 표현할 수 있지 않을까 싶네요!

그리고 isUserTurn의 경우 저라면 Bool 값보다는 "사용자", "컴퓨터"임을 볼 수 있게 하는것이 더 명확하지 않을까 싶어요! 그래서 저는 이를 enum에 넣어서 별도의 타입을 만들어볼 것 같네요! 묵지빠를 enum으로 빼신 것 처럼요!

2022-08-26 11:44 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func startMukChiBbaGame(computerNumber: Int, userNumber: Int, takeUserWin: Bool) -> (Bool,Bool) {
WhoWins 보다는 Winner가 좋아보입니다!

2022-08-26 11:45 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    let compareTwoThings = (computerPick, userPick)
Picks 사용 추천합니다!

2022-08-26 11:48 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    return (false,takeUserWin)
실행 예시를 다시 한 번 확인해주세요! 🙏🙏
"사용자의 턴입니다", "컴퓨터의 턴입니다"라는 문구가 실행되고 있지 않습니다! 
```
가위(1), 바위(2), 보(3)! <종료 : 0> : 1
이겼습니다!
[사용자 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 6
잘못된 입력입니다. 다시 시도해주세요.
[컴퓨터 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 3
컴퓨터의 턴입니다
[컴퓨터 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 3
사용자의 턴입니다
[사용자 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 3
사용자의 승리!
게임 종료
```

2022-08-26 11:54 UTC, Jeon-Minsu commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +}
메서드를 분리하기 위하여 노력해보셨군요! 아주 좋은 시도입니다! 👍👍

제가 좀 더 조언을 드리자면, 약식으로 표현해보았지만 아래와 같이 변경해보는 것은 어떨지 여쭈어보고 싶습니다!
```
func checkGameResult() {
    guard decideWhoWins() != nil else {
        return
    }
    decideWhoseTurn()
}
```

게임 결과를 체크하는 함수만을 호출하고, 내부에서 승자가 있으면 승자를 출력하고, 승자가 없다면 누구의 턴인지 확인하는 방법으로 분류를 해보았습니다.
여러분이 한 방법도 좋은 방법이라고 생각합니다! 두 방법을 고민해보고 어떤 방법이 프로젝트에서 말한 묵찌빠에 적합한지 고민해보시면 좋겠습니다!

2022-08-26 12:00 UTC, Jeon-Minsu commented
프로젝트 2주차로 PR이 익숙하지 않은데, 제가 너무 처음부터 완벽하기를 바란 것 같습니다. 이로 인하여 여러분들의 마음을 불편하게 하여 사과의 말씀을 전합니다. 좀 더 너그럽게 다룰 수 있는 사안이었는데 오해를 하여 감정적으로 대처한 것 같습니다. 그럼에도 완성도 있게 리팩토링을 진행해주셔서 정말 감사할 따름입니다. 🥲

전체적으로 코멘트를 바탕으로 리팩토링을 훌륭히 해주셔서 추가적인 코멘트가 많지 않았습니다! 순서도도 언급하지 않았는데 열심히 작성하셔서 올려주시고 매우 대단합니다!! 👍👍 추가적으로 코멘트 남긴 부분만 다시 한 번 봐주세요!!

2022-08-27 04:07 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    var exitGame: Bool = false
isGameOver가 게임이 끝났는가?라는 의미에 좀 더 가까운 것 같네요! 수정했습니다.

2022-08-27 04:15 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let selectMenu = userChoice
저희가 생각했을 때도 isGameOver: Bool 에 함수의 리턴을 받는 과정이 부자연스러운것 같아 isGameOver를 프로퍼티로 선언해주고 decide함수 내에서 프로퍼티의 값을 변경해주었습니다!

2022-08-27 04:15 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +    let userPick = RockScissorsPaper(rawValue: userChoice)
감사합니다! 👍

2022-08-27 04:17 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGame.swift
> +
오! computerPick, userPick을 비교하는건데 Picks를 쓸 생각을 못했네요 😮

2022-08-27 04:21 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func readyMukChiBbaGame(takeUserWin: Bool) {
넵 확인했습니다!

2022-08-27 05:38 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        var exitOrTurnChange = (canExit: exit, checkUserWin: isUserWin)
* 수꿍의 의견대로 var isGameOver: Bool = false를 MukChiBbaGame클래스 안에 생성하고 decideWhoWins함수 내부에서 승부가 판가름나면 튜플을 반환하는것에서 아무것도 반환하지 않고 그저 isGameOver = true로 변경하였습니다!
* enum타입 Player에 "컴퓨터"와 "사용자"를 케이스별로 생성했습니다. var attacker: Player를  MukChiBbaGame클래스 안에 생성하여 컴퓨터와 유저 둘중 한쪽이 묵찌빠에서 턴이 바뀌게된다면 attacker = Player.누구 이런식으로 리턴을 쓰지않고도 값을 변경하게 만들었습니다!

2022-08-27 05:43 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +func startMukChiBbaGame(computerNumber: Int, userNumber: Int, takeUserWin: Bool) -> (Bool,Bool) {
Winner로 수정했습니다!

2022-08-27 05:43 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    let compareTwoThings = (computerPick, userPick)
Picks로 수정했습니다!

2022-08-27 05:53 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +    return (false,takeUserWin)
아 저희가 지금까지 이부분을 빼먹고있었군요.. 다음부턴 꼼꼼하게 봐야겠습니다 😂 
decideWhoseTurn함수의 스위치문이 끝난 맨 아래에 출력되게 수정했습니다!

2022-08-27 06:03 UTC, jonghancha commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +}
저희가 위에서 코드를 수정하며 함수의 반환값들을 없앴습니다. 그래서 설명해주신 코드구조와는 살짝 다르지만 결국 같은 의미를 가지는 코드가 되긴 했습니다..ㅎㅎ 정말 훨씬 깔끔하고 좋네요 ..

2022-08-27 07:00 UTC, MangDi-L commented on RockPaperScissors/RockPaperScissors/MukChiBbaGame.swift
> +        guard let userNumber = filterUserInput() else {
* RockScissorsPaperGame와 MukChiBbaGame이 공통적으로 filterUserInput함수를 사용해서 CommonFunctions클래스의 상속을 받아 사용할수있게 class를 사용했었습니다. 하지만 이는 위의 말대로 
"상속 클래스와 피상속 클래스 간 정말 상속 관계에 있는지 확인해보아야 합니다. CommonFunctions는 가위바위보 게임보다 상위의 객체임을 유추할수 있을까요?" 
이 문구를 통해 과연 이렇게 구현하는것이 맞을까 의문이들었습니다. 그래서 제의해주신 protocol을 활용해보는 방법으로 접근해보려합니다. 
*  조언해주신 내용대로 protocol과 extension을 이용하여 구현에 성공했지만 protocol과 extension의 네이밍과 그들을 포함하는 파일명도 어떻게 지을까 고민이 되었습니다.
* 공식문서를 참고해보니 protocol의 네이밍은 무엇인가를 설명할때 명사형으로 짓고 기능을 설명할땐 able,ible,ing같은 접미사를 사용하여 이름을 붙인다고 나와있었습니다. 그래서 프로토콜의 이름을 inputFilterable로 지었습니다.
* 허나 enum,protocol,extenstion이 포함된 파일명을 어떻게 지을까 고민이 되었습니다. 이부분에 관해 파일명을 쉽게 짓는 방법이 있을까요?

2022-08-27 08:21 UTC, merged