묵찌빠 게임 [STEP 2] Baem, Dragon
yagom-academy/ios-rock-paper-scissors pull request #171
Opened 2022-08-24 16:36 UTC by Dylan-yoon

@bar-d 
[Step2] PR 보냅니다.

생각보다 저희가 기능 분리가 적었던 것 같아 다소 아쉬웠던 것 같습니다.
저희가 짠 코드에서 프로그래밍 구조에 대한 모호함이 있다고 생각됩니다.

# 😭고민했던 점
- 먼저 Step1에서의 기능 분리가 적절하게 잘 되지 않았다고 생각됩니다. 그래서 Step2를 진행하면서 생각처럼 잘 진행되지 않았습니다.

``` swift
func compareTwoInput(_ userNumber: Int, with computerNumber: Int) -> String {
...
return "컴퓨터"
return "사용자"
return "무승부"
```
와 같이  return 값을 String으로 해주었는데,
Enum 타입을 사용해서 열거형으로 정리를 해주는 것이 좋은지 고민을 했습니다.
두가지를 고려해 본 결과, Enum의 이점이 없다 판단하여 String 으로 적용했습니다.
 ## --> 이부분 조언 부탁드립니다.

더 생각해 봐야 할 부분
- 재귀 함수에 대해 좀 더 알아보려 함.
- 함수 기능분리를 더 적절하게 하려고 노력 해야 겠음.
- Enum을 적절하게 사용해서 핸들링 할 수 있도록 노력해야 겠음.

2022-08-25 06:32 UTC, bar-d commented
step2 진행하시느라 고생하셨습니다  
## 👏칭찬드리고 싶은 점

### 해당 프로젝트 명세서에 맞게 구현해내신 점👏  
- 전반적인 로직은 잘 구현해주신 것 같아요 
### 이전보다 코드 가독성이 좋아졌어요 👏👏  
- 개행을 적절히 사용해주셔서 저는 코드가 훨씬 보기 좋아졌어요  
다만 함수 순서도 신경 써주시면 더 좋은 코드가 될 것 같아요  

## 개선하면 좋은 점
### 함수 순서를 변경해주셨으면 좋겠어요  
코드는 위에서 아래로 읽기 때문에 저는 함수 실행 순서대로 함수를 놓는 편이에요  
그래야 저는 코드가 잘 읽어지더라고요  
한번 적용해보시고 어떤 방법이 더 코드가 잘 읽어지는지 경험해보시고 적용하시면 좋겠어요

### 함수 return값
```swift
func createUserNumber() -> Int? {
     let userInput = readLine()
    
    if let userNumber = checkUserInput(userInput) {
        return userNumber
    } else {
        return nil
    }
  }
```
해당 함수에서 else구문을 통과할 일이 있을까요?

## 😭고민했던 점

>먼저 Step1에서의 기능 분리가 적절하게 잘 되지 않았다고 생각됩니다.  
 그래서 Step2를 진행하면서 생각처럼 잘 진행되지 않았습니다.
- 유효성을 검사해주는 것들도 검증 별로 함수로 나눠줄 수 있을 것 같아요  
그 이외에는 함수분리를 잘 해주신 것 같습니다
```swift
func compareTwoInput(_ userNumber: Int, with computerNumber: Int) -> String {
...
return "컴퓨터"
return "사용자"
return "무승부"
```
>와 같이 return 값을 String으로 해주었는데,  
Enum 타입을 사용해서 열거형으로 정리를 해주는 것이 좋은지 고민을 했습니다.  
두가지를 고려해 본 결과, Enum의 이점이 없다 판단하여 String 으로 적용했습니다.  
--> 이부분 조언 부탁드립니다.

- 코드를 작성하면서 직접 값을 그때마다 입력해주면 오타가 날 수도 있어요  
오타를 작성하는 실수를 방지하기 위해 `enum` 타입을 사용해보는 것도 좋을 것 같아요  
또한 `enum` 타입을 파일로 따로 분리해서 관리해 줄 수 있을 것 같아요   
해당 리턴 값들도 `enum`타입이나, 매직 리터럴로 처리해줄 수 있을 것 같아요   
`enum`타입을 만들어 준다면 `HandShape`으로 손모양으로 case를 주고  
```swift
func compareTwoInput(_ userNumber: HandShape, with computerNumber: HandShape) -> String {
```  

-  이런 식으로 쓸 수 있지 않을까요

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/WinnerResult.swift
> +}
해당 파일은 프로젝트를 열어보면 보이지가 않네요?

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +
함수의 리턴값 전에 개행을 해주셨군요 👍

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func excuteSRP() -> String {
이전 함수명에서 축약을 해주신 이유가 있을까요?
원어민이 아닌 외국인이 해당 축약어를 보고 SRP가 무엇을 의미하는지 알 수 있을까요?

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("잘못된 입력입니다. 다시 시도해주세요.")
출력하는 구문을 함수로 빼낼 수 있을 것 같아요

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
continue는 어떠한 역할을 해주는 제어 전송 구문인가요

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func excuteMJB(_ winner: String) -> String {
축약어는 지양해주세요
전달인자를 사용해 보는 것도 좋을 것 같아요   
어떠한 승자인지를 명시해주는 것도 좋아요

2022-08-25 06:33 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("[\(winner)의 턴입니다] 묵(1), 찌(2), 빠(3)! <종료 : 0> : ", terminator: "")
함수 분리 가능할 것 같습니다

2022-08-25 09:09 UTC, DrageunKim commented on RockPaperScissors/RockPaperScissors/WinnerResult.swift
> +}
해당 파일은 사용하지 않게되어 삭제했습니다.

2022-08-25 09:09 UTC, DrageunKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +
👍

2022-08-25 09:09 UTC, DrageunKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +func excuteSRP() -> String {
축약할지 풀네임으로 쓸지 고민하다가 일단 축약적으로 사용한 네이밍입니다.
사용한 이유는 저희들의 편의성와 아래 프린트되는 문구로 함수명 유추가 가능할 것같아 축약했었습니다.
그래도 풀네임으로 써줘야 확실한 의미가 전달되는 것에는 동의하여 풀네임으로 변경하였습니다~!

2022-08-25 09:09 UTC, DrageunKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
사용자가 잘못된 입력을 하였을 경우 다음 실행구문들을 건너띄고 반복을 다시 시작해주는 역할입니다!

2022-08-25 09:09 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +func excuteMJB(_ winner: String) -> String {
네! 전달인자 추가와 어떤승자인지 명시하였습니다!

2022-08-25 09:09 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("잘못된 입력입니다. 다시 시도해주세요.")
출력하는 구문을 함수로 빼야하는 이유를 모르겠습니다...🥲
저희가 프린트문을 빼지 않아도 된다고 생각한 이유는 많은 프린트문을 다뤄야한다면 빼줘야 하지만 그렇지 않다고 생각하여
오히려 코드 직관성을 떨어트린다고 생각되어 프린트문은 지금 위치에 있는게 좋다는 의견입니다.
추가로, 가위바위보를 실행하는 함수에서 출력되는 프린트문 한줄은 가능하다고 생각되고,
가위바위보를 실행하는 점에서 더 직관적으로 보기 좋다고 생각합니다.

마지막으로 바드의 생각도 궁금합니다!😃

2022-08-25 09:09 UTC, DragonYG commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("[\(winner)의 턴입니다] 묵(1), 찌(2), 빠(3)! <종료 : 0> : ", terminator: "")
excuteSRP 와 동일한 의견입니다.

2022-08-25 16:41 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("잘못된 입력입니다. 다시 시도해주세요.")
드래곤과 뱀이 말씀해주신 것처럼 해당 출력 구문을 함수로 빼내주면 재사용성이 늘어납니다
그리고 해당 리터럴을 매번 입력하게 되면 오타를 입력할 위험이 있어요
코드가 한 줄이어도 재사용이 많이 되는 코드라면 따로 빼주는 것이 맞다고 생각합니다
지금같이 해당 출력문이 한번만 사용되면 드래곤과 뱀처럼 생각을 할 수 있을 것 같아요  
하지만 저는 출력을 해주는 것도 기능으로 볼 수 있다고 생각을 해서 말씀드렸어요

2022-08-25 16:42 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
다른 제어 전송 구문들에 대해서도 공부해보시면 좋을 것 같아요  
제대로 알고 사용하는 코드👍

2022-08-25 16:45 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +func excuteMJB(_ winner: String) -> String {
참고로 묵찌빠는 영어로 고유명사가 있답니다

2022-08-25 16:50 UTC, bar-d requested changes

2022-08-25 16:50 UTC, bar-d commented on RockPaperScissors/RockPaperScissors/main.swift
> +        default :
```suggestion
    while true {
        switch gameResult {
        case "무승부":
            print("\(winner)의 승리")
            return
        case "사용자":
            winner = "사용자"
            gameResult = excuteMukChiBa(from: winner)
        case "컴퓨터":
            winner = "컴퓨터"
            gameResult = excuteMukChiBa(from: winner)
        default:
```
보통 콜론 앞은 붙여주고 뒤는 띄어줍니다

2022-08-26 01:53 UTC, DrageunKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +        default :
알겠습니다!~ 컨벤션 확인 감사합니다~~!

2022-08-26 07:20 UTC, merged