묵찌빠 게임 [STEP 2] Jeremy, 애쉬
yagom-academy/ios-rock-paper-scissors pull request #172
Opened 2022-08-25 02:05 UTC by ash-youu

#### 안녕하세요 핀(@finnn1)!
#### 이번 프로젝트 Step2까지 구현하게 되어 PR 보내드립니다 🤓 
---
### 🤷‍♀️ 고민되었던 점
1. 높은 코드 중복도에 대한 고민
: Step1 가위바위보 게임 이후 Step2에서 묵찌빠 게임을 구현을 고민하던 도중 게임의 승자를 판단하는 함수, 사용자의 입력을 받는 함수, 사용자 입력에 따른 게임 메뉴를 여는 함수 등 두 게임에서 중복되는 함수가 많다는 생각을 하였습니다.
이에 클래스를 만들어 일반화하는 리팩토링 방식에 대해 고민하게 되었습니다.
-> Game 이라는 부모 클래스를 만들어 중복되는 코드를 해당 클래스 안에 작성하고, 게임별로 필요한 부분만 Overriding하여 수정하였습니다.

2. Fuction Override 시 프로퍼티를 변경하지 못하는 점때문에 고민이 있었습니다.
: 함수의 프로퍼티까지 전부 동일하지 않으면, 같은 함수라고 인식하지 않는 사실로 인해 처음에는 자식클래스에서 함수명만 동일한 함수를 새로 정의하는 방식으로 코드를 구현했었습니다.
-> 동일한 코드를 클래스화 하여 중복도를 줄이는 것이 기존 목표였기에 함수의 파라미터로 받아오려 했던 인자를 전역변수로 선언해 파라미터를 통일하는 것으로 수정하였습니다.
---
### 🔍 조언을 얻고 싶은 부분
1. 묵찌빠와 가위바위보게임의 네이밍에 대한 고민
영어로는 두 게임 모두 RockPaperScissors 으로만 네이밍 될 수 있을 것 같아 묵찌빠를 한국어 표기 그대로 mukjjippa 로 네이밍 하였습니다. 이런 한글 표기 그대로의 네이밍을 사용하여도 괜찮은 걸까요? 🥹
2. 네이밍 길이에 대한 고민
필요한 단어를 모두 포함하다보니 저희가 느끼기에 다소 길다고 느껴지는 네이밍들이 있었습니다. 적절한 네이밍 길이에 대한 조언을 주실 수 있을까요?
---
### 📝 추가 History
고민되었던 점 1번에서 이어지는 사항으로 코드의 단위와 재사용성에 대해 고민하며, 클래스화에 대한 논의를 하면서 프로젝트를 진행하다보니 코드 구조의 대격변이 일어났습니다...
함수 단위의 단위로 커밋을 하고자 하였는데, 이로 인해 파일 별 커밋을 하게 된 점 참고 부탁드리겠습니다. 🥲

2022-08-25 07:44 UTC, finnn1 commented
안녕하세요 Jeremy, Ash! ☺️
이번 STEP2도 정말 빠르게 진행해주셨네요!
그럼에도 많은 부분에서 고민하신 흔적이 느껴지는 코드였습니다 👍
Step 1 때부터 너무 잘 해주고 계세요!☺️

최대한 코멘트 남겨드렸지만 혹시라도 이해가 안되는 부분이 있다면 언제든지 질문해주세요 ☺️

## 🔍 조언을 얻고 싶은 부분에 대해서 :
### 묵찌빠와 가위바위보게임의 네이밍에 대한 고민
질문 주신 내용을 보고 저도 묵찌빠에 대해서 찾아봤는데,
일본에서 건너온 놀이인지 우리나라의 놀이인지는 확실하진 않지만
확실히 영어권의 놀이는 아니기 때문에 말씀해주신 대로 작성하셔도 없을 것 같아요 ☺️
마치 태권도를 영어로 `Taekwondo` 라고 표기하는 것 처럼요!

참고로 묵찌빠의 영어표기명은 `muk-chi-ba` 라고 하네요! 👍
[묵찌빠 - 위키백과](https://ko.wikipedia.org/wiki/묵찌빠)
[묵찌빠 - ichacha.net](https://ko.ichacha.net/english/묵찌빠.html)

### 네이밍 길이에 대한 고민
네이밍 길이에 대해서 고민이라고 하셨었는데요!
저도 같은 고민을 했었기에 충분히 하실 수 있는 고민이라고 생각해요. ☺️

개인적으로는 메서드명이 짧으면서 한 눈에 의미를 알아보기 어려운 이름보다는,
다소 길더라도 한 눈에 의미를 파악할 수 있는 메서드명이 훨씬 더 좋다고 생각해요.
앞으로도 여러 프로젝트를 진행하다 보시면 Apple에서 직접 만들어 놓은 메서드들 중에서도 이름이 길다고 느껴지는 메서드들을 많이 마주하실 수 있을 거에요.☺️
그렇다는건 애플도 다소 긴 이름을 쓰더라도 그 메서드가 어떤 역할을 하는지 한 눈에 파악할 수 있는 이름이 더 중요하다고 생각해서이겠죠?

의미를 파악하는데 필요한 단어를 생략하면서까지 짧은 메서드명에 집착할 필요는 없다고 생각해요 👍👍

기타 네이밍에 관해서는 `API Design Guidelines`를 참고해주시면 좋을 것 같아요!
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)

2022-08-25 08:13 UTC, finnn1 requested changes

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/Function.swift
> +}
`startRockPaperScissors()` 함수와 `startMukjjippa(with:)` 함수 내부에서 사용하고 있는 메서드들이 모두 `RockPaperScissors` 또는 `Mukjjippa` 클래스 내부에 들어있는 것처럼 보여요!
그렇다면 굳이 전역 함수로 선언해줄 필요가 있을까요? 🤔

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/Function.swift
> +func startMukjjippa(with: String) {
`startMukjjippa(with:)` 메서드의 파라미터인 `with`가 사용되지 않고 있는 것 같아요!
또한, `parameter name`의 네이밍이 마치 `argument label`인 것 같은 착각을 일으킬 수 있는 네이밍 인 것 같아요...!

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/Function.swift
> +    let computerNumber = rockPaperScissors.generateRandomComputerNumber()
아직 게임이 시작하지 않았는데 `computerNumber`을 만들어놓는 것은 비효율적이라는 느낌이 들어요.
실제로 `computerNumber`는 `switchMenu(userNumber:computerNumber:)`에서 게임이 시작한 경우에만 사용되고 있는 것으로 보이는데요 🤔
그렇다면 사용자가 `0`을 선택할 경우 `computerNumber`는 생성되었다가 그냥 파기되는 불필요한 작업이 실행되지 않을까요?

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/Function.swift
> +func translateNumbersToHandSigns(of input: Int) -> HandSigns? {
`translateNumbersToHandSigns(of:)` 함수는 `Game` 클래스를 상속받은 클래스에서만 사용되고 있네요!
그렇다면 해당 함수를 전역함수로 선언할 필요가 있을까요? 🤔

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +var offensivePlayer: String = ""
`offensivePlayer` 프로퍼티를 전역변수로 선언해주셨군요!
그런데 `offensivePlayer` 프로퍼티가 사용되고 있는 곳이 `Game` 클래스 내부 또는 `Game` 클래스를 상속받은 하위클래스 내부로 한정되어있는 느낌을 받았어요 🤔
`static` 키워드를 찾아보시면 좋을 것 같아요 👍

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +class Game {
벌써부터 상속을 활용해서 코드의 재활용성을 높일 수 있는 방법을 연구해보셨군요!! 👏👏👏

다만, `judgeWinner(with:and:)` 및 `getUserInput()` 메서드의 경우는 내부 구현이 아예 비어있네요.
어차피 메서드의 구현부가 비어있는 경우라면 `Protocol` 을 고려해보시는 건 어떻게 생각하실까요? 🤔
`generateRandomComputerNumber()` 메서드처럼 구현부가 있는 경우는 `Protocol Extension` 키워드로 찾아보시면 좋을 것 같아요 ☺️

---

또는, 지금처럼 `Class`의 상속을 활용하고 싶으시다면 하위 클래스(`RockPaperScissors` 및 `Mukjjippa`)에서 중복으로 작성되고 있는 코드들을 처리해주시는 것이 좋을 것 같아요!
(`judgeWinner(with:and:)`, `getUserInput()`, `switchMenu(userNumber:computerNumber:)` 메서드)

하위 클래스끼리 중복으로 작성되고 있는 코드들을 어떻게 하면 처리할 수 있을까요?🤔

`super` 키워드에 대해서 찾아보시면 좋을 것 같아요. ☺️

---

결론적으로, 지금처럼 `Class`의 상속을 사용하고 싶으시다면 `super` 키워드를,
`Protocol`을 사용하고 싶으시면 `Protocol` 및 `Protocol Extension` 키워드로 찾아보시면 될 것 같아요. ☺️

혹시라도 이해가 안가시거나 궁금한 점이 있으시면 언제든지 편하게 질문해주세요! 👍

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +    func switchMenu(userNumber: Int, computerNumber: Int) {
STEP1에서 말씀드렸듯이 메서드명은 하나의 문장처럼 자연스럽게 읽히는 것이 좋아요 ☺️
메서드명 변경 또는 `argument label` 사용을 고려해볼까요?

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +    }
`Mukjjippa` 클래스의 경우는 `switchMenu(userNumber:computerNumber:)` 메서드를 `override` 해서 사용하고 있네요 ☺️
그렇다면 15번째 라인의 `switchMenu(userNumber:computerNumber:)` 메서드는 어디서만 사용되고 있을까요? 꼭 `Game` 클래스 내부에서 구현이 될 필요가 있을까요?

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +        guard let input = readLine(), input.count == 1, let userNumber = Int(input) else { return 4 }
입력이 잘못될 경우 `4`를 반환하고 있는 것으로 보이는데요,
반환된 `4`가 `switchMenu(userNumber:computerNumber:)` 내부에서 `default:`로 빠지는 역할 외에는 별다른 역할은 하지 않고 있는 것으로 보여요. 🤔

`4`와 같은 특정한 숫자를 반드시를 사용해야하는 것이 아니라면, 잘못된 숫자 혹은 존재하지 않는 숫자의 의미로 `Optional`을 고려해보는 것은 어떻게 생각하시나요? ☺️

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +class mukjjippa: Game {
타입명의 경우는 대문자로 시작하는 것이 일반적인 네이밍인 것으로 알고 있어요 ☺️

2022-08-25 08:13 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +        let signsToJudge = (userHandSign, computerHandSign)
`signsToJudge`이 `Mukjjippa` 클래스의 `judgeWinner(with:and:)` 메서드에만 있고, `RockPaperScissors` 클래스의 `judgeWinner(with:and:)` 메서드에는 없는데 혹시 어떤 차이가 있을까요? 🤔

2022-08-25 11:48 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/Function.swift
> +}
전역 함수에서 클래스 메소드로 전환하였습니다! 감사합니다 ! ☺️

2022-08-25 11:49 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/Function.swift
> +func startMukjjippa(with: String) {
필요하지 않은 파마메터인 `with`를 삭제하였습니다! 감사합니다. 🤓

2022-08-25 11:51 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/Function.swift
> +    let computerNumber = rockPaperScissors.generateRandomComputerNumber()
말씀하신대로 게임 정상 실행 시에만 `generateComputerNumber()`를 호출하도록 수정하였습니다! 👍

2022-08-25 13:19 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +class Game {
`judgeWinner(with:and:)`와 `getUserInput()`를 전역 함수에서 메소드로 수정하였습니다. 
RockPaperScissors클래스의 경우 Game 클래스에서 `switchMenu()` 함수를 상속받아 사용하는데
Mukchiba클래스의 경우 Switch문의 default case의 처리가 달라서 Game 클래스의 `switchMenu()` 함수를 동일하게 상속받을 수 없었기에 overriding을 해주었습니다. 두 클래스에서 default case만 다른데 어떻게 super 키워드를 사용해야 할지 고민입니다. 🥹

2022-08-25 13:21 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +var offensivePlayer: String = ""
전역 변수였던 `offensivePlayer`를 Game 클래스 내부의 타입 프로퍼티로 수정하였습니다. 감사합니다 ~

2022-08-25 13:22 UTC, yjjem commented on RockPaperScissors/RockPaperScissors/Function.swift
> +func translateNumbersToHandSigns(of input: Int) -> HandSigns? {
전역 함수였던 `translateNumbersToHandSigns(of:)`를 Game 클래스 내부의 타입 메소드로 수정하였습니다. 🤓

2022-08-26 05:38 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +class Game {
코드의 중복을 없애고 재사용성을 높이시기 위해서 클래스의 상속을 사용하고 계신 것 같아요.
그렇다면 상위 클래스에 있는 메서드 내부에서 아무런 정의가 되어있지 않다면
하위 클래스에서 같은 코드를 반복해서 작성해야 하기 때문에 상속을 사용하는 이유가 없다고 볼 수 있을 것 같아요.

중복이 되고 있는 코드들을 상위 메서드 내부에 넣어보시는 것은 어떻게 생각하실까요? 🤔
아래와 같은 느낌으로요 ☺️
코드에 정답은 없기 때문에 단순 참고만 해주시고, 더 좋은 방법이 떠오르신다면 그대로 진행해주시면 될 것 같아요. 👍👍

---
```swift
class Game {
    func getUserInput() -> Int {
        guard let input = readLine(), input.count == 1, let userNumber = Int(input) else { return 4 }
        return userNumber
    }
}

class RockPaperScissors: Game {
    override func getUserInput() -> Int {
        print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
        return super.getUserInput()
    }
}

class Mukjjippa: Game {
    override func getUserInput() -> Int {
        print("[\(Game.offensivePlayer) 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : ", terminator: "")
        return super.getUserInput()
    }
}
```
---
```swift
class Game {
    func executeDefaultBehavior() {
        print("잘못된 입력입니다. 다시 시도해주세요.")
    }
    
    func switchMenu(userNumber: Int) {
        switch userNumber {
        case 1, 2, 3:
            let computerNumber = generateRandomComputerNumber()
            judgeWinner(with: userNumber, and: computerNumber)
        case 0:
            print("게임 종료")
        default:
            executeDefaultBehavior()
        }
    }
}

class RockPaperScissors: Game {
    override func executeDefaultBehavior() {
        super.executeDefaultBehavior()
        
        startGame()
    }
}

class Mukjjippa: Game {
    override func executeDefaultBehavior() {
        super.executeDefaultBehavior()
        
        if Game.offensivePlayer == "사용자" {
            Game.offensivePlayer = "컴퓨터"
            startGame()
        } else {
            startGame()
        }
    }
}
```
---

2022-08-26 07:57 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +class Game {
default문을 별도의 함수로 생성하여 처리하는 아이디어도 생각해보았는데, 정확히 어떻게 반영을 해야할지는 잘 떠오르지 않았던 것 같습니다. 🥲 알려주신 방법으로 처리하는 것으로 해결하였습니다! 감사합니다!

2022-08-26 08:07 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +    func switchMenu(userNumber: Int, computerNumber: Int) {
`switchMenu(userNumber:, computerNumber:)` 함수를 `switchMenu(with userNumber:, before judgingWinner:)` `argument label` 을 사용해 승자를 판단하기 전에 `userNumber`를 사용해 메뉴를 전환한다는 의미릐 네이밍으로 수정했습니다.

2022-08-26 08:12 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +    }
해당 내용은 불필요한 overriding을 삭제하면서 Game의 자식클래스들이 공통으로 사용할 수 있게 hidden comment 주신대로 수정하였습니다. 😅

2022-08-26 08:39 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +        guard let input = readLine(), input.count == 1, let userNumber = Int(input) else { return 4 }
```swift
func getUserInput() -> Int? {
        guard let input = readLine(), input.count == 1, let userNumber = Int(input) else {
            return nil
        }
        return userNumber
    }
```
말씀하신대로 4가 코드 내에서 의미없는 숫자로 생각되어 getUserInput() 함수의 반환타입을 Int? 로변경하고, return 4에서 nil로 수정하였습니다.
대신 `func startRockPaperScissors()` 와 `func startMukchiba()`함수에서 별도로 Int? 타입을 Int 타입으로 변환해 `switchMenu()` 함수의 인자로 넣어주도록 하였습니다.

2022-08-26 08:41 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +class mukjjippa: Game {
`mukjjippa` 클래스를 `Mukchiba` 로 수정하였습니다!

2022-08-26 08:54 UTC, ash-youu commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +        let signsToJudge = (userHandSign, computerHandSign)
switch 조건문에 별도의 `signsToJudge` 상수를 넣어주는 것 보다는 `(userHandSign, computerHandSign)`가 더 가독성이 좋다고 판단하여 통일하는 것으로 수정하였습니다. 😄

2022-08-26 14:06 UTC, finnn1 requested changes

2022-08-26 14:06 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +            Game.offensivePlayer = "컴퓨터"
"사용자"와 "컴퓨터" 라는 String 리터럴 문자가 여러 곳에서 반복적으로 사용되고 있는 것을 볼 수 있는데요!
`NameSpace` 키워드로 찾아보시는 건 어떨까요? ☺️

2022-08-26 14:06 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
>          let (userHandSign, computerHandSign) = super.intToHandSigns(with: userNumber, and: computerNumber)
이 곳에서 `super` 키워드를 명시적으로 사용할 필요가 있을까요? 🤔
`클래스의 상속` 및 `super` 키워드에 대해서 조금 더 알아볼 수 있을까요? ☺️

2022-08-26 14:28 UTC, finnn1 requested changes

2022-08-26 14:28 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +        case (.scissors, .scissors), (.paper, .paper), (.rock, .rock) :
69번째 라인에서는 `case (.scissors, .paper), (.paper, .rock), (.rock, .scissors) :` 형태로 이겼을 경우를 먼저 판단해주고 있는데 이 곳에서는 비겼을 경우를 먼저 판단하는 이유가 있을까요?
두 곳의 `case` 형태만 맞춰주신다면 `judgeWinner(with:and:)` 메서드를 `Game` 내부에 선언해서 중복되는 코드를 조금 더 줄여볼 수도 있을 것 같아요 ☺️

2022-08-26 14:28 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +    func switchMenu(with userNumber: Int, before judgingWinner: (Int, Int) -> Void) {
함수를 파라미터로 받아서 처리하셨군요! 👍👍👍
그런데 만약 `Game` 클래스 내부에 `judgeWinner(with:and:)` 메서드가 있다면 함수를 파라미터로 받지 않고 바로 호출할 수도 있지 않을까요? 🤔
하위 클래스(`RockPaperScissors`, `Mukchiba`)에서 둘 다 `judgeWinner(with:and:)` 메서드를 비슷한 모양으로 정의하고 있네요! ☺️

2022-08-26 14:28 UTC, finnn1 commented on RockPaperScissors/RockPaperScissors/GameClass.swift
> +            executeDefaultBehavior()
`RockPaperScissors`, `Mukchiba` 클래스에 `executeDefaultBehavior()` 메서드를 재정의해서 각각에 맞는 동작을 할 수 있도록 하셨군요 👏👏👏
그렇다면 `executeDefaultBehavior()` 메서드는 `Game`을 상속받는 하위 클래스에서 무조건 정의해주어야만 하는 요구사항 이라고 볼 수도 있겠네요 ☺️
(하위 클래스에서 `executeDefaultBehavior()` 메서드를 정의하지 않으면 프로그램이 정상적으로 동작하지 않으니까요!)

`Game`을 채택하고 있는 타입들(`RockPaperScissors`, `Mukchiba`)이 어떻게 하면 `executeDefaultBehavior()` 메서드가 반드시 정의해야만 하는 메서드인 것을 알 수 있을까요?
시간이 되신다면 `Protocol`에 대해서 공부해보시면 좋을 것 같아요! ☺️

2022-08-27 04:06 UTC, merged