- 가위 바위 보 게임 [Step 2] Kyo, Aaron
yagom-academy/ios-rock-paper-scissors pull request #173
Opened 2022-08-25 02:40 UTC by Hashswim

@yusw10
step 1 피드백 잘 봤습니다..!
Step 2 구현해서 PR 보냅니다.

진행 단계 : Step2

⭐️ 코드를 작성할 때 고민되었던 점
 - 사용자에게 Input을 받아오는 과정에서 기능 별로 함수를 많이 나누었습니다. 
이에 따라서 재귀함수를 사용하기가 쉽지않았습니다. 또한 playRPS함수의 while문 내부에서 입력값을 받아오는 형식으로 설계를 진행해나가 더욱 재귀를 사용하기가 어려웠습니다.
재귀를 사용을 하려면 처음부터설계를 재귀함수에 초점을 맞춰서 진행을 해나가야하는지..고민이 많이 되었습니다

⭐️ 해결이 되지 않은 점
 - 입력 받는 부분을 재귀함수로 구현하려고 했지만 설계 과정에서 잘못 설계한 부분이 있어 재귀함수를 사용하지 못했습니다.
 - playRPS 함수와 playMZB 함수 내에서 새로운 함수를 호출하는 방식으로 if 문을 줄여보려 했지만 그렇게 되면 또 조건문을 사용하게
되는 문제가 있어 구현하지 못했습니다. 
```swift
            if handlingInputError(input: userInput) == false {
                continue
            } else {
                userHands = MukZiBa(rawValue: castingUserInput(input: userInput))
            }
            
            if userHands == MukZiBa.none {
                print("게임 종료")
                return
            }
            
            if decideDraw(userHands?.rawValue, computerHands?.rawValue) {
                print("\(currentTurn.rawValue)의 승리!")
                break
            }
            
            if decideWinLose(gameName, userHands?.rawValue, computerHands?.rawValue) {
                currentTurn = .userTurn
            } else {
                currentTurn = .computerTurn
            }
```

⭐️ 조언을 얻고 싶은 부분
 - '가독성이 좋고 깔끔한 코드'와 '메모리, 시간 측면에서 효율적인 코드' 를 모두 만족시킬 수도 있겠지만 코드를 작성하다보면
충돌하는 부분도 생기는것 같습니다, 앞으로 코드를 짜는데 있어 어떤것을 생각하면서 짜야할지 조언을 얻고 싶습니다..!
 - 묵찌빠 함수의 이름을 MZB로 설정하는 등 네이밍에 대한 고민이 많았는데 전체적인 네이밍에 대한 조언을 얻고 싶습니다!

2022-08-26 02:12 UTC, yusw10 requested changes
⭐️ 코드를 작성할 때 고민되었던 점

> 사용자에게 Input을 받아오는 과정에서 기능 별로 함수를 많이 나누었습니다.
이에 따라서 재귀함수를 사용하기가 쉽지않았습니다. 또한 playRPS함수의 while문 내부에서 입력값을 받아오는 형식으로 설계를 진행해나가 더욱 재귀를 사용하기가 어려웠습니다.
재귀를 사용을 하려면 처음부터설계를 재귀함수에 초점을 맞춰서 진행을 해나가야하는지..고민이 많이 되었습니다

재귀는 사용하기 까다롭죠... 저도 비즈니스 로직을 작성할 때 재귀를 피하려고 노력하는 편입니다. 잘못 설계하면 메모리누수가 사방팔방 일어나거든요.
이부분은 저도 명쾌하게 정답을 아는건 아니지만 제 개인적으로는 "**재귀로 짠다면 재귀를 가정하에 코드 설계를 해야하지 않을까?**" 라고 생각합니다.

피보나치를 생각해보면 `F[n] = F[n-1] + F[n-2]` 라는 로직이 있죠? 다만 이 로직을 코드로 작성할 때는 여러 방법이 있을겁니다. 재귀로 짤수도있고 반복문을 활용할수도 있겠죠. 한가지 방법으로 구현하려고 코드 흐름에대한 설계를 다 해놨는데 중간에 이 흐름을 바꾸는 설계로 바꾸면 당연히 어렵지 않을까요? 재귀에서는 함수의 종료조건과 분기에 대한 조건설정이 중요할 것이고 반복문에서는 루프 조건등이 중요할텐데 고려하지 않은 점을 적용시켜야하니까요.

코드를 작성하면서 이런 구조적 고려사항을 생각하며 짠것과 안짠것은 크다고 생각해서 만약 재귀로 진행하실 예정이었다면 재귀에 맞춰서 짰어야 하지 않나 싶습니다(어디까지나 제 개인적 의견입니다..!)

⭐️ 조언을 얻고 싶은 부분

> '가독성이 좋고 깔끔한 코드'와 '메모리, 시간 측면에서 효율적인 코드' 를 모두 만족시킬 수도 있겠지만 코드를 작성하다보면
충돌하는 부분도 생기는것 같습니다, 앞으로 코드를 짜는데 있어 어떤것을 생각하면서 짜야할지 조언을 얻고 싶습니다..!

이건 경우에 따라 상황 따라 다를것 같아요. 코드 작성에 우선순위를 두시면 될것같습니다. 저는 **가독성이 좋은 코드**는 상황 불문 지켜야하고요. 메모리적으로, 시간복잡도상 우수한 코드여도 개발자가 신경쓰면 가독성은 올라갑니다.

> 묵찌빠 함수의 이름을 MZB로 설정하는 등 네이밍에 대한 고민이 많았는데 전체적인 네이밍에 대한 조언을 얻고 싶습니다!

네이밍은 회사마다, 부서마다도 다르고 개인차이도 있습니다. 개인적으로는 **이 코드를 진짜 완전 처음 보는 사람도 코드만 읽고 뭘하는지 알수있도록** 짜려고 노력하는편입니다.
MZB라는 네이밍은 어떨까요? 묵찌빠가 외국에는 없는 개념이니 읽는사람이 한국인이라고 가정했을 때 MZB를 읽었는데 묵찌빠를 떠올릴 수 있을까요? 코딩을 안하는 사람에게 변수명을 보여줬을때 어느정도 비슷한 의미로라도 읽힐정도는 되는게 좋은 네이밍이라고 생각합니다.

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
여기서 Foundation이 하는 역할이뭘까요?

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +final class PlayGame: HandlingInput {
final 키워드를 사용해주셨네요. final 키워드를 사용하면 안쓰는것과의 차이점과 장단점은 무엇일까요?

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/Model/RockScissorsPaper.swift
> +    case none = 0
none을 넣어주셨네요. 
이 부분은 생각을 해봐야합니다. 가위바위보인데 none은 어떤경우일까요? 안내는 경우일까요?

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/Model/Turn.swift
> +    case undecidedTurn = "정해지지 않은 턴"
rawValue를 넣어주셨는데 사용은안되고 있네요

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +
개행 기준이 이부분만 다른것같은데 이유가있을까요?

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/HandlingInput.swift
> +class HandlingInput {
사용자 입력과 검증 코드를 class로 묶어주고 이를 상속받는 형태로 구현하셨네요.
이렇게 작성하신 이유가 있을까요?
상속말고 playGame 클래스의 extension으로 코드분리하는것과 어떻게 다를까요?
struct에 protocol을 사용하여 구현하는것과 뭐가 다를까요?
이부분은 수정은 안하셔도되고 두분이서 어떻게 다를까 이야기해보시면 좋을것같습니다.

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/Model/MukZiBa.swift
> +enum MukZiBa: Int, CaseIterable {
caseIterable은 어떤역할을 할까요?

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/HandlingInput.swift
> +        }
checkUserInput메서드의 조건절과 비슷해보이는데 이곳은 switch를 사용하셨네요.
어떤 차이일까요?

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/HandlingInput.swift
> +    func castingUserInput(input: String?) -> Int {
메서드 명은 형변환을 의미하는 캐스팅인데 0부터 3 사이의 값인지 검증도 진행하고있네요. 
기능분리가 가능해보입니다.

2022-08-26 02:12 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +    func decideWinLose(_ gameName: String, _ userHands: Int?, _ computerHands: Int?) -> Bool {
승리와 패배를 결정한다는 네이밍인데 Bool 타입을 반환하네요.
이기는게 true일까요?
코드상에서는 결정이 나는지를 리턴하는게 아니라 이기는게 true인것같은데 맞을까요?

2022-08-26 02:48 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +final class PlayGame: HandlingInput {
final 키워드를 사용하게 되면 단점?으로는 상속이 불가해지고, 메서드 앞에 붙으면 override가 되지않습니다. 
장점으로는 final을 붙이게 된다면  클래스가 컴파일 내에서 StaticDispatch로 동작하게되어 성능이 좋아지는 것으로 알고있습니다.

2022-08-26 05:08 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/Model/Turn.swift
> +    case undecidedTurn = "정해지지 않은 턴"
PlayGame클래스의 playMZB() 메서드에서 누구의 턴인지를 보여줄 때 사용하고 있습니다!

2022-08-26 05:12 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +    func decideWinLose(_ gameName: String, _ userHands: Int?, _ computerHands: Int?) -> Bool {
네 맞습니다! 
생각해보니깐 승패를 결정한다기보다는 승리일때 True를 반환하니깐 decideWin 네이밍이 더 적합한 것 같습니다!

2022-08-26 07:10 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/HandlingInput.swift
> +        }
해당부분은  코멘트보고 의논 결과 `checkUserInput()` 과 기능적으로 겹쳐서 삭제 수정 하였습니다!

2022-08-26 07:11 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/HandlingInput.swift
> +    func castingUserInput(input: String?) -> Int {
바로 위에 코멘트 남긴대로 해당 부분 수정하였습니다.!

2022-08-26 07:26 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
Foundation Framework는 기본적인 데이터타입 부터 자료구조, 구조체, 타이머, 네트워크 통신 등 기본적인 프로그램 기능을 담당합니다!
하지만 Foundation을 import하지 않아도 동작하는 이유는 Foundation Framework에는 NSString,NSArray등 Objective-C자료 형들이 Foundation Framework에 속하기 때문인 것 같습니다. (제가 이해하고 있는 내용이 맞을까요?)
그래서 결과적으로 삭제가 되어도 괜찮을 것 같습니다!

2022-08-26 07:30 UTC, Hashswim commented on RockPaperScissors/RockPaperScissors/Model/RockScissorsPaper.swift
> +    case none = 0
유저로부터 입력을 받을 때 가위바위보와(1, 2, 3) 게임종료(0)를 같은 단계에서 입력 받기 때문에 
가위바위보의 개념의 연장선이라고 생각했습니다.
네이밍에 있어 의미를 명확히 하기위해 변수명을 exit으로 수정했습니다..!

2022-08-26 07:31 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +
다시 확인해보았는데 어느 부분인지 잘모르겠..습니다

2022-08-26 07:36 UTC, KyoPak commented on RockPaperScissors/RockPaperScissors/Model/MukZiBa.swift
> +enum MukZiBa: Int, CaseIterable {
CaseIterable은 열거형 내부 Item들을 컬렉션형처럼 순회할 수 있도록 해주는 프로토콜입니다.
for문에서 사용할수 있으며 이때 접근은 .allCases라는 속성 값으로 접근을 합니다!

처음에 코드 설계시 caseIterable프로토콜을 사용을 하려했는데 약간 로직 변경이 있어서 사용을 하지 않았습니다.
해당 프로토콜 채택은 삭제 수정 하였습니다.

2022-08-26 07:52 UTC, Hashswim commented on RockPaperScissors/RockPaperScissors/HandlingInput.swift
> +class HandlingInput {
1. 사용자의 입력을 받는 부분을 모듈화시켜 HandlingInput 클래스로 구현을해 playGame 클래스 뿐만 아니라 다른 기능을 하는 class를 만들게 될 때 또다시 상속만 하면 되어 코드 재사용성을 높일 수 있다고 생각했습니다.

2. 클래스의 확장으로 구현을 하게 된다면 위에 처럼 다른 클래스가 HandlingInput의 기능을 필요로 할 때 또 한번 확장을 하게 되는 번거로움이 생길거 같습니다.

3. 프로토콜을 확장하고 그 프로토콜을 채택하는 방향성으로 진행을 해나간다면 프로토콜에 있는 함수들을 자유롭게 재정의 할수 있고, 프로토콜 확장에서 정의한 그대로 사용을 할수 도있다는 이점이 있는것같습니다!

2022-08-28 08:42 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/PlayGame.swift
> +
지난 커밋 기준으로 봤을 때 winNumbers 변서 선언 위로 개행이 한번 있어서 코멘트 달았었는데 다시 맞춰져있네요!

2022-08-28 08:44 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/Model/Turn.swift
> +    case undecidedTurn = "정해지지 않은 턴"
아 이부분은 제가 확인 못했던것 같습니다!

2022-08-28 08:46 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/Model/RockScissorsPaper.swift
> +    case none = 0
exit으로 사용하는것도 좋네요!
다만 게임종료를 포함한 개념의 연장선이라면 "가위바위보 게임"이라는 의미가 포함된 네이밍도 좋아 보입니다. 
아예 게임의 개념과 가위바위보의 개념으로 분리시켜도 좋을것같구요.

2022-08-28 08:55 UTC, yusw10 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
프레임워크와 라이브러리의 차이점에 대해서 배우셨을까요?(추후에 배우게 됩니다)
swift에 내장된 기본형을 제외하고 기능을 확장해서 사용할 때 Foundation과 같은 프레임워크(또는 라이브러리)를 import하게 됩니다. 
main.swift 를 보면
```swift
let game = PlayGame()
game.playMZB()
```
두줄만 존재하는데 PlayGame타입은 여러분이 만들어주신 타입이니 결과적으로 보면 Foundation에서 제공하는 기능을 사용하고 있지 않네요. 기본 데이터타입, 자료구조, 구조체 등등 조사해주신 내용들에 대해 사용을 하고 있지 않기 때문에 삭제해도 괜찮은 코드가 되는것이죠. 
objective-C자료형을 사용하고 있지 않기 때문에 삭제해도 된다고 말씀주신것도 맞는 말입니다. 다만 그외의 기능도 사용하고있지 않기 떄문도 맞는 말이죠.
잘 찾아 주셨습니다!

2022-08-28 08:57 UTC, merged