묵찌빠 게임 [STEP 1] kaki, sehong
yagom-academy/ios-rock-paper-scissors pull request #178
Opened 2022-12-26 07:00 UTC by kak1x

@oneStar92 
안녕하세요 아얀! 첫 리뷰 잘 부탁드리겠습니다~!

### 고민했던 점
- printMenu 함수와 receiveUserInput 함수를 나눠줘야 하는지 고민했습니다.
- 승패의 출력을 그냥 print를 사용하여 출력할지, enum 타입을 선언하여 출력할지에 대해서 고민했습니다.

### 새로 알게된 점
- enum 타입의 사용법
- error 처리 방법 

### 조언이 필요한 점
- 함수를 나누는 기준을 정하기 어렵습니다. 세세한 기능 하나마다 함수를 선언해주어야 할지, 어느정도 연관이 있는 함수는 묶어주어도 될지 알고 싶습니다!

2022-12-26 14:09 UTC, oneStar92 requested changes
@kak1x @sehoong0429
안녕하세요 kaki, sehong😁
빠르게 Step1을 구현해 주셨네요👍
프로젝트 기간동안 잘 부탁드립니다!!🙇🏻‍♂️
궁금한 부분 있으시거나 코멘트 중 이해가 안되는 부분 있으시면 DM 주세욥!!

---

## 칭찬드리고 싶은 부분

- 요구사항에 맞게 구현해 주신 점 💯
- Type을 정의해 주신 점 💯
- 함수를 기능별로 잘 구현해주신 점 💯
- 옵셔널 바인딩을 잘 해주신 점 💯

---

## 조언을 얻고 싶은 부분에 대한 저의 의견

- 함수를 나누는 기준을 정하기 어렵습니다. 세세한 기능 하나마다 함수를 선언해주어야 할지, 어느정도 연관이 있는 함수는 묶어주어도 될지 알고 싶습니다!
    - 지금 역활 분리는 아주아주 잘해주셨습니다! Very Good!!👍 
    - kaki, sehong이 생각하시는 세세한 기능과 연관되어 있다는게 어떤 의미인지 무엇인지 정확하게 알 수 없어서 답변을 드리기가 어렵네요. 
    - 저의 경우에는 최대한 메서드, 함수가 한가지의 기능을 하도록 구현합니다.

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
Foundation을 import해주시는 이유가 있을까요??

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
Error Type을 정의해 주셨네요👍
채택해 주신 Error에 대해서 설명해주실 수 있을까요??😁

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- 네이밍에서 약어의 사용을 지양합니다. [Naming](https://www.swift.org/documentation/api-design-guidelines/#naming)을 살펴보시는게 좋을 것 같아요🙂
- RPS Type에 exit case는 해당 enum에 어울리지 않는 것 같아요... 이렇게 사용하신 이유가 있을까요??🤔
- 가위, 바위, 보의 rawValue가 Int인게 이상하게 느껴집니다... rawValue는 무엇을 뜻할까요??

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- `draw`, `win`, `lose` case의 rawValue가 String인게 이상하게 느껴집니다... 각 case가 message를 가질 수 있는 방법이 없을까요??

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func randomComputerHand() -> RPS {
randomComputerHand는 네이밍이 이상하게 느껴집니다... [Naming](https://www.swift.org/documentation/api-design-guidelines/#naming)을 참고해보시는게 좋을 것 같아요!!🙂

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
LGTM 👍
```suggestion
func receiveUserInput() throws -> Int {
    guard let input = readLine(), let inputNumber = Int(input) else {
        throw InputError.invalidNumber
    }
    
    return inputNumber
}
```
이렇게 작성할 수도 있을 것 같아요😁

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
여러분이 사용해주신 print문 안의 문자열을 매직 넘버/리터럴이라고 합니다.
- 매직 넘버/리터럴의 사용을 지양하는게 좋은데 왜 그럴까요??🙂
- 이번 프로젝트 부터 매직 넘버/리터럴을 사용하지 않아 보는건 어떨까요??🤔

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
Argument Label을 사용해보시는 건 어떨까요?? 명확하게 함수의 기능을 파악할 수 있을 것 같아요🙂
[Functions](https://docs.swift.org/swift-book/LanguageGuide/Functions.html#) Function Argument Labels and Parameter Names 참고하시면 좋을 것 같습니당😁

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgeGameResult(myChoice: RPS, computerChoice: RPS) {
- 이 부분도 Argument Label을 사용해보시면 좋을 것 같아요.
- myChoice와 computerChoice는 어색하게 느껴지는데 명확한 네이밍은 없을까요??

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- 중복된 코드인 `printGameResult(gameResult: )`를 줄일 수 있는 방법은 없을까요??

### 수정하지 않으셔도 됩니다
 저는 해당 부분에 `if`, `else if`, `else`를 사용하는게 어색하게 느껴지네요. 3가지 case인 `win`, `lose`, `draw`의 경우에 따라서 동작을 수행하게 되는데 `if`보다는 `switch`가 더 어울리고 명확한 결과를 전달할 수 있을 것 같아요.
 [Control Flow](https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html#)의 switch파트의 Compound Cases부분을 참고해보시면 좋을 것 같습니당😁

2022-12-26 14:09 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        play()
재귀 함수를 주로 사용해 주셨는데 재귀 함수를 사용하신 이유가 있으신가용??🤔
혹시 재귀 함수와 반복문의 차이점에 대해 설명해 주실 수 있을까요??😁

2022-12-26 14:36 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
지금 코드에서는 Foundation의 프레임워크를 사용할 일이 없어서 제거해줘도 될 것 같습니다!

2022-12-26 14:37 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
입력받은 것이 0, 1, 2, 3이 아닐 경우 유효하지 않은 입력값으로써 에러를 처리하기 위해 정의하였습니다.

2022-12-26 14:40 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- 네이밍은 다시 한 번 고민해보겠습니다!
- 입력받을 숫자가 0, 1, 2, 3인데, 이를 한가지의 switch - case문 내에서 처리해주고 싶어서 같이 정의하게 되었습니다.
- 단순하게 입력받은 숫자를 가지고 RPS(rawValue: 0...3)로 처리해주고 싶어서 Int로 원시값을 정의해주었는데, 정작 rawValue가 무엇인지 정확하게 설명하기 어렵네요. 이 부분은 다시 찾아보며 고민해보고, 잘 모르겠으면 DM 드리도록 하겠습니다.

2022-12-26 14:42 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
rawValue 없이 각 case 별로 switch-case문을 이용하면 각 case마다 message를 출력할 수 있을 것 같긴 한데, 조언 주신 부분이 이 방법과 일치하는건지 잘 모르겠네요 🥲

2022-12-26 14:42 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +func randomComputerHand() -> RPS {
전반적으로 네이밍에 관해 조금 더 고민해보도록 하겠습니다!

2022-12-26 14:42 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
훨씬 간략해진 것 같아요! 감사합니다~

2022-12-26 14:43 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
찾아보도록 하겠습니다.

2022-12-26 14:48 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +        play()
재귀를 사용한 이유는 반복문을 정의해주게 되면 들여쓰기 제한을 넘기게 될 것 같아서 사용하게 되었습니다.
차이점은.. 반복문은 주어진 명령을 반복적으로 수행하며 속도가 빠르고, 재귀의 경우 함수를 계속 호출해나가며 함수가 끝날때까지 반복되고 속도가 느리며 가독성이 좋아지는 장점이 있는 정도로 알고 있습니다!

2022-12-27 11:35 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            throw InputError.invalidNumber
```suggestion
        case .none:
            throw InputError.invalidNumber
```
문맥상 switch문을 이용하여 옵셔널을 바인딩 했을때에는 `default`보다 `case .none`이 더 자연스러운 것 같네요.
물론 지금도 괜찮습니다 참고만 해보시면 좋을 것 같아요!

2022-12-27 11:35 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
이부분은 에러를 왜 정의 했는지를 물어본게 아니라 Error Protocol이 무엇인지 알고 계신지 확인차 물어봤습니다.
[Error](https://developer.apple.com/documentation/swift/error)을 한번 읽어보시는 것도 좋을 것 같네요!👍

2022-12-27 11:35 UTC, oneStar92 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
enum을 이용하여 Type 프로퍼티로 네임 스페이스를 잘 사용해 주셨네요!👍
혹시 static 키워드가 무엇인지 왜 struct, class가 아닌 enum을 사용하셨는지 설명해주실 수 있을까요??🤔

2022-12-27 11:39 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +            throw InputError.invalidNumber
참고하도록 하겠습니다!

2022-12-28 05:09 UTC, sehoong0429 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
static 키워드에 대한 답변 : 
스위프트에서 static은 타입 프로퍼티 혹은 타입 함수라고 정의한다고 합니다!
게임메세지를 enum타입으로 선언해서 해당 프로젝트에 사용되는 게임 출력 메세지를 묶어서 사용하면 좋겠다는 생각을 했습니다. 
그래서 let으로 그냥 선언했더니 enum에서는 저장프로퍼티를 가질 수 없다고 해서 static 키워드를 사용하게됐는데 static 키워드는 사용하면 전역 변수처럼 공통으로 관리하는 공용 자원으로 사용할 수 있어서 사용하게 되었습니다. static let은 주로 값이 바뀔일이 없는 프로퍼티에 사용된다고 알고 있으며 해당 enum에 있는 객체를 인스턴스화 할 필요가 없기때문에 사용하기에 부합한것같습니다.

2022-12-28 05:09 UTC, kak1x commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- enum 사용 이유 : 인스턴스화가 필요 없다고 생각되어 struct를 사용하지 않았습니다. 또한 enum을 사용한 메시지 값 그룹에서 상수를 사용하는것이 코드의 가독성이 좋다고 생각하였습니다.

2022-12-28 07:33 UTC, merged