가위바위보/묵찌빠 프로젝트
yagom-academy/ios-rock-paper-scissors pull request #18
Opened 2020-11-06 07:08 UTC by innieminnie

가위바위보/묵찌빠 프로젝트입니다 :)

2020-11-06 07:20 UTC, yagom requested changes
구조화에 신경을 많이 쓴 것 같아요. 공을 많이 들였네요 :)
몇 가지 질문과 제안사항이 있습니다.

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +struct Card{
구조체를 사용한 것이 인상적입니다.
Card 뒤에 띄어쓰기를 하지 않은 것은 특별한 의도가 있는걸까요?

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +    func playGame(_ idx1: Int, _ idx2: Int) -> Bool{
다른 사람이 playGame 함수를 호출하려고 했을 때 주석을 찾아보지 않더라도 직관적으로 사용할 수 있는 방법에 대해 고민해봅시다.
매개변수 레이블에 와일드 카드를 꼭 사용할 필요가 있었을까요?
idx1과 idx2만 보고 이 매개변수가 어떤 일을 수행하는지 알 수 있을까요?
또, 함수 이름을 보면 게임을 실행한다는 이름인데  반환 값이 있습니다. 이 반환 값을 함수 이름만 보고 유추할 수 있을까요?
Swift API Guidelines를 다시 읽어보고 이름에 대해 고민해봅시다.

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +        if checkWinOrLose[idx1-1] == idx2{
함수를 호출할 때 idx1에 0을 전달하면 어떤 일이 벌어질까요?

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +     */
주석을 남기지 않더라도 함수의 결과를 알 수 있도록 직관적인 코드를 고민해봅시다

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func getPlayerInput() -> Int {
Swift와 Cocoa Touch의 API에서는 함수의 이름에 get을 붙이지 않습니다. (극히 예외는 있습니다) 
왜 그럴까요? Swift API Guidelines를 읽어보고 다시 한 번 고민해봅시다.

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +var currentTurn = Turn.사용자
전역 변수를 사용할 때 발생할 수 있는 부작용이나 위험요소는 없을까요?

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let inputNum = Int(readLine()!) ?? -1
사용자 입력을 받는 중 사용자가 아무 것도 입력하지 않고 실수로 엔터를 친다면?

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func playRoundOne() {
함수의 이름으로 유추해본다면 게임을 한 판만 진행하는 것 같은데, 코드를 보면 가위 바위 보가 끝날 때 까지 진행하는 것 같습니다.
또, 하나의 함수 안에서 너무 많은 일을 진행하고 있어요. 
함수를 적절히 여러 역할로 분리하는 것이 나중을 위해서라도 더 좋습니다.

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +//        print(playerCard.cardIdx, computerCard.cardIdx)
print로 디버깅을 하기 보다는 lldb 명령어를 통한 디버깅을 활용해보세요.
또, 이렇게 필요없는 코드를 주석으로 남겨두는 것은 좋지 못한 습관입니다.

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func playRoundTwo() {
위의 함수와 마찬가지 코멘트로 개선해보면 좋겠습니다.

2020-11-06 07:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +playRoundOne()
하나의 함수로 프로그램을 동작시키는 시도가 좋습니다.

2020-11-07 11:48 UTC, innieminnie commented
리뷰내용을 보고 Swift API Guideline Naming부분을 읽으면서  함수명,파라미터명 등을 프로그램 흐름에 맞게 보다 구체적이고 뚜렷하게 드러내려고자 했습니다.

2020-11-07 11:52 UTC, innieminnie commented
다만, 기존 입력값을 받던 getUserInput 함수에서 get을 함수명을 사용하는 부분은 computed프로퍼티로 개선될 여지가 있기에 함수명은 get/set을 사용을 지양한다는 것을 보았는데, readLine 입력값을 받아 computed프로퍼티로 연산하여 업데이트를 구현하는 데에 어려움이 있어 makeAvailableValue 함수로 입력값을 조건에 맞게 변형시키도록 구현해보았습니다!

2020-11-08 02:10 UTC, yagom approved these changes
코드가 훨씬 직관적으로 바뀌었네요 :) 
이런저런 고민의 흔적도 곳곳에 보입니다.
이번 코멘트와 리뷰는 여기서 마치고 제안사항은 다음번 프로젝트에 반영해도 좋아요.
코멘트 확인 후 스스로 머지하면 됩니다.
한 주간 고생 많았습니다 :)

2020-11-08 02:10 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
>      var cardIdx: Int
idx는 무슨 뜻인가요? 제가 잘 몰라서요 +_+ 축약어 같은 건가요?

2020-11-08 02:10 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +    func didWin(against computerIdx: Int, on executedGame: GameName) -> Bool {
이름에 고민을 많이 했군요! 매개변수 이름과 레이블이 인상적입니다 :)

2020-11-08 02:10 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +            fatalError("입력된 값이 정확하지 않습니다.")
fatalError도 좋지만, 잘못된 입력은 앱을 강제 종료 할 만큼 크리티컬한 일일까요? 사용자에게 다시 한 번 더 기회를 주는 방향은 어떨까요?

2020-11-08 02:10 UTC, yagom commented on RockPaperScissors/RockPaperScissors/Card.swift
> +        }
Swift의 swap 함수를 찾아보세요

2020-11-08 15:31 UTC, merged