묵찌빠게임 [STEP 01] Harry, Andrew
yagom-academy/ios-rock-paper-scissors pull request #184
Opened 2022-12-27 05:17 UTC by Andrew-0411

@jsa0224 
안녕하세요 Som! Step1 PR 잘 부탁드려요

## 고민했던 점
- guard문에서 return값을 줄 때 nil 사용하는 것이 적절한것 인지 고민했습니다.
- 사용자와 컴퓨터의 패를 비교하는 함수내에서 비교 구문이 너무 길어서 줄일 수 있는 방법이 있을지 고민했습니다.

``` swift
if computerHand.rawValue == 1 && userHand.rawValue == 3
        || computerHand.rawValue == 2 && userHand.rawValue == 1
        || computerHand.rawValue == 3 && userHand.rawValue == 2  {
        matchResult = MatchResult.lose
    } else if computerHand.rawValue == userHand.rawValue {
        matchResult = MatchResult.draw
    } else {
        matchResult = MatchResult.win
    }
```

## 조언을 받고 싶은 점
- 사용자에게 입력을 받을 때 Result타입을 받아서 에러처리를 했는데 게임종료도 success로 처리해서 입력값이 0일 경우에만 게임이 종료되도록 작성하였습니다. 이게 올바른 방법인지 다른 방법은 없을지 궁금합니다.
- 사용자의 패와 컴퓨터의 패를 생성하는 함수에서 RockPaperScissors 열거형 타입을 return해줍니다. 열거형의 init 생성자로 열거형 값을 만드는데 이 때 생성자로 들어가는 rawValue는 사용자로 받는 입력값으로 사용됩니다. 이렇게 되면 무조건 옵셔널 값을 반환해주는데 옵셔널 바인딩을 하기 위해서 guard let 구문을 사용하면 else 문에 무슨 값을 return할 지 몰라 nil을 return 했습니다. nil을 return 하는 방법 외에 다른 의견이 있으신지 궁금합니다.

2022-12-27 12:30 UTC, jsa0224 requested changes
안녕하세요, Harry, Andrew~! 코드 잘 읽어보았습니다. 
저도 리뷰어는 처음이라 많이 부족할 테지만 잘 부탁드립니다!
전체적으로 잘 구현해주셨지만, 몇 가지 수정하면 더 좋을 거 같네요☺️
남겨주신 고민 사항들에 대해서는 아래 글에서 답변 드리겠습니다!

## 👍 칭찬하고 싶은 부분
- `switch문`을 적절하게 활용했다는 점
- `HandShape` 열거형을 구현한 점
- 튜플을 활용한 점
- 파일 분리를 한 점
- 커밋메세지 굳굳👍

## 🧐 조언하고 싶은 부분
> ### 조언을 받고 싶은 점
> - 사용자에게 입력을 받을 때 Result타입을 받아서 에러처리를 했는데 게임종료도 success로 처리해서 입력값이 0일 경우에만 게임이 종료되도록 작성하였습니다. 이게 올바른 방법인지 다른 방법은 없을지 궁금합니다.

일단 드리고 싶은 말은 코드에 정답은 없습니다! 
Result타입은 코드의 간결성이 좋아서 저는 주로 사용하는 에러 타입 중 하나입니다. 
한 차례 리팩토링하시고 do-catch문으로 바뀐 거 같은데 맞을까요?
어느 코드로 구현하든 자신만의 이유가 있고, 그 이유가 상대방도 납득 가능하다면 그게 좋은 코드가 아닐까 싶습니다☺️

> - 사용자의 패와 컴퓨터의 패를 생성하는 함수에서 RockPaperScissors 열거형 타입을 return해줍니다. 열거형의 init 생성자로 열거형 값을 만드는데 이 때 생성자로 들어가는 rawValue는 사용자로 받는 입력값으로 사용됩니다. 이렇게 되면 무조건 옵셔널 값을 반환해주는데 옵셔널 바인딩을 하기 위해서 guard let 구문을 사용하면 else 문에 무슨 값을 return할 지 몰라 nil을 return 했습니다. nil을 return 하는 방법 외에 다른 의견이 있으신지 궁금합니다.

guard문 같은 경우, else 문은 return과 throw 중 하나로 구현하시면 됩니다. 해당 구문에 맞는 에러 타입이 있는 경우, throw로 옵셔널을 리턴할 경우는 return nil도 가능합니다. 어떤 것이 상황별로 적절한 지는 앞으로 프로젝트 진행하시면서 고민해보시면 좋을 거 같습니다👍

### 코드 컨벤션
- 코드 컨벤션을 맞추는 것은 아주 중요합니다! 프로젝트 코드 내에 컨벤션을 맞추지 못 한 부분들이 보여서 아래의 코멘트에 달아두었습니다. 참고하시면 좋을 거 같습니다😊

### 사용자 정의 타입 구현
- main 파일에 있는 함수들을 하나의 타입으로 구현해보는 것이 어떨까요? 
class와 struct 중 하나로 구현해보시고, 해당 타입을 선택한 이유도 알려주세요🧐

### main 브렌치에 프로젝트를 구현한 이유❓
main 브렌치에서 프로젝트를 구현한 이유가 따로 있으실까요?
브렌치를 나누는 이유는 무엇일까요? 한 번 찾아보시는 것도 추천드립니다☺️

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/HandShape.swift
> +}
`HandShape` 열거형 맨 윗 줄에 공백이 있네요🧐
그리고 `CaseIterable`을 채택한 이유가 무엇일까요?

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/InputError.swift
> +}
여기도 공백!

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- guard문을 하나로 통합할 수 있지 않을까요?
- `validationUserInput` 직역하자면 유저입력확인 이라는 뜻인데, 함수 네이밍은 동사로 시작하는 것으로 추천드립니다.
자세한 사항들은 [Naming](https://www.swift.org/documentation/api-design-guidelines/#naming) 문서를 참고해주세요

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- 여기서 옵셔널을 꼭 사용해야 할까요?
- `allCases`는 어떤 기능을 하나요?

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
```suggestion
    switch (computerHand, userHand) {
    case (.rock, .scissors),
        (.scissors, .paper),
        (.paper, .rock):
        return .lose
    case (.scissors, .rock),
        (.paper, .scissors),
        (.rock, .paper):
        return .win
    default:
        return .draw
    }
```

저는 보통 이렇게 구현하는 편입니다 ㅎㅎ

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            }
`do - catch문` 안에 있는 if문은 들여쓰기 제한 2회 이상을 어긴 부분입니다. 수정해주세요!

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                }
이 부분도 기능 분리가 필요해보입니다!

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
```suggestion
        } catch {
            print("잘못된 입력입니다. 다시 시도해주세요.")
        }
```

이 부분은 컨벤션이 맞지 않는 거 같네요. 리팩토링을 할 때 컨벤션을 지켰는지의 여부도 체크하는 습관 중요합니다!

2022-12-27 12:30 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
이 `guard문`도 하나로 합칠 수 있지 않을까요?

2022-12-28 08:52 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/InputError.swift
> +}
공식문서 보고 다시 고쳤습니다!

2022-12-28 08:52 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/HandShape.swift
> +}
코드 컨벤션을 잘못 인지하고 있었네요!
그 부분은 수정을 했고, CaseIterable은 컴퓨터의 손 모양을 랜덤 된 값을 가져오기 위해 사용했습니다!

2022-12-28 08:54 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
guard문에서 처리하는 에러의 종류가 하나이기 때문에 하나로 묶어주는 것이 좋다고 생각해 말씀해주신대로 하나의 guard문으로 수정했습니다.

그리고 `validationUserInput`은 `validateUserInput`으로 수정하는 것이 더 함수 기능을 이해하기 좋다고 생각해서 수정했습니다!

2022-12-28 08:55 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
guard문을 사용해서 out of range에 대비하기 위해 옵셔널을 사용했습니다
allCases 열거형을 배열과 같이 만들어서 배열 메서드를 사용할 수 있게끔 해줍니다 (ex. count, randomElement, isEmpty)

2022-12-28 08:57 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
넵 처음에 xcode에서 자동완성 제공이 안되어서 안되는줄 알았는데,

다시 수정해보니 잘 되네요 ! 훨씬 보기가 편한거 같습니다 👍🏼

2022-12-28 08:57 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            }
힌트로 주신 '함수로 기능 분리' 를 해서 수정했습니다!

2022-12-28 08:59 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
넵, 이번엔 저희가 확인이 좀 부족했네요 😂

2022-12-28 08:59 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
네 하나로 합쳤습니다 다시보니 같은 종류를 throw 하므로 하나로 합치는게 좋아보입니다!

2022-12-28 09:00 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                }
넵 여기도 기능분리 하였습니다!

2022-12-28 11:56 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/HandShape.swift
> +}
나중에 `CaseIterable`에 대한 공식문서를 읽어보시고 TIL로 작성해보는 것도 좋을 거 같습니다👍

2022-12-28 12:00 UTC, jsa0224 commented
리팩토링 하신 부분들 잘 보았습니다. 
전반적으로 코드 간결성이 좋아지고, 깔끔해진 거 같습니다👍

Step 2에서 타입을 사용하여 구현해보시면 좋은 경험이 되실 거 같습니다! Step 2도 화이팅!!

2022-12-28 12:00 UTC, merged