묵찌빠 게임 [STEP 2] 무리, 혜모리
yagom-academy/ios-rock-paper-scissors pull request #187
Opened 2022-12-28 05:50 UTC by hyemory

@jjpush 
제이푸시 안녕하세요! STEP 2 PR 보냅니다.
리뷰 기다리겠습니다. 감사합니다!

---
## 고민했던 점
### 타입 만들기
- 현재 구현한 내용에는 `Game`이라는 부모 클래스가 있고, 자식으로 `RockPaperScissors`, `MookJjiBba` 클래스들이 있습니다.
가위바위보와 묵찌빠가 공통적으로 사용하는 기능은 `Game` 클래스에 두었고 자식 클래스들이 공통 기능을 상속받도록 구현했습니다.
- 부모 클래스 `Game`의 네이밍은 처음엔 `HandSignGame`으로 설정했는데, 가위바위보를 나타내는 `HandSign` 타입의 하위 타입 같아 보여서 `Game`으로 변경했습니다.

### 지금 하고있는 게임이 가위바위보인지, 묵찌빠인지 어떻게 알 수 있을까?
- `GameType`을 만들어 입력 받은 사용자 숫자를 `HandSign` 내에서 convert 시 게임 타입을 선택하여 분기를 타도록 구현하였습니다.

### 가위바위보와 묵찌빠의 숫자가 다른 점
- 기존 가위바위보 기능만 있었을 땐 각 가위, 바위, 보 원시값에 맞는 번호를 넣어주었는데 묵찌빠 게임에서는 가위, 바위, 보의 번호가 달라 고민을 해보았습니다. 
- `HandSign`에서 번호를 기준으로 각각의 `GameType`타입에 맞는 가위, 바위, 보를 리턴해주도록 수정했습니다.

### static으로 타입 메서드 만들기
- `HandSign`, `GameResult` 타입을 굳이 인스턴스로 만들지 않고 바로`convertHandSignType`,`compareHandSigns` 함수를 호출하기 위해 함수를 타입 메서드로 만들어주는 `static` 키워드를 사용했습니다. `class` 키워드로도 타입 메서드를 만들 수 있으나, 추후 다른 곳에서 재정의할 일이 없으므로 `static`으로 정하였습니다.

2022-12-28 11:03 UTC, jjpush requested changes
## 고민했던 점

### 타입 만들기

>현재 구현한 내용에는 Game이라는 부모 클래스가 있고, 자식으로 RockPaperScissors, MookJjiBba 클래스들이 있습니다.
>가위바위보와 묵찌빠가 공통적으로 사용하는 기능은 Game 클래스에 두었고 자식 클래스들이 공통 기능을 상속받도록 구현했습니다.
>부모 클래스 Game의 네이밍은 처음엔 HandSignGame으로 설정했는데, 가위바위보를 나타내는 HandSign 타입의 하위 타입 같아 보여서 Game으로 변경했습니다.

### 지금 하고있는 게임이 가위바위보인지, 묵찌빠인지 어떻게 알 수 있을까?

>GameType을 만들어 입력 받은 사용자 숫자를 HandSign 내에서 convert 시 게임 타입을 선택하여 분기를 타도록 구현하였습니다.

### 가위바위보와 묵찌빠의 숫자가 다른 점

>기존 가위바위보 기능만 있었을 땐 각 가위, 바위, 보 원시값에 맞는 번호를 넣어주었는데 묵찌빠 게임에서는 가위, 바위, 보의 번호가 달라 고민을 해보았습니다.
>HandSign에서 번호를 기준으로 각각의 GameType타입에 맞는 가위, 바위, 보를 리턴해주도록 수정했습니다.

### static으로 타입 메서드 만들기

>HandSign, GameResult 타입을 굳이 인스턴스로 만들지 않고 바로convertHandSignType,compareHandSigns 함수를 호출하기 위해 함수를 타입 메서드로 만들어주는 static 키워드를 사용했습니다. class 키워드로도 타입 메서드를 만들 수 있으나, 추후 다른 곳에서 재정의할 일이 없으므로 static으로 정하였습니다.

띄어쓰기부터 줄바꿈까지 아주 깔끔하네요!! 😊
굉장히 굉장히 편안한 코드였습니다
다만 네이밍 한 부분과 각 타입들의 관계와 역할에 대해서 어색하다고 생각되는 부분이 있어 코멘트 남겨두었습니다.

2022-12-28 11:03 UTC, corpiii commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    var turnOwner: String = ""
turnOwner의 네이밍이 Player타입으로 읽히는 것 같습니다. 🤔

2022-12-28 11:03 UTC, corpiii commented on RockPaperScissors/RockPaperScissors/HandSign.swift
> +    static func convertHandSignType(_ number: Int, gameType: GameType) -> HandSign? {
좀 더 자연스러운 문장처럼 읽히는 네이밍이 있을까요? 
전치사를 사용하면 자연스러운 문장이 될 수도 있을 것 같습니다! 😊

[API Design Guidelines - Naming](https://www.swift.org/documentation/api-design-guidelines/#naming)

2022-12-28 11:03 UTC, corpiii commented on RockPaperScissors/RockPaperScissors/MookJjiBba.swift
> +    func judgeWinPlayer() {
여기도 접근제어!

2022-12-28 11:03 UTC, corpiii commented on RockPaperScissors/RockPaperScissors/main.swift
> +game.playGame()
가위바위보 타입을 생성해서 게임을 시작하는데 묵찌빠도 함께 실행이 되는 부분이 어색해보이네요 🤔
가위바위보는 가위바위보만 하도록
묵찌빠는 묵찌빠만 하도록 해볼 수 있을까요? 🫡

2022-12-28 11:03 UTC, corpiii commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    func checkUserNumber(number: Int?) -> Int {
[접근제어](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html)에 대해서 한번 알아보셔도 좋을 것 같습니다! 😁

접근제어자의 종류에는 어떤 것들이 있고 어떤 기능을 할까요?

2022-12-28 11:18 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +    var mookJjiBba: MookJjiBba = MookJjiBba()
var를 사용하신 이유가 궁금합니다!

2022-12-28 11:18 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/MookJjiBba.swift
> +        return super.choiceUserNumber()
super.choiceUserNumber()의 사용 아주 좋습니다!! 👍👍👍👍

2022-12-28 11:18 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/MookJjiBba.swift
> +class MookJjiBba: Game {
class를 사용해 주셨네요! 멋집니다! 
class와 struct의 차이점은 무엇이며
어떤 기준으로 class와 struct를 선택하는 것이 좋을까요?

2022-12-28 11:20 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/GameResult.swift
>          }
멋지게 결과를 뽑아내고 있네요! 👍

2022-12-28 11:20 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/GameType.swift
> +    case mookJjiBba
게임 타입을 구분하기 위해 만들어 주신 점 💯

2022-12-28 11:21 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/HandSign.swift
> +        }
게임 타입에 따라 변환해주셨네요! 💯

2022-12-29 06:39 UTC, hyemory commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    var turnOwner: String = ""
`turnOwner`의 타입을 `Player` 타입으로 변경했습니다!

2022-12-29 06:41 UTC, hyemory commented on RockPaperScissors/RockPaperScissors/HandSign.swift
> +    static func convertHandSignType(_ number: Int, gameType: GameType) -> HandSign? {
전치사를 사용하여 `convertNumberToHandSign` 메소드로 이름을 바꿨습니다!

2022-12-29 06:55 UTC, parkmuri commented on RockPaperScissors/RockPaperScissors/MookJjiBba.swift
> +class MookJjiBba: Game {
- `class`는 `reference type`으로 인스턴스에 값을 전달할 때 메모리 위치를 전달해주어 인스턴스가 값을 수정하면 class 타입에서도 값이 변경됩니다. 또 `class`는 상속이 가능합니다. 공통된 부분을 가진 다수의 Type이 필요하다면 `class`를 사용합니다.
- `struct`는 `value type`으로 인스턴스에 값을 전달할 때 값을 '복사'하여 전달합니다. `memberwise init`을 사용하여 `class`에 비해 간단하게 초기화 할 수 있다는 장점이 있습니다. 자신이 다른 타입을 상속 하거나 상속해줄 필요가 없을때 사용합니다.

2022-12-29 06:57 UTC, hyemory commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    func checkUserNumber(number: Int?) -> Int {
접근 제어자는 아래와 같습니다! 
- `open`: 개방 접근 수준(모듈 외부까지), 클래스에서만 사용
-> 다른 모듈에서도 이 클래스를 상속하거나 재정의하겠다는 의도로 사용
- `public`: 공개 접근 수준(모듈 외부까지)
-> open과 다르게 다른 모듈에서 public 클래스를 상속 받거나 재정의할 수는 없다.
- `internal`: 내부 접근 수준(모듈 내부)
-> 외부 모듈에서는 접근할 수 없다. 모듈의 기본값
- `fileprivate`: 파일 외부 비공개 접근 수준(파일 내부)
-> 그 요소가 구현된 소스파일 내부에서만 사용할 수 있다.
- `private`: 비공개 접근 수준(기능 정의 내부)
-> 기능을 정의한 내부에서만 사용할 수 있다.

짚어주신 `checkUserNumber`, `judgeWinPlayer` 함수는 다른 파일에서 호출하지 않아 
`private` 접근 제어자를 붙일 수 있었습니다!
외부에 공개하고 싶은 코드만 공개할 수 있고, 불필요한 접근으로 오류가 발생할 가능성을 줄여줄 수 있는 효과가 있습니다.

2022-12-29 07:00 UTC, hyemory commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +    var mookJjiBba: MookJjiBba = MookJjiBba()
변하지 않는 인스턴스이므로 상수를 사용하는게 더 좋을 것 같습니다. Main 파일 인스턴스 생성하는 부분은 상수로 선언하였습니다!

2022-12-29 07:08 UTC, parkmuri commented on RockPaperScissors/RockPaperScissors/main.swift
> +game.playGame()
- `RockPaperScissors`타입에서 `playGame`메소드 명을 `playRockPaperScissors`로 바꾸고 `playMookJjiBba`를 따로 실행하도록 수정하였습니다.
 가위바위보 인스턴스를 생성하여 게임을 한 후 `playRockPaperScissors` 결과를 기준으로 묵찌빠 인스턴스의 `turnOwner`를 저장합니다.  묵찌빠 인스턴스는 저장된 `turnOwner`를 가지고 `playMookJjiBba`를 실행합니다.

2022-12-30 06:56 UTC, jjpush commented on RockPaperScissors/RockPaperScissors/MookJjiBba.swift
> +class MookJjiBba: Game {
[이 문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)도 함께 읽어보시면 도움이 될 것 같습니다 😊

2022-12-30 07:20 UTC, jjpush commented
👍👍👍👍👍👍👍👍👍👍

타입별의 관계의 고민이나 의존성을 줄이고 결합도를 높이는 등 고민의 흔적이 많이 느껴집니다.
컨벤션, 네이밍, 함수의 기능분리 또한 잘 지켜주셔서 보기가 좋았습니다 

고생 많으셨습니다!! 😊

2022-12-30 07:21 UTC, merged