묵찌빠 게임 [Step2] Harry, Andrew
yagom-academy/ios-rock-paper-scissors pull request #193
Opened 2022-12-29 07:59 UTC by HarryHyeon

@jsa0224 
솜 `Step2` 구현을 완료하여 PR을 보냅니다. 이번에도 잘 부탁드려요! 👍🏼

## 고민했던 점
- 재귀함수를 사용하지 않고 반복문만 사용해서 구현하도록 고민했습니다.

- 사용자 타입을 이용해서 구현 하도록 고민했습니다.

- 열거형 타입을 4가지로 작성을 했는데, 여기서 열거형을 더 추가하면 오히려 코드 흐름을 파악하기 안좋은 것 아닌가 고민했습니다.. 그래서 최대한 있는 것을 활용하는 방향으로 결정했습니다.

---

<br>

## 조언을 받고 싶은 점
- `MukJiPPaGameManager` 클래스의 `startGame` 메서드가 있는데,
코드를 읽었을 때 어떤 경우일때 메서드가 종료되는지 가독성이 떨어진다고
생각 했습니다. 이 부분에서 반환되는 값은 게임을 계속 반복할지 말지 여부를
메인파일로 보내주는 역할을 하고 있습니다.

  읽는 것 만으로 흐름을 어느정도 파악할 수 있게 수정할 좋은 의견이 있으실까요??🥹

- MukJiPPaGameManager에 코드 마지막 부분 제어구문이지만 변수를 사용하지 않아서 경고창을 보기 싫어서 와일드카드(_)를 사용했는데 이런 경우 와일드카드를 사용해도 되는지 궁금합니다.

```swift=
guard let _ = informMatchResult(matchResult: matchResult) else {
    return (self.whosTurn, .gameOver)
}
```

- class랑 struct 둘 중에 상속을 사용하기 위해 class를 선택했는데 상속을 사용하지 않는다면 struct로 구현해도 될지 궁금합니다.

2022-12-29 14:49 UTC, jsa0224 requested changes
Step 2 구현하시느라 고생 많으셨습니다~!
전체적으로 고민을 많이 한 코드라고 느껴져서 좋았습니다👍

## 👍 칭찬하고 싶은 부분
- 사용자 정의 타입을 구현한 점
- 코드를 구현하면서 합리적인 방향을 생각한 점
- 커밋메세지 및 커밋분기 굳굳👍

## 🧐 조언하고 싶은 부분
> ## 고민했던 점
> 재귀함수를 사용하지 않고 반복문만 사용해서 구현하도록 고민했습니다.
>
> 사용자 타입을 이용해서 구현 하도록 고민했습니다.
>
> 열거형 타입을 4가지로 작성을 했는데, 여기서 열거형을 더 추가하면 오히려 코드 흐름을 파악하기 안좋은 것 아닌가 고민했습니다.. 그래서 최대한 있는 것을 활용하는 방향으로 결정했습니다.
- 재귀함수와 반복문의 차이를 공부하시고, 이유 있는 선택을 하신 부분 너무 좋았던 거 같습니다👍 
- 열거형을 추가하면 코드 흐름을 파악하기 어렵다는 생각이 드신 이유는 해당 코드에 대한 직관성이 떨어지고, 무슨 열거형인지 봐야 이해가 가능하다는 점에서 그렇게 생각하신 걸까요? 그렇다면 열거형의 적절한 네이밍이면 코드 흐름을 파악하기 쉬워지지 않을까 생각이 드네요😊

> ## 조언을 받고 싶은 점
>MukJiPPaGameManager 클래스의 startGame 메서드가 있는데,
코드를 읽었을 때 어떤 경우일때 메서드가 종료되는지 가독성이 떨어진다고
생각 했습니다. 이 부분에서 반환되는 값은 게임을 계속 반복할지 말지 여부를
메인파일로 보내주는 역할을 하고 있습니다.
>
> 읽는 것 만으로 흐름을 어느정도 파악할 수 있게 수정할 좋은 의견이 있으실까요??
>
> MukJiPPaGameManager에 코드 마지막 부분 제어구문이지만 변수를 사용하지 않아서 경고창을 보기 싫어서 와일드카드(_)를 사용했는데 이런 경우 와일드카드를 사용해도 되는지 궁금합니다.
> 
> guard let _ = informMatchResult(matchResult: matchResult) else {
    return (self.whosTurn, .gameOver)
}
class랑 struct 둘 중에 상속을 사용하기 위해 class를 선택했는데 상속을 사용하지 않는다면 struct로 구현해도 될지 궁금합니다
- 지금 보니 실질적인 게임 시작은 `playRockPaperScissors()` 함수가 담당하고 있는 거 같네요! 두 분이 하신 고민처럼 `startGame()`이 게임을 시작한다는 로직보다는 게임의 진행 여부를 판단하고 있는 거 같습니다. 제 생각에는 `playRockPaperScissors()`를 게임 시작하는 함수로 변경하시고, 그 안에`startGame()`의 게임 진행 여부를 넣어 구현하는 것도 좋아보일 거 같네요👍
- 와일드 카드 관련해서는 아래에서 코멘트로 설명드리도록 하겠습니다😁
- `class`와 `struct`를 선택한 이유를 들었을 때, 개인적으로는 `protocol`를 사용해도 좋을 거 같다는 생각이 들었습니다. 하지만 `protocol`의 개념을 모르거나, 애매하다고 느끼신다면 이 부분은 패스하셔도 좋습니다. 하지만 상속과 확장, 추상화의 개념에 대해서는 계속 고민해보시면 좋을 거 같아요! 

### 접근제어자
사용자가 알아서는 안 되는 로직들은 [접근제어자](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#:~:text=and%20so%20on.-,Access%20Levels,-Swift%20provides%20five)를 적용해보는 것도 좋을 거 같습니다!

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +    var whosTurn: String = "***"
- `***`로 값을 할당한 이유가 있나요?
- `whosTurn` 네이밍은 조금 어색해보이네요😲

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +                return "컴퓨터"
`whosTurn`이 프로퍼티로 계속 활용이 되고 있는데, `whosTurn`은 턴이 바뀔 때마다 값이 계속 바뀌게 되는 로직 같아 보입니다.
차라리 턴을 관리하는 타입을 만드는 건 어떨까요?

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +        }
```suggestion
        guard informMatchResult(matchResult: matchResult) != nil else {
            return (self.whosTurn, .gameOver)
        }
```

PR 코멘트로 여쭤보신 부분이군요!
옵셔널 바인딩의 목적은 값이 있는 지 없는 지에 대한 여부를 알기 위함이라고 저는 이해하고 있습니다.
이러한 시각에서 별다른 상수 선언 없이 `!= nil`로도 표현이 가능합니다!

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGameManager.swift
> +            }
```suggestion
        let input = readUserInput()
        var userNumber = 0
        
        do {
            userNumber = try validateUserInput(userInput: input)
            if userNumber == 0 {
                print("게임 종료")
                return (nil, .gameOver)
            }
```
변수와 메서드 부분은 이렇게 구분하는 게 좋아보입니다!

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +    func turn(matchResult: MatchResult?) {
`turn`이라는 네이밍이 돌아간다, 라는 의미로도 해석되어 명확한 네이밍이면 좋을 거 같습니다🤔
단순히 누구의 턴인지 보여주는 용도라면 `show`와 비슷한 네이밍도 괜찮아 보입니다.

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +//  Game.swift
- 게임의 요소들을 넣은 파일이라면, 조금 모호한 네이밍 같아요.
저라면 여기서 게임을 시작해야하나 기웃거릴 거 같은 느낌스...?
게임의 구성요소 혹은 더 좋은 네이밍 방향 있으심 그렇게 바꾸시는 걸 추천드립니다! 

- 그리고 `HandShape`도 게임의 기능 중 하나이기 때문에 여기에 같이 넣으면 좋을 거 같네요👍

2022-12-29 14:49 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
저는 main 파일 부분이 사용자에게 비춰지는 부분이라고 생각이 듭니다. 
사용자가 게임이 어떻게 진행되고 있는 지 로직을 볼 필요가 있을까요?

위에서 말씀드린 것처럼 이 부분이 `startGame()`의 로직이 되면 좋을 거 같아요. 
여기서는 사용자가 `.keepPlaying`를 바꿀 가능성이 있어보이네요!ㅋㅋ

제가 저번에 말한 `은닉화`와 `캡슐화` 개념으로 생각해보면 좋을 거 같아요👍

2022-12-30 03:13 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +    var whosTurn: String = "***"
누구의 턴인지 물어보는 느낌으로 whosTurn으로 네이밍을 했었는데,

보여주는 의미에 가까운거 같아 showTurn으로 변경하고 타입도 열거형을 새롭게 만들어 초기화 했습니다!

2022-12-30 03:13 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +                return "컴퓨터"
enum 타입으로 MukJiPPaTurn를 만들어서 관리하도록 하였습니다.

2022-12-30 03:14 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperGameManager.swift
> +            }
개행 하였습니다!

2022-12-30 03:14 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +        }
이 부분은 게임 실행부분의 코드를 전체적으로 수정하여서 사라지게 되었습니다!

!=nil 로도 검사할 수 있다는 점을 놓치고 있었네요 !

2022-12-30 03:15 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +    func turn(matchResult: MatchResult?) {
showTurn 으로 수정 후 묵찌빠턴 이라는 열거형 타입으로 선언해줬습니다!

2022-12-30 03:15 UTC, Andrew-0411 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +//  Game.swift
game의 요소들을 넣어줄 파일이기 때문에 gameComponent로 변경하였습니다

2022-12-30 03:15 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
저도 이전에 말씀해주신것처럼 굳이 사용자에게 보여질 필요가 없다고 생각해서

main 파일에서는 startGame만 수행하도록 전체 로직을 수정하였습니다!

2022-12-30 07:38 UTC, jsa0224 commented on RockPaperScissors/RockPaperScissors/MukJiPPaGameManager.swift
> +    var whosTurn: String = "***"
프로퍼티 변수명 네이밍이 동사로 시작하는 건 좋은 네이밍은 아닌 거 같습니다😅
turn을 사용하는 메서드들의 매개변수로 활용하는 방법도 좋을 거 같아요

2022-12-30 12:15 UTC, jsa0224 commented
두 분 묵찌빠 프로젝트 수행하시느라 고생 많으셨습니다!

2022-12-30 12:15 UTC, merged