묵찌빠 게임 [Step1] yy-ss99, Hemg
yagom-academy/ios-rock-paper-scissors pull request #194
Opened 2023-05-01 04:44 UTC by hemg2

@Rhode-park 
안녕하세요. 로데! 커리어 9기 yy-ss99, Hemg 입니다.
첫 PR 보냅니다. 한 주간 잘 부탁드립니다.
감사합니다.

## 고민 했던점

- 승리조건

```swift
if userInput == computerInput {
print("무승부")
}
else if userInput("가위") == computerInput("묵") {
print("졌습니다.)
}
else if userInput("가위") == computerInput("보") {
print("승리했습니다.")
}
.................
```

승리 조건과 패배의 조건에 대해서 많은 고민을 하게 되었습니다.

승리 조건, 패배 조건 모두 걸어야 된다고 생각을하며 처음에는 접근을 하였고

이런식으로 하나하나 모든 승리의 조건과 패배 조건을 진행 하려고 했습니다.

너무나 긴 코드가 생각이 되어서 고민을 하다보니 

`||(OR)` 조건이 생각 났으며 승리조건을 따로 모을수 있었습니다.

추가적으로 승리조건이 아니라면 무승부나, 졌다라고 생각하여 코드를 짰으며 테스트 진행시 잘되었습니다…

```swift
if userInput == computerInput {
        print("비겼습니다!")
    } else if userInput == "1" && computerInput == "3" ||
                userInput == "2" && computerInput == "1" ||
                userInput == "3" && computerInput == "2" {
        print("이겼습니다!")
    } else {
        print("졌습니다!")
    }
```

## 조언을 얻고 싶은 부분

- guard 와 병합 연산자의 차이를 알고 싶습니다.

```swift
1) let userNumber: String = readLine() ?? ""

2) guard let userNumber: String = readLine() else { return }
```

1번 코드에서 2번 코드로 변형을 했습니다.
옵셔널 바인딩을 하여 안전하게 추출해야 한다고 생각했습니다.
`guard`문, `if let`으로 바인딩 하여 안전하게 추출 후 사용 하는 방법도 있고 병합 연산자를 사용도 가능하다고 생각됩니다.
병합연산자 사용보다는 guard가 더 안전하다고 생각되어 변경을 진행했는데 이 둘의 차이점을 알 수 있을까요??

- 여러 조건이 있을 때 스위치 사용

```swift
if userNumber == gameEnd {
            isGameOn = false
            print("게임종료")
        } else if userNumber == "1" ||
                    userNumber == "2" ||
                    userNumber == "3" {
            checkRockPaperScissors(with: userNumber, computerNumber)
        } else {
            print("잘못된 입력입니다. 다시 시도해주세요.")
        }
```

else if 문에 있는 거 처럼 여러 조건을 switch문 에 넣을 수 있는 방법이 있을까요??

2023-05-02 03:48 UTC, Rhode-park requested changes
와이, Hemg PR을 일찍 보내주셨는데, 코멘트가 조금 늦어져서 미안합니다.
열심히 코드를 짜주셨네요!
다만 조금 제안하고 싶은 부분이 있습니다.

## 제안하고 싶은 부분
### 타입을 구현해보세요.
이제 막 객체지향을 배웠다고 알고 있는데, 객체지향적으로 타입을 구현해보시는 것은 어떨까요? 타입을 구현해서 main.swift에서는 메서드 하나만 호출할 수 있도록 해보세요! 그리고 객체지향적으로 타입을 구현하게 되면 그렇지 않을 때와 비교하여 어떤 장단점이 있을까요? 

### 함수의 기능을 분리해보세요.
하나의 함수/메서드는 하나의 기능만을 가지고 있는 것이 좋습니다. 왜 그런지에 대해서 알아볼까요?

## 조언을 얻고 싶은 부분에 대한 제 의견
### guard 와 병합 연산자의 차이를 알고 싶습니다.
> 1) `let userNumber: String = readLine() ?? ""`
> 
> 2) `guard let userNumber: String = readLine() else { return }`
> 1번 코드에서 2번 코드로 변형을 했습니다.
> 옵셔널 바인딩을 하여 안전하게 추출해야 한다고 생각했습니다.
> guard문, if let으로 바인딩 하여 안전하게 추출 후 사용 하는 방법도 있고 병합 연산자를 사용도 가능하다고 생각됩니다.
> 병합연산자 사용보다는 guard가 더 안전하다고 생각되어 변경을 진행했는데 이 둘의 차이점을 알 수 있을까요??

[Nil-Coalescing Operator](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/basicoperators#Nil-Coalescing-Operator), [Optional Binding](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics#Optional-Binding) [Early Exit](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow#Early-Exit)를 각각 읽어보고 차이점을 알아볼까요? Optional을 다루는 방식에는 어떠한 것들이 있으며, 각각의 것들은 어떻게 진행이 되는지, 또 어떤 특징을 가지고 있는지 알려주세요!

### 여러 조건이 있을 때 스위치 사용
> ```swift
> if userNumber == gameEnd {
>     isGameOn = false
>     print("게임종료")
> } else if userNumber == "1" ||
>             userNumber == "2" ||
>             userNumber == "3" {
>     checkRockPaperScissors(with: userNumber, computerNumber)
> } else {
>     print("잘못된 입력입니다. 다시 시도해주세요.")
> }
> ```
> else if 문에 있는 거 처럼 여러 조건을 switch문 에 넣을 수 있는 방법이 있을까요??

[Switch](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow#Switch)문서를 읽음으로써 답을 얻을 수 있을 것 같아요. 그래도 해결이 되지 않는다면 다시 질문 부탁드립니다.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by yy-ss99, Hemg.
main은 이미 생성되어있던 파일이므로 원작자는 그대로 두는게 맞습니다. `Created by yagom`으로 두는게 좋을 것 같네요.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> -import Foundation
`import Foundation`의 필요성을 확인하고 제거해주셨군요! LGTM👍🏻 

`import Foundation`은 어떤 기능을 하길래 제거해도 괜찮은 것일까요?

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +func showGameMune() {
스펠링이 틀렸네요. 유의해서 네이밍을 해야할 것 같아요.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +func showGameMune() {
하나의 함수에 너무 많은 기능들이 포함되어있습니다. 하나의 함수에는 하나의 기능만을 가지고 있는게 좋을 것 같네요. 지금 제가 보았을 때만 해도 네가지 혹은 그 이상의 기능이 있는 것 같네요. 이 부분 기능 분리가 필요해보여요.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var isGameOn: Bool = true
flag를 사용해주셨군요! LGTM👍🏻 현재의 코드에서 flag를 사용할 때의 이점/기능은 무엇이 있을까요?

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let gameEnd: String = "0"
여러 입력 옵션들 가운데에, `gameEnd`만 상수로 선언해 준 이유는 무엇일까요?

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("가위(1), 바위(2), 보(3)! <종료 :0> : ", terminator: "")
기능 하나: 메뉴를 보여 줌. 함수의 네이밍과 일치.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let userNumber: String = readLine() else { return }
기능 둘: 메뉴를 입력 받음. 함수의 네이밍과 불일치.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let computerNumber: String = String(Int.random(in: 1...3))
네이밍은 `computerNumber`라고 되어있는데, 타입은 String이네요? `userNumber`도 마찬가지네요. 무언가 어색하지 않나요? 네이밍이 타입을 반영하지 못하고 있는 것 같아요.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
[Control Flow - Switch](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#Switch)를 참고해보시겠어요? 

지금의 코드를 if-else if-else 문으로 작성했을 때와, switch문으로 작성했을 때 각각 어떤 이점을 가지게 될까요? 왜 제가 switch를 참고해보라고 하였을까요?

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +func checkRockPaperScissors(with userInput: String, _ computerInput: String) {
가위바위보를 확인하는 기능을 분리해주셨군요! LGTM👍🏻

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
마찬가지로 switch문으로 바꿔볼 수 있을 것 같아요.

2023-05-02 03:48 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("비겼습니다!")
해당 함수는 가위바위보를 확인하는 함수인데, 출력해주는 기능까지 겸하고 있네요? 기능분리가 필요하겠죠?

2023-05-02 06:15 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/main.swift
> -import Foundation
- 텍스트 처리 기능: 문자열 처리, 인코딩, 정규 표현식, 로케일 등의 기능을 제공합니다.
- 데이터 저장 및 관리 기능: 파일 시스템, 미디어 데이터, 네트워크 통신, plist 파일 등 데이터 저장과 관리에 필요한 기능을 제공합니다.
- 날짜와 시간 처리 기능: 시간대, 날짜 계산, 캘린더, 타이머 등의 기능을 제공합니다.

지금 프로젝트에서는 Foundation이 필요로 하지 않을꺼 같아서 제거 하게 되었습니다.

2023-05-02 06:15 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func showGameMune() {
변경 완료했습니다! 유의하도록 할게요!!

2023-05-02 06:16 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func showGameMune() {
네 피드백 이후 함수 기능 분리 진행했습니다!

2023-05-02 06:17 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var isGameOn: Bool = true
코드의 가독성을 높일 수 있고 조건식을 분리해서 조종할수 있어서 flag를 사용했습니다. 
재귀 함수를 쓸수도 있다고 생각합니다. 하지만 재귀 함수 실행시 오버플로우가 발생 할수 있어서 while문을 사용했습니다

2023-05-02 06:18 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let gameEnd: String = "0"
게임종료라는 것을 명시적으로 보여주고 싶어서 상수로 만들어서 조건문에 넣어주었습니다. 나머지 조건들도 열거형을 사용하여 코드 가독성을 높혔습니다.

2023-05-02 06:18 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let userNumber: String = readLine() else { return }
함수 기능분리를 했습니다!

2023-05-02 06:20 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let computerNumber: String = String(Int.random(in: 1...3))
네 피드백 진행하여 
`computerNumber` -> `computerInput` 
`userNumber `->  `userInput` 변경 해 보았습니다.

2023-05-02 06:21 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
가독성의 차이가 있습니다. 또한 if문의 경우 조건의 종류가 매우 다양한 경우나, 경우에 따라 다른 조건 분기가 필요한 경우에 유용합니다. switch문은 패턴으로 비교를 하고 if 문은 조건식으로 비교를 합니다.
위의 코드에서 스위치문으로 바꾼다면 ₩userNumber == ₩ 반복을 줄일 수 있는 이점이 있습니다.

2023-05-02 06:22 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
네 튜플을 이용하여 스위치문으로 변경 진행했습니다.! `감사합니다!`

2023-05-02 06:22 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("비겼습니다!")
기능 분리 하였습니다!!

2023-05-02 06:26 UTC, hemg2 commented
## PR 코멘트

- 타입을 구현해서 main.swift에서는 메서드 하나만 호출할 수 있도록 해보세요! 그리고 객체지향적으로 타입을 구현하게 되면 그렇지 않을 때와 비교하여 어떤 장단점이 있을까요?    
    장점
    - 코드 재사용이 용이하다
        → 캡슐화로 객체의 내부 구현이 외부에 노출되지 않기 때문에, 외부에서는 객체를 사용하는 방법만 알면 되기 때문에 이해하기 쉽다.
        유지보수가 쉽다
        
    - 코드의 가독성이 높아진다
    → 추상화를 통해 공통의 속성이나 기능을 묶어서 하나의 타입으로 만들기 때문이다
    
    단점
    - 객체가 많으면 용량이 커진다
    - 처음 설계 시 많은 시간과 노력이 필요하다

- 함수 기능을 분리해보세요.
    - 함수/메서드는 하나의 기능만을 가지고 있는 것이 좋습니다. 왜 그런지에 대해서 알아볼까요?
    - 왜? 클린코드를 하기 위해서라고 생각되며 함수의 가독성과 유지 보수를 높혀주기 때문이라고 생각됩니다.
    - 함수가 여러가지 일을 하게되면 동작하는걸 이해하기 힘들고 재사용 하기도 어렵다고 생각 됩니다.
- **guard 와 병합 연산자의 차이를 알고 싶습니다.**
    - Optional을 다루는 방식에는 어떠한 것들이 있으며, 각각의 것들은 어떻게 진행이 되는지, 또 어떤 특징을 가지고 있는지 알려주세요!
    1. 옵셔널에는 바인딩, 체이닝, 강제 추출, nil 병합 연산자 가 있습니다.
    2. 바인딩 → 옵셔널 값이 있는지 확인하고 값을 추출합니다 (if-let, guard-let)
    3. 체이닝 → 옵셔널 값을 확인하고 값이 존재하면 그값을 추출합니다 nil경우 nil반환 여러 옵셔널이 존재할때 체이닝을 사용한다(nil일시에 뒷코드들은 실행되지않습니다.)
    4. 강제추출 → 옵셔널값의 존재를 확인하지않고 강제로 추출합니다..
    5. nil 병합 연산자 → 옵셔널값이 nil일 경우 기본값을 지정하여 반환하는 연산자 입니다. nil이 아닐경우 옵셔널값이 반환됩니다.

2023-05-03 10:49 UTC, Rhode-park commented
열심히 요구사항들을 반영해주셨네요! 심지어 은닉화까지 잘 처리해주셨네요! LGTM👍🏻 그치만 메서드의 네이밍에 맞게 기능분리가 더 되어도 좋을 것 같아요. 그리고 userInput과 computerInput은 통일성을 주는 것도 좋을 것 같아요. 가령 이런 식으로요.

```swift
struct RockPaperScissors {
    func startGame() {
        
        showGameMenu()
        
        guard let userInput: String = readLine() else { return }
        let computerInput: String = makeComputerInput()
        
        checkGameEnd(userInput)
        getUserInput(userInput, computerInput)
    }
    
    private func showGameMenu() {
        print("가위(1), 바위(2), 보(3)! <종료 :0> : ", terminator: "")
    }
    ...
    
```

정말 수고하셨습니다. 머지해드릴게요. 나머지는 다음 step에서 조금 더 개선해보아요!

2023-05-03 10:50 UTC, merged