묵찌빠 게임 [STEP 1] kyungmin, Kobe
yagom-academy/ios-rock-paper-scissors pull request #200
Opened 2023-05-02 03:10 UTC by devKobe24

(레옹아범)@fatherLeon 안녕하세요🙋‍♂️ kyungmin, Kobe 입니다.

재미있고 즐겁게 해본 묵찌빠 게임의 [STEP 1] 첫 PR을 보내드립니다.😆
---
## 고민했던 점
- 열거형을 활용해 묵찌빠 게임 코드 중에 어떤 부분을 열거형으로 만들어 코드를 작성해야 할지 고민했습니다.
- 승리 조건에 대하여 고민했습니다.
- 인덴트와 네이밍에 대하여 정말 많이 고민했습니다.
---

## 해결이 되지 않은 점
- 입력에 대한 예외처리에 대해 고민이 있었습니다. 처음에는 Error프로토콜을 채택하여 열거형으로 error들을 나열한 후 throws, throw로 error를 던진 후 do try catch문을 이용하여 에러에 대한 처리를 했었습니다. 이렇게 구현하다 보니 입력을 받아 에러를 던지는 함수와 그에러를 받아 처리해주는 함수를 구현하게 돼서, 코드 간편화를 위해 현재 작성한 코드로 예외 처리를 해주었는데요. 어떤 상황에 어떤식으로 예외처리를 하는게 올바른 방법인지에 대해 알려주시면 정말 감사하겠습니다.
---

## 조언을 얻고 싶은 부분
- 조건부를 만들 때 어떻게 하면 조금 더 깔끔하게 조건부를 만들 수 있는지 궁굼합니다.
- 재귀 함수가 아닌 다른 방법으로 함수의 리턴 값을 가져와 사용할 수 있는 방법이 궁굼합니다.
- 짝 프로그래밍에서 좋은 결과를 얻을 수 있는 꿀팁이 있을까요?
- 가끔씩 다른 잘하는 사람들과 저 자신이 많이 비교가 됩니다 ㅠㅠ 이런것을 없앨 수 있는 팁 있을까요??
- 개인 공부를 할때, "이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야 하는 문서"를 먼저 읽어보다 보면 쉽게 지치고 시간도 오래 걸려서 프로젝트를 수행함에 있어 구현하기 어려운 개념에 대한 공부방식으로 바꿔나가게 되는데요. 이런식으로 공부하는게 맞을까요?
- 공부 방법에 대한 팁을 알려주세요.

2023-05-02 12:15 UTC, fatherLeon commented
* 안녕하세요 @devKobe24 @YaRkyungmin
* 되게 빠르게 구현을 해주셨네요👍
* 코드 리뷰 이외에 추가적으로 구현하면 좋을만한 점은 해당 글 맨 마지막에 적어두겠습니다.
* 이외에 구현이 어렵거나 리뷰 내용을 이해 못하는 부분이 있으시면 DM으로 말씀해주세요~~~

## 고민했던 점
* 열거형의 활용 및 Switch 결과 조건문은 잘 작성하신 것 같습니다.
* 들여쓰기의 경우 한개? 정도 고치실게 있고 나머지 들여쓰기 코멘트는 두분이서 고민하셔서 정하시면 좋을 것 같습니다.
* 다만 네이밍의 경우 어색한 부분도 많고 아쉬운 부분도 많아 문서 링크도 달아드렸으니 조금씩 읽어보시면서 추후 STEP2는 조금 더 깔끔하게 하실 수 있을거라 생각합니다

## 해결이 되지 않은 점
* 예외처리의 경우 말씀하신것처럼 `Error`프로토콜을 이용하여 처리하는 방법도 있습니다. 
* [LocalizedError | Apple Developer Documentation](https://developer.apple.com/documentation/foundation/localizederror) 위 프로토콜을 채택하여 에러마다 특별한 내용을 달아서 처리하는 방법도 있을것 같네요
* 예외처리를 구현하시다보면 분명히 `do-catch`문을 사용하다보니 코드가 지저분하다고 생각하실 수도 있지만

```swift
		if let inputString = readLine(), let convertInteger = Int(inputString) {
			outputNumber = convertInteger
		} else {
			print("잘못된 입력입니다. 다시 시도해주세요.")
			continue
		}
```

* `readLine()`과 `Int`로 만들어주는 부분이 만약 에러를 반환하는 메소드로 구현되어 있다면

```swift
		do {
			let userInput = try readUserInput()
			
			outputNumber = userInput
		} catch {
			print(error.description)	// 잘못된 입력입니다 다시 시도해주세요
		}
```

* 위와 같이 구현할 수도 있으니 역할분리에 조금 더 신경을 써보시면 좋을 것 같습니다.
* 다만 현재코드에서는 `Error`쪽을 이용하기 보다는 메서드의 반환타입을 옵셔널로 변화시켜 `guard`문으로 처리하는 방법을 조금 더 공부해보시는게 좋을 것 같습니다.

## 조언을 얻고 싶은 부분
> 조건부를 만들 때 어떻게 하면 조금 더 깔끔하게 조건부를 만들 수 있는지 궁굼합니다.

* 단순히 조건부뿐만아니라 조건문쪽까지 포함해서 전체적으로 말씀드리면
* `if`문을 사용하는게 잘못된것은 아니지만 현재 코드에서 사용하는 대부분의 `if`문은 `guard`문 변경을 하면 조금 더 깔끔하게 사용할 수 있을 것 같습니다.
* `guard`문을 사용할 경우 아무래도 `else`쪽에만 들여쓰기를 하면 되기 때문에 훨씬 더 깔끔하게 코드를 작성하실 수 있을것 같습니다.
* 메서드에서 단순히 특정 타입만을 반환하기보다는 nil도 반환하는 등 옵셔널 타입을 적극활용하여 조건문+조건부를 조금 더 깔끔하게 사용하실 수 있을것 같습니다.

> 재귀 함수가 아닌 다른 방법으로 함수의 리턴 값을 가져와 사용할 수 있는 방법이 궁굼합니다.
* 이 질문은 이해를 잘 못하겠네요..😅😅

> 짝 프로그래밍에서 좋은 결과를 얻을 수 있는 꿀팁이 있을까요?
* 개인적인 생각입니다만, 순전히 코드실력을 늘리는것은 짝 프로그래밍보다 혼자하거나 서로서로 조금씩 구현하는게 더 코드실력이 늘어난다고 생각합니다.
* 다만 짝 프로그래밍을 하는것은 내가 아는 것을 하고 싶은 것을 상대에게 말하는 것이 어렵기 떄문에 짝 프로그래밍을 통해 내비게이터 때는 소통 능력을 키우고 드라이버 때는 나라면 코드를 이렇게 짤텐데 타입을 분리할텐데 등등 생각을 할 수 있는 역할이라 생각합니다.
* 위 내용말고도 다른 점도 있을 것 같지만 제 생각은 이렇네요 ㅎㅎ;;;
* 이런 부분 참고하시고 짝 프로그래밍 검색해보시면 여러가지 내용 많으니 읽어보시면 좋은 결과를 얻으실 수 있을거라 생각합니다

> 가끔씩 다른 잘하는 사람들과 저 자신이 많이 비교가 됩니다 ㅠㅠ 이런것을 없앨 수 있는 팁 있을까요??
> 개인 공부를 할때, “이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야 하는 문서”를 먼저 읽어보다 보면 쉽게 지치고 시간도 오래 걸려서 프로젝트를 수행함에 있어 구현하기 어려운 개념에 대한 공부방식으로 바꿔나가게 되는데요. 이런식으로 공부하는게 맞을까요?
> 공부 방법에 대한 팁을 알려주세요.

* 음… 이부분은 서로 시간 잡아서 한번 얘기해보면 좋을 것 같네요

## 추가 구현하면 좋을 부분
1. STEP2부터는 브랜치를 파셔서 구현하면 좋을 것 같습니다. 현재 main브랜치 토대로 작업하고 계신데 이를 토대로 STEP2 브랜치를 파셔서 작업하시고 다음 PR보내실 때는 STEP2의 내용을 보내주세요~
2. 현재까지 구현하신 내용은 main파일에 전부 다 들어가도 읽는데 큰 문제 없을 정도로 내용이 적지만, 코드가 길어지다보면 각자 타입을 파악하기가 힘들 수 있습니다. `HandShape`, `GameResult`와 같은 타입은 하나하나 파일을 새로 생성하시는 것을 추천합니다.
3. 현재 main파일에 메서드만 존재하는데 해당 메서드들을 전부 포함하는 하나의 타입을 생성하여 타입 안에 메서드를 넣어서 큰 타입을 하나 구현해보시면 좋을 것 같습니다.
4. 추가로 타입을 구현하실 때 다른것도 중요하지만 은닉화를 꼭 해보시면 좋을 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon requested changes

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
`CaseIterable`을 사용하셨네요 좋습니다👍👍
`CaseIterable`은 어떤것이고, 왜 사용하셨나요??🤔

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
게임결과를 열거형 타입으로 만들어 주신것 좋습니다👍

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let inputUserMenu = inputUserNumber()
input이라는게 명사와 동사 둘 다 쓰일 수 있는 단어지만 메소드와 변수 명 둘 다 쓰이는 것은 보기 좋지는 않은 것 같습니다.
[API Design Guidelines - Omit needless words](https://www.swift.org/documentation/api-design-guidelines/)
해당 내용을 참고하여 조금 더 간결하게 변수명을 수정하면 좋을 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let selectInputUserNumber = inputUserMenu-1
[Basic Operators](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/basicoperators)
해당 부분은 컨벤션 수정이 필요해보이네요
무언가 컨벤션이 고민된다면 위와 같이 해당 문서를 참고하여 공식문서에서 사용하는 기존의 방법을 통해 컨벤션을 맞추면 좋습니다.
[API Design Guidelines - Embrace precedent](https://www.swift.org/documentation/api-design-guidelines/)

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let selectRandomNumber = generateRandomNumber()-1
윗 부분과 마찬가지 코멘트지만 추가적으로
일반적으로 메서드는 동사로 시작하고 변수명은 명사인데
해당 변수명은 동사로 시작하네요 변수명 수정이 필요해보입니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let randomHandShape = HandShape.allCases[selectRandomNumber]
똑같은 역할과 결과를 반환하기때문에 해당 내용을 메서드로 만들거나 기존 메서드를 수정하면 좋을 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		switch competeResult(user: handShape, computer: randomHandShape){
[Control Flow](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#Switch)
해당 내용을 참고하셔서 컨벤션을 수정하시면 좋을 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputUserNumber() -> Int {
제 생각에는 Int보다는 HandShape를 반환하고 옵셔널 타입을 이용하면 지금과 똑같이 사용할 수 있을 것 같습니다.
옵셔널을 이용하여 메서드 구현에 대해서 조금 더 공부해보시면 좋을 것 같아서 말씀드리는거니 굳이 수정하진 않으셔도 됩니다

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		if let inputString = readLine(), let convertInteger = Int(inputString) {
위 부분은 개행을 하면 조금 더 보기 편할 것 같습니다 코드 길이가 그렇게 길지 않다보니 굳이 하지는 않으셔도 됩니다

[Name variables, parameters, and associated types according to their roles, rather than their type constraints.](https://www.swift.org/documentation/api-design-guidelines/)
위 부분 참고하셔서 변수명은 수정하는게 좋을 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputUserNumber() -> Int {
추가로 해당 메서드의 `if`문을 `guard`문으로 바꾸면 좋을 것 같습니다.
`isNotCorrectNumber`를 사용하여 조건문 플래그를 만들어 주신것은 너무 좋지만 `guard`문을 사용하는 것이 해당 메서드의 전체적인 흐름을 보기 편할 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
되게 짧은 메서드이지만 역할이 확실하기 때문에 메서드로 분리해준 것 좋은것 같습니다.
다만, 굳이 숫자를 반환해줄 필요는 없어보입니다.
`CaseIterable`을 채택한만큼 랜덤한 `HandShape`를 리턴해주도록 메서드를 수정하면 좋을 것 같습니다.

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func competeResult(user: HandShape, computer: HandShape) -> GameResult {
`competeResult`라는 메서드가 결과와 경쟁한다? 이런식으로 이상하게 느껴지네요 해당 메서드 명이 역할을 온전히 못 담는것 같아 수정하면 좋을 것 같습니다.

또한 아래 링크 확인하셔서 인자 라벨도 컨벤션에 맞게 수정하시면 좋을 것 같습니다.
[Argument Labels](https://www.swift.org/documentation/api-design-guidelines/)

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
Switch문을 잘 활용하셨네요👍👍

2023-05-02 12:15 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func playRockScissorsPaper() {
전체적으로 메서드를 통해 조금 더 역할분리를 하시면
해당 메서드는 코드가 더 짧아지고 보기 좋을 것 같습니다

2023-05-03 00:11 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
열거형에 포함된 모든 케이스를 알아야 할 때 항목 순회 기능을 이용합니다.
열거형 이름의 뒤에 콜론(:)을 작성 한 후 한 칸 띄운 뒤 CaseIterable 프로토콜을 채택합니다.
채택 후 allCases라는 이름의 타입 프로퍼티를 통해 모든 케이스의 컬렉션을 생성해 줍니다.

CaseIterable을 채택한 이유는 랜덤으로 받아온 이유는 정수를 이용하여 인덱스 값으로 enum의 각 case에 접근하기 위해서 사용했습니다.

2023-05-03 00:13 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let inputUserMenu = inputUserNumber()
네 해당 내용 참고하여 수정해보겠습니다 :)

2023-05-03 00:19 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let selectInputUserNumber = inputUserMenu-1
inputUserMenu-1 부분의 띄어쓰기가 잘못된 것은 인지하였습니다. 혹시 if 실행문 뒤에 break도 개행을 해야하는게 맞는 걸까요?

2023-05-03 00:21 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let selectRandomNumber = generateRandomNumber()-1
해당 사항 참고하여 수정하겠습니다 감사합니다 :)

2023-05-03 00:22 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let randomHandShape = HandShape.allCases[selectRandomNumber]
네 메서드를 분리하여 구현해보겠습니다:)

2023-05-03 00:23 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/main.swift
> +		switch competeResult(user: handShape, computer: randomHandShape){
네 알겠습니다 해당 내용 확인하고 참고하여 수정해보겠습니다 :)

2023-05-03 00:24 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputUserNumber() -> Int {
네 옵셔널을 이용한 메서드 구현에 신경써보겠습니다. 감사합니다

2023-05-03 00:25 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/main.swift
> +		if let inputString = readLine(), let convertInteger = Int(inputString) {
네 해당 사항 참고하여 개행하도록 하겠습니다 :)

2023-05-03 00:26 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputUserNumber() -> Int {
guard문으로 변경해서 구현해보겠습니다

2023-05-03 00:26 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
네 수정하겠습니다 :)

2023-05-03 00:27 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +func competeResult(user: HandShape, computer: HandShape) -> GameResult {
네 네이밍에 대해 고민을 더 해보겠습니다.

2023-05-03 00:27 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +func playRockScissorsPaper() {
playRockScissorsPaper 메서드를 분리해보겠습니다

2023-05-03 00:39 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let randomHandShape = HandShape.allCases[selectRandomNumber]
receiveHandShapeElement 메서드로 분리하였습니다.

2023-05-03 01:54 UTC, devKobe24 commented
안녕하세요 @fatherLeon(레옹아범) kyungmin, kobe 입니다.
저희 수정 사항 모두 반영했습니다.
잘 부탁드립니다 😆

2023-05-03 05:33 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +		let selectInputUserNumber = inputUserMenu-1
* 한줄에 일정 글자 수 넘어가면 개행할 때도 있고 위와 같이 한 줄로 쓰는 경우도 있습니다.
* 구문안에 두줄이 들어가면 개행을 하는게 좋겠지만 지금은 코드도 짧고 `break`만 있기 때문에 지금같이 써도 상관없을것 같습니다.

2023-05-03 05:39 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
![randomElement](https://developer.apple.com/documentation/swift/array/randomelement())
* Array쪽에 이런 메소드도 있으니 한번 참고해보시면 좋을 것 같습니다

2023-05-03 05:40 UTC, merged