[STEP1] jusbug, idinaloq
yagom-academy/ios-rock-paper-scissors pull request #202
Opened 2023-05-02 06:31 UTC by JusBug

@Kyeongjun2 

안녕하세요 Rowan! Step1 PR합니다. 잘 부탁드립니다!!!

### 작성할 떄 고민한 점🧐
1. push 에러
짝프로그래밍 진행 중 커밋 후 푸쉬를 진행할 때 발생한 에러 메시지 입니다.
================================================================
Updates were rejected because the tip of your current branch is behind...
its remote counterpart. integrate the remote changes (e.g.'git pull...') before pushing again
See the 'Note about fast-forwards' in 'git push --help' for details
================================================================
처음에 브랜치로 커밋을 하려 했으나 강제로 푸쉬를 해도 해결이 되지 않아서 main에 커밋을 진행해왔습니다.

2. 비교처리 문제
if 조건문을 이용해서 비긴 값을 먼저 걸러내고 나머지 승패가 갈리는 경우의 값들 중 유저가 3(보)를 내고 컴퓨터가 1(가위)일 경우 유저가 승리로 넘어가는 오류가 있었습니다. 이는 처음에 3과 1 또는 1과 3의 경우를 걸러내는 절대값 조건 지정 후 Or 연산자 뒤에 추가로 유저의 패가 컴퓨터 보다 클 경우를 지정했던 것에서 우선 순위 처리가 되지 않아 발생한 오류였습니다. 그래서 else if 문을 뒤로 빼와서 따로 조건을 걸어두어 해결하였습니다.
 
### 해결되지 않은 점🥲
없습니다.

### 조언을 얻고 싶은 점😊
readline()메서드를 사용할 때 어느경우에는 let으로만 사용해도 될 때와 guard let 처럼 옵셔널 바인딩이 필요한 경우가 생기는 문제가 있었습니다. 단순하게 에러를 보고 수정을 해서 해결했지만, readline() 메서드를 사용할 때 어느 경우에 옵셔널 바인딩이 필요한지 이해가 되지 않습니다. 해당 부분과 관련되어 어떤 자료를 보는게 좋을까요?

2023-05-02 15:25 UTC, Kyeongjun2 requested changes
이디나로크, 저스버그 안녕하세요!
1주일간 묵찌빠게임 프로젝트를 함께하게 된 로웬이라고 합니다.
잘 부탁드립니다☺️

지난 프로젝트에서도 들으셨겠지만 리뷰어의 코멘트는 정답이 아닙니다! 여러분께서 작성하신 코드의 이유가 확실하다면 참고만 하고 넘어가셔도 좋습니다 👍

이번 프로젝트 기간이 서로 성장하는 시간이 되었으면 좋겠습니다. ✏️

전반적으로 코드 컨벤션도 잘 맞춰주시고, 커밋 로그 형식도 잘 맞춰주신 것 같습니다! 👏👏👏
하지만 main 파일에 아무런 타입 없이 함수로만 정의하신 것이 조금 아쉽네요.
STEP2를 진행하실 때는 적극적으로 타입을 활용해 주시면 좋을 것 같습니다. ☺️

리뷰는 아래 코멘트에서 확인해주세요 🙏

---

### 칭찬드릴 점
* 코드 전반의 컨벤션에 신경 써 주셔서 수월하게 읽을 수 있었습니다. 👍
* 스텝 구현 명세를 잘 지켜주셨습니다. 👍
* guard문을 통해 예외처리를 잘 해주셨습니다. 👍
* 프로젝트 제약 사항을 잘 지켜주셨습니다. 👍

</br>

## 💭 고민하신 부분에 대하여
> 1. push 에러
짝프로그래밍 진행 중 커밋 후 푸쉬를 진행할 때 발생한 에러 메시지 입니다.
================================================================
Updates were rejected because the tip of your current branch is behind...
its remote counterpart. integrate the remote changes (e.g.'git pull...') before pushing again
See the 'Note about fast-forwards' in 'git push --help' for details
================================================================
처음에 브랜치로 커밋을 하려 했으나 강제로 푸쉬를 해도 해결이 되지 않아서 main에 커밋을 진행해왔습니다.

정확한 상황은 제가 알 수 없지만...

로그를 읽어보니 현재 브랜치의 헤드가 원격 저장소보다 뒤에 있기 때문에 push가 거절됐다고 하네요.

원격 저장소와 변동 사항을 맞춰주기 위해서 짝프로그래밍을 진행하는 과정에 push 후 pull 받는 것을 꼭 잊지 말아주세요 😄

</br>

> 2. 비교처리 문제
if 조건문을 이용해서 비긴 값을 먼저 걸러내고 나머지 승패가 갈리는 경우의 값들 중 유저가 3(보)를 내고 컴퓨터가 1(가위)일 경우 유저가 승리로 넘어가는 오류가 있었습니다. 이는 처음에 3과 1 또는 1과 3의 경우를 걸러내는 절대값 조건 지정 후 Or 연산자 뒤에 추가로 유저의 패가 컴퓨터 보다 클 경우를 지정했던 것에서 우선 순위 처리가 되지 않아 발생한 오류였습니다. 그래서 else if 문을 뒤로 빼와서 따로 조건을 걸어두어 해결하였습니다.

절대값을 활용한 비교 방법 좋습니다 👍👍👍
Or 연산자라고 하신 부분은 논리 합 연산자 `||`가 맞을까요?
작성하신 코드에는 논리 곱 연산자 `&&`을 사용하고 계시네요.

비교 조건은 마지막에 잘 수정해주신 것 같습니다.

</br>

## 🤔 조언을 얻고 싶은 부분에 대하여
> readline()메서드를 사용할 때 어느경우에는 let으로만 사용해도 될 때와 guard let 처럼 옵셔널 바인딩이 필요한 경우가 생기는 문제가 있었습니다. 단순하게 에러를 보고 수정을 해서 해결했지만, readline() 메서드를 사용할 때 어느 경우에 옵셔널 바인딩이 필요한지 이해가 되지 않습니다. 해당 부분과 관련되어 어떤 자료를 보는게 좋을까요?

`readLine()` 함수의 공식문서를 볼까요?

### Declaration
```swift
func readLine(strippingNewline: Bool = true) -> String?
```

반환 타입이 `String?` 옵셔널이므로 readLine을 통해 얻은 값을 사용할 때, 어떤 타입으로 사용할 것인가가 중요한 부분 같습니다.

이번 프로젝트에서는 Int 타입의 이니셜라이저 파라미터로 readLine 반환 값을 전달하고 계시네요.
```swift
init?(_ description: String)
```

전달인자의 타입을 보면 `String`임을 확인할 수 있습니다.
이렇게 String? 타입 값을 String 타입으로 사용하고 싶을 때가 Optional Binding이 필요한 경우입니다.

만약, 전달인자의 타입이 `String?` 이었다면 Optional Binding을 하지 않아도 잘 전달이 되었을 거에요! ☺️

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
지난 숫자야구 프로젝트에선 Foundation 라이브러리에 대해 알아 보셨을까요?
지난 프로젝트에서 String 타입의 `component` 인스턴스 메서드를 사용하셨다면 import 하셨을거에요 🙂

이번 프로젝트에서는 Foundation 라이브러리의 어떤 기능을 사용하고 계신가요?

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userCard = Int(inputNumber) else { return }
guard let을 이용해 옵셔널 바인딩을 잘 해주셨네요 👍

참고로 각각의 guard else 구문을 통해 예외 처리 타이밍을 나누고 싶지 않으시다면 조건을 `,`로 연결할 수 있습니다 🙂
```suggestion
    guard let inputNumber = readLine(),
          let userCard = Int(inputNumber) else { return }
```

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
`inputMenu()`함수의 기능이 많아 보이네요🤔
함수/메서드는 한 가지 기능만 할 수 있는 것이 좋습니다.
inputMenu 라는 이름에 맞는 기능을 가질 수 있도록 함수 분리를 해볼까요?

---

추가로,
이 함수에서 생각해볼만한 점들을 남겨드리니 고민해보시면 좋겠습니다. ☺️

* 반복된 코드가 있는 경우, 해당 코드를 함수로 함수로 분리할 수 있습니다!
* switch case 1, 2, 3의 코드가 동일한 경우 `case 1, 2, 3:`,  `case 1...3:`처럼 연결할 수 있습니다!
* userCard를 enum으로 만드는 방법도 고려해보시면 좋을 것 같습니다.

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
`inputMenu()`는 함수 내부에서 다시 `inputMenu()`를 호출하는 재귀함수로 만들어 주셨네요.

재귀함수와 반복문의 장단점은 뭘까요? 🤔

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    } else if ((inputNumber - randomNumber).magnitude == 2) && (inputNumber == 3) {
여기에도 형태가 비슷한 코드가 보이네요 🤔
두 숫자의 차의 절대값을 비교하는 기능을 분리해보면 어떨까요?

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compareRandomNumber(_ inputNumber: Int, with randomNumber: Int) {
함수와 파라미터 이름을 정할 때, 중복되는 단어는 피하는 것이 좋다고 생각합니다.
그리고 현재 함수의 이름 `compareRandomNumber`는 무작위 숫자를 비교하는 기능을 할 것 같아요.

네이밍에 관한 내용은 프로젝트 참고 문서에 나와있는 공식문서 [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/)를 참고해주세요~!

완전히 좋은 네이밍은 아니니 참고로만 봐주세요!
위에서 `userCard`라는 이름을 사용하셨으니 이런 식으로 바꿔볼 수도 있겠네요 💭
```suggestion
func compareCard(user: Int, computer: Int) {
```

2023-05-02 15:25 UTC, Tediousday93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
절대값으로 승패를 비교하는 방법 좋습니다 👍👍👍

`compareRandomNumber` 함수도 기능이 한 가지라고 생각하기 어려울 것 같아요.
숫자 비교도 하고, 승패를 알려주는 기능도 있네요!
조금 더 세세하게 기능을 분리해보시면 좋을 것 같습니다. ☺️

2023-05-03 02:21 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
.random(), .magnitude() 메서드를 사용하고 있습니다.

2023-05-03 02:23 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userCard = Int(inputNumber) else { return }
guard문 ,이용해서 수정하였습니다.

2023-05-03 02:33 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
재귀함수는 스택메모리를 사용하기에 오버플로우가 발생할 수가 있다는 단점이 있는 반면에 코드가 간결해지는 장점이 있습니다. 반복문은 동일한 변수를 지속적으로 사용하기에 새로운 함수를 호출할 필요가 없어서 상대적으로 속도가 빠릅니다. 다만 재귀함수에 비해 가독성이 떨어지는 단점이 있습니다.

2023-05-03 02:39 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
> +    } else if ((inputNumber - randomNumber).magnitude == 2) && (inputNumber == 3) {
로웬이 말씀하신 내용을 정확히 이해한 건지는 모르겠지만 else if 안에 절대 값 조건을 따로 상수에 할당하여 수정하였습니다.

2023-05-03 02:46 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compareRandomNumber(_ inputNumber: Int, with randomNumber: Int) {
compareRandomNumber는 compareCard로 
inputNumber, randomNumber는 user, computer로 변경하였습니다.

2023-05-03 02:54 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
저희는 같은 함수 안에 숫자를 비교하고 바로 승패를 알려주도록 하는 것이 직관적이고 더욱 간결하다고 생각하는데 숫자비교와 승패출력 기능을 따로 분리하는 것이 어떤 면에서 더 좋은지 모르겠습니다. 추가로 리뷰 달아주시면 참고해서 Step2에서 따로 기능을 구현해보도록 하겠습니다.😀

2023-05-03 06:06 UTC, JusBug commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
userCard를 enum 타입으로 변경했는데 0...3 이외의 값을 입력했을 때 default로 빠지지 않고 프로그램이 바로 종료되는 문제가 있었습니다. 이 문제를 반복문 안에 try catch로 따로 구현하였으나 enum UserCardsError안에 exit을 정의한 것이 마음에 걸려서 이 부분에 대해서 조언을 얻고 싶습니다.

2023-05-03 06:54 UTC, Kyeongjun2 commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
말씀해주신 메서드는 standard library에서 제공하는 것으로 확인되네요!

"이유있는 코드"를 작성하는 것이 중요한 만큼 간단한 한 줄의 코드에도 이유가 분명히 있어야 한다고 생각해요.
Foundation을 꼭 import해야만 프로그램이 동작하는지 확인해보는 것도 좋겠습니다 ☺️

2023-05-03 06:57 UTC, Kyeongjun2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
직접 디스코드로 말씀드린 내용이네요~~

함수 / 메서드의 기능을 분리하는 이점은 각 기능을 따로따로 유지 / 보수하는 것에 용이하기 때문이라고 생각합니다.
여러가지 기능이 묶여있는 경우 전체적인 코드를 수정해야 하는 경우가 발생할 수 있을 거에요💭
다음 스텝에서 천천히 바꿔보시면 좋을 것 같습니다 !! 👍

2023-05-03 07:01 UTC, merged

2023-05-03 07:01 UTC, Kyeongjun2 commented
수고하셨습니다 🎉🎉🎉
스텝2도 화이팅!

2023-05-03 07:03 UTC, idinaloq commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
네! 저희가 찾아봤을 때 foundation에서 제공한다고 나와있었는데, 해당 기능의 추가기능 들이 제공되는 것 같네요.