[STEP 1] myungsun, yetti
yagom-academy/ios-rock-paper-scissors pull request #203
Opened 2023-05-02 07:59 UTC by myungsun7782

안녕하세요~! 해리!!
이번 묵찌빠 게임 프로젝트 리뷰를 받게 된 myungsun, yetti 입니다! 
많이 부족하지만, 리뷰 잘 부탁드리겠습니다:)
@HarryHyeon

### 고민했던 점, 어려웠던 점
- HandShape 열거형에 Int 형 정수 값을 설정할지 말지 고민했습니다. STEP1 에서 사용자한테 가위, 바위, 보 숫자를 입력받아서 원시값을 통해 열거형 케이스를 생성하려고 했습니다. 그런데, 이렇게 하면 계속 가위, 바위, 보에 대한 값을 사용할 때 옵셔널 바인딩을 통해서 값에 접근해야 한다는 불편함이 있었고, 무엇보다 STEP2에서 가위, 바위, 보에 대한 번호가 바뀌는 것을 알게 됐습니다. 그래서 STEP1에서 HandShape 열거형에 원시 값을 설정하게 된다면 STEP2에서 로직이 꼬일 거 같다는 생각이 들어 원시값을 사용하지 않고 HandShape 열거형 배열을 만들어서 인덱스를 통해 접근했습니다.
- class 내에서 캡슐화를 어떻게 해야할 지 고민했습니다. 캡슐화는 중요사항을 감추고, 외부에서 개체를 사용할 수 있는 수단을 제공하는 것이라고 어제 활동학습 시간에 배웠습니다. 그런데, 저희 코드에서 Player 클래스 안에서 currentHandShape, type 속성을 private으로 은닉하고 getCurrentHandShape, changeHandShape이라는 메서드를 통해서 외부에서 해당 속성에 접근할 수 있는 수단을 제공해주게 코드를 작성했는데 이게 캡슐화를 잘 한 것인지 잘 모르겠고, 캡슐화에 대한 개념을 코드에 적용시키기가 너무 어려웠습니다.
- git push한 파일이 변경되어 다시 pull 받을 때 에러가 발생했었습니다.
    - 해결 방안:  **git restore 파일명**(작업 트리에서 수정한 내용 되돌리기) 후 pull하여 해결하였습니다.

### 조언을 얻고 싶은 점
- 개념적으로 struct는 값 타입, 상속 불가능, 맴버 와이즈 이니셜라이저 기본 제공해준 다는 특성이 있고, class는 참조 타입, 상속 가능, 참조 카운팅 지원을 통한 메모리 관리 가능 등의 특성이 있다는 것은 알고 있는데, 실제로 상속이 필요한 경우를 제외하고, class와 struct를 고르는 기준을 잘 모르겠습니다..!

2023-05-02 16:18 UTC, HarryHyeon requested changes
안녕하세요! 예티, 명선👋👋

저는 이번에 두 분의 묵찌빠게임 프로젝트 리뷰를 맡게 된 해리입니다!!
잘 부탁드리겠습니다!

제가 드리는 리뷰는 이러한 의견이 있다는 저의 생각이니 참고해주시면 될 것 같습니다. 더 좋은 방향이 있다면 저에게도 의견을 제시해주시고 같이 소통하면서 프로젝트를 진행하면 좋을 것 같습니다 :+1: 

<br>

## 칭찬드리고 싶은 부분
- 사용자 정의 타입을 사용한 점
- 캡슐화, 은닉화에 대해서 고민한 점
- git 원격 저장소 사용의 문제를 고민하고 해결해 보신 점
- class와 struct를 선택하는 기준에 대해서 고민해 보신 점

<br>

## 고민하신 부분에 대한 의견
> ### 고민했던 점, 어려웠던 점
> - HandShape 열거형에 Int 형 정수 값을 설정할지 말지 고민했습니다. STEP1 에서 사용자한테 가위, 바위, 보 숫자를 입력받아서 원시값을 통해 열거형 케이스를 생성하려고 했습니다. 그런데, 이렇게 하면 계속 가위, 바위, 보에 대한 값을 사용할 때 옵셔널 바인딩을 통해서 값에 접근해야 한다는 불편함이 있었고, 무엇보다 STEP2에서 가위, 바위, 보에 대한 번호가 바뀌는 것을 알게 됐습니다. 그래서 STEP1에서 HandShape 열거형에 원시 값을 설정하게 된다면 STEP2에서 로직이 꼬일 거 같다는 생각이 들어 원시값을 사용하지 않고 HandShape 열거형 배열을 만들어서 인덱스를 통해 접근했습니다.
> - class 내에서 캡슐화를 어떻게 해야할 지 고민했습니다. 캡슐화는 중요사항을 감추고, 외부에서 개체를 사용할 수 있는 수단을 제공하는 것이라고 어제 활동학습 시간에 배웠습니다. 그런데, 저희 코드에서 Player 클래스 안에서 currentHandShape, type 속성을 private으로 은닉하고 getCurrentHandShape, changeHandShape이라는 메서드를 통해서 외부에서 해당 속성에 접근할 수 있는 수단을 제공해주게 코드를 작성했는데 이게 캡슐화를 잘 한 것인지 잘 모르겠고, 캡슐화에 대한 개념을 코드에 적용시키기가 너무 어려웠습니다.
> - git push한 파일이 변경되어 다시 pull 받을 때 에러가 발생했었습니다.
>   - 해결 방안: **git restore 파일명**(작업 트리에서 수정한 내용 되돌리기) 후 pull하여 해결하였습니다.

- 스텝1을 진행하면서 스텝2의 내용까지 고려하면서 하시다니 대단하신 것 같습니다👍🏼 제 개인적인 경험으로는 다음 스텝의 내용까지 고려하면서 코드를 작성하니 제한적인 부분이 많았던 것 같았습니다. 이것저것 시도해보면서 코드 작성 연습도 할겸 가볍게 하나하나 기능을 만들었을 때, 저는 더 많은 것들을 배워갔던 것 같아요! <br>
열거형의 인스턴스를 생성할 때, 옵셔널 때문에 많이 애쓰신 것 같아요. 이 부분에 대해서 저는 "굳이 값을 꺼낼 필요가 없다면, 항상 옵셔널 바인딩을 해야할까?" 라는 생각이듭니다. 단순히 비교만 할꺼면 옵셔널을 허용하고 열거형을 최대한 활용하는 (코드 가독성을 높이기 + 코드 작성의 실수를 줄이기) 것이 어떨까 하는 것이 제 생각입니다🤔

- 캡슐화와 은닉화에 대해서 많이 고민하셨군요!`GameManager` 클래스가 가지는 기능은 `startGame()`과 `getGameResult()` 라는 기능들로 추상화를 하여 제공되는 기능은 `startGame()`으로 잘 캡슐화를 하셨다고 생각합니다👍🏼 (추가로 저는 캡슐화는 정보은닉을 하기 위한 하나의 방법이될 수 있다고 생각합니다.) <br> 
제가 드린 예시가 적절했는지 확인하실 겸, 캡슐화와 은닉화의 차이에 대해서 조금 더 공부해보시면 좋을 것 같습니다.

- 👍👍👍

<br>

## 조언을 얻고 싶은 부분에 대한 의견
> ### 조언을 얻고 싶은 점
> - 개념적으로 struct는 값 타입, 상속 불가능, 맴버 와이즈 이니셜라이저 기본 제공해준 다는 특성이 있고, class는 참조 타입, 상속 가능, 참조 카운팅 지원을 통한 메모리 관리 가능 등의 특성이 있다는 것은 알고 있는데, 실제로 상속이 필요한 경우를 제외하고, class와 struct를 고르는 기준을 잘 모르겠습니다..!

- 이 부분은 저도 매번 고민하는 문제입니다. 자주 이 부분에 대해서 고민해본 결과 제 나름의 기준이 생기기도 했습니다. 두 분도 자주 이 문제에대해 부딪힐때마다 나름의 결론을 내려가면서 해결해보시면 좋을 것 같다는 생각이듭니다👍🏼  서면으로 모두 언급해드리기엔 내용이 좀 많아서 관련 문서 링크 남길게요!
    - [Struct and Classes](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures/)


### 보완하면 좋을 점
- 위에 언급드린대로 열거형을 아주 적절하게 사용하신 것 같은데, 조금 더 활용해보심이 어떨까요?
- 함수가 최대한 하나의 기능을 하도록 기능 분리를 시도해보시면 좋을 것 같습니다.

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Enums/HandShape.swift
> +}
열거형을 잘 정의하신 것 같아요👍🏼

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Enums/PlayerType.swift
> +}
👍🏼👍🏼👍🏼

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        let user: Player = Player(type: .person)
Player 타입을 통해 역할이 분리된 것이 너무 좋은 것 같아요👍🏼

다만, 타입 명이 Player라는 것을 딱 보자마자 뭔가 어색한 거 같다는 느낌이 들었습니다!
조금만 더 고민해볼까요?

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        while isGameOn {
`Bool` 타입의 변수를 이용해 반복문을 제어하셨네요 👍🏼
저도 이렇게 하는 편이 읽기가 좋아서 자주 사용하는 편입니다 !

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +            }
0~3의 값이 아닐 때 해당 문구를 출력해주고 있네요. 
중복된 출력문이라서 입력을 처리하는 부분에서 같이 해주어도 될 것 같다는 생각이 듭니다!

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +            case 1...3:
0이 무엇인지, 1...3이 무엇인지 열거형을 사용하면 좀 더 사람이 읽기 쉬운 코드가 될 것 같아요🤔
선언해두신 열거형을 적극적으로 사용해볼까요?

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                isGameOn = getGameResult(computerHandShape, userHandShape).0
튜플을 사용하셨군요👍🏼

튜플에는 원소에 이름을 줄 수 있는 `named tuple`을 사용해서 어떤 값을 나타내는지 명확하면 좋을 것 같아요🤔

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +            }
startGame()에서 분리하면 좋을 것 같은 기능이네요🤔

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +    }
조건문이 조금 길어서 가독성이 떨어진다고 느껴집니다🤔

`switch` + `enum` + `tuple` 의 조합으로 읽기 좋게 바꿔볼까요?

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/Player.swift
> +        guard let randomHandShape = handShapes.randomElement() else { return }
참고로 `CaseIterable` 이라는 프로토콜을 채택하여 해당 기능을 간단하게 구현할 수 있습니다👍🏼

2023-05-02 16:18 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                let userHandShape = handShapes[gameOptionNumber - 1]
배열 인덱스에 연산을 하고 있으시군요~

물론, 저 부분에 에러가 발생하지 않게 설계 하셨겠지만 혹여나 실수를 한다면 어떨까요?
- HandShape에 케이스가 추가된다면? -> HandShape 타입수정 + 배열 인덱스 계산 작업 등이 필요하는 부가적인 작업의 추가 발생이 생길 수도 있을 것 같습니다. 
- 입력 값 0이 가위이면? 과 같은 문제도 있을 수 있겠네요!

이외에도 다른 문제가 있을 수도 있지만 이런 부분에서 옵셔널의 안전함이 강조되는 것 같습니다👍🏼

2023-05-03 05:21 UTC, myungsun7782 commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        let user: Player = Player(type: .person)
다시 보니 Player라는 네이밍이 구체적이지 않게 느껴질 수도 있겠네요! 저희가 고민해본 결과 Player 대신 GamePlayer로 타입 명을 바꿔서 타입 의미를 더 구체화 시켰습니다.

2023-05-03 05:22 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +            }
넵! 동의합니다 :) startGame 메서드 내에서 사용자에게 입력 받는 기능 분리했습니다!

2023-05-03 05:22 UTC, myungsun7782 commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +    }
switch, enum, named tuple을 사용해서 다시 코드를 수정했습니다. 확실히 switch문과 열거형의 조합으로 코드를 작성해주니 가독성이 훨씬 좋아지네요!

2023-05-03 05:23 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                let userHandShape = handShapes[gameOptionNumber - 1]
넵! 알겠습니다. 우선 저희는 이미 유효한 값에 대해서 인덱스에 접근하는 상황이 보장이 돼서 이렇게 작성했는데, 다음에는 해리가 말씀해주신 부분도 고려해서 코드를 작성해보겠습니다!

2023-05-03 05:23 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/Player.swift
> +        guard let randomHandShape = handShapes.randomElement() else { return }
감사합니다 참고하겠습니다 !

2023-05-03 06:41 UTC, merged