묵찌빠 게임 [STEP 2] etialmoon, serena
yagom-academy/ios-rock-paper-scissors pull request #207
Opened 2023-05-03 12:52 UTC by serena0720

@gzzjk159 (vetto)
안녕하세요. Serena & etialmoon 팀입니다.
저희 가위바위보 & 묵찌빠 게임 Step2 리퀘스트 보냅니다.
리뷰 부탁드립니다.😆

## 고민한 부분
### 1. 가위바위보와 묵찌빠 함수 구조 중복
#### 전체적인 흐름이 유사한데, 세부 조건이 달라 결국 유사한 구조로 각각의 struct를 만들었습니다. - 가위바위보(FirstGame), 묵찌빠(SecondGame). 좀 더 효율적인 방법으로 코드 중복을 없앨 수 있는 방법이 있는지 궁금합니다. 😂

### 2. 전역 변수
#### 묵찌빠로 넘어갈 때 승자를 기억해야하기 때문에 `winner`라는 변수를 `Data` 파일에 전역 변수로 만들어 두었습니다. 처음에는 `FirstGame` 안에 변수 `winner`를 만들고 가위바위보의 승자가 결정 되었을 때 누가 이겼는지 `winner`에 저장한 다음 `SecondGame`으로 넘어가게 만들었습니다. `SecondGame`에서 `FirstGame`의 `winner`를 가져와 사용하려고 하니 `circular reference`라는 오류가 발생했기 때문에 전역 변수로 바꾸게 되었습니다.

### 3. 네이밍
#### 네이밍에 대한 어려움은 Step1에서도 있었지만, 수정을 반복해도 여전히 막히는 부분인 거 같습니다ㅜ 특히 Step2의 경우 전체적인 코드의 흐름이 유사하여 더더욱 이름을 정하는 것이 어려웠습니다.

### 4. 반복문과 재귀함수
#### 처음 `commit`때 `while`함수를 활용하여 조건을 반복시켰습니다. `반복문을 활용하거나 재귀함수를 사용하거나 둘의 장단점을 한 번 생각해보시는 것도 좋을 것 같습니다.` 라는 조언을 듣고 둘의 차이를 직접 느껴보고자 재귀함수를 활용하는 방향으로 수정해보았는데, 재귀함수 활용에 있어서 많은 어려움을 느꼈습니다. 특히 저희의 경우 재귀함수로 변경을 하니 반복 호출이 많아져서 반복문보다 비효율적으로 보여지고, 재귀함수의 장점을 살리지 못한 거 같아서 아쉬웠습니다.😅

### 5. .allCases.randomElement() 
####  `makeRival`함수와 `compareHand` 함수는 각각 단일의 역할이 있다 생각되어 하나로 합치기보단 나누는 게 맞다고 판단하여 나눴습니다. 이때 `makeRival`에 있는 해당 메소드를 `compareHand` 함수에서 호출할 때 에러 처리를 위해 `do-catch`를 사용하였는데, 이도 비효율적인 방법인 거 같아서 고민을 많이했지만 해결방안을 찾지 못했습니다.ㅜ

2023-05-03 22:08 UTC, gzzjk159 requested changes
step2 PR 리뷰 드립니다. 이해가 가지 않은 부분이나 궁금하신 점은 DM 보내주세요. 리팩토링도 화이팅입니다.

## 고민하신 사항
### 가위바위보와 묵찌빠 함수 구조 중복
말씀하신 부분이 정말 공감이 가는 거 같습니다. 이 고민에 대하여 제 생각에는 승부의 조건 차이(이겨야 승, 비겨야 승)와 입력의 차이(가위1바위2보3, 묵1찌2빠3)등등 사소한 차이 때문에 어쩔수 없이 새로운 함수를 작성해야한다고 생각합니다. 지금은 좋은 생각이 나지 않아 조언해드리지 못한 점 죄송합니다.

### 전역변수
저같은 경우에는 가위바위보 게임에서 위에 타입을 반환하는 함수로 만들고 반환받은 값을 이용해서 게임을 진행했었습니다.
```swift
enum Winner {
    case user
    case computer
    case draw
}
```

```swift
func startRockPaperScissorsGame() -> Winner {}
```

```swift
func runGame() {
    let winner = startRockPaperScissorsGame()
    startMookZziBbaGame(turn: winner)
}
```
시간은 충분히 남았으니 고민 많이 하시고 다양한 방법으로 시도하여 가장 만족하는 방법을 택하는 것이 좋아보이네요.

### 네이밍
저 같은 경우에는 이 프로젝트를 할 때 기준을 일단 이해하기 쉽게 풀네임으로 네이밍을 했었던 거 같네요. 예를 들면 가위바위보 게임의 승자를 결정하는 메서드라면 `decideRockPaperScissorWinner()` 이런식으로
 작성하였습니다. 네이밍같은 경우에는 정답이 없기 때문에 두분이 상의해서 이해하기 편한 이름으로 하시면 될 거 같습니다.

### 반복문과 재귀함수
두분이 반복문과 재귀함수에 대해서 이해하고 사용하면 좋을 거 같아 장단점을 생각해보시라 권유드린거였습니다. 재귀함수를 사용하면 코드의 가독성이 좋아지는 장점이 있습니다. 해당 코드에서는 그 장점이 충분히 보여지는 거 같다고 생각합니다. 만약 현재 재귀함수를 이용한 코드가 장점을 살리지 못한거 같다 생각하시면 언제든지 반복문으로 바꾸셔도 좋을 거 같아 보입니다.😀


### .allCases.randomElement()
비효율적인 방법이라고 생각하신 이유가 있을까요? 안전하게 처리하는 코드를 작성하신 것 같아보입니다. 만약 do-catch문 때문이라면 옵셔널을 이용하여 코드를 작성 해보는 것도 좋은 방법일 것 같네요.

## 칭찬 드리고 싶은 점
에러타입을 활용하여 에러처리를 하신 점👍
요구사항을 잘 지키신 점👍
파일 분리를 하신 점👍
코드 컨벤션이 확실하신 점👍

## 조언

### 브랜치
보통 step마다 브랜치를 만들어 어떤 step을 거쳐왔는지 파악할 수 있게 합니다. 현재는 main에서만 작업을 하신 거 같네요. 한번 브랜치를 만들어서 작업을 해보는 걸 추천드립니다.

### Error 파일 이름
Errors로 되어있는데 이것보단 RockPaperScissorsGameError와 같은 명칭이 더 자연스러워 보입니다.

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/Data.swift
> +//  Data.swift
주석 수정해주신 부분 좋습니다. 👍

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/Data.swift
> +enum MukjjipaOptions: String, CaseIterable {
현재는 rawValue를 사용하셨는데 연산프로퍼티라는 것도 이용할 수 있습니다.

RockPaperScissors는 대문자가 중간중간 들어가는데 Mukjjipa는 그러지 않은 거 같네요

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/FirstGame.swift
> +struct FirstGame {
순서상으로는 firstGame이 맞지만 가위바위보 게임이라는 명칭이 들어가는 것도 좋을 거 같네요.

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/FirstGame.swift
>      func startGame() {
묵찌빠는 startMukjjipa()인데 여기는 startGame()이네요.

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/SecondGame.swift
> +    private func compareTwoHand(with userHand: MukjjipaOptions) {
compareTwoHand()메서드인데 인자는 손 하나만 받는게 어색해보이네요.
```swift
compareTwoHand(user userHand: MukjjipaOptions, rival rivalHand: MukjjipaOptions) {}
```
하나의 예시입니다.

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var teamMoons = FirstGame()
var인 이유가 있나요?

변수명 teamMoons보단 좀 더 의미있는 변수명으로 지어주시는게 좋아보입니다.😀

2023-05-03 22:08 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/SecondGame.swift
> +            compareTwoHand(with: .pa)
```swift
case HandOptions.scissors.rawValue, HandOptions.rock.rawValue, HandOptions.paper.rawValue:
     compareTwoHand(with: ) // input 이용
```
요런식으로 작성할 수 있습니다. (수정은 안 하셔도 됩니다.)

2023-05-03 22:16 UTC, gzzjk159 commented on RockPaperScissors/RockPaperScissors/SecondGame.swift
> +    private func choiceMukjjipaMenu() {
접근제어자 설정하신 점 좋습니다.👍

2023-05-04 13:07 UTC, serena0720 commented on RockPaperScissors/RockPaperScissors/Data.swift
> +enum MukjjipaOptions: String, CaseIterable {
`현재는 rawValue를 사용하셨는데 연산프로퍼티라는 것도 이용할 수 있습니다.`
조언 감사합니다! 두개 비교해본 결과 현재 코드가 복잡하지 않아 rawValue를 그대로 사용하고자 합니다.

`RockPaperScissors는 대문자가 중간중간 들어가는데 Mukjjipa는 그러지 않은 거 같네요`
해당 조언 참고하여 변수, 함수, 파일 명 모두 수정하였습니다! :)

2023-05-04 13:08 UTC, hojun-jo commented on RockPaperScissors/RockPaperScissors/FirstGame.swift
> +struct FirstGame {
RockPaperScissorsGame으로 전부 변경했습니다!

2023-05-04 13:10 UTC, hojun-jo commented on RockPaperScissors/RockPaperScissors/FirstGame.swift
>      func startGame() {
`startRockPaperScissors()`로 변경했습니다!

2023-05-04 13:26 UTC, serena0720 commented on RockPaperScissors/RockPaperScissors/SecondGame.swift
> +            compareTwoHand(with: .pa)
조언 감사합니다~!

2023-05-04 13:26 UTC, serena0720 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var teamMoons = FirstGame()
처음에 `let`으로 선언하였다가 중간에 순환구조에 빠지면서 `var`로 임시 수정했던 부분을 놓치고 수정을 안했습니다ㅜ! 꼼꼼히 확인해주셔서 감사합니다!

저희 닉네임에 달이라는 뜻이 겹쳐서 `teamMoons`로 설정하였는데, 좀 더 게임스러운 이름 `funnyGame`으로 수정하였습니다! :)

2023-05-04 13:27 UTC, hojun-jo commented on RockPaperScissors/RockPaperScissors/SecondGame.swift
> +    private func compareTwoHand(with userHand: MukjjipaOptions) {
이번 수정 이후 `rivalHand`가 `createRival()`의 리턴값으로 옵셔널로 받게 됩니다. 그래서 함수 내부에서 옵셔널 바인딩을 하는 것은 똑같은 것같아 인자는 하나로 두고 함수 명을 바꾸기로 했습니다. 함수 명이 두 개를 비교하는 뜻을 갖고 있어서 혼란이 온듯하여 함수명을 `decideVictory`로 수정하였습니다.

2023-05-06 14:41 UTC, merged