묵찌빠 게임 [STEP 2] yy-ss99, Hemg
yagom-academy/ios-rock-paper-scissors pull request #208
Opened 2023-05-03 15:06 UTC by hemg2

@Rhode-park 
안녕하세요. `로데`! 4조 `yy-ss99`, `Hemg` 입니다.
어느덧 STEP2을 진행 하게 되었습니다.!
확인 부탁드립니다.
감사합니다!

### 고민 했던점
- 가위바위보 를 그대로 쓸수 있을까라는 생각을 했었습니다.  하지만 기존 가위바위보에서 첫게임에 조건으로 사용 되다보니 중복 사용이 어렵다는걸 알게 되어 `enum`가위바위보 와  `enum`  묵찌빠 2개의 열거형을 만들어 2가지의 게임을 진행 할 수 있게 했습니다.
- 처음 가위바위보에서 묵찌빠 게임을 넘어가기 위해 `extension` 을 사용하여 진행 하려고했습니다. 하지만 이렇게 되면 하나의 객체에 2가지의 게임을 진행하는거라고 생각되어 객체를 추가하여 각각의 게임을 진행하는 객체를 만들었습니다.
- 사용자 턴 컴퓨터 턴이 나눠져서 게임이 진행 되기에 user, computer 함수를 나누어 조건을 해야 겠다는 생각으로 함수 2가지에 대해서 로직을 구현 하던중에 하나의 함수에서도 가능해졌습니다. checkMuckJjiBbaGameResult 라는 함수 내에서 user 값으로 swich 문을 사용해서 컴퓨터 or 사용자 승리에 맞게 변경 하도록 진행했습니다.
- 최대한 기능 분리를 할 수 있게 노력해봤습니다

```swift
private func checkMuckJjiBbaTurn(with userInput: String, _ computerInput: String) -> GameResult {
        switch (userInput, computerInput) {
        case (MuckJjiBbaSign.jji.rawValue, MuckJjiBbaSign.bba.rawValue),
            (MuckJjiBbaSign.muck.rawValue, MuckJjiBbaSign.jji.rawValue),
            (MuckJjiBbaSign.bba.rawValue, MuckJjiBbaSign.muck.rawValue):
            return .win
        default:
            return .lose
        }
    }
```

### 조언을 얻고 싶은 부분
- `class` 를 사용해서 상속을 통하여 묵찌빠 게임을 진행 했었어도 될꺼라는 생각을 했습니다. 허나 상속을 하면서 솔리드원칙에 의해서 객체를 만들어야하는데 이부분에 대해서 잘 모르기에 진행 하지 못했습니다. 솔리드 원칙에 대한 자료 부분을 얻을 수 있을까요?? (혹시라도 알고있는 부분을 알려주신다면 정말 감사할꺼같습니다.)

2023-05-04 14:26 UTC, Rhode-park requested changes
안녕하세요 `와이`, `Hemg` 이번 리뷰는 각각 달린 리뷰 뿐만 아니라 이 리뷰도 잘 읽어주셔야 합니다. 코멘트가 달리지 않은 부분들이 있어 이쪽으로 빼두었어요. 보면서 이해가 되지 않는 부분 있으면 DM으로 문의 해주세요. 그럼 이번 프로젝트도 화이팅입니다. 

## 조언을 얻고 싶은 부분에 대한 제 생각
> class 를 사용해서 상속을 통하여 묵찌빠 게임을 진행 했었어도 될꺼라는 생각을 했습니다. 허나 상속을 하면서 솔리드원칙에 의해서 객체를 만들어야하는데 이부분에 대해서 잘 모르기에 진행 하지 못했습니다. 솔리드 원칙에 대한 자료 부분을 얻을 수 있을까요?? (혹시라도 알고있는 부분을 알려주신다면 정말 감사할꺼같습니다.)

SOLID원칙은 비단 swift에만 해당하는 개념이 아니기 때문에 공식 문서가 따로 없는 것 같습니다. [위키백과 - SOLID (객체 지향 설계)](https://ko.wikipedia.org/wiki/SOLID_(%EA%B0%9D%EC%B2%B4_%EC%A7%80%ED%96%A5_%EC%84%A4%EA%B3%84))를 한 번 살펴보세요. 그래도 부족하다면 관련 키워드로 검색을해보세요. 
처음부터 SOLID원칙을 모두 지키려고 하지 않으셔도 됩니다. 그래도 차근차근 프로젝트를 해나가면서 지키고 싶으시다면, 하나의 원칙만을 정해 그 원칙만큼은 반드시 지키는 방향으로 학습해보심이 어떨까요? SOLID원칙은 막상 적용하려고 하면 한 번에 모두 적용하기 어려운 경우가 많거든요.


## 제안드리고 싶은 부분
### 반복되는 print문 하나로 합치기
묵찌빠게임에서 비슷한 print문이 반복되는 상황들이 있습니다. 이 부분을 짧게 한 번의 print로 개선해 볼 수 있을 것 같은데요. rawValue와 문자열 보간법을 사용하면 좋을 것 같습니다. 한 번 해볼까요?

### getUserInput 메서드 관련(이 부분 코드에 코멘트를 달 수가 없어 따로 뺍니다)
```swift=
private func getUserInput(_ userInput: String, _ computerInput: String) {
        switch userInput {
        case HandSign.scissors.rawValue,
            HandSign.rock.rawValue,
            HandSign.paper.rawValue:
            let gameResult = checkRockPaperScissors(with: userInput, computerInput)
            showGameResult(gameResult)
        default:
            print("잘못된 입력입니다. 다시 시도해주세요.")
            showGameMenu()
        }
```
 - line1: 네이밍이 메서드의 기능과 일치하지 않는 것 같아보입니다. 해당 메서드는 어떤 기능을 하고 있나요? 제가 보기에는 각각의 가위바위보 손을 받고, user의 값이 제대로 된 값일 때 다음 단계로 넘어가는 메서드처럼 보입니다. 그런데, `getUserInput`이라고 하니 user의 입력값을 받아오는 것처럼보입니다.
 - line1: 그리고, swift에서는 보통 `get`으로 시작하는 메서드 만들길 꺼려하는 것 같습니다. 관련한 공식문서를 찾지는 못했습니다만, 다음과 같은 이유에서라고 생각합니다. 1. get이라는 단어가 가진 포괄성때문 2. swift의 예약어를 포함하여 메서드 이름 짓기를 피하기 위함. 자세한 이유는 저도 확실하게 알지는 못하지만, `get`으로 시작하는 메서드를 잘 만드는 편은 아닙니다.
 - line2: Switch문과 If문은 각각 어떤 상황에서 쓰면 좋을까요? 가독성을 높이기 위해 두 가지를 적절히 잘 구분해 쓰셔야할 것 같습니다. 만약에 `HandSign`의 case별로 다른 코드를 짜게 된다면 switch를 사용하는게 적절했을 것 같습니다. 그러나, 지금 이 상황은 두 가지 상황으로 나뉘네요? `userInput`이 `HandSign`의 rawValue에 해당하는 경우와 그렇지 않은 경우. 그렇다면, if문을 통해 `userInput`이 `HandSign`의 rawValue에 해당하는지를 확인해서 분기처리하는게 좋지 않을까요?
 - line6: 게임은 가위바위보에서 끝나는게 아니라 묵찌빠까지 이어져야 승부를 볼 수 있습니다. gameResult라고 하면 전체적인 게임의 승패가 정해진 것처럼 보입니다.
 - line8: 모든 switch문은 exhaustive해야하죠! LGTM👍🏻

<br/>

### checkRockPaperScissors 메서드 관련(이 부분 코드에 코멘트를 달 수가 없어 따로 뺍니다)
```swift=
private func checkRockPaperScissors(with userInput: String, _ computerInput: String) -> GameResult {
        switch (userInput, computerInput) {
        case (userInput, computerInput) where userInput == computerInput:
            return .draw
        case (HandSign.scissors.rawValue, HandSign.paper.rawValue),
            (HandSign.rock.rawValue, HandSign.scissors.rawValue),
            (HandSign.paper.rawValue, HandSign.rock.rawValue):
            return .win
        default:
            return .lose
        }
```
 - line1: `userInput` 앞에는 with이 `computerInput`앞에는 _가 있는 이유는 무엇일까요? with라는 전치사의 사용이 가독성을 향상시키는 것 같지 않아요.
 - line3: where를 사용해주셨네요. LGTM👍🏻 where문은 어떨 때 사용되나요?
 - line7: rawValue를 하나하나 붙여주고 있네요? 어떤 방법을 사용하면 이 부분의 코드를 줄일 수 있을까요? 지금은 파라미터로 각각 String을 받고 있는데 대신에 HandSign을 각각 받아오면 코드가 어떻게 바뀔까요?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
>  //  Created by yyss99 on 2023/05/03.
팀원 두 분의 이름을 같이 써주시면 좋겠습니다. `Created by yyss99, Hemg` 이렇게요. 다른 파일들도 마찬가지입니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
>      func showGameMenu() {
기능 분리가 덜 된 느낌입니다. showGameMenu라고 네이밍을 하였지만, 이 메서드는 어떤 기능들을 하고 있나요? 게임메뉴를 보여주는 기능, user의 선택을 받는기능, 받은 user의 선택이 0인지 아닌지 판단하는 기능 등이 들어가있습니다. 과연 기능분리가 이게 최선이었나요? 기능분리가 이게 최선이었다면 메서드의 네이밍은 어떻게 되어야할까요? 단순히 게임의 메뉴를 보여주는데에서 그치지 않고 있는데 말이죠.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
>          print("가위(1), 바위(2), 보(3)! <종료 :0> : ", terminator: "")
이 부분이 `showGameMenu`에 해당하는 부분이겠죠?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
>          guard userInput != "0" else { return print("게임종료") }
print라는 메서드를 return 해주고 있는게 어색해보입니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
> +        let computerInput = makeComputerInput()
짝을 맞추기 위해서 computerInput이라고 하였네요. 통일성을 주어 가독성이 더 좋아보여요! LGTM👍🏻 그런데, 컴퓨터가 `input`을 해주고 있는게 맞나요? 네이밍이 조금 어색한 것 같습니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
>      private func makeComputerInput() -> String {
마찬가지로 네이밍이 조금 어색한 것 같습니다. 컴퓨터가 `input`을 해주고 있는게 맞나요?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +struct MuckJjiBba {
별도의 struct를 만들어주셨군요! LGTM👍🏻

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    func getUserMuckJjiBbaInput(when userGameResult: GameResult) {
`userGameResult`라는 네이밍이 어색합니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    func getUserMuckJjiBbaInput(when userGameResult: GameResult) {
마찬가지로 기능분리가 필요해보입니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("[사용자 턴] 묵(1), 찌(2), 빠(3)! <종료: 0> : ", terminator: "")
코드 전체적으로 사용자, 컴퓨터라는 텍스트만 바뀌고 코드가 반복되네요. 그리고 이 텍스트들은 특정 조건에서 사용되고 있어요. `GameResult`가 `.win`일 경우 사용자라는 텍스트가 사용되고, `.lose`일 경우 컴퓨터라는 텍스트가 사용됩니다. 어떻게하면, 코드를 효과적으로 줄일 수 있을까요?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        guard userInput != "0" else { return print("게임 종료") }
마찬가지로 print라는 메서드를 return 해주고 있는게 어색해보입니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        let computerInput = makeComputerInput()
마찬가지로 네이밍이 어색합니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkValidInput(with userInput: String, _ computerInput: String, _ gameResult: GameResult) {
마찬가지로 with라는 전치사의 사용이 가독성을 향상시키는 것 같지 않아요.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        switch userInput {
여기도 마찬가지로 분기처리 방법에 대해서 다시 생각해봐야할 것 같습니다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaGameResult(with userInput: String, _ computerInput: String, gameResult: GameResult) {
마찬가지로 with라는 전치사의 사용이 가독성을 향상시키는 것 같지 않아요.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("사용자 승리!")
어떻게 하면 사용자 승리와 컴퓨터 승리를 하나의 코드로 프린트 할 수 있을까요?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaTurn(with userInput: String, _ computerInput: String) -> GameResult {
네이밍이 어색해요. check~Turn인데, Turn을 체크하고 있지 않네요?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaTurn(with userInput: String, _ computerInput: String) -> GameResult {
기능 분리가 되면 좋을 것 같아요. 이 메서드의 기능은 turn을 프린트 해주고, gameResult를 바꿔주는 기능이네요. 조금 더 쪼개볼까요?

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaTurn(with userInput: String, _ computerInput: String) -> GameResult {
마찬가지로 with라는 전치사의 사용이 가독성을 향상시키는 것 같지 않아요.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        switch (userInput, computerInput) {
분기처리 고민해봅시다.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("사용자의 턴입니다.")
변수를 통해 `.win`인지 `.lose`인지를 담아놓으면 어떨까요? 그런 방식을 사용하면 반복되는 코드를 줄일 수 있을 것 같습니다. 위에서부터 일관되게 `.win`일 경우 사용자라는 텍스트가 사용되고, `.lose`일 경우 컴퓨터라는 텍스트가 사용된다는 공통점이 있으니까요.

2023-05-04 14:26 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBbaSign.swift
> +    case muck = "1"
rawValue를 사용해주셨군요. LGTM👍🏻

2023-05-05 07:45 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors.swift
>      func showGameMenu() {
피드백 반영하여 수정 진행했습니다. 확인 부탁드려요!!

2023-05-05 07:46 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors.swift
>          print("가위(1), 바위(2), 보(3)! <종료 :0> : ", terminator: "")
네 기능분리를 진행했습니다

2023-05-05 07:48 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors.swift
> +        let computerInput = makeComputerInput()
네이밍 수정하였습니다

2023-05-05 07:49 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors.swift
>      private func makeComputerInput() -> String {
네이밍 변경진행 했습니다.  `computerInput` -> `computerHandSign`

2023-05-05 07:49 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    func getUserMuckJjiBbaInput(when userGameResult: GameResult) {
네이밍 변경하였습니다

2023-05-05 07:50 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    func getUserMuckJjiBbaInput(when userGameResult: GameResult) {
`RockPaperScissors` 객체와 동일하게 기능 분리 진행했습니다.!

2023-05-05 07:51 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("[사용자 턴] 묵(1), 찌(2), 빠(3)! <종료: 0> : ", terminator: "")
문자열 보간법과 rawValue를 활용해서 바꾸어 봤습니다!

2023-05-05 07:51 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        let computerInput = makeComputerInput()
앞의 코멘트와 같이 변경 진행했습니다! (감사합니다.)

2023-05-05 07:52 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaGameResult(with userInput: String, _ computerInput: String, gameResult: GameResult) {
수정 했습니다!

2023-05-05 07:52 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        switch userInput {
분기 처리 진행했습니다. 확인 부탁드립니다~!

2023-05-05 07:53 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("사용자 승리!")
문자열 보간법과 rawValue를 활용해서 바꾸어 봤습니다!

2023-05-05 07:53 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaTurn(with userInput: String, _ computerInput: String) -> GameResult {
수정했습니다!

2023-05-05 07:54 UTC, hemg2 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +    private func checkMuckJjiBbaTurn(with userInput: String, _ computerInput: String) -> GameResult {
네이밍 변경하고 기능 변경 진행 해 봤습니다.

2023-05-05 07:55 UTC, yy-ss99 commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("사용자의 턴입니다.")
변수를 사용하진 않았지만 턴을 print해주는 함수를 따로 만들었습니다!

2023-05-05 08:00 UTC, yy-ss99 commented
line3: where를 사용해주셨네요. LGTM👍🏻 where문은 어떨 때 사용되나요?
-> case 이후에 조건을 추가할 때 쓰인다고 알고 있습니다.

line7: rawValue를 하나하나 붙여주고 있네요? 어떤 방법을 사용하면 이 부분의 코드를 줄일 수 있을까요? 지금은 파라미터로 각각 String을 받고 있는데 대신에 HandSign을 각각 받아오면 코드가 어떻게 바뀔까요?
->매개변수 타입을 String에서 HandSign으로 변경하여 활용해 보았습니다. 훨씬 간결해지고 가독성이 높아졌습니다.

2023-05-05 12:05 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors.swift
>          guard userInput != "0" else { return print("게임종료") }
return 뒤의 print문을 빼셨네요. 그 결과 종료할 때 종료 문구가 나오지 않고 있습니다. 요렇게 작성해보면 어떨까요?

```swift
guard let userInput = readLine(),
      validate(userInput) else {
    print("게임종료")
    return
}
```

2023-05-05 12:14 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +            print("[사용자 턴] 묵(1), 찌(2), 빠(3)! <종료: 0> : ", terminator: "")
잘 바꾸어주셨네요! 한 마디만 덧붙이자면, 사실 win의 rawValue가 사용자, lose의 rawValue가 컴퓨터인 것은 조금 어색한 것 같아요. 만약에 타입의 이름이 Winner이고 case로 user, computer, nowinner 등을 들고 있었다면 각각의 rawValue에 더 적합한 네이밍이 되었겠죠? 지금도 잘 하신 것 같아요. 참고만 해주세요.

2023-05-05 12:15 UTC, Rhode-park commented on RockPaperScissors/RockPaperScissors/MuckJjiBba.swift
> +        guard userInput != "0" else { return print("게임 종료") }
이 부분도 요렇게 작성해보면 되겠지요?

```swift
guard let userInput = readLine(),
      validate(userInput) else {
    print("게임종료")
    return
}
```

2023-05-05 12:32 UTC, Rhode-park commented
## 참고만 해주세요.
### checkMuckJjiBbaGameResult의 로직
요렇게 사용하는 방법도 있을 것 같습니다.
```swift
private func checkMuckJjiBbaGameResult(_ userInput: MuckJjiBbaSign, _ computerInput: MuckJjiBbaSign, _ gameResult: GameResult) {
    if userInput == computerInput {
        print("\(gameResult.rawValue) 승리!")
    } else {
        let result = changeMuckJjiBbaTurn(userInput, computerInput)
        showPlayerTurn(result)
        startGame(result)
    }
}
private func changeMuckJjiBbaTurn(_ userInput: MuckJjiBbaSign, _ computerInput: MuckJjiBbaSign) -> GameResult {
    if (userInput == .jji && computerInput == .bba) ||
        (userInput == .muck && computerInput == .jji) ||
        (userInput == .bba && computerInput == .muck) {
        return .win
    } else {
        return .lose
    }
}
private func showPlayerTurn(_ gameResult: GameResult){
    print("\(gameResult.rawValue)의 턴")
}
```
이러면 `changeMuckJJiBbaTurn()`을 통해 반환한 `GameResult`를 `showPlayerTurn()`에서도 사용할 수 있고, `startGame()`에서 사용할 수도 있죠. 그리고 `changeMuckJJiBbaTurn()` 안에 두 번의 `showPlayerTurn()`를 호출할 필요도 없구요. 

### 묵찌빠 진행 기준
`와이`와 `Hemg`네는 묵찌빠 진행 기준이 지금 `GameResult`네요. 그런데, 기준이 `GameResult`가 아닌 `Winner`면 코드가 어떻게 흘러갈까요? 어떤 장점이 있을까요?
1. enum타입에서 네이밍과 rawValue가 더 적절한 짝을 찾게 됩니다.
2. `changeMuckJjiBbaTurn`에서 메서드 이름과 반환값이 더 부합하게 됩니다.(Winner를 반환->누구의 턴인지를 반환)

대충 생각하면 요 정도 장점이 있을 것 같습니다. 꼭 진행 기준이 `Winner`여야한다는 것은 아닙니다. 그렇게 했을 때에 아쉬운 점이 있을 수도 있고요. 이런 방법도 있구나~하고 받아들여주시면 감사하겠습니다.

한 주 동안 수고 많으셨습니다. 제가 추가로 달아드린 코멘트 한 번 읽어보세요. 읽어보시고 나서 말씀해주시면 머지해드리겠습니다.

2023-05-05 12:52 UTC, merged