묵찌빠 게임 [STEP2] myungsun, Yetti
yagom-academy/ios-rock-paper-scissors pull request #210
Opened 2023-05-04 08:26 UTC by myungsun7782

안녕하세요~! 해리 :)
STEP1 리뷰 꼼꼼하게 해주셔서 정말 감사합니다!
STEP2에서 저와 예티가 많이 고민을 하고 코드를 작성했습니다!
STEP2도 리뷰 잘 부탁드리겠습니다!
@HarryHyeon

### 코드를 작성하면서 고민했던 점과 어려웠던 점
- startGame이라는 메서드 내부에서만 게임이 동작 될 수 있게 각각의 가위바위보와 묵찌빠 메서드를 startGame 메서드로 넣어주면서도 필요한 변수들을 최대한 지역변수로만 사용하기 위해 고민하였습니다. 최종적으로 가위바위보 메서드의 반환 값을 튜플로 주면서 바인딩하고 묵찌빠 메서드의 매개변수로 넣어주는 로직을 startGame 메서드 내부에 구현하는 것을 코드를 작성했습니다.
- 해리가 STEP1 에서 피드백 해준 '기능 분리' 하는 것에 고민을 많이 했고 정말 어려웠던 거 같습니다. 처음에는 getGameResult 메서드에서 사용자의 손 모양과 컴퓨터의 손 모양을 받아서 비교를 해주는 로직과 결과를 반환하는 로직이 합쳐져 있었는데, 지금은 사용자의 손 모양과 컴퓨터의 손 모양을 받아서 비교를 해주는 메서드를 만들어서 getGameResult 메서드에서 해당 메서드를 호출하고, 호출한 결과에 따라 값을 반환해주는 것으로 기능 분리를 했습니다. 이 외에도 묵찌빠 게임을 실행하는 메서드 내에서 묵찌빠 게임 승자를 보여주는 기능과 현재 누구의 턴인지를 보여주는 기능도 따로 분리했고, 사용자에게 입력을 받는 메서드 내에서도 게임 유형에 따라서 콘솔 창에 메시지를 다르게 보여주는 기능도 분리하여 코드를 작성했습니다.
- STEP2 묵찌빠 게임에서 구현해야 하는 기능이 가위, 바위, 보에서 게임에서 구현해야 하는 기능과 비슷한 것들이 많아서 최대한 기존에 작성한 코드를 '재사용'해서 작성하려고 고민을 많이 했습니다. 사용자에게 입력을 받아 콘솔에 메시지를 띄워주는 기능은 가위, 바위, 보에서도 필요하고, 묵찌빠 게임에서도 필요했습니다. 그런데, 묵찌빠 게임에서는 메시지를 출력하는 동시에 현재 누구의 턴 인지까지 보여줘야 했습니다. 그래서 저희는 현재 누구의 턴인지를 의미하는 파라미터의 기본 값을 nil로 설정해서 가위, 바위, 보 게임에서는 해당 파라미터 값을 받지 않도록 설정하고 기존 메서드를 그대로 재사용했습니다. 또한, 각 게임에서 결과를 튜플 형태로 반환해주는 메서드에서 누가 이겼는 지를 나타내는 값을 추가해서 묵찌빠 게임에서도 해당 메서드를 재사용해서 게임 결과를 얻을 수 있었습니다.
- 순환함수(재귀 함수)가 저희에게 아직 낯설고 어려워서 적용은 못 했지만, 순환함수(재귀 함수)와 반복문에 장, 단점에 대해서 알아 봤습니다. 순환함수(재귀 함수)의 장점은 수학적 정의와 유사한 형태로 코드를 표현할 수 있고, 문제를 작은 단위로 나눠 해결하는 접근 방식으로, 복잡한 문제를 해결하는 데 도움이 될 수 있다는 것이고, 단점은 재귀 호출이 깊어지면 스택 오버 플로우를 발생시켜 메모리 문제가 발생할 수 있다는 것입니다. 반면, 반복문은 재귀 함수보다 실행 시간이 빠르 스택 오버플로우의 위험이 적다는 장점이 있습니다. 하지만, 이중-삼중 반복문을 사용할 경우 코드가 길어지거나 복잡해져서 가독성이 떨어질 수 있는 단점이 있습니다.

### 조언이 필요한 점
- 한 개의 메서드에서 기능을 분리해서 다른 메서드로 빼는 작업이 매번 쉽지 않은데, 메서드의 기능 분리를 할 때 해리 만의 노하우가 있을까요?
- 페어 프로그래밍을 작성할 때 팀원이 작성한 로직에 제가 생각한 로직을 합쳐서 작성하는 부분이 쉽지 않았습니다. 기본적인 실력에 차이가 있는 팀원과의 페어 프로그래밍 방식을 좀 더 다른 방식으로 가져갈 수 있는 방법이 있을까요?

2023-05-04 15:44 UTC, HarryHyeon requested changes
예티, 명선 이번 스텝에도 수고 많으셨습니다:clap: 

코드 컨벤션을 잘 지키려고 많이 노력하신 것 같아요👍🏼
지난 스텝에도 그렇고 전체적으로 고민을 많이 한 코드라고 느껴져서 저도 많이 배우는 것 같습니다

## 칭찬드리고 싶은 부분
- 메서드의 재사용, 메서드가 하나의 기능을 가지게 하고자 기능 분리에 대해 고민하신 점
- 순환함수, 재귀함수의 장단점에 대해서 생각해보신 점
- 정상적인 결과를 출력하는 콘솔 앱을 만드신 점
- 커밋 메시지, 커밋 분기 👍🏼👍🏼

## 고민하신 부분에 대한 의견
> ### 코드를 작성하면서 고민했던 점과 어려웠던 점
> - startGame이라는 메서드 내부에서만 게임이 동작 될 수 있게 각각의 가위바위보와 묵찌빠 메서드를 startGame 메서드로 넣어주면서도 필요한 변수들을 최대한 지역변수로만 사용하기 위해 고민하였습니다. 최종적으로 가위바위보 메서드의 반환 값을 튜플로 주면서 바인딩하고 묵찌빠 메서드의 매개변수로 넣어주는 로직을 startGame 메서드 내부에 구현하는 것을 코드를 작성했습니다.
> - 해리가 STEP1 에서 피드백 해준 '기능 분리' 하는 것에 고민을 많이 했고 정말 어려웠던 거 같습니다. 처음에는 getGameResult 메서드에서 사용자의 손 모양과 컴퓨터의 손 모양을 받아서 비교를 해주는 로직과 결과를 반환하는 로직이 합쳐져 있었는데, 지금은 사용자의 손 모양과 컴퓨터의 손 모양을 받아서 비교를 해주는 메서드를 만들어서 getGameResult 메서드에서 해당 메서드를 호출하고, 호출한 결과에 따라 값을 반환해주는 것으로 기능 분리를 했습니다. 이 외에도 묵찌빠 게임을 실행하는 메서드 내에서 묵찌빠 게임 승자를 보여주는 기능과 현재 누구의 턴인지를 보여주는 기능도 따로 분리했고, 사용자에게 입력을 받는 메서드 내에서도 게임 유형에 따라서 콘솔 창에 메시지를 다르게 보여주는 기능도 분리하여 코드를 작성했습니다.
> - STEP2 묵찌빠 게임에서 구현해야 하는 기능이 가위, 바위, 보에서 게임에서 구현해야 하는 기능과 비슷한 것들이 많아서 최대한 기존에 작성한 코드를 '재사용'해서 작성하려고 고민을 많이 했습니다. 사용자에게 입력을 받아 콘솔에 메시지를 띄워주는 기능은 가위, 바위, 보에서도 필요하고, 묵찌빠 게임에서도 필요했습니다. 그런데, 묵찌빠 게임에서는 메시지를 출력하는 동시에 현재 누구의 턴 인지까지 보여줘야 했습니다. 그래서 저희는 현재 누구의 턴인지를 의미하는 파라미터의 기본 값을 nil로 설정해서 가위, 바위, 보 게임에서는 해당 파라미터 값을 받지 않도록 설정하고 기존 메서드를 그대로 재사용했습니다. 또한, 각 게임에서 결과를 튜플 형태로 반환해주는 메서드에서 누가 이겼는 지를 나타내는 값을 추가해서 묵찌빠 게임에서도 해당 메서드를 재사용해서 게임 결과를 얻을 수 있었습니다.
> - 순환함수(재귀 함수)가 저희에게 아직 낯설고 어려워서 적용은 못 했지만, 순환함수(재귀 함수)와 반복문에 장, 단점에 대해서 알아 봤습니다. 순환함수(재귀 함수)의 장점은 수학적 정의와 유사한 형태로 코드를 표현할 수 있고, 문제를 작은 단위로 나눠 해결하는 접근 방식으로, 복잡한 문제를 해결하는 데 도움이 될 수 있다는 것이고, 단점은 재귀 호출이 깊어지면 스택 오버 플로우를 발생시켜 메모리 문제가 발생할 수 있다는 것입니다. 반면, 반복문은 재귀 함수보다 실행 시간이 빠르 스택 오버플로우의 위험이 적다는 장점이 있습니다. 하지만, 이중-삼중 반복문을 사용할 경우 코드가 길어지거나 복잡해져서 가독성이 떨어질 수 있는 단점이 있습니다.

- 자세한 이유는 모르겠지만, 지역변수로만 사용한 이유가 있을 것 같은데 궁금하네요🤔

- 개인적으로 게임 유형에따라 출력문이 달라지는 부분을 분리한 것은 너무 좋은 것 같습니다!

- 재사용에 대해 많이 고민하셨군요! 공통적으로 사용할 수 있는 메서드들을 재사용한 것이 정말 효율적인 것 같습니다. 한 가지 눈에 보이는 것은 **startRockPaperScissors(), startMukChiPa()** 메서드에서 게임에 필요한 값들을 지역변수로 사용하는 것이 문제는 없지만 두 메서드간에 중복된 변수가 많은 느낌이 들기도 합니다.

  이 부분을 어떻게 해결하면 좋을까요? 제 의견은 가위바위보와 묵찌빠가 가지는 속성들을 타입으로 분리하거나 프로퍼티로 선언하는 것이 하나의 방법이 될 수 있겠네요. 다른 아이디어가 있다면 저한테도 알려주세요🤔

- 재귀함수, 반복문 비교 👍🏼👍🏼👍🏼


## 조언을 얻고 싶은 부분에 대한 의견
> - 한 개의 메서드에서 기능을 분리해서 다른 메서드로 빼는 작업이 매번 쉽지 않은데, 메서드의 기능 분리를 할 때 해리 만의 노하우가 있을까요?
> - 페어 프로그래밍을 작성할 때 팀원이 작성한 로직에 제가 생각한 로직을 합쳐서 작성하는 부분이 쉽지 않았습니다. 기본적인 실력에 차이가 있는 팀원과의 페어 프로그래밍 방식을 좀 더 다른 방식으로 가져갈 수 있는 방법이 있을까요?

- 저는 해당 타입이 해야하는 역할에 대해서 생각하는 편입니다. 물론, 여러가지 고려해야될 사항이 많겠지만 우선 타입이 해야하는 역할에 대해서 생각해보고 새로운 타입으로 분리가 필요하다면 분리를 하는 편입니다.
또, 타입 내에서는 해당 기능이 가지는 역할에 대해서 세분화해서 생각해봅니다. 그 과정에서 재사용 가능한 공통분모가 있는 기능은 하나의 기능으로 분리하는 편입니다. 그리고 최대한 하나의 메서드에서 하나의 기능을 할 수 있도록 하는 편입니다. 

  질문 주신 내용은 앞으로도 꾸준히 고민해야 될 문제라고 생각합니다. 저도 많이 어려운 부분 중에 하나입니다. 고민하고 많은 코드를 작성하고 경험을 쌓다보면 아마 자신만의 기준이 생기지 않을까요?
  
- 짝 프로그래밍에서 어려움이 있으신 것 같아요. 짝 프로그래밍 방식에는 기본적으로 적용되는 룰이 있기때문에 룰 변경에 허용되는 범위가 있을 것 같습니다.
실력 차이가 얼만큼인지는 잘 모르겠지만, 제 생각엔 잘 하시는 분이 어려워하시는 분을 알려주면서 하는 것도 서로에게 많은 도움이 될 것 같아요.

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Enums/GameType.swift
> +}
GameType 통해 2가지 게임에 대한 다른 처리를 하셨네요👍🏼👍🏼

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Enums/GameResult.swift
> +}
GameResult 타입 덕분에 결과를 알아보기 쉬운 것 같아요👍🏼👍🏼

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                    return
들여쓰기 관련 요구사항에 벗어난 것 같아요~
이 부분은 수정이 필요해보입니다 !

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +    private func showGameMessageWith(_ gameType: GameType, _ currentTurnOwner: PlayerType?) {
메서드명 마지막에 전치사가 들어가서 어색해보입니다🤔
전치사는 전달인자 레이블로 활용하는 것이 더 좋아보여요!

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +    }
게임 타입에 따라 다른 출력문 👍🏼👍🏼

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +    private func compareHandShapeWith(_ computerHandShape: HandShape, _ userHandShape: HandShape) -> GameResult {
전치사는 전달인자 레이블로 활용하는 것이 좋아보입니다 🤔

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +            guard let computerHandShape = computer.getCurrentHandShape() else { continue }
이 부분의 중복되는 기능도 하나의 기능으로 분리할 수 있을 것 같아요 🤔
좀 더 고민해보시면 좋을 것 같습니다 !

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        print("\(currentTurnOwner.rawValue)의 승리!")
열거형의 원시 값을 콘솔 출력을 위해 사용하셨네요🤔
저는 원시 값은 해당 열거형 인스턴스 생성하기 위해 그 케이스를 대표하는 값이라고 생각합니다.
문자열이 필요하다면 열거형 내의 연산 프로퍼티를 선언해 주로 사용하는 편입니다 !

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        var isGameOn: Bool = true
어떤 이유에서 지역변수/상수 로만 사용하는 것을 고민했는지 궁금합니다!

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
>                  print("\(resultMessage)")
문자열 보간법을 사용할 필요가 없어 보입니다🤔

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        var isGameOn: Bool = true
startRockPaperScissors()에서는 endOption 선언이 없었는데 묵찌빠에서만 사용하는 이유가 있을까요?
특별한 이유가 없다면 둘 중 하나로 통일해 주는 것이 좋아 보입니다🤔

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                isGameOn = !getGameResult(computerHandShape, userHandShape).isGameOn
가위바위보 게임과는 게임이 끝나는 룰이 달라서 이렇게 하신 것 같은데, 
이 코드 한 줄만 봤을때는 무엇을 의도하는 것인지 파악하기 힘든 것 같아요. 
다른 방법이 있는지 좀 더 고민해보시면 좋을 것 같아요 🤔

2023-05-04 15:44 UTC, HarryHyeon commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
>                validOptionRange.contains(gameOptionNumber) else {
```suggestion
              0...3 ~= gameOptionNumber else {
```
이렇게도 사용할 수 있을 것 같아요👍🏼

2023-05-05 23:48 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
>                  print("\(resultMessage)")
수정해주었습니다 감사합니다!

2023-05-05 23:58 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
>                validOptionRange.contains(gameOptionNumber) else {
해리가 의견내주신 부분의 코드도 고민해보았습니다! 한 번 더 상기하게 되네요..! 감사합니다 😇

2023-05-06 03:05 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                isGameOn = !getGameResult(computerHandShape, userHandShape).isGameOn
default부분을 타게되면 게임이 계속 진행되고 isGameOn 부분은 계속 true가 할당되어 있기 때문에 따로 할당해 줄 필요가 없다는걸 깨달았습니다 😂 결과적으로 코드를 삭제했습니다!

2023-05-06 03:08 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        var isGameOn: Bool = true
이 부분에 대해 어제도 나누었지만 다시 한번 올리겠습니다 ㅎㅎ
여러 메서드에서 쓰이기 때문에 전역, 또는 해당 타입의 프로퍼티로 빼주는게 나은지 아니면 해당 타입이 가지고 있기에는 어색한 프로퍼티라면 메서드마다 변수를 생성해주는게 좋은지에 대해 서로의 의견이 달랐습니다!

2023-05-06 03:10 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +        print("\(currentTurnOwner.rawValue)의 승리!")
연산 프로퍼티를 사용해서 해결해 보았습니다!

2023-05-06 03:10 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +            guard let computerHandShape = computer.getCurrentHandShape() else { continue }
makeComputerHandShape 라는 메서드로 컴퓨터의 랜덤한 손을 정하는 부분을 기능분리해줬습니다!
아쉬운 부분은 gameOptionNumber를 받아 처리하는 과정은 가위바위보와 묵찌빠의 로직이 달라서 결과적으로 합치지 못했습니다. 이 부분은 더 고민해보겠습니다~

2023-05-06 03:11 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +    private func showGameMessageWith(_ gameType: GameType, _ currentTurnOwner: PlayerType?) {
함께 얘기나누었던 것처럼 API가이드라인을 따라 네이밍은 유지하기로 했습니다! 하지만 두 손을 비교하는 메서드의 이름은 compare로 바꾸어 훨씬 직관적으로 보일 수 있게 되었습니다. 좋은 피드백 감사합니다!

2023-05-06 03:13 UTC, iOS-Yetti commented on RockPaperScissors/RockPaperScissors/Models/GameManager.swift
> +                    return
getMukChiPaResult 메서드를 만들어 바인딩하며 결과값을 가져오도록 기능분리를 하여 해결하였습니다!

2023-05-06 14:40 UTC, merged