묵찌빠 게임 [STEP 2] kyungmin, kobe
yagom-academy/ios-rock-paper-scissors pull request #215
Opened 2023-05-05 09:13 UTC by devKobe24

안녕하세요, (레옹아범)@fatherLeon kyungmin, kobe 입니다.

STEP2 구현을 끝내서 PR 보냅니다. 
---
## 고민했던 점
- 반환 값이 없는 함수를 구현할 때 함수가 끝나는 시점에 return 을 써줘야 하는지 궁굼합니다.
- 추가로 구현 하면 좋은 부분 comment에서 “현재 main파일에 메서드만 존재하는데 해당 메서드들을 전부 포함하는 하나의 타입을 생성하여 타입 안에 메서드를 넣어서 큰 타입을 하나 구현해보시면 좋을 것 같습니다.” 라고 조언해주셨는데 클래스안에 따로 담는 방식을 말씀하신건지 궁금합니다.
---
## 해결이 되지 않은 점
- 프로젝트 요구사항을 봤을 때 정확히 어떤식으로 구현해야할지에 대한 명확한 기준을 모르겠습니다. “이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야 하는 문서”, “프로젝트 수행 중 핵심 경험”에서 class에 대한 언급이 없었기 때문에 함수를 기능단위로 분리해서 파일 단위로 나눠 놨는데요. 이게 맞는지 잘 모르겠습니다.
---
## 조언을 얻고 싶은 부분
- 임의의 HandShape을 받아오는 함수 generateRandomHandShape을 구현 할때 Int.random보다 randomElement로 구현해보라고 하셨는데 randdomElement 사용시 optional을 반환하여 옵셔널 바인딩 작업이 한번 더 필요한데 randomElement를 사용시 조금 더 좋은 점이 있을까요?
- 몸 상태가 좋지 않아 지난번에 못했던 조언을 위한 만남을 다시 할 수 있을까요?

2023-05-05 12:21 UTC, fatherLeon commented
안녕하세요 @devKobe @YaRkyungmin
STEP1에 비해 로직이나 역할분리가 잘 된 것 같습니다👍
그 외 컨벤션도 이전에 비해서 수정할 내용이 확 줄은 것이 많은 고민을 하신 것 같습니다👍👍

크게 어려운 부분은 없을 것 같긴한데 이해안되거나 어려운 부분 있으시면 DM보내주세요~~

## 고민했던 점
> 반환 값이 없는 함수를 구현할 때 함수가 끝나는 시점에 return 을 써줘야 하는지 궁굼합니다.

* 이 부분은 코멘트로도 남겼지만 함수가 끝나는 시점이 명확하다면 쓸 필요는 없습니다
* guard문이나 if문에서 특정 조건에서 끝나야한다면 그런 부분은 `return`을 써줘야겠죠?

> 추가로 구현 하면 좋은 부분 comment에서 “현재 main파일에 메서드만 존재하는데 해당 메서드들을 전부 포함하는 하나의 타입을 생성하여 타입 안에 메서드를 넣어서 큰 타입을 하나 구현해보시면 좋을 것 같습니다.” 라고 조언해주셨는데 클래스안에 따로 담는 방식을 말씀하신건지 궁금합니다.

* 이 부분은 코드 코멘트에는 따로 달지는 않았는데 구조체 혹은 클래스로 담으라는 말은 맞습니다.

## 해결이 되지 않은 점
> 프로젝트 요구사항을 봤을 때 정확히 어떤식으로 구현해야할지에 대한 명확한 기준을 모르겠습니다. “이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야 하는 문서”, “프로젝트 수행 중 핵심 경험”에서 class에 대한 언급이 없었기 때문에 함수를 기능단위로 분리해서 파일 단위로 나눠 놨는데요. 이게 맞는지 잘 모르겠습니다.

* 문서에는 없지만 아마? 활동학습 시간에 일반화, 추상화, 캡슐화 등에 대해 배우셨을텐데 해당 내용을 토대로 구현을 해보셨으면 좋을 것 같아 말씀드렸습니
* 또한, 현재 객체를 통하여 만들지는 않았지만 몇몇 부분에서는 은닉화가 안된 코드도 몇개 보이네요

## 조언을 얻고 싶은 부분
> 임의의 HandShape을 받아오는 함수 generateRandomHandShape을 구현 할때 Int.random보다 randomElement로 구현해보라고 하셨는데 randdomElement 사용시 optional을 반환하여 옵셔널 바인딩 작업이 한번 더 필요한데 randomElement를 사용시 조금 더 좋은 점이 있을까요?

* 우선 `Int.random`때문이라기 보다는 서브스크립트를 통한 배열의 접근 때문에 `randomElement`사용을 말씀드렸습니다.
* 이전에 사용했던 방법 `arr[1]`과 같은 방법을 subscript라고 하는데 [Documentation](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/subscripts/) 다음에 시간 나실 때 한번 읽어보세요
* 우선 서브스크립트의 경우 예상치 못한 값(현재 배열 개수 이상의 값)이 들어올 경우 현재 프로그램이 죽어버립니다.
* [randomElement() | Apple Developer Documentation](https://developer.apple.com/documentation/swift/array/randomelement()) 를 사용할 경우 읽어보시면 아시겠지만 배열의 값이 없을 경우에만 nil이 반환되고 그 외에는 항상 값이 반환됩니다.
* 물론 특정 값만을 통해 배열에 접근할 경우 큰 문제가 없다고 느낄 수도 있지만 이런 부분이 안정성을 더 보장해준다고 생각하여 사용해보라고 말씀드렸습니다.

> 몸 상태가 좋지 않아 지난번에 못했던 조언을 위한 만남을 다시 할 수 있을까요?

* 이 부분은 아까전에도 말씀드렸다시피 나중에 두분 모이실 때 말씀해주시면 될 것 같습니다👍👍

2023-05-05 12:26 UTC, fatherLeon requested changes

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/GameLogic.swift
> +func determinGameTurn(with gameResult: GameResult) -> GameTurn{
해당 부분 컨벤션 수정이 필요해보입니다

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +        typealias inputNumberGameTurn = (inputNumber: Int, gameTurn: GameTurn)
타입 별칭과 튜플에 라벨까지 달아서 사용하신 점 너무 좋습니다👍

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +func inputNumberAtMukJiBba(with turn: GameTurn) -> (inputNumber: Int, gameTurn: GameTurn) {
위에서 타입별칭을 정의했기 때문에 해당 메서드 반환 타입이 `inputNumberGameTurn`이 되면 좋을 것 같습니다.

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +        let handShape = receiveHandShapeElement(index: gameData.inputNumber)
현재 묵찌빠를 실행중인데 값이 입력될 경우 묵(1), 찌(2), 빠(3)에 관한 값이 아니라
가위(1), 바위(2), 보(3)의 값으로 리턴이 되네요

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +    return
`return`이 필요할까요?

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +    return
`return`이 필요할까요?

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/RockScissorsPaper.swift
> +        }
이 정도는 한줄로 적어도 될 것 같습니다

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/RockScissorsPaper.swift
> +		}
해당 `guard`문은 위의 `if`문이랑 합쳐도 될 것 같네요
위의 `if`문을 `guard`문으로 바꿔 하나의 `guard`문으로 처리하게끔 만들어주는게 좋아보입니다.

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/RockScissorsPaper.swift
> +			  let covertUserInput = Int(userInput),
해당 변수명이 동사로 시작하네요 
수정이 필요해보입니다

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/GameLogic.swift
> +    }
해당 부분도 짧으니 한줄로 만들어도 될 것 같아요

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/GameLogic.swift
> +func checkGameEnd(with inputNumber: Int) -> Bool {
메서드의 인자 라벨을 붙인 점 매우 좋습니다
하지만, `inputNumber`라는 인자명은 수정이 필요해보이네요

2023-05-05 12:26 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +func inputNumberAtMukJiBba(with turn: GameTurn) -> (inputNumber: Int, gameTurn: GameTurn) {
추가로 다른 몇몇 부분에도 수정하면 좋을 것 같은 부분이 있는데 여기에 우선 하나로 쓰겠습니다.
현재 프로그램이 동작하는데 있어서 `main`파일의 `playMukJjiBba`메소드만을 호출하여 사용합니다.

그렇기 때문에 `inputNumberAtMukJiBba`메서드 같은 경우 굳이 외부에 노출할 필요가 없어 접근제어자를 통해 외부 노출을 방지하면 좋을 것 같습니다.

이 부분은 단순히 이 함수만이 아니라 다른 함수에도 적용되니 고민해보시고 몇몇 메서드에 접근제어자를 설정해주시면 좋을 것 같네요

2023-05-05 12:30 UTC, fatherLeon requested changes

2023-05-05 12:30 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/GameTurn.swift
> +}
해당 부분을 열거형 내에서 계산프로퍼티로 만들어 `rawValue`의 접근이 아닌 프로퍼티로 접근 가능하게 끔 구현하는 방법도 한번 찾아보시면 좋을 것 같습니다
꼭 고치실 필요는 없어요~~

2023-05-06 06:03 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/GameLogic.swift
> +func determinGameTurn(with gameResult: GameResult) -> GameTurn{
컨벤션 관련해서
determinGameTurn을 determineGameTurn으로 변경하였고,
gameResult를 status로 변경하였고
중괄호 옆 띄어쓰기를 했습니다 
지적해주신 내용을 잘 반영한게 맞을까요?

2023-05-06 06:08 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +func inputNumberAtMukJiBba(with turn: GameTurn) -> (inputNumber: Int, gameTurn: GameTurn) {
typealias를 전역으로 빼줘야해서 이렇게 구현했었는데 class안에 담아서 구현해보겠습니다:)

2023-05-06 07:06 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +        let handShape = receiveHandShapeElement(index: gameData.inputNumber)
가위 바위 보와 묵찌빠를 반환하는 함수를 따로 구현했습니다 :)

2023-05-06 07:07 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +    return
함수가 끝나는 시점이 명확하기 때문에 return을 빼줬습니다ㅎ

2023-05-06 07:07 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +    return
함수가 끝나는 시점이 명확하기 때문에 return을 빼줬습니다ㅎ

2023-05-06 07:10 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/RockScissorsPaper.swift
> +        }
넵 한 줄로 줄여보겠습니다 :)

2023-05-06 07:19 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/RockScissorsPaper.swift
> +		}
하나로 합쳐서 해결해봤습니다:)

2023-05-06 07:28 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/RockScissorsPaper.swift
> +			  let covertUserInput = Int(userInput),
일단 수정은 했습니다, 그러나 질문 드릴 내용이 있습니다 :)

2023-05-06 07:28 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/GameLogic.swift
> +    }
네 바꿔줬습니다ㅎㅎ

2023-05-06 07:29 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/GameLogic.swift
> +func checkGameEnd(with inputNumber: Int) -> Bool {
userInput으로 수정해보았습니다 :)

2023-05-06 07:30 UTC, YaRkyungmin commented on RockPaperScissors/RockPaperScissors/MukJjiBba.swift
> +func inputNumberAtMukJiBba(with turn: GameTurn) -> (inputNumber: Int, gameTurn: GameTurn) {
클래스를 사용하여 구현할때 접근제어자를 이용해보겠습니다

2023-05-06 07:32 UTC, devKobe24 commented on RockPaperScissors/RockPaperScissors/GameTurn.swift
> +}
계산 프로퍼티를 사용하여 구현해보겠습니다, rawValue를 통한 접근이 좋지 않은 이유를 알 수 있을까요??

2023-05-06 19:22 UTC, fatherLeon commented on RockPaperScissors/RockPaperScissors/GameTurn.swift
> +}
`rawValue`사용이 좋지 않은건 아닙니다
```swift
GameTurn.user.description
GameTurn.user.rawValue
```

다만 `rawValue`는 향후 코드 작성시 어떤값인지 알아보기 어렵다는 단점이 있습니다.
`rawValue`보다 프로퍼티를 사용하는 것이 용도와 역할을 더욱더 확실히 알 수 있기 때문에 한번 구현해보면 좋을것 같다고 말씀드렸습니다~

2023-05-06 19:33 UTC, fatherLeon commented
전체적으로 구현하신 내용 봤을 때 깔끔하게 잘 하신것 같습니다.
클래스로 사용하는 부분도 상속을 이용하여 구현해보신 점
여러 타입을 구현하여 활용해보신 점 등 좋은것 같습니다.

추후에 해당 부분에 대해 조금 더 수정할 내용이나 고칠게 있다면 두 부분정도 있을 것 같습니다.

1. `MukJjiBba`의 몇몇 함수 은닉화하기
- `inputNumberAtMukJiBba`와 같은 함수는 외부에서 따로 접근할 필요가 없기 때문에 은닉화 할 필요가 있어보입니다.

2. 상속되지 않는 클래스의 경우 `final`키워드 붙이기
- [WWDC16 - Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)
- [OptimizationTips](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst)
- 위 영상과 문서는 굳이 지금은 보실 필요 없으시겠지만, 추후 조금 더 공부해보시고 방학기간 때 한번 보시고 정리해보는 것을 추천드립니다.

이 외에는 전체적으로 크게 수정할 내용이 없는것 같네요
한주동안 고생 많으셨습니다.
추가 질문 있다고 하신 내용은 DM보내주시면 답 해드리겠습니다

2023-05-06 19:34 UTC, merged