[STEP 1] 햄찌, 가마
yagom-academy/ios-rock-paper-scissors pull request #225
Opened 2024-01-08 14:32 UTC by forseaest

안녕하세요! 3조 햄찌, 가마입니다! 잘 부탁드립니다~ @carti1108

## 작성할 떄 고민한 점
- 게임을 실행하는 ```run()``` 함수 안에서 사용자의 입력을 받고, 가위바위보의 결과를 내는 부분까지 포함하고 있어 너무 길다고 생각해서, 가위바위보의 결과를 도출하는 부분을 ```showResult()``` 함수로 분리했습니다.

## 조언을 얻고 싶은 점
- 저희 코드에서는 if문 안에서 1, 2, 3과 같은 숫자를 통해 하드 코딩으로 판정을 내리는 로직을 사용했는데, 보다 더 좋은 방법이 있을 것 같다고 생각합니다.
- 함수 분리의 적절한 타이밍에 대해서 조언을 얻고 싶습니다. 함수 내용이 너무 적을 경우, 굳이 분리를 해야 하는 지 궁금합니다.

2024-01-09 02:36 UTC, carti1108 requested changes
안녕하세요 햄찌, 가마!
step1 진행하시느라 고생하셨습니다!
저 또한 같은 캠퍼이기 때문에 제가 드리는 리뷰가 항상 옳은게 아닙니다.
제가 질문을 할 때는 틀렸다는게 아닌 저도 정말 몰라서 물어보는 것입니다🥹
제 리뷰가 이해가 안되거나 본인들의 의견과 맞지 않다고 생각하면 언제든 dm주세요!
디코에서 같이 고민해봐도 좋을 것 같아요🙂

## 조언을 얻고 싶은 점
> 저희 코드에서는 if문 안에서 1, 2, 3과 같은 숫자를 통해 하드 코딩으로 판정을 내리는 로직을 사용했는데, 보다 더 좋은 방법이 있을 것 같다고 생각합니다.

[Enum](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations/)에 대해서 공부해 보시면 좋을 것 같아요.
다음 스텝에서도 도움이 될 수도 있어요🙂
해당 방식이 정답이라는 것은 아닙니다!

> 함수 분리의 적절한 타이밍에 대해서 조언을 얻고 싶습니다. 함수 내용이 너무 적을 경우, 굳이 분리를 해야 하는 지 궁금합니다.

제 생각을 말씀드리기 전에 햄찌, 가마는 함수를 분리해야 되는 이유가 뭐라고 생각하시나요?
또 함수 내용이 너무 적을 때는 꼭 분리를 해야하나? 라고 고민하신 이유가 뭘까요?

> 변수와 함수의 네이밍이 적절한지 조언 부탁드립니다!

코멘트를 확인해 주세요!

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let safeUserInput = userInput {
If let 바인딩을 사용하셨네요!👍

1. 다른 방법은 또 무엇이 있을까요?
2. 각 방법의 차이는 무엇일까요?

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch safeUserInput {
switch를 사용하셨네요!👍
switch에 대해서 설명해 주실 수 있으실까요?

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("프린트 종료")
프로젝트 요구사항과 맞지 않는 출력문인 것 같아요.
프로그램 동작에는 문제가 없지만 요구사항을 자세히 확인하고,
그 내용대로 구현하는 것도 중요합니다.🙂

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다시 시도하여 주세요.")
해당 코드가 꼭 있어야 할까요?

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func showResult(userInput: String){
컨벤션에 맞지 않는 것 같아요.
소괄호 뒤에 띄어쓰기가 들어가야 할 것 같은데 실수로 놓치신 것 같네요🥹
구현이 끝나면 작성한 코드들을 검토해보면 좋을 것 같아요.
개인적으로 체크리스트를 만들어서 확인하는 것도 좋은 습관이 될 것 같아요🙂

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    print("컴퓨터 : \(computerChoice)")
프로젝트 요구사항에는 없지만,
사용자가 컴퓨터가 어떤 패를 냈는지 볼 수 있어서 좋은 것 같네요👍

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if userInput == computerChoice {
if문을 사용하셨네요👍
if에 대해서 설명해 주실 수 있나요?

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("비겼습니다!")
프로젝트 요구사항에는 비겼을 때 프로그램을 종료하는 것이 아닌 다시 최초 실행 상태로 돌아가야한다고 적혀있는데,
해당 코드에서는 다시 최초 실행 상태로 돌아가는 코드가 보이지 않네요🥺

1. 해당 동작을 구현하기 위한 방법들은 어떤 것들이 있을까요?
2. 각 방법들에 대해 설명해 주실 수 있을까요?

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    } else if (userInput == "1" && computerChoice == "3") || (userInput == "2" && computerChoice == "1") || (userInput == "3" && computerChoice == "2") {
해당 코멘트는 개인 취향인데,
조건이 너무 길어질 때는 가독성을 위해 따로 상수로 빼주는 방법도 있습니다!

```swift
let isWin: Bool = (userInput == "1" && computerChoice == "3") || (userInput == "2" && computerChoice == "1") || (userInput == "3" && computerChoice == "2")
    
    print("컴퓨터 : \(computerChoice)")
    
    if userInput == computerChoice {
        print("비겼습니다!")
    } else if isWin {
        print("이겼습니다!")
  }
```

개인의 취향이니 참고만 해주세요🙂

2024-01-09 02:36 UTC, carti1108 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
함수명은 showResult라 단순히 결과만 출력해 줘야 할 것 같은데,
해당 코드에서는 사용자 입력도 받고, 결과도 만들어내고, 그 결과를 출력하는 동작까지 하는 것 같아요.
함수명에 맞게 동작하는 건 중요하다고 생각해요.
함수명을 바꾼다거나, 함수를 분리하는 방법이 있을 것 같네요🙂

2024-01-09 11:52 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if userInput == computerChoice {
if는 코드 흐름을 조건에 따라 분기시키는 조건문의 키워드입니다. if 다음의 조건식이 true면 중괄호 블록 안의 구문을 실행하고, false면 실행하지 않습니다. 조건식의 값은 반드시 bool 자료형이어야 합니다. swift에서는 다른 프로그래밍 언어와 다르게 if문의 조건식에 0 혹은 1과 같은 값을 넣을 수 없습니다.

2024-01-09 12:34 UTC, kkomgi commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let safeUserInput = userInput {
1. guard let / ?? 연산자 / 옵셔널 체이닝 / ! 강제 언래핑 이 있습니다
2. 방법의 차이
 - guard let : guard 구문을 사용하여 옵셔널 값이 nil 계속 코드 실행 가능합니다
 - ?? 연산자 : 옵셔널 nil 인 대체 값을 지정할 수 있는 ?? 연산자를 사용할 수 있습니다
 - 옵셔널 체이닝 : 옵셔널 체이닝 사용하여 옵셔널 프로퍼티나 메서드에 접근할 수 있습니다
 - ! 강제 언래핑 : 강제 언래핑 사용하여 옵셔널을 값을 강제로 추출할 수 있습니다

2024-01-09 12:47 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다시 시도하여 주세요.")
if let으로 옵셔널 바인딩이 되지 않는 사용자 입력이 nil인 가능성에 대해서 대응한 코드라서 필요하다고 생각합니다!

2024-01-09 12:50 UTC, kkomgi commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch safeUserInput {
다양한 값을 판별하고, 각 case에 따라 다른 동작을 수행할 때 사용하는 제어문입니다.

2024-01-09 12:56 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("프린트 종료")
오타 수정하였습니다!

2024-01-09 12:58 UTC, kkomgi commented on RockPaperScissors/RockPaperScissors/main.swift
> +    print("컴퓨터 : \(computerChoice)")
넵 감사합니다. 육안으로 확인해야 제대로 코드가 돌아가는 것을 볼 수 있어서 넣게 되었습니다.

2024-01-09 13:10 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +    } else if (userInput == "1" && computerChoice == "3") || (userInput == "2" && computerChoice == "1") || (userInput == "3" && computerChoice == "2") {
조건문의 조건 변수를 따로 분리시키는 코드로 수정했습니다!

2024-01-09 13:24 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +func showResult(userInput: String){
띄어쓰기 추가하여 수정했습니다!

2024-01-10 02:17 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
컴퓨터의 패를 만들고, 컴퓨터와의 승부를 도출해내는 부분을 ```makeComputerChoice()```로 분리시켰습니다. 이 과정에서 결과를 나타내는 자료형 ```GameResult```을 enum으로 만들어 나타내도록 하였습니다.

2024-01-10 05:41 UTC, forseaest commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("비겼습니다!")
```loopFlag```라는 Bool 변수를 true로 선언 및 초기화하고, while문으로 loopFlag가 true인 동안 입력과 출력을 하도록 하고, 0을 입력 받은 경우에만 loopFlag를 false로 변경시켜 while문을 탈출시켜 게임을 종료하게 만들었습니다.

2024-01-10 13:14 UTC, carti1108 commented
구두로 설명 완료했습니다

2024-01-10 13:15 UTC, merged