묵찌빠 게임 [STEP1] Diana, Gray
yagom-academy/ios-rock-paper-scissors pull request #226
Opened 2024-01-09 07:31 UTC by Diana-yjh

## 완료된 작업: [STEP1]
안녕하세요 @Hi-sop 🥰
묵찌빠 게임 [STEP1] PR 부탁드립니다 🙏</br>
## 📝 코드 설명
- ```computerPlay()``` :  컴퓨터의 가위, 바위, 보 중 하나 선택 구현
- ```userInput()```: 사용자의 입력 구현
- ```rockScissorsPaper()```: 게임 진행, 반복 구현
- ```gameResult()```: 사용자의 입력을 확인하여 게임 결과 출력 구현</br>
## 🤔 고민했던 부분
- 사용자 입력 구분: 게임종료(0)와 게임실행(1(가위), 2(바위), 3(보)) 의 입력이 구분되어 있지 않아 ```gameResult()```함수에서 함께 처리
- 프로젝트 브랜치 설정: step1이라는 브랜치를 설정하여 같이 작업 후 PR을 요청. PR 이후 local main에 step1 브랜치를 merge 후 step2라는 브랜치를 생성하여 STEP2 진행 예정</br>

🙌 감사합니다! 🙌

2024-01-09 13:19 UTC, Hi-sop requested changes
안녕하세요! 보내주신 PR 잘 읽었습니다.
리뷰한 내용을 반드시 수정하실 필요는 없습니다. 제 의견일 뿐이니 참고 후 팀의 의사대로 결정해주시면 됩니다.
리뷰한 내용 중 잘 이해되지 않거나 틀린 부분이 있다면 꼭 DM주세요. 같이 고민해보면 좋을 것 같습니다.

### 🤔 고민했던 부분
> 사용자 입력 구분: 게임종료(0)와 게임실행(1(가위), 2(바위), 3(보)) 의 입력이 구분되어 있지 않아 gameResult()함수에서 함께 처리

게임을 종료할지 확인하는데 필요한 건 사용자의 입력 뿐인 것 같아요. 다른 지점에서 처리해줄 수 있었을 것 같다는 생각이 들었어요.

> 프로젝트 브랜치 설정: step1이라는 브랜치를 설정하여 같이 작업 후 PR을 요청. PR 이후 local main에 step1 브랜치를 merge 후 step2라는 브랜치를 생성하여 STEP2 진행 예정

git을 어떻게 관리할지는 팀이 정하기 나름이라고 생각합니다. 지금도 잘 하고 계신 것 같아요.
다만 commit을 나누는 단위는 명확히 정해보아도 좋을 것 같습니다.

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RPS: Int {
swift의 네이밍은 약어를 지양하도록 되어있습니다. [네이밍 가이드라인](https://www.swift.org/documentation/api-design-guidelines/)을 다시 한번 보시면 좋을 것 같습니다!

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +let inputList: Array<Int> = [0, 1, 2, 3]
전역변수를 사용하신 이유가 있을까요? 전역적으로 사용되는지 궁금합니다.

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let computerSelect = menuList.randomElement() else {
[Int.random(in:)](https://developer.apple.com/documentation/swift/int/random(in:)-9mjpw) 로 랜덤값을 생성하는 방법도 있습니다

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return -1
-1을 리턴하는 이유가 있을까요? Magic Number나 Optional에 대해 찾아보셔도 좋을 것 같습니다

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let input = readLine(), !input.isEmpty else {
condition-list를 사용해 guard문을 간소화시킨 부분이 좋았습니다!

위 가드문에서 ','는 어떤 의미로 사용되는지 알려주실 수 있을까요?

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +            repeatFlag = gameResult(userInput: userInput, gameCase: [1, 2])
gameCase로 전달하는 값이 선언해두신 enum타입이면 읽기 더 좋았을 것 같습니다.
[2, 3]이 어떤 의미였지? 하고 enum 선언부로 올려보게 되는 것 같아요

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
if 문과 guard문의 차이점을 설명해주실 수 있을까요?

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    repeat {
repeat-while을 선택하신 이유가 있을까요?

재귀함수와 while문의 차이에 대해서도 설명해주시면 좋을 것 같습니다.

2024-01-09 13:19 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +func gameResult(userInput: Int, gameCase: Array<Int>) -> Bool {
gameResult가 결과 판별, 결과 출력 기능을 포함하고 있다는 느낌이 들었어요.
기능을 최대한 분리해보아도 좋을 것 같습니다.

2024-01-10 02:09 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RPS: Int {
네! 네이밍 가이드라인을 따라서 Gesture로 수정하도록 하겠습니다!😎

2024-01-10 02:12 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let computerSelect = menuList.randomElement() else {
Tip을 주셔서 감사합니다! 
다음 PR에 Int.random() 함수를 사용할 지, 그대로 배열의 값을 이용할 지 고려하여 수정하도록 하겠습니다!👏

2024-01-10 04:20 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return -1
Int 타입 반환하는 함수에서 예외처리 설정으로 -1, -2를 반환하였습니다.
힌트주신 Magic Number 를 참고하여 struct 로 매직넘버를 생성하여 가독성이 높은 코드로 수정했습니다!👍

2024-01-10 04:48 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let input = readLine(), !input.isEmpty else {
,는 동일한 예외처리를 하는 상황일때 사용합니다. 
&&와 ||은 논리연산자로서 Condition 앞과 뒤를 반드시 비교해야하는데, condition-list의 경우에는 비교를 하지 않고, 개별 컨디션으로서 인식합니다.

아래와 같은 상황일 때 , 사용
```swift
func userInput() -> Int {
    guard let input = readLine() else {
        print("잘못된 입력입니다. 다시 시도해주세요.")
        return errorCode.wrongInput
    }
    guard !input.isEmpty else {
        print("잘못된 입력입니다. 다시 시도해주세요.")
        return errorCode.wrongInput
    }
    return inputInt
}
```

2024-01-10 05:02 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            repeatFlag = gameResult(userInput: userInput, gameCase: [1, 2])
enum Gesture의 rawValue를 가져와서 지역상수로 선언했습니다.
```swift
let scissors:Int = Gesture.scissors.rawValue
    let rock:Int = Gesture.rock.rawValue
    let paper:Int = Gesture.paper.rawValue
```

의미를 헷갈리지 않도록 각 제스쳐 명으로 명시했습니다!
```swift
switch rpsValue {
        case .scissors:
            repeatFlag = gameResult(userInput: userInput, gameCase: [scissors, paper])
        case .rock:
            repeatFlag = gameResult(userInput: userInput, gameCase: [paper, scissors])
        case .paper:
            repeatFlag = gameResult(userInput: userInput, gameCase: [scissors, rock])
        }
```

2024-01-10 05:10 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
If문은 condition이 true일 경우, 구문을 실행합니다. if문에서 선언된 변수나 상수는 if문 밖에서 사용 불가능합니다.

guard문의 경우에는 function 내에서만 선언이 가능하며, condition이 false일 경우, 함수를 빠르게 종료시키는 목적으로 사용됩니다! guard문에서 선언된 변수나 상수는 guard 밖에서만 사용 가능합니다.

2024-01-10 05:41 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    repeat {
repeat-while을 선택한 이유는
조건 체크를 한 뒤 실행을 하는 while문과는 다르게, repeat문은 한 번 실행한 뒤에 조건을 체크하게 되다보니
게임을 우선 한 번 실행하기 위해서 repeat-while을 선택하였습니다. 

repeat-while을 사용함으로써 repeatFlag의 불필요한 재선언을 방지할 수 있습니다.

재귀함수는 함수 내부에 있는 모든 값을 재선언 해야하는 반면에
while 같은 경우, 필요한 부분만 반복을 할 수 있어 불필요한 재선언을 막을 수 있습니다.

재귀함수는 반복문의 종료 조건 명시를 반드시 해야 무한 루프를 방지할 수 있습니다.😀

2024-01-10 05:42 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func gameResult(userInput: Int, gameCase: Array<Int>) -> Bool {
기능을 최대한 분리해 보겠습니다!

2024-01-10 07:09 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let inputList: Array<Int> = [0, 1, 2, 3]
생각해보니, 전역변수로 굳이 선언할 필요가 없을 것 같아, 지역변수로 처리하였습니다!

2024-01-10 11:29 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
에러 핸들링은 일반적으로 Error타입을 프로토콜로 채택하여 처리하는것으로 알고 있습니다. 관심있으시면 찾아보셔도 좋을것같네요

2024-01-10 11:29 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    static let paper = 3
static 프로퍼티를 포함한 struct로 변경되었네요?
static 키워드의 어떤 특성 때문에 채택하셨는지 알려주시겠어요?

2024-01-10 11:34 UTC, Hi-sop commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let paper:Int = Gesture.paper
[Int]타입을 gameResult에 전달하기 위해 이렇게 변경하신것으로 보이는데
enum타입도 간단하게 전달이 가능합니다

2024-01-10 12:22 UTC, yawoong2 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let paper:Int = Gesture.paper
참고해서 변경하였습니다!

2024-01-10 13:40 UTC, merged