[Step 1] Fezz, Ian
yagom-academy/ios-rock-paper-scissors pull request #25
Opened 2021-03-01 13:46 UTC by Fezravien

# [STEP 1] Rock Scissors Paper Game 🔥

### 안녕하세요 `cozy`!  😀

`Ian`과 함께 최대한 공식문서를 따르기 위해 고민을 해봤어요 !

#### 고민되었던 점 ⁉️ &&  조언을 얻고 싶은 부분 👂

RockScissorsPaperGame Class를 인스턴스로 만드는 것을 시작으로 presentGameMemu, startGame을 통해 동작 단위 구분을 위해 extension을 사용해 봤어요 (extension의 진정한 기능은 못쓰지만 단순하게 메인 동작과 서브 동작을 구분하기 위해서 사용했습니다.) 구조는 그림으로 한번 만들어봤어요 👀 

<img width="650" alt="image" src="https://user-images.githubusercontent.com/44525561/109505114-9cafe180-7adf-11eb-8d12-e1f548ce02ef.png">

 옵셔널 강제추출에 있어서 지양해야겠지만, checkedInput 메소드에 옵셔널 강제 추출 하는 `validArrays.first!` 부분이 있는데요. if 조건문 상위 부분에서 이미 값은 존재하며 무조건 1개라는 조건을 통과해서 강제 추출에 위험성이 없다고 판단해서 이렇게 작성했어요. 혹시 문제가 있을까요? 🙂

2021-03-02 02:25 UTC, yagom commented
오늘 코지가 몸이 안좋아서 제가 대신 리뷰합니다 :p 이따 오후에 리뷰할게요~

2021-03-02 06:32 UTC, yagom requested changes
많은 고민이 엿보이는 코드였습니다.
코드가 규칙을 갖추고 예쁘게 작성되어 있어서 읽기 편했어요 :)

몇 가지 질문과 함께 Fezz와 Ian이 고민했던 내용을 코멘트로 남겨두었습니다.
코멘트 확인하면 이모지로 코멘트 확인했다는 표시를 남겨두면 리뷰어가 두 사람의 상태를 확인할 수 있어 좋습니다.

코멘트에 대해서 궁금하거나 의문이 생기거나 이해가 가지 않는 부분이 있다면 `둘이서 끙끙대지 말고` 리뷰어의 코멘트에 질문 남겨서 빠르게 의사소통 하는것이 좋습니다. 

또, 리뷰어의 질문에 대해서 이유를 설명할 수 있는 것이 있다면 바로바로 답변을 남겨두는게 좋아요. 나중에 코드 새로 작성해서 그 때 답변달면 늦습니다.

마지막 질문에 대한 저의 질문이 있어요.
순환함수(재귀함수)와 반복문의 차이점은 무엇이고 장단점은 무엇이라 생각하나요? :)

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> -import Foundation
Foundation은 무엇이길래? 왜 지웠을까요? 없어도 되나요?
`import Foundation` 코드의 의미는 뭘까요?

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func createComputerRandomNumber() -> Int {
임의의 숫자가 꼭 컴퓨터 숫자만을 위한걸까요?
이 메서드를 좀 더 범용적으로 사용하려면 어떤 이름이 좋을까요?
나중에 사용자의 임의의 수가 필요한 기획이 출현한다면??

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +extension RockScissorsPaperGame {
익스텐션에 대해 고민해봤다고 했는데요, 메인 기능과 서브 기능의 구분은 어떤 기준으로 나눈건가요?
또, 익스텐션을 정의할 때는 문서화 주석 등으로 이 익스텐션이 타입의 구현부 혹은 다은 익스텐션과 어떤 점이 달라서 익스텐션으로 나눈 것인지 설명해두면 더 좋아요.
스위프트의 기본 타입도 다양한 익스텐션을 활용하는데요, 거기에선 어떻게 적어뒀는지 확인해 보는 것도 좋겠네요.
`Int`, `Array` 등의 기본 타입의 정의부를 살펴보면 도움이 될거예요 :)

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func isValidInput() -> Int {
입력이 유효한지 확인한다는 뜻의 메서드 같은데, 내부에서 입력까지 한번에 받고 있네요.
이름에 맞게 구현을 수정해봄이 좋겠습니다.

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func printError() {
지금의 기능요구로는 '잘못된 입력입니다. 다시 시도해주세요.' 오류만 있지만, 나중에 새로운 오류 유형이 추가된다면, 이 메서드는 이 모양 그대로 살아남을 수 있을까요?

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        } else if validArrays.contains(-1) {
기능상세서를 숙지하지 않고 이 코드만 보고서는 `-1` 이라는 숫자가 어떤 의미를 가지는지 파악하려면 너무 어려울 것 같아요.
코드에 포함하는 상수를 좀 더 유의미하게 표현할 수 있는 방법은 없을까요?

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        } else if validedNumbers.contains(validArrays.first!) == false {
guard 구문의 의미에 대해서 조금 더 생각해보면 좋겠습니다.
guard 구문이 이 메서드의 처음에 존재한다면?
guard는 왜 guard일까요?

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +RockScissorsPaperGame().presentGameMemu()
start point에서는 startGame 등의 메서드를 호출하는 것이 훨씬 더 직관적이지 않을까요? :)

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            inputNumbers = optionalInputNumber.split(separator: " ").map { Int(String($0)) ?? -1 }
map과 compactMap은 어떤 차이가 있을까요?

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let decisionStatus = userState - computerState
10년 뒤에 `decisionStatus`가 0일때와 1일때와 2일때 각각 어떤 상황인지 단번에 파악할 수 있을까요?
각각의 상수를 좀 더 유의미한 값으로 표현하려면 어떤 방법이 좋을까요?

2021-03-02 06:32 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        } else if validedNumbers.contains(validArrays.first!) == false {
! 느낌표를 사용하지 않을 수 있는 더 좋은 방법들은 여전히 존재할겁니다.
기획은 언제나 변경될 수 있고, 코드가 실행될 조건은 언제든 변경될 수 있습니다.
어떤 상황에서도 안전할 수 있게 코드를 작성하는 것이 차후에 발생할 기술부채를 덜어낼 수 있는 좋은 습관이 될 것입니다.

2021-03-02 07:18 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func presentGameMemu() {
presentGameMemu와 startGame 메소드를 startGame로 통합해서 메서드 이름에 부합하도록 수정했습니다 😃

2021-03-02 07:37 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func startGame() {
https://awesomeopensource.com/project/StyleShare/swift-style-guide#줄바꿈
https://docs.swift.org/swift-book/LanguageGuide/Functions.html

### 메서드 사이에 줄바꿈이 따로 없는데, 붙여쓰면 좋은점이 무엇이 있을까요? 이렇게 규칙을 정한 이유가 있나요?
* 이 문서들을 살펴보았을 때 `함수 정의가 최대 길이를 초과하는 경우에는 아래와 같이 줄바꿈`합니다. 이 부분에 대해 최대 길이가 초과하지 않는 일반적인 메서드간에는 줄바꿈이 없어도 된다고 판단하여 이렇게 진행했습니다 😀 

* 구성원들이 Swift 코드를 이해하기 쉽고 명확하게 작성하기 위한 규칙이라고 생각합니다 😁 
(이러한 부분은 구성원들과 협의를 통해 바뀔 수 있습니다 👍 )

2021-03-02 07:44 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> -import Foundation
#### Foundation 
- 애플리케이션의 핵심 객체와 `네트워크`, `문자열 처리` 등의 서비스를 제공하는 프레임워크  

입력값을 받았을때 공백을 기준으로 배열을 만들기 위한 두 가지 방식으로
1. split(separator: " ").map { ... } 
2. components(separatedBy: " ") 

components 뿐만 아니라 그 외에 네트워크, 문자열 처리 함수등을 사용하기 위해서는 `Foundation`을 임포트 해야합니다 
이번 프로젝트에서는 굳이 필요하지 않다고 판단하여 `Foundation`을 지웠습니다  😀

2021-03-02 07:58 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func createComputerRandomNumber() -> Int {
메서드의 범용성을 생각해서 createComputerRandomNumber -> createRandomNumber 로 수정했습니다 👍

2021-03-02 08:00 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func startGame() {
제 뜻은 이전 메서드가 끝나는 중괄호 `}`와 새로운 메서드의 시작인 `func` 줄과 사이에 띄움이 없다는 뜻이었어요 :)

2021-03-02 08:01 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> -import Foundation
`애플리케이션의 핵심 객체`라는 것이 무엇인지 궁금하네요 ㅎㅎ

2021-03-02 08:02 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func createComputerRandomNumber() -> Int {
`createRandomNumber`와 `randomNumber`와 의미전달의 차이가 있을까요?

2021-03-02 08:27 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +extension RockScissorsPaperGame {
- 메인 동작과 서브 동작을 구분하기 위해서 extension을 사용하면 괜찮다고 판단하여 사용했습니다 😀 
- 메인 부분(startGame)은 게임 전체를 핸들링하고, 서브 부분에서 조건 필터링 및 게임 처리를 기준하여 메인과 서브를 나누었습니다 😁

2021-03-02 08:29 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +extension RockScissorsPaperGame {
그렇군요!

2021-03-02 08:50 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func isValidInput() -> Int {
- 내부에서 입력까지 한번에 받고 있는 부분을 입력을 받는 부분과 검증하는 부분의 메소드로 세분화시켰습니다 😀 
- isValidInput -> isValidInput, userTyping

2021-03-02 09:03 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func printError() {
지금은 하나의 오류 호출이라 괜찮지만 추후 다수의 오류가 있다면 
1. 열거형을 사용해서 정리를 하면 좋다고 생각했습니다 😀
2. 인자로 오류의 상태를 받아서 조건을 사용하는 방법도 있을것 같습니다 🙃

2021-03-02 09:09 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +        } else if validArrays.contains(-1) {
저희만 생각한 `-1` 이라는 오류값을 상수 errorValue로 명시했습니다 ✍️

2021-03-02 09:10 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +RockScissorsPaperGame().presentGameMemu()
presentGameMenu를 startGame 메소드로 포함시켜서
RockScissorsPaperGame().startGame() 으로 수정했습니다 😀

2021-03-02 09:24 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let decisionStatus = userState - computerState
userWinStatus, computerWinStatus 상수로 지정해서 명확하게 값을 표현했습니다 🙃

2021-03-02 09:29 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +            inputNumbers = optionalInputNumber.split(separator: " ").map { Int(String($0)) ?? -1 }
- Map
기존의 배열에서 값을 제외하거나 추가하지는 않고, 존재하는 값을 변형시킬 때.
- compactMap
1차원 배열에서 nil을 제거하고 옵셔널 바인딩을 하고싶으실때는 compactMap 사용.
- flatMap
2차원 배열을 1차원 배열로 flatten하게 만들때 flatMap을 사용.

#### 직접 사용해보면서 차이점을 공부해보겠습니다 🔥

2021-03-02 14:16 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +        } else if validedNumbers.contains(validArrays.first!) == false {
#### guard ?

- `빠른 종료`의 핵심 키워드
- if 구문과 유사하게 `Bool 타입의 값`으로 동작하는 기능이다.
- if 구문과 다르게 항상 `else` 구문이 따라와야 한다.
- `else` **구문의 블록 내부에는 꼭 자신보다 상위의 코드 블록을 종료하는 코드가 들어가야 한다.**
  - 특정 조건에 부합하지 않다는 판단이 되면 재빠르게 코드 블록의 실행을 종료 
  - `return`, `break`, `continue`, `throw` 등 제어문 전환 명령어를 사용한다. 
    - 제어문 전환 명령어를 쓸 수 없는 상황이라면 사용이 불가능하다.
    - 함수나 메서드, 반복문 등 특정 블록 내부에 위치하지 않는다면 사용이 제한된다.
  - 또는 `fatalError()`와 같은 비반환 함수나 메서드를 호출할 수도 있다.
- if 코드를 훨씬 간결하고 읽기 좋게 구성할 수 있다.
  - if 구문을 사용하면 예외사항을 else 블록으로 처리해야 하지만 예외사항만을 처리하고 싶다면 `guard` 구문이 훨씬 간편하다.
- Bool 타입의 값으로 `guard` 구문을 동작시킬 수 있지만, 옵셔널 바인딩의 역할도 한다.
---
#### guard는 왜 guard일까요?
- 옵셔널 타입으로 인한 nil 부분을 가드한다(막는다, 보호한다) 이런 의미가 있지 않을까요? 🙂

---
저희 코드에서 if로 3가지 조건을 두었던 부분을 `복합 옵셔널 바인딩`을 활용해서 수정해봤습니다 🙃
또한 `!`를 guard 사용으로 제거했습니다. 더 열심히 `!` 를 지양해볼겠습니다 !!!!

2021-03-03 03:13 UTC, Fezravien commented
# [STEP 1] Rock Scissors Paper Game 🔥 - 2
@zieunv or @yagom 
### 안녕하세요 `cozy`!  Or `yagom` 😀

**cozy! 아프시다는 말을 들었는데 몸은 괜찮으신가요? 빠른 완쾌를 바라요** 💊

---

`Ian`과 함께 `재귀와 반복`, `if let, guard`. `오류처리` 에 대해서 고민을 많이 해봤어요 🤔

### 고민되었던 점 ⁉️

- **재귀와 반복**

  - 재귀 중에 작성된 변수는 스택에 저장되지만 반복에는 스택이 필요하지 않다.

  저희가 재귀 방식으로 로직을 짜서 실행해보니 스택에 불필요한 값이 쌓인 상태로 반환되어 결과값이 중첩되는 문제점이 존재했었어요 🤥

  그래서 반복문으로 로직을 교체했어요 😀

  

- **if let, guard**

  `yagom` 의 피드백으로 `guard` 에 대해서 한번더 찾아보면서 생각해봤어요 🤔

  - 특정 조건에 부합하지 않다는 판단이 되면 재빠르게 코드 블록의 실행을 종료 
  - if 구문을 사용하면 예외사항을 else 블록으로 처리해야 하지만 예외사항만을 처리하고 싶다면 `guard` 구문이 훨씬 간편하다.

  

  

- **오류처리** **(throws, do-catch, try)**

  - 특정 조건에 부합하지 않다는 판단이 되면 재빠르게 코드 블록의 실행을 종료

  `guard` 의 특징을 수행하기 위해 오류처리를 고민해봤어요  🤔



- **구조체와 열거형**
  - 게임의 결과, 상태값을 구조화 하기 위해 구조체와 열거형을 생각해봤어요 🙃

---


   <img width="500" alt="image" src="https://user-images.githubusercontent.com/44525561/109746965-a3db0a80-7c19-11eb-8c65-9daff52da7af.png">



---

### 조언을 얻고 싶은 부분 👂

저희는 구조화하기 위해서 구조체와 열거형을 생각했는데 혹시 좀 더 개선하거나 수정해야할 부분이나 방법이 있을까요? 🤔

2021-03-03 03:21 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> -import Foundation
https://developer.apple.com/documentation/foundation
공식문서에는 "Foundation은 앱에서 `필수 데이터 타입`, `컬렉션`, 및 `운영 체제 서비스`에서 접근하는 앱의 `기본 기능 계층`을 정의한다."
라는 정의를 볼 수 있었는데 `핵심 객체`라는 것이 `필수 데이터 타입`, `컬렉션`, 및 `운영 체제 서비스` 가 아닐까 생각합니다 🤔

2021-03-03 03:23 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func createComputerRandomNumber() -> Int {
컴퓨터의 랜덤값을 주문받고 정수를 반환하는 메소드이기 때문에 `create` 동사를 넣음으로써 `정수를 만들어서 준다`라는 메소드 역할에 맞는 이름이라 생각합니다 🤔

2021-03-03 07:08 UTC, yagom approved these changes
순환함수의 결과가 잘못된 결과였다면, 함수(메서드)를 호출한 로직이 잘못되지 않았을까요?
순환함수는 잘못이 없습니다. 그것을 사용하는 사람이 그렇게 해줬을뿐 ㅠㅠ
간단한 애플리케이션에서는 스택의 문제가 발생할 정도의 콜을 하진 않을것 같아요.

몇 가지 고민 포인트 남겨뒀습니다.

스텝2로 넘어가봅시다 :)

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +            }
do-try-catch!!! 👍

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func createRandomNumber() -> Int {
훨씬 범용적인 이름이 되었군요 :)

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let rock1Scissors2Paper3 = 1...3
오! 이름에 각 숫자의 의미를 넣는 방법이...!! 생각치도 못해봤어요!

enum의 allCases에 대해 알아볼까요?
allCases를 사용하려면 RockScissorsPaper는 어떤 모습인 것이 좋을까요?

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func isValidInput(userInput validInput: String?) throws -> Int {
던지는 메서드라니! 멋저요!

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func checkedInput(inputOptionalString OptionalString: String?) throws -> Int {
메서드 이름과 매개변수 이름의 고민이 필요할 것 같습니다

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let userComputerDraw = 0
1과 -2가 어떤 것을 의미하는지 이 코드만으로는 이해하기가 어렵습니다.

상수를 의미있게 다루는 방법에 대해 생각해보면 좋겠습니다.
즉, 로직의 코드에 상수(1, 2, -1 등등)이 출현하지 않도록 하는 방법이 없을까요?

2021-03-03 07:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +RockScissorsPaperGame().startGame()
이제 시작점 같군요!

2021-03-03 07:08 UTC, merged

2021-03-03 12:11 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- ErrorStatus -> GameRestart 
오류가 발생했을때 게임을 재시작하는 상황을 고려해서 이름을 생각해봤어요 🤔

- inputError -> inputValue
오류 케이스에서 오류를 다시쓰는 중복을 피하기 위해 inputValue로 수정했어요 🙃

2021-03-03 12:13 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- Result -> UserSideGameResult
Swift Standard Library에 Result 타입이 존재하므로 `유저 측면의 게임 결과`라는 의미로 수정했어요 🙃

2021-03-03 12:22 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
initStatus 에 -1을 할당하므로써 나머지 값들은 순차적으로 0, 1, 2, 3 입력되어요
추측을 한 것과 명시를 한 것을 비교를 하며 생각해보았는데 야곰이 말한대로 명시를 한 것이 눈에 훨씬 더 잘 보이네요 👍

2021-03-03 12:30 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- GameStatus -> Hand, GameConditions으로 세분화했어요 ➗

2021-03-03 12:40 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
- 현재 코드에 있는 구조체는 동작하는 로직에 있어서 도움이 되지는 않지만, 상태값을 더욱 명확하게 표현하기 위해 사용했어요 🙂
- let 앞에 `static`을 붙임으로써 인스턴스를 생성하지 않고도 사용할 수 있으며 타입에 해당하는 값이라고 알게되었어요

2021-03-03 12:44 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +        for _ in 0...Int.max {
- while true 에서 혹시나 무한 루프에 빠질 수 있기 때문에 그것을 방지하고자 큰 정수(9223372036854775807)로 반복했어요 
- 만약에 9223372036854775807 번의 경우의 수가 넘어가면 오류를 출력해서 사용자가 다시 시작하게 만들어주면 되지 않을까요? 🤔

2021-03-03 12:46 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +            }
Thx 🥳

2021-03-03 12:46 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func createRandomNumber() -> Int {
Thx ! 🤩

2021-03-03 12:58 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let rock1Scissors2Paper3 = 1...3
```swift 
enum GameStatus: Int {
    case initHandValue = -1
    case endGameValue = 0
}
enum HandShape: Int, CaseIterable {
    case rock = 1, scissors = 2, paper = 3
}
print(HandShape.allCases)
print(HandShape.allCases.map { $0.rawValue })

for value in HandShape.allCases {
    print(value.rawValue)
} 
```
RockScissorsPaper -> HandShape, GameStatus 조금 더 열거형을 상태에 맞게 세분화했어요 ➗

2021-03-03 13:00 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func isValidInput(userInput validInput: String?) throws -> Int {
Thx !! 🧑‍💻

2021-03-03 13:08 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func checkedInput(inputOptionalString OptionalString: String?) throws -> Int {
외부 매개변수는 `needValidInput`, `needCheckInput`로 받고, 내부 매개변수는 `userInput`으로 통일해봤어요  🙆‍♂️

2021-03-03 13:37 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let userComputerDraw = 0
```swift 
enum UserResultSituation: Int {
    case SelectWinRockScissors = 1
    case SelectWinScissors = -2
    case SelectLoseScissorsRock = -1
    case SelectLosePaper = 2
    case SelectDraw = 0
}

let userWinStatus = [GameConditions.userSelectWinRockScissors, GameConditions.userSelectWinScissors]
let computerWinStatus = [GameConditions.userSelectLoseScissorsRock, GameConditions.userSelectLosePaper]
let userComputerDraw = GameConditions.userSelectDraw
````
열거형에 숫자의 의미를 case로 나누어봤어요 ➗

2021-03-03 13:38 UTC, Fezravien commented on RockPaperScissors/RockPaperScissors/main.swift
> +RockScissorsPaperGame().startGame()
Thx !!! ␂