[Step1] James-Neph
yagom-academy/ios-rock-paper-scissors pull request #26
Opened 2021-03-02 02:36 UTC by Neph3779

@corykim0829 

## 조언을 얻고싶은 점
- getUserInput함수에서 optional string을 해제하기 위해서 한번, 그리고 Initializer을 통해서 해당 String을 새로운 Int 구조체의 인스턴스를 생성한 뒤 guard let으로 Int값을 추출했습니다.
총 두번의 guard let 구문이 사용되었는데 이것보다 효율적으로 구현할 수 있는 방법이 없을까요?

2021-03-02 11:24 UTC, corykim0829 requested changes
수고하셨습니다! 많이 고민하신 흔적들이 많이 보이네요 😃

전반적으로 깔끔하게 코드를 작성하시고 함수들의 책임 분리가 잘되어있어서 이해하는데 어렵지 않았습니다. 👍 
아쉬운 점은 코드들이 너무 붙어있어서 답답한 느낌이 있었습니다. 그래서 규칙을 정하여 함수 앞뒤에 공백줄을 넣기와 같은 걸 추가하면 보기가 더 깔끔할 것 같습니다!

마지막으로 커밋들을 봤는데, 규칙에 잘 맞추어서 하신 것은 잘하시고 계십니다! 다만 commit 타이틀에 `Feat 특정함수() 구현` 이러한 내용보다는 실질적으로 어떤 기능을 구현했다고 명시하는게 보기 더 깔끔할 것 같아요. 어차피 해당 커밋을 확인하기 때문에 어떤 함수를 구현하는지는 확인을 하기 때문에 `Feat: 사용자 입력 처리 구현` 이런식으로 하면 더욱 깔끔할 것 같습니다.

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func compareHands(_ user: Int, with computer: Int) -> GameResult {
- 함수명이 조금 아쉬운 것 같습니다! 양쪽 손을 비교한다는 의미는 전달이 됐지만, 보통 compare라 하면 대소를 비교하는데 많이 사용하고, GameResult라는 타입을 반환하기 때문에 조금 더 명확하게 바뀌면 좋을 것 같아요.
- 현재 `compareHands` 함수 인자로 사용자와 컴퓨터의 hand가 사용되는데, 이미 클래스 내부에 변수로 선언해놓았는데 굳이 또 인자로 전달해야할 이유가 있을까요? 두 개 중 하나에서만 사용해도 될 것 같습니다!

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var handOfUser = 0
`Int`로 선언된 이 변수들은 1, 2, 3이 아닌 다른 값이 들어가도 괜찮은 걸까요?

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch (user, computer) {
switch를 잘 활용하셔서 비교하셨네요! 좋은 아이디어 같아요! 😃👍

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func getUserInput() throws -> Int {
throw 에러 처리 잘하셨네요 😀

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch input {
여기서 input을 switch로 처리하고 있는데, GameResult enum 자체에서 처리할 수 있는 방법을 생각해보면 좋을 것 같아요.
switch 문이 많아지면 귀찮아지거든요 ㅎ

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func getUserInput() throws -> Int {
무조건 동사로 시작해야한다는 생각을 조금 덜어내고 명사형 함수 네이밍도 도전해보는건 어떨까요?
스위프트 공식문서 참고해서 네이밍에 조금 더 고민해보면 좋을 것 같아요!

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func initialize() {
RockScissorPaper 클래스를 초기화하는 함수 같은데, 사용자, 컴퓨터의 손만 초기화 하고 있어서 의미 전달이 조금 더 명확해질 수 있도록 함수명을 변경하면 좋을 것 같아요!

2021-03-02 11:24 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum GameResult {
`GameResult` enum은 `RockScissorPaper` 클래스 내부에 선언되어도 괜찮을까요?
`enum` 과 `nested enum` 차이를 알아보면 좋을 것 같습니다!

2021-03-02 11:28 UTC, corykim0829 commented
> @corykim0829
> 
> ## 조언을 얻고싶은 점
> * getUserInput함수에서 Optional String을 해제하기 위해서 한번, 그리고 Initializer을 통해서 해당 String을 새로운 Int 구조체의 인스턴스를 생성한 뒤 guard let으로 Int값을 추출했습니다.
> 
> 총 두번의 guard let 구문이 사용되었는데 이것보다 효율적으로 구현할 수 있는 방법이 없을까요?

두번 사용하셨는데 잘 사용하셨습니다! guard let을 연속으로 unwrapping 할 수 있기 때문에 그것도 찾아보면 좋을 것 같아요. `optional chaining`이라는 키워드로 찾아보세요~

2021-03-02 12:08 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let unsafeUserInput = readLine() else {
guard let 구문을 통해 unsafe한 user의 input을 safe하게 바꾼다!...
이런 의미로 적었는데 적절한지는 잘 모르겠네요 ㅠㅠ
guard let 뒤에 적어주는 변수명 짓기가 너무 어려운데 혹시 이 부분 조언해주실 수 있으신가요?

2021-03-02 12:11 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func compareHands(_ user: Int, with computer: Int) -> GameResult {
argument label을 활용해서
compareHands(handOfUser with: handOfComputer) 
이렇게 호출할 수 있으니 괜찮은 것 같다 생각했었어요
근데 지금와서 보니 handOfUser와 handOfComputer가 프로퍼티로 있으니 parameter를 전달할 필요가 없군요! 더 명확한 함수명으로 바꿔볼게요!!

2021-03-02 12:21 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var handOfUser = 0
음.. 그렇지 않아요 ㅠ
저희가 했던 생각은 만약 저희가 짠 코드에 논리적 오류가 있다면 0이 저 두개의 프로퍼티에 저장될 것이고 그러면 오류를 찾아낼 수 있을거라 생각했어요!.. 

근데 다시 생각해보면 유저 입장에서는 알 수 없는 오류로 인해 프로그램이 아예 다운되는 것보다 논리적인 오류가 발생하여 비정상적인 게임이라도 돌아가는 것을 원할 것 같네요 🥲

그런 의미에서 1...3 범위의 랜덤한 변수로 초기화해주도록 하겠습니다!

2021-03-02 12:34 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch input {
이 코멘트 덕분에 enum의 raw value에 대해 알게 되었어요!
raw value를 이용하여 switch문 없이 간단하게 바꿔봤습니다!

2021-03-02 13:03 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let unsafeUserInput = readLine() else {
아래 적어주신 Optional Chaining 키워드를 통해 검색했더니 하나의 guard 블록 안에 두 개 이상의 변수를 선언할 수 있다는걸 알게됐어요!
정말 속이 시원하네요 ㅎㅎ 뭔가 방법이 있을 것 같긴한데 어떻게 해야할지 몰랐거든요
감사합니다! 😆

2021-03-02 13:09 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let unsafeUserInput = readLine() else {
> guard let 구문을 통해 unsafe한 user의 input을 safe하게 바꾼다!...
이런 의미로 적었는데 적절한지는 잘 모르겠네요 ㅠㅠ
guard let 뒤에 적어주는 변수명 짓기가 너무 어려운데 혹시 이 부분 조언해주실 수 있으신가요?

safe하게 바꾸면 guard문을 뚫고 나온 친구는 safeUserInput이 맞지 않을까요? ㅎㅎ
optional 처리가 된 친구들은 대부분 해당 범위에서만 쓰여서 간단한 변수명으로 쓰는 것도 좋은 방법입니다!!

2021-03-02 13:10 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var handOfUser = 0
흠 제가 여쭤본 내용은 Int 타입인게 맞냐는 질문이었습니다! 두 프로퍼티 모두 0, 1, 2, 3 이라는 숫자밖에 갖지 않는데 Int 타입을 사용하는게 적합한지 의문이 들어서요! ㅎ

2021-03-02 13:17 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var handOfUser = 0
오! 이런데 쓰라고 있는데 `enum` 인거군요
당장 고치러 가보겠습니다 🏃💨

2021-03-02 13:31 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(input.rawValue)
rawValue를 직접적으로 사용하기 보다는 다른 변수로 접근해서 코드의 가독성을 높이면 좋을 것 같아요!

2021-03-03 01:46 UTC, Neph3779 commented
@corykim0829 

좋은 피드백들 감사합니다!! 😄

1차 피드백을 반영해서 commit 했습니다!
Optional Chaining과 enum에 대해 알아보고 바꿀만한 부분들을 바꾸어 주었어요

다만 아직도 noun 함수 네이밍에 대해서는 잘 모르겠습니다 ㅠㅠ
공식문서에는 noun만 가지고 명확히 설명이 되면서 자기자신을 mutate 하지 않는 메서드일 때
noun 네이밍을 한다고 적혀있는데 저희가 구현한 showMenu() 같은 함수도 이에 해당하니 show를 삭제하고 menu() 함수로 구현하는 것이 더 좋은 것일까요?..

2021-03-03 06:51 UTC, corykim0829 commented
> @corykim0829
> 
> 좋은 피드백들 감사합니다!! 😄
> 
> 1차 피드백을 반영해서 commit 했습니다!
> Optional Chaining과 enum에 대해 알아보고 바꿀만한 부분들을 바꾸어 주었어요
> 
> 다만 아직도 noun 함수 네이밍에 대해서는 잘 모르겠습니다 ㅠㅠ
> 
> 공식문서에는 noun만 가지고 명확히 설명이 되면서 자기자신을 mutate 하지 않는 메서드일 때 noun 네이밍을 한다고 적혀있는데 저희가 구현한 showMenu() 같은 함수도 이에 해당하니 show를 삭제하고 menu() 함수로 구현하는 것이 더 좋은 것일까요?..
> 
> > #### Step1을 바탕으로 Step2도 얼추 완성되었습니다! 이 브랜치를 merge해주시면 Stpe2도 Pull request 하도록 하겠습니다 ☺️☺️☺️

공식문서대로 하시면 될 것 같습니다 😀
반환하는게 있다면 noun형식으로 하는게 좋고 showMenu()는 적절하게 잘 지으신 것 같아요! 👏👏👏👏

2021-03-03 06:54 UTC, corykim0829 approved these changes
너무너무 수고하셨습니다! 👍

리뷰를 빠르게 반영해주셔서 놀랐습니다 ㅎㅎ

제가 마지막으로 해드린 리뷰들은 step2를 진행하면서 반영하시면 될 것 같습니디ㅏ!

2021-03-03 06:54 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case exit = 0
Hand 안에 exit가 있는게 조금 부자연스럽네요 exit는 다른 로직에서 처리하는게 좋지 않을까요?

2021-03-03 06:54 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand: Int {
enum 깔끔하게 잘 처리하셨습니다! struct로 하나의 타입으로 만들어도 된다는거 알아두세요 ㅎ

2021-03-03 06:54 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func returnResultOfGame() -> GameResult {
return, get이런 단어는 조금 피하는게 좋습니다!

2021-03-03 06:55 UTC, merged