[Step 1] Coda, Tak
yagom-academy/ios-rock-paper-scissors pull request #28
Opened 2021-03-02 07:58 UTC by Tak95

궁금한 점:
1. 게임 승패를 (컴퓨터의 수 - 사용자 입력값)의 결과에 따라 case로 나누어 봤는데 리뷰어의 입장에서 봤을 때 이해하기 편했는지 궁금합니다.
2. checkInputString() 메서드에서 default와 case "0"에서 inputNumber를 6이상으로 설정해주어야 그 아래 메서드인 makeResult에서 예외사항이 발생하지않습니다. 이걸 조금 더 깔끔하게 쓰고싶은데 어떻게 해야 좋을지 조언해주셨으면 좋겠습니다.

2021-03-02 09:43 UTC, Tak95 commented
@myssun0325

2021-03-02 18:16 UTC, myssun0325 requested changes
안녕하세요 Coda, Tak 반갑습니다. 아까 인사나눴던 메이슨입니다~ 잘 부탁드려요 🤠
궁금한 사항들은 언제든 DM이나 코멘트 남겨주시면 가능한 빨리 답변을 남겨드리도록할게용~
리뷰남긴 코멘트를 확인해보세요. (말씀해주신거처럼 0을 입력했을 때 버그가 있군요 🪲)

- 1번 궁금한점에 대한 답변 : 게임의 승패 결과를 case로 나눈건 굉장히 좋은 아이디어 같습니다👍 결과가 case별로 있다는 것을 잘 드러내신거 같습니다.(+ 코멘트를 확인해보세요)
- 2번 궁금한점에 대한 답변은 아래 코멘트로 대체하겠습니다.

✅start()메서드를 잘 작성하신거같습니다.
지금도 충분히 훌륭하지만 우리 메서드의 역할과 분리에 대해서 조금 더 연습해봅시다.
의도하신대로 일단 나열을해보자면

'안내문구 > 랜덤넘버를 선정(컴퓨터의 패) > 유저넘버 입력 > 유저넘버 입력체크(종료인지, 잘못된 숫자인지 등) > (process)결과가 무엇일까 (랜덤넘버와 유저넘버비교) > 결과 출력' 이 되겠죠?

```
// 문구
makeRandomNumber() // 랜덤넘버 선정
inputUserNumber() // 유저입력
checkInputString() // 유저입력 체크(종료인지, 잘못된 숫자인지 등) 
makeResult() // 결과가 무엇일지 프로세싱
.... // 결과 출력'
```
이 되겠죠??

- 유저넘버 입력체크(종료인지, 잘못된 숫자인지 등)메서드의 역할이 입력된 숫자가 어떤커맨드인지를 나타내는거라면 지금 작성된 메서드에서 옮겨져야할 것들이 있을거 같습니다. (결과를 출력하는 print라든지..)
- 게임의 결과를 만드는 로직과 결과를 출력하는 로직을 분리해보세요
- 위의 사항들로 분리를 해보고 2번 궁금증에 대한것을 다시 다뤄봅시당 :) 
- 메서드 네이밍: 보통 `make..`라는 메서드는 리턴값이 팩토리메서드(어려운 개념이라면 지금은 넘어가도 좋아요.)라는 네이밍으로 많이 활용됩니다. 느낌만 가져봅시다

```swift
// 내가 밀가루를 줄테니깐 빵으로 바꿔줘
let flour: Flour = Flour()
let bread: Bread = makeBread(ingredient: flour)
```
- 위의 make 관련된 내용은 Swift API Guidelines에서 찾을 수 있습니다. (캡쳐본을 첨부할테니 꼭 찾아서 읽어보세용)

<img width="760" alt="image" src="https://user-images.githubusercontent.com/26790375/109694656-669d5b00-7bce-11eb-9924-9ef0f9853eac.png">

코멘트를 적지 않게 남긴거 같네요. 리뷰어의 코멘트가 많다고 코드가 잘못되거나 한건 아닙니다. 코드의 정답은 없어요~ 지금도 충분히 좋은 코드지만 같이 더 개선할 수 있는 +를 찾는다고 생각하시면될거같아요!!
처음이라 많이 어려울 수 있어요~ 하지만 못해서가 아니라 익숙하지 않아서 그런거니깐 걱정마세요!!!
💪💪💪💪💪💪💪💪화이팅해봅시당

2021-03-02 18:23 UTC, myssun0325 commented
커밋 컨벤션을 잘 작성하셨습니다 👍
중간에 feat & refactor라는 커밋이 있군요 ~ 커밋의 단위도 나눠서 작아지도록 연습해보아요 :)

2021-03-02 18:36 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var inputNumber: Int = 0
private filepriavte 등과 같이 속성이나 메서드를 숨기는 것(은닉화)은 객체지향에서 굉장히 중요합니다

2021-03-02 21:02 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +   func checkInputString() {
입력값으로 만약 ‘문자열’이 들어온다면 어떻게 될까? 라고 생각했을 때, inputNumber만을 가지고 진행한다면, 문자열에 대한 case를 지정해줄 수 없지 않을까요?(nil)이 될테니까요!

2021-03-02 21:09 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +            inputNumber = 10
이 부분이 궁금한점 2의 발단입니다!
저희는 (컴퓨터수-유저수)를 케이스로 나누어 이기고 지는 결과값을 산출해냈어요. 그런데 만약 0을 입력했을 때 바로 종료가 되는 것이 이니라 makeResult 메서드가 실행된 후 빠져나오게 되는게 문제였습니다.

컴퓨터 수=2, 유저 수 =0이라면 
본래라면 게임 종료가 되어야 하나, 저희는 메서드가 하나 더 실행되면서 “사용자 승리”가 됩니다. 

Tak과 고민한 결과 이ㅂ혁된 값이 0이거나 1,2,3 이외의 것이라면 inputNumber에 일괄적으로 10이라는 수를 저장하고,
(컴퓨터수-유저수)의 값이 최대 -7이 되어 결과에 영향을 주지 않도록 설정했습니다. 저희도 이 과정이 꼼수처럼 느껴질 수 있어서 이 부분을 어떻게 고치면 좋을까 조언을 여쭈어본 것이었습니다!

2021-03-04 07:12 UTC, dacodaco commented on a.txt
> +# <타입>: <제목>
감사합니다 활용해보았어요!

2021-03-04 09:23 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let temporaryStorage: String? = readLine()
저희 나름대로 변수명을 좀 변경해보았습니다. :)

2021-03-04 09:23 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let temporaryString: String = temporaryStorage else { return }
미처 놓친 부분 알려주셔서 감사합니다 :):):):)

2021-03-04 09:24 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func makeResult() {
출력 메서드를 따로 구현했습니다!!

2021-03-04 09:26 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch (randomNumber - inputNumber) {
추후 묵찌빠 진행 시에 코드를 재활용하기 위해서 a, b, c 파라미터를 활용해보았습니다.
문제는 파라미터의 이름을 어떻게 지어야 할 지가 너무 어려워요
Tak과 함께 고민해봤는데, 메이슨의 조언을 조금 듣고 싶습니다. 
PR 본문에도 궁금한 점으로 남겨두겠습니다.

2021-03-04 09:28 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +            print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "") // printMenu func
메서드로 만드려고 했는데, 코드가 한줄이라 그냥 적는게 가독성이 더 높아보여 이렇게 진행했습니다!
아참, 각주는 지웠어요!

2021-03-04 09:30 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return
안필요했어요..ㅜㅜ

2021-03-04 09:30 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +            inputNumber = 10
새로 만들면서 삭제.

2021-03-04 09:31 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var inputNumber: Int = 0
은닉화에 대해서 아직 개념이 잘 잡히지 않아서,
공부를 더 진행해보도록 하겠습니다 :/

2021-03-04 09:53 UTC, Tak95 commented
@myssun0325 [Step1] 수정했습니다. 확인해주세요! :)

2021-03-04 20:40 UTC, myssun0325 approved these changes
Wow..더 읽기 편하고 로직도 더 심플해져서 이해하는데 더 쉬워졌습니다!!🤩
이번단계에서 했던 고민들과 함께 다음단계에서 코멘트에 대한 것들도 도전해보아요 :)

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +//  Created by Coda & Tak
이런 디테일까지..!!

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +///
불필요한 주석들을 조금 더 삭제해봅시다!

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +/** ## 가위바위보에 대한 기능(속성)과 메서드(행동)을 'RockPaperScissors 타입'으로 묶었음.
오호 !!?마크다운 문법을 사용하셨군요. 마치 공식문서를 보는느낌..

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func sortResult(a: Int, b: Int, c: GameDecision) { // #1 이 부분을 물어보고 싶습니다!!!!
물어보고싶은 부분이 있다면 주석보단 PR을 남긴 후에 코드에 코멘트를 활용하는 걸 추천드려요 :)
(a, b와 같이 의미없는 이름을 사용하는 것은 지양해야합니다.)
실제로 사용하는 곳에선 아래와 같이 사용되고 있는 메서드군요.
```swift
sortResult(a: randomNumber, b: inputNumber, c: gameMenu)
```
 Swift에서의 네이밍은 역할에 중점을 두고 있습니다. 축약보단 명확함을요.
메서드의 내용을 보아하니 GameDecision을 가지고 체크한 뒤에 컴퓨터의 수, 유저의 수를 가지고 gameCommand를 결정하는군요
- GameDecision체크도 이 메서드에서 해야하는 역할일까요? 컴퓨터의 수와 유저의 수를 가지고 gameCommand를 결정하도록 하는 한가지의 역할에 집중하도록 해보는건 어떨까요?
- 실질적으로 GameDecision이 start일때만 동작하는 메서드라면 외부에서 start일때만 이 메서드를 호출하는것과도 같겠군요!
- 메서드의 네이밍은 개인적인 의견으론 : "유저의 수와 컴퓨터의 수를 받아서 gameCommand를 결정하거나 세팅한다"를 표현할거같아요. 네이밍을 한번만 더 고민해보면 어떨까요?

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func checkInputNumber() -> Bool {
오! 반환값을 활용하셨군요 멋집니다 👍👍👍

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func makeRandomNumber() {
make라는 메서드를 쓴다면 반환값을 갖도록, 내부 프로퍼티를 변경하는 메서드라면 다른 이름을 고민해보는건 어떤가요?

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func checkInputNumber() -> Bool {
메서드명으로 "유효한 입력을 받았니?"라고 물어볼 수 있는 이름을 지어보는건 어떨까요? (ex: isValidInputNumber)

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch checkInputNumber() {
switch문을 쓰신것도 좋지만 Bool값이라면 `if checkInputNumber() { } else { }`를 활용해볼 수도 있을거같네용!
아니면 이번에 guard는 확실하게 하고 간다고하셨으니 
```
guard checkInputNumber() else { ... } 
```
를 활용해보는 것도 뎁스를 쭐이면서 사용할 수 잇는 방법일거같습니다.

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                gameCommand = GameResult.error
메서드가 gameMenu를 정하는 메서드 같은데 여기서 이 경우에만 gameCommand를 결정하는게 좀 아쉬운데 gameCommand를 여기서 할당하지 않도록 개선해 볼 수 있을까요?

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var gameMenu: GameDecision = GameDecision.restart
변수명은 gameMenu인데 타입은 GameDecision이군요 개선해볼 수 있을까요?!

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var inputString: String = ""
사용하지 않는 프로퍼티입니다 🚀

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            switch inputNumber {
inputNumber를 체크하는 메서드로 또 더 작게 나눠볼 수 있을거같네용!

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rockPaperScissors = RockPaperScissorsGame() //인스턴스화
많은 경우 코드 윗줄에 주석을 남기도록 합니다. 추가적으로 통일을 위해 
//를 쓰고 바로 코멘트를 다는것과 // 를 쓰고 한칸 띄고 코멘트를 다는 것 중 하나를 선택하여 통일감을 주도록 하는건 어떨까요?

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +/*
아래의 주석은 필요한 부분인가요?

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func initializeNumbers() {
👍멋져부려

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func start() {
start가 무엇을 start하는지 조금더 명확성을 줘볼까요?

2021-03-04 20:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch (randomNumber - inputNumber) {
해당 코드에 코멘트 남겨두었습니다!

2021-03-04 20:41 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +   func checkInputString() {
해결하신거 같군요 안쓰는 프로퍼티는 삭제하길 권유하며 코멘트 남겨두었습니당

2021-03-06 03:51 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch checkInputNumber() {
일단 guard 문으로 고쳐보았습니다 :):)

2021-03-06 03:55 UTC, dacodaco commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func start() {
헉 미쳐 못보고 지나쳤었네요..!!! 곧 수정해두겠습니다.

2021-03-06 06:40 UTC, myssun0325 reviewed
Coda, Tak 수고하셨습니다! 👏
처음보다 코드의 뎁스도 줄고 무엇을 할지 명확해져가고 있습니다 🚀
남겨진 코멘트를 확인하시고 이번스텝에서 적용못하더라도 꼭 다음스텝에서 고민해보시길 바래요!

2021-03-06 06:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if isValidInputNumber() == true {
[참고] 반환값 자체가 Bool이기 때문에
`if isValidInputNumber() { ... } `를 사용할 수 있습니다.

2021-03-06 06:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var DecisionAboutGamePlay: GameDecision = GameDecision.restart
변수명이 대문자로 시작하네요! 😱

2021-03-06 06:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            DecisionAboutGamePlay = GameDecision.restart
실질적으로 프로퍼티가 GameDecision.restart 가 기본값으로 세팅되어있기 때문에 `if validInputNumber()`의 로직은 불필요해보이네요

2021-03-06 06:40 UTC, myssun0325 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if DecisionAboutGamePlay == GameDecision.exit {
guard와 if를 비교해서 공부해보세용 :)

2021-03-06 06:40 UTC, merged