[STEP 1] JM, Sunny
yagom-academy/ios-rock-paper-scissors pull request #30
Opened 2021-03-02 09:00 UTC by CJMIN

담당 리뷰어 태그 : ex) @붱이(O-O-wl)

# 1번째 STEP

# :pushpin: 코드를 작성할 때 고민되었던 점 :

1. 플로우차트의 가독성을 높이는 방법이 고민되었습니다.
(플로우차트의 가독성을 높이기 위해 화살표의 색을 구분지어봤습니다.)
<img width="1035" alt="스크린샷 2021-03-02 오후 5 54 08" src="https://user-images.githubusercontent.com/46758264/109623283-5494cb80-7b80-11eb-9321-a46e1658a157.png">
2. 변수명 작성 방법.
3. 코드 작성 기준(가독성 등등)
4. 클린코드 작성 방법

# :pushpin: 해결이 되지 않은 점:
1. 플로우차트의 가독성을 높이는 방법
2. 변수명 작성 방법.
3. 코드 작성 기준(가독성 등등)
4. 클린코드 작성 방법

# :pushpin: 조언을 얻고 싶은 부분 :
1. 변수명 작성 방법.
2. 코드 작성 기준(가독성 등등)
3. 클린코드 작성 방법

2021-03-02 09:23 UTC, yagom commented
붱이의 깃헙 아이디를 태그해야 붱이가 이 PR을 볼 수 있을거예요.
@ 뒤에 붱이를 선택할 수 있는 드롭다운이 나왔던가요? 
위에처럼 태그하면 붱이는 이 PR을 볼 수 없습니다.

2021-03-03 07:00 UTC, O-O-wl requested changes
고생하셨습니다 Sunny JM!
몇가지 코멘트 남겼습니다.

플로우 차트에 세부 구현사항들이 들어가서 읽기 어려워진 것 같아요
플로우 차트에 말그대로 플로우들을 명시하는 건 어떨까요?
사용자 1 - 컴퓨터 1  과 같은 세부 구현보다 **승패 비교**와 같은 하나의 작업으로 표시하는 것도 좋을 것 같아요

변수명을 짓는데 어려움을 겪으신다면 
[ 🎨 Swift API Design Guideline](https://swift.org/documentation/api-design-guidelines/)를 참고하면 큰도움이 되실 거에요 🙇‍♂️

2021-03-03 07:00 UTC, O-O-wl commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
처음 설정된 랜덤한 값을 계속 사용하는 것 같네요
비겨서 다시 가위바위보를 할때 컴퓨터는 이전에 낸 값을 그대로 내는 건가요!?

2021-03-03 07:00 UTC, O-O-wl commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return
while문은 조건에 따라 반복을 수행하는 구문이에요
```swift
while (condition) { 
 // do something
} 
```
항상 condition을 true로 설정하면 
while true 까지만 읽었을 때는 이 구문은 무한히 반복된다고 오해할 수 있을 것 같아요.
대신
```swift
var isContinue: Bool
while isContinue {
// do something
}
```
과 같은 형태로 condition을 잘 이용하면 특정 조건에 따라 반복되는 것이라는 걸 명시적으로 잘 표현할 수 있을 것 같아요

2021-03-03 07:00 UTC, O-O-wl commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let userInputIsInt = userInput else {
**userInputIsInt**를 번역해보면 **사용자의 입력은 정수이다.** 로 되겠네요.
이러한 명제형태의 변수명은 Bool같은 참거짓을 나타내는 변수명으로 통상적으로 쓰이고 있어요.
ex) `Array.isEmpty` , `String.isEmpty` `10.isMultiple(of: 2)`
다른 네이밍을 찾아볼까요?!

2021-03-03 07:00 UTC, O-O-wl commented on RockPaperScissors/RockPaperScissors/main.swift
> +                print("졌습니다!")
반복적인 로직들이 보이네요
여기서 규칙을 한번 정리해보면 하나하나 비교하지 않으면서도 로직을 구현할 수 있을 것 같아요
- 컴퓨터와 같은 값이면 비긴다
- 자신이 컴퓨터보다 + 1인 값이면 이긴다.
- 나머지는 진다

% 모듈러스 연산자에 대해서 공부해보면 더 쉽게 구현하실 수 있을수도!?

2021-03-03 07:00 UTC, O-O-wl commented on RockPaperScissors/RockPaperScissors/main.swift
> +var randomNumberOfComputer: Int = 0
computer의 number가 random으로 결정된다는 사실까지 변수명에 표현하고 있군요.
자세한 설명이 될 수 있겠지만, 우리가 표현하고자 하는 의도를 명확하고 간결하게 네이밍해보는 건 어떨까요?

2021-03-03 07:00 UTC, O-O-wl commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
if 문과 guard문은 어떤 차이가 있을까요?

2021-03-05 00:14 UTC, unme88 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
고쳤습니다. 비긴 경우 firstFlag = false을 넣어줘서 컴퓨터 랜덤 값을 다시 계산하도록 했습니다.

2021-03-05 00:15 UTC, unme88 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return
말씀해주신데로 var isContinue: Bool
while isContinue로 고쳐봤습니다 ^.^

2021-03-05 00:17 UTC, unme88 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let userInputIsInt = userInput else {
네 일단 UserIntInput으로 바꿔봤습니다.

2021-03-05 00:23 UTC, unme88 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var randomNumberOfComputer: Int = 0
네 좀 더 간결하게 표현하기 위해
userIntInput을 userNumber로
randomNumberOfComputer을 computerNumber로 변경해봤습니다.

2021-03-05 00:28 UTC, unme88 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            continue
guard문으로도 작성해보고 바꿔보도록 고려해보겠습니다! 감사합니다 :)

2021-03-05 00:35 UTC, unme88 commented
> 고생하셨습니다 Sunny JM!
> 몇가지 코멘트 남겼습니다.
> 
> 플로우 차트에 세부 구현사항들이 들어가서 읽기 어려워진 것 같아요
> 플로우 차트에 말그대로 플로우들을 명시하는 건 어떨까요?
> 사용자 1 - 컴퓨터 1 과 같은 세부 구현보다 **승패 비교**와 같은 하나의 작업으로 표시하는 것도 좋을 것 같아요

말씀해주신데로 세부 구현사항들을 지우고
승패 비교 함수를 넣는 것으로 플로우가 더 잘 보일 수 있게 플로우차트를 변경했습니다.

2021-03-05 01:19 UTC, CJMIN commented
담당 리뷰어 태그 : ex) @O-O-wl 

1번째 STEP

위에서 리뷰해주신 부분들 수정했습니다.

# 📌 조언을 얻고 싶은 부분 :
rockPaperScissorResult 함수명에 대해서 조언을 얻고 싶습니다.

2021-05-31 01:06 UTC, closed without merging