[STEP 1] Jay, Bobby (3A)
yagom-academy/ios-rock-paper-scissors pull request #31
Opened 2021-03-02 09:09 UTC by helloworldjay

## reviewer: @corykim0829 

## 코드를 작성할 때 고민되었던 점 :
    - Int 함수 결과물이 optional인지 몰라서 고민 했습니다.
    - if let vs guard let 팀 코드에서 어느 것이 더 나은지

## 조언을 얻고 싶은 부분 :
    - convertUserSelection에서 return -1을 더 효율적으로 처리할 방법
    - 파라미터 명과 대입 값의 이름이 같아도 괜찮은지 여부
    - 여러 함수에서 파라미터 명이 같아도 관계 없는지

리뷰 감사합니다! :)

2021-03-02 11:52 UTC, corykim0829 requested changes
정말 수고 많으셨습니다! 함수명에 고민한 흔적도 많이 보이고, 코드도 깔끔하게 작성해주셨네요! 👍👍👍👍

리뷰 해드린 것도 다 보시겠지만 피드백 반영하시면서 전체적인 로직의 흐름을 한번 더 고민해보면 좋을 것 같습니다. 지금은 getUserSelection() 함수부터 시작해서 어느 순간에서 다시 startGame()으로 돌아가서 이러한 전체적인 흐름을 한번에 캐치할 수 있도록 고민해보면 좋을 것 같아요!

정말 수고 많으셨어요!

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +struct RockScissorsPaper {
struct로 `RockScissorsPaper ` 객체를 생성하신 이유가 있을까요?
struct와 class의 차이가 무엇인가요?

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func getUserSelection() -> Void {
함수명을 보면 사용자의 선택을 가져오는 함수 같은데, 출력함수가 두개나 있네요. 함수가 하나의 일만 하도록 나눠 보면 좋을 것 같아요!

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if let userSelection: String = readLine() {
`readLine()`은 String 타입을 반환하는 함수이기 때문에 String 타입을 선언해줄 필요가없습니다!

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if let userSelection: String = readLine() {
여기 if let 에서 nil값으로 나오면 어떻게 처리되나요?

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return -1
여기서 -1이 의미하는게 무엇일까요? 문서를 따로 보지 않으면 어떤 의미인지 코드만 보고서는 알기 어렵네요 ㅜ

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func checkValidUserSelection(userSelection: String) -> Bool {
함수명 끝에 UserSelection과 인자의 userSelection이 중복되네요 보통 이런경우에는 어떻게 네이밍을 하는지 스위프트 공식 문서에서 확인해보시면 좋을 것 같습니다 😃

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let newGame: RockScissorsPaper = RockScissorsPaper()
보통 인스턴스의 이름은 `rockScissorsPaper` 이렇게 객체명의 소문자형태로 쓰는게 정석입니다 참고하세요!
또한 `RockScissorsPaper()`와 같이 객체로 인스턴스를 생성하면 타입이 확실하기 때문에 타입을 명시할 필요가 없습니다!

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func getUserSelection() -> Void {
Swift에서는 함수의 반환값이 없으면 Void는 명시하지 않습니다!

2021-03-02 11:52 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let criterion: Int = (userChoice - randomRockScissorsPaperChoice + 3) % 3
와우 😀 신기한 계산식이네요! 👍👍👍

2021-03-02 11:58 UTC, corykim0829 commented
> ## reviewer: @corykim0829
> ## 코드를 작성할 때 고민되었던 점 :
> ```
> - Int 함수 결과물이 optional인지 몰라서 고민 했습니다.
> - if let vs guard let 팀 코드에서 어느 것이 더 나은지
> ```
> 
> ## 조언을 얻고 싶은 부분 :
> ```
> - convertUserSelection에서 return -1을 더 효율적으로 처리할 방법
> - 파라미터 명과 대입 값의 이름이 같아도 괜찮은지 여부
> - 여러 함수에서 파라미터 명이 같아도 관계 없는지
> ```
> 
> 리뷰 감사합니다! :)

## 코드를 작성할 때 고민되었던 점 :

Int 함수 결과물이 optional인지 몰라서 고민 했습니다. 
➡️ 이부분은 어떤 부분을 말하는지 잘 이해가 안가네요! 예시와 함께 알려주시면 감사하겠습니다 ㅎ

if let vs guard let 팀 코드에서 어느 것이 더 나은지
➡️ 일단 guard는 예외를 처리하는데 주로 사용됩니다. guard 공식문서를 확인하셔서 if와 차이점을 먼저 알아보시고 코드에 한번 적용해보시고 차이점을 직접 느끼시면 좋을 것 같아요!

## 조언을 얻고 싶은 부분 :
convertUserSelection에서 return -1을 더 효율적으로 처리할 방법
➡️ 해당 함수에서 Int를 반환하는 로직을 변경하거나 / -1이 아닌 다른 형태로 예외 처리를 하거나 / -1을 상수화 하거나 / ... 
직접적인 해답은 제시해드리지 못하구요..ㅎ 너무 하나에 고민하지 말고 다른 방식을 고민해보는 것도 좋은 것 같습니다!


파라미터 명과 대입 값의 이름이 같아도 괜찮은지 여부
➡️ 같아도 괜찮습니다. 다만 같으면 보통 인자명을 생략합니다!

여러 함수에서 파라미터 명이 같아도 관계 없는지
➡️ 이 부분은 리뷰로 답변 해드렸습니다!!

이 질문을 늦게봐서 조금 리뷰랑 꼬여버린 기분이 있네요 🥲
답변들이 도움이 되길 바라며 화이팅입니다!!

2021-03-03 00:49 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func checkValidUserSelection(userSelection: String) -> Bool {
수정했습니다!

2021-03-03 00:56 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +let newGame: RockScissorsPaper = RockScissorsPaper()
인스턴스의 이름은 newGame이라서 소문자 형태로 쓰고 뒤에 Rock-은 구조체의 이름이라 대문자로 적었었는데 타입이 확실해서 생략하도록 하겠습니다! 혹시 그럼 인스턴스를 생성할 때는 대부분 객체 타입 명시를 생략해줄까요?

2021-03-03 01:05 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if let userSelection: String = readLine() {
else를 만들었습니다!

2021-03-03 01:06 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return -1
의미를 가진 변수를 생성해서 처리했습니다 :)

2021-03-03 01:11 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func getUserSelection() -> Void {
게임 시작시 출력은 게임 시작 함수로 옮기고 재시작은 함수를 따로 생성해서 재시작하게 만들었습니다!

Void는 삭제했습니다!

2021-03-03 01:20 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +struct RockScissorsPaper {
현재 코드에서 상속의 개념이 없고, 단일한 객체 하나를 생성해서 클래스가 아니여도 괜찮다고 생각했습니다. 저희가 찾아본 바로는 
```
1. 구조체는 값 타입, 클래스는 참조 타입으로 연관된 간단한 값의 집합을 캡슐화하는 것만이 목적일 때 
2. 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할 때 
3. 상속이 필요가 없을 때
```
애플에서 구조체를 사용하는 것을 권한다고 나와서 구조체를 사용하게 되었습니다.

2021-03-03 06:57 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +struct RockScissorsPaper {
RockScissorsPaper 값을 참조하는 일이 많을까요 복사하는 일이 많을까요? 아직은 파일이 크지 않아서 큰 문제가 없지만, 퍼포먼스를 고려하여 struct와 class를 선택하는 것은 큰 고민거리 중 하나라는거 알아두시면 좋을 것 같아요 😃

2021-03-03 07:00 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let newGame: RockScissorsPaper = RockScissorsPaper()
```Swift
let rockScissorsPaper = RockScissorsPaper()
```
이 정석이긴 하지만, newGame이라는 의미를 명확하게 주고 싶다면 newGame을 사용하셔도 괜찮습니다. `RockScissorsPaperGame`이라고 하면 조금 더 클래스의 의미가 명확해질 것 같네요 ㅎ

```Swift
let rockScissorsPaper: RockScissorsPaper = RockScissorsPaper()
```
위와 같이 작성하면 너무 중복되는게 많아서 보기가 좋지 않아서 생략하는게 일반적입니다 ㅎ

2021-03-03 07:20 UTC, corykim0829 requested changes
수고 많으셨습니다 ㅎ 👍👍👍👍

스위프트의 타입추론 기능을 이해하고 코드를 접근해보면 좋을 것 같아요! 

로직에 대해 고민은 해보지만 너무 크게는 바꾸지 않고 일단 코드의 가독성을 높이는 것에 집중하고, 
step2를 진행하면서 로직을 변경하면 좋을 것 같네요 ㅎ

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
들여쓰기 정리해주세요!

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                let convertedUserSelection: Int = convert(userSelection)
여기서도 타입 명시를 하지 않으셔도 됩니다. convert 함수의 반환값이 Int인거는 금방 알 수 있는 사실이니까요!

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func convert(_ userSelection: String) -> Int {
convert라는 함수를 보면 그냥 동작만하고 반환값이 없을 것 같다는 생각이 드네요!
반환하는 값이 있다면 명사형 함수형도 한번 해보시는 것도 좋을 것 같아요
스위프트 공식문서 보고 한번 고민해보면 좋을 것 같아요 ㅎ

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func restartGame() {
이런 로직으로 재귀방식으로 진행되면 반복문을 사용하는 것과 어떤 장단점이 있을까요?

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func checkValidation(_ userSelection: String) -> Bool {
함수명이 훨씬 깔끔해질 것 같네요! 아래 리뷰 참고하셔서 명사형 함수명도 고려해보세요 ㅎ

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("가위(1), 바위(2), 보(3)! <종료:0> : ", terminator: "")
print를 하는 부분도 따로 함수로 빼면 가독성도 좋고 관리도 더욱 쉬울 것 같아요 ㅎ

2021-03-03 07:20 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return notIntError
이렇게 구현하면 여기서는 notIntError인 것을 알 수 있지만 이 반환값을 받는 곳에서는 -1이라는 것밖에 모르지 않을까요?
조금더 고민해보면 좋을 것 같아요 ㅎ

2021-03-03 07:39 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +struct RockScissorsPaper {
네 감사합니다! 뒤에 작업하면서 class로 변경하였습니다! ㅎㅎ

2021-03-04 00:39 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +let newGame: RockScissorsPaper = RockScissorsPaper()
네! 변경하도록 하겠습니다!

2021-03-04 00:43 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if let userSelection: String = readLine() {
삭제했습니다! :)

2021-03-04 07:13 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
수정했습니다! :)

2021-03-04 09:37 UTC, helloworldjay commented on RockPaperScissors/RockPaperScissors/main.swift
> +                let convertedUserSelection: Int = convert(userSelection)
명시 삭제했습니다!

2021-05-31 01:06 UTC, closed without merging