[Step 1] Steven, Ryan
yagom-academy/ios-rock-paper-scissors pull request #33
Opened 2021-03-02 12:38 UTC by ryan-son

@seizze 

안녕하세요, 하이디! 처음 뵙겠습니다! Steven, Ryan입니다. 잘 부탁드릴게요~!  😆

미숙하지만 저희 최대한 처음 코드를 접한 사람이 이해할 수 있었으면 좋겠다는 마음으로 코드를 짜보았습니다.

저희가 성장할 수 있도록 맹렬한 지적 부탁드립니다! 

## 코드 작성 시 고민한 점
- **개행 스타일**: 현재는 상수/변수부와 메서드부 사이에 개행을 한 번만 사용했습니다.
- **메서드 단위**: 개별 메서드가 적은 기능을 수행하도록 메서드를 기능별로 최대한 분할해보았습니다.
- **메서드, 프로퍼티, 변수/상수명**: 어떤 손 모양을 냈는지의 작명을 choice로 할지, handSign으로 할지 등
- **실제와 같은 상황을 모사하여 타입 구현**: 컴퓨터와 사용자에게 각각 Player 클래스의 인스턴스를 부여
- **승리 판단 로직**: 1, 2, 3 중 두 수를 선택하였을 때 1 차이만큼 큰 수가 이기되 3은 1이 이긴다 -> 나머지 연산 활용하여 컴퓨터가 제시한 수를 이기는 수를 먼저 도출 (이기는 수 = 컴퓨터가 고른 수 % 3 + 1) -> 사용자의 선택이 이기는 수이면 승리, 컴퓨터와 같으면 비김, 아니면 패배

## 해결이 되지 않은 점
- checkInvalidInput(of userInput:) 메서드는 사용자 입력이 0~3에 해당하지 않는 경우 에러 구문을 출력합니다. 따라서 게임 에러 출력을 위해 getUserInput() 메서드에서 유효하지 않은 입력 (0 ~ 3에 해당하지 않는 Int)를 return 해주어야 합니다 (). 이를 위해 열거형으로부터 0 ~ 3에 해당하지 않는 Int형 rawValue를 GameError 열거형으로부터 불러와 에러 처리에 활용하고 있는데 이것이 처음 코드를 접하는 프로그래머에게 이해가 되지 않을 수 있다는 점을 해결하지 못했습니다 (rawValue를 각각 -1, -2라고 지정한 이유가 없기 때문).

## 조언을 얻고 싶은 부분
- 타입 내부 프로퍼티를 변경할 필요가 있는 경우 (본 프로젝트에서는 사용자의 숫자 입력의 형변환 String -> Int), 레퍼런스 타입과 값 타입, 메모리 관리 종합적인 측면에서 클래스와 구조체 중 어떤 것으로 구현하는 것이 좋은가요? 혹은 관련해서 알아보려면 어떤 것을 공부하여야 하나요?
- 프로토콜, 익스텐션으로 구현하였을 때의 장점은 무엇이 있나요? 학습한 문법을 사용해본 것이라 사용한 이유가 빈약합니다.
  -  저희가 생각한 장점은 필요한 프로퍼티와 메서드가 있을 경우 타입에 관계없이 프로토콜을 준수한다고만 선언하면 바로 미리 정의한 프로퍼티와 메서드를 재사용 가능하다는 점이 있습니다.
  - 해당 문법을 처음 적용해봤는데 현업에서 사용할 수 있는 방법인가요? 
  - 이런 코딩 스타일은 좋은 습관인가요, 나쁜 습관인가요?
  - 소규모 프로젝트에도 유효한 방법인가요?

2021-03-02 13:34 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
Error 타입을 새로 만드신 것, 아주 좋습니다

2021-03-02 15:27 UTC, seizze requested changes
여러 타입들을 만들고, 각 객체의 기능을 고민해 나눈 점이 보였습니다.
또한 TIL을 보니 이번에 일반화, 추상화 등의 객체지향적인 개념을 배우셨던데, 배운 내용을 활용해 보려는 점도 좋았습니다.

다만 아쉬운 점은 페어 프로그래밍인데 커밋이 한 사람의 것만 보이네요. 페어 프로그래밍에서 네비게이터와 드라이버의 역할을 잘 나눠 보고, 일정 시간이 지나면 드라이버가 커밋하는 방식도 고려해 보세요~

다음은 PR에 남겨주신 사항들에 대한 코멘트입니다.

> checkInvalidInput(of userInput:) 메서드는 사용자 입력이 0~3에 해당하지 않는 경우 에러 구문을 출력합니다. 따라서 게임 에러 출력을 위해 getUserInput() 메서드에서 유효하지 않은 입력 (0 ~ 3에 해당하지 않는 Int)를 return 해주어야 합니다 (). 이를 위해 열거형으로부터 0 ~ 3에 해당하지 않는 Int형 rawValue를 GameError 열거형으로부터 불러와 에러 처리에 활용하고 있는데 이것이 처음 코드를 접하는 프로그래머에게 이해가 되지 않을 수 있다는 점을 해결하지 못했습니다 (rawValue를 각각 -1, -2라고 지정한 이유가 없기 때문).

실패할 경우 에러를 리턴하고 싶고, 성공할 경우 사용자 입력을 리턴하고 싶은것이군요~ 스위프트의 Result 타입에 대해 알아보면 좋을 것 같아요.의미를 갖지 않는 Int형 rawValue는 피하는 편이 좋습니다.

> 타입 내부 프로퍼티를 변경할 필요가 있는 경우 (본 프로젝트에서는 사용자의 숫자 입력의 형변환 String -> Int), 레퍼런스 타입과 값 타입, 메모리 관리 종합적인 측면에서 클래스와 구조체 중 어떤 것으로 구현하는 것이 좋은가요? 혹은 관련해서 알아보려면 어떤 것을 공부하여야 하나요?

클래스와 구조체는 절대적으로 어떤 게 더 좋다기 보다는 상황에 따라 적절한 걸 선택해야 하고, 그러기 위해 둘의 차이를 잘 알아둬야 하는데요. 말씀하신 타입 내부 프로퍼티를 변경할 필요가 있는 경우에도 꼭 클래스로 작성해야 하는 것은 아닙니다. 구조체를 선택 후 내부 프로퍼티 변경이 필요하다면 계속해서 새 인스턴스를 만드는 방법도 있어요

성능 측면에서 둘의 차이에 대해 더 자세한 내용을 알고 싶다면 [Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)라는 세션이 있어요~ 한국어 버전은 [여기](https://www.youtube.com/watch?v=z1Gf6EosaUQ)
지금 이해하기엔 너무 어려울 수도 있으니 (정말 보고 싶다면) 앞쪽 클래스와 구조체 부분만 보시는게 좋을거 같아요.

> 프로토콜, 익스텐션으로 구현하였을 때의 장점은 무엇이 있나요? 학습한 문법을 사용해본 것이라 사용한 이유가 빈약합니다.

이 부분은 조금 더 경험이 쌓이고 어떨 때 좋은지, 어떨 때 문제가 생기는지를 스스로 판단해 보는게 좋을 것 같아요. 일단 프로토콜을 채택만 하면 미리 정의해 둔 기능을 편하게 갖다 쓸 수 있다는 장점도 맞고, 현업에서 실제로 그렇게 사용하기도 해요. 하지만 편리한 만큼 대규모 프로젝트로 갈수록 문제가 되는 부분이 있기도 합니다.

그럼 스텝 2도 기대할게요!

2021-03-02 15:27 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func comparePlayersHands() {
단지 비교 보다는 조금 더 구체적으로 "승자를 판단한다"는 의미가 포함되면 더 의미가 잘 전달될 것 같아요.

2021-03-02 15:27 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +game.play()
이런 부분은 스위프트 API Design Guidelines의 [Strive for Fluent Usage](https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage) 부분을 잘 지켰다고 볼 수 있겠습니다! 굿굿

2021-03-03 08:15 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
추가로, 추상화를 시도할 때 주의할 점은 좀 더 일반적인 개념을 사용해야 한다는 것입니다.
"랜덤 숫자 발생" 이라는 (추상적인)기능은 결과가 묵찌빠인게 맞을까요? RockPaperScissors 타입이 RandomNumberGenerator 프로토콜을 채택한다면, "묵찌빠는 랜덤 숫자 발생을 할 수 있다"라는 개념이 자연스러울까요?

추상화와 그 구현체(여기선 RockPaperScissors 타입)의 관계를 설정할 땐 이와같은 고민을 해 보셨으면 좋겠습니다 :)

2021-03-04 07:56 UTC, ryan-son commented
@seizze 

하이디!

### 접근 제어
> 메서드들을 private으로 은닉화하신 것 아주 좋습니다. 하지만 프로퍼티의 은닉화는 더더 중요합니다!
프로퍼티는 가장 먼저 private를 고려해 보고, 필요에 따라 private(set) 등으로 개방 단계를 올리는 것을 추천합니다.

외부에서 수정, 접근이 필요 없는 요소는 private, 접근만 해야하는 경우 private(set)으로 변경하였습니다.

### rawValue 은닉화
> 아마 input으로 enum 인스턴스를 생성하기 위해 각 case가 숫자를 가지도록 만든걸로 보여집니다.
enum 타입이 채택할 수 있는 CaseIterable 프로토콜에 대해 한번 알아보세요. 각 case가 숫자를 가지지 않고도 랜덤한 case의 인스턴스를 생성할 수 있습니다.
이렇게 int 값과 연관지은 뒤 rawValue를 외부에서 직접 사용하는 방식은 은닉화를 잘 하지 못했다고 볼 수 있습니다.
아래쪽 코드들에서도 computer.handSign.rawValue % 3 + 1등과 같이 rawValue를 직접 사용하고 있는데, 이 부분들도 함께 개선해 본다면 좋은 학습이 될 수 있을 것 같네요!

가위바위보 열거형 타입 안에 `index()` 메서드를 통해 각 케이스의 rawValue에 접근할 수 있도록 구현하였습니다.

### CaseIterable 프로토콜 채택
> 일단 protocol에 extension을 활용해 기본 구현을 제공하신 부분 좋습니다 👍
또한 "랜덤 숫자 발생" 기능을 프로토콜로 추상화하신 점도 좋네요~
개선해볼 점은, RockPaperScissors 타입이 자신의 데이터를 그대로 오픈하고 수동적으로 동작하고 있는데 random한 case를 만들어주는 기능을 RockPaperScissors 타입에서 능동적으로 수행하게 만들고, 상위에서는 RockPaperScissors.random() 등으로 호출만 하도록 만들면 더 객체지향적인 코드가 될 것 같습니다. 그렇게 된다면 이 기본 구현은 없어질 수도 있겠네요
추가로, 추상화를 시도할 때 주의할 점은 좀 더 일반적인 개념을 사용해야 한다는 것입니다.
"랜덤 숫자 발생" 이라는 (추상적인)기능은 결과가 묵찌빠인게 맞을까요? RockPaperScissors 타입이 RandomNumberGenerator 프로토콜을 채택한다면, "묵찌빠는 랜덤 숫자 발생을 할 수 있다"라는 개념이 자연스러울까요?
추상화와 그 구현체(여기선 RockPaperScissors 타입)의 관계를 설정할 땐 이와같은 고민을 해 보셨으면 좋겠습니다 :)

`RandomNumberGenerator` 프로토콜과 익스텐션을 삭제하고 `CaseIterable` 프로토콜을 채택하여 `allCases.randomElement()` 메서드를 통해 랜덤값을 받아올 수 있도록 구현하였습니다. 이 메서드를 가위바위보 타입 안의 새로운 메서드를 만들어서 하이디 말씀처럼 `RockPaperScissors.random()` 같이 더 은닉화가 가능해보이네요. 이렇게 하는게 더 좋을까요?

### 게임 나가기 기능 checkInvalidInput() 메서드에서 분리
> 게임을 나가는 기능을 입력이 유효한지 검증하는 메서드 안에서 수행하고 있네요?
여기선 진짜 유효성 검증만 수행하고, 게임의 큰 흐름에 해당하는 나가기 기능은 더 상위에서 처리하는게 자연스러워 보입니다.

`play()` 메서드에서 해당 구문을 처리할 수 있도록 변경하였습니다.


### 메서드명 변경
> 단지 비교 보다는 조금 더 구체적으로 "승자를 판단한다"는 의미가 포함되면 더 의미가 잘 전달될 것 같아요.

메서드명을 `decideWinner()`로 변경하였습니다.

2021-03-04 14:51 UTC, seizze approved these changes
스티븐 & 라이언 수고하셨습니다.

커밋을 잘 나누어 수정한 점도 좋았고, 각각 어떻게 수정했는지 설명해 주셔서 더 수정하신 방향을 더 잘 이해할 수 있었네요! 다만 어떻게 수정했는지 한 곳에 몰아서 써 주시는것보다 각각의 스레드에 나눠서 답변을 달아주면 조금 더 맥락 이해도 잘 되고 보기 편할 것 같아요 ㅎㅎ

추가적으로 피드백 드린 부분은 다음 스텝을 진행하며 개선해 보시면 좋겠습니다.

제가 드린 의견들은 무조건 기계적으로 고치라는 것이 아니라, 고민해볼 만한 사항들을 말씀드리는 것이니 의문이 든다면 다시 반론을 제시해도 좋고 더 나은 방법을 제시하면 더더 좋습니다 :)

2021-03-04 14:51 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
여러 시도를 해보는 것은 좋습니다! 하지만 사용자 입력을 받는 기능을 이런 식으로 작성한게 사실 자연스럽게 느껴지진 않네요 ㅠㅠ
객체 간의 관계는 여러 종류로 구성될 수 있습니다. 그 중 상위 클래스도 있고, 프로토콜도 있고, RockPaperScissorsGame과 Player의 관계처럼 프로퍼티로 참조하는 관계로 구성될 수 있습니다. 이 내용에 대해선 앞으로 진행하며 더 피드백을 드릴 수 있을것 같아요. :)

2021-03-04 14:51 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return GameError.nilInput.rawValue
여기서도 rawValue를 사용하고 있네요! 그냥 에러 객체 자체를 리턴할 순 없을까요? 그리고 nilInput과 -1 사이에는 어떤 연관이 있을까요? 만약 사용자(또는 이 함수를 사용하는 개발자)에게 -1이라는 숫자가 보여진다면 어떤 정보를 얻을 수 있나요?

2021-03-04 14:51 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private var userInput = 0
userInput 프로퍼티는 play 메서드 안에서만 사용되는 것 같네요. 이럴땐 play 안의 로컬 변수로 선언하는 게 더 좋습니다.
클래스에 프로퍼티가 많아질수록 객체가 많은 상태를 갖게 되어 나중엔 이해하기 힘들어지게 될 수도 있어요. 프로퍼티에 저장하지 않고 매개변수와 리턴값으로 처리할 수 있다면 그렇게 하는 편이 더 좋습니다. 참고하세요 :)

2021-03-04 14:51 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
이렇게 하면 그냥 rawValue를 가져다 쓰는 것과 별반 차이가 없긴 합니다. ㅎㅎ 이런 getter 형식의 메서드를 구현하지 않고는 방법이 없을까요? 이 피드백은 고치지 않고 생각만 해보고 넘어가도 괜찮습니다~

2021-03-04 14:51 UTC, merged

2021-03-05 00:47 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
코드를 최초에 설계하였을 때 가위바위보 게임 타입과 묵찌빠 게임 타입이 별도로 존재할 수 있겠다고 생각하여 재사용을 위해 사용자 입력 관련 메서드를 프로토콜과 익스텐션으로 분할하였었습니다. 현재 내부 프로퍼티를 활용하여 두 게임을 한 타입에서 수행하는 방향으로 협의하여 삭제하였습니다!

2021-03-05 01:37 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return GameError.nilInput.rawValue
getUserInput() 메서드에서 에러 객체 자체를 throw하도록 처리하였습니다.

2021-03-05 01:40 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private var userInput = 0
RockPaperScissorsGame 타입에 선언된 userInput 프로퍼티를 play() 메서드의 지역변수로 변경하였습니다.

2021-03-05 01:49 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
decideWinner() 메서드를 RockPaperScissors 열거 타입 안에 구현하는 방법을 고려해보았는데, 코드의 흐름이 논리적이어 보이지 않아 포기하였습니다..
- 저희 승패 판단 로직을 사용하려면 가위바위보의 index를 다른 타입에서 Int형으로 받아야합니다 (`computer.handSign.index() % 3 + 1`). 
- enum의 index를 다른 타입에서 접근하는 방법이 있나요? 고민하고 찾아보았는데 잘 모르겠습니다 ㅠㅠ😭

2021-03-05 01:55 UTC, ryan-son commented
@seizze 
하이디! 여전히 늦은 시간에 피드백 주셔서 감사해요.

저희도 기계적으로 코드를 수정하기 보다 개선 방법을 찾아보고 고민해보려 노력해보고 있어요 ㅠ😭.
하지만 배우는 기간이라 결국 하이디의 피드백을 수용해보자는 쪽으로 결론이 나고 있습니다!
저희도 하이디의 피드백에 더해서 더 다양한 방법을 찾아 코드를 개선하도록 하겠습니다.

2021-03-05 01:59 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
최초 설계 단계에서는 가위바위보와 묵찌빠를 담당하는 타입이 별도로 구성되어 공통으로 사용할 수 있는 사용자 입력 메서드의 경우 프로토콜, 익스텐션 구성을 통해 재사용하고자 하였습니다. 하지만 RockPaperScissorsGame 내에서 두 게임을 진행하는 것으로 변경하는 것으로 협의하여 프로토콜을 삭제하고 RockPaperScissorsGame 내의 메서드로 구현하였습니다.

2021-03-05 02:00 UTC, stevenkim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
그럼 어떻게 하는 것이 좋을까요 😭  가위바위보 타입 안에서 승패를 결정하는 것도 고려해 봤는데 논리적이지 않은 것 같아서 그렇게 하지는 않았어요   
아니면 외부에서 enum 타입의 인덱스를 접근 할 수 있는 방법이 있을까요? 저희가 찾아봤는데 잘 모르겠어요 😭

2021-03-05 02:02 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return GameError.nilInput.rawValue
getUserInput() 메서드에서 에러 객체 자체를 throw 하는 형식으로 변경하였습니다. C++, Java 등 다른 언어에서는 성능 문제로 인해 try catch 구문을  많이 사용하지 않는 것으로 알고있는데, swift는 어떤지 궁금합니다.

2021-03-05 02:03 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private var userInput = 0
RockPaperScissorsGame 타입에 사용되던 userInput 프로퍼티를 play() 메서드의 지역변수로 변경하였습니다.

2021-03-05 02:36 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
RockPaperScissors 타입에서 Comparable 프로토콜을 채택해 구현하고, 이를 이용해 승패를 결정하는 방식은 어떤가요? ㅎㅎ