[STEP 1] Hailey, 수킴
yagom-academy/ios-rock-paper-scissors pull request #35
Opened 2021-03-02 12:50 UTC by eunseo5355

@seizze 
하이디 안녕하세요!😃
Hailey, 수킴입니다!

## 코드를 작성할 때 고민되었던 점
- 변수명 작성
- 숫자 1, 2, 3 가독성을 높이기 위해 scissor, rock, paper 변수에 저장

## 조언을 얻고 싶은 부분
- 플로우차트를 그려봤는데 잘 그린건지 조언 얻고 싶어요!
<img width="290" alt="rockpaperscissors" src="https://user-images.githubusercontent.com/55755686/109649577-76517b00-7b9f-11eb-93c4-8e130b248926.png">

- playRockPaperScissors 함수에 case 1, 2, 3 구문에서 강제 언래핑을 사용했는데 case를 통해 Int 값이 들어온다는 확신을 가지고 있어서 사용했는데 혹시 더 괜찮은 방법이 있을까요?
- if구문에서 실행문이 한줄일때 가독성때문에 조건문이랑 같은 줄에 써줬는데 따로 써주는게 맞는 방법인가요?
- 작은 프로젝트에서 나중에 코드 유지보수 및 확장성까지 고려해서 작성하는 게 맞나요?(예를 들어, 변수가 3개있으면 배열로 작성 또는 enum으로 열거 등등)

2021-03-02 16:44 UTC, seizze requested changes
안녕하세요 헤일리, 수킴~
수고 많으셨습니다. 코멘트 확인해 주시고,
더 설명이 필요한 부분이 있다면 얼마든지 DM 주세요.

아래는 PR에 남긴 코멘트에 대한 제 의견이니 참고해 주세요.

> 플로우차트를 그려봤는데 잘 그린건지 조언 얻고 싶어요!

좋은 시도입니다. 플로우 차트, 클래스 다이어그램 등은 미리 약속된 문법이 있기 때문에 함께 일하는 개발자들과의 커뮤니케이션을 원활히 할 수 있다는 점에서 좋은 선택 중 하나라고 생각되네요. 저도 플로우에 대한 이해가 명확히 된 것 같아요.

> playRockPaperScissors 함수에 case 1, 2, 3 구문에서 강제 언래핑을 사용했는데 case를 통해 Int 값이 들어온다는 확신을 가지고 있어서 사용했는데 혹시 더 괜찮은 방법이 있을까요?

관련 코멘트 남겼으니 확인해주세요!

> if구문에서 실행문이 한줄일때 가독성때문에 조건문이랑 같은 줄에 써줬는데 따로 써주는게 맞는 방법인가요?

이것도 코드에 남겼으니 확인해주세요~!

> 작은 프로젝트에서 나중에 코드 유지보수 및 확장성까지 고려해서 작성하는 게 맞나요?(예를 들어, 함수를 기능별로 더 세세하게 나눈다거나 변수가 3개있으면 배열로 작성 또는 enum으로 열거 등등)

작은 프로젝트인데 괜히 코드를 더 써서 세세하게 나눠야 하는 고민이 드셨군요 ㅎㅎ
우리가 소규모 프로젝트들을 하는 이유는, 여기서 연습하고 학습 과정을 거친 뒤에 큰 프로젝트에 적용해 보기 위함이라고 저는 생각해요.
실제 업무에서는 이 정도의 규모로 끝나는 프로젝트는 없고, 항상 구조나 확장성, 유지보수를 고려하며 작성해야 합니다. 그러기 위해서는 소규모 프로젝트에서의 학습 단계가 꼭 필요해요.
은닉화, 추상화, 일반화 등 여러 객체지향 개념을 배운 만큼 그것을 활용해 보는 연습을 해보는건 어떨까요?
앞으로의 프로젝트들을 거치면서 여러 도전을 해 보고, 시행착오도 겪어 보고, 많은 것을 얻어갔으면 좋겠어요~

아마 확신이 서지 않으셔서 안하신 것 같아요. 개선 후에 추가적인 피드백을 드리는 게 더 좋을거 같네요 ! ☺️

2021-03-02 16:44 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +            playRockPaperScissors()
재귀 방식을 사용했네요!
재귀를 사용할 땐 어떤 문제를 고려해야 할까요? 그 문제가 절대 발생하지 않는다는 보장이 있을까요?

2021-03-02 16:44 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +            gameResult(userNumber: Int(inputUserNumber)!, computerNumber: computerNumber)
위에서 Int 형변환을 했지만 아래서 다시 수행했네요~
여러번 같은 작업을 해야하는 이유가 있나요? 없다면, 형변환한 결과를 저장해 뒀다가 재사용할 수 있는 방법은 없을까요?
그리고 옵셔널 바인딩은 한 줄에 한 번만 할 수 있을까요?

이 부분을 해결하면 강제 언래핑하는 부분도 자연스레 없어질 수 있을것 같아요~

2021-03-02 16:44 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
> if구문에서 실행문이 한줄일때 가독성때문에 조건문이랑 같은 줄에 써줬는데 따로 써주는게 맞는 방법인가요?

이런 코멘트를 남겨주셨는데요, 이거는 맞다 틀리다의 문제는 아니고 같은 줄에 쓸지, if문이면 반드시 내려 쓸지 개발팀에서 협의해서 정하는 사항인 것 같아요. 페어 프로그래밍이니 우리 팀만의 기준을 정하고 그것을 지키도록 해보세요.

다만, case마다 계속 같은 동작을 하고 있으니 승패를 판단하는 메서드로 추출 후 그걸 호출하는 방식(한 줄)으로 개선해 볼 수 있을 것 같네요!

2021-03-04 06:29 UTC, eunseo5355 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            playRockPaperScissors()
재귀 함수를 사용하면 메모리를 많이 차지해 성능이 반복문에 비해 느리고 만약 재귀로 인해 함수를 반복적으로 호출하게되면 스택 메모리가 커져 스택오버플로우가 발생할 수 있다는 문제점이 있네요..! 하지만 메모리 제한이 없는 경우에는 재귀 방식도 가독성 부분이나 변수 사용을 줄일 수 있어서 각각의 상황에 맞게 사용하는 것이 좋을 것 같아요😃

2021-03-04 06:46 UTC, eunseo5355 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            gameResult(userNumber: Int(inputUserNumber)!, computerNumber: computerNumber)
옵셔널 바인딩 안에 또 옵셔널 바인딩을 해줄 수 있다는 것을 처음 알게되었습니다!

```Swift
if let inputUserNumber = readLine() {
    if let intInputUserNumber = Int(inputUserNumber) {
        switch intInputUserNumber { 
        case 0:
              print("게임 종료")
              return
         case 1, 2, 3:
               gameResult(userNumber: intInputUserNumber), computerNumber: computerNumber)
```

이런 식으로 수정했더니  형변환한 결과를 저장해 뒀다가 재사용 가능해졌고 강제 언래핑이 자연스럽게 없어졌네요😆

2021-03-04 07:00 UTC, eunseo5355 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
if문에서 명령문이 한 줄이면 조건문과 같은 줄에 작성하는게 가독성이 더 좋다고 판단하여 저희 팀은 한 줄로 작성하기로 했습니다!

두 번째 코멘트는 정확히 이해를 못해서 저희가 다시 작성한 코드에서 judgeHand 함수 부분 다시 확인해 주시면 감사하겠습니다😂

2021-03-04 07:19 UTC, eunseo5355 commented
@seizze 
안녕하세요 하이디😃

확장성을 고려해서 클래스 만들고 함수를 더 세세하게 나눠봤어요~!

## 조언 받고 싶은 부분
- 전 피드백에서 37번째 줄 case마다 같은 동작을 하고 있어서 메서드를 추출하면 좋을 것 같다는 피드백을 받았는데 judgeHand() 메서드로 추출하였는데 잘 보완이 되었나요?
- finishGame() 메서드가 print("게임종료")  명령문이 한 개만 있는 간단한 메서드인데 나중에 다른 모듈에서도 재사용하기 위해 따로 메서드를 만든 부분이 나은가요?
- private를 가위바위보게임 클래스 내에서만 사용하기 위해서 사용했는데 접근제어자를 잘 사용했는지 궁금합니다!!
- 코드 가독성을 위해 enum 열거형을 사용했는데 알맞게 사용한건지 궁금합니다!

2021-03-04 13:23 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +            gameResult(userNumber: Int(inputUserNumber)!, computerNumber: computerNumber)
```swift
if let inputUserNumber = readLine(), let intInputUserNumber = Int(inputUserNumber) {
    ...
}
```
이렇게 콤마로 나누어 여러번 할수도 있습니다. ㅎㅎ 참고하세요

2021-03-04 13:24 UTC, seizze approved these changes
헤일리, 수킴 고생하셨습니다.

전체적으로 한 메서드에서 하나의 기능만 하도록 고민하신게 보이네요~
이슈가 되는 부분을 리서치해보고 자신의 말로 논리적으로 설명하려 한 점도 좋습니다. 실무에서 반드시 필요한 역량이니 앞으로도 이런 연습을 계속 해 나가면 좋을것 같아요.

추가적으로 피드백 드린 부분은 다음 스텝을 진행하며 개선해 보시고,
다음 스텝부터는 커밋도 자신만의 기준을 정해서 의미 단위로 나누어 보세요 ㅎㅎ

또한 페어 프로그래밍이니 네비게이터와 드라이버의 역할 분담이 커밋에도 나타났으면 좋겠어요. 네비게이터와 드라이버의 역할을 잘 나누어 진행해 보세요.

다음은 코멘트 주신 사항에 대한 의견입니다.

> 전 피드백에서 37번째 줄 case마다 같은 동작을 하고 있어서 메서드를 추출하면 좋을 것 같다는 피드백을 받았는데 judgeHand() 메서드로 추출하였는데 잘 보완이 되었나요?

코드에 의견 남겼으니 확인해 주세요 ㅎㅎ

> finishGame() 메서드가 print("게임종료") 명령문이 한 개만 있는 간단한 메서드인데 나중에 다른 모듈에서도 재사용하기 위해 따로 메서드를 만든 부분이 나은가요?

이 내용에 대해서도 의견 남겼습니다. "묵찌빠" 타입에 finish라는 case가 들어가는 건 어색하다는 코멘트랑 함께 보시고 개선해보면 좋을 것 같아요~

> private를 가위바위보게임 클래스 내에서만 사용하기 위해서 사용했는데 접근제어자를 잘 사용했는지 궁금합니다!!

네 프로퍼티를 private로 은닉화하신 부분 아주 좋습니다. 👍👍 하지만 클래스에 프로퍼티가 많아질수록 객체가 많은 상태를 갖게 되어 나중엔 이해하기 힘들어지게 될 수도 있어요. 프로퍼티에 저장하지 않고 매개변수와 리턴값으로 처리할 수 있다면 그렇게 하는 편이 더 좋습니다. 참고하세요 :)

> 코드 가독성을 위해 enum 열거형을 사용했는데 알맞게 사용한건지 궁금합니다!

enum 사용하신 부분 아주 좋아요~ 이 부분에 대해서도 코멘트 남겼으니 확인해 주세요.

2021-03-04 13:24 UTC, merged

2021-03-05 02:16 UTC, Sookim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            else if userHand == RockPaperScissorsHand.paper { print("졌습니다!") }
코멘트를 보고 확인을 해보니 타입 어노테이션으로 컴파일러에게 RockPaperScissorsHand타입을 알려주었기 때문에 값만 입력해도 타입추론이 가능하다는 것을 알게 되었어요!

2021-03-05 02:20 UTC, Sookim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                if isValidUserNumber(inputUserNumber) {
중첩되어 사용하는 조건문을 한 줄로 작성할 수 있는 방법을 알게 되었어요. 감사합니다😄

2021-03-05 02:26 UTC, Sookim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
개선할 수 있는 방법 중 하나로는 enum 타입명을 사용자가 입력받을 수 있는 범위로 더 상위 흐름으로 명명을 하거나,
다른 방법으로는 사용자가 0을 입력 했을 때  finish를 RockPaperScissorsHand타입에 넣지 말고 게임이 바로 종료될 수 있도록 개선할 수 있을 것 같습니다.❗️

2021-03-05 02:44 UTC, Sookim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            computerHand = RockPaperScissorsHand(rawValue: Int.random(in: 1...3))
enum 열거형에서 인스턴스메소드 및 정적메소드를 사용할 수 있다는 방법을 알았습니다.📖
좀 더 공부를 해보고 다음 코드를 작성할 때 개선해보겠습니다❗️

2021-03-05 02:46 UTC, Sookim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func isValidUserNumber(_ userNumber: String) -> Bool {
isValidUserNumber 를 동사형으로 변경해본다면 checkValidUserNumber로 변경할 수 있을 것 같습니다.

2021-03-05 02:53 UTC, Sookim18 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
동작이 한 줄일때는 따로 메소드를 구현하지 않는 것이 더 좋을 것 같아요! 조언 감사합니다 :)

2021-03-05 13:11 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
메서드 이름은 "게임을 끝낸다"인데 안에서는 정보 출력만 하고 있어서 동작과 이름이 맞지 않는다는 말이었어요~ 이름을 "게임을 끝낸다"로 지으려면 실제 게임을 끝내는 코드가 들어가야 한다는 의미입니다. 동작이 한 줄이라고 해서 메서드로 구현하지 말라는 의미는 아닙니다! 🙂

2021-03-05 15:08 UTC, eunseo5355 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func getIntHands() {
userHand, computerHand 변수에 RockPaperScissorsHand타입이 들어간 걸 지양해야한다고 말씀해주신게 맞나요?? 저희가 잘 이해한건지 헷갈려서 다시 여쭤봅니다..!

2021-03-05 15:10 UTC, eunseo5355 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
앗 다시보니까 그렇네요! 조언 감사합니다😃

2021-03-05 16:49 UTC, seizze commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private func getIntHands() {
아 getIntHands 이름의 Int를 말한거였어요! ㅎㅎ