[Step2] James-Neph
yagom-academy/ios-rock-paper-scissors pull request #38
Opened 2021-03-03 08:32 UTC by Neph3779

@corykim0829 

### 조언이 필요한 부분

- 함수명, 변수명을 신경써서 지었지만.. 코리가 보시기에 적합하지 않은 부분이 있다면 조언해주세요!

- 피드백 내용 바탕으로 enum과 rawValue들을 활용해보았는데 적절하지 않은 부분이 있다면 알려주세요!

- README.md의 마지막 부분에 저희가 정한 줄넘김 규칙을 추가해준 뒤, 반영해보았는데요.. 적절하지 않은 부분이 있다면 알려주세요!!

- startGame 메서드에서 while문을 사용해 게임이 계속 진행되도록 하였는데... 47~54번째 줄에 있는 do-catch문을 메서드로 구현하고 싶었지만 특정 조건에서 while문의 continue/break를 진행해줘야 했기 때문에 메서드화 하지 못했습니다. 

  이 부분을 메서드화 할 수 있을까요? 만약 할 수 있다면 하는 것이 좋을까요?

\+ PR을 보내려하니 Can't automatically merge라는 에러 메세지가 나오는데 저희가 뭔가 잘못한게 있는걸까요?..

2021-03-03 10:09 UTC, corykim0829 commented
step1 머지하기 전에 step2를 먼저 진행하셨나요? 아마 그 작업들이 step1 머지된 작업들과 충돌이 난 것 같네요! 나중에 머지할 때 해결해도 될 것 같아요 😀

2021-03-03 10:33 UTC, corykim0829 requested changes
수고하셨습니다 ㅎㅎ step2가 엄청 빨리 와서 놀랐네요 ㅎㅎ 아주 잘하고 계십니다 👍👍👍👍👍
그리고 PR 날려주실 때 결과 화면을 캡쳐해서 같이 보내주세요 ㅎ

한가지 팁을 드리자면, 너무 한가지 방식으로만 생각하기 보다는 다양한 접근법도 고려해보면 좋을 것 같아요! 이 말은 리뷰 보시면 이해가 가실 것 같아요 ㅎ
일단 해드린 리뷰에 대해서 같이 고민해보고 수정해서 푸쉬해주세요!

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +class MukChiBa : RockPaperScissors {
여기에서 상속을 사용한 이유가 궁금합니다!

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case userLose = "졌습니다!"
사용자 입장으로 생각하고 user를 빼버리는건 어떨까요? computerWin Lose는 따로 없어서 더 깔끔할 것 같아요!

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if let randomHand = Hand(rawValue: Int.random(in: 1...3)) {
enum에 CaseIterable 프로토콜 참고하면 좋을 것 같습니다.
optional 처리 안해줘도 될거에요

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var rawUserInput: String? = ""
`rawUserInput` 프로퍼티는 어디서 사용되나요? scope를 확인해보면 좋을 것 같아요!

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var handOfUser: Hand = .rock
프로퍼티들은 기본적으로 private으로 선언하는게 좋습니다. 외부에서 사용이 될 때만 접근제어자를 수정하는게 좋습니다 ㅎ

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func RockPaperScissorsResult() -> ResultsOfRockPaperScissors {
함수가 대문자로 시작하네요 🥲
함수는 항상 소문자로 시작해주세요 ㅎ

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum ResultsOfRockPaperScissors: String {
nested enum이기 때문에 RockPaperScissors까지 모두 적을 필요는 없을 것 같아요 RockPaperScissors 클래스에서만 사용하니까 GameResult와 같이 간단하게 해보는건 어떨까요?

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                if let safeHandOfUser = RockPaperScissors.Hand(rawValue: try checkUserInput().rawValue) {
`checkUserInput()` 에서 Hand 타입을 반환하는데 또 Hand를 만드는게 부자연스럽네요!
이 부분 수정하면 훨씬 깔끔해질 것 같네요

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var currentTurn: String
currentTurn을 String으로 구분하면, 위험성이 큰 것 같아요. 위에 enum 만들어 놓은 것을 활용해도 좋을 것 같아요

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var currentTurn: String
이 turn의 String을 바로 이용하고 싶었던 거라면 enum의 CustomStringConvertible 프로토콜에 대해 공부해보면 좋을 것 같네요!

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func mukChiBaStart() {
여기 함수명도 gameStart처럼 간단하게 하면 좋을 것 같네요 이미 클래스가 mukChiBa가 들어가 있으니 중복이 되네요!

2021-03-03 10:33 UTC, corykim0829 commented on README.md
> +  4. 메소드 속 코드는 기본적으로 붙여 쓰되 도중에 흐름 제어 또는 에러 처리를 쓰는 경우 해당 코드 블럭 위 아래 한 칸 줄넘김
깔끔합니다 ㅎ

2021-03-03 10:33 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func mukChiBaResult() -> ResultsOfMukChiBa {
이 부분을 꼭 Result enum를 반환해야한다는 생각에 코드가 제한적으로 나오는 느낌이네요 이부분은 이제까지 구현하신 것을 조합하면 더 부드럽게 처리할 수 있을 것 같아요!!

2021-03-03 10:38 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
>                  print("잘못된 입력입니다. 다시 시도해주세요.")
PR에 올려주신 질문에 조금 답변을 해드리면 catch에서 error를 잡을 수 있으니 이부분은 따로 함수로 빼면 좋을 것 같네요 에러에 따라 출력을 해줄 수 있을 것 같아요!

2021-03-04 08:01 UTC, Neph3779 commented
@corykim0829 
안녕하세요 코리! Step2의 2차 피드백 요청을 드립니다!

## 반영한 피드백

1. case명에 user를 생략하자는 피드백을 반영했습니다.
2. CaseIterable 프로토콜을 채용하여 optional 처리를 안할 수 있도록 코드를 바꿔보았습니다.
3. 함수의 네이밍이 대문자로 시작하는 것을 고치자는 피드백을 반영했습니다.
4. nested enum이니 이름을 더 간단히 바꿔보자는 피드백을 반영했습니다.
5. handOfUser를 갱신하는 과정에서 불필요한 프로세스가 있는데 그것을 없애자는 피드백을 반영했습니다. (Hand type에 CaseIterable 프로토콜을 채용하여 해결했습니다.)
6. currentTurn을 String으로 저장했었는데 이러면 위험하니 이를 ResultOfGame에 CustomStringConvertible 프로토콜을 채용하여 해결해보자는 피드백을 반영하여 String으로 저장되어있던 rawValue를 없애고 description을 이용하여 해결했습니다.
7. mukChiBaStart() 함수명을 간단히 하자는 피드백을 반영하여 gameStart()로 rename 했습니다.

   

## 반영하지 못한 피드백 & 궁금한 점

- 부모 클래스의 프로퍼티를 private으로 접근제어 지정자 설정시, 하위클래스에서 접근할 수 없었습니다. 이를 어떻게 해결할 수 있을까요?

  ### 이 부분에 대해 저희가 생각해본 해결 방법을 적어보았습니다

  1. 가위바위보 클래스와 묵찌빠 클래스를 아예 하나의 클래스로 통합하자는 의견이 있었습니다

  2. 각각의 클래스에 private으로 변수들을 따로 저장하자는 의견이 있었습니다.

     이 경우 private 변수에 접근하는 모든 함수를 override 해줘야하는데.. 이게 맞는 방향인지 궁금합니다!

     

- > 이 부분을 꼭 Result enum를 반환해야한다는 생각에 코드가 제한적으로 나오는 느낌이네요 이부분은 이제까지 구현하신 것을 조합하면 더 부드럽게 처리할 수 있을 것 같아요!!

  이 피드백을 이해하지 못했습니다. 어떻게 처리해야 부드럽게 처리할 수 있을까요? ㅠㅠ

  

- CustomStringConvertible 프로토콜을 채용하여 currentTurn의 타입을 String이 아니게 바꾸어 주었지만 왜 이게 위험했던것인지 잘 이해하지 못했습니다. 중간에 프로그래머의 실수로 String의 값이 변경될 수 있기 때문일까요?

  

지난번 피드백을 바탕으로 

  ```swift
  do {
  			if let safeHandOfUser = RockPaperScissors
    		.Hand(rawValue: try checkUserInput().rawValue) {
  			handOfUser = safeHandOfUser
  }
  ```

  를 아래와 같이 바꾸어 주었더니

  ```swift
  do {
  		handOfUser = try checkUserInput()
  }
  ```

  이제 충분히 간결해져서 함수로 뺄 필요가 없는 것 같은데 이대로 두어도 괜찮을까요?

2021-03-04 08:04 UTC, inwoodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +class MukChiBa : RockPaperScissors {
저희는 가위바위보에서 기능이 추가 된 것이 묵찌빠라고 생각했습니다. 그래서 가위바위보를 부모 클래스로 지정한 뒤 해당 클래스로부터 중복되는 메소드는 그냥 호출하고 그외 조금 차이점이 있는 메소드는 override를 통해 변형시키려고 했습니다. 그래서 묵찌빠를 상속클래스로 정의하였습니다.

2021-03-04 08:06 UTC, inwoodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var rawUserInput: String? = ""
rawUserInput은 가위바위보와 묵찌빠 두 클래스의 공용 프로퍼티로 써도 문제 없다고 판단했기에 공용 변수로 설정을 해 두었습니다.

2021-03-04 14:41 UTC, corykim0829 commented
> @corykim0829
> 안녕하세요 코리! Step2의 2차 피드백 요청을 드립니다!
> 
> ## 반영한 피드백
> 1. case명에 user를 생략하자는 피드백을 반영했습니다.
> 2. CaseIterable 프로토콜을 채용하여 optional 처리를 안할 수 있도록 코드를 바꿔보았습니다.
> 3. 함수의 네이밍이 대문자로 시작하는 것을 고치자는 피드백을 반영했습니다.
> 4. nested enum이니 이름을 더 간단히 바꿔보자는 피드백을 반영했습니다.
> 5. handOfUser를 갱신하는 과정에서 불필요한 프로세스가 있는데 그것을 없애자는 피드백을 반영했습니다. (Hand type에 CaseIterable 프로토콜을 채용하여 해결했습니다.)
> 6. currentTurn을 String으로 저장했었는데 이러면 위험하니 이를 ResultOfGame에 CustomStringConvertible 프로토콜을 채용하여 해결해보자는 피드백을 반영하여 String으로 저장되어있던 rawValue를 없애고 description을 이용하여 해결했습니다.
> 7. mukChiBaStart() 함수명을 간단히 하자는 피드백을 반영하여 gameStart()로 rename 했습니다.

gameStart가 한국 문법에서는 자연스럽게 들리지만, startGame이 영어 문법에 조금 더 맞는 표현인 것 같아요 ㅎ

> 
> ## 반영하지 못한 피드백 & 궁금한 점
> * 부모 클래스의 프로퍼티를 private으로 접근제어 지정자 설정시, 하위클래스에서 접근할 수 없었습니다. 이를 어떻게 해결할 수 있을까요?
>   ### 이 부분에 대해 저희가 생각해본 해결 방법을 적어보았습니다

객체 안의 프로퍼티는 private 먼저 고려해보시고, private(set) -> public 순으로 개방하는게 좋습니다! 외부에서 직접 수정하기 보다는 내부 로직으로 변경되거나 처리되는게 좋습니다. 하지만 필요한 경우에는 private을 쓰지 않을 수도 있습니다. 언제나 상황을 고려하는 것은 중요합니다!

>   1. 가위바위보 클래스와 묵찌빠 클래스를 아예 하나의 클래스로 통합하자는 의견이 있었습니다
>   2. 각각의 클래스에 private으로 변수들을 따로 저장하자는 의견이 있었습니다.
>      이 경우 private 변수에 접근하는 모든 함수를 override 해줘야하는데.. 이게 맞는 방향인지 궁금합니다!

개인적으로는 클래스를 상속하는게 큰 의미가 없는 것 같아서 말씀을 드렸었어요! 상속을 사용하는 이점이 없다면 굳이 사용할 필요가 없지 않을까요?

> * > 이 부분을 꼭 Result enum를 반환해야한다는 생각에 코드가 제한적으로 나오는 느낌이네요 이부분은 이제까지 구현하신 것을 조합하면 더 부드럽게 처리할 수 있을 것 같아요!!

이 부분은 Result enum을 꼭 사용하지 않아도 승패 처리는 할 수 있을 것 같아서 말씀드린 부분이여서 말씀 드렸던 부분이에요! 이해가 안가시면 한번 더 말씀해주세요!

>   
>   이 피드백을 이해하지 못했습니다. 어떻게 처리해야 부드럽게 처리할 수 있을까요? ㅠㅠ
> * CustomStringConvertible 프로토콜을 채용하여 currentTurn의 타입을 String이 아니게 바꾸어 주었지만 왜 이게 위험했던것인지 잘 이해하지 못했습니다. 중간에 프로그래머의 실수로 String의 값이 변경될 수 있기 때문일까요?

맞습니다 이전에 Int 타입에 대해서 피드백 해드렸던 것 처럼 String도 다른 값이 들어갈 수 있는 건가? 라고 생각할 수 있습니다. 또한 String은 다른 타입에 비해 비용이 조금 더 들어가는 친구여서 대체할 수 있으면 대체하는게 좋습니다 ㅎ

> 
> 지난번 피드백을 바탕으로
> 
> ```swift
> do {
> 			if let safeHandOfUser = RockPaperScissors
>   		.Hand(rawValue: try checkUserInput().rawValue) {
> 			handOfUser = safeHandOfUser
> }
> ```
> 
> 를 아래와 같이 바꾸어 주었더니
> 
> ```swift
> do {
> 		handOfUser = try checkUserInput()
> }
> ```
> 
> 이제 충분히 간결해져서 함수로 뺄 필요가 없는 것 같은데 이대로 두어도 괜찮을까요?
> 


네 깔끔한 것 같습니다. 이미 `checkUserInput()` 함수로 처리하고 있어서 깔끔하네요 ㅎ 함수명이 조금 더 Hand를 반환하는 느낌의 함수명으로 바꾸면 좋을 것 같아요!

PR에 스크린샷도 잘 첨부해줘서 이해하기 좋았어요 ㅎ 수고하셨습니다

2021-03-04 14:43 UTC, corykim0829 commented
앗 그리고 커밋 메세지를 조금 더 함축해서 보낼 수 있도록 노력해보세요! 최대한 간단하게 적고 더 자세한 내용은 내용으로 적으면 좋을 것 같습니다 ㅎㅎ 

![image](https://user-images.githubusercontent.com/34022757/109980468-4b079100-7d43-11eb-9e19-506395ec9493.png)
이렇게 뒤에 ...으로 넘어가지 않도록 하면 좋을 것 같아요 ㅎ

2021-03-04 14:45 UTC, corykim0829 commented
![image](https://user-images.githubusercontent.com/34022757/109980785-9de14880-7d43-11eb-8a95-0a3ba5f61bcd.png)
여기서는 가위바위보 게임에서는 처리해줬던 걸로 기억하는데, 묵찌빠에서는 잘못된 입력을 해도 따로 알려주지는 않나요?
Error 처리 로직을 잘 짜두셔서 금방 처리하실 수 있을 것 같아요!

2021-03-04 14:59 UTC, corykim0829 requested changes
피드백 너무 잘 반영해주셨는데요! 

너무 잘하고 계셔서 제가 요청드리고 싶은게 있네요.
```Swift
     var rawUserInput: String? = ""
```
이 부분을 제거하고 로직을 완성해보는 걸 도전해보시면 어떨까요? 여유가 안되시면 안하셔도 됩니다 ㅎ

2021-03-04 14:59 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        handOfComputer = Hand.allCases.map{$0}[Int.random(in: 0...2)]
고차함수로 잘 처리하셨군요! 근데 저도 찾아보니까 allCases에서도 랜덤 함수가 구현되어있더라구요 한번 찾아보시면 좋을 것 같아요!
왜냐하면 이러헥 구현해버리면 만약 Hand에 새로운 타입이 추가되면 여기 2라는 숫자를 변경해야할 수 도 있기 때문에 2라는 숫자를 따로 상수로 만들거나 allCases의 count로 처리하면 되는데 랜덤함수가 있으니 그거를 사용해봅시다!

2021-03-05 02:10 UTC, inwoodev commented
@corykim0829 

안녕하세요 코리! step2의 2차 피드백 반영했습니다.
프로그램은 정상적으로 작동해서 따로 저번처럼 사진 첨부는 하지 않았습니다.
항상 디테일한 피드백 감사합니다. 덕분에 많이 배워가요.😃

## 반영한 피드백
---
1. `gameStart()`를 영어 문법에 맞게 `startGame()`으로 변경하였습니다.
2. 객체 안의 프로퍼티를 모두 `private`으로 수정하였습니다.
3. Cory의 의견을 반영하여 가위바위보 클래스와 묵찌빠 클래스를 별개 클래스로 분리하였습니다.
4. 묵찌빠 결과를 `result enum`으로 반환하지 않고 `bool` 값을 반환하여 게임결과를 도출하도록 변경하였습니다. 메소드 이름 또한 `isGameOver()` 로 변경하였습니다.
5. `checkUserInput()` 함수명을 `checkedUserHand()`로 바꿔서 Hand을 반환한다는 점을 강조 해 보았습니다.
6. 커밋 메세지를 함축하고 대신 description에 자세한 변경사항을 적어봤습니다. 
7. `rawUserInput` 지역 변수를 없애고 대신 메소드 내에서 유저 입력값을 처리하도록 수정했습니다.
8. `renewComputerHand()` 메소드 내에서 고차함수를 쓰지않고 대신 `allCases.randomElement()`를 활용하여 랜덤값을 반환하도록 변경했습니다.
9. Cory가 피드백은 아니었지만 10년 뒤에도 코드를 알아볼 수 있게 코드를 짜면 좋겠다는 피드백을 들은 적이 있어서 `isGameOver()` 와 `rockPaperScissorsResult()` 내 case를 rawValue가 아니라 `.scissor`, `.rock`과 같은 case name 조건일 때 값을 반환하도록 변경하였습니다.



## 반영하지 못한 피드백 & 궁금한 점
---
- 객체 안의 프로퍼티는 모두 `private`으로 설정하였습니다. 다만 메소드 같은 경우 그냥 internal 상태로 유지하였는데 메소드도 `private` 설정 하는 것이 좋을지 궁금니다.
- 저희 `startGame()`은 while문으로 이뤄져있고 `break`와 `continue`를 사용해서 다양한 게임 결과를 도출해 내도록 설정하였습니다. Cory가 생각하는 저희 프로그램의 로직이 어떤지 궁금합니다. 이렇게 쓰는 것 보다 재귀함수를 쓰는게 나을지 아니면 다른 더 효율적인 방법이 있는지 궁금합니다.

2021-03-06 15:08 UTC, corykim0829 commented
> @corykim0829
> 
> 안녕하세요 코리! step2의 2차 피드백 반영했습니다.
> 프로그램은 정상적으로 작동해서 따로 저번처럼 사진 첨부는 하지 않았습니다.
> 항상 디테일한 피드백 감사합니다. 덕분에 많이 배워가요.😃
> 
> ## 반영한 피드백
> 1. `gameStart()`를 영어 문법에 맞게 `startGame()`으로 변경하였습니다.
> 2. 객체 안의 프로퍼티를 모두 `private`으로 수정하였습니다.
> 3. Cory의 의견을 반영하여 가위바위보 클래스와 묵찌빠 클래스를 별개 클래스로 분리하였습니다.
> 4. 묵찌빠 결과를 `result enum`으로 반환하지 않고 `bool` 값을 반환하여 게임결과를 도출하도록 변경하였습니다. 메소드 이름 또한 `isGameOver()` 로 변경하였습니다.
> 5. `checkUserInput()` 함수명을 `checkedUserHand()`로 바꿔서 Hand을 반환한다는 점을 강조 해 보았습니다.
> 6. 커밋 메세지를 함축하고 대신 description에 자세한 변경사항을 적어봤습니다.
> 7. `rawUserInput` 지역 변수를 없애고 대신 메소드 내에서 유저 입력값을 처리하도록 수정했습니다.
> 8. `renewComputerHand()` 메소드 내에서 고차함수를 쓰지않고 대신 `allCases.randomElement()`를 활용하여 랜덤값을 반환하도록 변경했습니다.
> 9. Cory가 피드백은 아니었지만 10년 뒤에도 코드를 알아볼 수 있게 코드를 짜면 좋겠다는 피드백을 들은 적이 있어서 `isGameOver()` 와 `rockPaperScissorsResult()` 내 case를 rawValue가 아니라 `.scissor`, `.rock`과 같은 case name 조건일 때 값을 반환하도록 변경하였습니다.
10년 뒤에도 알아볼 수 있는 코드라.. 되게 좋은 말이네요! 너무 좋아요!


> ## 반영하지 못한 피드백 & 궁금한 점
> * 객체 안의 프로퍼티는 모두 `private`으로 설정하였습니다. 다만 메소드 같은 경우 그냥 internal 상태로 유지하였는데 메소드도 `private` 설정 하는 것이 좋을지 궁금니다.

메소드도 private을 우선으로 생각하는게 객체지향적이여서 좋습니다!

> * 저희 `startGame()`은 while문으로 이뤄져있고 `break`와 `continue`를 사용해서 다양한 게임 결과를 도출해 내도록 설정하였습니다. Cory가 생각하는 저희 프로그램의 로직이 어떤지 궁금합니다. 이렇게 쓰는 것 보다 재귀함수를 쓰는게 나을지 아니면 다른 더 효율적인 방법이 있는지 궁금합니다.

저는 개인적으로 깔끔하게 잘 짰다고 생각합니다. 재귀함수를 사용하면 어떤 차이가 있는지는 알고 넘어가는게 좋을 것 같아요! 여유가 된다면 성능차이도 공부해보면 좋을 것 같아요 ㅎ

2021-03-06 15:25 UTC, corykim0829 requested changes
수고하셨습니다!! 조금 더 고민해보면 좋을 것들을 적어보았습니다 ㅎ

2021-03-06 15:25 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand: Int, CaseIterable {
두가지 클래스에서 사용되면 클래스 밖에서 선언하여서 관리하면 더 좋을 것 같아요!
파일도 따로 만들어서 관리하면 더 좋을 것 같네요 ㅎ

2021-03-06 15:25 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    private var handOfUser: Hand = .rock
가위바위보 할 때에는 프로퍼티 사용이 꼭 필요한 것 같지 않습니다!
여기 프로퍼티들을 사용하지 않고 구현해보세요

2021-03-06 15:25 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            let resultOfRockPaperScissors = rockPaperScissorsResult()
여기서는 짧게 result라고 변수명을 해주면 더 좋을 것 같네요!

2021-03-06 15:25 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    init(rockPaperScissorsResult: RockPaperScissors.GameResult) {
GameResult가 win과 lose일 때만 넘어오기 때문에 GameResult자체를 넘기는 건 조금 더 고민해보면 좋을 것 같네요!

2021-03-06 15:25 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case somebodyWin
이 case가 사용되고 있나요? GameResult enum인데, case에는 Turn을 나타내고 있어서 아쉽네요!
더 고민해보면 좋을 것 같아요!

2021-03-07 00:05 UTC, Neph3779 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand: Int, CaseIterable {
가위바위보 클래스에서는 Hand의 case에 할당된 원시 값이 각각
- scissor = 1
- rock = 2
- paper = 3
이고
묵찌빠 클래스에서는
- rock = 1
- scissor = 2
- paper = 3
이라 아예 enum Hand를 각각의 클래스에 만들어주고 각각의 클래스에 따로 private var을 사용했습니다.

##### 질문
- 혹시 enum의 원시 값을 저장할 때 각각의 클래스에서 다르게 적용되도록 설정해줄 수 있을까요?
- 만약 조언해주신 방향이 이게 아니라면 어떻게 수정해야할지 다시 피드백 주실 수 있을까요?

2021-03-07 04:49 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand: Int, CaseIterable {
아 그렇군요! 통일하는 것은 어려울까요? 거의 같은 동작을 하고 있는 모델이여서 한번에 처리하는게 좋을 것 같아요!

2021-03-07 08:11 UTC, inwoodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand: Int, CaseIterable {
계속 통일을 하려 노력했는데 요구사항을 보시면 
가위(1). 바위(2). 보(3)! <종료 : 0>
묵(1). 찌(2). 빠(3)! <종료 : 0>

이렇게 가위와 찌, 그리고 바위와 묵이 요구하는 숫자가 달라서 이것을 어떻게 통일하면 좋을지 고민이 됩니다.
Neph 가 얘기 해 주신데로 enum의 원시 값을 각 각 클래스별로 다르게 적용할 수 있나요?
아니면 enum말고 다르게 접근할 필요가 있을까요?

2021-03-07 08:23 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand: Int, CaseIterable {
그렇군요! 그러면 따로 구현하는게 맞는 것 같아요! 헷갈리게해서 죄송합니다 🥲

2021-03-08 08:44 UTC, merged