[Step2] Kane, Kio, KangKyung
yagom-academy/ios-rock-paper-scissors pull request #44
Opened 2021-03-05 03:16 UTC by kane-young

@idevjinie 
지니이😃 STEP2 PR해봅니다 🙃

### 고민했던 점
- step1에서 사용한 메서드들을 다시 활용할 수 없을지 고민하였습니다.
- step1에서 가위바위보를 enum으로 받았었는데, step2에서는 가위바위보와 묵찌빠 숫자가 달라 열거형에서 어떻게 풀어나가야할지 고민했습니다.
### 조언을 바라는 점
- 클래스 MukjjibbaGame의 getHandByplayer()의 부분에서 switch를 좀 더 가독성을 높일 수 있는 방법이 없을지 궁금합니다.

<br>

commit 메세지 실수를 했네요..ㅠ 
Feat : create RockPaperScissorsGame.swift, MukjjibbaGame.swift 부터 확인해주시면 감사하겠습니다!

2021-03-06 12:11 UTC, idevjinie requested changes
세 분의 열정 잘 봤습니다 🔥🧑‍🚒
switch 가독성을 포함해서 코멘트 몇가지 남겨두었어요.
커밋 로그도 훑어봤는데 전반적으로 하나의 커밋에 여러 작업이 포함되어 있었어요.
아직은 익숙치 않겠지만 커밋 로그를 읽는 것만으로 히스토리를 알 수 있도록 하나의 커밋에는 하나의 일만 기록해보세요.
남은 주말 동안 리프레시 잘하고, 이번 프로젝트에서 얻은 피드백을 다음 프로젝트에서 적극 반영해보면 좋겠습니다.
이번 한 주 정말 고생 많았습니다!

2021-03-06 12:51 UTC, KangKyung commented on RockPaperScissors/RockPaperScissors/RockPaperScissorsGame.swift
> +        case player = "플레이어"
묵지빠 프로젝트 step2의 출력(print)조건이 '플레이어'라서, 그렇게 변경했습니다..!

2021-03-06 12:53 UTC, KangKyung commented on RockPaperScissors/RockPaperScissors/main.swift
> +let mukjjibba = RockPaperScissorsGame()
묵찌빠 게임 안에 가위바위보 게임이 들어가있는 형태라고 생각해서 그렇게 명명했습니다.
더 좋은 이름을 찾아보겠습니다 조언 감사합니다☺️

2021-03-07 09:12 UTC, Kioding commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    }
CustomStringConvertible 프로토콜은 정의하여 출력할 수 있네요! 좀 더 알아보겠습니다 :)

2021-03-07 14:02 UTC, kane-young commented on RockPaperScissors/RockPaperScissors/MukjjibbaGame.swift
> +    }
0 의 경우는 게임 종료를 하기 위한 `return nil`이 필요하지만, 밑에 나머지 `1,2,3,default` 의 경우는 밑에 있는 `guard let playerHand ` 구문에서 처리되기 때문에 불필요하군요!!

2021-05-31 01:06 UTC, closed without merging