묵찌빠 게임 [STEP 1] namu, Charlotte
yagom-academy/ios-rock-paper-scissors pull request #54
Opened 2021-06-01 06:16 UTC by yaewonLee

@yagom
안녕하세요 야곰 6C 팀 STEP1 입니다.
궁금한 점은 README.md에 작성하였습니다. 
잘 부탁드립니다!

2021-06-01 10:57 UTC, yagom requested changes
고민이 참 많았죠? :)

질문은 README가 아니라, PR 코멘트에 남겨주세요~ 선배들의 PR 메시지를 보면 많은 참고가 될겁니다.
전반적으로 함수의 반환이라는 개념이 부족한 것 같아요.
함수는 입력과 출력으로 구성됩니다. 함수가 입력을 받는다는 것과 결과값을 돌려준다는 것에 대한 개념을 둘 다 명확히 해야할 필요가 있어요.
더 코드를 작성하기 전에 이 개념을 명확히 알고가야겠습니다.
함수가 입력을 받는다는 것은 어떻게 입력을 받는다는 것인지, 함수가 값을 돌려준다는 것은 어떻게 돌려준다는 것인지 알아봐야겠어요.
제 스위프트 기초 강좌에서 함수에 대한 부분을 다시 보면 힌트가 되려나요? 👀

그 점이 해결되면 코드가 엄청나게 달라질거라고 생각해요 :)

서두르지 말고 함수부터 다시 생각해봅시다 옙~! 🚀

2021-06-01 10:57 UTC, yagom commented on README.md
> +일단 현 단계에서는 전역변수를 사용하고 startGame() 내에서 함수들을 제어하는 방식으로 설계했는데, 피하는게 좋다면 다른 방향으로 리팩토링 해보고 싶습니다.
전역변수를 왜 피해야 한다고 생각하나요? 그 이유가 궁금합니다 :)
왜 저 질문이 나왔는지 배경에 대해서 리뷰어가 알지 못하면 이렇게 다시 되묻게 됩니다.

2021-06-01 10:57 UTC, yagom commented on README.md
> +- 배웠던 struct, class 개념을 적용해보고 싶은데, 어떻게 해야할지 감이 잘 오지 않습니다….
개념을 적용해 보고 싶다는 뜻이 무엇인가요? 타입을 만들어보고 싶다는 뜻이겠군요!
다음 프로젝트부터 적용해봐도 늦지 않습니다 :)

2021-06-01 10:57 UTC, yagom commented on README.md
> +- readLine() 받아온 String? 타입의 값을 옵셔널바인딩 구문 (if let / guard let)을 사용하지 않고, testValid()함수 내부 switch문에서 default case로 처리했는데, 이렇게 하면 옵셔널 바인딩이 안전하게 된 것이 맞을까요?  (= 꼭 if let / guard let을 사용해야만 옵셔널 바인딩이 가능한걸까
옵셔널 바인딩은 `if let` / `while let` / `guard let` 으로 할 수 있습니다.
switch 구문도 옵셔널 바인딩이 아녜요 :)

2021-06-01 10:57 UTC, yagom commented on README.md
> +if (Int(userChoice)! - computerChoice + 3) % 3 == 1 {
느낌표가 나오지 않도록 해주세요.
그 어떤 흐름에서도 느낌표가 나오지 않도록 해달라는 제약이 왜 필요한지 나중에는 이해할 수 있을거예요.
지금 당장 이해가 가지 않는다면 그런가보다 하고 넘어가도 괜찮아요.

2021-06-01 10:57 UTC, yagom commented on README.md
> +이런 식으로 알아보기는 어렵지만 간단하게 표현할 방법이 있을 때 쓰는것이 바람직한 방법인지가 궁금합니다.
알아보기는 어려운데 간단하게 표현한다는 것 자체가 뭔가... 역설인 것 같은데요?ㅎㅎ

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
함수 이름은 메시지를 스스로 출력해 줄 것 같은데, 막상 메시지를 출력하는게 아니라 문자열을 돌려주고 있네요 :)
단순히 문자열을 돌려준다고 해서 함수로서의 역할로 부족한 것은 아니나, 이름과 걸맞지 않는 동작이라는 생각이 듭니다

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> -//
필요없는 주석 지운 것 좋아요 :)

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
함수의 반환값이라는 것을 이해하면 전역변수를 훨씬 많이, 혹은 아예 없앨 수 있을지도 몰라요 :)

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func testValid(of input: String?) {
무엇에 대한 검증인가요? 빈 문자열인지? nil인지? 문자열 길이에 대한 검증인지?? 어떤 검증일까요?

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgeWinner() -> Void {
승자를 판단한다고 하는데, 승자가 누구인지 판단한 결과는 어떻게 전달되는걸까요?

`enum`을 사용하면 코드에서 몇몇 선택지를 만들어볼 수 있어요.
하루이틀 내로 이해되지 않으면 enum은 다음 프로젝트에서 구현해봐도 괜찮습니다~!

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func setComputerChoice() {
set은 어디엔가 값을 세팅해준다, 꽂아준다 뭐 이런 뉘앙스 아닐까요? :)

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    computerChoice = Int.random(in: 1...3)
일 년 뒤에, 아니 3개월 뒤에 이 코드를 보면 1과 3이 뜻하는 바가 무엇인지 한 번에 파악할 수 있을까요?
날것의 숫자에 의미를 명확하게 줄 수 있는 방법은 뭐가 있을까요? :)

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +
여기 한 줄은 왜 띄었나요? 특별한 이유가 있을까요?

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func pickWinner() -> Void{
다른 함수와 다르게 `Void`와 중괄호 사이에 띄어쓰기가 없는 이유는 무엇일까요? 👀

2021-06-01 10:57 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
`where`를 활용한 것은 정말 멋지네요 👍 
여기도 마찬가지로 1년 뒤에 1과 2와 3이 어떤 의미인지 단번에 알아챌 수 있을까요? 🤔

2021-06-01 12:14 UTC, YongHoonJJo commented on README.md
> +- readLine() 받아온 String? 타입의 값을 옵셔널바인딩 구문 (if let / guard let)을 사용하지 않고, testValid()함수 내부 switch문에서 default case로 처리했는데, 이렇게 하면 옵셔널 바인딩이 안전하게 된 것이 맞을까요?  (= 꼭 if let / guard let을 사용해야만 옵셔널 바인딩이 가능한걸까
오.. `while let` 이란 것도 있었군요..!!

2021-06-02 11:04 UTC, yaewonLee commented on RockPaperScissors/RockPaperScissors/main.swift
> +func testValid(of input: String?) {
무엇에 대한 검증인지 함수명에서 더 명확하게 표현하라는 말씀으로 이해하면 될까요?

2021-06-02 11:13 UTC, yaewonLee commented on README.md
> +일단 현 단계에서는 전역변수를 사용하고 startGame() 내에서 함수들을 제어하는 방식으로 설계했는데, 피하는게 좋다면 다른 방향으로 리팩토링 해보고 싶습니다.
제가 평소 코딩을 할 때 전역변수 사용이 코드 작성에 편리해서 많이 사용하는데, 어디선가 전역변수 사용이 좋은 것이 아니라는 말을 본 기억이 있어서 질문하게 되었습니다.

2021-06-02 11:24 UTC, jsim27 commented on README.md
> +- readLine() 받아온 String? 타입의 값을 옵셔널바인딩 구문 (if let / guard let)을 사용하지 않고, testValid()함수 내부 switch문에서 default case로 처리했는데, 이렇게 하면 옵셔널 바인딩이 안전하게 된 것이 맞을까요?  (= 꼭 if let / guard let을 사용해야만 옵셔널 바인딩이 가능한걸까
switch의 default로 처리하는것은 옵셔널 바인딩이 아니라는 것, 잘 알겠습니다! :)

그런데 지금 저희 코드 상에서, nil 값까지 바인딩 없이도 처리가 되지 않을까 하는 궁금증이 있었어요. 제 생각에는 처리가 되는 것 같아서요..

2021-06-02 12:12 UTC, jsim27 commented
@yagom 
리뷰 감사합니다! 덕분에 공부도 많이 하고 고민을 많이 했어요.

리뷰해주신 내용을 바탕으로 많은 수정들을 했고, 다음은 그 내용입니다!

- 코드의 가독성을 위해 1, 2, 3으로 표현되던 손패를 Hand라는 enum을 생성해 값을 전달
- show로 시작하는 메세지 출력 함수들을 이름에 맞게 직접 출력하는 기능으로 변경
- 전역변수에 값을 저장하여 함수간 값을 주고받던 구조에서 전달인자를 통해 주고받는 구조로 변경
- recieveInput() 함수에서 readLine()으로 입력받은 값을 옵셔널바인딩하는 코드 추가
- 코딩 컨벤션에 어긋나는 일관적이지 않은 표현 수정
- setComputerChoice() 함수를 기능에 맞게 generateComputerChoice()로 네이밍 변경

2021-06-02 14:48 UTC, yagom approved these changes
고생 많았습니다 :)
이번 PR은 코드가 한단계 업그레이드 된 것 같아요!

한 가지 개선했으면 좋겠다는 점은 커밋이 번갈아 되지 않았고, 한 커밋에 모든 내용이 모여있다는 것이에요.
커밋 4e7d6a0339768a6e61db40f35ab5ef60e751fef8 에 모든 수정사항이 모여있는데, 커밋 단위를 나누는 습관을 들이는 것이 좋을것 같아요.
커밋의 의미는 무엇이고, 커밋을 왜 나눠 하라고 한 것일까요?
커밋은 어떤 단위로 나눠서 하는 것이 좋을까요?

또, 전역변수가 안좋다고 주장한 사람의 결론이 중요한 것이 아니라 그 사람이 어떤 근거로 그렇게 이야기한 것인지도 한 번 찾아보면 좋겠습니다. 샬롯과 나무는 그사람의 의견에 전적으로 동의하거나 반대하나요? 어떤 의견을 갖고있나요? 왜 그렇게 생각하는지 제게 그 의견을 알려주면 좋겠습니다.

개선의 여지가 남아있지만 다음 스텝에서 충분히 반영할 수 있을것이라 생각해요! 이번 PR 머지할게요 ;)
고생 많았고, 다음 스텝에서 만나요! 🚀

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case exitGame = "0"
Hand 타입 안에 관련없는 case가 있는 것 같아요 :)

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
게임 시작 함수 내부에 시작 메시지를 보여주는 함수만 호출해주고 있는데, 그렇다면 startGame 함수가 꼭 필요한 함수일까 의문이 듭니다

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
함수 이름은 메시지를 보여준다 인데, 입력까지 받고있군요!

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
오! 함수 네이밍도 옵셔널 바인딩도 좋아요!

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
>      case "1":
```suggestion
    case Hand.scissors.rawValue:
```

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
>  }
오류 메시지를 보여주는 함수에서 시작 메시지까지 출력하고 있군요!

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        judgeWinner(userChoice: Hand.paper)
열거형의 활용, 훨씬 코드가 직관적으로 변했죠? 👍

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgeWinner(userChoice: Hand) -> Void {
매개변수의 활용 좋습니다! 👍

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let randomNumber = Int.random(in: 1...3)
Int의 1~3 중에 임의의 값을 만드는 대신, `Hand` 타입에서 임의의 case를 뽑아내는 방법이 더 직관적이고 좋을것 같단 생각이 드는군요 😎

2021-06-02 14:48 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func pickWinner(userChoice: Hand, computerChoice: Hand) -> Void {
매개변수의 활용으로 전역변수 사용을 줄일 수 있었군요! 🥇

2021-06-02 14:49 UTC, merged

2021-06-03 12:47 UTC, jsim27 commented
* 아직 커밋을 나눠서 하는 습관이 없어서 단위를 나누지 않고 끝까지 쭉 작업하게 되는 것 같네요..ㅜㅜ 단계를 나누어 기능별로 수정하고 커밋하면 추후에 수정방향의 오류를 깨달았을 때 쉽게 특정 시점으로 돌아갈 수 있는 등 많은 장점이 있는 것으로 알고 있습니다. 세분화된 커밋하기를 습관화해볼게요!  


* 전역 변/상수 중에서도 전역"변수"의 사용을 줄이는 것이 좋은 근거를 찾아봤어요! 

1. 전역변수를 사용하면, 여러 함수들이 작동할 때 맨 윗줄에 선언된 전역변수의 값을 참조하고 변경하길 반복하는데, 이럴 경우 프로그래머 본인과 협업자 모두가 혼란스러울 수 있다고 합니다. 코드의 flow를 따라가는 와중에 모든 전역변수의 변경상태를 인지하며 코딩/검토해야하기에 가독성있는 코드가 아니게 되는 것이지요. 그래서 전역변수로 값을 저장/참조하기 보다는  매개변수와 반환값을 통해 함수에서 함수로 직접 전달하는 것이 좋은 방식이라고 이해했습니다.

2. 지금처럼 프로그램의 규모가 작을 때는 전역변수 사용이 편리하다 느낄 수 있지만, 규모가 커질수록 아주 많은 함수들이 단 하나의 변수를 통해 작동하기에 함수 재사용성을 떨어트리고 오히려 로직이 제한되는 상황이 있을 수 있습니다. 편의를 위해 사용한 방법이 오히려 코딩을 어렵게 하는 것이죠. 

3. 다른 인스턴스에서 참조하거나 값을 변경할 필요가 없는 / 변경하면 안되는 경우에 접근 제어를 해야 하는데, 전역 변수는 프로그램 모든 곳에서 접근할 수 있기에 잘못된 접근으로 에러를 유발할 수 있습니다.

4. 동시성 문제 - 추후 여러 스레드를 통해 프로그램이 작동될 경우에, 모든 함수와 전역변수의 관계를 파악해 작업순서를 정해주기는 어렵다고 합니다. 전역변수가 동기화가 적절히 되어야 하는데, 이를 컨트롤하기란 아주 어려운 작업이 될 것입니다. 

5. Namespace 오염 문제 - 사용자가 인지하지 못하는 사이 같은 이름의 지역변수를 사용하거나 스펠링 오류를 범할 경우 원인을 알아차리기 어려운 에러가 발생할 수 있습니다.

이 외에도, 코드를 테스트하기 어려워지거나 메모리 관련 문제도 있는 듯 합니다. 

위 내용을 알게되니 왜 전역변수 사용을 가급적 줄여야 하는지 충분히 납득이 되었어요!


리뷰 감사합니다 야곰! 다른 수정사항들도 반영하여 Step2 진행해볼게요!

2021-06-03 15:48 UTC, yagom commented
찾아보느라 고생 많았겠습니다 ㅎㅎ 모두 다 좋은 이야기들이네요.
이렇게 어떤 이야기들을 들었을 때, 그 이야기의 결론만 취하기 보다는 그 결론이 왜 나왔는지를 찾아보고 이해해보는 습관이 중요합니다. 더불어 그 주장의 반대 의견도 찾아보고 그 근거들을 비교해본 후 나의 기준을 찾아가는 것도 중요해요.
위에 남겨준 코멘트에 대한 이해는 두 짝꿍 모두가 이해하고 넘어가면 좋겠네요. 지금 스텝2 코드 한 줄 작성하는 것보다 훨씬 중요한 일입니다. 
둘 다 모두 이해하고 넘어갈 수 있도록 서로에게 설명해주세요. 중요과제입니다 🙏