묵찌빠 게임 [Step 1] shapiro, jamking
yagom-academy/ios-rock-paper-scissors pull request #56
Opened 2021-06-01 06:56 UTC by shapiro711

@SungPyo 

안녕하세요 내일날씨맑음!! step-1을 완성하여 풀리퀘스트를 보냅니다!! 잘 부탁드려요 :)

## 고민한 부분
### 1.열거형 사용법에 대한 고민
열거형의 원시 값 저장과 사용법을 잘 몰라 찾아보며 공부했습니다.
### 2. 게임 흐름 제어 부분
게임 흐름 제어에서 막혀서 재귀를 사용하여 해결했습니다
### 3. 기능 별로 함수 나누기
한가지의 기능만 하도록 함수를 나누도록 노력했습니다.
### 4. 1,2,3 이라는 숫자로 가위바위보로 어떻게 명시할지 고민했습니다
열거형을 사용하여 rawvalue값을 이용하여 해결하였습니다.

## 조언 받고 싶은 부분
### 1. computeGameResult() 함수 로직

``` swift 
func checkGameResult(user: RockPaperScissors, computer: RockPaperScissors) {
    if user == computer {
        gameResult = .draw
    }
    
    switch user {
    case .scissors:
        if computer == .paper {
            gameResult = .win
        }
    case .rock:
        if computer == .scissors {
            gameResult = .win
        }
    case .paper:
        if computer == .rock {
            gameResult = .win
        }
    case .etc:
        printError()
    }
}
```
처음에 위와 같은 로직을 사용했다가 현재의 로직으로 바꾸었습니다.
위의 방법이 더 명확하게 표현 했다고 생각을 하고 바뀐 코드는 간결하게 표현했다고 생각하는데
어떤 방법이 더 괜찮은지 여쭤보고 싶습니다!

### 2. computeGameResult()
처음에 이 함수의 이름을 checkGameResult() 라고 지어줬습니다.
무언가를 체크한다 라는 함수네이밍을 사용할 경우에 Bool값을 반환하는 것이 이름에 맞다고 생각하여 바꾸었습니다.
하지만 함수의 내용은 결국 누가 이겼는지 판단해주는 것이라고 생각합니다. 이럴 경우 어떤 네이밍이 더 적합할까요?

2021-06-01 14:42 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +var computerValue: RockPaperScissors = .paper
이 전역 변수들이 과연 정말 필요한 변수들일까요? '꼭 없어져야만 한다' 는 아닙니다.
함수의 반환값을 이용하면 전역변수를 불필요하게 초기화 하지 않고도 가능할것 같아요 :)

2021-06-01 14:43 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +var isExit: Bool = false
프로젝트가 거대해 질수록 이러한 플래그는 가독성을 해치는데 많은 영향을 줍니다.
 inputUserValue 내부에서 1,2,3 과 같이 하드코딩한 값을 사용하지 않는다면... isExit도 없앨 수 있을 것 같은데 한번 해보시겠어요?!

2021-06-01 14:44 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let value = RockPaperScissors(rawValue: Int.random(in: 1...3)) {
1. 1...3과 같은 매직넘버를 사용하지 않고 RockPaperScissors를 생성할 수 있는 방법을 한번 공부해보세요! (힌트: CaseIterable)
2. 제가 실무에서 사용하는 옵셔널 바인딩은 상황에 따라 if let, guard let, flatMap을 구분하여 사용합니다. 요 세가지 방법에 대해 한번 고민해보시겠어요? (정답이 있는건 아닙니다 ^^)

2021-06-01 14:46 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +func computeGameResult(user: RockPaperScissors, computer: RockPaperScissors) {
뺼셈을 이용하여 승패를 결정하는 로직을 구성하셨군요! 하지만 수개월 뒤 이 코드를 봤을때 이해가 쉬울까요?
 여기있는 매직넘버(숫자)가 없는 순수 enum으로는 구성이 힘들까요? 아주 고 난이도가 될 수도 있는데 한번 고민해보세요! 
(힌트: 가위,바위,보 에 대한 비교로직 함수를 나눠보세요!)

2021-06-01 15:09 UTC, SungPyo requested changes
야곰 아카데미에서의 첫 리뷰입니다! 잘 부탁드릴게요 :)

아래에 답변 드리는 내용 및 코멘트, 그리고 앞으로 제가 리뷰해 드리는 내용이 절대적인건 아닙니다. 
리뷰어마다, 사람마다, 캠퍼마다 성향의 차이와 코드 스타일이 다 다르기 때문에 '정답은 없다' 라고 생각하시면 좋을 것 같아요.
낮에 제가 디스코드에서 말씀드린 것 처럼. 다른사람이 맞다고 하는 '남' 의 코드가 아니라 '내' 코드가 더 중요합니다. 정답에 가깝고 깔끔한 다른사람의 코드를 보기전에 앞으로 '나' 는 어떻게 코딩할 것이고 어떤 스타일을 추구할 것인지 정하는 걸 추천드립니다! 
저 또한 4년이 넘는 시간동안 수십번의 코드 스타일이 변경되었고, 앞으로도 계속 변화될 예정입니다.

코멘트 중간중간 고민해보고 수정해보라는 내용이 있는데, 무조건 해야 하는 건 아니니 부담갖진 마세요!

**고민한 부분에 대한 답변** 
- 
- **열거형 사용법에 대한 고민**
기본적인 사용법에 대해서는 문제가 없을 정도라고 판단됩니다. 이제 막 시작이니까요! 고민한 결과가 좋다고 보여집니다. 물론 Swift의 열거형은 정말 많은 기능이 있기때문에, 계속해서 고민해 주세요 화이팅!

- **게임 흐름 제어 부분**
 왜 '게임 흐름 제어에서 막혔다' 라고 생각하셨을까요? 재귀 함수를 호출한것도 하나의 아이디어이고 제가 생각했을때는 '막혔다' 보다는 '해결했다' 에 가깝다고 생각되네요.

- ** 기능 별로 함수 나누기**
 이 부분은 칭찬 드리고 싶습니다. 완벽하진 않더라도, 기능별로 함수를 나누고자 했던 노력이 코드에서 보여집니다. 이 부분은 계속해서 노력해주세요!

- **1,2,3 이라는 숫자로 가위바위보로 어떻게 명시할지 고민했습니다**
 1,2,3 이라는 숫자를 꼭 사용해야 할까요? 제가 각 라인별 코멘트를 따로 달아놓았는데, 코멘트를 보시고 한번 더 고민해 보셔도 좋을것 같아요.
 
 **조언 받고 싶은 부분에 대한 답변** 
-
- **computeGameResult() 함수 로직**
 코멘트로 달아주신 함수가 1번, PR 요청한 코드가 2번이라고 하면 저는 1번이 더 좋습니다. 이유는 코멘트에 달아주신 내용과 같습니다. 더 명확하게 표현되었다고 생각되거든요 :)
 
 - **computeGameResult()**
 저도 네이밍엔 상당히 약한 편입니다만...^^: computerGameResult 라는 이름 자체가 주는 의미가 더 명확하다고 생각됩니다. check는 무언가를 체크하는 함수라고 생각할 것 같은데, 무언가를 체크한다기 보다 결과를 대입하는 거니까요. 다만 한가지 아쉬운건 Result가 들어가면 결과를 반환해야 할 것 같은데 무언가를 반환하지 않는다는 것이죠. 비교하고 대입을 하는 함수니까 Result보단 Compare 쪽이 더 어울리지 않을까 싶습니다!

2021-06-02 08:46 UTC, jaemuYeo commented
코드 수정하였습니다!!

2021-06-02 14:52 UTC, shapiro711 commented
@SungPyo 
안녕하세요!! 내일날씨맑음!

리뷰를 받으면서 정말 많은 것을 느낄 수 있었습니다! 정말 도움이 많이 되었어요 감사합니다 :)

## 새로 수정한 내용
1. 전역 변수 대신 함수 반환값 이용
2. 프로그램 종료시키는 로직에서 전역변수로 만든 플래그 사용하지 않기
3. CaseIterable 사용하여 enum에 접근해보기
4. 유저의 값을 받는 함수에서 하드코딩 하지 않고 받은 값에 맞는 가위, 바위, 보 넣어주기
5. 가위바위보 비교 로직 변경

이렇게 수정 하였습니다!!!

2021-06-02 17:02 UTC, SungPyo commented
아쉬운 부분이 없지 않아 있지만 그래도 1차 리뷰에 비하면 많이 변화된 모습이 보여서 좋네요!

 **수정한 내용에 대한 답변** 
-
- **전역 변수 대신 함수 반환값 이용**
1번과 2번이 공통된 답변입니다!
이 부분은 완벽하게 잘 해주신 것 같아요. 함수의 반환값을 조금만 더 깊게 이용했으면 하는 아쉬움이 남지만 이정도면 충분했던 것 같습니다.
 
 - **CaseIterable 사용하기**
제가 힌트를 드린 내용이고 이 부분에 대해서 제가 생각했던 대로 사용하셨습니다! 하지만 이렇게 사용한다! 를 끝으로 보지 마시고, 어떻게 구현되어 있는지, 어떨때 사용하면 좋을지 등을 더 깊게 고민해 보시면 좋을것 같아요!

 - **유저의 값을 받는 함수에서 하드코딩 제거하기**
4번과 5번이 공통된 답변입니다!
이 부분도 수정 이후 코드를 보시면 기존의 매직넘버 보다 더 명확하다고 느껴지지 않으시나요? 
코드가 길어져서 어떻게 하면 좋겠냐는 질문도 디코에서 같이 하셨는데, 코드를 획기적으로 줄이는 방법이 있을것 같진 않다고 생각됩니다.
다만 유저의 값과 컴퓨터의 값이 같은 경우에는 무조건 비기는 상황이니 guard 로 한번 막아준다면 비기는 로직에 대한 부분은 줄어들지 않을까요?


부족한 부분은 다음 스텝에서 진행하는 것으로 하고 수정한 내용에 대한 답변으로 마무리 하고 머지 하도록 하겠습니다!
코드가 만족스러워서 머지하는건 아니라는걸 명심해 주시고, 다음 스텝에서도 계속 고민해서 좋은 발전을 이뤄내시면 좋겠습니다 :)

2021-06-02 17:02 UTC, merged