1-jake
yagom-academy/ios-rock-paper-scissors pull request #6
Opened 2020-11-05 02:30 UTC by jryoun1

Step 1 가위.바위.보 게임까지 진행한 코드입니다.
코드 리뷰 부탁드려요~

2020-11-05 02:56 UTC, yagom reviewed
열심히 해내고 있네요!
몇 가지 질문이 있습니다 :)

2020-11-05 02:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var resultNum = 0
주석을 적지 않더라도 resultNum의 값을 직관적으로 알 수 있도록 하는 방법은 없을까요?

2020-11-05 02:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgmentWinDrawLose (computer : Int, user : Int) -> Int {
아래 함수들과 띄어쓰기가 다른데 특별한 규칙이나 이유가 있나요?

2020-11-05 02:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func isChoiceComputer() -> Int {
이름을 다시 고민해보면 좋겠습니다. 주석 없이 이름만으로 이 함수가 어떤 결과를 주는지 모르겠습니다.
Swift API Guidelines를 통해 고민해보세요.

2020-11-05 02:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputRockPaperScissors() {
함수의 이름은 가위 바위 보를 입력받는 함수라고 되어있는데, 내부에서 문자를 출력하기도 하고 승패를 판단하기도 합니다.
함수 사용에 있어 오해의 소지가 많지 않을까요?

2020-11-05 02:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNum = Int(input) else { return print("게임 종료") }
사용자의 입장에서 왜 게임이 종료되었는지 알 수 없을 것 같아요

2020-11-05 02:56 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +@discardableResult
이 함수의 결과 값을 사용하지 않고 있는 것 같은데, 반환 타입을 만든 이유가 있나요? 또, 반환 타입을 만든 이유가 있다면 그 반환 값을 왜 사용하고 있지 않은지도 궁금합니다.

2020-11-05 03:00 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +@discardableResult
코드 리뷰 감사해요 야곰!!
먼저 여기서 반환 타입을 만든 이유는 step2에서 묵.지.빠 게임을 진행하기 위해 가위.바위.보 결과를 return 해주어야 한다고 생각했습니다. 그래서 step2 코드를 작성할 때 사용하려고 했습니다. 하지만 step1에서는 return 값을 사용하지 않으므로 삭제하고 나중에 추가하는 것이 좋을까요??

2020-11-05 03:04 UTC, hakju commented on RockPaperScissors/RockPaperScissors/main.swift
> +func isChoiceComputer() -> Int {
우선 리뷰 감사드립니다 야곰!
함수명에 대해서 다시 한번 생각해보도록 할게요!

2020-11-05 03:06 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +@discardableResult
맞다 틀리다의 문제는 아녜요 :)
지금은 간단한 작업이라 바로 내일 작업할 수 있어서 큰 문제가 되지 않을 수 있지만,
현업에서 큰 덩어리들을 만났을 때는 다음 주에 요구사항이 어떻게 변경될지 모르는 경우가 많아요.
현재 커밋은 현재 구현한 기능에 맞게 두는 것도 좋은 방법입니다.
하지만, 합당한 이유가 있다면 작업자의 결정에 맡길 수 있는 일이죠. 자신의 판단에 따라 진행해 보는 것도 좋습니다.

2020-11-05 03:09 UTC, hakju commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNum = Int(input) else { return print("게임 종료") }
우선 리뷰 감사드립니다 야곰!
입력하지 않을 경우의 예외처리를 표현해준거고 저 부분은 출력할 가능성이 희박하다고 생각하여 마음대로 작성한 것 같습니다.
만약 출력이 된다면 사용자 입장에서 생각해보니 게임이 왜 종료되었는지 알 수가 없을 것 같네요.
지니가 말했던 "필요없는 코드는 없다."라는 말이 생각이 나네요. 수정하겠습니다!

2020-11-05 03:15 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var resultNum = 0
사실 처음에는 result를 String 타입으로 선언하여 결과를 직관적으로 알려줄까도 고민해봤었는데, 이 결과 값을 반환 값으로 하여 step2묵.찌.빠 게임에서 결과 값에 따라 case를 구분할 때 문자열을 비교하는 것보다는 Int형을 비교하는 것이 효율적일 것 같아서 Int형으로 작성하고 주석으로 처리했습니다. 하지만 막상 저도 1,2,3 번이 뭐였는지 헷갈리는 것을 봤을 때는 결과를 직관적으로 보이도록 만드는 것이 좋을 것 같다고 생각이 들었습니다. 감사합니다.

2020-11-05 03:17 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgmentWinDrawLose (computer : Int, user : Int) -> Int {
아니요 야곰 저도 모르게 space가 들어간 것 같아요 ㅠ 코드 작성의 통일성을 지키도록 할게요!!

2020-11-05 03:17 UTC, hakju commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputRockPaperScissors() {
우선 리뷰 감사드립니다 야곰!
생각해보니 야곰의 말처럼 오해의 소지가 많을 것 같아요!
step 1 기능을 우선적으로 처리되게 만드려고 억지로 그랬던 것 같아요.
함수 이름대로 입력만 받게하고 다른 처리들은 다른 함수에서 이루어져야 할 것 같네요!
어떻게할지 고민해봐야겠어요.

2020-11-05 03:20 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func isChoiceComputer() -> Int {
의견을 개진하고 토의를 할 필요가 있을 때 빼고는 코멘트마다 답할 필요는 없어요 ㅎㅎㅎ
코드로 대답을 해도 됩니다~
아래 jake의 코멘트 댓글처럼 의논이 필요한 부분에만 코멘트 해도 괜찮아요 :)

2020-11-05 09:21 UTC, yagom commented
한 번 PR을 보낸 이후에는 다음 push가 코드 pr을 한 번 더 보내는 것과 같은 효과를 줍니다.
이번 수정내역 두 커밋도 리뷰를 위해서 push 한걸까요?

2020-11-06 00:54 UTC, yagom requested changes
발전하고 있네요!

2020-11-06 00:54 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let input = readLine() else { print("입력값이 nil이라서 종료됩니다."); exit(0) }
https://wotjd.github.io/2019/06/ios-%EC%95%B1-%EC%A2%85%EB%A3%8C%ED%95%98%EA%B8%B0-how-to-quit-app-in-swift/

2020-11-06 00:54 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func main(){
띄어쓰기는 의도된 것일까요?

2020-11-06 00:54 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func RockPaperScissorsGame() {
함수의 이름은 어떻게 지어야 할까요?
Swift API Guidelines 참고해보세요

2020-11-06 08:08 UTC, yagom reviewed
이번에도 몇 가지 질문이 있어요 :)
고군분투 하고 있는 모습이 보입니다!

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let input = readLine() else { print("입력하지 않아서 종료합니다."); return "0" }
사용자에게는 더 명확하게 와닿겠네요 ㅎㅎ 사용자는 프로그래머가 아니죠 :) 좋은 배려입니다.

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printMukChiPaResult(_ judgement : String) {
함수 이름을 보면 전달인자로 전달한 문자열을 그대로 출력해줄 것만 같아요.
전달할 값이 무엇인지 함수를 호출하는 입장에서 생각해 봐야 하지 않을까요?

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    default : //묵찌빠 게임이 종료 되었을 경우
각각의 띄어쓰가 다른 이유가 있을까요?

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return print(judgement)
print 함수의 결과 값이 있나요? 그것을 return 하는 이유를 알 수 있을까요?

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func judgementMukChiPaWinLose(computer : Int, user : Int, turn : String) -> String {
컴퓨터와 사용자 자체가 이 매개변수로 전달되는 것일까요?
컴퓨터의 무엇과 사용자의 무엇이 이 곳으로 전달되어야 할까요?
내가 함수를 사용하는 다른 프로그래머라는 입장으로 생각해봅시다.

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case 1 : // computer 묵인 경우
주석이 없이도 이 case가 묵이라는 것을 표현할 수 있는 방법은 없을까요?

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +startRockPaperScissors()
불필요한 main 이라는 함수를 사용한 것보다는 훨씬 깔끔하네요 :)
하지만 때로는 main이라는 함수 자체가 관례적인 사용이기 때문에 직관적일 수도 있어요.
프로그래머의 결정에 달렸습니다. 전 다 좋아요 :)

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    userNumber = verifyInput(userInput : inputRockPaperScissors())
verifyInput 함수는 입력값을 검증만 하는 것 같은데, 이름만 보아서는 반환된 값이 어떤 값인지 전혀 감이 오질 않습니다.
좀 더 나음 방법을 고민해봅시다.

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var userNumber : Int = 0
아직까지 명확히 사용자의 입력값을 알 수 없는 상태에서 사용자의 입력값을 0으로 둔 이유가 있을까요?
아직 알 수 없는 값을 표현하는 방법은 없을까요?

2020-11-06 08:08 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        var judgment : String = ""
"" 빈 문자열도 하나의 문자열 값입니다.
실제로는 판단이 끝나지 않은 상태라면 어떻게 표현해 주는 것이 좋을까요?

2020-11-06 08:48 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerNumber = Int.random(in : 1...3)
전체적인 코드를 보았을 때 코드 형식이 통일이 안된 부분이 있어서 통일을 하는 과정에서 띄어쓰기를 하기로 하였습니다.

2020-11-06 09:58 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerNumber = Int.random(in : 1...3)
그렇군요! 팀끼리 협의된 내용이라면 그대로 팀끼리 지키기만 한다면 문제 없습니다.
기존에 애플에서 사용하는 컨벤션은 공식 문서에서 확인해 볼 수 있습니다.
https://docs.swift.org/swift-book/LanguageGuide/Functions.html

2020-11-06 13:51 UTC, yagom approved these changes
단 며칠만에 많은 발전을 이뤘네요!
여기서 코멘트 한 내용은 다음 프로젝트에 이어서 고민해봐도 됩니다 :)
이번 한 주 고생했어요.
코멘트 확인하고 직접 머지해도 좋습니다.

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
enum을 활용한 시도가 좋네요!
enum의 case 이름을 정하는 방법은 Swift 언어 가이드 문서를 보는 것이 좋겠습니다.

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
enum의 이름을 짓는 방법에 대해서는 문서를 보는 것이 좋겠습니다.

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let Rock = RockPaperScissors.Rock.rawValue
변수 혹은 상수의 이름을 짓는 방법이 서로 다르네요. 뭐가 맞는걸까요?

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case Rock :
숫자를 사용한 것보다 훨씬 직관적으로 바뀌었네요 :)

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if userHand == Scissors { print("비겼습니다!"); result = "비겼습니다!" }
print로 출력하는 문자열과 result로 반환하는 문자열이 같네요. 
나중에 문자열을 변경해야 한다면, 실수를 줄일 수 있는 방법은 없을까요?

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printMukChiPaResult(by judgement : String) {
함수 내부에 print 함수 한 줄만 들어가 있는데, print 함수를 사용하는 것과는 무엇이 다를까요?

2020-11-06 13:51 UTC, yagom commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let Chi = mukChiPa.Chi.rawValue
변수 혹은 상수의 이름을 짓는 방법이 서로 다르네요. 뭐가 맞는걸까요?

2020-11-08 15:08 UTC, merged