[STEP1] 수박, jint
yagom-academy/ios-rock-paper-scissors pull request #65
Opened 2021-06-02 03:02 UTC by filmcanister

1) 변수나 함수의 이름을 어떻게 지을 것인지,,,
2) 변수나 함수의 이름을 지은 뒤, 이 이름에 잘 맞는 기능을 하고 있는지 확인하는 과정
3) 타입을 만드는 데에 class, struct, protocol 등이 사용될 수 있는데 뭘 사용해야할지(기준이 있다면?)
4) 메서드 여러개가 서로 호출하여 도미노처럼 진행되는 형태가 좋을지, 혹은 main부분에서 매번 필요한 함수를 호출 후 리턴값을 저장한 후에 새로운 함수를 직접 호출하는 방식이 좋을까요?

저번 pr 잘 close해주셔서 감사합니다. 의견주신대로 하나의 pr로 새로 만들어 보내드립니다.
항상 감사드립니다!

2021-06-02 14:19 UTC, yagom commented
PR 메시지에 리뷰어를 태그하지 않으면 리뷰어가 PR을 확인하지 못합니다.
@filmcanister @soo941226 @leejun6694

2021-06-02 15:41 UTC, leejun6694 requested changes

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +class RPS {
줄임말을 보고 모두가 이해할 수 있는게 아니라면, 네이밍이 길어져도 좋으니 풀어서 작성 부탁드립니다 : )

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand : Int {
사소한 띄어쓰기도 중요합니다!

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let input = Int(readLine() ?? "") , input >= 0 && input <= 3 else {
띄어쓰기...!

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let input = Int(readLine() ?? "") , input >= 0 && input <= 3 else {
guard 문을 통해 optional 값 및 조건을 하나씩 처리하는 로직으로 보입니다.
다만, 중간 연산 과정이나 결과물을 보면 아직도 optional 이 남아있는 것으로 보이네요.
메서드 내에서 다 처리해보는건 어떨까요?

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func userHand() -> Hand? {
메서드는 행동으로 비유를 할 수 있습니다.
네이밍을 수정해본다면 더 읽기 좋을 것 같네요.
참고 : Swift Coding Convention (Style Guide)

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let input = Int(readLine() ?? "") , input >= 0 && input <= 3 else {
input 의 값이 어떤 것과 비교되는지 좀 더 명확하게 작성한다면, 코드를 읽는 사람이 더 이해하기 좋을 것 같네요 ㅎㅎ

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func matchOutcome(hand userHand: Hand?) -> GameState {
parameter 도 Swift Style Guide 를 참고한다면, 더 읽기 좋게 작성할 수 있을 것 같습니다.

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let computerHand = Hand(rawValue: Int.random(in: 1...3))
현재 코드 상에선 문제가 없을 것으로 보이지만, 혹여나 다른 어떠한 이유로 인해(?) computerHand 가 nil 이 되어버린다면 게임이 어떻게 진행될까요?

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let hand: Hand = userHand else {
타입 추론에 대해 찾아보고, 어떤 장점이 있는지 생각해보아요 : )

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +
다른 코드들을 살펴봤을 때, 이 부분은 엔터가 없을 것이라고 저는 추측했습니다 @.@
혹시 일부러 띄워둔 곳일까요?

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func startGame() {
메서드들의 역할 분배를 잘하고, 로직을 잘 구성해서 게임을 진행하는 부분은 코드가 간결하네요 👍

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case error = 0
게임을 진행하는 문구를 보면, 0은 다른 케이스를 담아야할 것 같네요..!

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if  (hand == Hand.scissors && computerHand == Hand.rock) ||
띄어쓰기..........!!

2021-06-02 15:41 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            gameContinue = outcome == GameState.continueGame
게임 멘트 중 0은 종료를 나타내는데, 명확하게 종료하는 케이스가 있으므로 에러인 경우에도 게임이 계속 진행되면 어떨까해요~~!

2021-06-02 15:52 UTC, leejun6694 commented
안녕하세요. 쿠마입니다 : )
enum 과 메서드들의 역할을 잘 구분해주셔서 코드를 읽는데 어려움이 없었습니다. 고생 많으셨어요 💯 

질문 주신 내용에 답을 드리면
- 네이밍의 경우 Swift Coding Convention (Style Guide) 등으로 검색을 해서, 문서를 읽으면 좋은 자료들이 많습니다. 참고해서 공부하면 좋을 것 같네요~~!
- 네이밍은 개발자의 영원한 숙제로 보입니다... 지금은 확인하는 과정을 어떻게 하고 계실까요!?
- 타입을 어떻게 만드는지는 경우에 따라 너무 다를 것 같네요ㅠㅡㅜ 수박, jint 는 어떻게 기준을 나누면 될 것 같나요?
- 메서드의 호출도 상황에 따라 바뀔 것 같네요 @.@ 이번 프로젝트를 진행할 땐, 어떤 점을 고려해서 구현하셨나요?

2021-06-03 01:54 UTC, soo941226 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        guard let input = Int(readLine() ?? "") , input >= 0 && input <= 3 else {
여기서 두번째로 말씀하신 내용이 함수의 리턴값을 얘기하시는 건지, 아니면 변수 input을 얘기하시는 건지 잘 모르겠습니다..!
일단 type(of:input)으로 input을 확인을 해봤는데 Int로 찍히는데 이게 옵셔널을 포함하고 있는지 잘 모르겠습니다..

2021-06-03 01:54 UTC, filmcanister commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum Hand : Int {
띄어쓰기는 함수와 함수 사이 외에는 모두 붙여주는것인가요?
줄간격이 들어가야하는 부분이 정확히 언젠지 궁금합니다.

2021-06-03 03:08 UTC, filmcanister commented
@leejun6694 

네이밍은 swift에선 주로 기능을 잘 설명하게 축약형이 아닌방향으로 만드는 연습을 하고 있고요
타입의 경우에는 좀더 다양한 기능을 이용해보아야 저희가 각 타입에 대한 장단점을 알고 활용할 수 있을것 같아요 ㅎㅎ
메서드는 의존성을 낮추기 위해 (향후 활용도를 높이기 위함?) 각자 독립적으로 작동할 수 있도록 구현하는게 좋을것 같다고 수박이 의견제시해줬습니다....


리뷰해주신 내용으로 수정해보았으니 한번 확인해주시면 감사하겠습니다.
너무 친절하게 잘 확인해주셔서 수박하고 할얘기가 많아서 좋았습니다!

2021-06-03 17:09 UTC, leejun6694 approved these changes
리뷰 내용이 많은 부분 반영되어 있습니다 👍 
다음엔 추가 commit 도 양식에 맞게 작성해주시면 더 좋을 것 같네요!
고생 많으셨습니다 ㅎㅎ

2021-06-03 17:09 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        switch Int.random(in: 1...3) {
switch 없이 Hand 의 rawValue 를 이용해서 구현해볼 수도 있겠네요~
참고해주세요!

2021-06-03 17:09 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func settingUsersHand() -> Hand {
동사의 기본형으로 네이밍을 해주면 더 좋을 것 같습니다 : )
예약어 관련해서 찾아보면 네이밍에 더 도움이 될거에요 ㅎㅎ

2021-06-03 17:09 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return GameState.endGame
타입명을 생략할 수 있습니다. 참고 부탁해요~~!

2021-06-03 17:09 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        if  (userHand == .scissors && computerHand == .rock) ||
띄어쓰기가 2칸이 되어있습니다ㅠㅡㅜ

2021-06-03 17:09 UTC, merged