묵찌빠 게임 [Step1] Ehd, Geon
yagom-academy/ios-rock-paper-scissors pull request #67
Opened 2021-06-02 11:11 UTC by jgkim1008

안녕하세요 리뷰어님! @wonhee009 @yagom 
애드와 건 드디어 step1 PR합니다.

## 궁금한 점/ 고민한점
#### #1

readme에서 보시는 flow chart는 수정한 chart 입니다. 처음 flow chart를 작성할 때는 [ readLine()을 통해 받은 "String?" -> "String" ] 으로 타입캐스팅 해주는 1번 함수와, [ "String" -> "Int" ] 로 타입캐스팅 해주는 2번 함수를 나눠서 두개의 함수로 진행했었습니다. 하지만 그렇게 하다보니 과정 도중에 불필요한 전역변수가 하나 더 생겼고, 사실상 같은 기능을 수행하는 함수가 번복되었습니다. 그래서 두개의 함수를 하나로 묶어서 guard let , let  구문을 통해 한번에 표현했습니다. 해당부분에서 optional binding 할 때 guard let을 한번 쓰는 경우는 본적이 있지만 뒤에 let을 한번 더 붙여서 조건을 추가한 경험이 처음이어서 여쭤봅니다. 

1-1. 혹시 앞에서 guard가 각각의 let으로 분배되어 두번의 optional binding이 진행되는 건가요? 
1-2. optional binding을 이렇게 한번에 묶어서 진행하는 것이 나을지, guard let이나 if let을 두번 사용해서 따로 따로 (String? -> String, String -> Int) 타입캐스팅을 하는게 나을 까요?
1-3. 코딩을 하면서 처음 계획에서 벗어나는 함수들이 생기거나 기존의 함수들이 없어지는 일들이 발생할 때 flow chart도 함께 수정을 해야하나요?

#### #2 

return startGame() 과 그냥 startGame()을 재귀함수로 호출하는 것과의 차이가 무엇인지 궁금합니다. 메모리 관련해서 문제가 있다고 들어서요!
2-1. return startGame()이면 모듈이 실행되어 메모리에 적재되어 있는 함수와 변수들이 모두 사라지고 다시 시작되는걸로 이해하면 될까요??
2-2. startGame()은 기존에 모듈이 실행되어 있는와중에 새로운 모듈이 호출되는것이니 모듈이 2개가 실행되고 있다고 생각하면 되는걸까요??

#### #3 
저희 함수 중에 returnResult() 이라는 함수가 있습니다. 그렇게 명명한 이유는 게임의 시작을 관장하는 startGame()에서 returnResult라는 이 함수를 보고 상대방 개발자가 "이 함수에서 결과가 판명나는구나" 라는 생각을 할 수 있도록 하기 위해서 였습니다. 하지만 엄밀히 말하면 returnResult에서 결과를 판별하는 작업을 직접하는 것이 아니라 returnResult에서 소환하는 compareCard()에서 서로의 패를 비교하여 결과를 리턴하는 작업을 합니다. 때문에 관점에 따라 함수명이 적절치 않을 수 있다는 생각을 했습니다. 

그래서 returnResult 라는 함수 대신에 '내가 제시한 패에 따라 어떤 process가 진행될 것인지 나누는 의미의 processSeperator()" 와 같은 함수명이 나은지 궁금합니다. 이렇게되면 processSeperator()라는 캡슐화된 함수의 내부를 들여다볼 때 해당 기능에 대한 설득력은 얻을 수 있지만, 전체 게임을 관장하는 startGame()만 볼 때에는 동료 개발자가 "프로세스를 나눈다. 그래서 뭐?" 라는 의문을 가질 수 있을 것 같습니다. 

두가지의 관점 중에서 어떤 것이 낫다고 생각하시나요? 혹은 저희의 관점보다 더욱 진보적인 해결방안이 있을까요?

2021-06-02 13:02 UTC, wonhee009 requested changes
Ehd, Geon PR 축하해요!🎉
전체적으로 함수를 깔끔하게 나누려고 노력한 모습이 보였습니다!
그래서 코드 파악하는데도 수월했구요.
남겨주신 코멘트 #1, #3은 관련된 코드에 코멘트 달아놨으니 확인 부탁드릴게요🙏
#2는 Ehd, Geon이 잘 이해하고 계셔서 여기에 남깁니다.ㅎㅎ
step1 작성하시느라 수고하셨고 아래의 코멘트들 확인하시고 이해 안가는거나 궁금한 점 있다면 언제든 연락주세요!☺️

2021-06-02 14:27 UTC, yagom commented
근데 전 왜 매번 이 모둠에 태그되는거예요? ㅋㅋ

2021-06-03 04:45 UTC, jgkim1008 commented
> 근데 전 왜 매번 이 모둠에 태그되는거예요? ㅋㅋ

앗..죄송해요 야곰~제가 잘못 이해를 해서 태그를 했네요 ㅠㅜ

2021-06-03 12:49 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var userCard: Int = 0
저희가 처음에 생각했을 때는 userCard도 나름 직관적이라고 생각했는데 생각보다 아니었나봐요 ㅠㅠ 그래서 userCardToInt, intTypeUserCard 등의 후보를 통해 최종 intTypeUserCard 를 선정했는데 괜찮은 네이밍인지 모르겠네요.😅

2021-06-03 12:50 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    userCard = userInput()
전역변수를 선언하면 userCard 변수가 필요한 함수에서 접근하여 사용하기 편하기 떄문에 그랬던 것 같습니다. (좀 더 엄밀히 말하면 인자로 넣어주는 것보다 전역변수를 써서 값을 여러함수에서 사용하는 것이 더욱 편하다고 생각했습니다.) 혹시 이런 전역변수가 많이 쌓인다면 메모리의 공간을 점유하기 때문에 안좋은가요?

2021-06-03 12:50 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
아하 궁금했던 내용인데 훌륭한 설명 감사합니다!!

2021-06-03 12:52 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        end()
맞아요 ㅠㅠ 저희도 이부분에 대해서 처음에 고민을 했습니다. 원래 맨처음 플로우 차트에는 isEnd()라는 함수를 통해서 한번 0을 거르고 가는 방식을 생각했었는데 returnResult()의 case문에서 어차피 걸러지기 때문에 괜찮을 것 이라고 생각했어요… 그래서 저희가 다시 생각해본 방식은 

#1. 아래와 같이 함수 안에 0이 게임을 끝내는 숫자임을 명시하는 상수를 하나 정의한다. (함수명을 바꿨습니다. 아래에서 언급예정)
 #2.  저희가 처음에 구상한 방식대로 0을 입력하면 함수를 끝내는 함수를 통해 0을 거른다.

등이 있습니다. 우선은 시간이 많이 없어서 1번으로만 고쳐보았는데 라자냐의 생각이 궁금하네요 :)

```Swift
func processSeparator(userCard: Int) {
    let exitNumber = 0
    
    switch userCard {
    case exitNumber:
        print("게임종료")

    case 1, 2, 3:
        judgeResult(inputCard: userCard)
    default:
        print("잘못된 입력입니다. 다시 시도해주세요.")
        return startGame()
    }
}
```

2021-06-03 12:53 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        compareCard(inputCard: 3)
case1,2,3 을 묶어서 공통적인 값을 반환할수 있는것은 처음알았네요! 이부분은 몰랐던 부분이라 라쟈나의 의견에 동의해서 수정했습니다. 나머지 방법들은 2번 질문으로 대체될것 같습니다.

2021-06-03 12:56 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return startGame()
2가지 방법을 생각해봤어요!

첫번째 방법으로, 함수 이름을 바꾸는 방법을 생각했습니다.  함수명을 0~3까지 아닌 값은 필터링하고 0일 때는 게임을 종료, 1~3일 때는 결과를 반환, 나머지 값일 때는 게임을 재시작할 수 있는 프로세스를 나눠서  진행하도록 함수 이름을 바꾸는 processSeperator()라는 함수이름을 생각해보았습니다. 또한 기존의 compareNumber() 함수를 본래 역할에 더 충실한 judgeResult()로 변경했어요. 적절한 값을 입력한 경우 processSeperator를 거쳐 결과를 반환하도록이요! 

두번째 방법으로는, isEnd()라는 함수를 신설하고 startGame()에서 소환하여 기능을 분산하는 방법을 생각해봤어요. 아래와 같이 흐름제어문을 통해 첫번째 PR의  returnResult 함수 (1안의 processSeparator로 함수명을 변경하는 것과는 다른 2안입니다! 물론 2안을 채택할 경우에도 returnResult함수의 이름을 isValid() 등으로 바꿔줘야할 필요성은 있겠지만요. 하하^^… 말이 너무 길군요. 의사전달이 잘 될지 모르겠어요.)의 역할을 경감해주었습니다. 

```Swift
func isEnd() -> Bool {
    if userCard== 0 {
        print("게임 종료")
        return true
    }
    return false
}
```

이 것으로 라자냐가 남겨주신 마지막 코멘트에 대해서도 답을 할 수 있을 것 같습니다.

2021-06-03 12:57 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return
Q) end()에 return을 작성한 이유

저희가 수업시간에 작업을 끝낼 때 return 하고 공백을 남기면 가능하다고 들은 것 같아서 그랬어요… ^^; 확실친 않지만요. 그런데 지금 해보니 아무것도 안 넣으니 그냥 끝나네요 ㅎㅎ… 그래서 아예 end함수를 없애고 processSeperator() 에서 case 가 0일 때는 게임종료를 프린트하고 끝내는 것으로 수정했습니다. 저희가 잘 몰랐어요 하하…

Q) returnResult()도 end()와 동일하게 return type이 없는데 return을 작성한 이유
입력값을 다시 받기 위해 return startGame()을 하여 기존에 실행되고 있는 모듈을 종료시키고, 새로운 모듈을 불러오기 위해 return startGame()을 했습니다. return을 안붙이고 startGame()을 하면 기존에 실행되고 있던 모듈의 변수나, 함수들이 계속 메모리에 쌓일것이라고 생각했습니다.

2021-06-03 12:58 UTC, Brian2931 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerCard = generateComputerCard()
randomComputerCard라는 이름으로 네이밍 해봤어요~!

2021-06-03 16:09 UTC, jgkim1008 commented
@wonhee009  

리뷰 감사합니다!  리뷰 해주신 내용을 바탕으로 수정 진행하였습니다.

* 직관적인 네이밍으로 변경 ( userCard -> intTypeUserCard, computerNumber -> randomComputerNumber )
* case 문 변경
* returnResult() -> processSeparator()로 refactor하여 함수의 기능에 대한 명확성 확보
* 불필요한 end() 함수 제거 및 지역변수(exitNumber)로 0을 표현하여 직관적으로 표기
* compareCard -> judgeResult 로 reafactor하여 함수의 기능에 대한 명확성 확보

2021-06-04 02:23 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var userCard: Int = 0
아하! 저는 `userNumber` 정도로 생각했었는데요.
제 생각에는 `card`라는 단어가 명확하다고 생각이 안 들어서요!
이 부분은 취향이나 개인차가 있으니 제 리뷰가 정답은 아닙니다😂

2021-06-04 02:35 UTC, wonhee009 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    userCard = userInput()
전역 변수가 필요한 곳에서는 전역변수를 써야지요☺️
제가 전역변수를 사용한 이유를 물었던 의도는 잘못해서 물어본 것이 아니라 **어떤 이유때문에 전역 변수를 썼을까**였습니다!
전역 변수를 사용해야하는 이유가 있다면 전역 변수를 사용해야한다고 생각합니다!

이전 코드에서는 전역 변수로 선언된 `userCard`의 값은 사용자의 입력에 따라 계속 바뀌고 게임 1회가 끝나면 `userCard`의 값이 1/2/3으로 남아 있어서 이 부분이 다음 게임 턴에도 필요한가? 라는 생각이 들었어요!
그리고 이 부분이 전역 변수가 아니라 함수의 파라미터로 넘겨줘도 되겠다라는 생각이 들어서 Ehd, Geon의 의견이 궁금했습니다!

2021-06-04 03:29 UTC, wonhee009 commented
@Brian2931 @jgkim1008 애드, 건 코드 수정하느라 정말 수고 많았습니다!😃
남겨주신 코멘트 확인하면서 1가지 방법이 아니라 여러 방향을 생각해보는 애드와 건을 보면서 저도 반성을 많이 했습니다!

우선 남겨주신 코멘트에 대해서 저도 답변을 달아뒀는데 안 달은 코멘트들은 여기서 얘기해보고 싶어서요!
애드와 건은 함수명을 변경해서 함수가 하고 있는 역할을 좀 더 명확하게 보여주려고 노력한거 같아요!
명확한 네이밍을 하려고 노력한거 칭찬합니다!🎉
이 부분은 항상 생각하면서 코드를 짜셨으면 좋겠어요! (물론 저도 아직 너무 어렵습니다😢)

### 그렇다면 우리 함수의 역할과 기능에 대해서 한 번 생각해볼까요?
`userInfo()`에서는 사용자에게 입력 받은 **문자열**을 **Int**로 바꿔주고 있네요.
이 과정에서 사용자가 숫자를 입력했는지 확인하는 과정을 거치고 있지요.
그런데 우리가 확인해야하는 것은 **사용자가 0~3까지의 숫자를 입력했는지 확인**해야하죠.
현재 이 부분을 `processSeparator(intTypeUserCard: _)`가 하고 있네요!
그렇다면 이렇게 조건을 수정해볼 수 있지 않을까요?
```swift
guard let stringInput = readLine(),
          let intInput = Int(stringInput),
          (intInput >= 0 && intInput <= 3) else {
        print("잘못된 입력입니다. 다시 시도해주세요.")
        
        return userInput()
    }
```
이렇게 한다면 `userInfo()`에만 사용자의 입력을 확인하는 역할을 갖게 되겠죠?

`processSeparator(intTypeUserCard: _)`를 한 번 봐볼까요?
여기서는 사용자가 게임을 종료하는지, 게임을 진행하는지를 확인하고 있네요! (잘못된 입력은 위에서 다뤘으니 제외할게요!)
```swift
let exitCode = 0

func startGame() {
    let intTypeUserCard = userInput()
    if judgeExit(intTypeUserCard: intTypeUserCard) {
       ...
    } else {
        judgeResult(intTypeUserCard: intTypeUserCard)
    }
}

func judgeExit(intTypeUserCard: Int) -> Bool {
    return intTypeUserCard == exitCode
}
```
이렇게 한다면 게임 종료와 진행의 역할을 나눌 수 있지 않을까요? (물론 이것도 제가 임의로 짠 코드이니 정답은 아닙니다!)

이렇게 1개의 함수가 1개의 역할만 하도록 코드를 짜다보면 애드와 건이 저에게 해줬던 질문들이 많이 해결될거 같아요!
우선 이 부분들은 step2에서 개선해봤으면 좋겠습니다!

2021-06-04 03:29 UTC, merged