묵찌빠 게임 [Step 2] Tacocat, Jiwon
yagom-academy/ios-rock-paper-scissors pull request #68
Opened 2021-06-03 10:11 UTC by jyoon54

<h1>고민 되었던 점</h1>

연산 프로퍼티를 활용하여 현재 턴을 쥔 플레이어를 나타내는 방법을 고민해 봤습니다. 그래서 Player enum을 만들고 연산프로퍼티로 
플레이어 이름 (사용자, 컴퓨터) 를 나타내도록 하였습니다.
승패가 정해지지 않았을때, Unknown 케이스를 추가하여 이를 활용해 루프를 탈출 하였습니다.
가위 바위 보 한판 하는것을 처음에 함수로 만들려고 했는데, 0 입력시 프로그램 종료 부분이 까다로워 while 루프로 구현 했습니다.

2021-06-04 14:18 UTC, YebinKim requested changes
타코캣, 지원 안녕하세요~
굉장히 빠르게 Step2 PR을 날려주셔서 놀랐습니다 🤩
이번에도 역시 번갈아가며 커밋을 잘 날려주셨네요! 이번 스텝까지 잘 구현하시느라 고생 많으셨어요 😊👏

우선 질문주신 부분부터 답변 드릴게요.

---

### - unknown과 noOne가 쓰이는 상황은 다르지만 기능이 동일해서 noOne이라는 케이스를 추가 할 지, unknown을 다시 사용할지의 여부

현재 unknown이 쓰이는 상황은 가위바위보 게임에서 승패가 정해지기 전의 상황,
noOne이 쓰이는 상황은 게임을 종료했을 때의 상황으로 이해했는데요.

저는 두 상황에서의 currentPlayer는 동일하게 알 수 없는 상태(unknown)가 아닌가..? 라고 생각이 들었어요.
하지만, 타코캣과 지원이 생각하기에 두 상황에서 나타내고자 하는 플레이어의 상태가 다르다면 두 케이스를 나눠서 사용할 수 있다고 생각해요~

---

그리고 기능 명세서와 다른 동작이 보여서 확인 요청 드려요-!

- 묵찌빠 게임 중 0을 입력하지 않았음에도 게임이 종료됨
<img width="503" alt="스크린샷 2021-06-04 오후 11 42 36" src="https://user-images.githubusercontent.com/38066039/120819580-ae959a80-c58e-11eb-9194-ff630204a609.png">
<img width="503" alt="스크린샷 2021-06-04 오후 11 43 22" src="https://user-images.githubusercontent.com/38066039/120819590-b05f5e00-c58e-11eb-8aba-bb15a2172f35.png">


—

또한, 아래의 상세 리뷰 코멘트에도 말씀드렸지만 전체적으로 **반복문과 전역 변수의 사용은 줄이고, 함수를 사용**할 수 있도록 리팩토링 진행해보았으면 하구요.
README 문서도 작성해보면서 프로젝트를 문서화시켜보는 경험을 가져보았으면 해요 😊

enum의 사용이나 if, switch 와 같은 조건문의 사용은 잘 해주셔서 추가로 코멘트 드릴 부분은 없는 거 같습니다 ㅎㅎ
리팩토링과 동작 오류 수정만 한 번 잘 진행해보아요! 💪👀💪

2021-06-04 14:18 UTC, YebinKim commented on README.md
> +<img src=https://github.com/Ldoy/ios-rock-paper-scissors/blob/915167d58f195cb86c8b7b51971143be7cce45ae/묵찌빠.png>
플로우차트를 잘 넣어주셨군요! 😊
현재의 플로우차트에서 수정할 부분이 몇 가지 보여 코멘트 드립니다 ㅎㅎ

- 플로우차트는 시작 지점과 종료 지점을 명시해야 합니다.
- 전체적으로 모양이 복잡합니다. 아래->위 방향의 역방향 화살표의 사용을 지양하고 각 스텝의 화살표가 겹치지 않도록 배치해주세요.
- 입략: 0 <- '입력' 오타가 있네요
- 플로우차트에는 약속된 기호들이 몇 가지 있습니다. 참고해보시면 도움이 될 거 같아요 (https://www.smartdraw.com/flowchart/flowchart-symbols.htm)

2021-06-04 14:18 UTC, YebinKim commented on README.md
>  <img src=https://github.com/yagom-academy/ios-rock-paper-scissors/blob/e772d205d71bc4f4a2adf9e502cb32200932613d/가위바위보%20수정판.png>
README는 프로젝트를 이해할 수 있도록 작성하는 설명서와 같은 역할을 합니다.
README 문서를 잘 작성해두면 다른 사람이 프로젝트를 이해하기 쉽고, 
개발자 스스로도 프로젝트 구조를 정리하고 히스토리를 관리할 수 있어서 큰 도움이 돼요!

저에게 리뷰를 요청하고, 설명해주실 때 처럼 적절한 글과 함께 README 문서를 작성해주시면 좋을 거 같습니다 ☺️

2021-06-04 14:18 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +	var name: String {
연산프로퍼티를 사용하셨군요!!
지난 리뷰에서 드린 포인트를 바로 적용하시다니 훌륭합니다😆👏

2021-06-04 14:18 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +while mookZziPpaWinner == .unknown && currentPlayer != .noOne  {
이 부분 전역 while을 사용하지 않는 방식으로 다시 구현해보면 어떨까요?
전체적으로 두 개의 while문과 두 개의 전역변수를 중심으로 게임이 진행되고 있는데
전역 변수와 전역 반복문은 프로그램의 시작부터 끝까지 해당 변수를 유지하고 있기 때문에 메모리 효율에 좋지 않고
전역 반복문 역시 탈출하지 못 할 경우 프로그램이 멈춰버릴 수 있기 때문에 사용을 지양하는 편이 좋습니다.

그리고 지난 스텝에서는 while **반복문**을 통해 게임을 진행해보았으니 
이번 스텝에서는 **함수의 선언과 재귀**를 떠올려보며 리팩토링 진행해보았으면 합니다 😊

2021-06-04 14:44 UTC, YebinKim requested changes
ㅌㅅㅌ

2021-06-04 15:56 UTC, jyoon54 commented
질문 있습니다! 사용자의 승리로 게임이 끝났어야 하지만 정상적으로 동작하지 않음 <- 이부분이 이해가 잘 가지 않습니다 ㅠㅠ 
제 나름대로 컴퓨터 손모양도 출력해서 비교해가며 테스트 하고 있는데 아무리 봐도 묵찌빠 부분에서 오동작은 하지 않는것 같습니다.
한번 확인 해주실 수 있나요?

2021-06-04 16:09 UTC, YebinKim commented
네네!
저는 묵찌빠 게임이 사용자와 컴퓨터와 사용자가 같은 손을 낸 후, 선을 가진 사람이 한 번 더 같은 손을 내면 이기는 게임이라고 생각했는데요.
아래와 같이 게임이 진행되어야 한다고 생각했어요~

```swift
가위(1), 바위(2), 보(3)! <종료 : 0> : 2
이겼습니다!
[사용자 턴] 묵(1), 찌(2), 빠(3)!<종료 : 0> : 2    // 사용자가 턴을 쥔 상태, 사용자(2) : 컴퓨터(?)
컴퓨터의 턴입니다
[컴퓨터 턴] 묵(1), 찌(2), 빠(3)!<종료 : 0> : 2    // 사용자가 턴을 쥔 상태, 사용자(2) : 컴퓨터(2) --> 이 때 사용자가 
사용자의 턴입니다
[사용자 턴] 묵(1), 찌(2), 빠(3)!<종료 : 0> : 2    // 사용자가 턴을 쥔 상태, 사용자가 찌를 낸 상태 -> 게임 종료
```

추가적으로 현재 기능 명세서의 출력 예시는 아래와 같지만
> 실행 예

- 가위(1), 바위(2), 보(3)! <종료 : 0> : 1
- 이겼습니다!
- [사용자 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 6
- 잘못된 입력입니다. 다시 시도해주세요.
- [컴퓨터 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 3
- 컴퓨터의 턴입니다
- [컴퓨터 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 3
- 사용자의 턴입니다
- [사용자 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> : 3
- 사용자의 승리!

같은 입력에 대해 프로그램의 실행 모습을 아래와 같습니다.

<img width="503" alt="스크린샷 2021-06-05 오전 1 08 57" src="https://user-images.githubusercontent.com/38066039/120831545-9c215e00-c59a-11eb-8d63-c8e57201adcc.png">

2021-06-05 04:55 UTC, YebinKim commented
기능 명세서와 다른 동작과 관련해서는 묵찌빠 게임에 대해 서로의 이해가 달랐고, 이 부분 디코에서 얘기 나누면서
“***의 승리!” 출력 후 게임 종료 (이후 다시 게임 시작) <- 만 수정하는 것으로 결정되었어요-!
히스토리차 남겨둡니다 😊

2021-06-05 08:18 UTC, YebinKim reviewed
지원, 타코캣 안녕하세요~
리팩토링 진행하느라 고생 많으셨습니다-!!
while 문을 하나도 사용하지 않고 리팩토링을 진행한 점, 
함수의 반환값으로 함수를 사용한 점 박수 드려요! 😆👏

이번 스텝은 여기서 머지 진행하도록 하구요.
이후의 개선은 자유롭게 진행하시면 됩니다 ☺️

앞으로 개선할만한 부분의 포인트를 3가지로 정리해봤어요!
- Repository 안에서 사용하지 않는 파일 삭제
- 한 메서드는 하나의 기능만 수행할 수 있도록 작성 (라인별 코멘트에도 작성해두었어요)
- 의미 불명의 숫자(매직 넘버) 사용 지양 (라인별 코멘트에도 작성해두었어요)

그럼 묵찌빠 프로젝트는 여기서 마무리 할게요 😄
다음 프로젝트 진행도 화이팅입니다!!

2021-06-05 08:18 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +		case 1:
다른 사람들이 코드를 볼 때 이 부분에 남겨진 숫자가 무슨 의미인지 바로 파악할 수 있을까요? 🤔
코드 안에 이렇게 의미를 알 수 없는 숫자를 사용했을 때, 이러한 숫자를 매직넘버라고 하는데요.
매직넘버는 코드의 가독성을 떨어뜨리기 때문에 사용을 지양해주시는 편이 좋아요~
매직넘버를 사용하지 않기 위한 방법으로는 enum을 사용하거나 상수를 선언하는 방법 등이 있습니다!

2021-06-05 08:18 UTC, merged

2021-06-05 09:46 UTC, jyoon54 commented on RockPaperScissors/RockPaperScissors/main.swift
> +		case 1:
출력문에 설명이 되어있다 생각해서 방심했네요... 앞으론 조심하겠습니다!

2021-06-05 09:47 UTC, jyoon54 commented on RockPaperScissors/RockPaperScissors/main.swift
> +	func playMookZziPpa() {
저도 이부분이 가장 아쉬운데요, 기능설명서의 변경사항을 조금만 더 빨리 캐치했더라면 더 좋은 설계를 할 수 있었을 것 같습니다

2021-06-05 09:51 UTC, jyoon54 commented on RockPaperScissors/RockPaperScissors/main.swift
> +		if self == .unknown {
솔직히 guard문은 생각 못했습니다. unknown을 nil 대용으로 사용했던거같아요

2021-06-06 07:35 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +		if self == .unknown {
guard문이 Swift에서 처음 접하는 구문이다보니 코드를 처음 작성할 때는 떠올리기 힘든 구문인 거 같아요😂
앞으로 guard문을 생각할 때는 "만약 이 조건이 만족되지 않는다면, **구문 아래의 로직이 실행되지 않도록 방어한다**." 의 의미로 받아들여 주시면 활용에 도움이 될 거에요! 😊

2021-06-06 07:42 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +	func playMookZziPpa() {
프로그램의 요구사항은 끝없이 변경되고, 기능 개발 중에는 코드 퀄리티에 많은 신경을 기울이기 어렵기에 개발자는 늘 코드에 아쉬움을 느끼고 리팩토링을 진행하게 되는 거 같아요☺️
현재의 설계가 나쁜 것은 아닙니다! 충분히 프로젝트를 잘 마무리 해주셨고 이후의 프로젝트에서는 메서드의 활용에 좀 더 신경을 써보면 Swift의 문법을 이해하고 기능이 잘 분할된 설계를 하는데 도움이 될 거 같아 드린 말이에요 😊👏

2021-06-06 07:46 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +		case 1:
매직넘버는 저도 늘 리팩토링 하면서 수정하게 되는 부분이에요😅
코드를 작성하면서 신경쓸 수 있는 점들을 이렇게 하나둘씩 알게 되면, 코드 퀄리티를 높이기 위한 방법 또한 하나씩 깨닫고 적용할 수 있게 될 거에요!!
이후의 프로젝트도 힘내봅시다😆💪