묵찌빠 게임[Step 2] - Shapiro, Jamking
yagom-academy/ios-rock-paper-scissors pull request #69
Opened 2021-06-03 10:58 UTC by jaemuYeo

@SungPyo 
안녕하세요 날씨!! Step1의 아쉬움을 뒤로하고 Step2를 진행하고 PR보내요 ☺️
이번 리뷰도 잘 부탁드립니다!! 많은 지적 부탁해요 ㅎㅎ

## 고민한 점
1. Step1에 이어서 전역변수의 사용을 하지않기 위해 노력했습니다.
2. 기능 단위로 함수를 구현하기 위해 노력했습니다.
3. Step1의 코드를 최대한 해치지않기 위해 많은 생각을 했습니다.
---
## 조언받고 싶은 부분
- 열거형에서 rawValue로 값을 사용할때와 customStringConvertible로 값을 사용할때의 차이점이 궁금합니다.
- startStageOne, startStageTwo 두 개의 함수가 중복된 부분이 많아서 고민해 봤는데 더 깔끔하게 작성할 수 있을까요?
- 네이밍에 대한 지적도 부탁드립니다 🙏
- Step2 문제를 해결하기 위해 어쩔 수 없이 inputUserValue의 파라미터에 winner라는 매개변수 이름을 사용했는데 어울리지 않는것 같아요. 좋은 이름 또는 방법이 있을까요?

2021-06-03 14:47 UTC, SungPyo requested changes
우선 commit 전 충돌은 해결하고 올려주세요!
기존 가위바위 보 기능에서 이어지던 프로젝트라 그런지 리뷰 할 부분이 크지는 않지만
step1과 마찬가지로 부분부분 코멘트를 달아놓았으니 참고 부탁드립니다!

2021-06-03 14:47 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +func inputUserValue(mode: Mode, winner: Player) -> RockPaperScissors? {
에러처리에 대해서 고민해 보신적이 있으실까요?
 이 inpuUserValue에는 여러가지 기능이 있고, 에러가 발생할 확률이 가장 큰 함수입니다.
 어떤 에러가 발생할지 볼 수 있는 에러처리를 보고싶어요!

2021-06-03 14:48 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +func startStageOne() {
stageOne, StageTwo 라는 이름을 보고 어떤 로직이 들어있는 함수인지 알 수 있을까요? 알 수 없는 의미의 이름보다는 함수만 보고 어떤 로직을 실행하는지 표현하는게 더 좋을 것 같아요.

2021-06-03 14:48 UTC, SungPyo commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if checkIsDraw(thisGameResult: thisGameResult) {
checkIsDraw 와 printGameResult의 경우에는 불필요하게 함수를 나누었다는 느낌이 강한것 같아요. 무언가의 처리를 위해서가 아니라 단순히 나누기만 한 것 같은 느낌을 받습니다.
     쪼개는건 좋았지만 의미를 조금씩 모아보도록 해봐요 :)
     이미 thisGameResult에서 결과를 받았는데 해당 결과를 그대로 사용하는 방법은 없을까요?

2021-06-03 14:50 UTC, SungPyo commented
코드 전체적으로 느낀 부분은. 너무 많은 부분으로 함수를 나누지 않았나... 생각이 듭니다.
아직 배워가는 단계이니 자신만의 기준을 잡고 기능별로 함수를 나눠 작업해 보는걸 연습해 봅시다!

2021-06-04 08:48 UTC, jaemuYeo commented
안녕하세요 @SungPyo !!
Step2 리뷰 위주로 코드 수정후 재 PR요청드립니다!

## 수정한 부분
- stageOne, stageTwo 함수명 변경하였습니다.
- checkIsDraw 함수가 불필요하다 생각하여 제거하였습니다.
- 지적하신 부분에 에러 처리를 적용해보았습니다.

## 조언받고 싶은 부분
- 에러처리에서 0을 입력받았을때 프로그램이 종료가 되는 것을 에러처리를 통해 구현하였는데 특정 기능을 에러처리를 통해 처리하여도 괜찮을까요?
그리고 의도하신 에러처리가 이런 방법이였는지 궁금합니다!

## 해결하지 못한 부분
- 가위바위보, 묵찌빠 게임시작 함수들이 겹치는 부분이 많고, 몸집이 너무 커진것같아 아쉬움이 남습니다.

마지막 리뷰 잘 부탁드립니다 🙏

2021-06-07 03:54 UTC, SungPyo commented
안녕하세요 @jaemuYeo 
2차 PR에 대해서는 앞으로도 코드 부분에 하나씩 다 리뷰를 달아드리기 보다는 텍스트로 전체적인 부분을 말씀드릴게요.
(코드에 계속 리뷰를 달고 수정하다 보면 끝도 없기때문에...)

## 수정한 부분
- stageOne, stageTwo 함수명 변경하였습니다. 
ㄴ 우선 이 부분은 잘하셨어요! one two 보다는 더 명확한 함수명이 되었으니까요!

- checkIsDraw 함수가 불필요하다 생각하여 제거하였습니다. 
ㄴ 제거한것 까진 좋았으나, compare 함수 안에서 한번에 처리했으면 어땠을까.. 하는 아쉬움이 조금 남습니다. 컴퓨터의 핸드는 항상 랜덤값을 가져오는 것이기 때문에, 인자로 받지않고 함수로 분리 후 비교 함수 안에서 호출해서 사용해도 됐을법 해요. 이러한 부분은 다른 프로젝트를 진행하면서 계속 해봅시다!

- 지적하신 부분에 에러 처리를 적용해보았습니다. 
ㄴ 에러처리에 대한 함수 분리가 조금 미숙해 보이지만 그래도 현재는 이정도면 충분해 보입니다 :)

## 조언받고 싶은 부분
- 에러처리에서 0을 입력받았을때 프로그램이 종료가 되는 것을 에러처리를 통해 구현하였는데 특정 기능을 에러처리를 통해 처리하여도 괜찮을까요?
ㄴ 여러 사람마다 생각은 다르겠지만 저의 경우 0을 입력 받았을대 프로그램이 종료되는게 '특정 기능' 이라고 생각되진 않기때문에 에러처러를 통해서 구현되어도 문제가 없다 라고 생각됩니다.

- 그리고 의도하신 에러처리가 이런 방법이였는지 궁금합니다!
ㄴ 의도한 에러처리와 크게 다르지 않습니다. 함수 분리가 좀 덜 된게 아쉽긴 하지만 잘하셨어요!

## 해결하지 못한 부분
- 가위바위보, 묵찌빠 게임시작 함수들이 겹치는 부분이 많고, 몸집이 너무 커진것같아 아쉬움이 남습니다.
ㄴ 보기에 좋다면 몸집이 커지는것은 신경쓰지 않으셔도 됩니다. 겹치는 함수들은 함수를 어떻게 분리하여 같이 사용할 수 있을지 고민해 보는것이 좋구요! 현재 상황에서는 겹치는 함수들을 어떻게 줄일까 어떻게 최적화 시킬까 보다는 '동작의 이해 + 버그없는 실행' 이 더 중요하지 않을까 싶어요! 프로젝트를 진행하다 보면 이러한 부분들은 자연스레 해결될 것이라고 생각됩니다.

제 기준에서 아쉬운 부분도 많고 고쳐야 할 부분도 많다고 보여지지만, 다음 프로젝트도 있고, 앞으로 갈길도 많이 남았기 때문에 step2 리뷰는 여기까지 할게요!

충돌 해결해서 다시 푸시해 주시면 머지하겠습니다.

고생하셨어요!

2021-06-07 03:56 UTC, SungPyo approved these changes

2021-06-13 07:56 UTC, closed without merging