묵찌빠 게임 [Step2] hosinging, terry
yagom-academy/ios-rock-paper-scissors pull request #74
Opened 2021-06-04 06:45 UTC by Hosinging

@YebinKim 
비비 풀리퀘스트 올렸어요.
리뷰 잘 부탁드립니다.

- 호싱잉
    1. Enum안에 예를들면 가위바위보, 묵찌빠의 케이스가 있을 때 가위바위보에서 턴 결정 및 승자를 결정하는 것과  묵찌빠 값의 변화에 따라  턴 결정 및 승자 결정하는 것을 Computed Property를 선언해서 결정하게 하거나, 프로퍼티 옵저버를 통해 할 수 있지 않을까 고민을 해봤습니다. 이런 방식으로의 처리가 가능할지와 이런 방식으로 처리를 하게 된다면 발생할 수 있는 문제점들이 있을지...궁금합니다. 

        PR하는 현재는 curly brace가 2개가 넘어가는 것 같고, 태리의 코드가 좋아 그대로 진행을 해봤고, 진행해보고자 했던 부분들에 대해서는 PR후 따로 해볼 예정입니다. PR후 피드백받고나서 이런 부분에 대해서 말씀 주실 내용이 있으시다면 말씀 나눠보고 싶습니다.

    2. 현재 저희의 코드에서는 RockPaperScissors Enum을 활용해서 턴과 승자가 결정됐을 때 RockPaperScissors Enum을 활용해 묵찌빠의 숫자입력의 값을 변환해주어 묵찌빠에서 낸 숫자로 인식하게 만들었는데요. 이러한 방식과 각 각의 Enum을 따로 만들어서 사용하는 방법이 있을 것 같은데 이것은 단순한 선택인건지, 협업을 위해서는 따로 빼주는 것이 맞을지 고민을 해봤습니다.

- 테리
    1. 현재 Game이라는 구조체를 만들고 여기서만 쓰이는 enum이 세개 있는데요.

    Game 구조체 내부에서만 사용되기 때문에 내부로 넣어서 선언했는데 위치가 맞는지 궁금합니다.

    ---

    2. 함수 개선사항

    play함수 내부에

    ```swift
    guard isRockPaperScissorsOrRightInput(userInput: userInput) else {
        turn = .computer
        return
    }
    ```

    이 부분에서 묵찌빠중인데 잘못된 인풋(= -1)이 들어온경우 earlyExit을 하는 코드인데요.

    좀더 다른사람이 보기에 쉽게 읽히게 만들고 싶은데 쉽지가 않았습니다.

    혹시 더 나은 개선방법이 있을까요?

2021-06-04 17:38 UTC, YebinKim requested changes
호싱잉, 테리 안녕하세요~
Step2까지 진행하느라 고생 많으셨습니다!
struct 내에서 프로퍼티와 메서드를 사용하고, 특히 enum의 사용에 있어 고민을 많이 하셨음이 느껴졌어요 👀👍

우선 질문 주신 부분부터 답변 드릴게요~

---

### 1. enum 안에서 가위바위보 / 묵찌빠 게임의 승자를 결정하는 것이 가능할지

가능하다고 생각합니다!
말씀해주신 것 처럼 computed property를 사용하는 방법 또는 메서드를 사용하는 방법 등이 떠오르는데요.
enum 안에 프로퍼티 또는 메서드를 추가하면서 주의해야 할 점이라고 한다면.. 작성하는 프로퍼티와 메서드는 enum과 관련 없는 처리를 하지 않도록 신경써야 할 점 정도인 거 같아요 ㅎㅎ (캡슐화가 깨어지는 것을 주의해야 한다는 뜻이에요)

생각하시는 방향을 알려주시면 저도 구현을 위한 키워드를 좀 더 알려드릴 수 있도록 할게요 ㅎㅎ

호싱잉이 말씀해주신 방향대로 enum 케이스 안에서 가위바위보 / 묵찌빠 게임의 승자를 결정할 수 있게 되면 playRockPaperScissors 메서드와 playMukjjibba 메서드 또한 좀 더 가독성을 향상시켜볼 수 있으리라 기대됩니다 😄

### 2. 이 질문은 제가 이해를 잘 못해서 요약이 어렵네요..!

현재 enum으로 정의된 3가지는 과하지도 부족하지도 않다고 생각합니다! 👍
이 부분도 다시 코멘트 주시면 추가로 답변 드릴게요 ㅎㅎ

--- 

### 1. enum의 위치 관련 질문

해당 구조체 안에서만 사용하고자 한다면 현재와 같이 구조체 안에 선언하는 것이 좋은 구조로 보입니다~
가능하면 타입 안에서 사용할 타입, 메서드, 프로퍼티는 내부에 숨겨주는 편이 프로그램의 성능을 위해서도, 캡슐화를 위해서도 좋다고 생각해요!

테리가 고민하신 것 처럼 위치도 고민해볼 수 있고, 앞으로 접근제어를 배우면 선언하고자 하는 타입, 메서드, 프로퍼티의 공개 범위에 대해서도 생각해볼 수 있게 되실 거에요 😊

### 2. 함수 개선사항

잘못된 인풋이 들어왔을 때 earlyExit을 실행하는 코드의 가독성을 개선하는 방법을 질문해주셨는데요.
우선 해당 메서드의 문제점을 생각해보자면

1. 메서드의 이름을 봤을 때 무슨 역할을 하는 것인지 알기 어려워요.
2. isPlayingRockPaperScissors() 를 세 번 호출하고 있어요. (110 라인 메서드 내부에서 한 번, 114 라인 내부 메서드에서 한 번, 121 라인에서 한 번)

이렇게 두 가지 사항이 있을 거 같아요.
그래서 해당 사항들을 개선해보자면

1번 개선
해당 메서드의 역할은 현재 묵찌빠 게임을 진행할 수 있는 상태인지 확인하고자 하는 메서드로 보이기 때문에
isPlayingRockPaperScissors() 메서드와 네이밍을 비슷하게 가져가보는 방법이 있을 거 같아요.

2번 개선
현재 가위바위보를 진행 중인지를 체크하고 분기하는 코드가 많기 때문에
가위바위보 진행과 묵찌빠 진행을 크게 두 갈래로 나눠서 진행할 수 있도록 수정하는 방향을 생각해보면 개선에 도움이 될 거 같아요!

---

추가적으로 같은 입력 값에 대해 매번 결과가 다르게 나오는 동작이 있어 확인 요청드려요~

<img width="583" alt="스크린샷 2021-06-05 오전 2 26 01" src="https://user-images.githubusercontent.com/38066039/120841176-2622f400-c5a6-11eb-818a-a4e0a293b65c.png">

2021-06-04 17:38 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var turn = Turn.notDecided
변수를 선언하셨군요!
변수를 선언했을 때는 해당 변수를 다시 초기화하는 곳이 어디일지 함께 생각해보시면 좋아요.
현재는 게임을 재시작하는 동선이 있으니 재시작 시에는 반드시 초기값으로 초기화가 되어야겠죠?

2021-06-05 01:51 UTC, taelee42 commented on README.md
> +![image](https://user-images.githubusercontent.com/55867479/120573431-87d54800-c458-11eb-992c-c046cfaf83c9.png)
말씀해주신 부분을 수정했습니다!!
읽기 쉬운 문서가 되기 위해 중요한 부분인것 같아요.
찾아주셔서 감사합니다😁

2021-06-05 01:52 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum RockPaperScissors: Int {
감사합니다!!😃😁😊

2021-06-05 01:52 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +    enum RockPaperScissors: Int {
감사합니다!🙂🙏🏻

2021-06-05 01:59 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case notDecided = ""
rawValue로 턴을 초기화 하는 경우는 없고 단, 유저 턴과 컴퓨터 턴일 때 지정해준 rawValue를 출력하기 위해서 썼었는데, 실제 사용이 없기 때문에 제거하였습니다. 두 개의 case에는 rawValue가 있는데 한 개의 case에는 rawValue가 없는 이런 형태로 Enum을 선언해도 괜찮을지 궁금합니다.

2021-06-05 02:04 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case tie
보기 좋은 코드를 위해서 써주는 편이 좋은것 같습니다.
말씀해주신 enum이외에도 위에 RockPaperScissors enum도 rock만 1로 명시해놨었는데 그 밑에 case들도 숫자를 넣어줬습니다.
```swift
    enum RockPaperScissors: Int {
        case scissors = 1
        case rock = 2
        case paper = 3
    }

    enum ValueDifference: Int {
        case tie = 0
        case win = 1
        case lose = 2
    }
```
요렇게 바꿨습니다.😆

2021-06-05 02:19 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let wrongInputInMukjjibba = -1
네 말씀해주신대로 Game구조체 내의 프로퍼티와 함수 내의 지역 변수, 그리고 Game구조체의 인스턴스를 생성하는 변수에도 타입을 선언해줬습니다. 궁금한 점은 guard문에서 임시 상수에도 타입을 주는 경우와 그렇지 않은 경우, 그 외 타입을 선언하는 경우와 선언하지 않은 경우를 본 적이 있는데, 어느 경우에는 타입어노테이션을 반드시 적어야하고, 어느 경우에는 타입어노테이션을 생략가능한지 그런 기준이 궁금합니다.

2021-06-05 02:21 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return RockPaperScissors(rawValue: number) != nil || number == exitNumber
감사합니다!!😁😁

2021-06-05 02:21 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return RockPaperScissors(rawValue: number) != nil || number == exitNumber
감사합니다🙂🙏🏻

2021-06-05 02:22 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func printInputMessage() {
감사합니다🙂🙏🏻

2021-06-05 02:22 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func printInputMessage() {
감사합니다. 한 함수에 한기능을 담당하는게 정말 쉽지 않은 것 같아요 
계속 신경써보겠습니다.😁

2021-06-05 02:24 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func playRockPaperScissors(userChoice: RockPaperScissors ,computerChoice: RockPaperScissors) -> String {
mutating이 처음에 어색했는데 몇번 쓰다보니 익숙해졌어요!!
오타는 수정했습니다!😁

2021-06-05 02:41 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case 1:
매직 넘버를 네임드 튜플을 이용해서 해결할 수 있을거라고 생각해서 네임드 튜플로 해결하고자 하였습니다.🙂

2021-06-05 02:46 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +              let computerChoice = RockPaperScissors(rawValue: Int.random(in: 1...3))
caseIterable을 활용하여 randomElement메서드로 구현해봤습니다!!
매직넘버에 항상 유의해야겠어요😄

2021-06-05 02:54 UTC, Hosinging commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func playMukjjibba(userChoice: RockPaperScissors, computerChoice: RockPaperScissors) -> String {
네 감사합니다. 저희도 전달인자 레이블의 사용에 대해 고민해 봤었던 부분이 있었는데요. 
전달 인자 레이블을 사용하지 않을 경우 함수 내에 작성한 파라미터 네임이 함수 호출시 전달 인자 레이블로 사용된다는 점에서 해당 부분을 생략하고 작성을 해봤습니다.(사실...전달 인자 레이블 네이밍이...🤣)
위에 작성한 관점으로 봤을 때 전달 인자 레이블을 사용하는 경우와 사용하지 않는 경우에 대한 기준이 궁금합니다.

2021-06-05 03:13 UTC, taelee42 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var turn = Turn.notDecided
이 변수의 초기화는 playRockPaperScissors나 playMukjjibba의 함수가 종료될때 각각 초기화해요.
Turn.notDecided라는 값이 turn에 저장되어 있으면 묵찌빠를 실행하지 않고 가위바위보를 실행하게 됩니다.
그래서 start()에서 초기화를 해주면 문제가 생길 수 있는데요. 제 생각에 start라는 메서드명이 처음 한번만 실행되는 이름처럼 느껴져서 오해를 불러일으킨것 같습니다. 함수구조를 바꿔서 좀더 읽히기 쉬운 코드를 작성해보려고 하는데 좀더 고민해보겠습니다.😊

2021-06-05 03:16 UTC, taelee42 commented
@YebinKim 
비비 리뷰 너무 감사드립니다!!
비비 덕분에 읽기 쉬운코드에 대해서 좀더 깨달은것 같아요.
읽기 쉬운 코드를 작성해야지라고 생각은 했지만 이번 리뷰를 겪으니
코드를 작성하면서 이게 남이 봤을때 잘 이해될까를 계속 떠올리게 되더라고요.
감사합니다!!😁

---
![](https://user-images.githubusercontent.com/38066039/120841176-2622f400-c5a6-11eb-818a-a4e0a293b65c.png)
그리고 요 부분은 컴퓨터의 패가 랜덤으로 나오기 때문에 
묵찌빠의 결과가 계속 달라질 수 있어요!!
이상한 입력(여기서는 6)이외에는 전부 랜덤한 결과가 나오는게 맞는거 같습니다.
어떻게 생각하시나요?

2021-06-05 05:41 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case notDecided = ""
오호 네네~ 실제 사용이 없다는 것을 보여주기 위해 제거하셨군요!

두 개의 case에는 rawValue가 있는데 한 개의 case에는 rawValue가 없는 이런 형태로 Enum을 선언하는 것은 약속된 규칙이 있는 경우 컴파일러가 자동으로 rawValue를 할당하거나, 각 case에 어떤 rawValue를 할당해야 할 지 알 수 없는 경우는 컴파일러 에러를 발생시키기 때문에 불가능해요.

Int형의 rawValue는 약속된 규칙이 있기 때문에
RockPaperScissors enum과 ValueDifference enum은 하나의 case에만 값을 전달하거나, 아예 값을 전달하지 않아도 0부터 순서대로 rawValue가 할당되었겠지만,

String형의 약속된 규칙이 없기 때문에
Turn은 모든 case에 값을 전달해야만 했을 거에요.

enum의 rawValue는 한 enum 내에서 고유한 값을 가지기 때문에 notDecided와 같이 실제 사용이 없는 케이스가 추가되면 "" rawValue를 지정해줄 수는 없을 거 같아 보이는데요.
이런 경우는 rawValue 대신 다른 구현 방법을 생각해보면 어떨까요? 🤔
enum 안에는 Associated Value, computed property, method 등 다양한 구현이 들어갈 수 있으니 구현하고자 하는 방향을 생각하며 더 적절한 방법을 선택해주면 좋을 거 같아요~

2021-06-05 05:47 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let wrongInputInMukjjibba = -1
타입어노테이션 추가 확인했어요! 👍

타입어노테이션을 추가할 기준과 그렇지 않은 기준은
컴파일러에서 타입추정을 하는지 / 안 하는지,
다른 사람이 봤을 때 타입이 헷갈릴 수 있는지 / 아닌지
로 생각해볼 수 있는데요.

컴파일러에서 어떤 경우에 타입추정을 하고 또 안 하기도 하는지는 앞으로 Swift를 배우면서 더 알게되실 거에요!
그리고 팀 규칙을 통해 어떤 경우에 타입어노테이션을 추가할지를 정하는 경우도 있습니다.

지금은 최대한 타입어노테이션을 추가하는 습관을 가지고 가는 것만으로도 충분할 거 같아요~ 😊

2021-06-05 05:52 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func playMukjjibba(userChoice: RockPaperScissors, computerChoice: RockPaperScissors) -> String {
네네~!
이전 스텝에서 전달인자 레이블을 잘 활용한 메서드가 있어 호싱잉과 테리 모두 메서드를 잘 이해하고 계신 거 같다고 생각했어요👍

전달인자 레이블을 사용하는 경우는 개발자의 코딩 습관에 따라 달라지겠지만
메서드를 사용할 때 어떤 타입의 값을 전달해야 하는지를 더 명확하게 보여주거나,
메서드 안에서 좀 더 짧은 이름으로 매개변수를 사용하고자 할 때 사용할 수 있어요 😄

2021-06-05 05:57 UTC, YongHoonJJo commented
서로의 패가 뭔질 보여주면 조금 더 명확했을텐데, 실행 예시에는 그런 부분이 없는것이 조큼 아쉬운 것 같아요..!!

2021-06-05 05:59 UTC, YebinKim commented on RockPaperScissors/RockPaperScissors/main.swift
> +        case notDecided = ""
오호 네네~ 실제 사용이 없다는 것을 보여주기 위해 제거하셨군요!

두 개의 case에는 rawValue가 있는데 한 개의 case에는 rawValue가 없는 이런 형태로 Enum을 선언하는 것은 약속된 규칙이 있는 경우 컴파일러가 자동으로 rawValue를 할당하거나, 각 case에 어떤 rawValue를 할당해야 할 지 알 수 없는 경우는 컴파일러 에러를 발생시키기 때문에 불가능해요.

Int형의 rawValue는 약속된 규칙으로 0부터 순서대로 값을 가지거나, 명시된 값을 기준으로 순서대로 값을 가지도록 설계되어 있고
String형의 rawValue는 약속된 규칙으로 해당 case의 이름을 가지도록 설계되어 있어요.

현재 변경된 코드에 따르면 notDecided case는 rawValue로 "notDecided"를 가질 것으로 보이는데요.
말씀하신 구현 방향과 같이 유저 턴과 컴퓨터 턴일 때만 값을 지정해주고자 하는 경우는 rawValue 대신 다른 구현 방법을 생각해보면 어떨까요? 🤔
enum 안에는 Associated Value, computed property, method 등 다양한 구현이 들어갈 수 있으니 구현하고자 하는 방향을 생각하며 더 적절한 방법을 선택해주면 좋을 거 같아요~

2021-06-05 06:11 UTC, YebinKim commented
리뷰 반영 확인했어요!
가위바위보 프로젝트와 묵찌빠 프로젝트를 진행하면서 
테리와 호싱잉이 프로젝트에 대해 얼마나 고민해서 코드를 작성하시는지 느껴져서 저도 배울 점이 많았고 👍
질문에 대한 답변을 쏙쏙 흡수해주셔서 감사했습니다 😁

저는 기능명세서를 보고 묵찌빠 게임에서 컴퓨터의 턴일 경우 컴퓨터의 패를 랜덤으로 생성하는 것이 아닌 직접 입력하는 것이라고 생각했었는데요.
테리의 설명대로라면 현재처럼 컴퓨터는 항상 랜덤패를 만들고 같은 입력에 대해서도 랜덤하게 승패를 결정하는게 맞는 거 같아요~
호싱잉의 설명처럼 서로의 패가 뭔지 보여주는 게 있었으면 좀 더 명확했을 거라는 생각이 듭니다!

Step2는 이대로 머지 진행하겠습니다!
추가로 코멘트 드린 부분은 앞으로 프로젝트를 진행하며 생각해보면 좋을 거 같아요 ☺️🙌
묵찌빠 게임 프로젝트 정말 고생 많으셨습니다-!

2021-06-05 06:11 UTC, merged