[STEP2] 수박, jint
yagom-academy/ios-rock-paper-scissors pull request #75
Opened 2021-06-04 06:47 UTC by filmcanister

@leejun6694 

1. 프로토콜과 익스텐션을 활용하여 각 클래스의 setUserHand를 추상화하고, 다시 묵찌빠와 가위바위보 클래스에서 이것을 상속받아 사용하고 싶은데 서로 다른 이넘을 사용하여 쉽지 않은데 좋은 방법이 있을까요?
2. GameState에서 drawGame과 endGame에는 rawValue 할당되어 있지 않은데 이런 것도 괜찮을까요?
3. 승패를 결정하는 논리들을 더 쉽게 구현할 수 있는 방법이 있을까요?

더러운코드 보시느라 수고가 많습니다. 밤늦게 고생치 마시고 아무때나 리뷰해 주시면 잘 받아보겠습니다. 감사합니다.

2021-06-05 15:51 UTC, leejun6694 requested changes
중복되는 코드들을 어떻게 정리할 수 있을지 고민해보면 프로젝트를 마무리할 수 있을 것 같습니다 👍 
코멘트 중 잘 이해가되지 않는 부분이 있다면, 언제든 말씀주세요 : )

2021-06-05 15:51 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
>          switch Int.random(in: 1...3) {
왜 숫자를 1 부터 3 까지 랜덤으로 뽑는지 현재 로직에선 좀 낯설다라는 느낌이 드네요.
raw 한 숫자가 아닌, 의미를 넣어주면 더 좋을 것 같습니다ㅎㅎ

2021-06-05 15:51 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        var outcome: GameState
굳이 outcome 변수를 만들지 않아도 될 것 같습니다~~!

2021-06-05 15:51 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                print("\(whosTurn.rawValue)의 승리입니다")
해당 로직만 본다면, 게임이 비겼는데 누군가의 승리가 되어버립니다.
매끄럽게 이해할 수 있도록 수정이 필요해보입니다...!

2021-06-05 15:51 UTC, leejun6694 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let outcome = MukChiBba(prevWinner: winner).startGame()
가위바위보 ~ 묵찌빠 까지 게임이 어떻게 진행되는지 한눈에 이해할 수 있었습니다 👍 
다만, `outcome` 이라는 변수가 여기저기서 쓰이고 있는데, 상황에 맞게 좀 더 명확한 네이밍을 정하면 좋을 것 같네요 ㅎㅎ

2021-06-09 02:22 UTC, filmcanister commented on RockPaperScissors/RockPaperScissors/main.swift
> +                print("\(whosTurn.rawValue)의 승리입니다")
맞네요.. 이부분부터 약간 멘붕느낌이라 좀 갈아엎을 필요가 있을것같습니다 ㅠㅠ

2021-06-13 07:56 UTC, closed without merging