묵찌빠 게임 [Step 1] 고사리, 신나
yagom-academy/ios-rock-paper-scissors pull request #93
Opened 2021-10-13 14:04 UTC by gogosilver

@ryan-son
안녕하세요, 라이언. 신나와 고사리입니다.
Step 1의  PR을 요청합니다.

아는 것이 적어 저희가 보지 못하는 부분이 많을 텐데, 많이 지적해주시면 감사드리겠습니다!

---

### 고민한 지점
1. ``do-catch를 게임 실행 함수 안에 적는다`` 와 ``do-catch에 함수를 호출한다.`` 각각의 특징은 무엇인지에 대해 고민하였습니다.\
-> 생각 1: do-catch를 외부에 적을 경우, 이후 추가되는 함수의 오류를 처리할 수 있기 때문에 오류처리의 확장성이 좋아진다.
2. ``unknown 케이스를 정의하여 매칭되지 않는 상황`` 에 대해 ``swift enum 문법 중 rawValue를 사용한 enum 인스턴스 생성을 통해 매칭되지 않는 상황을 옵셔널로 처리`` 해보고 싶은데 알맞은 접근법인지 궁금합니다.
```swift
enum RockPaperScissorsJudgement {
    case win
    case loose
    case draw
    case unknown
    
    mutating func matchResult(with number: Int) {
        switch number {
        case -2, 1:
            self = .win
        case 2, -1:
            self = .loose
        case 0:
            self = .draw
        default:
            self = .unknown
        }
    }
}
```
3. ``깔끔한 커밋을 위하여 오류처리를 한 번에 진행하는 방법`` 과 ``에러를 담는 enum을 처음부터 작성하는 방법`` 중 저희는 커밋 로그 작성에 집중하고자 전자를 선택하였습니다. 후자를 선택하면서 커밋 로그를 깨끗하게 남기는 방법이 있을지 고민하였습니다.
4. 각 커밋의 순간에 존재하였던 이슈와 처리방법은 커밋 메세지의 바디에 작성하여 이후 파악이 용이하도록 처리하였습니다.

### 조언을 얻고싶은 내용
* 메서드는 '인스턴스 self 값을 변경'하거나 '변환된 결과를 반환'하거나 를 기준으로 mutating과 non mutating method의 네이밍을 적용받는다고 생각하였습니다.\
반면 function은 인스턴스를 바꾸는 역할을 하지 않지만 처리된 결과를 반환한다는 측면에서 non mutating method의 네이밍을 차용할 수 있다고 생각하는데 (과거 분사나 현재 분사를 붙이는 네이밍 방법) 가이드라인을 올바르게 해석한 것일까요?
* API 가이드라인 문서를 참고하여 네이밍을 진행하였습니다. 해당 문서의 요구와 일치하지 않는 네이밍이 있는지 궁금합니다.

2021-10-14 00:13 UTC, ryan-son requested changes
고사리, 신나, 고생 많으셨습니다! 👏 고민하신 흔적이 많이 느껴지는 코드였어요. 😊

저는 수행하신 작업들을 보면서 아래와 같은 부분들이 좋다고 생각했어요.
1. 커밋의 단위가 적당하게 작은 크기로 나누시고  제목과 변경사항이 일치하여 추후에 문제가 생겨도 원하는 시점으로 돌아갈 수 있다고 판단되었어요.
2. 커밋을 번갈아가면서 하셔서 두 분 모두 작성하신 내용을 잘 이해하고 있으실거라는 인상을 받았어요.
3. 커밋 로그 형식, 코딩 컨벤션, API Design Guidelines에 따른 명명 방식을 지키려고 했다는 것이 느껴졌어요.

## 질문에 대한 답변
먼저, 제가 제시하는 방안이 정답이 아님을 알아두세요. 의견을 나누다 보면 제가 말씀드리는 것보다 더 좋은 방안을 찾아내실 수 있을겁니다. 제가 피드백 드린 내용에 대해 무조건적인 수용은 지양해주시고, 모든 내용에 대해 의심을 가지고 판단해주세요.

### 고민한 지점
> 1. ``do-catch를 게임 실행 함수 안에 적는다`` 와 ``do-catch에 함수를 호출한다.`` 각각의 특징은 무엇인지에 대해 고민하였습니다.\
> -> 생각 1: do-catch를 외부에 적을 경우, 이후 추가되는 함수의 오류를 처리할 수 있기 때문에 오류처리의 확장성이 좋아진다.

함수 안에 작성할 경우 특정한 함수에서 특정한 문제가 발생했을 때 즉시 적절한 조치를 취해줄 수 있다는 장점이 있고, 반대의 경우 현재까지 호출되었던 함수에서 발생한 에러를 모두 다룰 수 있으니 에러 처리 관련 코드가 한 군데 작성할 수 있다는 장점이 있겠네요.

정답은 없지만 저는 에러가 발생한 함수에서 바로 에러를 처리하는 것을 선호해요. 에러를 세분화하지 않은 상태에서도 발생한 위치를 특정하기 쉽고, 한 번 작성하면 최종적으로 사용되는 함수를 호출할 때 더 이상 `do-catch` 구문을 작성하지 않아도 되니 scope를 나누는 것에 대한 고민을 하지 않아 코드가 더 간결해지기도 하고요.

> 2. `unknown` 케이스를 정의하여 매칭되지 않는 상황에 대해 `swift enum 문법 중 rawValue를 사용한 enum 인스턴스 생성을 통해 매칭되지 않는 상황을 옵셔널로 처리` 해보고 싶은데 알맞은 접근법인지 궁금합니다.

`matchResult(with:)`의 결과가 `RockPaperScissorsJudgement.unknown`이면 아래와 같이 처리하고 싶다는 말씀이신가요?

```swift
enum RockPaperScissorsJudgement: Int? {
    case win
    case loose
    case draw
    case unknown = nil
}
```

아쉽게도 [`RawRepresentable` 프로토콜](https://developer.apple.com/documentation/swift/rawrepresentable/)을 채택하고 있는 열거형 타입은 `rawValue` 타입으로 옵셔널을 가지지 못합니다. 대신에 이 건 관련하여 개별 코멘트를 남겨두었으니 확인해보시고, 모자다라고 느끼시면 말씀해주세요.

> 3. ``깔끔한 커밋을 위하여 오류처리를 한 번에 진행하는 방법`` 과 ``에러를 담는 enum을 처음부터 작성하는 방법`` 중 저희는 커밋 로그 작성에 집중하고자 전자를 선택하였습니다. 후자를 선택하면서 커밋 로그를 깨끗하게 남기는 방법이 있을지 고민하였습니다.

두 가지 경우가 어떤 것인지 잘 이해하지 못했어요. 전자는 `do-catch` 처리를 최상위 함수에서 수행했다는 것이고, 후자는 에러를 담는 열거형 타입을 작성하는 것에 대한 이야기인가요?

아시겠지만 에러와 관련된 열거형은 에러가 추가될 때 타입에 추가해주시면 됩니다. 한 번에 에러 타입을 완성해야 깨끗한 커밋이 되는 것이 아니기 때문에 이후에 추가하는 것을 나쁘게 생각하지 않으셔도 됩니다. 그러기 위한 소스 컨트롤이기도 하고요.

### 조언을 얻고 싶은 내용
> 메서드는 '인스턴스 self 값을 변경'하거나 '변환된 결과를 반환'하거나 를 기준으로 mutating과 non mutating method의 네이밍을 적용받는다고 생각하였습니다.\
> 반면 function은 인스턴스를 바꾸는 역할을 하지 않지만 처리된 결과를 반환한다는 측면에서 non mutating method의 네이밍을 차용할 수 있다고 생각하는데 (과거 분사나 현재 분사를 붙이는 네이밍 방법) 가이드라인을 올바르게 해석한 것일까요?

- 함수나 메서드는 인스턴스의 self를 변경하는 행위나 변환된 결과를 반환하는 것과 관계 없이 모두 크게 보면 대상에게 어떠한 행위를 하도록 만드는 것입니다 (객체지향 프로그래밍 관점에서 대상에게 메시지를 보내는 행위). 그래서 소수의 예외를 제외하고 동사 (+ 명사)형으로 이름을 짓는 것입니다. 예를 들어, 작성하신 함수를 살펴보시면 `startRockPaperScissorsGame() (가위바위보 게임을 시작해)`과 같이 명령형 (imperative)으로 작명되어 있습니다. 따라서 앞으로도 거의 대부분의 상황에서는 이와 같이 이름을 지으시면 되겠습니다.
- 현재진행 또는 과거분사형으로 이름을 짓는 경우는 side-effect가 없이 특정 인스턴스를 변경하고 결과값을 반환받는 경우에 주로 사용됩니다. 따라서 목적 자체가 side-effect가 없이 변환된 결과물을 받아보는 것으로 목적이 달라 이름을 특이하게 짓는다고 보시면 되겠습니다. 따라서 함수나 메서드의 기능을 살펴보시고 어떤 해석이 더 자연스러운지에 따라 결정하시면 되겠습니다.
- 이 내용에 대해 동료들도 궁금함을 가지고 있을겁니다. 정답이 아닌 제 의견을 제시한 것이니 동료들과 자유롭게 토의하셔서 나름의 기준을 만드시면 더 좋을 것 같네요.  

```swift
var numbers: [Int] = [3, 1, 2]

let sorted: [Int] = numbers.sorted() // 정렬된 numbers -> numbers == [3, 1, 2] / sorted == [1, 2, 3]
numbers.sort() // numbers야, 정렬해. ->  numbers == [1, 2, 3] / 반환값 없음
```

궁금하신 점 있으시면 언제든지 말씀해주세요! 화이팅! 💪 😋

2021-10-14 06:19 UTC, smart8612 commented on README.md
> +* [Step-1 Flow Chart](https://user-images.githubusercontent.com/25794814/136899729-bc3cb8fc-4c7d-4cb5-aa8e-fa23ad8b5d08.jpeg)
순서도를 동해 문제를 파악하는 것이 정말 중요하다는 점을 배울 수 있었어요 😃
동료와 같은 이해를 공유하고 있는지 빠르게 확인할 수 있어서 의사소통에 있어서 장점도 느낄 수 있었어요!

2021-10-14 06:32 UTC, smart8612 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let possibleInputRange = 0...3
* `possible`은 **가능한** 이라는 의미의 형용사 입니다.
* `valid`는 (논리적으로) **타당한**, (컴퓨터 시스템에 쓰기에) **유효한**  이라는 의미의 형용사 입니다.
* 상수 `possibleInputRange` 의 의도는 사용자가 입력할 수 있는 유효 숫자 범위를 의미합니다.
* 유효한 입력 범위를 지정한다는 측면에서 `possible` 을 사용하면 어떤 측면에서 가능한지가 모호할 수 있다도 생각합니다.
* Swift API 가이드라인의 Fundamental 에서 강조하는 `명확성(Clarity)`을 높여주는 방법으로 `valid` 이름을 사용하면 유효한 범위라는 의미로 해석되어서 가독성이 향상되었다고 생각합니다!

2021-10-14 07:06 UTC, smart8612 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rockPaperScissorsRange = 1...3
* 이번 프로젝트의 룰을 세움에 있어서 **Type annotation 기준** 이 누락되었음을 파악할 수 있었습니다.
* 다음 commit 에서 type annotation 부분에 대한 규칙 세워서 반영하겠습니다.
* type annotation 문제에 대한 저의 이해를 적어보았습니다🤔
___
* Swift는 Type Safety한 언어이기 때문에 개발자가 작업하는 코드의 type을 명확성을 높여서 컴파일 타임에서 잘못된 type 끼리 계산되는 문제를 예방할 수 있습니다.
* Swift 컴파일러에서 제공해주는 Type Inference 기능을 통해 변수나 상수에 할당되는 값의 Type이 명확한 경우 type annotation을 명시하는 것을 생략할 수 있습니다. [Type Safety and Type Inference](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID322)
* possibleInputRange와 rockPaperScissorsRange는 닫힌 구간을 의미하는 범위 연산자 `...` 을 사용하여 선언되었으며 [ClosedRange](https://developer.apple.com/documentation/swift/closedrange) 타입을 갖게됩니다.

* **장점** : Integer 혹은 String 리터럴 값과 같이 값의 타입이 명확한 경우 코딩하는 양이 줄어듭니다. 
* **단점** : 컴파일러의 타입 추론으로 인해 컴파일 타임이 길어질 수 있으며 복잡한 사용자 정의 타입을 사용할 경우 잘못된 타입 추론이 발생될 수 있습니다.

2021-10-14 07:45 UTC, smart8612 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var isGameRunning = true
* 게임이 진행되는 도중에 `게임이 실행 중인가?` 네이밍이 혼동될 수 있음에 매우 공감합니다!
* 첨부해주신 불리언 변수 명명 방식을 차용하여 `게임이 실행되어야 하는가?` 의미의 `shouldRunGame` 이라는 네이밍을 생각해보았습니다.

2021-10-14 11:11 UTC, smart8612 commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
* rawValue 를 사용하는 것이 코드를 읽을때 어색하게 느껴질 수 있다는 생각을 했어요.
* 코드 개선 방안으로 `CustomStringConvertible` 채택하여 진행해보도록 하겠습니다.

2021-10-14 11:33 UTC, FIIIIN commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case dismissedError
```swift
enum RockPaperScissorsGameError: Error {
        case invalidInput
}
```
작성하였던 dismissedError의 경우, 사용자의 입력이 유효하지 않을 때 던져졌기 때문에, 말씀하신 것처럼 더 명확한 의미를 부여하여 ``invalidInput``으로 리팩토링 진행하겠습니다.

2021-10-14 16:04 UTC, smart8612 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func pullComputersHandPose(in range: ClosedRange<Int> = rockPaperScissorsRange) -> Int {
* `HandPose` naming을 사용하기 이전에 `pair`와 `choice`를 혼용하여 사용했습니다.
* 가위 바위 보 손동작의 의미를 강조하기 위해 `HandPose`를 사용하였습니다.
* 손동작에는 가위바위보 외에도 여러 가지가 존재할 수 있기에 명확하지 못한 측면이 있을 수 있다는 생각을 하게되었습니다.
* 말씀해주신 사항을 반영하여 네이밍을 수정하겠습니다!

2021-10-15 03:00 UTC, FIIIIN commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
타입 메서드와 전역함수를 두 가지 케이스로 나누어서 말씀드리겠습니다.
1. 타입 메서드: 함수 matchResult 가 타입인 RockPaperScissorsJudgement 를 통해서 호출될 수 있다.
let gameResult = RockPaperScissorsJudgement.matchResult(with: Comparison)

이 경우 matchResult가 해당 타입의 인스턴스를 생성해서 반환하는 과정을 코드를 사용하는 관점에서 보여주기 위해 타입을 통해 matchResult 를 호출하는 방법을 생각해보게 되었습니다.

2. 전역함수: 전역함수의 호출부는 아래와 같습니다.
let gameResult = matchResult(with: Comparison)

전역함수라도 동일한 결과를 발생시킨다면, matchResult의 리팩토링으로 코드의 전달력을 높이는 게 좋다는 의견이 있었습니다.

저 두 가지 방법 중 한 가지를 채택함에 있어서 라이언의 생각을 들어보고 싶습니다.

2021-10-15 06:14 UTC, smart8612 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RockPaperScissorsJudgement {
matchResult 를 전역함수로 설정한 후 matchJudgement로 이름을 수정해볼께요!

2021-10-15 23:55 UTC, ryan-son approved these changes
신나, 고사리, 코멘트 드린 내용에 대해 학습하신 내용을 공유해주셔서 정말 깊이 고민해보셨다는 인상을 받았어요. 고생 많으셨습니다! 👏
Step 1은 잘 수행해주셨으니 이 수준에서 머지하겠습니다.
이번에 피드백 드린 내용들은 Step 2에서 반영해보시면 되겠습니다!

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
말씀 드린 `CustomStringConvertible`을 사용해보셨네요! `rawValue`를 설정하시면 작성하신 형태로 사용하실 수 있고, 아래와 같은 형태로 사용하기도 합니다! extension을 사용한 이유는 프로토콜을 준수하기 위한 구현부를 명확히 나누어 가독성을 높이기 위함입니다 ([참고 링크](https://github.com/raywenderlich/swift-style-guide#protocol-conformance)).

```suggestion
enum Script {
    case menu
    case win
    case lose
    case draw
    case gameEnd
    case dismissedError
    case choiceOutOfRangeError
}

extension Script: CustomStringConvertible {
    var description: String {
        switch self {
        case .menu:
            return "가위(1), 바위(2), 보(3)! <종료 : 0> : "
        case .win:
            return "이겼습니다!"
        case .lose:
            return "졌습니다!"
        case .draw:
            return "비겼습니다!"
        case .gameEnd:
            return "게임 종료"
        case .dismissedError:
            return "잘못된 입력입니다. 다시 시도해주세요."
        case .choiceOutOfRangeError:
            return "가위바위보와 매칭될 수 있는 유효값이 아닙니다."
        }
    }
}
```

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
단순히 에러를 출력하는 동작만 수행한다면 아래와 같이 작성할 수도 있을거예요. `RockPaperScissorsError` 타입에도 `CustomStringConvertible` 프로토콜을 이용하여 에러 문구를 지정해주시면 발생한 에러에 따라 다양한 에러 문구를 보여줄 수 있겠죠?

```suggestion
        do {
            try startRockPaperScissorsGame()
        } catch {
            print(error)
        }
    }
```

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +func initUserAndComputerChoice(by userInput: Int) throws -> (user: RockPaperScissors, computer: RockPaperScissors) {
함수나 메서드 이름에 `and`가 들어간다면 복수의 기능을 제공한다고 생각할 수 있어요. 이런 경우에는 더 분리될 수 있을 여지가 있으니 함수를 분리하는 것을 고려해보는 것도 좋아요.

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let gameResult = gameJudgement(by: choices)
`gameJudgement(by:)` 함수는 `get`을 제외한 형태로 '게임 판단 결과를 얻는다'라는 의미로 이름을 지으신 것 같아요. `judgeGame(by:)`라는 이름은 어떨까요?

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
이 영역은 취향에 따라 유지하셔도 되고, 변경을 고려해보셔도 된다는 것을 먼저 말씀드릴게요.

`startRockPaperScissorsGame()` 함수의 역할이 게임 전반의 진행과 반복문 처리라고 한다면, 승리와 패배를 출력하는 함수는 승패판정 기능을 담당하는 함수로 옮기는 것도 생각해볼 수 있을 것 같아요.

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +/// - Returns: 사용자 숫자
함수의 인터페이스를 읽어보면 `throws` 키워드가 적용되어 있으니 에러를 던질 수 있는 함수라는 점을 유추할 수 있을 것 같아요. 그래서 이 함수를 사용하는 사람 입장에서는 `throws`가 잘못된 입력 오류라는 사실보다 이 함수의 매개변수는 어떤 인자를 받을 수 있고, 어떤 상황에서 에러가 발생하는지에 대한 정보를 더 얻고 싶어 할 것 같아요.

```suggestion
/// 사용자 입력을 받아서 타입을 변환하고 유효성을 검증하여 사용자 숫자를 반환합니다.
/// 아무것도 입력하지 않은 상태로 입력을 확정, 정수로 변환할 수 없는 값을 입력, 유효한 범위 (x...y)의 정수값을 입력하지 않는 경우 에러가 발생합니다. 
/// - Returns: 사용자가 입력한 수를 정수 형태로 반환합니다.
```

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard filteredInput.count == 1, validInputRange ~= filteredInput[0] else {
이번에는 배열의 요소에 접근할 때 `filteredInput[0]`과 같이 subscription을 사용하셨네요. 기존의 `Array.first`와 어떤 점이 달랐나요?

2021-10-15 23:55 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
적용하신 `CustomStringConvertible`의 구현 방식에 대해 추가 코멘트를 남겨두었으니 참고하세요~

2021-10-16 00:00 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }
디스코드로 답변 드린 내용을 그대로 남길게요~

두 가지 방법 모두 적용할 수 있겠네요. 저는 개인적으로 2 번 방식으로 작성해볼 것 같아요. matchResult(with:) 함수의 인터페이스를 통해 매개변수 타입과 반환 타입을 알 수 있기 때문에 굳이 타입 메서드로 구성하지 않아도 된다고 생각해서 결정해봤습니다.

2021-10-16 00:03 UTC, merged